import { useMemo, useRef, useState } from 'react';
import type { StudyMaterialAnnotation, StudyMaterialAnnotationInput, StudyMaterialDetail, StudyMaterialPoint, StudyMaterialRect } from '@shared/types';
import { Icon } from '../ui';
import { t } from '../../i18n';

type EpubTool = 'highlight' | 'underline' | 'brush' | 'sticky' | 'comment';
interface PendingNote { kind: 'sticky' | 'comment'; rect: StudyMaterialRect; from: number | null; to: number | null; selectedText: string }
const PASTELS = ['#fde68a', '#fbcfe8', '#bfdbfe', '#bbf7d0', '#ddd6fe', '#fed7aa'];
const INKS = ['#ef4444', '#2563eb', '#111827', '#0f766e', '#9333ea', '#f97316'];

export function EpubViewer({ material, onAnnotation, onDeleteAnnotation, onCreateNote }: {
  material: StudyMaterialDetail;
  onAnnotation: (input: StudyMaterialAnnotationInput) => Promise<void>;
  onDeleteAnnotation: (id: string) => Promise<void>;
  onCreateNote: (annotationId?: string | null) => Promise<void>;
}) {
  const [tool, setTool] = useState<EpubTool>('highlight');
  const [highlightColor, setHighlightColor] = useState(PASTELS[0]); const [inkColor, setInkColor] = useState(INKS[0]);
  const [thickness, setThickness] = useState(4); const [pending, setPending] = useState<PendingNote | null>(null); const [sidebarDraft, setSidebarDraft] = useState<PendingNote | null>(null); const [note, setNote] = useState(''); const [exporting, setExporting] = useState(false); const [message, setMessage] = useState('');
  const articleRef = useRef<HTMLDivElement>(null); const drawingRef = useRef<StudyMaterialPoint[]>([]); const [draftPath, setDraftPath] = useState<StudyMaterialPoint[]>([]);
  const text = material.extractedText || t('Este EPUB no contiene texto extraíble.');
  const inlineAnnotations = material.annotations.filter((item) => (item.kind === 'highlight' || item.kind === 'underline') && item.from != null && item.to != null).sort((a, b) => (a.from ?? 0) - (b.from ?? 0));
  const segments = useMemo(() => {
    const result: Array<{ text: string; annotation?: StudyMaterialAnnotation }> = []; let cursor = 0;
    for (const annotation of inlineAnnotations) { const from = Math.max(cursor, annotation.from ?? cursor); const to = Math.min(text.length, annotation.to ?? from); if (from > cursor) result.push({ text: text.slice(cursor, from) }); if (to > from) result.push({ text: text.slice(from, to), annotation }); cursor = Math.max(cursor, to); }
    if (cursor < text.length) result.push({ text: text.slice(cursor) }); return result;
  }, [text, material.annotations]);

  const selectionOffsets = () => {
    const selection = window.getSelection(); const root = articleRef.current;
    if (!root || !selection?.rangeCount || !selection.toString().trim() || !root.contains(selection.anchorNode) || !root.contains(selection.focusNode)) return null;
    const range = selection.getRangeAt(0); const before = document.createRange(); before.selectNodeContents(root); before.setEnd(range.startContainer, range.startOffset); const from = before.toString().length; return { from, to: from + range.toString().length, selectedText: range.toString().trim() };
  };
  const captureSelection = () => {
    if (tool === 'brush') return; const selected = selectionOffsets(); if (!selected) return;
    if (tool === 'highlight' || tool === 'underline') void onAnnotation({ ...selected, kind: tool, color: tool === 'highlight' ? highlightColor : inkColor, thickness: 2 }).then(() => window.getSelection()?.removeAllRanges());
    else { const root = articleRef.current!.getBoundingClientRect(); const box = window.getSelection()!.getRangeAt(0).getBoundingClientRect(); const value = { ...selected, kind: tool, rect: { x: Math.max(0, (box.left - root.left) / root.width), y: Math.max(0, (box.top - root.top) / root.height), width: .02, height: .02 } } as PendingNote; if (tool === 'sticky') setPending(value); else setSidebarDraft(value); setNote(''); window.getSelection()?.removeAllRanges(); }
  };
  const saveNote = async (value: PendingNote) => { if (!note.trim()) return; await onAnnotation({ ...value, note, color: value.kind === 'sticky' ? '#fde68a' : '#c7d2fe' }); setNote(''); setPending(null); setSidebarDraft(null); };
  const point = (event: React.PointerEvent<SVGSVGElement>) => { const box = event.currentTarget.getBoundingClientRect(); return { x: (event.clientX - box.left) / box.width, y: (event.clientY - box.top) / box.height }; };
  const interaction = tool === 'brush' || tool === 'sticky' || tool === 'comment'; const colors = tool === 'highlight' ? PASTELS : INKS; const color = tool === 'highlight' ? highlightColor : inkColor;
  const toolButton = (value: EpubTool, icon: string, label: string) => <button data-testid={`study-epub-tool-${value}`} className={`btn h-8 px-2.5 ${tool === value ? 'btn-secondary' : 'btn-ghost'}`} onClick={() => setTool(value)}><Icon name={icon} size={14} /><span className="hidden xl:inline">{t(label)}</span></button>;
  return <div className="flex h-full min-h-0 flex-col" data-testid="study-epub-viewer">
    <div className="flex flex-wrap items-center gap-1.5 border-b border-neutral-200 bg-white px-3 py-2 dark:border-neutral-800 dark:bg-neutral-950"><span className="mr-1 text-xs font-medium text-neutral-600 dark:text-neutral-300">EPUB</span>{toolButton('highlight', 'edit', 'Resaltar')}{toolButton('underline', 'minus', 'Subrayar')}{toolButton('brush', 'palette', 'Pincel')}{toolButton('sticky', 'star', 'Sticker con nota')}{toolButton('comment', 'chat', 'Comentario lateral')}<div className="flex gap-1 rounded-lg border border-neutral-200 px-1.5 py-1 dark:border-neutral-800">{colors.map((item) => <button key={item} aria-label={`${t('Color')} ${item}`} className={`h-5 w-5 rounded-full ${color === item ? 'ring-2 ring-teal-500' : ''}`} style={{ backgroundColor: item }} onClick={() => tool === 'highlight' ? setHighlightColor(item) : setInkColor(item)} />)}</div>{tool === 'brush' && <label className="flex items-center gap-2 text-[10px] text-neutral-500">{t('Grosor')}<input data-testid="study-epub-brush-thickness" type="range" min="1" max="16" value={thickness} onChange={(event) => setThickness(Number(event.target.value))} /><span>{thickness}</span></label>}<button data-testid="study-epub-export-annotated" className="btn btn-primary ml-auto h-8" disabled={exporting} onClick={() => { setExporting(true); setMessage(''); void window.nodus.exportAnnotatedStudyMaterial(material.id).then((result) => { if (result) setMessage(t('Copia anotada guardada')); }).finally(() => setExporting(false)); }}><Icon name="download" size={13} />{exporting ? t('Exportando…') : t('Descargar anotado')}</button></div>
    {message && <p className="border-b border-teal-200 bg-teal-50 px-3 py-1 text-[10px] text-teal-800 dark:border-teal-900 dark:bg-teal-950 dark:text-teal-200">{message}</p>}
    <div className="flex min-h-0 flex-1"><div className="min-w-0 flex-1 overflow-auto bg-stone-100 px-6 py-8 dark:bg-neutral-900/50"><div ref={articleRef} className="relative mx-auto min-h-full max-w-3xl whitespace-pre-wrap rounded-sm bg-white px-12 py-14 font-serif text-[16px] leading-8 text-stone-800 shadow-xl dark:bg-neutral-950 dark:text-neutral-200" onMouseUp={captureSelection}>{segments.map((segment, index) => segment.annotation ? <span key={index} style={segment.annotation.kind === 'highlight' ? { backgroundColor: segment.annotation.color, boxDecorationBreak: 'clone' } : { textDecoration: `underline ${segment.annotation.color} ${segment.annotation.thickness}px`, textUnderlineOffset: '3px' }}>{segment.text}</span> : <span key={index}>{segment.text}</span>)}{material.annotations.filter((item) => item.kind === 'sticky' || item.kind === 'comment').map((item) => item.rect && <span key={item.id} className={`pointer-events-none absolute z-10 grid h-6 w-6 place-items-center rounded shadow ${item.kind === 'sticky' ? 'bg-amber-200 text-amber-900' : 'bg-indigo-200 text-indigo-900'}`} style={{ left: `${item.rect.x * 100}%`, top: `${item.rect.y * 100}%` }}>{item.kind === 'sticky' ? '★' : '💬'}</span>)}<svg className={`absolute inset-0 z-20 h-full w-full ${interaction ? tool === 'brush' ? 'cursor-crosshair' : 'cursor-copy' : 'pointer-events-none'}`} viewBox="0 0 1000 1000" preserveAspectRatio="none" onPointerDown={(event) => { if (tool === 'brush') { event.currentTarget.setPointerCapture(event.pointerId); drawingRef.current = [point(event)]; setDraftPath(drawingRef.current); } }} onPointerMove={(event) => { if (tool === 'brush' && event.currentTarget.hasPointerCapture(event.pointerId)) { drawingRef.current = [...drawingRef.current, point(event)]; setDraftPath(drawingRef.current); } }} onPointerUp={(event) => { if (tool === 'brush' && drawingRef.current.length > 1) { void onAnnotation({ kind: 'brush', path: drawingRef.current, color: inkColor, thickness }); drawingRef.current = []; setDraftPath([]); } else if (tool === 'sticky' || tool === 'comment') { const p = point(event); const value = { kind: tool, rect: { x: p.x, y: p.y, width: .02, height: .02 }, from: null, to: null, selectedText: '' } as PendingNote; if (tool === 'sticky') setPending(value); else setSidebarDraft(value); setNote(''); } }}>{material.annotations.filter((item) => item.kind === 'brush').map((item) => <polyline key={item.id} points={item.path.map((p) => `${p.x * 1000},${p.y * 1000}`).join(' ')} fill="none" stroke={item.color} strokeWidth={item.thickness * 1.7} strokeLinecap="round" strokeLinejoin="round" opacity=".82" />)}<polyline points={draftPath.map((p) => `${p.x * 1000},${p.y * 1000}`).join(' ')} fill="none" stroke={inkColor} strokeWidth={thickness * 1.7} strokeLinecap="round" strokeLinejoin="round" /></svg></div></div>
      <aside className="w-80 shrink-0 overflow-y-auto border-l border-neutral-200 bg-white p-3 dark:border-neutral-800 dark:bg-neutral-950" data-testid="study-epub-annotations-sidebar"><h3 className="mb-2 text-[10px] font-semibold uppercase tracking-wide text-neutral-500">{t('Comentarios y anotaciones')}</h3>{sidebarDraft && <div className="mb-3 rounded-xl border border-indigo-200 bg-indigo-50 p-3 dark:border-indigo-900 dark:bg-indigo-950/30"><p className="text-xs font-medium">{t('Nuevo comentario lateral')}</p>{sidebarDraft.selectedText && <p className="mt-1 line-clamp-3 text-xs italic text-neutral-500">“{sidebarDraft.selectedText}”</p>}<textarea autoFocus className="input mt-2 min-h-20 w-full" value={note} onChange={(event) => setNote(event.target.value)} placeholder={t('Escribe el comentario')} /><div className="mt-2 flex justify-end gap-2"><button className="btn btn-ghost" onClick={() => setSidebarDraft(null)}>{t('Cancelar')}</button><button className="btn btn-primary" disabled={!note.trim()} onClick={() => void saveNote(sidebarDraft)}>{t('Guardar')}</button></div></div>}{material.annotations.map((item) => <EpubAnnotationCard key={item.id} annotation={item} onCreateNote={() => onCreateNote(item.id)} onDelete={() => onDeleteAnnotation(item.id)} />)}</aside></div>
    {pending && <div className="absolute inset-0 z-50 grid place-items-center bg-black/40 p-6" onClick={() => setPending(null)}><section className="card-modal w-full max-w-sm p-4" onClick={(event) => event.stopPropagation()} data-testid="study-epub-sticky-dialog"><h3 className="font-semibold">★ {t('Sticker con nota')}</h3>{pending.selectedText && <p className="mt-2 line-clamp-3 text-xs italic text-neutral-500">“{pending.selectedText}”</p>}<textarea autoFocus className="input mt-3 min-h-28 w-full" value={note} onChange={(event) => setNote(event.target.value)} placeholder={t('Escribe una nota')} /><div className="mt-3 flex justify-end gap-2"><button className="btn btn-ghost" onClick={() => setPending(null)}>{t('Cancelar')}</button><button className="btn btn-primary" disabled={!note.trim()} onClick={() => void saveNote(pending)}>{t('Guardar sticker')}</button></div></section></div>}
  </div>;
}

function EpubAnnotationCard({ annotation, onCreateNote, onDelete }: { annotation: StudyMaterialAnnotation; onCreateNote: () => Promise<void>; onDelete: () => Promise<void> }) {
  const label = annotation.kind === 'highlight' ? t('Resaltado') : annotation.kind === 'underline' ? t('Subrayado') : annotation.kind === 'brush' ? t('Pincel') : annotation.kind === 'sticky' ? t('Sticker') : t('Comentario');
  return <article className="mb-2 rounded-lg border border-neutral-200 p-2.5 dark:border-neutral-800"><span className="flex items-center gap-2 text-[10px] text-neutral-500"><i className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: annotation.color }} />{label}</span>{annotation.selectedText && <p className="mt-1 line-clamp-3 text-xs italic text-neutral-500">“{annotation.selectedText}”</p>}{annotation.note && <p className="mt-1 text-xs text-neutral-700 dark:text-neutral-300">{annotation.note}</p>}<div className="mt-2 flex text-[10px]"><button className="text-teal-600" onClick={() => void onCreateNote()}>{t('Crear apunte')}</button><button className="ml-auto text-red-600" onClick={() => void onDelete()}>{t('Eliminar')}</button></div></article>;
}
