import type { CompassProviderAdapter, CompassProviderId } from '@shared/compass';
import { adapter, author, identifier, page, queryString, requestJson, requestText, result, text } from './provider';
function authors(values: unknown[]): Array<NonNullable<ReturnType<typeof author>>> { return values.map(author).filter((entry): entry is NonNullable<ReturnType<typeof author>> => !!entry); }

function semanticScholar(apiKey?: string): CompassProviderAdapter { return adapter('semanticscholar', 'Semantic Scholar Academic Graph API (provider terms apply)', async (c) => { const u = new URL('https://api.semanticscholar.org/graph/v1/paper/search'); u.searchParams.set('query', queryString(c.query).replaceAll('-', ' ')); u.searchParams.set('limit', '25'); u.searchParams.set('offset', c.cursor ?? '0'); u.searchParams.set('fields', 'paperId,title,abstract,year,publicationDate,authors,url,venue,publicationTypes,externalIds,citationCount,openAccessPdf,fieldsOfStudy'); const fromYear = c.filters.fromYear ?? c.query.fromYear; const toYear = c.filters.toYear ?? c.query.toYear; if (fromYear || toYear) u.searchParams.set('publicationDateOrYear', `${fromYear ?? ''}:${toYear ?? ''}`); if (c.filters.openAccessOnly || c.query.openAccessOnly) u.searchParams.set('openAccessPdf', ''); const headers = apiKey ? { 'x-api-key': apiKey } : undefined; const { data } = await requestJson(u.toString(), c.signal, { headers }); const records = (Array.isArray(data?.data) ? data.data : []).map((x: any) => { const value = result({ provider: 'semanticscholar', providerId: x.paperId, title: x.title, abstract: x.abstract, authors: authors(Array.isArray(x.authors) ? x.authors : []), year: Number(x.year) || undefined, url: x.url, doi: x.externalIds?.DOI, ids: [identifier('arxiv', x.externalIds?.ArXiv), identifier('pmid', x.externalIds?.PubMed), identifier('corpusid', x.externalIds?.CorpusId)].filter(Boolean) as any[], language: undefined, venue: x.venue, citationCount: Number.isFinite(x.citationCount) ? x.citationCount : undefined, type: Array.isArray(x.publicationTypes) && x.publicationTypes.includes('Book') ? 'book' : Array.isArray(x.publicationTypes) && x.publicationTypes.includes('BookSection') ? 'chapter' : Array.isArray(x.publicationTypes) && x.publicationTypes.includes('Dataset') ? 'dataset' : 'article' }); value.disciplines = Array.isArray(x.fieldsOfStudy) ? x.fieldsOfStudy.map((entry: unknown) => text(entry, 120)).filter(Boolean) : []; if (x.openAccessPdf?.url) value.openAccess = { status: 'green', url: x.openAccessPdf.url, provider: 'semanticscholar', verifiedAt: new Date().toISOString() }; return value; }); return page(records, 'semanticscholar', data?.next == null ? undefined : String(data.next), 'Semantic Scholar'); }); }

function dspaceMetadata(item: any, key: string): string[] { return (Array.isArray(item?.metadata) ? item.metadata : []).filter((entry: any) => entry?.key === key || entry?.key?.startsWith(`${key}.`)).map((entry: any) => text(entry?.value, 4_000)).filter(Boolean); }
function dspaceBooks(provider: 'doab' | 'oapen', endpoint: string): CompassProviderAdapter { return adapter(provider, `${provider === 'doab' ? 'DOAB' : 'OAPEN'} metadata (CC0)`, async (c) => { const u = new URL(endpoint); u.searchParams.set('query', queryString(c.query)); u.searchParams.set('expand', 'metadata'); u.searchParams.set('limit', '25'); u.searchParams.set('offset', c.cursor ?? '0'); const { data, response } = await requestJson(u.toString(), c.signal); const items = Array.isArray(data) ? data : Array.isArray(data?.items) ? data.items : []; const records = items.map((x: any) => { const creators = authors([...dspaceMetadata(x, 'dc.contributor.author'), ...dspaceMetadata(x, 'dc.creator')]); const identifiers = dspaceMetadata(x, 'dc.identifier'); const doi = identifiers.find((value) => /10\.\d{4,9}\//i.test(value))?.replace(/^https?:\/\/(?:dx\.)?doi\.org\//i, ''); const isbn = identifiers.find((value) => /(?:97[89][ -]?)?\d[\d -]{8,16}\d/.test(value)); const url = dspaceMetadata(x, 'dc.identifier.uri')[0] ?? (x.handle ? `https://${provider === 'doab' ? 'directory.doabooks.org' : 'library.oapen.org'}/handle/${x.handle}` : undefined); const value = result({ provider, providerId: x.handle ?? x.uuid ?? url ?? x.name, title: dspaceMetadata(x, 'dc.title')[0] ?? x.name, abstract: dspaceMetadata(x, 'dc.description.abstract')[0] ?? dspaceMetadata(x, 'dc.description')[0], authors: creators, year: Number((dspaceMetadata(x, 'dc.date.issued')[0] ?? '').slice(0, 4)) || undefined, url, doi, ids: [identifier('isbn', isbn)].filter(Boolean) as any[], language: dspaceMetadata(x, 'dc.language')[0], type: 'book' }); value.publisher = dspaceMetadata(x, 'dc.publisher')[0]; value.topics = dspaceMetadata(x, 'dc.subject').slice(0, 20); value.openAccess = { status: 'gold', url, provider, verifiedAt: new Date().toISOString() }; return value; }); const total = Number(response.headers.get('x-total-count') ?? data?.totalElements ?? data?.total ?? 0); const offset = Number(c.cursor ?? 0); const next = records.length === 25 && (!total || offset + records.length < total) ? String(offset + records.length) : undefined; return page(records, provider, next, provider === 'doab' ? 'Directory of Open Access Books' : 'OAPEN Library'); }); }

function decodeXml(value: string): string { return value.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, '$1').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&amp;/g, '&').replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim(); }
function xmlValues(block: string, localName: string): string[] { const expression = new RegExp(`<(?:[\\w.-]+:)?${localName}\\b[^>]*>([\\s\\S]*?)<\\/(?:[\\w.-]+:)?${localName}>`, 'gi'); return [...block.matchAll(expression)].map((match) => decodeXml(match[1])).filter(Boolean); }
function queryMatches(resultText: string, query: string): boolean { const terms = query.toLocaleLowerCase().split(/[^\p{L}\p{N}]+/u).filter((term) => term.length > 2).slice(0, 12); const haystack = resultText.toLocaleLowerCase(); return !terms.length || terms.some((term) => haystack.includes(term)); }
function oaiProvider(provider: 'dialnet' | 'openedition' | 'scielo', endpoint: string, attribution: string): CompassProviderAdapter { return adapter(provider, attribution, async (c) => { const u = new URL(endpoint); if (c.cursor) { u.searchParams.set('verb', 'ListRecords'); u.searchParams.set('resumptionToken', c.cursor); } else { u.searchParams.set('verb', 'ListRecords'); u.searchParams.set('metadataPrefix', 'oai_dc'); } const { data } = await requestText(u.toString(), c.signal); const blocks = [...data.matchAll(/<record\b[^>]*>([\s\S]*?)<\/record>/gi)].map((match) => match[1]).slice(0, 100); const records = blocks.map((block) => { const title = xmlValues(block, 'title')[0]; const creators = authors(xmlValues(block, 'creator')); const descriptions = xmlValues(block, 'description'); const identifiers = xmlValues(block, 'identifier'); const doi = identifiers.find((value) => /(?:doi\.org\/|^doi:|^10\.\d{4,9}\/)/i.test(value))?.replace(/^doi:\s*/i, '').replace(/^https?:\/\/(?:dx\.)?doi\.org\//i, ''); const isbn = identifiers.find((value) => /(?:ISBN[:\s]*)?(?:97[89][ -]?)?\d[\d -]{8,16}\d/i.test(value)); const date = xmlValues(block, 'date')[0]; const typeValue = xmlValues(block, 'type').join(' ').toLowerCase(); const url = identifiers.find((value) => /^https?:\/\//i.test(value)); const value = result({ provider, providerId: xmlValues(block, 'identifier')[0] ?? title, title, abstract: descriptions[0], authors: creators, year: Number(date?.match(/\b\d{4}\b/)?.[0]) || undefined, url, doi, ids: [identifier('isbn', isbn)].filter(Boolean) as any[], language: xmlValues(block, 'language')[0], type: /thesis|tesis/.test(typeValue) ? 'thesis' : /book|libro|livro/.test(typeValue) ? 'book' : /chapter|cap[ií]tulo/.test(typeValue) ? 'chapter' : 'article' }); value.topics = xmlValues(block, 'subject').slice(0, 20); if (provider === 'scielo') value.openAccess = { status: 'gold', url, provider, verifiedAt: new Date().toISOString() }; return value; }).filter((entry) => entry.title !== 'Untitled work' && queryMatches(`${entry.title} ${entry.abstract ?? ''} ${entry.topics.join(' ')}`, queryString(c.query))); const token = xmlValues(data, 'resumptionToken')[0] || undefined; return page(records, provider, token, attribution); }); }

function openAlex(apiKey?: string): CompassProviderAdapter { return adapter('openalex', 'OpenAlex (CC BY 4.0 metadata)', async (c) => { const u = new URL('https://api.openalex.org/works'); u.searchParams.set('search', queryString(c.query)); u.searchParams.set('per-page', '25'); u.searchParams.set('cursor', c.cursor ?? '*'); const fromYear = c.filters.fromYear ?? c.query.fromYear; const toYear = c.filters.toYear ?? c.query.toYear; const dateFilters = [fromYear ? `from_publication_date:${fromYear}-01-01` : '', toYear ? `to_publication_date:${toYear}-12-31` : ''].filter(Boolean); if (dateFilters.length) u.searchParams.set('filter', dateFilters.join(',')); if (apiKey) u.searchParams.set('api_key', apiKey); const { data } = await requestJson(u.toString(), c.signal); const records = (Array.isArray(data?.results) ? data.results : []).map((x: any) => result({ provider: 'openalex', providerId: x.id ?? x.openalex_id ?? '', title: x.title, abstract: x.abstract_inverted_index ? Object.entries(x.abstract_inverted_index).flatMap(([w, p]) => Array.isArray(p) ? (p as number[]).map((i) => [i, w] as [number, string]) : []).sort((a, b) => a[0] - b[0]).map((x) => x[1]).join(' ') : x.abstract_inverted_index, authors: Array.isArray(x.authorships) ? x.authorships.map((a: any) => author(a.author)).filter(Boolean) : [], year: x.publication_year, url: x.primary_location?.landing_page_url ?? x.id, doi: text(x.doi).replace(/^https?:\/\/doi.org\//i, '') || undefined, ids: [identifier('pmid', x.ids?.pmid), identifier('pmcid', x.ids?.pmcid)].filter(Boolean) as any[], language: x.language, venue: x.primary_location?.source?.display_name, citationCount: Number.isFinite(x.cited_by_count) ? x.cited_by_count : undefined })); return page(records, 'openalex', data?.meta?.next_cursor ?? undefined, 'OpenAlex'); }); }

function crossref(): CompassProviderAdapter { return adapter('crossref', 'Crossref metadata (CC0)', async (c) => { const u = new URL('https://api.crossref.org/works'); u.searchParams.set('query.bibliographic', queryString(c.query)); u.searchParams.set('rows', '20'); u.searchParams.set('cursor', c.cursor ?? '*'); const fromYear = c.filters.fromYear ?? c.query.fromYear; const toYear = c.filters.toYear ?? c.query.toYear; const filters = [fromYear ? `from-pub-date:${fromYear}-01-01` : '', toYear ? `until-pub-date:${toYear}-12-31` : ''].filter(Boolean); if (filters.length) u.searchParams.set('filter', filters.join(',')); if (c.email) u.searchParams.set('mailto', c.email); const { data } = await requestJson(u.toString(), c.signal); const records = (Array.isArray(data?.message?.items) ? data.message.items : []).map((x: any) => result({ provider: 'crossref', providerId: x.DOI ?? x.URL ?? '', title: Array.isArray(x.title) ? x.title[0] : x.title, authors: Array.isArray(x.author) ? x.author.map(author).filter(Boolean) : [], year: Number((x.published?.['date-parts']?.[0] ?? [])[0]) || undefined, url: x.URL, doi: x.DOI, ids: [identifier('issn', x.ISSN?.[0])].filter(Boolean) as any[], venue: Array.isArray(x['container-title']) ? x['container-title'][0] : x['container-title'], type: x.type === 'journal-article' ? 'article' : x.type === 'book' ? 'book' : 'other' })); return page(records, 'crossref', data?.message?.['next-cursor'] ?? undefined, 'Crossref'); }); }

function openAire(): CompassProviderAdapter { return adapter('openaire', 'OpenAIRE metadata (CC BY)', async (c) => { const u = new URL('https://api.openaire.eu/search/publications'); u.searchParams.set('keywords', queryString(c.query)); u.searchParams.set('size', '25'); const fromYear = c.filters.fromYear ?? c.query.fromYear; const toYear = c.filters.toYear ?? c.query.toYear; if (fromYear) u.searchParams.set('fromDateAccepted', `${fromYear}-01-01`); if (toYear) u.searchParams.set('toDateAccepted', `${toYear}-12-31`); if (c.cursor) u.searchParams.set('cursor', c.cursor); const { data } = await requestJson(u.toString(), c.signal); const items = data?.response?.results?.result ?? data?.results ?? []; const records = (Array.isArray(items) ? items : []).map((x: any) => { const e = x.metadata?.oaf_entity?.oaf_result ?? x.metadata?.entity?.result ?? x; return result({ provider: 'openaire', providerId: e.id ?? x.id ?? '', title: e.title?.['$'] ?? e.title ?? x.title, authors: Array.isArray(e.creator) ? e.creator.map(author).filter(Boolean) : [], year: Number(e.dateofacceptance ?? e.year) || undefined, url: e.url?.['$'] ?? e.url, doi: e.pid?.['$'] ?? e.doi, abstract: e.description?.['$'] ?? e.description }); }); return page(records, 'openaire', data?.response?.nextCursor ?? data?.nextCursor, 'OpenAIRE'); }); }

function hal(): CompassProviderAdapter { return adapter('hal', 'HAL Open Archives (metadata reuse subject to HAL terms)', async (c) => { const u = new URL('https://api.archives-ouvertes.fr/search/'); u.searchParams.set('q', queryString(c.query)); u.searchParams.set('rows', '30'); u.searchParams.set('wt', 'json'); u.searchParams.set('fl', 'docid,title_s,authFullName_s,producedDateY_i,uri_s,doiId_s,abstract_s,language_s'); const fromYear = c.filters.fromYear ?? c.query.fromYear; const toYear = c.filters.toYear ?? c.query.toYear; if (fromYear || toYear) u.searchParams.set('fq', `producedDateY_i:[${fromYear ?? '*'} TO ${toYear ?? '*'}]`); u.searchParams.set('cursorMark', c.cursor ?? '*'); const { data } = await requestJson(u.toString(), c.signal); const records = (Array.isArray(data?.response?.docs) ? data.response.docs : []).map((x: any) => result({ provider: 'hal', providerId: x.docid, title: Array.isArray(x.title_s) ? x.title_s[0] : x.title_s, authors: (Array.isArray(x.authFullName_s) ? x.authFullName_s : [x.authFullName_s]).filter(Boolean).map(author).filter(Boolean), year: x.producedDateY_i, url: Array.isArray(x.uri_s) ? x.uri_s[0] : x.uri_s, doi: Array.isArray(x.doiId_s) ? x.doiId_s[0] : x.doiId_s, abstract: Array.isArray(x.abstract_s) ? x.abstract_s[0] : x.abstract_s, language: Array.isArray(x.language_s) ? x.language_s[0] : x.language_s })); return page(records, 'hal', data?.response?.nextCursor ?? undefined, 'HAL'); }); }

function unpaywall(): CompassProviderAdapter { return adapter('unpaywall', 'Unpaywall (API data subject to Unpaywall terms)', async (c) => { const doi = c.query.identifiers.find((x) => x.scheme === 'doi')?.value; if (!doi) return page([], 'unpaywall', undefined, 'Unpaywall'); const u = new URL(`https://api.unpaywall.org/v2/${encodeURIComponent(doi)}`); u.searchParams.set('email', c.email || ''); const { data } = await requestJson(u.toString(), c.signal); const r = result({ provider: 'unpaywall', providerId: data?.doi ?? doi, title: data?.title, year: Number(data?.year) || undefined, url: data?.doi_url ?? data?.best_oa_location?.url_for_landing_page, doi: data?.doi ?? doi }); if (data?.best_oa_location?.url_for_pdf) r.openAccess = { status: data.is_oa ? 'gold' : 'closed', url: data.best_oa_location.url_for_pdf, license: data.best_oa_location.license, provider: 'unpaywall', verifiedAt: new Date().toISOString() }; return page([r], 'unpaywall', undefined, 'Unpaywall'); }); }

function openCitations(): CompassProviderAdapter { return adapter('opencitations', 'OpenCitations (CC BY 4.0)', async (c) => { const doi = c.query.identifiers.find((x) => x.scheme === 'doi')?.value; if (!doi) return page([], 'opencitations', undefined, 'OpenCitations'); const u = `https://api.opencitations.net/index/v2/metadata/${encodeURIComponent(doi)}`; const { data } = await requestJson(u, c.signal); const x = Array.isArray(data) ? data[0] : data; const r = result({ provider: 'opencitations', providerId: doi, title: x?.title, authors: Array.isArray(x?.author) ? x.author.map(author).filter(Boolean) : [], year: Number(x?.pub_date?.slice(0, 4)) || undefined, doi }); r.citationCount = Number(x?.citation_count) || undefined; return page([r], 'opencitations', undefined, 'OpenCitations'); }); }

export function createCompassAdapters(config: Partial<Record<CompassProviderId, { apiKey?: string; email?: string }>> = {}): Map<CompassProviderId, CompassProviderAdapter> {
  const out = new Map<CompassProviderId, CompassProviderAdapter>();
  out.set('openalex', openAlex(config.openalex?.apiKey)); out.set('crossref', crossref()); out.set('openaire', openAire()); out.set('hal', hal());
  out.set('unpaywall', unpaywall()); out.set('opencitations', openCitations()); out.set('semanticscholar', semanticScholar(config.semanticscholar?.apiKey));
  out.set('doab', dspaceBooks('doab', 'https://directory.doabooks.org/rest/search'));
  out.set('oapen', dspaceBooks('oapen', 'https://library.oapen.org/rest/search'));
  out.set('dialnet', oaiProvider('dialnet', 'https://dialnet.unirioja.es/oai/OAIHandler', 'Dialnet OAI-PMH'));
  out.set('openedition', oaiProvider('openedition', 'https://oai.openedition.org/', 'OpenEdition OAI-PMH'));
  out.set('scielo', oaiProvider('scielo', 'https://oaipmh.scielo.org/br/', 'SciELO OAI-PMH'));
  return out;
}
