import type { CompassProviderAdapter, CompassProviderId } from '@shared/compass';
import { providerDescriptor } from './catalog';
import { adapter, author, downloadLink, identifier, page, queryFor, requestJson, requestText, result, text, xmlValues } from './provider';

const authors = (values: unknown[]) => values.map(author).filter((entry): entry is NonNullable<ReturnType<typeof author>> => Boolean(entry));
const yearOf = (value: unknown) => Number(text(value).match(/\b(?:1[0-9]{3}|20\d{2})\b/)?.[0]) || undefined;
const dspace = (item: any, key: string): string[] => (Array.isArray(item?.metadata) ? item.metadata : []).filter((entry: any) => entry?.key === key || entry?.key?.startsWith(`${key}.`)).map((entry: any) => text(entry?.value, 8_000)).filter(Boolean);

function openLibrary(): CompassProviderAdapter { return adapter(providerDescriptor('openlibrary'), async (context) => {
  const isbn = context.query.identifiers.find((entry) => entry.scheme === 'isbn')?.value; const pageNumber = Math.max(1, Number(context.cursor ?? 1));
  const url = new URL('https://openlibrary.org/search.json'); if (isbn) url.searchParams.set('isbn', isbn); else url.searchParams.set('q', queryFor(context)); url.searchParams.set('limit', '25'); url.searchParams.set('page', String(pageNumber));
  url.searchParams.set('fields', 'key,title,subtitle,author_name,first_publish_year,publish_year,isbn,language,subject,publisher,edition_key,public_scan_b,ia,ebook_access');
  const { data } = await requestJson(url.toString(), context.signal); const records = (Array.isArray(data?.docs) ? data.docs : []).map((book: any) => { const ia = book?.ia?.[0]; const pdf = ia && book?.public_scan_b ? downloadLink('openlibrary', `https://archive.org/download/${encodeURIComponent(ia)}/${encodeURIComponent(ia)}_text.pdf`, { mediaType: 'application/pdf' }) : null; const value = result({ provider: 'openlibrary', providerId: book?.key, title: book?.title, authors: authors(book?.author_name ?? []), year: Number(book?.first_publish_year) || undefined, url: book?.key ? `https://openlibrary.org${book.key}` : undefined, ids: (book?.isbn ?? []).slice(0, 20).map((entry: unknown) => identifier('isbn', entry)).filter(Boolean), language: book?.language?.[0], type: 'book', downloads: pdf ? [pdf] : [] }); value.subtitle = text(book?.subtitle, 1_000) || undefined; value.publisher = text(book?.publisher?.[0], 400) || undefined; value.topics = (book?.subject ?? []).slice(0, 20).map((entry: unknown) => text(entry, 120)); if (pdf) value.openAccess = { status: 'green', url: pdf.url, provider: 'openlibrary', verifiedAt: pdf.verifiedAt }; return value; });
  return page(records, 'openlibrary', pageNumber * 25 < Number(data?.numFound ?? 0) ? String(pageNumber + 1) : undefined, 'Open Library');
}); }

function dspaceBook(provider: 'doab' | 'oapen', endpoint: string): CompassProviderAdapter { return adapter(providerDescriptor(provider), async (context) => {
  const offset = Math.max(0, Number(context.cursor ?? 0)); const url = new URL(endpoint); url.searchParams.set('query', queryFor(context)); url.searchParams.set('expand', 'metadata,bitstreams'); url.searchParams.set('limit', '25'); url.searchParams.set('offset', String(offset));
  const { data, response } = await requestJson(url.toString(), context.signal); const items = Array.isArray(data) ? data : Array.isArray(data?.items) ? data.items : [];
  const records = items.map((item: any) => { const ids = dspace(item, 'dc.identifier'); const doi = ids.find((value) => /10\.\d{4,9}\//i.test(value))?.replace(/^https?:\/\/(?:dx\.)?doi\.org\//i, ''); const isbn = ids.filter((value) => /(?:97[89][ -]?)?\d[\d -]{8,16}[\dX]/i.test(value)); const landing = dspace(item, 'dc.identifier.uri')[0] ?? (item?.handle ? `https://${provider === 'doab' ? 'directory.doabooks.org' : 'library.oapen.org'}/handle/${item.handle}` : undefined); const bitstreams = Array.isArray(item?.bitstreams) ? item.bitstreams : []; const openFiles = bitstreams.map((bitstream: any) => downloadLink(provider, bitstream?.retrieveLink ? new URL(bitstream.retrieveLink, endpoint).toString() : bitstream?.url, { mediaType: bitstream?.mimeType, format: bitstream?.format, license: dspace(item, 'dc.rights')[0] })).filter(Boolean) as NonNullable<ReturnType<typeof downloadLink>>[]; const value = result({ provider, providerId: item?.handle ?? item?.uuid ?? landing, title: dspace(item, 'dc.title')[0] ?? item?.name, abstract: dspace(item, 'dc.description.abstract')[0] ?? dspace(item, 'dc.description')[0], authors: authors([...dspace(item, 'dc.contributor.author'), ...dspace(item, 'dc.creator')]), year: yearOf(dspace(item, 'dc.date.issued')[0]), issuedDate: dspace(item, 'dc.date.issued')[0], url: landing, doi, ids: isbn.map((entry) => identifier('isbn', entry)).filter(Boolean) as any, language: dspace(item, 'dc.language')[0], type: /chapter/i.test(dspace(item, 'dc.type')[0] ?? '') ? 'chapter' : 'book', rights: dspace(item, 'dc.rights')[0], downloads: openFiles }); value.publisher = dspace(item, 'dc.publisher')[0]; value.topics = dspace(item, 'dc.subject').slice(0, 20); value.openAccess = { status: 'gold', url: openFiles[0]?.url ?? landing, license: dspace(item, 'dc.rights')[0], provider, verifiedAt: new Date().toISOString() }; return value; });
  const total = Number(response.headers.get('x-total-count') ?? data?.totalElements ?? data?.total ?? 0); return page(records, provider, records.length === 25 && (!total || offset + 25 < total) ? String(offset + 25) : undefined, provider.toUpperCase());
}); }

function cql(context: Parameters<CompassProviderAdapter['search']>[0]): string {
  const isbn = context.query.identifiers.find((entry) => entry.scheme === 'isbn')?.value; if (isbn) return `bib.isbn all "${isbn.replaceAll('"', '')}"`;
  const clauses = [`bib.anywhere all "${queryFor(context).replaceAll('"', ' ')}"`]; if (context.query.authors[0]) clauses.push(`bib.author all "${context.query.authors[0].replaceAll('"', '')}"`); return clauses.join(' and ');
}
function bnf(): CompassProviderAdapter { return adapter(providerDescriptor('bnf'), async (context) => {
  const start = Math.max(1, Number(context.cursor ?? 1)); const url = new URL('https://catalogue.bnf.fr/api/SRU'); url.searchParams.set('version', '1.2'); url.searchParams.set('operation', 'searchRetrieve'); url.searchParams.set('query', cql(context)); url.searchParams.set('recordSchema', 'dublincore'); url.searchParams.set('maximumRecords', '25'); url.searchParams.set('startRecord', String(start));
  const { data } = await requestText(url.toString(), context.signal); const blocks = [...data.matchAll(/<(?:\w+:)?recordData\b[^>]*>([\s\S]*?)<\/(?:\w+:)?recordData>/gi)].map((match) => match[1]); const records = blocks.map((block) => { const ids = xmlValues(block, 'identifier'); const ark = ids.find((entry) => /ark:\/12148\//i.test(entry)); const landing = ark ? `https://catalogue.bnf.fr/${ark.replace(/^.*?(ark:\/12148\/)/i, '$1')}` : ids.find((entry) => /^https?:/i.test(entry)); const typeValue = xmlValues(block, 'type').join(' '); const value = result({ provider: 'bnf', providerId: ark ?? ids[0] ?? xmlValues(block, 'title')[0], title: xmlValues(block, 'title')[0], abstract: xmlValues(block, 'description')[0], authors: authors(xmlValues(block, 'creator')), year: yearOf(xmlValues(block, 'date')[0]), issuedDate: xmlValues(block, 'date')[0], url: landing, ids: ids.flatMap((entry) => { const isbn = entry.match(/(?:97[89][ -]?)?\d[\d -]{8,16}[\dX]/i)?.[0]; return isbn ? [identifier('isbn', isbn)!] : []; }), language: xmlValues(block, 'language')[0], type: /thesis|thèse/i.test(typeValue) ? 'thesis' : /chapter/i.test(typeValue) ? 'chapter' : /book|livre|text/i.test(typeValue) ? 'book' : 'other', rights: xmlValues(block, 'rights')[0] }); value.publisher = xmlValues(block, 'publisher')[0]; value.topics = xmlValues(block, 'subject').slice(0, 20); return value; }); const total = Number(xmlValues(data, 'numberOfRecords')[0] ?? 0); return page(records, 'bnf', start + records.length <= total ? String(start + records.length) : undefined, 'Bibliothèque nationale de France');
}); }

export function bookAdapters(): Array<[CompassProviderId, CompassProviderAdapter]> { const list = [openLibrary(), dspaceBook('doab', 'https://directory.doabooks.org/rest/search'), dspaceBook('oapen', 'https://library.oapen.org/rest/search'), bnf()]; return list.map((entry) => [entry.id, entry]); }
