import type { CompassProviderAdapter, CompassProviderId } from '@shared/compass';
import { providerDescriptor } from './catalog';
import { adapter, author, downloadLink, identifier, page, queryFor, requestJson, requestText, result, text, xmlValues } from './provider';

const authors = (values: unknown[]) => values.map(author).filter((entry): entry is NonNullable<ReturnType<typeof author>> => Boolean(entry));

function europePmc(): CompassProviderAdapter { return adapter(providerDescriptor('europepmc'), async (context) => {
  const pageNumber = Math.max(1, Number(context.cursor ?? 1)); const id = context.query.identifiers.find((entry) => entry.scheme === 'pmid' || entry.scheme === 'pmcid'); const url = new URL('https://www.ebi.ac.uk/europepmc/webservices/rest/search'); let query = id ? `${id.scheme.toUpperCase()}:${id.value}` : queryFor(context); if (context.query.openAccessOnly) query += ' AND OPEN_ACCESS:Y'; if (context.query.fromYear || context.query.toYear) query += ` AND FIRST_PDATE:[${context.query.fromYear ?? 1800}-01-01 TO ${context.query.toYear ?? new Date().getFullYear()}-12-31]`; url.searchParams.set('query', query); url.searchParams.set('format', 'json'); url.searchParams.set('pageSize', '25'); url.searchParams.set('page', String(pageNumber));
  const { data } = await requestJson(url.toString(), context.signal); const records = (data?.resultList?.result ?? []).map((work: any) => { const pmcid = work?.pmcid; const pdf = pmcid && work?.isOpenAccess === 'Y' ? downloadLink('europepmc', `https://www.ebi.ac.uk/europepmc/webservices/rest/${pmcid}/fullTextPDF`, { mediaType: 'application/pdf' }) : null; const value = result({ provider: 'europepmc', providerId: work?.id ?? work?.pmid ?? pmcid, title: work?.title, authors: authors((work?.authorList?.author ?? []).map((entry: any) => ({ name: entry?.fullName, given: entry?.firstName, family: entry?.lastName }))), year: Number(work?.pubYear) || undefined, issuedDate: work?.firstPublicationDate, url: pmcid ? `https://europepmc.org/article/MED/${work?.pmid ?? pmcid}` : work?.doi ? `https://doi.org/${work.doi}` : undefined, doi: work?.doi, ids: [identifier('pmid', work?.pmid), identifier('pmcid', pmcid)].filter(Boolean) as any, venue: work?.journalTitle, citationCount: Number(work?.citedByCount) || undefined, type: work?.source === 'PPR' ? 'preprint' : 'article', downloads: pdf ? [pdf] : [] }); if (work?.isOpenAccess === 'Y') value.openAccess = { status: 'green', url: pdf?.url ?? value.landingUrl, provider: 'europepmc', verifiedAt: new Date().toISOString() }; return value; }); const total = Number(data?.hitCount ?? 0); return page(records, 'europepmc', pageNumber * 25 < total ? String(pageNumber + 1) : undefined, 'Europe PMC');
}); }

function arxiv(): CompassProviderAdapter { return adapter(providerDescriptor('arxiv'), async (context) => {
  const offset = Math.max(0, Number(context.cursor ?? 0)); const id = context.query.identifiers.find((entry) => entry.scheme === 'arxiv')?.value; const url = new URL('https://export.arxiv.org/api/query'); url.searchParams.set('search_query', id ? `id:${id}` : `all:${queryFor(context).replaceAll('"', '')}`); url.searchParams.set('start', String(offset)); url.searchParams.set('max_results', '25'); url.searchParams.set('sortBy', 'relevance');
  const { data } = await requestText(url.toString(), context.signal); const entries = [...data.matchAll(/<entry\b[^>]*>([\s\S]*?)<\/entry>/gi)].map((match) => match[1]); const records = entries.map((entry) => { const arxivId = xmlValues(entry, 'id')[0]?.split('/abs/')[1]; const pdfUrl = [...entry.matchAll(/<link\b([^>]+)>/gi)].map((match) => match[1]).find((attrs) => /type=["']application\/pdf/i.test(attrs))?.match(/href=["']([^"']+)/i)?.[1] ?? (arxivId ? `https://arxiv.org/pdf/${arxivId}` : undefined); const pdf = downloadLink('arxiv', pdfUrl, { mediaType: 'application/pdf' }); const value = result({ provider: 'arxiv', providerId: arxivId, title: xmlValues(entry, 'title')[0], abstract: xmlValues(entry, 'summary')[0], authors: [...entry.matchAll(/<author\b[^>]*>([\s\S]*?)<\/author>/gi)].map((match) => author(xmlValues(match[1], 'name')[0])).filter(Boolean) as any, year: Number(xmlValues(entry, 'published')[0]?.slice(0, 4)) || undefined, issuedDate: xmlValues(entry, 'published')[0], url: xmlValues(entry, 'id')[0], doi: xmlValues(entry, 'doi')[0], ids: [identifier('arxiv', arxivId)].filter(Boolean) as any, type: 'preprint', downloads: pdf ? [pdf] : [] }); value.topics = [...entry.matchAll(/<category\b[^>]*term=["']([^"']+)/gi)].map((match) => match[1]); value.openAccess = { status: 'green', url: pdf?.url, provider: 'arxiv', verifiedAt: new Date().toISOString() }; return value; }); const total = Number(xmlValues(data, 'totalResults')[0] ?? 0); return page(records, 'arxiv', offset + records.length < total ? String(offset + records.length) : undefined, 'arXiv');
}); }

function dblp(): CompassProviderAdapter { return adapter(providerDescriptor('dblp'), async (context) => {
  const offset = Math.max(0, Number(context.cursor ?? 0)); const url = new URL('https://dblp.org/search/publ/api'); url.searchParams.set('q', queryFor(context)); url.searchParams.set('h', '25'); url.searchParams.set('f', String(offset)); url.searchParams.set('format', 'json'); const { data } = await requestJson(url.toString(), context.signal); const hits = data?.result?.hits?.hit ?? []; const records = hits.map((hit: any) => { const info = hit?.info ?? {}; const creatorList = Array.isArray(info?.authors?.author) ? info.authors.author : info?.authors?.author ? [info.authors.author] : []; return result({ provider: 'dblp', providerId: info?.key ?? info?.url, title: info?.title, authors: authors(creatorList.map((entry: any) => typeof entry === 'string' ? entry : entry?.text)), year: Number(info?.year) || undefined, url: info?.ee ?? info?.url, doi: text(info?.ee).match(/doi\.org\/(10\..+)/i)?.[1], venue: info?.venue, type: /books\//i.test(info?.key ?? '') ? 'book' : 'article', nativeScore: Number(hit?.['@score']) || undefined }); }); const total = Number(data?.result?.hits?.['@total'] ?? 0); return page(records, 'dblp', offset + records.length < total ? String(offset + records.length) : undefined, 'DBLP');
}); }

function semanticScholar(): CompassProviderAdapter { return adapter(providerDescriptor('semanticscholar'), async (context) => {
  const offset = Math.max(0, Number(context.cursor ?? 0)); const doi = context.query.identifiers.find((entry) => entry.scheme === 'doi')?.value; const endpoint = doi ? `https://api.semanticscholar.org/graph/v1/paper/DOI:${encodeURIComponent(doi)}` : 'https://api.semanticscholar.org/graph/v1/paper/search'; const url = new URL(endpoint); const fields = 'paperId,title,abstract,year,publicationDate,authors,url,venue,publicationTypes,externalIds,citationCount,openAccessPdf,fieldsOfStudy'; url.searchParams.set('fields', fields); if (!doi) { url.searchParams.set('query', queryFor(context).replaceAll('-', ' ')); url.searchParams.set('limit', '25'); url.searchParams.set('offset', String(offset)); }
  const { data } = await requestJson(url.toString(), context.signal); const entries = doi ? [data] : data?.data ?? []; const records = entries.map((work: any) => { const pdf = downloadLink('semanticscholar', work?.openAccessPdf?.url, { mediaType: 'application/pdf', license: work?.openAccessPdf?.license }); const value = result({ provider: 'semanticscholar', providerId: work?.paperId, title: work?.title, abstract: work?.abstract, authors: authors(work?.authors ?? []), year: Number(work?.year) || undefined, issuedDate: work?.publicationDate, url: work?.url, doi: work?.externalIds?.DOI, ids: [identifier('arxiv', work?.externalIds?.ArXiv), identifier('pmid', work?.externalIds?.PubMed), identifier('corpusid', work?.externalIds?.CorpusId)].filter(Boolean) as any, venue: work?.venue, citationCount: Number(work?.citationCount) || undefined, type: work?.publicationTypes?.includes('Book') ? 'book' : work?.publicationTypes?.includes('BookSection') ? 'chapter' : work?.publicationTypes?.includes('Dataset') ? 'dataset' : 'article', downloads: pdf ? [pdf] : [] }); value.disciplines = (work?.fieldsOfStudy ?? []).map((entry: unknown) => text(entry, 120)); if (pdf) value.openAccess = { status: 'green', url: pdf.url, license: pdf.license, provider: 'semanticscholar', verifiedAt: pdf.verifiedAt }; return value; }); return page(records, 'semanticscholar', !doi && offset + records.length < Number(data?.total ?? 0) ? String(offset + records.length) : undefined, 'Semantic Scholar');
}); }

export function disciplineAdapters(): Array<[CompassProviderId, CompassProviderAdapter]> { const list = [europePmc(), arxiv(), dblp(), semanticScholar()]; return list.map((entry) => [entry.id, entry]); }
