import type { CompassProviderAdapter, CompassProviderId, CompassPublicationType } from '@shared/compass';
import { providerDescriptor } from './catalog';
import { adapter, author, identifier, page, queryFor, requestJson, result, text } from './provider';

const authors = (values: unknown[]) => values.map(author).filter((entry): entry is NonNullable<ReturnType<typeof author>> => Boolean(entry));
function crossrefType(value: string): CompassPublicationType { return value === 'journal-article' ? 'article' : value === 'book' || value === 'monograph' ? 'book' : value === 'book-chapter' ? 'chapter' : value === 'dissertation' ? 'thesis' : value === 'report' ? 'report' : 'other'; }
function mapCrossref(work: any) { const title = Array.isArray(work?.title) ? work.title[0] : work?.title; const dateParts = work?.published?.['date-parts']?.[0] ?? work?.issued?.['date-parts']?.[0] ?? []; return result({ provider: 'crossref', providerId: work?.DOI ?? work?.URL, title, abstract: work?.abstract, authors: authors(work?.author ?? []), year: Number(dateParts[0]) || undefined, issuedDate: dateParts.length ? dateParts.join('-') : undefined, url: work?.URL, doi: work?.DOI, ids: [...(work?.ISBN ?? []).map((entry: unknown) => identifier('isbn', entry)), ...(work?.ISSN ?? []).map((entry: unknown) => identifier('issn', entry))].filter(Boolean) as any, language: work?.language, venue: Array.isArray(work?.['container-title']) ? work['container-title'][0] : work?.['container-title'], citationCount: Number(work?.['is-referenced-by-count']) || undefined, type: crossrefType(work?.type), nativeScore: Number(work?.score) || undefined }); }

function crossref(): CompassProviderAdapter { return adapter(providerDescriptor('crossref'), async (context) => {
  const doi = context.query.identifiers.find((entry) => entry.scheme === 'doi')?.value; if (doi) { const { data } = await requestJson(`https://api.crossref.org/works/${encodeURIComponent(doi)}`, context.signal); return page([mapCrossref(data?.message)], 'crossref', undefined, 'Crossref'); }
  const offset = Math.max(0, Number(context.cursor ?? 0)); const url = new URL('https://api.crossref.org/works'); const requestedAuthor = context.query.authors[0]; const orcid = context.query.identifiers.find((entry) => entry.scheme === 'orcid')?.value; if (requestedAuthor) url.searchParams.set('query.author', requestedAuthor); else if (!orcid) url.searchParams.set('query.bibliographic', queryFor(context)); url.searchParams.set('rows', '25'); url.searchParams.set('offset', String(offset)); const filters = [orcid ? `orcid:${orcid}` : '', context.query.fromYear ? `from-pub-date:${context.query.fromYear}-01-01` : '', context.query.toYear ? `until-pub-date:${context.query.toYear}-12-31` : ''].filter(Boolean); if (filters.length) url.searchParams.set('filter', filters.join(',')); const { data } = await requestJson(url.toString(), context.signal); const records = (data?.message?.items ?? []).map(mapCrossref); const total = Number(data?.message?.['total-results'] ?? 0); return page(records, 'crossref', records.length === 25 && offset + records.length < total ? String(offset + records.length) : undefined, 'Crossref');
}); }

function openCitations(): CompassProviderAdapter { return adapter(providerDescriptor('opencitations'), async (context) => {
  const doi = context.query.identifiers.find((entry) => entry.scheme === 'doi')?.value; if (!doi) return page([], 'opencitations', undefined, 'OpenCitations'); const encoded = encodeURIComponent(doi); const { data: metadata } = await requestJson(`https://api.opencitations.net/meta/v1/metadata/${encoded}`, context.signal); const { data: citations } = await requestJson(`https://api.opencitations.net/index/v2/citations/${encoded}`, context.signal); const { data: references } = await requestJson(`https://api.opencitations.net/index/v2/references/${encoded}`, context.signal); const work = Array.isArray(metadata) ? metadata[0] : metadata; const creators = typeof work?.author === 'string' ? work.author.split(';').map((name: string) => author(name)).filter(Boolean) as any : authors(work?.author ?? []); const value = result({ provider: 'opencitations', providerId: doi, title: work?.title, authors: creators, year: Number(text(work?.pub_date).slice(0, 4)) || undefined, issuedDate: work?.pub_date, url: `https://doi.org/${doi}`, doi, venue: work?.venue, citationCount: Array.isArray(citations) ? citations.length : Number(work?.citation_count) || undefined, type: text(work?.type).toLocaleLowerCase().includes('book') ? 'book' : 'article' }); value.topics = Array.isArray(references) ? references.slice(0, 20).map((entry: any) => text(entry?.cited ?? entry?.citing, 120)).filter(Boolean) : []; return page([value], 'opencitations', undefined, 'OpenCitations');
}); }

export function enrichmentAdapters(): Array<[CompassProviderId, CompassProviderAdapter]> { const list = [crossref(), openCitations()]; return list.map((entry) => [entry.id, entry]); }
