import type { CompassProviderAdapter, CompassProviderId, CompassPublicationType } from '@shared/compass';
import { providerDescriptor } from './catalog';
import { adapter, author, downloadLink, identifier, page, queryFor, requestJson, requestText, result, text, xmlValues } from './provider';

const authors = (values: unknown[]) => values.map(author).filter((entry): entry is NonNullable<ReturnType<typeof author>> => Boolean(entry));
const yearOf = (value: unknown) => Number(text(value).match(/\b(?:1[0-9]{3}|20\d{2})\b/)?.[0]) || undefined;
function primaryType(value: unknown): CompassPublicationType { const key = text(value).toLocaleLowerCase(); return /photo|image|still image|fotograf|photograph/.test(key) ? 'photograph' : /newspaper|journal|periodical|press|presse/.test(key) ? 'newspaper' : /map|cartograph|carte/.test(key) ? 'map' : /manuscript|manuscrit/.test(key) ? 'manuscript' : /audio|sound|sonore/.test(key) ? 'audio' : /video|moving image|film/.test(key) ? 'video' : /book|text/.test(key) ? 'book' : 'archive-item'; }

function internetArchive(): CompassProviderAdapter { return adapter(providerDescriptor('internetarchive'), async (context) => {
  const pageNumber = Math.max(1, Number(context.cursor ?? 1)); const url = new URL('https://archive.org/advancedsearch.php'); url.searchParams.set('q', queryFor(context)); for (const field of ['identifier', 'title', 'description', 'creator', 'date', 'year', 'language', 'mediatype', 'subject', 'collection', 'rights', 'licenseurl', 'downloads']) url.searchParams.append('fl[]', field); url.searchParams.set('rows', '25'); url.searchParams.set('page', String(pageNumber)); url.searchParams.set('output', 'json');
  const { data } = await requestJson(url.toString(), context.signal); const records = (data?.response?.docs ?? []).map((doc: any) => { const id = doc?.identifier; const mediatype = text(doc?.mediatype); const type = primaryType(mediatype); const thumb = downloadLink('internetarchive', id && type === 'photograph' ? `https://archive.org/download/${encodeURIComponent(id)}/page/n0.jpg` : undefined, { mediaType: 'image/jpeg', rights: doc?.rights }); const value = result({ provider: 'internetarchive', providerId: id, title: doc?.title, abstract: doc?.description, authors: authors(Array.isArray(doc?.creator) ? doc.creator : [doc?.creator]), year: Number(doc?.year) || yearOf(doc?.date), issuedDate: text(doc?.date, 40), url: id ? `https://archive.org/details/${encodeURIComponent(id)}` : undefined, ids: [identifier('internetarchive', id)].filter(Boolean) as any, language: Array.isArray(doc?.language) ? doc.language[0] : doc?.language, type, lane: 'primary', rights: doc?.rights ?? doc?.licenseurl, downloads: thumb ? [thumb] : [] }); value.topics = (Array.isArray(doc?.subject) ? doc.subject : [doc?.subject]).filter(Boolean).slice(0, 20).map((entry: unknown) => text(entry, 120)); return value; }); const total = Number(data?.response?.numFound ?? 0); return page(records, 'internetarchive', pageNumber * 25 < total ? String(pageNumber + 1) : undefined, 'Internet Archive');
}); }

function loc(): CompassProviderAdapter { return adapter(providerDescriptor('loc'), async (context) => {
  const pageNumber = Math.max(1, Number(context.cursor ?? 1)); const url = new URL('https://www.loc.gov/search/'); url.searchParams.set('q', queryFor(context)); url.searchParams.set('fo', 'json'); url.searchParams.set('c', '25'); url.searchParams.set('sp', String(pageNumber)); if (context.query.fromYear || context.query.toYear) url.searchParams.set('dates', `${context.query.fromYear ?? 1000}-${context.query.toYear ?? new Date().getFullYear()}`);
  const { data } = await requestJson(url.toString(), context.signal); const records = (data?.results ?? []).map((item: any) => { const formats = Array.isArray(item?.format) ? item.format : [item?.format]; const type = primaryType(formats.join(' ')); const files = (item?.resources ?? []).flatMap((resource: any) => Array.isArray(resource?.files) ? resource.files.flat() : []).map((file: any) => downloadLink('loc', file?.url ?? file?.full ?? file, { mediaType: file?.mimetype, format: file?.format, rights: item?.rights })).filter(Boolean) as NonNullable<ReturnType<typeof downloadLink>>[]; const value = result({ provider: 'loc', providerId: item?.id ?? item?.url, title: item?.title, abstract: Array.isArray(item?.description) ? item.description[0] : item?.description, authors: authors(Array.isArray(item?.contributor) ? item.contributor : []), year: yearOf(item?.date), issuedDate: item?.date, url: item?.id ?? item?.url, ids: [identifier('loc', item?.id ?? item?.url), ...(item?.number ?? []).map((entry: unknown) => identifier('lccn', entry))].filter(Boolean) as any, language: Array.isArray(item?.language) ? item.language[0] : item?.language, type, lane: 'primary', rights: Array.isArray(item?.rights) ? item.rights.join(' ') : item?.rights, downloads: files.slice(0, 10) }); value.topics = [...(item?.subject ?? []), ...(item?.partof ?? [])].slice(0, 20).map((entry: unknown) => text(entry, 120)); return value; }); const next = data?.pagination?.next ? String(pageNumber + 1) : undefined; return page(records, 'loc', next, 'Library of Congress');
}); }

function gallica(): CompassProviderAdapter { return adapter(providerDescriptor('gallica'), async (context) => {
  const start = Math.max(1, Number(context.cursor ?? 1)); const query = `gallica all "${queryFor(context).replaceAll('"', ' ')}"`; const url = new URL('https://gallica.bnf.fr/SRU'); url.searchParams.set('operation', 'searchRetrieve'); url.searchParams.set('version', '1.2'); url.searchParams.set('query', query); url.searchParams.set('maximumRecords', '25'); url.searchParams.set('startRecord', String(start));
  const { data } = await requestText(url.toString(), context.signal); const blocks = [...data.matchAll(/<(?:\w+:)?recordData\b[^>]*>([\s\S]*?)<\/(?:\w+:)?recordData>/gi)].map((match) => match[1]); const records = blocks.map((block) => { const ids = xmlValues(block, 'identifier'); const arkUrl = ids.find((entry) => /gallica\.bnf\.fr\/ark:\/12148\//i.test(entry)) ?? ids.find((entry) => /ark:\/12148\//i.test(entry)); const landing = arkUrl?.startsWith('http') ? arkUrl : arkUrl ? `https://gallica.bnf.fr/${arkUrl.replace(/^.*?(ark:\/12148\/)/i, '$1')}` : undefined; const rights = xmlValues(block, 'rights').join(' · '); const type = primaryType(xmlValues(block, 'type').join(' ')); const downloadable = landing && !/consultable sur place|protected|indisponible/i.test(rights) ? downloadLink('gallica', `${landing}.highres`, { format: type === 'photograph' || type === 'map' ? 'image' : 'document', rights }) : null; const value = result({ provider: 'gallica', providerId: landing ?? ids[0] ?? xmlValues(block, 'title')[0], title: xmlValues(block, 'title')[0], abstract: xmlValues(block, 'description')[0], authors: authors(xmlValues(block, 'creator')), year: yearOf(xmlValues(block, 'date')[0]), issuedDate: xmlValues(block, 'date')[0], url: landing, ids: [identifier('ark', landing)].filter(Boolean) as any, language: xmlValues(block, 'language')[0], type, lane: 'primary', rights, downloads: downloadable ? [downloadable] : [] }); value.publisher = xmlValues(block, 'publisher')[0]; value.topics = xmlValues(block, 'subject').slice(0, 20); return value; }); const total = Number(xmlValues(data, 'numberOfRecords')[0] ?? 0); return page(records, 'gallica', start + records.length <= total ? String(start + records.length) : undefined, 'Gallica / Bibliothèque nationale de France');
}); }

export function heritageAdapters(): Array<[CompassProviderId, CompassProviderAdapter]> { const list = [internetArchive(), loc(), gallica()]; return list.map((entry) => [entry.id, entry]); }
