import { createHash } from 'node:crypto';
import type { CompassFilters, CompassIdentifier, CompassPublicationType, CompassQueryPlan } from '@shared/compass';

const LANGUAGES: Record<string, string> = { english: 'en', inglés: 'en', french: 'fr', francés: 'fr', français: 'fr', german: 'de', alemán: 'de', deutsch: 'de', spanish: 'es', español: 'es', catalan: 'ca', català: 'ca', portuguese: 'pt', português: 'pt', italian: 'it', italiano: 'it', arabic: 'ar', árabe: 'ar' };
const TYPE_MAP: Record<string, CompassPublicationType> = { article: 'article', articles: 'article', artículo: 'article', artículos: 'article', book: 'book', books: 'book', libro: 'book', libros: 'book', chapter: 'chapter', chapters: 'chapter', capítulo: 'chapter', thesis: 'thesis', theses: 'thesis', tesis: 'thesis', dissertation: 'thesis', report: 'report', reports: 'report', informe: 'report', dataset: 'dataset', datasets: 'dataset', preprint: 'preprint', preprints: 'preprint' };
function clean(value: unknown, max = 2_000): string { return String(value ?? '').replace(/\s+/g, ' ').trim().slice(0, max); }
function unique(values: string[]): string[] { return [...new Set(values.map((v) => clean(v, 120).toLowerCase()).filter(Boolean))]; }
function quoted(query: string): string[] { return [...query.matchAll(/"([^"\n]{2,200})"|'([^'\n]{2,200})'/g)].map((m) => m[1] || m[2]).filter(Boolean); }
function years(query: string): { fromYear?: number; toYear?: number } { const range = query.match(/\b(19\d{2}|20\d{2})\s*(?:-|–|to|a|hasta)\s*(19\d{2}|20\d{2})\b/i); if (range) return { fromYear: Number(range[1]), toYear: Number(range[2]) }; const since = query.match(/\b(?:since|desde|after|después de)\s+(19\d{2}|20\d{2})\b/i); if (since) return { fromYear: Number(since[1]) }; const only = query.match(/\b(19\d{2}|20\d{2})\b/); return only ? { fromYear: Number(only[1]), toYear: Number(only[1]) } : {}; }
function identifiers(query: string): CompassIdentifier[] { const out: CompassIdentifier[] = []; for (const m of query.matchAll(/\b(10\.\d{4,9}\/[-._;()/:A-Z0-9]+)\b/ig)) out.push({ scheme: 'doi', value: m[1].replace(/[.,;]+$/, '') }); for (const m of query.matchAll(/\b(?:ISBN(?:-1[03])?[:\s]*)?((?:97[89][ -]?)?\d[\d -]{8,16}\d)\b/ig)) { const value = m[1].replace(/[ -]/g, ''); if (value.length === 10 || value.length === 13) out.push({ scheme: 'isbn', value }); } return out; }
export function interpretCompassQuery(input: string, filters: CompassFilters = {}): CompassQueryPlan {
  const source = clean(input); if (!source) return { text: '', exactPhrases: [], excludedTerms: [], authors: [], venues: [], identifiers: [], languages: filters.languages ?? [], types: filters.types ?? [], disciplines: filters.disciplines ?? [], openAccessOnly: filters.openAccessOnly === true, providers: filters.providers ?? [] };
  const exactPhrases = quoted(source); const excludedTerms = unique([...source.matchAll(/(?:^|\s)-([\p{L}\d][\p{L}\d-]*)/gu)].map((m) => m[1]));
  const authors = unique([...source.matchAll(/(?:author|autor|auteur|by|por):([^\s,;]+)/gi)].map((m) => m[1])); const venues = unique([...source.matchAll(/(?:venue|journal|revista|journal):([^\s,;]+)/gi)].map((m) => m[1]));
  const langs = [...source.toLowerCase().matchAll(/(?:language|lang|idioma|langue):?\s*([\p{L}-]+)/gu)].map((m) => LANGUAGES[m[1]] || m[1]).concat((filters.languages ?? []).map((x) => x.toLowerCase()));
  const types = [...source.toLowerCase().matchAll(/(?:type|tipo):?\s*([\p{L}-]+)/gu)].map((m) => TYPE_MAP[m[1]]).filter(Boolean) as CompassPublicationType[];
  for (const word of source.toLowerCase().split(/[^\p{L}]+/u)) if (TYPE_MAP[word]) types.push(TYPE_MAP[word]);
  const range = years(source); const plan: CompassQueryPlan = { text: source, exactPhrases, excludedTerms, authors, venues, identifiers: identifiers(source), fromYear: filters.fromYear ?? range.fromYear, toYear: filters.toYear ?? range.toYear, languages: unique(langs), types: [...new Set([...(filters.types ?? []), ...types])], disciplines: unique(filters.disciplines ?? []), openAccessOnly: filters.openAccessOnly === true || /\b(?:open\s+access|oa|acceso\s+abierto)\b/i.test(source), providers: filters.providers ?? [] };
  return plan;
}
export function compassQueryFingerprint(plan: CompassQueryPlan, filters: CompassFilters = {}): string { return createHash('sha256').update(JSON.stringify({ plan, filters })).digest('hex'); }
