import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { ProsopSourceInput, ProsopSourcesWorkspace } from '@shared/prosopography';
import { Icon } from '../components/ui';
import { ProsopObservationsPanel } from '../components/ProsopObservationsPanel';
import { errorText, t, tx } from '../i18n';

type Tab = 'catalogue' | 'batches' | 'templates' | 'observations';
const inputClass = 'w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm outline-none focus:border-blue-500 dark:border-neutral-700 dark:bg-neutral-950';

export function ProsopSourcesView() {
  const [data, setData] = useState<ProsopSourcesWorkspace | null>(null);
  const [tab, setTab] = useState<Tab>('catalogue');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [draft, setDraft] = useState<ProsopSourceInput>({ title: '', sourceKind: 'document' });
  const [segment, setSegment] = useState({ locatorDisplay: '', quotedText: '', language: '' });
  const [error, setError] = useState('');
  const [busy, setBusy] = useState('');
  const fileRef = useRef<HTMLInputElement>(null);
  const load = useCallback(async () => {
    try { const next = await window.nodus.getProsopSourcesWorkspace(); setData(next); setSelectedId((current) => current ?? next.sources[0]?.sourceId ?? null); }
    catch (cause) { setError(errorText(cause)); }
  }, []);
  useEffect(() => { void load(); }, [load]);
  const selected = useMemo(() => data?.sources.find((item) => item.sourceId === selectedId) ?? null, [data, selectedId]);
  const act = async (key: string, action: () => Promise<unknown>) => {
    setBusy(key); setError('');
    try { await action(); await load(); } catch (cause) { setError(errorText(cause)); } finally { setBusy(''); }
  };
  if (!data) return <div className="grid h-full place-items-center text-sm text-neutral-500"><Icon name="sync" className="animate-spin" /></div>;
  return (
    <div className="flex h-full min-h-0 flex-col bg-neutral-50 dark:bg-neutral-950" data-testid="prosop-sources-view">
      <header className="border-b border-neutral-200 bg-white px-6 py-5 dark:border-neutral-800 dark:bg-neutral-950"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-wider text-blue-600">{t('Corpus y captura')}</p><h1 className="mt-1 text-2xl font-semibold">{t('Fuentes')}</h1><p className="mt-1 text-xs text-neutral-500">{t('Cada observación vuelve a un segmento citable de una fuente.')}</p></div><nav className="flex gap-1">{([['catalogue','Catálogo','archive'],['batches','Lotes','table'],['templates','Plantillas','copy'],['observations','Observaciones','edit']] as const).map(([id,label,icon]) => <button key={id} className={`btn text-xs ${tab === id ? 'bg-blue-600 text-white' : 'btn-ghost'}`} onClick={() => setTab(id)}><Icon name={icon} size={13} />{t(label)}</button>)}</nav></div></header>
      {error && <div className="mx-6 mt-4 rounded-lg border border-red-300 bg-red-50 px-3 py-2 text-xs text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{error}</div>}
      <main className="min-h-0 flex-1 overflow-auto p-6">
        {tab === 'catalogue' && <div className="grid gap-5 xl:grid-cols-[280px_minmax(0,1fr)_330px]">
          <section className="rounded-2xl border border-neutral-200 bg-white p-3 dark:border-neutral-800 dark:bg-neutral-900/50"><div className="flex items-center justify-between px-2 pb-3"><h2 className="text-sm font-semibold">{tx('{count} fuentes', { count: data.sources.length })}</h2><button className="rounded-lg p-2 text-blue-600 hover:bg-blue-50 dark:hover:bg-blue-950" onClick={() => { setSelectedId(null); setDraft({ title: '', sourceKind: 'document' }); }}><Icon name="plus" size={15} /></button></div><div className="space-y-1">{data.sources.map((source) => <button key={source.sourceId} className={`w-full rounded-xl px-3 py-2 text-left ${selectedId === source.sourceId ? 'bg-blue-50 ring-1 ring-blue-300 dark:bg-blue-950/30 dark:ring-blue-800' : 'hover:bg-neutral-50 dark:hover:bg-neutral-900'}`} onClick={() => { setSelectedId(source.sourceId); setDraft(source); }}><span className="block truncate text-sm font-medium">{source.title}</span><span className="mt-1 block text-[10px] text-neutral-500">{source.sourceKind} · {source.segments.length} {t('segmentos')} · {source.factoidCount} {t('observaciones')}</span></button>)}</div></section>
          <section className="rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900/50"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{selected ? t('Dossier de fuente') : t('Nueva fuente')}</h2><p className="mt-1 text-xs text-neutral-500">{t('Conserva cita, cobertura, fiabilidad y restricciones por separado.')}</p></div><button disabled={!draft.title.trim() || busy === 'source'} className="btn bg-blue-600 text-white" onClick={() => void act('source', async () => { const saved = await window.nodus.saveProsopSource(draft); setSelectedId(saved.sourceId); setDraft(saved); })}><Icon name="check" size={14} />{t('Guardar')}</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs text-neutral-500 sm:col-span-2">{t('Título')}<input className={`${inputClass} mt-1`} value={draft.title} onChange={(e) => setDraft((item) => ({ ...item, title: e.target.value }))} /></label><label className="text-xs text-neutral-500">{t('Tipo de fuente')}<input className={`${inputClass} mt-1`} value={draft.sourceKind} onChange={(e) => setDraft((item) => ({ ...item, sourceKind: e.target.value }))} /></label><label className="text-xs text-neutral-500">{t('Referencia')}<input className={`${inputClass} mt-1`} value={draft.referenceCode ?? ''} onChange={(e) => setDraft((item) => ({ ...item, referenceCode: e.target.value }))} /></label><label className="text-xs text-neutral-500 sm:col-span-2">{t('Cita')}<textarea className={`${inputClass} mt-1 min-h-20`} value={draft.citation ?? ''} onChange={(e) => setDraft((item) => ({ ...item, citation: e.target.value }))} /></label><label className="text-xs text-neutral-500">{t('Repositorio')}<input className={`${inputClass} mt-1`} value={draft.repository ?? ''} onChange={(e) => setDraft((item) => ({ ...item, repository: e.target.value }))} /></label><label className="text-xs text-neutral-500">{t('Acceso')}<select className={`${inputClass} mt-1`} value={draft.accessStatus ?? 'open'} onChange={(e) => setDraft((item) => ({ ...item, accessStatus: e.target.value as ProsopSourceInput['accessStatus'] }))}><option value="open">{t('Abierto')}</option><option value="restricted">{t('Restringido')}</option><option value="embargoed">{t('Embargado')}</option></select></label><label className="text-xs text-neutral-500">{t('Cobertura')}<textarea className={`${inputClass} mt-1 min-h-20`} value={draft.coverageNotes ?? ''} onChange={(e) => setDraft((item) => ({ ...item, coverageNotes: e.target.value }))} /></label><label className="text-xs text-neutral-500">{t('Fiabilidad contextual')}<textarea className={`${inputClass} mt-1 min-h-20`} value={draft.reliabilityNotes ?? ''} onChange={(e) => setDraft((item) => ({ ...item, reliabilityNotes: e.target.value }))} /></label></div></section>
          <aside className="rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900/50"><h2 className="font-semibold">{t('Segmentos citables')}</h2>{!selected ? <p className="mt-3 text-xs text-neutral-500">{t('Guarda primero la fuente.')}</p> : <><div className="mt-4 space-y-2">{selected.segments.map((item) => <article key={item.segmentId} className="rounded-xl border border-neutral-200 p-3 dark:border-neutral-800"><p className="text-xs font-medium text-blue-700 dark:text-blue-300">{item.locatorDisplay}</p><p className="mt-1 line-clamp-3 text-xs text-neutral-500">{item.quotedText || t('Sin transcripción')}</p></article>)}</div><div className="mt-4 space-y-2 border-t border-neutral-200 pt-4 dark:border-neutral-800"><input className={inputClass} placeholder={t('Localizador: folio, página, tiempo…')} value={segment.locatorDisplay} onChange={(e) => setSegment((item) => ({ ...item, locatorDisplay: e.target.value }))} /><textarea className={`${inputClass} min-h-24`} placeholder={t('Transcripción literal')} value={segment.quotedText} onChange={(e) => setSegment((item) => ({ ...item, quotedText: e.target.value }))} /><button disabled={!segment.locatorDisplay.trim()} className="btn w-full bg-blue-600 text-white" onClick={() => void act('segment', async () => { await window.nodus.saveProsopSourceSegment({ sourceId: selected.sourceId, ...segment }); setSegment({ locatorDisplay: '', quotedText: '', language: '' }); })}><Icon name="plus" size={14} />{t('Añadir segmento')}</button></div></>}</aside>
        </div>}
        {tab === 'batches' && <section className="rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900/50"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{t('Importación por lotes')}</h2><p className="mt-1 text-xs text-neutral-500">{t('Cada fila queda en staging; nunca se convierte automáticamente en persona.')}</p></div><><input ref={fileRef} type="file" accept=".csv,.tsv,.txt" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; if (!file) return; void act('import', async () => window.nodus.importProsopDelimited({ sourceId: selectedId, fileName: file.name, text: await file.text() })); event.target.value=''; }} /><button className="btn bg-blue-600 text-white" onClick={() => fileRef.current?.click()}><Icon name="upload" size={14} />{t('Importar CSV o TSV')}</button></></div><div className="mt-5 space-y-3">{data.batches.length === 0 && <p className="rounded-xl border border-dashed border-neutral-300 py-12 text-center text-sm text-neutral-500 dark:border-neutral-700">{t('Todavía no hay lotes importados.')}</p>}{data.batches.map((batch) => <article key={batch.batchId} className="rounded-xl border border-neutral-200 dark:border-neutral-800"><div className="flex items-center justify-between gap-3 p-4"><div><h3 className="text-sm font-medium">{batch.fileName}</h3><p className="mt-1 text-[10px] text-neutral-500">{tx('{rows} filas · {accepted} aceptadas · huella {hash}', { rows: batch.rowCount, accepted: batch.acceptedCount, hash: batch.contentHash.slice(0, 10) })}</p></div><span className="rounded-full bg-amber-100 px-2 py-1 text-[10px] text-amber-700 dark:bg-amber-500/15 dark:text-amber-300">{t(batch.status)}</span></div><div className="max-h-72 overflow-auto border-t border-neutral-200 dark:border-neutral-800"><table className="w-full text-left text-xs"><tbody>{batch.rows.slice(0,100).map((row) => <tr key={row.captureRowId} className="border-b border-neutral-100 last:border-0 dark:border-neutral-800"><td className="w-16 px-3 py-2 text-neutral-400">{row.rowNo}</td><td className="max-w-0 truncate px-3 py-2 font-mono text-[10px]">{JSON.stringify(row.raw)}</td><td className="w-36 px-3 py-2"><div className="flex gap-1"><button className="rounded p-1.5 text-emerald-600 hover:bg-emerald-50" onClick={() => void act(`row-${row.captureRowId}`, () => window.nodus.reviewProsopCaptureRow(row.captureRowId,'accepted'))}><Icon name="check" size={13} /></button><button className="rounded p-1.5 text-red-600 hover:bg-red-50" onClick={() => void act(`row-${row.captureRowId}`, () => window.nodus.reviewProsopCaptureRow(row.captureRowId,'rejected'))}><Icon name="x" size={13} /></button><span className="ml-1 text-[10px] text-neutral-500">{t(row.status)}</span></div></td></tr>)}</tbody></table></div></article>)}</div></section>}
        {tab === 'templates' && <section className="rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900/50"><h2 className="font-semibold">{t('Plantillas de vaciado')}</h2><p className="mt-1 text-xs text-neutral-500">{t('Una carta, un padrón y un acta pueden capturarse con formularios distintos sin cambiar el modelo maestro.')}</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.templates.map((item) => <article key={item.templateId} className="rounded-xl border border-neutral-200 p-4 dark:border-neutral-800"><h3 className="text-sm font-medium">{item.name}</h3><p className="mt-1 text-xs text-neutral-500">{item.sourceKind} · v{item.version}</p></article>)}<button className="rounded-xl border border-dashed border-neutral-300 p-6 text-sm text-neutral-500 hover:border-blue-400 hover:text-blue-600 dark:border-neutral-700" onClick={() => void act('template', () => window.nodus.saveProsopCaptureTemplate({ name: t('Plantilla general'), sourceKind: 'document' }))}><Icon name="plus" className="mx-auto mb-2" />{t('Crear plantilla')}</button></div></section>}
        {tab === 'observations' && <ProsopObservationsPanel sources={data.sources}/>}
      </main>
    </div>
  );
}
