import { useCallback, useEffect, useMemo, useState } from 'react';
import type { ProsopIdentityWorkspace, ProsopPersonProfile } from '@shared/prosopography';
import { Icon } from '../components/ui';
import { errorText, t, tx } from '../i18n';

const field = 'w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm outline-none focus:border-blue-500 dark:border-neutral-700 dark:bg-neutral-950';

export function ProsopPersonsView() {
  const [data,setData] = useState<ProsopIdentityWorkspace | null>(null);
  const [selectedId,setSelectedId] = useState<string | null>(null);
  const [name,setName] = useState(''); const [context,setContext] = useState('');
  const [candidates,setCandidates] = useState<Array<ProsopPersonProfile & { score:number; reasons:string[] }>>([]);
  const [error,setError] = useState(''); const [busy,setBusy] = useState(false);
  const load = useCallback(async () => { try { const next=await window.nodus.getProsopIdentityWorkspace(); setData(next); setSelectedId((value)=>value??next.persons[0]?.personId??null); } catch(cause){setError(errorText(cause));} },[]);
  useEffect(()=>{void load();},[load]);
  const selected=useMemo(()=>data?.persons.find((item)=>item.personId===selectedId)??null,[data,selectedId]);
  const act=async(action:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await action();await load();}catch(cause){setError(errorText(cause));}finally{setBusy(false);}};
  const inspect=async()=>{try{setCandidates(await window.nodus.searchProsopIdentityCandidates(name));}catch(cause){setError(errorText(cause));}};
  if(!data)return <div className="grid h-full place-items-center"><Icon name="sync" className="animate-spin"/></div>;
  return <div className="flex h-full min-h-0 flex-col bg-neutral-50 dark:bg-neutral-950" data-testid="prosop-persons-view">
    <header className="border-b border-neutral-200 bg-white px-6 py-5 dark:border-neutral-800 dark:bg-neutral-950"><p className="text-[10px] font-semibold uppercase tracking-wider text-blue-600">{t('Identidad histórica')}</p><h1 className="mt-1 text-2xl font-semibold">{t('Personas')}</h1><p className="mt-1 text-xs text-neutral-500">{t('Una mención no es una persona: compara, documenta y decide.')}</p></header>
    {error&&<p role="alert" className="mx-6 mt-4 rounded-lg bg-red-50 px-3 py-2 text-xs text-red-700 dark:bg-red-950/30 dark:text-red-300">{error}</p>}
    <main className="grid min-h-0 flex-1 gap-5 overflow-auto p-6 xl:grid-cols-[300px_minmax(0,1fr)_390px]">
      <section className="rounded-2xl border border-neutral-200 bg-white p-3 dark:border-neutral-800 dark:bg-neutral-900/50"><h2 className="px-2 pb-3 text-sm font-semibold">{tx('{count} personas · {mentions} menciones sin resolver',{count:data.persons.filter((item)=>item.identityStatus!=='merged').length,mentions:data.attestations.filter((item)=>!item.personId).length})}</h2><div className="space-y-1">{data.persons.map((person)=><button key={person.personId} className={`w-full rounded-xl px-3 py-2 text-left ${selectedId===person.personId?'bg-blue-50 ring-1 ring-blue-300 dark:bg-blue-950/30 dark:ring-blue-800':'hover:bg-neutral-50 dark:hover:bg-neutral-900'} ${person.identityStatus==='merged'?'opacity-50':''}`} onClick={()=>setSelectedId(person.personId)}><span className="block text-sm font-medium">{person.displayName}</span><span className="mt-1 block text-[10px] text-neutral-500">{person.attestations.length} {t('menciones')} · {person.sourceCount} {t('fuentes')} · {t(person.identityStatus)}</span></button>)}</div></section>
      <section className="rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900/50">{selected?<><div className="flex items-start justify-between"><div><h2 className="text-xl font-semibold">{selected.displayName}</h2><p className="mt-1 text-xs text-neutral-500">{t('Dossier documentado, no biografía inferida.')}</p></div><span className="rounded-full bg-blue-50 px-2.5 py-1 text-[10px] text-blue-700 dark:bg-blue-950/30 dark:text-blue-300">{t(selected.identityStatus)}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{[['Identidad',selected.reviewStatus],['Fuentes',selected.sourceCount],['Observaciones',selected.statementCount]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-neutral-50 p-3 dark:bg-neutral-950"><p className="text-[10px] uppercase text-neutral-400">{t(String(label))}</p><p className="mt-1 text-sm font-semibold">{String(value)}</p></div>)}</div><h3 className="mt-6 text-sm font-semibold">{t('Nombres documentados')}</h3><div className="mt-2 space-y-2">{selected.attestations.map((item)=><article key={item.attestationId} className="rounded-xl border border-neutral-200 p-3 dark:border-neutral-800"><p className="text-sm font-medium">{item.literalName}</p><p className="mt-1 text-xs text-neutral-500">{item.context||t('Sin contexto')} · {t(item.certainty)}</p></article>)}</div><h3 className="mt-6 text-sm font-semibold">{t('Autoridades')}</h3><div className="mt-2 flex flex-wrap gap-2">{selected.authorityIds.map((item)=><span key={item.authorityId} className="rounded-lg border border-neutral-200 px-2 py-1 text-xs dark:border-neutral-800">{item.scheme}: {item.externalId}</span>)}</div></>:<p className="py-20 text-center text-sm text-neutral-500">{t('Selecciona una persona.')}</p>}</section>
      <aside className="space-y-5"><section className="rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900/50"><h2 className="font-semibold">{t('Individualizar una mención')}</h2><p className="mt-1 text-xs text-neutral-500">{t('Primero conserva la grafía; después busca candidatos.')}</p><div className="mt-4 space-y-2"><input className={field} placeholder={t('Nombre tal como aparece')} value={name} onChange={(event)=>setName(event.target.value)}/><textarea className={`${field} min-h-20`} placeholder={t('Contexto, título, lugar…')} value={context} onChange={(event)=>setContext(event.target.value)}/><button disabled={!name.trim()} className="btn w-full btn-ghost" onClick={()=>void inspect()}><Icon name="search" size={14}/>{t('Buscar candidatos')}</button></div><div className="mt-4 space-y-2">{candidates.map((candidate)=><article key={candidate.personId} className="rounded-xl border border-neutral-200 p-3 dark:border-neutral-800"><div className="flex items-center justify-between"><div><p className="text-sm font-medium">{candidate.displayName}</p><p className="text-[10px] text-neutral-500">{Math.round(candidate.score*100)}%</p></div><button disabled={busy} className="rounded-lg bg-blue-600 px-2 py-1 text-xs text-white" onClick={()=>void act(async()=>{const mention=await window.nodus.saveProsopNameAttestation({literalName:name,context});const proposal=await window.nodus.saveProsopIdentityHypothesis({leftKind:'attestation',leftId:mention.attestationId,rightKind:'person',rightId:candidate.personId,relation:'same_as',rationale:'Decisión humana tras comparar la mención.'});await window.nodus.decideProsopIdentityHypothesis(proposal.hypothesisId,'accepted');setName('');setContext('');setCandidates([]);})}>{t('Vincular')}</button></div></article>)}</div><div className="mt-4 grid grid-cols-2 gap-2"><button disabled={!name.trim()||busy} className="btn btn-ghost" onClick={()=>void act(async()=>{await window.nodus.saveProsopNameAttestation({literalName:name,context});setName('');setContext('');})}>{t('Dejar sin resolver')}</button><button disabled={!name.trim()||busy} className="btn bg-blue-600 text-white" onClick={()=>void act(async()=>{const person=await window.nodus.createProsopPerson({displayName:name,preferredNameBasis:'Mención revisada'});await window.nodus.saveProsopNameAttestation({literalName:name,context,personId:person.personId});setSelectedId(person.personId);setName('');setContext('');})}>{t('Crear persona')}</button></div></section>
      <section className="rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900/50"><h2 className="font-semibold">{t('Organizaciones')}</h2><p className="mt-1 text-xs text-neutral-500">{t('Instituciones y variantes se resuelven como autoridades separadas.')}</p><div className="mt-3 flex flex-wrap gap-2">{data.organizations.map((item)=><span key={item.organizationId} className="rounded-lg bg-neutral-100 px-2 py-1 text-xs dark:bg-neutral-800">{item.preferredName}</span>)}</div><button className="mt-3 btn btn-ghost" onClick={()=>void act(()=>window.nodus.saveProsopOrganization({preferredName:t('Organización sin nombre'),kind:'institution'}))}><Icon name="plus" size={14}/>{t('Añadir organización')}</button></section></aside>
    </main>
  </div>;
}
