import { useEffect, useState } from 'react';
import type { ProsopSearchHit } from '@shared/prosopography';
import { Icon } from '../components/ui';
import { errorText, t, tx } from '../i18n';
export function ProsopSearchView(){
  const [query,setQuery]=useState('');const [kind,setKind]=useState<ProsopSearchHit['kind']|''>('');const [hits,setHits]=useState<ProsopSearchHit[]>([]);const [error,setError]=useState('');
  useEffect(()=>{const timer=setTimeout(()=>{if(!query.trim()){setHits([]);return;}void window.nodus.searchProsopography(query,kind||undefined).then(setHits).catch((cause)=>setError(errorText(cause)));},180);return()=>clearTimeout(timer);},[query,kind]);
  return <div className="h-full overflow-auto bg-neutral-50 p-6 dark:bg-neutral-950" data-testid="prosop-search-view"><div className="mx-auto max-w-5xl"><p className="text-[10px] font-semibold uppercase tracking-wider text-blue-600">{t('Trazabilidad transversal')}</p><h1 className="mt-1 text-2xl font-semibold">{t('Buscar')}</h1><p className="mt-1 text-xs text-neutral-500">{t('Recorre la ruta entre personas, grafías, observaciones y fuentes.')}</p><div className="mt-5 flex gap-2"><div className="flex flex-1 items-center gap-2 rounded-xl border border-neutral-300 bg-white px-3 dark:border-neutral-700 dark:bg-neutral-900"><Icon name="search" size={16}/><input autoFocus className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none" placeholder={t('Nombre, literal, cita o referencia…')} value={query} onChange={(event)=>setQuery(event.target.value)}/></div><select className="rounded-xl border border-neutral-300 bg-white px-3 text-sm dark:border-neutral-700 dark:bg-neutral-900" value={kind} onChange={(event)=>setKind(event.target.value as typeof kind)}><option value="">{t('Todo')}</option>{['person','mention','source','statement'].map((value)=><option key={value} value={value}>{t(value)}</option>)}</select></div>{error&&<p role="alert" className="mt-3 text-xs text-red-600">{error}</p>}<p className="mt-5 text-xs text-neutral-500">{tx('{count} resultados',{count:hits.length})}</p><div className="mt-3 divide-y divide-neutral-200 overflow-hidden rounded-2xl border border-neutral-200 bg-white dark:divide-neutral-800 dark:border-neutral-800 dark:bg-neutral-900/45">{hits.map((hit)=><button key={`${hit.kind}-${hit.id}`} className="flex w-full items-center gap-3 p-4 text-left hover:bg-neutral-50 dark:hover:bg-neutral-800"><span className="grid h-9 w-9 place-items-center rounded-lg bg-blue-50 text-blue-600 dark:bg-blue-950/30"><Icon name={hit.kind==='person'?'person':hit.kind==='source'?'archive':'edit'} size={15}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{hit.title}</p><p className="mt-1 truncate text-xs text-neutral-500">{hit.subtitle}</p></div><span className="rounded-full bg-neutral-100 px-2 py-1 text-[10px] dark:bg-neutral-800">{t(hit.kind)}</span><Icon name="chevronRight" size={14} className="text-neutral-400"/></button>)}</div></div></div>;
}
