import { useCallback, useEffect, useMemo, useState } from 'react';
import type { StudyFlashcard, StudyFlashcardInput, StudyQuestion, StudyWorkspace } from '@shared/types';
import { clozeStudyFlashcard } from '@shared/studyFlashcards';
import { Icon } from '../components/ui';
import { t } from '../i18n';

const emptyCard = (): StudyFlashcardInput => ({ type: 'front_back', front: '', back: '', tags: [], difficulty: 'medium' });

export function StudyReviewView() {
  const [cards, setCards] = useState<StudyFlashcard[]>([]); const [workspace, setWorkspace] = useState<StudyWorkspace | null>(null);
  const [questions, setQuestions] = useState<StudyQuestion[]>([]); const [draft, setDraft] = useState<StudyFlashcardInput | null>(null);
  const [search, setSearch] = useState(''); const [subjectId, setSubjectId] = useState(''); const [dueOnly, setDueOnly] = useState(false);
  const [reviewing, setReviewing] = useState(false); const [revealed, setRevealed] = useState(false); const [index, setIndex] = useState(0);
  const [startedAt, setStartedAt] = useState(Date.now()); const [reviewed, setReviewed] = useState(0); const [error, setError] = useState('');
  const load = useCallback(async () => {
    const [nextCards, nextWorkspace, nextQuestions] = await Promise.all([
      window.nodus.listStudyFlashcards({ search, subjectId: subjectId || undefined, dueOnly }), window.nodus.getStudyWorkspace(), window.nodus.listStudyQuestions({ status: 'approved', subjectId: subjectId || undefined }),
    ]); setCards(nextCards); setWorkspace(nextWorkspace); setQuestions(nextQuestions);
  }, [dueOnly, search, subjectId]);
  useEffect(() => { void load().catch((cause) => setError(cause instanceof Error ? cause.message : String(cause))); }, [load]);
  const sessionCards = useMemo(() => cards.filter((card) => !card.srs.excluded && !card.srs.mastered), [cards]);
  const current = sessionCards[index] ?? null;
  const displayed = current?.type === 'cloze' ? clozeStudyFlashcard(current.front) : current ? { question: current.front, answer: current.back } : null;
  const save = async () => { if (!draft) return; try { await window.nodus.createStudyFlashcard(draft); setDraft(null); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } };
  const rate = async (rating: 0 | 1 | 2 | 3 | 4 | 5) => { if (!current) return; await window.nodus.reviewStudyFlashcard({ cardId: current.id, rating, elapsedMs: Date.now() - startedAt }); setReviewed((value) => value + 1); setRevealed(false); setStartedAt(Date.now()); if (index + 1 >= sessionCards.length) { setReviewing(false); setIndex(0); await load(); } else setIndex((value) => value + 1); };
  const speak = (text: string) => { speechSynthesis.cancel(); speechSynthesis.speak(new SpeechSynthesisUtterance(text)); };
  return <div className="flex h-full min-h-0 flex-col" data-testid="study-review-view">
    <header className="border-b border-neutral-800 bg-neutral-950/70 px-4 py-3"><div className="flex flex-wrap items-center gap-2"><div className="mr-auto"><p className="text-[10px] uppercase tracking-[0.18em] text-teal-400">{t('Aprendizaje adaptativo')}</p><h1 className="text-xl font-semibold">{t('Flashcards y repaso')}</h1></div><button className="btn btn-ghost" disabled={!questions.length} onClick={() => void window.nodus.createStudyFlashcardsFromQuestions(questions.map((question) => question.id)).then(load)}><Icon name="wand" />{t('Convertir preguntas')}</button><button data-testid="study-flashcard-new" className="btn btn-secondary" onClick={() => setDraft(emptyCard())}><Icon name="plus" />{t('Nueva tarjeta')}</button><button data-testid="study-review-start" className="btn btn-primary" disabled={!sessionCards.length} onClick={() => { setReviewing(true); setIndex(0); setRevealed(false); setStartedAt(Date.now()); }}>{t('Repasar ahora')} · {sessionCards.length}</button></div>
      <div className="mt-3 grid gap-2 md:grid-cols-[minmax(240px,1.5fr)_1fr_auto]"><div className="relative"><Icon name="search" size={14} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-neutral-600" /><input className="input input-with-leading-icon w-full" value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t('Buscar tarjetas…')} /></div><select className="input" value={subjectId} onChange={(event) => setSubjectId(event.target.value)}><option value="">{t('Todas las asignaturas')}</option>{workspace?.subjects.map((subject) => <option key={subject.id} value={subject.id}>{subject.name}</option>)}</select><label className="flex items-center gap-2 rounded-lg border border-neutral-800 px-3 text-xs"><input type="checkbox" checked={dueOnly} onChange={(event) => setDueOnly(event.target.checked)} />{t('Solo pendientes')}</label></div>
    </header>
    {error && <div className="m-4 rounded-lg border border-red-900 bg-red-950/20 p-3 text-xs text-red-300">{error}</div>}
    {draft && <section className="m-4 grid gap-3 rounded-xl border border-teal-900 bg-teal-950/15 p-4 md:grid-cols-2" data-testid="study-flashcard-editor"><select className="input" value={draft.type} onChange={(event) => setDraft({ ...draft, type: event.target.value as StudyFlashcardInput['type'] })}><option value="front_back">{t('Pregunta / respuesta')}</option><option value="term_definition">{t('Término / definición')}</option><option value="cloze">{t('Completar huecos')}</option><option value="image_explanation">{t('Imagen / explicación')}</option></select><select className="input" value={draft.subjectId ?? ''} onChange={(event) => setDraft({ ...draft, subjectId: event.target.value || null })}><option value="">{t('Sin asignatura')}</option>{workspace?.subjects.map((subject) => <option key={subject.id} value={subject.id}>{subject.name}</option>)}</select><textarea data-testid="study-flashcard-front" className="input min-h-28" value={draft.front} onChange={(event) => setDraft({ ...draft, front: event.target.value })} placeholder={draft.type === 'cloze' ? 'La capital es {{c1::Madrid}}.' : t('Cara frontal')} /><textarea className="input min-h-28" value={draft.back} onChange={(event) => setDraft({ ...draft, back: event.target.value })} placeholder={t('Respuesta')} /><input className="input" value={draft.tags?.join(', ') ?? ''} onChange={(event) => setDraft({ ...draft, tags: event.target.value.split(',').map((value) => value.trim()).filter(Boolean) })} placeholder={t('Etiquetas')} /><div className="flex justify-end gap-2"><button className="btn btn-ghost" onClick={() => setDraft(null)}>{t('Cancelar')}</button><button data-testid="study-flashcard-save" className="btn btn-primary" disabled={!draft.front.trim() || !draft.back.trim()} onClick={() => void save()}>{t('Guardar tarjeta')}</button></div></section>}
    {!draft && !reviewing && <main className="min-h-0 flex-1 overflow-y-auto p-4"><div className="mb-3 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-xl bg-neutral-900 p-3"><b className="block text-xl">{cards.length}</b>{t('Tarjetas')}</div><div className="rounded-xl bg-neutral-900 p-3"><b className="block text-xl text-amber-300">{cards.filter((card) => new Date(card.srs.dueAt) <= new Date() && !card.srs.mastered).length}</b>{t('Pendientes hoy')}</div><div className="rounded-xl bg-neutral-900 p-3"><b className="block text-xl text-emerald-300">{cards.filter((card) => card.srs.mastered).length}</b>{t('Dominadas')}</div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cards.map((card) => <article key={card.id} className="rounded-xl border border-neutral-800 bg-neutral-900/30 p-4"><div className="flex text-[10px] text-neutral-600"><span>{card.type}</span><span className="ml-auto">{card.srs.intervalDays < 1 ? t('Hoy') : `${card.srs.intervalDays} d`}</span></div><h2 className="mt-2 text-sm font-medium">{card.type === 'cloze' ? clozeStudyFlashcard(card.front).question : card.front}</h2><p className="mt-2 line-clamp-3 text-xs text-neutral-500">{card.back}</p><div className="mt-3 flex gap-1"><button className="btn btn-ghost h-7 text-[10px]" onClick={() => speak(`${card.front}. ${card.back}`)}><Icon name="volume" size={11} />{t('Escuchar')}</button><button className="btn btn-ghost h-7 text-[10px]" onClick={() => void window.nodus.setStudyFlashcardState(card.id, card.srs.mastered ? 'reset' : 'master').then(load)}>{t(card.srs.mastered ? 'Reactivar' : 'Marcar dominada')}</button></div></article>)}</div>{!cards.length && <div className="rounded-xl border border-dashed border-neutral-800 p-10 text-center text-sm text-neutral-600">{t('Crea tarjetas manualmente o conviértelas desde el banco de preguntas.')}</div>}</main>}
    {reviewing && <main className="flex min-h-0 flex-1 items-center justify-center overflow-y-auto p-6" data-testid="study-review-session"><div className="w-full max-w-2xl"><div className="mb-3 flex text-xs text-neutral-500"><span>{index + 1} / {sessionCards.length}</span><span className="ml-auto">{reviewed} {t('repasadas')}</span></div><button className="min-h-72 w-full rounded-2xl border border-teal-900/60 bg-teal-950/15 p-8 text-center" onClick={() => setRevealed(true)}><p className="text-xl leading-8">{displayed?.question}</p>{!revealed && <p className="mt-8 text-xs text-neutral-500">{t('Pulsa para mostrar la respuesta')}</p>}{revealed && <><div className="mx-auto my-6 h-px max-w-sm bg-neutral-800" /><p className="text-lg text-emerald-200">{displayed?.answer}</p>{current?.hint && <p className="mt-3 text-xs text-neutral-500">{current.hint}</p>}</>}</button>{revealed && <div className="mt-4 grid grid-cols-4 gap-2">{([{ rating: 1, label: 'Otra vez', color: 'text-red-300' }, { rating: 3, label: 'Difícil', color: 'text-amber-300' }, { rating: 4, label: 'Bien', color: 'text-teal-300' }, { rating: 5, label: 'Fácil', color: 'text-emerald-300' }] as const).map((item) => <button key={item.rating} data-testid={`study-review-rate-${item.rating}`} className={`rounded-xl border border-neutral-800 p-3 text-sm ${item.color}`} onClick={() => void rate(item.rating)}>{t(item.label)}</button>)}</div>}</div></main>}
  </div>;
}
