import { useCallback, useEffect, useRef, useState } from 'react';
import type { StudyPlannerSnapshot, StudyStudySession, StudyWorkspace } from '@shared/types';
import { Icon } from '../components/ui';
import { t } from '../i18n';

function localInputValue(date = new Date(Date.now() + 3_600_000)) { const offset = date.getTimezoneOffset() * 60_000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); }

export function StudyPlannerView() {
  const [snapshot, setSnapshot] = useState<StudyPlannerSnapshot | null>(null); const [workspace, setWorkspace] = useState<StudyWorkspace | null>(null);
  const [title, setTitle] = useState(''); const [startsAt, setStartsAt] = useState(localInputValue()); const [duration, setDuration] = useState(25); const [subjectId, setSubjectId] = useState('');
  const [kind, setKind] = useState<'block' | 'event' | 'goal'>('block'); const [activeSession, setActiveSession] = useState<StudyStudySession | null>(null); const [remaining, setRemaining] = useState(0); const startedAtRef = useRef(0); const [error, setError] = useState('');
  const load = useCallback(async () => { const [next, nextWorkspace] = await Promise.all([window.nodus.getStudyPlanner(), window.nodus.getStudyWorkspace()]); setSnapshot(next); setWorkspace(nextWorkspace); }, []);
  useEffect(() => { void load().catch((cause) => setError(cause instanceof Error ? cause.message : String(cause))); }, [load]);
  useEffect(() => { if (!activeSession || remaining <= 0) return; const timer = window.setInterval(() => setRemaining((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [activeSession, remaining]);
  const create = async () => { if (!title.trim()) return; try { if (kind === 'block') await window.nodus.createStudyPlanBlock({ title, startsAt: new Date(startsAt).toISOString(), durationMinutes: duration, subjectId: subjectId || null }); else if (kind === 'event') await window.nodus.createStudyCalendarEvent({ title, type: 'exam', startsAt: new Date(startsAt).toISOString(), subjectId: subjectId || null, reminderMinutes: 60 }); else await window.nodus.createStudyGoal({ title, period: 'weekly', targetValue: duration, unit: 'minutos', subjectId: subjectId || null }); setTitle(''); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } };
  const start = async (blockId?: string, minutes = 25) => { const block = snapshot?.blocks.find((item) => item.id === blockId); const session = await window.nodus.startStudySession({ planBlockId: blockId ?? null, subjectId: block?.subjectId ?? (subjectId || null), topicId: block?.topicId ?? null, mode: 'pomodoro', plannedMinutes: minutes }); startedAtRef.current = Date.now(); setActiveSession(session); setRemaining(minutes * 60); };
  const finish = async () => { if (!activeSession) return; await window.nodus.finishStudySession(activeSession.id, { actualSeconds: Math.round((Date.now() - startedAtRef.current) / 1000) }); setActiveSession(null); setRemaining(0); await load(); };
  const upcoming = [...(snapshot?.blocks ?? []), ...(snapshot?.events ?? [])].sort((a, b) => a.startsAt.localeCompare(b.startsAt));
  return <div className="flex h-full min-h-0 flex-col" data-testid="study-planner-view"><header className="border-b border-neutral-800 px-4 py-3"><div className="flex flex-wrap items-center gap-2"><div className="mr-auto"><p className="text-[10px] uppercase tracking-[0.18em] text-teal-400">{t('Organización académica')}</p><h1 className="text-xl font-semibold">{t('Planificador de estudio')}</h1></div><button className="btn btn-ghost" onClick={() => void window.nodus.exportStudyPlannerIcs()}><Icon name="download" />{t('Exportar .ics')}</button><button data-testid="study-pomodoro-quick" className="btn btn-primary" disabled={Boolean(activeSession)} onClick={() => void start(undefined, 25)}>{t('Pomodoro 25 min')}</button></div></header>
    {error && <div className="m-4 rounded-lg border border-red-900 p-3 text-xs text-red-300">{error}</div>}
    {activeSession && <section className="mx-4 mt-4 flex items-center rounded-xl border border-teal-800 bg-teal-950/25 p-4" data-testid="study-pomodoro-active"><span className="rounded-lg bg-teal-900/50 p-2"><Icon name="timer" /></span><div className="ml-3"><p className="text-xs text-teal-300">{t('Sesión de concentración')}</p><b className="font-mono text-2xl">{String(Math.floor(remaining / 60)).padStart(2, '0')}:{String(remaining % 60).padStart(2, '0')}</b></div><button className="btn btn-primary ml-auto" onClick={() => void finish()}>{t('Finalizar y registrar')}</button></section>}
    <main className="grid min-h-0 flex-1 gap-4 overflow-y-auto p-4 lg:grid-cols-[minmax(300px,0.8fr)_minmax(420px,1.4fr)]"><section><div className="rounded-xl border border-neutral-800 bg-neutral-900/30 p-4" data-testid="study-planner-create"><h2 className="text-sm font-semibold">{t('Añadir al plan')}</h2><div className="mt-3 grid grid-cols-3 gap-1">{(['block', 'event', 'goal'] as const).map((value) => <button key={value} className={`rounded-lg px-2 py-2 text-xs ${kind === value ? 'bg-teal-900/50 text-teal-200' : 'bg-neutral-900 text-neutral-500'}`} onClick={() => setKind(value)}>{t(value === 'block' ? 'Bloque' : value === 'event' ? 'Fecha clave' : 'Objetivo')}</button>)}</div><input data-testid="study-planner-title" className="input mt-3 w-full" value={title} onChange={(event) => setTitle(event.target.value)} placeholder={t('Título')} />{kind !== 'goal' && <input className="input mt-2 w-full" type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} />}<select className="input mt-2 w-full" value={subjectId} onChange={(event) => setSubjectId(event.target.value)}><option value="">{t('Sin asignatura')}</option>{workspace?.subjects.map((subject) => <option key={subject.id} value={subject.id}>{subject.name}</option>)}</select><label className="mt-2 block text-xs text-neutral-500">{kind === 'goal' ? t('Meta en minutos') : t('Duración en minutos')}<input className="input mt-1 w-full" type="number" min="1" value={duration} onChange={(event) => setDuration(Number(event.target.value))} /></label><button data-testid="study-planner-save" className="btn btn-primary mt-3 w-full" disabled={!title.trim()} onClick={() => void create()}>{t('Guardar')}</button></div>
      <div className="mt-4 rounded-xl border border-neutral-800 p-4"><h2 className="text-sm font-semibold">{t('Objetivos')}</h2><div className="mt-3 space-y-2">{snapshot?.goals.map((goal) => <label key={goal.id} className="flex items-center rounded-lg bg-neutral-900/50 px-3 py-2 text-xs"><input type="checkbox" checked={goal.completed} onChange={(event) => void window.nodus.updateStudyPlannerItem('goal', goal.id, { completed: event.target.checked, currentValue: event.target.checked ? goal.targetValue : 0 }).then(load)} /><span className="ml-2">{goal.title}</span><span className="ml-auto text-neutral-500">{goal.currentValue}/{goal.targetValue} {goal.unit}</span></label>)}</div></div></section>
      <section className="rounded-xl border border-neutral-800 p-4"><h2 className="text-sm font-semibold">{t('Próximas sesiones y fechas')}</h2><div className="mt-3 space-y-2">{upcoming.map((item) => { const block = 'durationMinutes' in item; return <article key={item.id} className="flex items-center rounded-xl border border-neutral-800 bg-neutral-900/30 p-3"><span className={`rounded-lg p-2 ${block ? 'bg-teal-950 text-teal-300' : 'bg-amber-950 text-amber-300'}`}><Icon name={block ? 'timer' : 'calendar'} /></span><div className="ml-3 min-w-0"><h3 className="truncate text-sm">{item.title}</h3><p className="text-[10px] text-neutral-600">{new Date(item.startsAt).toLocaleString()} {block ? `· ${item.durationMinutes} min` : ''}</p></div>{block && <><button className="btn btn-ghost ml-auto h-8 text-xs" onClick={() => void start(item.id, item.durationMinutes)}>{t('Iniciar')}</button><button className="btn btn-ghost h-8 text-xs" onClick={() => void window.nodus.updateStudyPlannerItem('block', item.id, { status: 'completed' }).then(load)}>✓</button></>}</article>; })}{!upcoming.length && <div className="rounded-lg border border-dashed border-neutral-800 p-8 text-center text-xs text-neutral-600">{t('Añade una sesión, un examen o un objetivo para empezar.')}</div>}</div><div className="mt-5 border-t border-neutral-800 pt-4"><h3 className="text-xs font-semibold uppercase tracking-wider text-neutral-600">{t('Tiempo registrado')}</h3><p className="mt-2 text-2xl">{Math.round((snapshot?.sessions.reduce((sum, session) => sum + session.actualSeconds, 0) ?? 0) / 60)} min</p></div></section></main>
  </div>;
}
