import { useEffect, useState } from 'react';
import type { StudyProgressDashboard } from '@shared/types';
import { Icon } from '../components/ui';
import { t } from '../i18n';

function MasteryBar({ value }: { value: number }) { return <div className="h-2 overflow-hidden rounded-full bg-neutral-800"><div className="h-full rounded-full bg-gradient-to-r from-amber-500 to-teal-500" style={{ width: `${value}%` }} /></div>; }

export function StudyProgressView({ onOpenReview, onOpenPlanner }: { onOpenReview: () => void; onOpenPlanner: () => void }) {
  const [dashboard, setDashboard] = useState<StudyProgressDashboard | null>(null); const [hidden, setHidden] = useState(false); const [error, setError] = useState('');
  useEffect(() => { void window.nodus.getStudyProgressDashboard().then(setDashboard).catch((cause) => setError(cause instanceof Error ? cause.message : String(cause))); }, []);
  if (hidden) return <div className="flex h-full items-center justify-center"><button className="btn btn-primary" onClick={() => setHidden(false)}>{t('Mostrar mis métricas')}</button></div>;
  return <div className="h-full overflow-y-auto p-5" data-testid="study-progress-view"><div className="mx-auto max-w-6xl space-y-5">
    <header className="flex flex-wrap items-center gap-2"><div className="mr-auto"><p className="text-[10px] uppercase tracking-[0.18em] text-teal-400">{t('Seguimiento local')}</p><h1 className="text-xl font-semibold">{t('Progreso de aprendizaje')}</h1></div><button className="btn btn-ghost" onClick={() => setHidden(true)}><Icon name="eyeOff" />{t('Ocultar métricas')}</button><button className="btn btn-secondary" onClick={onOpenPlanner}>{t('Ajustar plan')}</button><button className="btn btn-primary" onClick={onOpenReview}>{t('Repasar puntos débiles')}</button></header>
    {error && <div className="rounded-lg border border-red-900 p-3 text-xs text-red-300">{error}</div>}
    {dashboard && <>
      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div className="rounded-xl border border-neutral-800 bg-neutral-900/30 p-4"><span className="text-xs text-neutral-500">{t('Dominio estimado')}</span><b className="mt-2 block text-3xl text-teal-300">{dashboard.overall.mastery}%</b><MasteryBar value={dashboard.overall.mastery} /></div><div className="rounded-xl border border-neutral-800 p-4"><span className="text-xs text-neutral-500">{t('Precisión')}</span><b className="mt-2 block text-3xl">{dashboard.overall.accuracy == null ? '—' : `${Math.round(dashboard.overall.accuracy * 100)}%`}</b></div><div className="rounded-xl border border-neutral-800 p-4"><span className="text-xs text-neutral-500">{t('Evidencias')}</span><b className="mt-2 block text-3xl">{dashboard.overall.attempts + dashboard.overall.reviews}</b></div><div className="rounded-xl border border-neutral-800 p-4"><span className="text-xs text-neutral-500">{t('Repasos pendientes')}</span><b className="mt-2 block text-3xl text-amber-300">{dashboard.dueCards}</b></div><div className="rounded-xl border border-neutral-800 p-4"><span className="text-xs text-neutral-500">{t('Tiempo real / plan')}</span><b className="mt-2 block text-xl">{dashboard.actualMinutes} / {dashboard.plannedMinutes} min</b></div></section>
      <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-neutral-800 p-4"><h2 className="text-sm font-semibold">{t('Rendimiento por asignatura')}</h2><div className="mt-4 space-y-4">{dashboard.bySubject.map((scope) => <div key={scope.id}><div className="mb-1 flex text-xs"><span>{scope.name}</span><span className="ml-auto text-neutral-500">{scope.mastery}% · {scope.attempts + scope.reviews} {t('evidencias')}</span></div><MasteryBar value={scope.mastery} /></div>)}{!dashboard.bySubject.length && <p className="text-xs text-neutral-600">{t('Aún no hay asignaturas con actividad.')}</p>}</div></div><div className="rounded-xl border border-neutral-800 p-4"><h2 className="text-sm font-semibold">{t('Temas que requieren atención')}</h2><div className="mt-3 space-y-2">{[...dashboard.byTopic].sort((a, b) => a.mastery - b.mastery).slice(0, 8).map((scope) => <div key={scope.id} className="flex items-center rounded-lg bg-neutral-900/50 px-3 py-2 text-xs"><span>{scope.name}</span><span className={`ml-auto ${scope.status === 'problematic' ? 'text-red-300' : 'text-amber-300'}`}>{scope.mastery}% · {t(scope.status)}</span></div>)}</div></div></section>
      <section className="rounded-xl border border-teal-900/50 bg-teal-950/15 p-4"><h2 className="text-sm font-semibold text-teal-200">{t('Recomendaciones basadas en evidencia')}</h2><ul className="mt-2 space-y-2 text-sm text-neutral-300">{dashboard.recommendations.map((item) => <li key={item} className="flex gap-2"><Icon name="sparkles" size={13} className="mt-1 text-teal-400" />{item}</li>)}</ul><p className="mt-4 text-[10px] text-neutral-600">{t('Estas métricas se calculan localmente a partir de tests, repasos y sesiones registradas.')}</p></section>
    </>}
  </div></div>;
}
