// Subtitle translations for the tutorial narration.
//
// These are narration, not interface copy, so they live here instead of the app's
// i18n tables — adding them there would drag them into the i18n coverage contract
// and make every future voice-over tweak a translation emergency across the UI.
//
// English is not listed: it is the spoken language and is read straight from
// shots.mjs, so the script and its subtitles can never disagree.
//
// The language list is the twelve the cinematic tutorial offered, since this video
// replaces it. `youtube` is the BCP-47 tag YouTube expects when the caption file is
// uploaded — notably `zh-Hans` rather than a bare `zh`.
//
// A language with no entry falls back to English *and is reported* by
// subtitles.mjs; a half-translated file must never look finished.

export const LANGUAGES = [
  { code: 'es', label: 'Español', youtube: 'es' },
  { code: 'en', label: 'English', youtube: 'en' },
  { code: 'fr', label: 'Français', youtube: 'fr' },
  { code: 'tr', label: 'Türkçe', youtube: 'tr' },
  { code: 'de', label: 'Deutsch', youtube: 'de' },
  { code: 'it', label: 'Italiano', youtube: 'it' },
  { code: 'pt', label: 'Português', youtube: 'pt-PT' },
  { code: 'pt-BR', label: 'Português do Brasil', youtube: 'pt-BR' },
  { code: 'zh', label: '中文', youtube: 'zh-Hans' },
  { code: 'ja', label: '日本語', youtube: 'ja' },
  { code: 'ru', label: 'Русский', youtube: 'ru' },
  { code: 'uk', label: 'Українська', youtube: 'uk' },
];

/** Keyed by language, then by shot id. */
export const CAPTIONS = {
  es: {
    'welcome': 'Te damos la bienvenida a Nodus. Es un espacio de trabajo para tus documentos, notas y fuentes, hecho para mostrarte cómo se relacionan.',
    'local-first': 'Todo se guarda en tu propio equipo. Tu material solo sale de él cuando eliges una función que usa un servicio externo.',
    'tour-plan': 'En los próximos minutos veremos las bóvedas, los modelos de IA que Nodus necesita y las herramientas construidas alrededor.',
    'vault-concept': 'Todo empieza con una bóveda. Una bóveda es un espacio de trabajo independiente que mantiene junto un proyecto.',
    'vault-open-types': 'Al crear una, Nodus te pregunta para qué tipo de trabajo es, y esa elección da forma a toda la bóveda.',
    'vault-academic': 'Académica es para investigar: bibliografía desde Zotero, ideas extraídas, autores y relaciones.',
    'vault-study': 'Estudio es para aprender: cursos, asignaturas, apuntes, materiales y repaso.',
    'vault-teaching': 'Docencia es para el otro lado del aula: tus propios cursos, horarios, materiales y calificaciones.',
    'vault-databases': 'Bases de datos es para información estructurada: tablas tipadas, relaciones entre ellas y análisis.',
    'vault-genealogy': 'Genealogía es para la historia familiar: personas, parentescos, cronologías y evidencias documentales.',
    'vault-more': 'Vendrán más, y las etiquetas te dicen cuáles están todavía en beta o en vista previa.',
    'vault-isolation': 'Cada bóveda conserva su propia biblioteca, sus notas y sus ajustes, así que dos proyectos nunca se mezclan.',
    'sidebar': 'Dentro de una bóveda te mueves por la barra lateral. Sus secciones se agrupan según lo que estés haciendo: explorar, analizar y crear.',
    'library-intro': 'La Biblioteca guarda tus fuentes. Según la bóveda, llegan desde Zotero, desde tus propios archivos o desde lo que grabes.',
    'library-scan': 'Cada elemento muestra hasta dónde lo ha leído Nodus. Un escaneo ligero encuentra temas; uno profundo extrae ideas junto con su evidencia.',
    'library-analyse': 'Tú eliges qué se analiza y cuándo. No se procesa nada si no lo pides.',
    'ideas-intro': 'Lo que extrae ese escaneo profundo aparece aquí, como ideas sueltas en lugar de documentos enteros.',
    'ideas-open': 'Abre una y tendrás su panorama completo.',
    'ideas-evidence': 'Su tipo, la fuente de la que procede y el pasaje exacto que la sostiene.',
    'ideas-trust': 'Esa última parte es la importante: confía en una idea solo cuando hayas leído la evidencia que la respalda.',
    'graph-intro': 'El grafo convierte esas ideas en un paisaje. Cada nodo es una idea y cada enlace una relación entre ellas.',
    'graph-reading': 'Los grupos muestran dónde coinciden tus fuentes. Los puentes entre grupos suelen ser los lugares más interesantes.',
    'models-why': 'Nada de eso ocurre solo. Nodus no trae inteligencia propia: tú eliges qué modelos de IA usa, y este es el paso de configuración que más importa.',
    'models-basic': 'Hay dos formas de configurarlos. La configuración básica usa un único modelo general para todo, y es el sitio adecuado para empezar.',
    'models-advanced': 'La configuración avanzada asigna un modelo distinto a cada tarea. Resulta útil más adelante, cuando ya sabes qué partes quieres afinar.',
    'models-providers': 'Los modelos vienen de proveedores. Añades uno con su clave de API, y Nodus guarda esa clave cifrada en tu equipo.',
    'models-openrouter': 'OpenRouter es un buen punto de partida, porque una sola clave te da modelos de muchas empresas distintas.',
    'models-catalogue': 'Una vez conectado un proveedor, todo su catálogo queda disponible en cada selector de modelos de Nodus.',
    'extraction-intro': 'Dos consejos sobre el modelo que extrae las ideas, porque deciden si Nodus se siente rápido o se siente roto.',
    'extraction-api': 'Primero, prefiere un modelo accesible por API. La extracción lee tus documentos por fragmentos, y un modelo remoto hace en segundos lo que uno local tarda minutos.',
    'extraction-thinking': 'Segundo, no uses un modelo de razonamiento para extraer. Los modelos que «piensan» gastan su presupuesto deliberando y a menudo no devuelven nada aprovechable; uno sencillo y rápido es mejor opción.',
    'extraction-recommend': 'Tras muchas pruebas, los modelos Gemini Flash Lite dieron el mejor equilibrio de velocidad, coste y resultados fiables para esta tarea concreta.',
    'local-models': 'Nodus también puede ejecutar modelos en tu propio equipo, sin que nada salga de tu ordenador.',
    'local-kinds': 'Hay uno para conversar, uno para transcribir audio, uno para generar imágenes y otro para embeddings. Cada uno se descarga solo si lo quieres.',
    'local-tradeoff': 'Son privados y gratuitos, pero más lentos, y necesitan un equipo capaz. Un buen término medio: modelos locales para el chat diario y una API para el análisis pesado.',
    'embeddings-what': 'Y ahora el ajuste que casi todo el mundo pasa por alto: el modelo de embeddings, que construye un índice semántico de tu material.',
    'embeddings-why': 'Ese índice es lo que te permite buscar por significado en lugar de por palabras exactas, y lo que encuentra las relaciones y los puentes entre tus ideas.',
    'embeddings-warning': 'Sin él, la búsqueda semántica sencillamente no devuelve nada, y entonces un resultado vacío significa que la bóveda nunca se indexó, no que tus fuentes no traten el tema.',
    'embeddings-recommend': 'La recomendación es BGE M3. Funciona en local, maneja pasajes largos y trabaja entre idiomas, algo que importa cuando tus fuentes no están todas en el mismo.',
    'images': 'Más allá del texto, Nodus lee imágenes y puede generarlas, lo que ayuda con figuras, diagramas y páginas escaneadas.',
    'audio': 'También transcribe grabaciones y lee tu material en voz alta, así puedes escuchar un documento largo en lugar de leerlo.',
    'toolkit': 'El Toolkit reúne las herramientas prácticas: convertir archivos, proteger documentos, traducir, un modo presentación y un espacio de OCR.',
    'mcp-intro': 'Nodus también puede abrirse a otros programas. El servidor MCP permite que un asistente de IA lea esta bóveda directamente.',
    'mcp-how': 'Escucha solo en tu propio equipo, así que un asistente puede buscar en tus fuentes, leer tus notas y citarlas sin que tu biblioteca se publique en ningún sitio.',
    'server-intro': 'Nodus Server hace algo distinto: mantiene al día una copia filtrada de una bóveda a través de una conexión saliente.',
    'server-how': 'Así llegas a la misma bóveda desde otro dispositivo o la compartes con alguien, sin abrir ningún puerto en tu equipo.',
    'plugins': 'También hay complementos para los sitios donde ya trabajas: Zotero, Microsoft Word y LibreOffice.',
    'nodi-settings': 'Por último, aquí no estás solo. Nodi es el acompañante que flota en la esquina, y puedes elegir su aspecto.',
    'nodi-meet': 'Este es Nodi.',
    'nodi-open': 'Haz clic y tendrás un chat que conoce tanto la aplicación como tu propio material, además de tus notificaciones y ayuda cuando la necesites.',
    'first-setup': 'Una forma segura de empezar es hacerlo poco a poco. Crea una bóveda, conecta un proveedor, elige un modelo de embeddings y analiza un puñado de documentos que ya conozcas bien.',
    'closing': 'Esto es Nodus. Comprueba la evidencia, mantén tuyo tu material y deja que el grafo crezca con tu lectura.',
  },

  fr: {
    'welcome': 'Bienvenue dans Nodus. C’est un espace de travail pour vos documents, vos notes et vos sources, conçu pour montrer comment ils se relient.',
    'local-first': 'Tout est stocké sur votre propre ordinateur. Votre matériel n’en sort que si vous choisissez une fonction qui utilise un service externe.',
    'tour-plan': 'Dans les prochaines minutes, nous verrons les coffres, les modèles d’IA dont Nodus a besoin et les outils construits autour.',
    'vault-concept': 'Tout commence par un coffre. Un coffre est un espace de travail distinct qui garde un projet d’un seul tenant.',
    'vault-open-types': 'Quand vous en créez un, Nodus demande à quel type de travail il est destiné, et ce choix façonne tout le coffre.',
    'vault-academic': 'Académique, c’est pour la recherche : une bibliographie depuis Zotero, des idées extraites, des auteurs et des relations.',
    'vault-study': 'Étude, c’est pour apprendre : cours, matières, notes, supports et révisions.',
    'vault-teaching': 'Enseignement, c’est l’autre côté de la salle de classe : vos propres cours, emplois du temps, supports et notation.',
    'vault-databases': 'Bases de données, c’est pour l’information structurée : des tableaux typés, des relations entre eux et de l’analyse.',
    'vault-genealogy': 'Généalogie, c’est pour l’histoire familiale : personnes, parentés, chronologies et preuves documentaires.',
    'vault-more': 'D’autres arrivent, et les badges indiquent lesquels sont encore en bêta ou en aperçu.',
    'vault-isolation': 'Chaque coffre garde sa propre bibliothèque, ses notes et ses réglages : deux projets ne se mélangent jamais.',
    'sidebar': 'Dans un coffre, vous naviguez par la barre latérale. Ses sections sont regroupées selon ce que vous faites : explorer, analyser et créer.',
    'library-intro': 'La Bibliothèque contient vos sources. Selon le coffre, elles viennent de Zotero, de vos propres fichiers ou de ce que vous enregistrez.',
    'library-scan': 'Chaque élément montre jusqu’où Nodus l’a lu. Une passe légère trouve les thèmes ; une passe approfondie extrait les idées avec leurs preuves.',
    'library-analyse': 'Vous choisissez ce qui est analysé et quand. Rien n’est traité sans votre demande.',
    'ideas-intro': 'Ce que cette passe approfondie extrait apparaît ici, sous forme d’idées individuelles plutôt que de documents entiers.',
    'ideas-open': 'Ouvrez-en une et vous en avez le tableau complet.',
    'ideas-evidence': 'Son type, la source dont elle provient et le passage exact qui l’appuie.',
    'ideas-trust': 'C’est ce dernier point qui compte : ne faites confiance à une idée qu’après avoir lu la preuve qui la soutient.',
    'graph-intro': 'Le graphe transforme ces idées en paysage. Chaque nœud est une idée et chaque lien une relation entre elles.',
    'graph-reading': 'Les regroupements montrent où vos sources s’accordent. Les ponts entre eux sont souvent les endroits les plus intéressants.',
    'models-why': 'Rien de tout cela ne se fait tout seul. Nodus n’apporte pas d’intelligence propre : vous choisissez les modèles d’IA qu’il utilise, et c’est l’étape de configuration la plus importante.',
    'models-basic': 'Il y a deux façons de les configurer. La configuration de base utilise un seul modèle général pour tout, et c’est par là qu’il faut commencer.',
    'models-advanced': 'La configuration avancée attribue un modèle différent à chaque tâche. Utile plus tard, quand vous savez ce que vous voulez affiner.',
    'models-providers': 'Les modèles viennent de fournisseurs. Vous en ajoutez un avec sa clé d’API, et Nodus conserve cette clé chiffrée sur votre machine.',
    'models-openrouter': 'OpenRouter est un bon point de départ, car une seule clé vous donne des modèles de nombreuses entreprises différentes.',
    'models-catalogue': 'Une fois un fournisseur connecté, tout son catalogue devient disponible dans chaque sélecteur de modèle de Nodus.',
    'extraction-intro': 'Deux conseils sur le modèle qui extrait les idées, car ils décident si Nodus paraît rapide ou paraît cassé.',
    'extraction-api': 'D’abord, préférez un modèle accessible par API. L’extraction lit vos documents par morceaux, et un modèle distant fait en secondes ce qu’un modèle local met des minutes à faire.',
    'extraction-thinking': 'Ensuite, n’utilisez pas de modèle de raisonnement pour l’extraction. Les modèles qui « réfléchissent » dépensent leur budget à délibérer et ne renvoient souvent rien d’exploitable ; un modèle simple et rapide est préférable.',
    'extraction-recommend': 'Après de nombreux tests, les modèles Gemini Flash Lite ont donné le meilleur équilibre entre vitesse, coût et résultats fiables pour cette tâche précise.',
    'local-models': 'Nodus peut aussi exécuter des modèles sur votre propre machine, sans que rien ne quitte votre ordinateur.',
    'local-kinds': 'Il y en a un pour la conversation, un pour transcrire l’audio, un pour générer des images et un pour les embeddings. Chacun ne se télécharge que si vous le voulez.',
    'local-tradeoff': 'Ils sont privés et gratuits, mais plus lents, et exigent un ordinateur capable. Un bon compromis : des modèles locaux pour le chat quotidien et une API pour l’analyse lourde.',
    'embeddings-what': 'Et maintenant le réglage que la plupart des gens négligent : le modèle d’embeddings, qui construit un index sémantique de votre matériel.',
    'embeddings-why': 'Cet index permet de chercher par le sens plutôt que par les mots exacts, et c’est lui qui trouve les relations et les ponts entre vos idées.',
    'embeddings-warning': 'Sans lui, la recherche sémantique ne renvoie tout simplement rien — et un résultat vide signifie alors que le coffre n’a jamais été indexé, non que vos sources ignorent le sujet.',
    'embeddings-recommend': 'La recommandation est BGE M3. Il fonctionne en local, gère les longs passages et travaille entre les langues, ce qui compte quand vos sources ne sont pas toutes dans la même.',
    'images': 'Au-delà du texte, Nodus lit les images et peut en générer, ce qui aide pour les figures, les schémas et les pages numérisées.',
    'audio': 'Il transcrit aussi les enregistrements et lit votre matériel à voix haute, pour écouter un long document au lieu de le lire.',
    'toolkit': 'Le Toolkit réunit les outils pratiques : conversion de fichiers, protection de documents, traduction, un mode présentation et un espace d’OCR.',
    'mcp-intro': 'Nodus peut aussi s’ouvrir à d’autres logiciels. Le serveur MCP permet à un assistant IA de lire ce coffre directement.',
    'mcp-how': 'Il n’écoute que sur votre propre ordinateur : un assistant peut donc chercher dans vos sources, lire vos notes et les citer, sans que votre bibliothèque soit publiée nulle part.',
    'server-intro': 'Nodus Server fait autre chose : il maintient à jour une copie filtrée d’un coffre via une connexion sortante.',
    'server-how': 'C’est ainsi que vous atteignez le même coffre depuis un autre appareil ou que vous le partagez, sans ouvrir le moindre port sur votre machine.',
    'plugins': 'Il existe aussi des extensions pour les endroits où vous travaillez déjà : Zotero, Microsoft Word et LibreOffice.',
    'nodi-settings': 'Enfin, vous n’êtes pas seul ici. Nodi est le compagnon qui flotte dans le coin, et vous pouvez choisir son apparence.',
    'nodi-meet': 'Voici Nodi.',
    'nodi-open': 'Cliquez dessus et vous obtenez un chat qui connaît à la fois l’application et votre propre matériel, ainsi que vos notifications et de l’aide au besoin.',
    'first-setup': 'Une façon sûre de commencer, c’est de commencer petit. Créez un coffre, connectez un fournisseur, choisissez un modèle d’embeddings et analysez quelques documents que vous connaissez bien.',
    'closing': 'Voilà Nodus. Vérifiez les preuves, gardez votre matériel chez vous, et laissez le graphe grandir avec vos lectures.',
  },

  de: {
    'welcome': 'Willkommen bei Nodus. Es ist ein Arbeitsbereich für Ihre Dokumente, Notizen und Quellen, gebaut, um zu zeigen, wie sie zusammenhängen.',
    'local-first': 'Alles wird auf Ihrem eigenen Rechner gespeichert. Ihr Material verlässt ihn nur, wenn Sie eine Funktion wählen, die einen externen Dienst nutzt.',
    'tour-plan': 'In den nächsten Minuten sehen wir uns Vaults an, die KI-Modelle, die Nodus braucht, und die Werkzeuge darum herum.',
    'vault-concept': 'Alles beginnt mit einem Vault. Ein Vault ist ein eigenständiger Arbeitsbereich, der ein Projekt zusammenhält.',
    'vault-open-types': 'Beim Anlegen fragt Nodus, für welche Art von Arbeit er gedacht ist — und diese Wahl prägt den gesamten Vault.',
    'vault-academic': 'Akademisch ist für die Forschung: eine Bibliografie aus Zotero, extrahierte Ideen, Autoren und Beziehungen.',
    'vault-study': 'Studium ist fürs Lernen: Kurse, Fächer, Notizen, Materialien und Wiederholung.',
    'vault-teaching': 'Lehre ist die andere Seite des Klassenzimmers: Ihre eigenen Kurse, Stundenpläne, Materialien und Bewertungen.',
    'vault-databases': 'Datenbanken ist für strukturierte Information: typisierte Tabellen, Beziehungen zwischen ihnen und Auswertung.',
    'vault-genealogy': 'Genealogie ist für Familiengeschichte: Personen, Verwandtschaft, Zeitleisten und dokumentarische Belege.',
    'vault-more': 'Weitere kommen, und die Kennzeichen zeigen, welche noch in Beta oder Vorschau sind.',
    'vault-isolation': 'Jeder Vault behält seine eigene Bibliothek, seine Notizen und seine Einstellungen, sodass sich zwei Projekte nie vermischen.',
    'sidebar': 'Innerhalb eines Vaults bewegen Sie sich über die Seitenleiste. Ihre Bereiche sind danach gruppiert, was Sie gerade tun: erkunden, analysieren und erstellen.',
    'library-intro': 'Die Bibliothek enthält Ihre Quellen. Je nach Vault kommen sie aus Zotero, aus Ihren eigenen Dateien oder aus dem, was Sie aufnehmen.',
    'library-scan': 'Jeder Eintrag zeigt, wie weit Nodus ihn gelesen hat. Ein leichter Durchgang findet Themen; ein tiefer extrahiert Ideen samt ihrer Belege.',
    'library-analyse': 'Sie wählen, was analysiert wird und wann. Nichts wird verarbeitet, ohne dass Sie es verlangen.',
    'ideas-intro': 'Was dieser tiefe Durchgang herausarbeitet, erscheint hier — als einzelne Ideen statt als ganze Dokumente.',
    'ideas-open': 'Öffnen Sie eine, und Sie haben das vollständige Bild davon.',
    'ideas-evidence': 'Ihr Typ, die Quelle, aus der sie stammt, und die genaue Textstelle, die sie stützt.',
    'ideas-trust': 'Der letzte Punkt ist der wichtige: Vertrauen Sie einer Idee erst, wenn Sie den Beleg dahinter gelesen haben.',
    'graph-intro': 'Der Graph macht aus diesen Ideen eine Landschaft. Jeder Knoten ist eine Idee, jede Kante eine Beziehung zwischen ihnen.',
    'graph-reading': 'Cluster zeigen, wo Ihre Quellen übereinstimmen. Die Brücken dazwischen sind oft die interessantesten Stellen.',
    'models-why': 'Nichts davon geschieht von allein. Nodus bringt keine eigene Intelligenz mit — Sie wählen, welche KI-Modelle es nutzt, und das ist der wichtigste Einrichtungsschritt.',
    'models-basic': 'Es gibt zwei Wege, sie einzurichten. Die einfache Konfiguration nutzt ein allgemeines Modell für alles, und dort sollte man anfangen.',
    'models-advanced': 'Die erweiterte Konfiguration weist jeder Aufgabe ein eigenes Modell zu. Nützlich später, wenn Sie wissen, was Sie feinjustieren wollen.',
    'models-providers': 'Modelle kommen von Anbietern. Sie fügen einen mit seinem API-Schlüssel hinzu, und Nodus bewahrt diesen Schlüssel verschlüsselt auf Ihrem Rechner auf.',
    'models-openrouter': 'OpenRouter ist ein guter Anfang, denn ein einziger Schlüssel gibt Ihnen Modelle vieler verschiedener Anbieter.',
    'models-catalogue': 'Sobald ein Anbieter verbunden ist, steht sein gesamter Katalog in jedem Modellauswahlfeld von Nodus zur Verfügung.',
    'extraction-intro': 'Zwei Ratschläge zum Modell, das die Ideen extrahiert — sie entscheiden, ob Nodus schnell wirkt oder kaputt.',
    'extraction-api': 'Erstens: Bevorzugen Sie ein Modell über eine API. Die Extraktion liest Ihre Dokumente in Abschnitten, und ein entferntes Modell schafft in Sekunden, wofür ein lokales Minuten braucht.',
    'extraction-thinking': 'Zweitens: Nehmen Sie kein Reasoning-Modell für die Extraktion. Denkende Modelle verbrauchen ihr Budget mit Abwägen und liefern oft nichts Brauchbares; ein schlichtes, schnelles Modell ist hier besser.',
    'extraction-recommend': 'Nach vielen Tests boten die Gemini-Flash-Lite-Modelle das beste Verhältnis aus Geschwindigkeit, Kosten und verlässlichen Ergebnissen für genau diese Aufgabe.',
    'local-models': 'Nodus kann Modelle auch auf Ihrem eigenen Rechner ausführen, ohne dass irgendetwas Ihren Computer verlässt.',
    'local-kinds': 'Es gibt eines fürs Chatten, eines für Transkription, eines für Bilder und eines für Embeddings. Jedes wird nur geladen, wenn Sie es wollen.',
    'local-tradeoff': 'Sie sind privat und kostenlos, aber langsamer und brauchen einen leistungsfähigen Rechner. Ein guter Kompromiss: lokale Modelle für den Alltag, eine API für schwere Analysen.',
    'embeddings-what': 'Und nun die Einstellung, die die meisten übersehen: das Embedding-Modell, das einen semantischen Index Ihres Materials aufbaut.',
    'embeddings-why': 'Dieser Index erlaubt die Suche nach Bedeutung statt nach exakten Wörtern, und er findet die Beziehungen und Brücken zwischen Ihren Ideen.',
    'embeddings-warning': 'Ohne ihn liefert die semantische Suche schlicht nichts — ein leeres Ergebnis heißt dann, dass der Vault nie indexiert wurde, nicht dass Ihre Quellen das Thema nicht behandeln.',
    'embeddings-recommend': 'Die Empfehlung lautet BGE M3. Es läuft lokal, kommt mit langen Passagen zurecht und arbeitet sprachübergreifend — wichtig, wenn Ihre Quellen nicht alle dieselbe Sprache haben.',
    'images': 'Über Text hinaus liest Nodus Bilder und kann sie erzeugen, was bei Abbildungen, Diagrammen und gescannten Seiten hilft.',
    'audio': 'Es transkribiert auch Aufnahmen und liest Ihr Material vor, sodass Sie ein langes Dokument hören können, statt es zu lesen.',
    'toolkit': 'Das Toolkit bündelt die praktischen Werkzeuge: Dateien konvertieren, Dokumente schützen, übersetzen, ein Präsentationsmodus und ein OCR-Arbeitsbereich.',
    'mcp-intro': 'Nodus kann sich auch anderer Software öffnen. Der MCP-Server lässt einen KI-Assistenten diesen Vault direkt lesen.',
    'mcp-how': 'Er lauscht nur auf Ihrem eigenen Rechner, sodass ein Assistent Ihre Quellen durchsuchen, Ihre Notizen lesen und zitieren kann, ohne dass Ihre Bibliothek irgendwo veröffentlicht wird.',
    'server-intro': 'Nodus Server macht etwas anderes: Er hält eine gefilterte Kopie eines Vaults über eine ausgehende Verbindung aktuell.',
    'server-how': 'So erreichen Sie denselben Vault von einem anderen Gerät oder teilen ihn mit jemandem, ohne dass auf Ihrem Rechner ein Port geöffnet wird.',
    'plugins': 'Außerdem gibt es Plugins für die Orte, an denen Sie ohnehin arbeiten: Zotero, Microsoft Word und LibreOffice.',
    'nodi-settings': 'Zuletzt: Sie sind hier nicht allein. Nodi ist der Begleiter, der in der Ecke schwebt, und Sie können sein Aussehen wählen.',
    'nodi-meet': 'Das ist Nodi.',
    'nodi-open': 'Ein Klick, und Sie bekommen einen Chat, der sowohl die App als auch Ihr eigenes Material kennt, dazu Ihre Benachrichtigungen und Hilfe, wenn Sie sie brauchen.',
    'first-setup': 'Ein sicherer Anfang ist ein kleiner. Legen Sie einen Vault an, verbinden Sie einen Anbieter, wählen Sie ein Embedding-Modell und analysieren Sie eine Handvoll Dokumente, die Sie gut kennen.',
    'closing': 'Das ist Nodus. Prüfen Sie die Belege, behalten Sie Ihr Material bei sich, und lassen Sie den Graphen mit Ihrer Lektüre wachsen.',
  },

  it: {
    'welcome': 'Benvenuto in Nodus. È uno spazio di lavoro per i tuoi documenti, appunti e fonti, pensato per mostrarti come si collegano.',
    'local-first': 'Tutto è salvato sul tuo computer. Il tuo materiale ne esce solo quando scegli una funzione che usa un servizio esterno.',
    'tour-plan': 'Nei prossimi minuti vedremo i vault, i modelli di IA di cui Nodus ha bisogno e gli strumenti costruiti attorno.',
    'vault-concept': 'Tutto comincia da un vault. Un vault è uno spazio di lavoro separato che tiene insieme un progetto.',
    'vault-open-types': 'Quando ne crei uno, Nodus chiede per che tipo di lavoro è, e quella scelta dà forma all’intero vault.',
    'vault-academic': 'Accademico è per la ricerca: bibliografia da Zotero, idee estratte, autori e relazioni.',
    'vault-study': 'Studio è per imparare: corsi, materie, appunti, materiali e ripasso.',
    'vault-teaching': 'Insegnamento è l’altro lato dell’aula: i tuoi corsi, gli orari, i materiali e le valutazioni.',
    'vault-databases': 'Database è per l’informazione strutturata: tabelle tipizzate, relazioni tra loro e analisi.',
    'vault-genealogy': 'Genealogia è per la storia familiare: persone, parentele, cronologie e prove documentarie.',
    'vault-more': 'Altri sono in arrivo, e le etichette indicano quali sono ancora in beta o in anteprima.',
    'vault-isolation': 'Ogni vault conserva la propria biblioteca, i propri appunti e le proprie impostazioni, così due progetti non si mescolano mai.',
    'sidebar': 'Dentro un vault ti muovi con la barra laterale. Le sezioni sono raggruppate per ciò che stai facendo: esplorare, analizzare e creare.',
    'library-intro': 'La Biblioteca contiene le tue fonti. A seconda del vault arrivano da Zotero, dai tuoi file o da ciò che registri.',
    'library-scan': 'Ogni elemento mostra fin dove Nodus l’ha letto. Una passata leggera trova i temi; una profonda estrae le idee con le prove che le sostengono.',
    'library-analyse': 'Scegli tu cosa analizzare e quando. Nulla viene elaborato se non lo chiedi.',
    'ideas-intro': 'Ciò che la passata profonda estrae compare qui, come singole idee anziché documenti interi.',
    'ideas-open': 'Aprine una e ne avrai il quadro completo.',
    'ideas-evidence': 'Il suo tipo, la fonte da cui proviene e il passo esatto che la sostiene.',
    'ideas-trust': 'Quest’ultimo punto è quello importante: fidati di un’idea solo dopo aver letto la prova che la sorregge.',
    'graph-intro': 'Il grafo trasforma quelle idee in un paesaggio. Ogni nodo è un’idea e ogni collegamento una relazione fra loro.',
    'graph-reading': 'I gruppi mostrano dove le tue fonti concordano. I ponti fra i gruppi sono spesso i punti più interessanti.',
    'models-why': 'Niente di tutto ciò accade da sé. Nodus non porta un’intelligenza propria: scegli tu quali modelli di IA usa, ed è il passo di configurazione che conta di più.',
    'models-basic': 'Ci sono due modi di configurarli. La configurazione base usa un solo modello generale per tutto, ed è il punto giusto da cui partire.',
    'models-advanced': 'La configurazione avanzata assegna un modello diverso a ogni compito. Utile più avanti, quando sai quali parti vuoi regolare.',
    'models-providers': 'I modelli vengono dai fornitori. Ne aggiungi uno con la sua chiave API, e Nodus la conserva cifrata sul tuo computer.',
    'models-openrouter': 'OpenRouter è un buon punto di partenza, perché una sola chiave ti dà modelli di molte aziende diverse.',
    'models-catalogue': 'Una volta collegato un fornitore, tutto il suo catalogo diventa disponibile in ogni selettore di modelli di Nodus.',
    'extraction-intro': 'Due consigli sul modello che estrae le idee, perché decidono se Nodus sembra rapido o sembra rotto.',
    'extraction-api': 'Primo, preferisci un modello raggiungibile via API. L’estrazione legge i documenti a blocchi, e un modello remoto fa in secondi ciò che uno locale impiega minuti a fare.',
    'extraction-thinking': 'Secondo, non usare un modello di ragionamento per l’estrazione. I modelli che “pensano” spendono il loro budget a deliberare e spesso non restituiscono nulla di utile; meglio uno semplice e veloce.',
    'extraction-recommend': 'Dopo molte prove, i modelli Gemini Flash Lite hanno dato il miglior equilibrio fra velocità, costo e risultati affidabili per questo compito specifico.',
    'local-models': 'Nodus può anche eseguire modelli sul tuo computer, senza che nulla lo lasci.',
    'local-kinds': 'Ce n’è uno per la chat, uno per trascrivere l’audio, uno per generare immagini e uno per gli embedding. Ognuno si scarica solo se lo vuoi.',
    'local-tradeoff': 'Sono privati e gratuiti, ma più lenti, e richiedono un computer capace. Un buon compromesso: modelli locali per la chat quotidiana e un’API per l’analisi pesante.',
    'embeddings-what': 'E ora l’impostazione che quasi tutti trascurano: il modello di embedding, che costruisce un indice semantico del tuo materiale.',
    'embeddings-why': 'Quell’indice è ciò che ti permette di cercare per significato invece che per parole esatte, ed è ciò che trova le relazioni e i ponti fra le tue idee.',
    'embeddings-warning': 'Senza di esso la ricerca semantica non restituisce nulla — e allora un risultato vuoto significa che il vault non è mai stato indicizzato, non che le tue fonti non trattino l’argomento.',
    'embeddings-recommend': 'La raccomandazione è BGE M3. Gira in locale, gestisce passaggi lunghi e lavora fra le lingue, cosa che conta quando le tue fonti non sono tutte nella stessa.',
    'images': 'Oltre al testo, Nodus legge le immagini e può generarle, utile per figure, diagrammi e pagine scansionate.',
    'audio': 'Trascrive anche le registrazioni e legge il tuo materiale ad alta voce, così puoi ascoltare un documento lungo invece di leggerlo.',
    'toolkit': 'Il Toolkit raccoglie gli strumenti pratici: convertire file, proteggere documenti, tradurre, una modalità presentazione e uno spazio OCR.',
    'mcp-intro': 'Nodus può anche aprirsi ad altri programmi. Il server MCP consente a un assistente IA di leggere direttamente questo vault.',
    'mcp-how': 'Ascolta solo sul tuo computer, così un assistente può cercare nelle tue fonti, leggere i tuoi appunti e citarli, senza che la tua biblioteca venga pubblicata da nessuna parte.',
    'server-intro': 'Nodus Server fa un’altra cosa: mantiene aggiornata una copia filtrata di un vault tramite una connessione in uscita.',
    'server-how': 'È così che raggiungi lo stesso vault da un altro dispositivo o lo condividi con qualcuno, senza aprire alcuna porta sul tuo computer.',
    'plugins': 'Ci sono anche plugin per i posti in cui già lavori: Zotero, Microsoft Word e LibreOffice.',
    'nodi-settings': 'Infine, qui non sei solo. Nodi è il compagno che fluttua nell’angolo, e puoi scegliere il suo aspetto.',
    'nodi-meet': 'Questo è Nodi.',
    'nodi-open': 'Fai clic e ottieni una chat che conosce sia l’app sia il tuo materiale, insieme alle notifiche e all’aiuto quando serve.',
    'first-setup': 'Un modo sicuro di iniziare è iniziare in piccolo. Crea un vault, collega un fornitore, scegli un modello di embedding e analizza pochi documenti che già conosci bene.',
    'closing': 'Questo è Nodus. Controlla le prove, tieni tuo il tuo materiale, e lascia che il grafo cresca con le tue letture.',
  },

  pt: {
    'welcome': 'Bem-vindo ao Nodus. É um espaço de trabalho para os seus documentos, notas e fontes, feito para mostrar como se relacionam.',
    'local-first': 'Tudo fica guardado no seu computador. O seu material só sai dele quando escolhe uma função que usa um serviço externo.',
    'tour-plan': 'Nos próximos minutos veremos os cofres, os modelos de IA de que o Nodus precisa e as ferramentas construídas à volta.',
    'vault-concept': 'Tudo começa com um cofre. Um cofre é um espaço de trabalho separado que mantém um projeto junto.',
    'vault-open-types': 'Ao criar um, o Nodus pergunta para que tipo de trabalho é, e essa escolha molda todo o cofre.',
    'vault-academic': 'Académico é para investigação: bibliografia a partir do Zotero, ideias extraídas, autores e relações.',
    'vault-study': 'Estudo é para aprender: cursos, disciplinas, apontamentos, materiais e revisão.',
    'vault-teaching': 'Docência é o outro lado da sala de aula: os seus cursos, horários, materiais e avaliação.',
    'vault-databases': 'Bases de dados é para informação estruturada: tabelas tipadas, relações entre elas e análise.',
    'vault-genealogy': 'Genealogia é para a história familiar: pessoas, parentescos, cronologias e provas documentais.',
    'vault-more': 'Estão a chegar mais, e as etiquetas indicam quais estão ainda em beta ou pré-visualização.',
    'vault-isolation': 'Cada cofre mantém a sua própria biblioteca, as suas notas e as suas definições, por isso dois projetos nunca se misturam.',
    'sidebar': 'Dentro de um cofre navega pela barra lateral. As secções estão agrupadas conforme o que está a fazer: explorar, analisar e criar.',
    'library-intro': 'A Biblioteca guarda as suas fontes. Consoante o cofre, vêm do Zotero, dos seus próprios ficheiros ou do que gravar.',
    'library-scan': 'Cada item mostra até onde o Nodus o leu. Uma passagem ligeira encontra temas; uma profunda extrai ideias com as provas que as sustentam.',
    'library-analyse': 'É você que escolhe o que é analisado e quando. Nada é processado sem o pedir.',
    'ideas-intro': 'O que essa passagem profunda extrai aparece aqui, como ideias individuais em vez de documentos inteiros.',
    'ideas-open': 'Abra uma e terá o quadro completo dela.',
    'ideas-evidence': 'O seu tipo, a fonte de onde veio e a passagem exata que a sustenta.',
    'ideas-trust': 'Essa última parte é a importante: confie numa ideia só depois de ler a prova que a apoia.',
    'graph-intro': 'O grafo transforma essas ideias numa paisagem. Cada nó é uma ideia e cada ligação uma relação entre elas.',
    'graph-reading': 'Os agrupamentos mostram onde as suas fontes concordam. As pontes entre eles são muitas vezes os sítios mais interessantes.',
    'models-why': 'Nada disto acontece sozinho. O Nodus não traz inteligência própria: é você que escolhe os modelos de IA que usa, e este é o passo de configuração que mais importa.',
    'models-basic': 'Há duas formas de os configurar. A configuração básica usa um único modelo geral para tudo, e é o sítio certo para começar.',
    'models-advanced': 'A configuração avançada atribui um modelo diferente a cada tarefa. Útil mais tarde, quando já sabe o que quer afinar.',
    'models-providers': 'Os modelos vêm de fornecedores. Adiciona um com a sua chave de API, e o Nodus guarda essa chave cifrada no seu computador.',
    'models-openrouter': 'O OpenRouter é um bom início, porque uma só chave lhe dá modelos de muitas empresas diferentes.',
    'models-catalogue': 'Assim que um fornecedor está ligado, todo o seu catálogo fica disponível em cada seletor de modelos do Nodus.',
    'extraction-intro': 'Dois conselhos sobre o modelo que extrai as ideias, porque decidem se o Nodus parece rápido ou parece avariado.',
    'extraction-api': 'Primeiro, prefira um modelo acessível por API. A extração lê os documentos em blocos, e um modelo remoto faz em segundos o que um local demora minutos.',
    'extraction-thinking': 'Segundo, não use um modelo de raciocínio para extrair. Os modelos que «pensam» gastam o seu orçamento a deliberar e muitas vezes não devolvem nada aproveitável; um modelo simples e rápido é melhor.',
    'extraction-recommend': 'Depois de muitos testes, os modelos Gemini Flash Lite deram o melhor equilíbrio entre velocidade, custo e resultados fiáveis para esta tarefa concreta.',
    'local-models': 'O Nodus também pode executar modelos no seu próprio computador, sem que nada saia dele.',
    'local-kinds': 'Há um para conversar, um para transcrever áudio, um para gerar imagens e outro para embeddings. Cada um só é descarregado se o quiser.',
    'local-tradeoff': 'São privados e gratuitos, mas mais lentos, e precisam de um computador capaz. Um bom compromisso: modelos locais para o dia a dia e uma API para a análise pesada.',
    'embeddings-what': 'E agora a definição que quase todos ignoram: o modelo de embeddings, que constrói um índice semântico do seu material.',
    'embeddings-why': 'Esse índice é o que lhe permite pesquisar por significado em vez de palavras exatas, e é o que encontra as relações e as pontes entre as suas ideias.',
    'embeddings-warning': 'Sem ele, a pesquisa semântica simplesmente não devolve nada — e um resultado vazio significa então que o cofre nunca foi indexado, não que as suas fontes não tratem o tema.',
    'embeddings-recommend': 'A recomendação é o BGE M3. Funciona localmente, lida com passagens longas e trabalha entre línguas, o que importa quando as suas fontes não estão todas na mesma.',
    'images': 'Para além do texto, o Nodus lê imagens e pode gerá-las, o que ajuda com figuras, diagramas e páginas digitalizadas.',
    'audio': 'Também transcreve gravações e lê o seu material em voz alta, para poder ouvir um documento longo em vez de o ler.',
    'toolkit': 'O Toolkit reúne as ferramentas práticas: converter ficheiros, proteger documentos, traduzir, um modo de apresentação e um espaço de OCR.',
    'mcp-intro': 'O Nodus também se pode abrir a outros programas. O servidor MCP permite que um assistente de IA leia este cofre diretamente.',
    'mcp-how': 'Escuta apenas no seu computador, por isso um assistente pode pesquisar nas suas fontes, ler as suas notas e citá-las, sem que a sua biblioteca seja publicada em lado nenhum.',
    'server-intro': 'O Nodus Server faz algo diferente: mantém atualizada uma cópia filtrada de um cofre através de uma ligação de saída.',
    'server-how': 'É assim que chega ao mesmo cofre a partir de outro dispositivo ou o partilha com alguém, sem abrir qualquer porta no seu computador.',
    'plugins': 'Há também extensões para os sítios onde já trabalha: Zotero, Microsoft Word e LibreOffice.',
    'nodi-settings': 'Por fim, não está sozinho aqui. O Nodi é o acompanhante que flutua no canto, e pode escolher o seu aspeto.',
    'nodi-meet': 'Este é o Nodi.',
    'nodi-open': 'Clique nele e terá um chat que conhece tanto a aplicação como o seu próprio material, além das suas notificações e ajuda quando precisar.',
    'first-setup': 'Uma forma segura de começar é começar pequeno. Crie um cofre, ligue um fornecedor, escolha um modelo de embeddings e analise um punhado de documentos que já conheça bem.',
    'closing': 'Isto é o Nodus. Verifique as provas, mantenha o seu material consigo, e deixe o grafo crescer com as suas leituras.',
  },

  'pt-BR': {
    'welcome': 'Boas-vindas ao Nodus. É um espaço de trabalho para seus documentos, notas e fontes, feito para mostrar como eles se conectam.',
    'local-first': 'Tudo fica salvo no seu próprio computador. Seu material só sai dele quando você escolhe um recurso que usa um serviço externo.',
    'tour-plan': 'Nos próximos minutos vamos ver os cofres, os modelos de IA de que o Nodus precisa e as ferramentas construídas em volta.',
    'vault-concept': 'Tudo começa com um cofre. Um cofre é um espaço de trabalho separado que mantém um projeto junto.',
    'vault-open-types': 'Quando você cria um, o Nodus pergunta para que tipo de trabalho ele serve, e essa escolha molda o cofre inteiro.',
    'vault-academic': 'Acadêmico é para pesquisa: bibliografia vinda do Zotero, ideias extraídas, autores e relações.',
    'vault-study': 'Estudo é para aprender: cursos, disciplinas, anotações, materiais e revisão.',
    'vault-teaching': 'Docência é o outro lado da sala de aula: seus próprios cursos, horários, materiais e avaliação.',
    'vault-databases': 'Bancos de dados é para informação estruturada: tabelas tipadas, relações entre elas e análise.',
    'vault-genealogy': 'Genealogia é para história familiar: pessoas, parentescos, linhas do tempo e evidências documentais.',
    'vault-more': 'Outros estão a caminho, e as etiquetas mostram quais ainda estão em beta ou prévia.',
    'vault-isolation': 'Cada cofre mantém a própria biblioteca, as próprias notas e as próprias configurações, então dois projetos nunca se misturam.',
    'sidebar': 'Dentro de um cofre você navega pela barra lateral. As seções são agrupadas conforme o que você está fazendo: explorar, analisar e criar.',
    'library-intro': 'A Biblioteca guarda suas fontes. Dependendo do cofre, elas vêm do Zotero, dos seus próprios arquivos ou do que você gravar.',
    'library-scan': 'Cada item mostra até onde o Nodus o leu. Uma passagem leve encontra temas; uma profunda extrai ideias junto com as evidências delas.',
    'library-analyse': 'Você escolhe o que é analisado e quando. Nada é processado sem você pedir.',
    'ideas-intro': 'O que essa passagem profunda extrai aparece aqui, como ideias individuais em vez de documentos inteiros.',
    'ideas-open': 'Abra uma e você tem o quadro completo dela.',
    'ideas-evidence': 'O tipo dela, a fonte de onde veio e a passagem exata que a sustenta.',
    'ideas-trust': 'Essa última parte é a que importa: confie em uma ideia só depois de ler a evidência por trás dela.',
    'graph-intro': 'O grafo transforma essas ideias em uma paisagem. Cada nó é uma ideia e cada ligação é uma relação entre elas.',
    'graph-reading': 'Os agrupamentos mostram onde suas fontes concordam. As pontes entre eles costumam ser os lugares mais interessantes.',
    'models-why': 'Nada disso acontece sozinho. O Nodus não traz inteligência própria: você escolhe quais modelos de IA ele usa, e esse é o passo de configuração que mais importa.',
    'models-basic': 'Há duas formas de configurá-los. A configuração básica usa um único modelo geral para tudo, e é o lugar certo para começar.',
    'models-advanced': 'A configuração avançada atribui um modelo diferente a cada tarefa. Útil mais adiante, quando você já sabe o que quer ajustar.',
    'models-providers': 'Os modelos vêm de provedores. Você adiciona um com a chave de API dele, e o Nodus guarda essa chave criptografada na sua máquina.',
    'models-openrouter': 'O OpenRouter é um bom começo, porque uma única chave te dá modelos de muitas empresas diferentes.',
    'models-catalogue': 'Assim que um provedor está conectado, todo o catálogo dele fica disponível em cada seletor de modelos do Nodus.',
    'extraction-intro': 'Dois conselhos sobre o modelo que extrai as ideias, porque eles decidem se o Nodus parece rápido ou parece quebrado.',
    'extraction-api': 'Primeiro, prefira um modelo acessado por API. A extração lê seus documentos em blocos, e um modelo remoto faz em segundos o que um local leva minutos para fazer.',
    'extraction-thinking': 'Segundo, não use um modelo de raciocínio para extração. Modelos que "pensam" gastam o orçamento deliberando e muitas vezes não devolvem nada aproveitável; um modelo simples e rápido é a melhor escolha.',
    'extraction-recommend': 'Depois de muitos testes, os modelos Gemini Flash Lite deram o melhor equilíbrio entre velocidade, custo e resultados confiáveis para essa tarefa específica.',
    'local-models': 'O Nodus também pode rodar modelos na sua própria máquina, sem que nada saia do seu computador.',
    'local-kinds': 'Tem um para conversa, um para transcrever áudio, um para gerar imagens e um para embeddings. Cada um é baixado só se você quiser.',
    'local-tradeoff': 'São privados e gratuitos, mas mais lentos, e exigem um computador capaz. Um bom meio-termo: modelos locais para o chat do dia a dia e uma API para a análise pesada.',
    'embeddings-what': 'Agora a configuração que quase todo mundo ignora: o modelo de embeddings, que constrói um índice semântico do seu material.',
    'embeddings-why': 'Esse índice é o que permite buscar por significado em vez de palavras exatas, e é o que encontra as relações e as pontes entre suas ideias.',
    'embeddings-warning': 'Sem ele, a busca semântica simplesmente não devolve nada — e um resultado vazio significa que o cofre nunca foi indexado, não que suas fontes não tratem do assunto.',
    'embeddings-recommend': 'A recomendação é o BGE M3. Roda localmente, lida com passagens longas e funciona entre idiomas, o que importa quando suas fontes não estão todas no mesmo.',
    'images': 'Além do texto, o Nodus lê imagens e pode gerá-las, o que ajuda com figuras, diagramas e páginas digitalizadas.',
    'audio': 'Ele também transcreve gravações e lê seu material em voz alta, então você pode ouvir um documento longo em vez de lê-lo.',
    'toolkit': 'O Toolkit reúne as ferramentas práticas: converter arquivos, proteger documentos, traduzir, um modo de apresentação e um espaço de OCR.',
    'mcp-intro': 'O Nodus também pode se abrir para outros programas. O servidor MCP deixa um assistente de IA ler este cofre diretamente.',
    'mcp-how': 'Ele escuta só no seu computador, então um assistente pode buscar nas suas fontes, ler suas notas e citá-las, sem que sua biblioteca seja publicada em lugar nenhum.',
    'server-intro': 'O Nodus Server faz outra coisa: mantém atualizada uma cópia filtrada de um cofre por uma conexão de saída.',
    'server-how': 'É assim que você alcança o mesmo cofre de outro dispositivo ou compartilha com alguém, sem abrir nenhuma porta na sua máquina.',
    'plugins': 'Também há plugins para os lugares onde você já trabalha: Zotero, Microsoft Word e LibreOffice.',
    'nodi-settings': 'Por último, você não está sozinho aqui. O Nodi é o companheiro que flutua no canto, e você pode escolher a aparência dele.',
    'nodi-meet': 'Este é o Nodi.',
    'nodi-open': 'Clique nele e você tem um chat que conhece tanto o app quanto o seu próprio material, junto com suas notificações e ajuda quando precisar.',
    'first-setup': 'Um jeito seguro de começar é começar pequeno. Crie um cofre, conecte um provedor, escolha um modelo de embeddings e analise alguns documentos que você já conhece bem.',
    'closing': 'Esse é o Nodus. Confira as evidências, mantenha seu material com você, e deixe o grafo crescer junto com a sua leitura.',
  },

  tr: {
    'welcome': 'Nodus’a hoş geldiniz. Belgeleriniz, notlarınız ve kaynaklarınız için, aralarındaki bağı göstermek üzere kurulmuş bir çalışma alanı.',
    'local-first': 'Her şey kendi bilgisayarınızda saklanır. Materyaliniz oradan yalnızca dış bir hizmet kullanan bir özelliği seçtiğinizde çıkar.',
    'tour-plan': 'Önümüzdeki birkaç dakikada kasalara, Nodus’un ihtiyaç duyduğu yapay zekâ modellerine ve çevresindeki araçlara bakacağız.',
    'vault-concept': 'Her şey bir kasayla başlar. Kasa, tek bir projeyi bir arada tutan ayrı bir çalışma alanıdır.',
    'vault-open-types': 'Bir kasa oluşturduğunuzda Nodus hangi tür çalışma için olduğunu sorar ve bu seçim kasanın tamamını biçimlendirir.',
    'vault-academic': 'Akademik, araştırma içindir: Zotero’dan gelen kaynakça, çıkarılan fikirler, yazarlar ve ilişkiler.',
    'vault-study': 'Çalışma, öğrenmek içindir: dersler, konular, notlar, materyaller ve tekrar.',
    'vault-teaching': 'Öğretim, sınıfın diğer tarafı içindir: kendi dersleriniz, ders programları, materyaller ve değerlendirme.',
    'vault-databases': 'Veritabanları, yapılandırılmış bilgi içindir: tipli tablolar, aralarındaki ilişkiler ve analiz.',
    'vault-genealogy': 'Şecere, aile tarihi içindir: kişiler, akrabalık, zaman çizelgeleri ve belgesel kanıtlar.',
    'vault-more': 'Daha fazlası yolda; rozetler hangilerinin hâlâ beta veya önizlemede olduğunu gösterir.',
    'vault-isolation': 'Her kasa kendi kütüphanesini, notlarını ve ayarlarını korur; böylece iki proje asla karışmaz.',
    'sidebar': 'Bir kasanın içinde kenar çubuğuyla gezinirsiniz. Bölümler ne yaptığınıza göre gruplanmıştır: keşfetmek, çözümlemek ve üretmek.',
    'library-intro': 'Kütüphane kaynaklarınızı tutar. Kasaya göre Zotero’dan, kendi dosyalarınızdan ya da kaydettiklerinizden gelirler.',
    'library-scan': 'Her öğe Nodus’un onu ne kadar okuduğunu gösterir. Hafif tarama temaları bulur; derin tarama fikirleri kanıtlarıyla birlikte çıkarır.',
    'library-analyse': 'Neyin ne zaman çözümleneceğini siz seçersiniz. Siz istemedikçe hiçbir şey işlenmez.',
    'ideas-intro': 'Derin taramanın çıkardıkları burada belirir: belgeler yerine tek tek fikirler olarak.',
    'ideas-open': 'Birini açın, tüm resmi görün.',
    'ideas-evidence': 'Türü, geldiği kaynak ve onu destekleyen tam pasaj.',
    'ideas-trust': 'Asıl önemli olan bu son kısım: bir fikre ancak arkasındaki kanıtı okuduktan sonra güvenin.',
    'graph-intro': 'Grafik bu fikirleri bir manzaraya dönüştürür. Her düğüm bir fikir, her bağ aralarındaki bir ilişkidir.',
    'graph-reading': 'Kümeler kaynaklarınızın nerede uyuştuğunu gösterir. Kümeler arasındaki köprüler çoğu zaman en ilginç yerlerdir.',
    'models-why': 'Bunların hiçbiri kendiliğinden olmaz. Nodus kendi zekâsıyla gelmez: hangi yapay zekâ modellerini kullanacağını siz seçersiniz ve bu, en çok önem taşıyan kurulum adımıdır.',
    'models-basic': 'Bunları yapılandırmanın iki yolu var. Temel yapılandırma her şey için tek bir genel model kullanır ve başlamak için doğru yerdir.',
    'models-advanced': 'Gelişmiş yapılandırma her göreve farklı bir model atar. Hangi kısımları ayarlamak istediğinizi bildiğinizde, ilerisi için yararlıdır.',
    'models-providers': 'Modeller sağlayıcılardan gelir. Birini API anahtarıyla eklersiniz ve Nodus bu anahtarı cihazınızda şifreli tutar.',
    'models-openrouter': 'OpenRouter başlamak için iyi bir yer, çünkü tek bir anahtar size pek çok farklı şirketin modelini verir.',
    'models-catalogue': 'Bir sağlayıcı bağlandığında, tüm kataloğu Nodus’taki her model seçicisinde kullanılabilir hale gelir.',
    'extraction-intro': 'Fikirleri çıkaran model hakkında iki öneri; çünkü Nodus’un hızlı mı yoksa bozuk mu hissettireceğini bunlar belirler.',
    'extraction-api': 'Birincisi, API üzerinden erişilen bir modeli tercih edin. Çıkarım belgelerinizi parçalar hâlinde okur ve uzak bir model, yerel bir modelin dakikalar sürdüğü işi saniyelerde yapar.',
    'extraction-thinking': 'İkincisi, çıkarım için akıl yürüten bir model kullanmayın. Düşünen modeller bütçelerini tartışarak harcar ve çoğu kez kullanılabilir bir şey döndürmez; sade ve hızlı bir model burada daha iyidir.',
    'extraction-recommend': 'Pek çok denemenin ardından Gemini Flash Lite modelleri, bu iş için hız, maliyet ve güvenilir sonuç arasında en iyi dengeyi verdi.',
    'local-models': 'Nodus modelleri kendi makinenizde de çalıştırabilir; hiçbir şey bilgisayarınızdan çıkmaz.',
    'local-kinds': 'Sohbet için bir tane, ses yazıya çevirmek için bir tane, görsel üretmek için bir tane ve gömmeler için bir tane var. Her biri yalnızca isterseniz indirilir.',
    'local-tradeoff': 'Gizli ve ücretsizler ama daha yavaşlar ve güçlü bir bilgisayar isterler. İyi bir orta yol: günlük sohbet için yerel modeller, ağır çözümleme için bir API.',
    'embeddings-what': 'Şimdi çoğu kişinin gözden kaçırdığı ayar: materyalinizin anlamsal dizinini kuran gömme modeli.',
    'embeddings-why': 'Bu dizin, tam sözcükler yerine anlama göre aramanızı sağlayan şeydir; fikirleriniz arasındaki ilişkileri ve köprüleri de o bulur.',
    'embeddings-warning': 'O olmadan anlamsal arama hiçbir şey döndürmez ve boş bir sonuç, kaynaklarınızın konuyu içermediği değil, kasanın hiç dizinlenmediği anlamına gelir.',
    'embeddings-recommend': 'Önerimiz BGE M3. Yerelde çalışır, uzun pasajları kaldırır ve diller arasında iş görür; kaynaklarınız aynı dilde değilse bu önemlidir.',
    'images': 'Metnin ötesinde Nodus görselleri okur ve üretebilir; şekiller, şemalar ve taranmış sayfalar için işe yarar.',
    'audio': 'Ayrıca kayıtları yazıya çevirir ve materyalinizi sesli okur; böylece uzun bir belgeyi okumak yerine dinleyebilirsiniz.',
    'toolkit': 'Toolkit pratik araçları toplar: dosya dönüştürme, belge koruma, çeviri, sunum kipi ve bir OCR çalışma alanı.',
    'mcp-intro': 'Nodus başka yazılımlara da açılabilir. MCP sunucusu, bir yapay zekâ asistanının bu kasayı doğrudan okumasını sağlar.',
    'mcp-how': 'Yalnızca kendi bilgisayarınızda dinler; böylece bir asistan kaynaklarınızda arama yapabilir, notlarınızı okuyup alıntılayabilir, kütüphaneniz hiçbir yerde yayımlanmadan.',
    'server-intro': 'Nodus Server farklı bir şey yapar: bir kasanın filtrelenmiş kopyasını giden bir bağlantı üzerinden güncel tutar.',
    'server-how': 'Aynı kasaya başka bir cihazdan böyle ulaşır ya da onu biriyle paylaşırsınız; makinenizde hiçbir bağlantı noktası açılmadan.',
    'plugins': 'Ayrıca zaten çalıştığınız yerler için eklentiler var: Zotero, Microsoft Word ve LibreOffice.',
    'nodi-settings': 'Son olarak, burada yalnız değilsiniz. Nodi köşede süzülen yol arkadaşınız ve görünüşünü seçebilirsiniz.',
    'nodi-meet': 'Bu Nodi.',
    'nodi-open': 'Tıklayın; hem uygulamayı hem de kendi materyalinizi bilen bir sohbet, bildirimleriniz ve gerektiğinde yardım karşınıza gelir.',
    'first-setup': 'Güvenli bir başlangıç küçük olanıdır. Bir kasa oluşturun, bir sağlayıcı bağlayın, bir gömme modeli seçin ve iyi bildiğiniz birkaç belgeyi çözümleyin.',
    'closing': 'İşte Nodus. Kanıtı kontrol edin, materyaliniz sizde kalsın ve grafik okumalarınızla birlikte büyüsün.',
  },

  zh: {
    'welcome': '欢迎使用 Nodus。这是一个面向你的文档、笔记和来源的工作空间，用来呈现它们之间的关联。',
    'local-first': '一切都保存在你自己的电脑上。只有当你主动选择使用外部服务的功能时，你的材料才会离开本机。',
    'tour-plan': '接下来的几分钟，我们会看看资料库、Nodus 所需的 AI 模型，以及围绕它们构建的工具。',
    'vault-concept': '一切从资料库开始。资料库是一个独立的工作空间，把同一个项目的内容集中在一起。',
    'vault-open-types': '创建时，Nodus 会询问它用于哪一类工作，这个选择决定了整个资料库的形态。',
    'vault-academic': '学术型用于研究：来自 Zotero 的文献、提取出的想法、作者与关系。',
    'vault-study': '学习型用于学习：课程、科目、笔记、材料与复习。',
    'vault-teaching': '教学型面向讲台这一侧：你自己的课程、课表、教学材料与评分。',
    'vault-databases': '数据库型用于结构化信息：带类型的表格、表间关系与分析。',
    'vault-genealogy': '族谱型用于家族历史：人物、亲属关系、时间线与文献佐证。',
    'vault-more': '还有更多正在开发，标签会告诉你哪些仍处于测试版或预览阶段。',
    'vault-isolation': '每个资料库都保有自己的文库、笔记和设置，因此两个项目永远不会混在一起。',
    'sidebar': '在资料库内，你通过侧边栏移动。各个区块按你正在做的事分组：探索、分析和创作。',
    'library-intro': '文库存放你的来源。视资料库而定，它们来自 Zotero、你自己的文件，或你录制的内容。',
    'library-scan': '每一项都会显示 Nodus 读到了什么程度。轻量扫描找出主题；深度扫描连同支撑证据一起提取想法。',
    'library-analyse': '分析什么、何时分析由你决定。你不提出要求，就不会处理任何内容。',
    'ideas-intro': '深度扫描提取的内容会出现在这里，呈现为一条条独立的想法，而不是整份文档。',
    'ideas-open': '打开其中一条，就能看到它的全貌。',
    'ideas-evidence': '它的类型、出自哪个来源，以及支撑它的确切段落。',
    'ideas-trust': '最后这一点最重要：只有读过背后的证据，才去相信一条想法。',
    'graph-intro': '图谱把这些想法变成一片地貌。每个节点是一条想法，每条连线是它们之间的关系。',
    'graph-reading': '聚簇显示你的来源在哪里彼此吻合。而簇与簇之间的桥梁，往往是最值得关注的地方。',
    'models-why': '这一切都不会自动发生。Nodus 不自带智能——使用哪些 AI 模型由你决定，这是最关键的设置步骤。',
    'models-basic': '配置方式有两种。基础配置用一个通用模型处理所有任务，也是最适合入门的选择。',
    'models-advanced': '高级配置为每项任务分配不同的模型。等你清楚想调整哪些环节时，它才派得上用场。',
    'models-providers': '模型来自服务提供商。你用它的 API 密钥添加一次，Nodus 会把该密钥加密保存在你的电脑上。',
    'models-openrouter': 'OpenRouter 是不错的起点，因为一把密钥就能让你用上许多不同公司的模型。',
    'models-catalogue': '一旦连接了提供商，它的整个目录就会出现在 Nodus 的每一个模型选择器中。',
    'extraction-intro': '关于提取想法的模型，有两点建议，它们决定了 Nodus 用起来是流畅还是像坏掉了。',
    'extraction-api': '第一，优先选择通过 API 访问的模型。提取会分块读取你的文档，远程模型几秒就能完成本地模型要花几分钟的工作。',
    'extraction-thinking': '第二，不要用推理模型来做提取。会“思考”的模型把预算耗在推敲上，常常返回不了可用的结果；朴素而快速的模型在这里更合适。',
    'extraction-recommend': '经过大量测试，Gemini Flash Lite 系列在这项具体任务上，于速度、成本和结果可靠性之间取得了最好的平衡。',
    'local-models': 'Nodus 也可以在你自己的机器上运行模型，任何内容都不会离开你的电脑。',
    'local-kinds': '其中有对话用的、音频转写用的、图像生成用的，还有嵌入用的。每一个都只在你需要时才下载。',
    'local-tradeoff': '它们私密且免费，但速度较慢，也需要性能足够的电脑。一个不错的折中：日常对话用本地模型，繁重分析用 API。',
    'embeddings-what': '接下来是大多数人会忽略的设置：嵌入模型，它为你的材料建立语义索引。',
    'embeddings-why': '正是这个索引让你能按含义而非精确字词检索，也是它找出想法之间的关系与桥梁。',
    'embeddings-warning': '没有它，语义搜索根本不会返回任何结果——此时的空结果意味着资料库从未建立索引，而不是你的来源没有涉及该主题。',
    'embeddings-recommend': '推荐使用 BGE M3。它在本地运行，能处理长段落，并且跨语言可用——当你的来源不是同一种语言时，这一点很重要。',
    'images': '除了文本，Nodus 还能读取和生成图像，这对插图、示意图和扫描页很有帮助。',
    'audio': '它也能转写录音并朗读你的材料，让你可以听完一份长文档，而不必逐字阅读。',
    'toolkit': 'Toolkit 汇集了实用工具：文件转换、文档保护、翻译、演示模式，以及 OCR 工作区。',
    'mcp-intro': 'Nodus 还能向其他软件开放。MCP 服务器让 AI 助手直接读取这个资料库。',
    'mcp-how': '它只在你自己的电脑上监听，因此助手可以检索你的来源、阅读并引用你的笔记，而你的文库不会被发布到任何地方。',
    'server-intro': 'Nodus Server 做的是另一件事：通过一个向外的连接，持续更新资料库的一份过滤副本。',
    'server-how': '你正是这样从另一台设备访问同一个资料库，或把它分享给别人，而你的电脑上不会开放任何端口。',
    'plugins': '此外还有插件，用在你本来就在用的地方：Zotero、Microsoft Word 和 LibreOffice。',
    'nodi-settings': '最后，你在这里并不孤单。Nodi 是漂浮在角落里的伙伴，你可以选择它的外观。',
    'nodi-meet': '这就是 Nodi。',
    'nodi-open': '点击它，你会得到一个既懂这款应用、也懂你自己材料的聊天窗口，还有你的通知，以及随时可用的帮助。',
    'first-setup': '稳妥的开始方式是从小做起。创建一个资料库，连接一个提供商，选好嵌入模型，然后分析几份你已经熟悉的文档。',
    'closing': '这就是 Nodus。核对证据，让材料始终属于你，并让图谱随着你的阅读一同生长。',
  },

  ja: {
    'welcome': 'Nodusへようこそ。文書やノート、資料のための作業空間で、それらのつながりが見えるように作られています。',
    'local-first': 'すべてはあなたのコンピューターに保存されます。外部サービスを使う機能を選んだときだけ、資料が外に出ます。',
    'tour-plan': 'これからの数分で、Vault、Nodusに必要なAIモデル、そしてその周りに用意された道具を見ていきます。',
    'vault-concept': 'すべてはVaultから始まります。Vaultは、ひとつのプロジェクトをまとめて保つ独立した作業空間です。',
    'vault-open-types': '作成するとき、Nodusはどんな作業のためのものかを尋ねます。この選択がVault全体の形を決めます。',
    'vault-academic': '学術は研究のためのものです。Zoteroからの文献、抽出されたアイデア、著者、そして関係。',
    'vault-study': '学習は学ぶためのものです。コース、科目、ノート、教材、そして復習。',
    'vault-teaching': '教育は教室の反対側のためのものです。自分の授業、時間割、教材、そして評価。',
    'vault-databases': 'データベースは構造化された情報のためのものです。型のある表、その間の関係、そして分析。',
    'vault-genealogy': '系譜は家族史のためのものです。人物、親族関係、年表、そして文書による証拠。',
    'vault-more': 'さらに追加される予定で、バッジがどれがまだベータやプレビューかを示します。',
    'vault-isolation': '各Vaultは独自のライブラリ、ノート、設定を保つので、二つのプロジェクトが混ざることはありません。',
    'sidebar': 'Vaultの中はサイドバーで移動します。各セクションは、探す・分析する・作るという作業内容ごとにまとめられています。',
    'library-intro': 'ライブラリには資料が入ります。Vaultに応じて、Zoteroから、自分のファイルから、あるいは録音したものから集まります。',
    'library-scan': '各項目には、Nodusがどこまで読んだかが示されます。軽いスキャンはテーマを見つけ、深いスキャンは根拠とともにアイデアを抽出します。',
    'library-analyse': '何をいつ分析するかはあなたが決めます。求めない限り、何も処理されません。',
    'ideas-intro': '深いスキャンが取り出したものは、文書全体ではなく一つひとつのアイデアとしてここに並びます。',
    'ideas-open': 'ひとつ開けば、その全体像がわかります。',
    'ideas-evidence': '種類、出典となった資料、そしてそれを支える正確な一節。',
    'ideas-trust': '最後の点が肝心です。裏づけとなる根拠を読んで初めて、そのアイデアを信頼してください。',
    'graph-intro': 'グラフはそれらのアイデアをひとつの地形に変えます。各ノードがアイデアで、各リンクがその関係です。',
    'graph-reading': 'かたまりは資料が一致している場所を示します。かたまりの間の橋渡しは、しばしば最も興味深い場所です。',
    'models-why': 'これらは自然に起こるわけではありません。Nodusは独自の知能を持ちません。どのAIモデルを使うかはあなたが選び、それが最も重要な設定です。',
    'models-basic': '設定方法は二つあります。基本設定はすべてを一つの汎用モデルでまかなうもので、始めるにはここが適しています。',
    'models-advanced': '詳細設定は作業ごとに別々のモデルを割り当てます。どこを調整したいかが分かってから役に立ちます。',
    'models-providers': 'モデルはプロバイダーから来ます。APIキーで一度追加すれば、Nodusはそのキーを暗号化して端末に保存します。',
    'models-openrouter': 'OpenRouterは始めるのに向いています。ひとつのキーで多くの企業のモデルが使えるからです。',
    'models-catalogue': 'プロバイダーを接続すると、そのカタログ全体がNodusのすべてのモデル選択欄で使えるようになります。',
    'extraction-intro': 'アイデアを抽出するモデルについて助言が二つあります。Nodusが軽快に感じられるか、壊れて見えるかを左右します。',
    'extraction-api': '第一に、API経由のモデルを選んでください。抽出は文書を分割して読むため、リモートのモデルはローカルが数分かかる処理を数秒でこなします。',
    'extraction-thinking': '第二に、抽出に推論モデルを使わないでください。考えるモデルは予算を検討に費やし、使える結果を返さないことが多いので、素直で速いモデルの方が適しています。',
    'extraction-recommend': '多くの検証の結果、この作業に関してはGemini Flash Liteが速度・費用・結果の安定性の釣り合いで最良でした。',
    'local-models': 'Nodusは自分の端末でモデルを動かすこともできます。何ひとつコンピューターの外に出ません。',
    'local-kinds': 'チャット用、音声の文字起こし用、画像生成用、そして埋め込み用があります。どれも必要なときだけダウンロードされます。',
    'local-tradeoff': '非公開で無料ですが、遅く、性能の高いコンピューターが要ります。良い折衷案は、日常のチャットはローカル、重い分析はAPIです。',
    'embeddings-what': 'そして多くの人が見落とす設定、埋め込みモデルです。これが資料の意味的な索引を作ります。',
    'embeddings-why': 'この索引があるからこそ、正確な語ではなく意味で検索でき、アイデア同士の関係や橋渡しも見つかります。',
    'embeddings-warning': 'これがないと意味検索は何も返しません。そのときの空の結果は、資料が話題を扱っていないのではなく、Vaultが索引化されていないという意味です。',
    'embeddings-recommend': '推奨はBGE M3です。ローカルで動き、長い一節を扱え、言語をまたいで機能します。資料の言語がそろっていないときに効いてきます。',
    'images': 'テキストにとどまらず、Nodusは画像を読み取り、生成もできます。図やダイアグラム、スキャンしたページに役立ちます。',
    'audio': '録音の文字起こしや、資料の読み上げも行うので、長い文書は読まずに聴くこともできます。',
    'toolkit': 'Toolkitは実用的な道具をまとめています。ファイル変換、文書の保護、翻訳、プレゼンテーションモード、そしてOCRワークスペースです。',
    'mcp-intro': 'Nodusは他のソフトウェアにも開くことができます。MCPサーバーを使うと、AIアシスタントがこのVaultを直接読めます。',
    'mcp-how': '待ち受けるのは自分のコンピューター上だけです。ですからアシスタントは資料を検索し、ノートを読んで引用できますが、ライブラリはどこにも公開されません。',
    'server-intro': 'Nodus Serverは別のことをします。外向きの接続を通じて、Vaultの絞り込んだ複製を最新に保ちます。',
    'server-how': 'これにより、別の端末から同じVaultにアクセスしたり誰かと共有したりできます。しかも端末側でポートは一切開きません。',
    'plugins': 'すでに使っている場所向けのプラグインもあります。Zotero、Microsoft Word、LibreOfficeです。',
    'nodi-settings': '最後に、ここであなたは一人ではありません。Nodiは隅に浮かぶ相棒で、見た目を選べます。',
    'nodi-meet': 'これがNodiです。',
    'nodi-open': 'クリックすると、アプリのことも自分の資料のことも分かるチャットに加えて、通知と、必要なときの助けが得られます。',
    'first-setup': '安全な始め方は、小さく始めることです。Vaultをひとつ作り、プロバイダーを接続し、埋め込みモデルを選び、よく知っている文書をいくつか分析してみてください。',
    'closing': 'これがNodusです。根拠を確かめ、資料は自分の手元に置き、読書とともにグラフを育ててください。',
  },

  ru: {
    'welcome': 'Добро пожаловать в Nodus. Это рабочее пространство для ваших документов, заметок и источников, созданное, чтобы показать, как они связаны.',
    'local-first': 'Всё хранится на вашем компьютере. Ваши материалы покидают его только тогда, когда вы выбираете функцию, использующую внешний сервис.',
    'tour-plan': 'В ближайшие минуты мы посмотрим на хранилища, на модели ИИ, которые нужны Nodus, и на инструменты вокруг них.',
    'vault-concept': 'Всё начинается с хранилища. Хранилище — это отдельное рабочее пространство, которое держит один проект вместе.',
    'vault-open-types': 'При создании Nodus спрашивает, для какой работы оно предназначено, и этот выбор задаёт форму всему хранилищу.',
    'vault-academic': 'Академическое — для исследования: библиография из Zotero, извлечённые идеи, авторы и связи.',
    'vault-study': 'Учебное — для обучения: курсы, предметы, конспекты, материалы и повторение.',
    'vault-teaching': 'Преподавание — это другая сторона аудитории: ваши собственные курсы, расписания, материалы и оценивание.',
    'vault-databases': 'Базы данных — для структурированной информации: типизированные таблицы, связи между ними и анализ.',
    'vault-genealogy': 'Генеалогия — для истории семьи: люди, родство, хронологии и документальные свидетельства.',
    'vault-more': 'Появятся и другие, а метки показывают, какие пока в бета-версии или предпросмотре.',
    'vault-isolation': 'У каждого хранилища своя библиотека, свои заметки и свои настройки, поэтому два проекта никогда не смешиваются.',
    'sidebar': 'Внутри хранилища вы перемещаетесь по боковой панели. Её разделы сгруппированы по тому, что вы делаете: искать, анализировать и создавать.',
    'library-intro': 'В Библиотеке лежат ваши источники. В зависимости от хранилища они приходят из Zotero, из ваших файлов или из того, что вы записали.',
    'library-scan': 'Каждый элемент показывает, насколько глубоко Nodus его прочёл. Лёгкий проход находит темы; глубокий извлекает идеи вместе с подтверждающими их цитатами.',
    'library-analyse': 'Вы выбираете, что и когда анализировать. Ничего не обрабатывается без вашей просьбы.',
    'ideas-intro': 'То, что извлекает глубокий проход, появляется здесь — отдельными идеями, а не целыми документами.',
    'ideas-open': 'Откройте одну — и увидите её целиком.',
    'ideas-evidence': 'Её тип, источник, откуда она взята, и точный фрагмент, который её подтверждает.',
    'ideas-trust': 'Именно последнее и важно: доверяйте идее лишь после того, как прочли стоящее за ней подтверждение.',
    'graph-intro': 'Граф превращает эти идеи в ландшафт. Каждый узел — идея, каждая связь — отношение между ними.',
    'graph-reading': 'Скопления показывают, где ваши источники согласуются. Мостики между ними часто оказываются самыми интересными местами.',
    'models-why': 'Ничего из этого не происходит само собой. Nodus не несёт собственного интеллекта: вы выбираете, какие модели ИИ он использует, и это самый важный шаг настройки.',
    'models-basic': 'Настроить их можно двумя способами. Базовая настройка использует одну общую модель для всего — с неё и стоит начинать.',
    'models-advanced': 'Расширенная настройка назначает свою модель каждой задаче. Это пригодится позже, когда вы поймёте, что хотите донастроить.',
    'models-providers': 'Модели приходят от провайдеров. Вы добавляете провайдера с его ключом API, и Nodus хранит этот ключ на вашем устройстве в зашифрованном виде.',
    'models-openrouter': 'OpenRouter — хорошее начало, потому что один ключ даёт вам модели множества разных компаний.',
    'models-catalogue': 'Как только провайдер подключён, весь его каталог становится доступен в каждом списке выбора модели в Nodus.',
    'extraction-intro': 'Два совета о модели, которая извлекает идеи, — от них зависит, покажется ли Nodus быстрым или сломанным.',
    'extraction-api': 'Во-первых, предпочтите модель, доступную по API. Извлечение читает документы по частям, и удалённая модель делает за секунды то, на что локальной нужны минуты.',
    'extraction-thinking': 'Во-вторых, не берите для извлечения рассуждающую модель. «Думающие» модели тратят бюджет на размышления и часто не возвращают ничего пригодного; простая и быстрая здесь лучше.',
    'extraction-recommend': 'После множества проверок модели Gemini Flash Lite дали лучшее сочетание скорости, стоимости и надёжности результата именно для этой задачи.',
    'local-models': 'Nodus может запускать модели и на вашей машине — тогда ничего не покидает компьютер.',
    'local-kinds': 'Есть модель для чата, для расшифровки звука, для генерации изображений и для эмбеддингов. Каждая скачивается только по вашему желанию.',
    'local-tradeoff': 'Они приватны и бесплатны, но медленнее и требуют мощного компьютера. Разумный компромисс: локальные модели для повседневного чата и API для тяжёлого анализа.',
    'embeddings-what': 'А теперь настройка, которую большинство упускает: модель эмбеддингов, строящая семантический индекс ваших материалов.',
    'embeddings-why': 'Этот индекс позволяет искать по смыслу, а не по точным словам, и именно он находит связи и мостики между вашими идеями.',
    'embeddings-warning': 'Без него семантический поиск попросту ничего не возвращает — и тогда пустой результат означает, что хранилище не индексировали, а не что источники не касаются темы.',
    'embeddings-recommend': 'Рекомендация — BGE M3. Он работает локально, справляется с длинными фрагментами и работает между языками, что важно, если ваши источники не на одном языке.',
    'images': 'Помимо текста Nodus читает изображения и умеет их создавать, что помогает с рисунками, схемами и отсканированными страницами.',
    'audio': 'Он также расшифровывает записи и читает материалы вслух, так что длинный документ можно послушать, а не читать.',
    'toolkit': 'Toolkit собирает практические инструменты: конвертацию файлов, защиту документов, перевод, режим презентации и рабочее место OCR.',
    'mcp-intro': 'Nodus может открыться и другим программам. Сервер MCP позволяет ИИ-ассистенту читать это хранилище напрямую.',
    'mcp-how': 'Он слушает только на вашем компьютере, поэтому ассистент может искать по источникам, читать заметки и цитировать их, а ваша библиотека нигде не публикуется.',
    'server-intro': 'Nodus Server делает другое: он поддерживает в актуальном состоянии отфильтрованную копию хранилища через исходящее соединение.',
    'server-how': 'Так вы попадаете в то же хранилище с другого устройства или делитесь им с кем-то — и при этом на вашей машине не открывается ни один порт.',
    'plugins': 'Есть и плагины для тех мест, где вы уже работаете: Zotero, Microsoft Word и LibreOffice.',
    'nodi-settings': 'И наконец, здесь вы не одни. Nodi — спутник, парящий в углу, и вы можете выбрать, как он выглядит.',
    'nodi-meet': 'Это Nodi.',
    'nodi-open': 'Нажмите — и получите чат, который знает и приложение, и ваши материалы, а вместе с ним уведомления и помощь, когда она нужна.',
    'first-setup': 'Надёжный способ начать — начать с малого. Создайте хранилище, подключите провайдера, выберите модель эмбеддингов и разберите несколько документов, которые вы хорошо знаете.',
    'closing': 'Это Nodus. Проверяйте подтверждения, оставляйте материалы у себя и позвольте графу расти вместе с вашим чтением.',
  },

  uk: {
    'welcome': 'Вітаємо в Nodus. Це робочий простір для ваших документів, нотаток і джерел, створений, щоб показати, як вони пов’язані.',
    'local-first': 'Усе зберігається на вашому комп’ютері. Ваші матеріали покидають його лише тоді, коли ви обираєте функцію, що використовує зовнішній сервіс.',
    'tour-plan': 'За кілька наступних хвилин ми подивимося на сховища, на моделі ШІ, потрібні Nodus, і на інструменти навколо них.',
    'vault-concept': 'Усе починається зі сховища. Сховище — це окремий робочий простір, що тримає один проєкт разом.',
    'vault-open-types': 'Коли ви його створюєте, Nodus запитує, для якої роботи воно призначене, і цей вибір формує все сховище.',
    'vault-academic': 'Академічне — для досліджень: бібліографія із Zotero, видобуті ідеї, автори та зв’язки.',
    'vault-study': 'Навчальне — щоб учитися: курси, предмети, конспекти, матеріали та повторення.',
    'vault-teaching': 'Викладання — це інший бік аудиторії: ваші власні курси, розклади, матеріали та оцінювання.',
    'vault-databases': 'Бази даних — для структурованої інформації: типізовані таблиці, зв’язки між ними та аналіз.',
    'vault-genealogy': 'Генеалогія — для історії родини: люди, спорідненість, хронології та документальні свідчення.',
    'vault-more': 'З’являться й інші, а позначки показують, які ще в беті або в передперегляді.',
    'vault-isolation': 'Кожне сховище має власну бібліотеку, власні нотатки й власні налаштування, тож два проєкти ніколи не змішуються.',
    'sidebar': 'Усередині сховища ви рухаєтеся бічною панеллю. Її розділи згруповані за тим, що ви робите: досліджувати, аналізувати та створювати.',
    'library-intro': 'Бібліотека містить ваші джерела. Залежно від сховища вони надходять із Zotero, з ваших файлів або з того, що ви записали.',
    'library-scan': 'Кожен елемент показує, наскільки глибоко Nodus його прочитав. Легкий прохід знаходить теми; глибокий видобуває ідеї разом із доказами.',
    'library-analyse': 'Ви обираєте, що аналізувати і коли. Нічого не обробляється, доки ви цього не попросите.',
    'ideas-intro': 'Те, що видобуває глибокий прохід, з’являється тут — окремими ідеями, а не цілими документами.',
    'ideas-open': 'Відкрийте одну — і побачите її повну картину.',
    'ideas-evidence': 'Її тип, джерело, з якого вона походить, і точний уривок, що її підтверджує.',
    'ideas-trust': 'Саме останнє й важливе: довіряйте ідеї лише після того, як прочитали доказ за нею.',
    'graph-intro': 'Граф перетворює ці ідеї на ландшафт. Кожен вузол — ідея, а кожен зв’язок — відношення між ними.',
    'graph-reading': 'Скупчення показують, де ваші джерела узгоджуються. Містки між ними часто виявляються найцікавішими місцями.',
    'models-why': 'Ніщо з цього не стається саме собою. Nodus не несе власного інтелекту: ви обираєте, які моделі ШІ він використовує, і це найважливіший крок налаштування.',
    'models-basic': 'Налаштувати їх можна двома способами. Базове налаштування використовує одну загальну модель для всього — саме звідси й варто починати.',
    'models-advanced': 'Розширене налаштування призначає окрему модель кожному завданню. Це знадобиться згодом, коли ви зрозумієте, що хочете підлаштувати.',
    'models-providers': 'Моделі надходять від постачальників. Ви додаєте одного з його ключем API, і Nodus зберігає цей ключ зашифрованим на вашому пристрої.',
    'models-openrouter': 'OpenRouter — гарний початок, бо один ключ дає вам моделі багатьох різних компаній.',
    'models-catalogue': 'Щойно постачальника підключено, увесь його каталог стає доступним у кожному списку вибору моделі в Nodus.',
    'extraction-intro': 'Дві поради щодо моделі, яка видобуває ідеї, — саме вони вирішують, чи здаватиметься Nodus швидким, чи зламаним.',
    'extraction-api': 'По-перше, віддавайте перевагу моделі, доступній через API. Видобування читає документи частинами, і віддалена модель робить за секунди те, на що локальній потрібні хвилини.',
    'extraction-thinking': 'По-друге, не беріть для видобування модель із міркуванням. Такі моделі витрачають бюджет на роздуми й часто не повертають нічого придатного; проста і швидка модель тут краща.',
    'extraction-recommend': 'Після багатьох перевірок моделі Gemini Flash Lite дали найкраще поєднання швидкості, вартості та надійних результатів саме для цього завдання.',
    'local-models': 'Nodus може запускати моделі й на вашій машині — тоді ніщо не покидає комп’ютер.',
    'local-kinds': 'Є модель для чату, для розшифрування аудіо, для створення зображень і для вбудовувань. Кожна завантажується лише за вашим бажанням.',
    'local-tradeoff': 'Вони приватні й безкоштовні, але повільніші й потребують потужного комп’ютера. Розумний компроміс: локальні моделі для щоденного чату та API для важкого аналізу.',
    'embeddings-what': 'А тепер налаштування, яке більшість оминає: модель вбудовувань, що будує семантичний покажчик ваших матеріалів.',
    'embeddings-why': 'Цей покажчик дає змогу шукати за змістом, а не за точними словами, і саме він знаходить зв’язки та містки між вашими ідеями.',
    'embeddings-warning': 'Без нього семантичний пошук просто нічого не повертає — і тоді порожній результат означає, що сховище не індексували, а не що джерела не торкаються теми.',
    'embeddings-recommend': 'Рекомендація — BGE M3. Він працює локально, дає раду довгим уривкам і працює між мовами, що важливо, коли ваші джерела не всі однією мовою.',
    'images': 'Окрім тексту, Nodus читає зображення й може їх створювати, що допомагає з рисунками, схемами та відсканованими сторінками.',
    'audio': 'Він також розшифровує записи й читає ваші матеріали вголос, тож довгий документ можна послухати, а не читати.',
    'toolkit': 'Toolkit збирає практичні інструменти: конвертування файлів, захист документів, переклад, режим презентації та робоче місце OCR.',
    'mcp-intro': 'Nodus може відкритися й іншим програмам. Сервер MCP дозволяє ШІ-асистенту читати це сховище напряму.',
    'mcp-how': 'Він слухає лише на вашому комп’ютері, тож асистент може шукати у ваших джерелах, читати нотатки й цитувати їх, а ваша бібліотека ніде не публікується.',
    'server-intro': 'Nodus Server робить інше: він підтримує актуальною відфільтровану копію сховища через вихідне з’єднання.',
    'server-how': 'Саме так ви дістаєтеся того самого сховища з іншого пристрою або ділитеся ним, і при цьому на вашій машині не відкривається жоден порт.',
    'plugins': 'Є також плагіни для місць, де ви вже працюєте: Zotero, Microsoft Word і LibreOffice.',
    'nodi-settings': 'І нарешті, ви тут не самі. Nodi — супутник, що ширяє в кутку, і ви можете обрати його вигляд.',
    'nodi-meet': 'Це Nodi.',
    'nodi-open': 'Натисніть — і отримаєте чат, який знає і застосунок, і ваші матеріали, а разом із ним сповіщення та допомогу, коли вона потрібна.',
    'first-setup': 'Надійний спосіб почати — почати з малого. Створіть сховище, підключіть постачальника, оберіть модель вбудовувань і розберіть кілька документів, які ви добре знаєте.',
    'closing': 'Це Nodus. Перевіряйте докази, тримайте матеріали при собі й дайте графу зростати разом із вашим читанням.',
  },
};
