import type { JsonSchema } from '../../../packages/capability-api/src/json';
import type { CapabilityToolV2 } from '../../../packages/capability-api/src/manifest';
const text = {type:'string'} as const;
const position: JsonSchema = {type:'array',items:{type:'number'},minItems:2,maxItems:2};
const source: JsonSchema = {type:'object',properties:{label:text,attribution:text,license:text,url:text,period:{type:'object',properties:{from:text,to:text},required:['from','to'],additionalProperties:false}},required:['label','attribution','license'],additionalProperties:false};
const query: JsonSchema = {type:'object',properties:{provider:{type:'string',enum:['natural-earth','geoboundaries']},country:text,level:{type:'integer',minimum:0,maximum:2},period:{type:'object',properties:{from:text,to:text},required:['from','to'],additionalProperties:false}},required:['provider'],additionalProperties:false};
export const MAP_TOOLS: CapabilityToolV2[] = [
  {id:'retrieve',artifactTypes:[],concurrency:1,answerMode:'replace-block',metered:true,description:'Retrieve approved geographic geometry: natural-earth world countries or geoboundaries ISO alpha-3 country + ADM level 0/1/2. No arbitrary URLs, no historical-date support. Returns geometry and host-owned provenance. Use render with layers[].query to retrieve and draw in one call.',inputSchema:query,billing:'none',timeoutMs:30000,maxPerReply:4},
  {id:'render',artifactTypes:[],concurrency:1,answerMode:'replace-block',metered:true,description:'Create an attributed SVG map from WGS84 [longitude,latitude]. Layers: provider query, scope-owned datasetId, or caller GeoJSON + source. select/colors use exact property matches ($id for IDs). Markers/routes require overlaySource. Connections are not road directions. detail: standard simplification or full geometry. Never claim success before execution.',inputSchema:{type:'object',properties:{
    title:text,alt:text,width:{type:'number',minimum:640,maximum:1600},height:{type:'number',minimum:480,maximum:1400},projection:{type:'string',enum:['equal-earth','mercator','equirectangular']},detail:{type:'string',enum:['standard','full']},centralMeridian:{type:'number',minimum:-180,maximum:180},bounds:{type:'array',items:{type:'number'},minItems:4,maxItems:4},
    layers:{type:'array',maxItems:4,items:{type:'object',properties:{query,datasetId:text,data:{type:'object',properties:{geojson:{type:'object'},source},required:['geojson','source'],additionalProperties:false},select:{type:'object',properties:{property:text,values:{type:'array',items:{},minItems:1,maxItems:5000}},required:['property','values'],additionalProperties:false},fill:text,colors:{type:'object',properties:{property:text,values:{type:'array',items:{type:'object',properties:{value:{},color:text},required:['value','color'],additionalProperties:false},maxItems:1000}},required:['property','values'],additionalProperties:false},labelProperty:text},additionalProperties:false}},
    markers:{type:'array',maxItems:200,items:{type:'object',properties:{coordinates:position,label:text,color:text,radius:{type:'number',minimum:2,maximum:16}},required:['coordinates'],additionalProperties:false}},
    routes:{type:'array',maxItems:100,items:{type:'object',properties:{coordinates:{type:'array',items:position,minItems:2,maxItems:100},kind:{type:'string',enum:['straight','curved','great-circle']},arrow:{type:'boolean'},color:text,width:{type:'number',minimum:1,maximum:12},label:text},required:['coordinates'],additionalProperties:false}},overlaySource:source,
    legend:{type:'array',maxItems:16,items:{type:'object',properties:{label:text,color:text},required:['label','color'],additionalProperties:false}},
  },required:['title','alt'],additionalProperties:false},billing:'none',timeoutMs:30000,maxPerReply:8},
];
