/**
 * The three model-guidance slides (idea extraction, local speed, subscriptions) in
 * every language the essential guide speaks besides Spanish and English, which live
 * with the rest of the Toolkit beta copy. The guide used to fall back to English for
 * these three slides only, so a French or Korean deck switched language halfway.
 *
 * Only the keys the three panels read are here; `toolkitBetaGuideCopy` layers them
 * over English, so a key missing from one language degrades to English, not to blank.
 */
export type ModelGuidanceCopy = {
  extractionEyebrow: string;
  extractionTitle: string;
  extractionSummary: string;
  extractionBody: string;
  gemmaBody: string;
  graniteBody: string;
  gemmaNote: string;
  performanceEyebrow: string;
  performanceTitle: string;
  performanceSummary: string;
  performanceBody: string;
  performanceExample: string;
  subscriptionsEyebrow: string;
  subscriptionsTitle: string;
  subscriptionsSummary: string;
  chatgpt: string;
  copilot: string;
  opencode: string;
  claude: string;
  trademark: string;
  compatible: string;
  apiOnly: string;
};

const ZH_CN: ModelGuidanceCopy = {
  extractionEyebrow: '想法提取',
  extractionTitle: '提取：少一些推理，多一些精确',
  extractionSummary: '提取想法需要一个直接、稳定、能可靠返回结构化数据的模型。',
  extractionBody: '这项任务请避免使用推理模型。它们擅长展开长篇分析，因此通常更慢、更啰嗦，也更容易偏离 Nodus 所需的结构化格式。',
  gemmaBody: '通过内部提取测试的内置本地模型：在一篇约 7,000 字的真实论文上运行 20 次，20 次全部成功，没有出现格式错误。',
  graniteBody: '更轻量，仅支持文本，适合对话、摘要和文档概况。它不用于提取：在端到端测试中，它对大型作品的合并判断不符合 JSON 约定。',
  gemmaNote: '与领先的远程模型相比，Gemma 4 E2B Q4 很小，但选择它是因为它在提取任务上的可靠性，而不是综合智能水平。',
  performanceEyebrow: '本地模型',
  performanceTitle: '速度取决于你的电脑',
  performanceSummary: '本地模型使用你的 CPU 和系统内存；如果可用，也会使用 GPU 和显存（VRAM）或统一内存。',
  performanceBody: 'Nodus 负责安排工作，但无法让性能有限的设备像更快的电脑一样运行。标准模式下，它会把文本切成约 1,800 个词的片段（带少量重叠），并逐步提取想法；不会在一次请求中发送整篇论文或整个章节。',
  performanceExample: '如果每个片段需要 30 秒，而一部作品需要十个片段，提取大约需要五分钟。先用一部作品测试：时间可以接受就继续；否则请改用免费或付费的远程服务商。',
  subscriptionsEyebrow: '官方接入',
  subscriptionsTitle: '也可以使用部分订阅',
  subscriptionsSummary: 'Nodus 支持官方或有文档说明的接入方式，不会把订阅变成通用的 API 密钥。',
  chatgpt: '通过 Codex App Server 官方接入。消耗的是 ChatGPT 套餐中的 Codex 额度或点数，而不是 OpenAI API 余额。',
  copilot: '通过官方 SDK 接入。每次请求都会计入你 GitHub 套餐的额度或高级请求次数。',
  opencode: '使用你的个人密钥和 OpenCode Go 官方端点。适用其自身的限制，余额在 OpenCode Console 中查看。',
  claude: 'Anthropic 禁止第三方接入 Claude.ai 的 Free、Pro 或 Max 订阅。因此 Nodus 只支持通过官方 API 密钥使用 Claude。',
  trademark: 'Nodus 是独立项目，与这些服务商没有隶属关系，也未获得其背书。',
  compatible: '兼容',
  apiOnly: '仅 API',
};

export const MODEL_GUIDANCE_COPY: Record<string, ModelGuidanceCopy> = {
  fr: {
    extractionEyebrow: 'Extraction d’idées',
    extractionTitle: 'Extraction : moins de raisonnement, plus de précision',
    extractionSummary: 'Pour extraire des idées, il faut un modèle direct, discipliné et fiable avec les données structurées.',
    extractionBody: 'Évitez les modèles de raisonnement pour cette tâche. Conçus pour développer de longues analyses, ils répondent souvent plus lentement, plus longuement et s’écartent plus facilement du format structuré dont Nodus a besoin.',
    gemmaBody: 'Le modèle local intégré qui a réussi les tests internes d’extraction : 20 exécutions réussies sur 20 sur un article réel d’environ 7 000 mots, sans aucune erreur de format.',
    graniteBody: 'Plus léger et limité au texte, il convient à la conversation, aux résumés et aux profils de documents. Il n’est pas proposé pour l’extraction : lors des tests de bout en bout, ses décisions de fusion ne respectaient pas le contrat JSON sur les œuvres volumineuses.',
    gemmaNote: 'Gemma 4 E2B Q4 est petit face aux grands modèles distants, mais il a été choisi pour sa fiabilité en extraction, pas pour une mesure générale d’intelligence.',
    performanceEyebrow: 'Modèles locaux',
    performanceTitle: 'La vitesse dépend de votre ordinateur',
    performanceSummary: 'Les modèles locaux utilisent votre processeur, la mémoire du système et, si disponibles, le GPU et la VRAM ou la mémoire unifiée.',
    performanceBody: 'Nodus organise le travail, mais ne peut pas rendre un matériel limité aussi rapide qu’une machine plus puissante. En mode standard, il découpe le texte en fragments d’environ 1 800 mots avec un léger chevauchement et extrait les idées progressivement ; il n’envoie jamais un article ou un chapitre entier en une seule requête.',
    performanceExample: 'Si chaque fragment prend 30 secondes et qu’une œuvre en compte dix, l’extraction durera environ cinq minutes. Testez d’abord une œuvre : continuez si la durée vous convient, sinon choisissez un fournisseur distant gratuit ou payant.',
    subscriptionsEyebrow: 'Accès officiels',
    subscriptionsTitle: 'Vous pouvez aussi utiliser certains abonnements',
    subscriptionsSummary: 'Nodus prend en charge des accès officiels ou documentés, sans transformer votre abonnement en clé API générique.',
    chatgpt: 'Accès officiel via Codex App Server. Il consomme le quota ou les crédits Codex de votre forfait ChatGPT, pas le crédit de l’API OpenAI.',
    copilot: 'Accès via le SDK officiel. Chaque requête est décomptée du quota ou des requêtes premium de votre forfait GitHub.',
    opencode: 'Utilise votre clé personnelle et les points d’accès officiels d’OpenCode Go. Ses limites s’appliquent et le solde se consulte dans OpenCode Console.',
    claude: 'Anthropic interdit aux tiers de connecter les abonnements Claude.ai Free, Pro ou Max. Nodus ne prend donc en charge Claude qu’avec une clé de l’API officielle.',
    trademark: 'Nodus est indépendant et n’est ni affilié ni approuvé par ces fournisseurs.',
    compatible: 'Compatible',
    apiOnly: 'API uniquement',
  },
  de: {
    extractionEyebrow: 'Ideenextraktion',
    extractionTitle: 'Extraktion: weniger Schlussfolgern, mehr Präzision',
    extractionSummary: 'Für die Ideenextraktion eignet sich ein direktes Modell, das zuverlässig strukturierte Daten liefert.',
    extractionBody: 'Vermeiden Sie Reasoning-Modelle für diese Aufgabe. Sie sind für lange Analysen gedacht, antworten daher langsamer und ausführlicher und weichen leichter vom strukturierten Format ab, das Nodus benötigt.',
    gemmaBody: 'Das integrierte lokale Modell, das den internen Extraktionstest bestanden hat: 20 von 20 erfolgreichen Durchläufen mit einem echten Artikel von etwa 7.000 Wörtern, ohne Formatfehler.',
    graniteBody: 'Leichter und nur für Text, geeignet für Gespräche, Zusammenfassungen und Dokumentprofile. Für die Extraktion wird es nicht angeboten: In End-to-End-Tests erfüllten seine Zusammenführungsentscheidungen bei großen Werken den JSON-Vertrag nicht.',
    gemmaNote: 'Gemma 4 E2B Q4 ist klein im Vergleich zu führenden Remote-Modellen, wurde aber wegen seiner Zuverlässigkeit bei der Extraktion gewählt – nicht als allgemeines Maß für Intelligenz.',
    performanceEyebrow: 'Lokale Modelle',
    performanceTitle: 'Die Geschwindigkeit hängt von Ihrem Computer ab',
    performanceSummary: 'Lokale Modelle nutzen Ihre CPU und den Arbeitsspeicher sowie, falls vorhanden, GPU und VRAM oder gemeinsamen Speicher.',
    performanceBody: 'Nodus organisiert die Arbeit, kann aber begrenzte Hardware nicht so schnell machen wie einen leistungsstärkeren Rechner. Im Standardmodus teilt es den Text in Abschnitte von etwa 1.800 Wörtern mit leichter Überlappung und extrahiert die Ideen schrittweise; ein ganzer Artikel oder ein ganzes Kapitel wird nie in einer einzigen Anfrage gesendet.',
    performanceExample: 'Dauert jeder Abschnitt 30 Sekunden und braucht ein Werk zehn davon, dauert die Extraktion etwa fünf Minuten. Testen Sie zuerst ein Werk: Passt die Dauer, fahren Sie fort; sonst wählen Sie einen kostenlosen oder kostenpflichtigen Remote-Anbieter.',
    subscriptionsEyebrow: 'Offizielle Zugänge',
    subscriptionsTitle: 'Auch einige Abonnements lassen sich nutzen',
    subscriptionsSummary: 'Nodus unterstützt offizielle oder dokumentierte Zugänge, ohne ein Abonnement in einen allgemeinen API-Schlüssel zu verwandeln.',
    chatgpt: 'Offizieller Zugang über Codex App Server. Verbraucht das Codex-Kontingent oder die Codex-Credits Ihres ChatGPT-Tarifs, nicht das Guthaben der OpenAI-API.',
    copilot: 'Zugang über das offizielle SDK. Jede Anfrage zählt gegen das Kontingent oder die Premium-Anfragen Ihres GitHub-Tarifs.',
    opencode: 'Nutzt Ihren persönlichen Schlüssel und die offiziellen Endpunkte von OpenCode Go. Dessen Limits gelten, und das Guthaben sehen Sie in der OpenCode Console.',
    claude: 'Anthropic untersagt Drittanbietern, Claude.ai-Abonnements (Free, Pro oder Max) anzubinden. Nodus unterstützt Claude daher nur über einen offiziellen API-Schlüssel.',
    trademark: 'Nodus ist unabhängig und weder mit diesen Anbietern verbunden noch von ihnen empfohlen.',
    compatible: 'Kompatibel',
    apiOnly: 'Nur API',
  },
  it: {
    extractionEyebrow: 'Estrazione di idee',
    extractionTitle: 'Estrazione: meno ragionamento, più precisione',
    extractionSummary: 'Per estrarre idee serve un modello diretto, disciplinato e affidabile con i dati strutturati.',
    extractionBody: 'Evita i modelli di ragionamento per questo compito. Sono pensati per sviluppare analisi estese, quindi tendono a rispondere in modo più lento e prolisso e ad allontanarsi più facilmente dal formato strutturato di cui Nodus ha bisogno.',
    gemmaBody: 'Il modello locale integrato che ha superato i test interni di estrazione: 20 esecuzioni riuscite su 20 su un articolo reale di circa 7.000 parole, senza errori di formato.',
    graniteBody: 'Più leggero e solo testuale, utile per conversazione, riassunti e profili dei documenti. Non è proposto per l’estrazione: nei test end-to-end le sue decisioni di fusione non rispettavano il contratto JSON sulle opere più grandi.',
    gemmaNote: 'Gemma 4 E2B Q4 è piccolo rispetto ai grandi modelli remoti, ma è stato scelto per la sua affidabilità nell’estrazione, non come misura generale di intelligenza.',
    performanceEyebrow: 'Modelli locali',
    performanceTitle: 'La velocità dipende dal tuo computer',
    performanceSummary: 'I modelli locali usano la CPU e la memoria di sistema e, se disponibili, GPU e VRAM o memoria unificata.',
    performanceBody: 'Nodus organizza il lavoro, ma non può rendere un hardware limitato veloce come una macchina più potente. In modalità standard divide il testo in frammenti di circa 1.800 parole, con una piccola sovrapposizione, ed estrae le idee progressivamente; non invia mai un intero articolo o capitolo in una sola richiesta.',
    performanceExample: 'Se ogni frammento richiede 30 secondi e un’opera ne ha dieci, l’estrazione durerà circa cinque minuti. Prova prima con un’opera: se il tempo ti sembra ragionevole continua, altrimenti usa un fornitore remoto gratuito o a pagamento.',
    subscriptionsEyebrow: 'Accessi ufficiali',
    subscriptionsTitle: 'Puoi usare anche alcuni abbonamenti',
    subscriptionsSummary: 'Nodus supporta accessi ufficiali o documentati senza trasformare il tuo abbonamento in una chiave API generica.',
    chatgpt: 'Accesso ufficiale tramite Codex App Server. Consuma la quota o i crediti Codex del tuo piano ChatGPT, non il credito dell’API di OpenAI.',
    copilot: 'Accesso tramite l’SDK ufficiale. Ogni richiesta viene conteggiata nella quota o nelle richieste premium del tuo piano GitHub.',
    opencode: 'Usa la tua chiave personale e gli endpoint ufficiali di OpenCode Go. Si applicano i suoi limiti e il saldo si consulta in OpenCode Console.',
    claude: 'Anthropic vieta a terzi di collegare gli abbonamenti Claude.ai Free, Pro o Max. Per questo Nodus supporta Claude solo tramite una chiave dell’API ufficiale.',
    trademark: 'Nodus è indipendente e non è affiliato né approvato da questi fornitori.',
    compatible: 'Compatibile',
    apiOnly: 'Solo API',
  },
  pt: {
    extractionEyebrow: 'Extração de ideias',
    extractionTitle: 'Extração: menos raciocínio, mais precisão',
    extractionSummary: 'Para extrair ideias convém um modelo direto, disciplinado e fiável com dados estruturados.',
    extractionBody: 'Evite modelos de raciocínio nesta tarefa. Foram pensados para desenvolver análises extensas, por isso tendem a responder de forma mais lenta e longa e a afastar-se com mais facilidade do formato estruturado de que o Nodus precisa.',
    gemmaBody: 'O modelo local integrado que passou nos testes internos de extração: 20 execuções corretas em 20 sobre um artigo real de cerca de 7000 palavras, sem falhas de formato.',
    graniteBody: 'Mais leve e só de texto, útil para conversa, resumos e perfis de documentos. Não é oferecido para extração: nos testes de ponta a ponta, as suas decisões de fusão não cumpriram o contrato JSON em obras grandes.',
    gemmaNote: 'O Gemma 4 E2B Q4 é pequeno face aos grandes modelos remotos, mas foi escolhido pela sua fiabilidade na extração, não como medida geral de inteligência.',
    performanceEyebrow: 'Modelos locais',
    performanceTitle: 'A velocidade depende do seu computador',
    performanceSummary: 'Os modelos locais usam o processador e a memória do sistema e, quando disponíveis, a GPU e a VRAM ou a memória unificada.',
    performanceBody: 'O Nodus organiza o trabalho, mas não consegue tornar um equipamento limitado tão rápido como um mais potente. No modo padrão divide o texto em fragmentos de cerca de 1800 palavras, com uma pequena sobreposição, e extrai as ideias progressivamente; nunca envia um artigo ou capítulo inteiro num só pedido.',
    performanceExample: 'Se cada fragmento demorar 30 segundos e uma obra precisar de dez, a extração levará cerca de cinco minutos. Teste primeiro uma obra: se o tempo lhe parecer razoável, continue; caso contrário, use um fornecedor remoto gratuito ou pago.',
    subscriptionsEyebrow: 'Acessos oficiais',
    subscriptionsTitle: 'Também pode aproveitar algumas subscrições',
    subscriptionsSummary: 'O Nodus suporta acessos oficiais ou documentados sem transformar a sua subscrição numa chave de API genérica.',
    chatgpt: 'Acesso oficial através do Codex App Server. Consome a quota ou os créditos Codex do seu plano ChatGPT, não o saldo da API da OpenAI.',
    copilot: 'Acesso através do SDK oficial. Cada pedido conta para a quota ou os pedidos premium do seu plano GitHub.',
    opencode: 'Usa a sua chave pessoal e os endpoints oficiais do OpenCode Go. Aplicam-se os seus limites e o saldo consulta-se no OpenCode Console.',
    claude: 'A Anthropic proíbe terceiros de ligar subscrições Claude.ai Free, Pro ou Max. Por isso o Nodus só suporta o Claude através de uma chave da API oficial.',
    trademark: 'O Nodus é independente e não é afiliado nem apoiado por estes fornecedores.',
    compatible: 'Compatível',
    apiOnly: 'Só API',
  },
  'pt-BR': {
    extractionEyebrow: 'Extração de ideias',
    extractionTitle: 'Extração: menos raciocínio, mais precisão',
    extractionSummary: 'Para extrair ideias, o ideal é um modelo direto, disciplinado e confiável com dados estruturados.',
    extractionBody: 'Evite modelos de raciocínio nessa tarefa. Eles foram feitos para desenvolver análises longas, então costumam responder de forma mais lenta e extensa e se afastam com mais facilidade do formato estruturado de que o Nodus precisa.',
    gemmaBody: 'O modelo local integrado que passou nos testes internos de extração: 20 execuções corretas em 20 sobre um artigo real de cerca de 7.000 palavras, sem falhas de formato.',
    graniteBody: 'Mais leve e só de texto, útil para conversa, resumos e perfis de documentos. Não é oferecido para extração: nos testes de ponta a ponta, suas decisões de fusão não cumpriram o contrato JSON em obras grandes.',
    gemmaNote: 'O Gemma 4 E2B Q4 é pequeno perto dos grandes modelos remotos, mas foi escolhido pela confiabilidade na extração, não como medida geral de inteligência.',
    performanceEyebrow: 'Modelos locais',
    performanceTitle: 'A velocidade depende do seu computador',
    performanceSummary: 'Os modelos locais usam o processador e a memória do sistema e, quando disponíveis, a GPU e a VRAM ou a memória unificada.',
    performanceBody: 'O Nodus organiza o trabalho, mas não consegue deixar um equipamento limitado tão rápido quanto uma máquina mais potente. No modo padrão, ele divide o texto em trechos de cerca de 1.800 palavras, com uma pequena sobreposição, e extrai as ideias aos poucos; nunca envia um artigo ou capítulo inteiro em uma única solicitação.',
    performanceExample: 'Se cada trecho levar 30 segundos e uma obra precisar de dez, a extração vai durar cerca de cinco minutos. Teste primeiro uma obra: se o tempo parecer razoável, continue; se não, use um provedor remoto gratuito ou pago.',
    subscriptionsEyebrow: 'Acessos oficiais',
    subscriptionsTitle: 'Você também pode usar algumas assinaturas',
    subscriptionsSummary: 'O Nodus aceita acessos oficiais ou documentados sem transformar sua assinatura em uma chave de API genérica.',
    chatgpt: 'Acesso oficial pelo Codex App Server. Consome a cota ou os créditos do Codex do seu plano ChatGPT, não o saldo da API da OpenAI.',
    copilot: 'Acesso pelo SDK oficial. Cada solicitação conta na cota ou nas solicitações premium do seu plano do GitHub.',
    opencode: 'Usa sua chave pessoal e os endpoints oficiais do OpenCode Go. Os limites dele se aplicam e o saldo fica no OpenCode Console.',
    claude: 'A Anthropic proíbe que terceiros conectem assinaturas Claude.ai Free, Pro ou Max. Por isso, o Nodus só aceita o Claude por meio de uma chave da API oficial.',
    trademark: 'O Nodus é independente e não é afiliado nem endossado por esses provedores.',
    compatible: 'Compatível',
    apiOnly: 'Só API',
  },
  tr: {
    extractionEyebrow: 'Fikir çıkarma',
    extractionTitle: 'Çıkarma: daha az akıl yürütme, daha fazla doğruluk',
    extractionSummary: 'Fikir çıkarmak için doğrudan, disiplinli ve yapılandırılmış veride güvenilir bir model gerekir.',
    extractionBody: 'Bu iş için akıl yürütme modellerinden kaçının. Uzun analizler geliştirmek üzere tasarlandıkları için daha yavaş ve uzun yanıt verir, Nodus’un ihtiyaç duyduğu yapılandırılmış biçimden de daha kolay saparlar.',
    gemmaBody: 'Dahili çıkarma testlerini geçen yerleşik yerel model: yaklaşık 7.000 kelimelik gerçek bir makalede 20 çalıştırmanın 20’si başarılı, hiç biçim hatası yok.',
    graniteBody: 'Daha hafif ve yalnızca metin; sohbet, özet ve belge profilleri için kullanışlı. Çıkarma için sunulmaz: uçtan uca testlerde büyük eserlerde birleştirme kararları JSON sözleşmesine uymadı.',
    gemmaNote: 'Gemma 4 E2B Q4, önde gelen uzak modellere göre küçüktür; ancak genel zekâ ölçüsüyle değil, çıkarmadaki güvenilirliği nedeniyle seçildi.',
    performanceEyebrow: 'Yerel modeller',
    performanceTitle: 'Hız bilgisayarınıza bağlıdır',
    performanceSummary: 'Yerel modeller işlemcinizi ve sistem belleğinizi, varsa GPU ve VRAM’i ya da birleşik belleği kullanır.',
    performanceBody: 'Nodus işi düzenler ama sınırlı bir donanımı daha güçlü bir makine kadar hızlı çalıştıramaz. Standart modda metni küçük bir örtüşmeyle yaklaşık 1.800 kelimelik parçalara ayırır ve fikirleri adım adım çıkarır; bir makaleyi veya bölümü asla tek istekte göndermez.',
    performanceExample: 'Her parça 30 saniye sürüyor ve bir eser on parça gerektiriyorsa çıkarma yaklaşık beş dakika sürer. Önce bir eserle deneyin: süre size uygunsa devam edin, değilse ücretsiz ya da ücretli bir uzak sağlayıcı kullanın.',
    subscriptionsEyebrow: 'Resmî erişim',
    subscriptionsTitle: 'Bazı abonelikleri de kullanabilirsiniz',
    subscriptionsSummary: 'Nodus, aboneliğinizi genel bir API anahtarına dönüştürmeden resmî ya da belgelenmiş erişimleri destekler.',
    chatgpt: 'Codex App Server üzerinden resmî erişim. OpenAI API bakiyenizi değil, ChatGPT planınızdaki Codex kotasını veya kredilerini kullanır.',
    copilot: 'Resmî SDK üzerinden erişim. Her istek GitHub planınızın kotasından veya premium isteklerinden düşülür.',
    opencode: 'Kişisel anahtarınızı ve OpenCode Go’nun resmî uç noktalarını kullanır. Onun sınırları geçerlidir; bakiyeniz OpenCode Console’da görünür.',
    claude: 'Anthropic, üçüncü tarafların Claude.ai Free, Pro veya Max aboneliklerini bağlamasını yasaklar. Bu yüzden Nodus Claude’u yalnızca resmî API anahtarıyla destekler.',
    trademark: 'Nodus bağımsızdır; bu sağlayıcılarla bağlantılı değildir ve onlar tarafından onaylanmamıştır.',
    compatible: 'Uyumlu',
    apiOnly: 'Yalnızca API',
  },
  'zh-CN': ZH_CN,
  zh: ZH_CN,
  'zh-TW': {
    extractionEyebrow: '想法擷取',
    extractionTitle: '擷取：少一點推理，多一點精確',
    extractionSummary: '擷取想法需要一個直接、穩定、能可靠回傳結構化資料的模型。',
    extractionBody: '這項任務請避免使用推理模型。它們擅長展開長篇分析，因此通常較慢、較冗長，也更容易偏離 Nodus 所需的結構化格式。',
    gemmaBody: '通過內部擷取測試的內建本機模型：在一篇約 7,000 字的真實論文上執行 20 次，20 次全部成功，沒有任何格式錯誤。',
    graniteBody: '更輕量、只支援文字，適合對話、摘要和文件概況。它不提供擷取用途：在端對端測試中，它對大型作品的合併判斷不符合 JSON 規格。',
    gemmaNote: '與領先的遠端模型相比，Gemma 4 E2B Q4 很小，但選擇它是因為它在擷取上的可靠性，而不是整體智慧程度。',
    performanceEyebrow: '本機模型',
    performanceTitle: '速度取決於你的電腦',
    performanceSummary: '本機模型會使用你的 CPU 和系統記憶體；若有的話，也會使用 GPU 和顯示記憶體（VRAM）或統一記憶體。',
    performanceBody: 'Nodus 負責安排工作，但無法讓效能有限的裝置跑得像更快的電腦。標準模式下，它會把文字切成約 1,800 個詞的片段（帶少量重疊），並逐步擷取想法；不會在單一請求中傳送整篇論文或整個章節。',
    performanceExample: '如果每個片段需要 30 秒，而一部作品需要十個片段，擷取大約需要五分鐘。先用一部作品測試：時間可以接受就繼續；否則請改用免費或付費的遠端供應商。',
    subscriptionsEyebrow: '官方存取',
    subscriptionsTitle: '也可以使用部分訂閱',
    subscriptionsSummary: 'Nodus 支援官方或有文件說明的存取方式，不會把訂閱變成通用的 API 金鑰。',
    chatgpt: '透過 Codex App Server 官方存取。使用的是 ChatGPT 方案中的 Codex 額度或點數，而不是 OpenAI API 餘額。',
    copilot: '透過官方 SDK 存取。每次請求都會計入你 GitHub 方案的額度或進階請求次數。',
    opencode: '使用你的個人金鑰和 OpenCode Go 官方端點。適用其自身的限制，餘額可在 OpenCode Console 查看。',
    claude: 'Anthropic 禁止第三方連接 Claude.ai 的 Free、Pro 或 Max 訂閱。因此 Nodus 只支援透過官方 API 金鑰使用 Claude。',
    trademark: 'Nodus 是獨立專案，與這些供應商沒有隸屬關係，也未獲得其背書。',
    compatible: '相容',
    apiOnly: '僅限 API',
  },
  ja: {
    extractionEyebrow: 'アイデア抽出',
    extractionTitle: '抽出：推論は少なく、精度は高く',
    extractionSummary: 'アイデア抽出には、構造化データを確実に返す素直なモデルが向いています。',
    extractionBody: 'この作業には推論モデルを避けてください。長い分析を展開するよう設計されているため、応答が遅く冗長になりがちで、Nodusが必要とする構造化形式からも外れやすくなります。',
    gemmaBody: '社内の抽出テストに合格した内蔵ローカルモデルです。約7,000語の実際の論文で20回中20回成功し、形式エラーは一度もありませんでした。',
    graniteBody: 'より軽量でテキスト専用。会話、要約、文書プロファイルに便利です。抽出には提供されません。エンドツーエンドのテストで、大きな作品における統合判断がJSONの規約を満たさなかったためです。',
    gemmaNote: 'Gemma 4 E2B Q4は主要なリモートモデルと比べると小さなモデルですが、一般的な賢さではなく、抽出における信頼性で選ばれています。',
    performanceEyebrow: 'ローカルモデル',
    performanceTitle: '速度はお使いのコンピューター次第です',
    performanceSummary: 'ローカルモデルはCPUとシステムメモリを使い、利用できる場合はGPUとVRAM、またはユニファイドメモリも使います。',
    performanceBody: 'Nodusは作業を段取りしますが、性能の限られたハードウェアを高速なマシンのように動かすことはできません。標準モードでは、テキストを少し重なりのある約1,800語の断片に分け、アイデアを順に抽出します。論文や章を丸ごと1回のリクエストで送ることはありません。',
    performanceExample: '1つの断片に30秒かかり、1作品に10個の断片が必要なら、抽出にはおよそ5分かかります。まず1作品で試し、時間が許容範囲なら続けてください。そうでなければ、無料または有料のリモートプロバイダーを使いましょう。',
    subscriptionsEyebrow: '公式アクセス',
    subscriptionsTitle: '一部のサブスクリプションも使えます',
    subscriptionsSummary: 'Nodusは、サブスクリプションを汎用のAPIキーに変えることなく、公式または文書化されたアクセス方法に対応しています。',
    chatgpt: 'Codex App Server経由の公式アクセスです。OpenAI APIの残高ではなく、ChatGPTプランのCodex利用枠またはクレジットを消費します。',
    copilot: '公式SDK経由のアクセスです。各リクエストはGitHubプランの利用枠またはプレミアムリクエストとして計上されます。',
    opencode: '個人キーとOpenCode Goの公式エンドポイントを使います。同サービスの制限が適用され、残高はOpenCode Consoleで確認できます。',
    claude: 'Anthropicは、第三者がClaude.aiのFree、Pro、Maxサブスクリプションに接続することを禁止しています。そのためNodusは、公式APIキーによるClaudeのみに対応しています。',
    trademark: 'Nodusは独立したプロジェクトであり、これらのプロバイダーとは提携しておらず、承認も受けていません。',
    compatible: '対応',
    apiOnly: 'APIのみ',
  },
  ko: {
    extractionEyebrow: '아이디어 추출',
    extractionTitle: '추출: 추론은 줄이고 정확도는 높이고',
    extractionSummary: '아이디어 추출에는 구조화된 데이터를 안정적으로 돌려주는 직관적인 모델이 좋습니다.',
    extractionBody: '이 작업에는 추론 모델을 피하세요. 긴 분석을 전개하도록 설계되어 응답이 느리고 장황해지기 쉬우며, Nodus가 필요로 하는 구조화된 형식에서도 더 쉽게 벗어납니다.',
    gemmaBody: '내부 추출 테스트를 통과한 내장 로컬 모델입니다. 약 7,000단어 분량의 실제 논문에서 20번 중 20번 성공했고, 형식 오류는 한 번도 없었습니다.',
    graniteBody: '더 가볍고 텍스트 전용이라 대화, 요약, 문서 프로필에 유용합니다. 추출용으로는 제공되지 않습니다. 엔드투엔드 테스트에서 큰 작품의 병합 판단이 JSON 규약을 지키지 못했기 때문입니다.',
    gemmaNote: 'Gemma 4 E2B Q4는 주요 원격 모델에 비하면 작지만, 전반적인 지능이 아니라 추출에서의 신뢰성 때문에 선택되었습니다.',
    performanceEyebrow: '로컬 모델',
    performanceTitle: '속도는 컴퓨터 성능에 달려 있습니다',
    performanceSummary: '로컬 모델은 CPU와 시스템 메모리를 사용하며, 가능하면 GPU와 VRAM 또는 통합 메모리도 사용합니다.',
    performanceBody: 'Nodus는 작업을 조율하지만, 성능이 제한된 하드웨어를 더 빠른 컴퓨터처럼 만들 수는 없습니다. 표준 모드에서는 텍스트를 약간 겹치는 약 1,800단어 단위로 나누어 아이디어를 차례로 추출하며, 논문이나 장 전체를 한 번의 요청으로 보내지 않습니다.',
    performanceExample: '조각 하나에 30초가 걸리고 작품 하나에 조각이 열 개 필요하다면 추출에는 약 5분이 걸립니다. 먼저 작품 하나로 시험해 보세요. 시간이 괜찮다면 계속하고, 그렇지 않다면 무료 또는 유료 원격 공급자를 사용하세요.',
    subscriptionsEyebrow: '공식 접속',
    subscriptionsTitle: '일부 구독도 활용할 수 있습니다',
    subscriptionsSummary: 'Nodus는 구독을 범용 API 키로 바꾸지 않고, 공식적이거나 문서화된 접속 방식을 지원합니다.',
    chatgpt: 'Codex App Server를 통한 공식 접속입니다. OpenAI API 잔액이 아니라 ChatGPT 요금제의 Codex 사용량 또는 크레딧을 사용합니다.',
    copilot: '공식 SDK를 통한 접속입니다. 요청마다 GitHub 요금제의 사용 한도 또는 프리미엄 요청에서 차감됩니다.',
    opencode: '개인 키와 OpenCode Go의 공식 엔드포인트를 사용합니다. 해당 서비스의 한도가 적용되며, 잔액은 OpenCode Console에서 확인합니다.',
    claude: 'Anthropic은 제3자가 Claude.ai Free, Pro, Max 구독을 연결하는 것을 금지합니다. 따라서 Nodus는 공식 API 키를 통해서만 Claude를 지원합니다.',
    trademark: 'Nodus는 독립 프로젝트이며 이 공급자들과 제휴하거나 승인을 받지 않았습니다.',
    compatible: '호환',
    apiOnly: 'API 전용',
  },
  ru: {
    extractionEyebrow: 'Извлечение идей',
    extractionTitle: 'Извлечение: меньше рассуждений, больше точности',
    extractionSummary: 'Для извлечения идей нужна прямолинейная модель, которая надёжно возвращает структурированные данные.',
    extractionBody: 'Не используйте для этой задачи модели с рассуждениями. Они созданы для развёрнутого анализа, поэтому отвечают медленнее и многословнее и легче отходят от структурированного формата, который нужен Nodus.',
    gemmaBody: 'Встроенная локальная модель, прошедшая внутренние тесты извлечения: 20 успешных запусков из 20 на реальной статье примерно в 7000 слов без единой ошибки формата.',
    graniteBody: 'Легче и работает только с текстом; подходит для диалога, кратких изложений и профилей документов. Для извлечения не предлагается: в сквозных тестах её решения о слиянии на больших работах не соответствовали контракту JSON.',
    gemmaNote: 'Gemma 4 E2B Q4 невелика по сравнению с ведущими удалёнными моделями, но выбрана за надёжность при извлечении, а не как мерило общего интеллекта.',
    performanceEyebrow: 'Локальные модели',
    performanceTitle: 'Скорость зависит от вашего компьютера',
    performanceSummary: 'Локальные модели используют процессор и оперативную память, а при наличии — GPU и видеопамять (VRAM) или единую память.',
    performanceBody: 'Nodus организует работу, но не может заставить слабое оборудование работать как более мощный компьютер. В стандартном режиме текст делится на фрагменты примерно по 1800 слов с небольшим перекрытием, и идеи извлекаются постепенно; статья или глава никогда не отправляется целиком одним запросом.',
    performanceExample: 'Если каждый фрагмент обрабатывается 30 секунд, а в работе их десять, извлечение займёт около пяти минут. Сначала попробуйте одну работу: если время устраивает, продолжайте, если нет — выберите бесплатного или платного удалённого провайдера.',
    subscriptionsEyebrow: 'Официальный доступ',
    subscriptionsTitle: 'Можно использовать и некоторые подписки',
    subscriptionsSummary: 'Nodus поддерживает официальные или документированные способы доступа, не превращая подписку в универсальный API-ключ.',
    chatgpt: 'Официальный доступ через Codex App Server. Расходуется квота или кредиты Codex вашего тарифа ChatGPT, а не баланс API OpenAI.',
    copilot: 'Доступ через официальный SDK. Каждый запрос учитывается в квоте или премиум-запросах вашего тарифа GitHub.',
    opencode: 'Использует ваш личный ключ и официальные конечные точки OpenCode Go. Действуют его ограничения, а баланс виден в OpenCode Console.',
    claude: 'Anthropic запрещает сторонним приложениям подключать подписки Claude.ai Free, Pro или Max. Поэтому Nodus поддерживает Claude только через официальный API-ключ.',
    trademark: 'Nodus — независимый проект, не связанный с этими провайдерами и не одобренный ими.',
    compatible: 'Поддерживается',
    apiOnly: 'Только API',
  },
  uk: {
    extractionEyebrow: 'Видобування ідей',
    extractionTitle: 'Видобування: менше міркувань, більше точності',
    extractionSummary: 'Для видобування ідей потрібна пряма модель, яка надійно повертає структуровані дані.',
    extractionBody: 'Не використовуйте для цього завдання моделі з міркуваннями. Вони створені для розгорнутого аналізу, тож відповідають повільніше й багатослівніше та легше відходять від структурованого формату, потрібного Nodus.',
    gemmaBody: 'Вбудована локальна модель, що пройшла внутрішні тести видобування: 20 успішних запусків із 20 на реальній статті приблизно на 7000 слів без жодної помилки формату.',
    graniteBody: 'Легша й працює лише з текстом; корисна для розмови, підсумків і профілів документів. Для видобування не пропонується: у наскрізних тестах її рішення про злиття на великих працях не відповідали контракту JSON.',
    gemmaNote: 'Gemma 4 E2B Q4 невелика порівняно з провідними віддаленими моделями, але її обрано за надійність у видобуванні, а не як мірило загального інтелекту.',
    performanceEyebrow: 'Локальні моделі',
    performanceTitle: 'Швидкість залежить від вашого комп’ютера',
    performanceSummary: 'Локальні моделі використовують процесор і оперативну пам’ять, а за наявності — GPU та відеопам’ять (VRAM) або спільну пам’ять.',
    performanceBody: 'Nodus організовує роботу, але не може змусити слабке обладнання працювати як потужніший комп’ютер. У стандартному режимі текст ділиться на фрагменти приблизно по 1800 слів із невеликим перекриттям, а ідеї видобуваються поступово; стаття чи розділ ніколи не надсилається цілком одним запитом.',
    performanceExample: 'Якщо кожен фрагмент обробляється 30 секунд, а праця містить десять фрагментів, видобування триватиме близько п’яти хвилин. Спершу спробуйте одну працю: якщо час прийнятний, продовжуйте; якщо ні — оберіть безкоштовного чи платного віддаленого постачальника.',
    subscriptionsEyebrow: 'Офіційний доступ',
    subscriptionsTitle: 'Можна використовувати й деякі підписки',
    subscriptionsSummary: 'Nodus підтримує офіційні або задокументовані способи доступу, не перетворюючи підписку на універсальний API-ключ.',
    chatgpt: 'Офіційний доступ через Codex App Server. Витрачається квота або кредити Codex вашого тарифу ChatGPT, а не баланс API OpenAI.',
    copilot: 'Доступ через офіційний SDK. Кожен запит враховується в квоті або преміум-запитах вашого тарифу GitHub.',
    opencode: 'Використовує ваш особистий ключ і офіційні кінцеві точки OpenCode Go. Діють його обмеження, а баланс видно в OpenCode Console.',
    claude: 'Anthropic забороняє стороннім застосункам підключати підписки Claude.ai Free, Pro або Max. Тому Nodus підтримує Claude лише через офіційний API-ключ.',
    trademark: 'Nodus — незалежний проєкт, не пов’язаний із цими постачальниками та не схвалений ними.',
    compatible: 'Підтримується',
    apiOnly: 'Лише API',
  },
};
