import { useCallback, useEffect, useState } from 'react';
import type { ProsopPopulationWorkspace } from '@shared/prosopography';
import { Icon } from './ui';
import { errorText, t, tx } from '../i18n';

const field='w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm dark:border-neutral-700 dark:bg-neutral-950';
export function ProsopCohortsPanel({tab,population}:{tab:'cohorts'|'coverage';population:ProsopPopulationWorkspace}){
  const [data,setData]=useState<Awaited<ReturnType<typeof window.nodus.getProsopMembershipWorkspace>>|null>(null);
  const [people,setPeople]=useState<Awaited<ReturnType<typeof window.nodus.getProsopIdentityWorkspace>>['persons']>([]);
  const [personId,setPersonId]=useState('');const [status,setStatus]=useState<'candidate'|'included'|'excluded'|'uncertain'>('candidate');const [rationale,setRationale]=useState('');
  const [cohortName,setCohortName]=useState('');const [kind,setKind]=useState<'dynamic'|'frozen'>('dynamic');const [error,setError]=useState('');
  const load=useCallback(async()=>{try{const [next,identity]=await Promise.all([window.nodus.getProsopMembershipWorkspace(),window.nodus.getProsopIdentityWorkspace()]);setData(next);setPeople(identity.persons.filter((item)=>item.identityStatus!=='merged'));setPersonId((value)=>value||identity.persons[0]?.personId||'');}catch(cause){setError(errorText(cause));}},[]);
  useEffect(()=>{void load();},[load]);
  const method=population.methodologies.find((item)=>item.status==='published');const questionnaire=population.questionnaires.find((item)=>item.status==='published');
  const act=async(action:()=>Promise<unknown>)=>{setError('');try{await action();await load();}catch(cause){setError(errorText(cause));}};
  if(!data)return <div className="grid h-40 place-items-center"><Icon name="sync" className="animate-spin"/></div>;
  if(tab==='coverage'){const cards=[['Personas',data.coverage.totalPersons],['Incluidas',data.coverage.included],['Excluidas',data.coverage.excluded],['Candidatas',data.coverage.candidate],['Inciertas',data.coverage.uncertain],['Observaciones revisadas',data.coverage.reviewedStatements],['Ausencias razonadas',data.coverage.missingValues]];return <section className="rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900/45" data-testid="prosop-coverage-panel"><h2 className="font-semibold">{t('Cobertura auditable')}</h2><p className="mt-1 text-xs text-neutral-500">{t('Distingue falta de investigación, silencio documental y exclusión.')}</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label,value])=><article key={String(label)} className="rounded-xl bg-neutral-50 p-4 dark:bg-neutral-950"><p className="text-[10px] uppercase text-neutral-400">{t(String(label))}</p><p className="mt-2 text-2xl font-semibold">{value}</p></article>)}</div></section>;}
  return <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_380px]" data-testid="prosop-cohorts-panel"><section className="rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900/45"><h2 className="font-semibold">{t('Decisiones de pertenencia')}</h2><p className="mt-1 text-xs text-neutral-500">{t('Cada estado queda ligado a la versión metodológica y a una justificación.')}</p>{error&&<p role="alert" className="mt-3 text-xs text-red-600">{error}</p>}<div className="mt-4 grid gap-3 sm:grid-cols-2"><select className={field} value={personId} onChange={(event)=>setPersonId(event.target.value)}>{people.map((item)=><option key={item.personId} value={item.personId}>{item.displayName}</option>)}</select><select className={field} value={status} onChange={(event)=>setStatus(event.target.value as typeof status)}>{['candidate','included','excluded','uncertain'].map((value)=><option key={value} value={value}>{t(value)}</option>)}</select><textarea className={`${field} min-h-20 sm:col-span-2`} placeholder={t('Justificación y evidencia')} value={rationale} onChange={(event)=>setRationale(event.target.value)}/><button disabled={!method||!personId||!rationale.trim()} className="btn bg-blue-600 text-white sm:col-span-2" onClick={()=>void act(()=>window.nodus.saveProsopMembership({personId,methodologyVersionId:method!.versionId,status,decision:status,rationale,assessments:[]}))}>{t('Guardar decisión')}</button></div><div className="mt-5 overflow-hidden rounded-xl border border-neutral-200 dark:border-neutral-800">{data.memberships.map((item)=><div key={item.membershipId} className="flex items-center justify-between border-b border-neutral-200 px-4 py-3 last:border-0 dark:border-neutral-800"><span className="text-sm">{people.find((person)=>person.personId===item.personId)?.displayName??item.personId}</span><span className="rounded-full bg-neutral-100 px-2 py-1 text-[10px] dark:bg-neutral-800">{t(item.status)}</span></div>)}</div></section>
  <aside className="rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900/45"><h2 className="font-semibold">{t('Cohortes reproducibles')}</h2><p className="mt-1 text-xs text-neutral-500">{t('La dinámica se recalcula; la congelada conserva exactamente sus integrantes.')}</p><div className="mt-4 space-y-2"><input className={field} placeholder={t('Nombre de la cohorte')} value={cohortName} onChange={(event)=>setCohortName(event.target.value)}/><select className={field} value={kind} onChange={(event)=>setKind(event.target.value as typeof kind)}><option value="dynamic">{t('Dinámica')}</option><option value="frozen">{t('Congelada')}</option></select><button disabled={!cohortName.trim()||!method||!questionnaire} className="btn w-full bg-blue-600 text-white" onClick={()=>void act(async()=>{await window.nodus.saveProsopCohort({name:cohortName,kind,description:'',filter:{conjunction:'and',rules:[{field:'membershipStatus',operator:'eq',value:'included'}]},methodologyVersionId:method!.versionId,questionnaireVersionId:questionnaire!.questionnaireVersionId});setCohortName('');})}>{t('Crear cohorte')}</button></div><div className="mt-5 space-y-2">{data.cohorts.map((item)=><article key={item.cohortId} className="rounded-xl border border-neutral-200 p-3 dark:border-neutral-800"><div className="flex items-center justify-between"><div><p className="text-sm font-medium">{item.name}</p><p className="mt-1 text-[10px] text-neutral-500">{tx('{count} integrantes · {kind}',{count:item.memberIds.length,kind:t(item.kind)})}</p></div>{item.kind==='dynamic'&&<button aria-label={t('Recalcular')} className="rounded p-2 text-blue-600" onClick={()=>void act(()=>window.nodus.refreshProsopDynamicCohort(item.cohortId))}><Icon name="sync" size={14}/></button>}</div></article>)}</div></aside></div>;
}
