import crypto from 'node:crypto';
import type { ProsopInvariantIssue } from '@shared/prosopography';
import { toProsopIpif } from '@shared/prosopographyInterchange';
import { getDb } from './database';
import { getProsopIdentityWorkspace } from './prosopIdentityRepo';
import { getProsopObservationsWorkspace } from './prosopFactoidsRepo';
import { listProsopSources } from './prosopSourcesRepo';
import { describeSyncCoverage } from './syncTables';

export function exportProsopLongRows():Array<Record<string,unknown>>{const db=getDb();return db.prepare(`SELECT e.entity_id AS person_id,s.variable_id,s.statement_type,s.value_kind,s.literal_value,s.value_text,s.value_number,s.value_boolean,s.value_date_display,s.value_term_id,s.value_person_id,s.value_place_id,s.value_organization_id,s.value_event_id,s.negated,s.source_modality,s.reading_certainty,s.source_assertion_certainty,s.interpretation_certainty,s.status AS statement_status,s.statement_id,s.factoid_id,f.source_id,f.source_segment_id,g.locator_display,src.title AS source_title,src.citation FROM prosop_statements s JOIN prosop_factoids f ON f.factoid_id=s.factoid_id JOIN prosop_sources src ON src.source_id=f.source_id JOIN prosop_source_segments g ON g.segment_id=f.source_segment_id LEFT JOIN prosop_statement_entities e ON e.statement_id=s.statement_id AND e.entity_kind='person' AND e.role IN ('subject','principal','self') LEFT JOIN prosop_person_profiles p ON p.person_id=e.entity_id LEFT JOIN prosop_variable_revisions v ON v.revision_id=s.variable_revision_id WHERE COALESCE(p.privacy_status,'ordinary')!='restricted' AND COALESCE(v.sensitivity,'ordinary')!='restricted' ORDER BY e.entity_id,s.variable_id,s.statement_id`).all() as Array<Record<string,unknown>>;}
export function exportProsopIpif(){const identity=getProsopIdentityWorkspace(),sources=listProsopSources(),observations=getProsopObservationsWorkspace();const people=identity.persons.filter((person)=>person.privacyStatus!=='restricted');const allowedPeople=new Set(people.map((person)=>person.personId));const restrictedRevisions=new Set((getDb().prepare("SELECT revision_id FROM prosop_variable_revisions WHERE sensitivity='restricted'").all() as Array<{revision_id:string}>).map((item)=>item.revision_id));const statements=observations.factoids.flatMap((item)=>item.statements).filter((statement)=>!statement.variableRevisionId||!restrictedRevisions.has(statement.variableRevisionId)).filter((statement)=>!statement.entities.some((entity)=>entity.entityKind==='person'&&!allowedPeople.has(entity.entityId)));const statementIds=new Set(statements.map((statement)=>statement.statementId));const factoidIds=new Set(statements.map((statement)=>statement.factoidId));return toProsopIpif({people:people.map((person)=>({personId:person.personId,names:[person.displayName,...person.attestations.map((item)=>item.literalName)]})),sources,segments:sources.flatMap((item)=>item.segments),factoids:observations.factoids.filter((item)=>factoidIds.has(item.factoidId)),statements,entities:observations.factoids.flatMap((item)=>item.statements.flatMap((statement)=>statement.entities)).filter((entity)=>statementIds.has(entity.statementId))});}
export function auditProsopIntegrity():{ok:boolean;issues:ProsopInvariantIssue[];checksum:string;syncCoverage:ReturnType<typeof describeSyncCoverage>}{const db=getDb(),issues:ProsopInvariantIssue[]=[];const checks:[string,string,string,string][]=[["statement_without_factoid","SELECT statement_id AS id FROM prosop_statements WHERE factoid_id NOT IN (SELECT factoid_id FROM prosop_factoids)","Statement sin factoid.","error"],["factoid_without_source","SELECT factoid_id AS id FROM prosop_factoids WHERE source_id NOT IN (SELECT source_id FROM prosop_sources) OR source_segment_id NOT IN (SELECT segment_id FROM prosop_source_segments)","Factoid sin fuente o segmento.","error"],["explicit_edge_without_evidence","SELECT edge_id AS id FROM prosop_network_edges WHERE origin='explicit' AND edge_id NOT IN (SELECT edge_id FROM prosop_network_edge_factoids)","Arista explícita sin evidencia.","error"],["derived_edge_without_fingerprint","SELECT edge_id AS id FROM prosop_network_edges WHERE origin='derived' AND derivation_fingerprint IS NULL","Arista derivada sin huella.","error"],["frozen_cohort_without_snapshot","SELECT cohort_id AS id FROM prosop_cohorts WHERE kind='frozen' AND frozen_at IS NULL","Cohorte congelada sin fecha.","error"]];for(const [code,sql,message,severity] of checks)(db.prepare(sql).all() as Array<{id:string}>).forEach((row)=>issues.push({code,entityId:row.id,message,severity:severity as 'error'}));const quick=(db.pragma('quick_check') as Array<{quick_check:string}>).map((row)=>row.quick_check);if(quick.some((item)=>item!=='ok'))issues.push({code:'sqlite_integrity',entityId:'database',message:quick.join('; '),severity:'error'});const canonical={study:db.prepare('SELECT * FROM prosop_studies ORDER BY study_id').all(),factoids:db.prepare('SELECT * FROM prosop_factoids ORDER BY factoid_id').all(),statements:db.prepare('SELECT * FROM prosop_statements ORDER BY statement_id').all(),memberships:db.prepare('SELECT * FROM prosop_population_memberships ORDER BY membership_id').all()};const checksum=crypto.createHash('sha256').update(JSON.stringify(canonical)).digest('hex');return{ok:!issues.some((item)=>item.severity==='error'),issues,checksum,syncCoverage:describeSyncCoverage()};}
