import { getDb } from './database';
import { updateProsopStudy, createProsopMethodologyDraft, replaceProsopCriteria, publishProsopMethodology } from './prosopStudyRepo';
import { createProsopQuestionnaireDraft, publishProsopQuestionnaire, saveProsopVariableRevision, saveProsopVocabulary, saveProsopVocabularyTerm } from './prosopQuestionnaireRepo';
import { saveProsopSource, saveProsopSourceSegment } from './prosopSourcesRepo';
import { createProsopPerson, saveProsopNameAttestation } from './prosopIdentityRepo';
import { saveProsopFactoid } from './prosopFactoidsRepo';
import { saveProsopCohort, saveProsopMembership } from './prosopMembershipRepo';
import { saveProsopNetworkEdge, saveProsopNetworkLayer } from './prosopNetworksRepo';

export function seedProsopDemo():{seeded:boolean;message:string}{
  const db=getDb();if(db.prepare("SELECT 1 FROM prosop_sources WHERE reference_code='DEMO-PROSOP-1'").get())return{seeded:false,message:'La demo prosopográfica ya existe.'};
  if((db.prepare('SELECT COUNT(*) AS c FROM prosop_studies').get() as {c:number}).c>0&&(db.prepare('SELECT COUNT(*) AS c FROM prosop_factoids').get() as {c:number}).c>0)throw new Error('La demo solo puede añadirse a un vault sin observaciones.');
  updateProsopStudy({title:'Mujeres de letras en Madrid, 1620–1680',researchQuestion:'¿Cómo circularon las escritoras por academias y redes epistolares?',populationDefinition:'Mujeres con actividad literaria documentada en Madrid entre 1620 y 1680.',temporalScope:'1620–1680',geographicScope:'Madrid',samplingStrategy:'Exhaustiva dentro del corpus seleccionado.',sourceStrategy:'Actas académicas y correspondencia.',knownBiases:'Conservación desigual de cartas y actas.'});
  const method=createProsopMethodologyDraft('demo');const criteria=replaceProsopCriteria(method.versionId,[{kind:'include',label:'Actividad literaria documentada',required:true,weight:1},{kind:'exclude',label:'Sin evidencia dentro del periodo',required:false,weight:1}]);publishProsopMethodology(method.versionId,'Metodología de demostración','demo');
  const vocabulary=saveProsopVocabulary({name:'Ocupaciones históricas',version:'1'});const poet=saveProsopVocabularyTerm({vocabularyId:vocabulary.vocabularyId,code:'poeta',preferredLabel:'Poeta',definition:'Término normalizado de demostración.'});
  const questionnaire=createProsopQuestionnaireDraft({title:'Cuestionario común',createdBy:'demo'});const occupation=saveProsopVariableRevision(questionnaire.questionnaireVersionId,{key:'occupation',label:'Ocupación',question:'¿Qué ocupación atribuye la fuente?',valueType:'term',cardinality:'many',vocabularyId:vocabulary.vocabularyId});publishProsopQuestionnaire(questionnaire.questionnaireVersionId,'Cuestionario de demostración','demo');
  const source=saveProsopSource({title:'Actas de la Academia de Madrid',sourceKind:'acta',citation:'Demo Nodus, Actas, libro I',repository:'Corpus de demostración',referenceCode:'DEMO-PROSOP-1',date:{display:'1642',startSort:1642,endSort:1642},coverageNotes:'Dos sesiones de ejemplo.',reliabilityNotes:'Transcripción ficticia para aprender el flujo.',accessStatus:'open'});const segment=saveProsopSourceSegment({sourceId:source.sourceId,locatorDisplay:'fol. 12r',locator:{folio:'12r'},quotedText:'Doña Ana de Carvajal leyó versos y escribió a María de Zayas.',transcriptionStatus:'literal',language:'es'});
  const ana=createProsopPerson({displayName:'Ana de Carvajal',preferredNameBasis:'Actas, fol. 12r'});const maria=createProsopPerson({displayName:'María de Zayas',preferredNameBasis:'Actas, fol. 12r'});saveProsopNameAttestation({sourceId:source.sourceId,sourceSegmentId:segment.segmentId,literalName:'Doña Ana de Carvajal',personId:ana.personId,context:'Leyó versos.'});saveProsopNameAttestation({sourceId:source.sourceId,sourceSegmentId:segment.segmentId,literalName:'María de Zayas',personId:maria.personId,context:'Destinataria de una carta.'});
  const factoid=saveProsopFactoid({sourceId:source.sourceId,sourceSegmentId:segment.segmentId,factoidKind:'activity',summary:'Lectura y correspondencia',status:'reviewed',createdBy:'demo',reviewedBy:'demo',statements:[{statementType:'occupation',variableId:occupation.variableId,variableRevisionId:occupation.revisionId,literalValue:'leyó versos',value:{kind:'term',termId:poet.termId,literal:'leyó versos'},entities:[{entityKind:'person',entityId:ana.personId,role:'subject',position:0}]},{statementType:'correspondence',literalValue:'escribió a',value:{kind:'person',personId:maria.personId,literal:'María de Zayas'},entities:[{entityKind:'person',entityId:ana.personId,role:'subject',position:0},{entityKind:'person',entityId:maria.personId,role:'object',position:1}]}]});
  for(const person of [ana,maria])saveProsopMembership({personId:person.personId,methodologyVersionId:method.versionId,status:'included',decision:'included',rationale:'Cumple el criterio en la fuente de demostración.',decidedBy:'demo',assessments:[{criterionId:criteria[0].criterionId,result:'met',factoidId:factoid.factoidId}]});
  saveProsopCohort({name:'Población incluida',kind:'frozen',filter:{conjunction:'and',rules:[{field:'membershipStatus',operator:'eq',value:'included'}]},methodologyVersionId:method.versionId,questionnaireVersionId:questionnaire.questionnaireVersionId});
  const layer=saveProsopNetworkLayer({name:'Correspondencia explícita',kind:'correspondence',directionality:'directed',color:'#2563eb'});saveProsopNetworkEdge({layerId:layer.layerId,sourcePersonId:ana.personId,targetPersonId:maria.personId,origin:'explicit',factoidIds:[factoid.factoidId],weight:1,date:{display:'1642',startSort:1642,endSort:1642}});
  return{seeded:true,message:'Demo prosopográfica creada.'};
}
