import { v4 as uuid } from 'uuid';
import type { JsonValue, ProsopAnalysisDefinitionRecord, ProsopAnalysisRunRecord, ProsopAnalysisWorkspace, ProsopProjectionDefinition } from '@shared/prosopography';
import { buildProsopProjection, projectionMatrix } from '@shared/prosopographyProjection';
import { prosopCrosstab, prosopFrequencies } from '@shared/prosopographyAnalysis';
import { getDb } from './database';
import { getProsopObservationsWorkspace } from './prosopFactoidsRepo';
import { ensureProsopStudy } from './prosopStudyRepo';

const now=()=>new Date().toISOString();const id=(prefix:string)=>`${prefix}_${uuid()}`;
const asJson=(value:unknown):JsonValue=>JSON.parse(JSON.stringify(value)) as JsonValue;
function runRecord(row:Record<string,unknown>):ProsopAnalysisRunRecord{return{runId:String(row.run_id),analysisId:String(row.analysis_id),engineVersion:String(row.engine_version),inputFingerprint:String(row.input_fingerprint),populationCount:Number(row.population_count),includedCount:Number(row.included_count),missingSummary:JSON.parse(String(row.missing_summary_json)),result:JSON.parse(String(row.result_json)),warnings:JSON.parse(String(row.warnings_json)),createdAt:String(row.created_at)};}
function definition(row:Record<string,unknown>):ProsopAnalysisDefinitionRecord{return{analysisId:String(row.analysis_id),title:String(row.title),analysisKind:row.analysis_kind as ProsopAnalysisDefinitionRecord['analysisKind'],cohortIds:JSON.parse(String(row.cohort_ids_json)),projection:JSON.parse(String(row.projection_json)),filter:JSON.parse(String(row.filter_json)),questionnaireVersionId:String(row.questionnaire_version_id),sourceCutoff:row.source_cutoff==null?null:String(row.source_cutoff),createdBy:String(row.created_by),createdAt:String(row.created_at),updatedAt:String(row.updated_at)};}
export function getProsopAnalysisWorkspace():ProsopAnalysisWorkspace{const db=getDb();return{definitions:(db.prepare('SELECT * FROM prosop_analysis_definitions ORDER BY updated_at DESC').all() as Record<string,unknown>[]).map(definition).map((item)=>({...item,runs:(db.prepare('SELECT * FROM prosop_analysis_runs WHERE analysis_id=? ORDER BY created_at DESC').all(item.analysisId) as Record<string,unknown>[]).map(runRecord)}))};}

export function runProsopAnalysis(input:{analysisId?:string;title:string;analysisKind:ProsopAnalysisDefinitionRecord['analysisKind'];personIds?:string[];variableIds:string[];cohortIds?:string[];createdBy?:string;policies?:ProsopProjectionDefinition['variablePolicies']}):ProsopAnalysisRunRecord{
  if(!input.title.trim()||!input.variableIds.length)throw new Error('El análisis necesita título y al menos una variable.');
  const db=getDb();const analysisId=input.analysisId??id('pan');const previous=db.prepare('SELECT created_at,source_cutoff FROM prosop_analysis_definitions WHERE analysis_id=?').get(analysisId) as {created_at:string;source_cutoff:string|null}|undefined;const study=ensureProsopStudy();if(!study.currentQuestionnaireVersionId||!study.currentMethodologyVersionId)throw new Error('Publica metodología y cuestionario antes de analizar.');
  const personIds=input.personIds?.length?input.personIds:(db.prepare("SELECT person_id FROM prosop_population_memberships WHERE methodology_version_id=? AND status='included' ORDER BY person_id").all(study.currentMethodologyVersionId) as Array<{person_id:string}>).map((item)=>item.person_id);
  const sourceIds=(db.prepare('SELECT source_id FROM prosop_sources ORDER BY source_id').all() as Array<{source_id:string}>).map((item)=>item.source_id);
  const projectionDefinition:ProsopProjectionDefinition={grain:'person',personIds,variableIds:input.variableIds,questionnaireVersionId:study.currentQuestionnaireVersionId,methodologyVersionId:study.currentMethodologyVersionId,sourceIds,sourceCutoff:previous?.source_cutoff??now(),resolutionPolicy:'reviewed_resolutions',variablePolicies:Object.fromEntries(input.variableIds.map((variableId)=>[variableId,input.policies?.[variableId]??{multivalue:'preferred_resolution',missing:'include_reason'}]))};
  const evidence=getProsopObservationsWorkspace();const statements=evidence.factoids.flatMap((item)=>item.statements);const entities=evidence.factoids.flatMap((item)=>item.statements.flatMap((statement)=>statement.entities));const factoidSourceIds=Object.fromEntries(evidence.factoids.map((item)=>[item.factoidId,item.sourceId]));
  const projection=buildProsopProjection({definition:projectionDefinition,statements,entities,resolutions:evidence.resolutions,missingValues:evidence.missingValues,factoidSourceIds});
  let result:JsonValue;
  if(input.analysisKind==='frequency')result=asJson({kind:'frequency',frequency:prosopFrequencies(projection,input.variableIds[0]),matrix:projectionMatrix(projection)});
  else if(input.analysisKind==='crosstab'){if(input.variableIds.length<2)throw new Error('La tabla cruzada necesita dos variables.');result=asJson({kind:'crosstab',crosstab:prosopCrosstab(projection,input.variableIds[0],input.variableIds[1]),matrix:projectionMatrix(projection)});}
  else result=asJson({kind:input.analysisKind,points:projection.rows.flatMap((row)=>input.variableIds.flatMap((variableId)=>{const cell=row.cells[variableId];return cell.values.map((value,index)=>({personId:row.personId,variableId,value,statementId:cell.statementIds[index]??cell.statementIds[0]??null,sourceIds:cell.sourceIds}));})),matrix:projectionMatrix(projection)});
  const missingSummary:Record<string,number>={};projection.rows.forEach((row)=>Object.values(row.cells).forEach((cell)=>{if(cell.missingReason)missingSummary[cell.missingReason]=(missingSummary[cell.missingReason]??0)+1;}));
  const ts=now();const runId=id('par');
  const tx=db.transaction(()=>{db.prepare(`INSERT INTO prosop_analysis_definitions (analysis_id,study_id,title,analysis_kind,cohort_ids_json,projection_json,filter_json,questionnaire_version_id,source_cutoff,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(analysis_id) DO UPDATE SET title=excluded.title,analysis_kind=excluded.analysis_kind,cohort_ids_json=excluded.cohort_ids_json,projection_json=excluded.projection_json,filter_json=excluded.filter_json,questionnaire_version_id=excluded.questionnaire_version_id,source_cutoff=excluded.source_cutoff,updated_at=excluded.updated_at`).run(analysisId,study.studyId,input.title,input.analysisKind,JSON.stringify(input.cohortIds??[]),JSON.stringify(projectionDefinition),'{}',study.currentQuestionnaireVersionId,projectionDefinition.sourceCutoff,input.createdBy??'human',previous?.created_at??ts,ts);db.prepare(`INSERT INTO prosop_analysis_runs (run_id,analysis_id,engine_version,input_fingerprint,population_count,included_count,missing_summary_json,result_json,warnings_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)`).run(runId,analysisId,'prosop-projection-1',projection.fingerprint,projection.populationCount,projection.includedCount,JSON.stringify(missingSummary),JSON.stringify(result),JSON.stringify(projection.warnings),ts);});tx();
  return getProsopAnalysisWorkspace().definitions.find((item)=>item.analysisId===analysisId)!.runs.find((item)=>item.runId===runId)!;
}
