import { getDb } from './database';
import { getSettings } from './settingsRepo';
import { normalizePromptLanguage } from '@shared/promptLanguageOptions';
import { prosopDemoText } from './prosopDemoI18n';
import { updateProsopStudy, createProsopMethodologyDraft, replaceProsopCriteria, publishProsopMethodology } from './prosopStudyRepo';
import { createProsopQuestionnaireDraft, publishProsopQuestionnaire, saveProsopVariableRevision, saveProsopVocabulary, saveProsopVocabularyTerm } from './prosopQuestionnaireRepo';
import { saveProsopSource, saveProsopSourceSegment } from './prosopSourcesRepo';
import { createProsopPerson, saveProsopNameAttestation } from './prosopIdentityRepo';
import { saveProsopFactoid } from './prosopFactoidsRepo';
import { saveProsopCohort, saveProsopMembership } from './prosopMembershipRepo';
import { saveProsopNetworkEdge, saveProsopNetworkLayer } from './prosopNetworksRepo';

export function seedProsopDemo():{seeded:boolean;message:string}{
  const db=getDb();if(db.prepare("SELECT 1 FROM prosop_sources WHERE reference_code='DEMO-PROSOP-1'").get())return{seeded:false,message:prosopDemoText('La demo prosopográfica ya existe.')};
  if((db.prepare('SELECT COUNT(*) AS c FROM prosop_studies').get() as {c:number}).c>0&&(db.prepare('SELECT COUNT(*) AS c FROM prosop_factoids').get() as {c:number}).c>0)throw new Error(prosopDemoText('La demo solo puede añadirse a un vault sin observaciones.'));
  updateProsopStudy({title:prosopDemoText('Mujeres de letras en Madrid, 1620–1680'),researchQuestion:prosopDemoText('¿Cómo circularon las escritoras por academias y redes epistolares?'),populationDefinition:prosopDemoText('Mujeres con actividad literaria documentada en Madrid entre 1620 y 1680.'),temporalScope:prosopDemoText('1620–1680'),geographicScope:prosopDemoText('Madrid'),samplingStrategy:prosopDemoText('Exhaustiva dentro del corpus seleccionado.'),sourceStrategy:prosopDemoText('Actas académicas y correspondencia.'),knownBiases:prosopDemoText('Conservación desigual de cartas y actas.')});
  const method=createProsopMethodologyDraft('demo');const criteria=replaceProsopCriteria(method.versionId,[{kind:'include',label:prosopDemoText('Actividad literaria documentada'),required:true,weight:1},{kind:'exclude',label:prosopDemoText('Sin evidencia dentro del periodo'),required:false,weight:1}]);publishProsopMethodology(method.versionId,prosopDemoText('Metodología de demostración'),'demo');
  const vocabulary=saveProsopVocabulary({name:prosopDemoText('Ocupaciones históricas'),version:'1'});const poet=saveProsopVocabularyTerm({vocabularyId:vocabulary.vocabularyId,code:'poeta',preferredLabel:prosopDemoText('Poeta'),definition:prosopDemoText('Término normalizado de demostración.')});
  const questionnaire=createProsopQuestionnaireDraft({title:prosopDemoText('Cuestionario común'),createdBy:'demo'});const occupation=saveProsopVariableRevision(questionnaire.questionnaireVersionId,{key:'occupation',label:prosopDemoText('Ocupación'),question:prosopDemoText('¿Qué ocupación atribuye la fuente?'),valueType:'term',cardinality:'many',vocabularyId:vocabulary.vocabularyId});publishProsopQuestionnaire(questionnaire.questionnaireVersionId,prosopDemoText('Cuestionario de demostración'),'demo');
  const source=saveProsopSource({title:prosopDemoText('Actas de la Academia de Madrid'),sourceKind:'acta',citation:prosopDemoText('Demo Nodus, Actas, libro I'),repository:prosopDemoText('Corpus de demostración'),referenceCode:'DEMO-PROSOP-1',date:{display:'1642',startSort:1642,endSort:1642},coverageNotes:prosopDemoText('Dos sesiones de ejemplo.'),reliabilityNotes:prosopDemoText('Transcripción ficticia para aprender el flujo.'),accessStatus:'open'});const segment=saveProsopSourceSegment({sourceId:source.sourceId,locatorDisplay:prosopDemoText('fol. 12r'),locator:{folio:'12r'},quotedText:prosopDemoText('Doña Ana de Carvajal leyó versos y escribió a María de Zayas.'),transcriptionStatus:'literal',language:normalizePromptLanguage(getSettings().uiLanguage)});
  const ana=createProsopPerson({displayName:prosopDemoText('Ana de Carvajal'),preferredNameBasis:prosopDemoText('Actas, fol. 12r')});const maria=createProsopPerson({displayName:prosopDemoText('María de Zayas'),preferredNameBasis:prosopDemoText('Actas, fol. 12r')});saveProsopNameAttestation({sourceId:source.sourceId,sourceSegmentId:segment.segmentId,literalName:'Doña Ana de Carvajal',personId:ana.personId,context:prosopDemoText('Leyó versos.')});saveProsopNameAttestation({sourceId:source.sourceId,sourceSegmentId:segment.segmentId,literalName:'María de Zayas',personId:maria.personId,context:prosopDemoText('Destinataria de una carta.')});
  const factoid=saveProsopFactoid({sourceId:source.sourceId,sourceSegmentId:segment.segmentId,factoidKind:'activity',summary:prosopDemoText('Lectura y correspondencia'),status:'reviewed',createdBy:'demo',reviewedBy:'demo',statements:[{statementType:'occupation',variableId:occupation.variableId,variableRevisionId:occupation.revisionId,literalValue:prosopDemoText('leyó versos'),value:{kind:'term',termId:poet.termId,literal:prosopDemoText('leyó versos')},entities:[{entityKind:'person',entityId:ana.personId,role:'subject',position:0}]},{statementType:'correspondence',literalValue:prosopDemoText('escribió a'),value:{kind:'person',personId:maria.personId,literal:prosopDemoText('María de Zayas')},entities:[{entityKind:'person',entityId:ana.personId,role:'subject',position:0},{entityKind:'person',entityId:maria.personId,role:'object',position:1}]}]});
  for(const person of [ana,maria])saveProsopMembership({personId:person.personId,methodologyVersionId:method.versionId,status:'included',decision:'included',rationale:prosopDemoText('Cumple el criterio en la fuente de demostración.'),decidedBy:'demo',assessments:[{criterionId:criteria[0].criterionId,result:'met',factoidId:factoid.factoidId}]});
  saveProsopCohort({name:prosopDemoText('Población incluida'),kind:'frozen',filter:{conjunction:'and',rules:[{field:'membershipStatus',operator:'eq',value:'included'}]},methodologyVersionId:method.versionId,questionnaireVersionId:questionnaire.questionnaireVersionId});
  const layer=saveProsopNetworkLayer({name:prosopDemoText('Correspondencia explícita'),kind:'correspondence',directionality:'directed',color:'#2563eb'});saveProsopNetworkEdge({layerId:layer.layerId,sourcePersonId:ana.personId,targetPersonId:maria.personId,origin:'explicit',factoidIds:[factoid.factoidId],weight:1,date:{display:'1642',startSort:1642,endSort:1642}});
  return{seeded:true,message:prosopDemoText('Demo prosopográfica creada.')};
}
