/** Complete Italian catalogue; generated once and committed for offline use. */
export const DOC_TYPE_LABEL_IT: Record<string, string> = {
  "acta_de_asociacion_sociedad": "Verbali dell'associazione/società",
  "acta_de_pleno_municipal_cabildo": "Verbali del consiglio comunale/cabildo",
  "acta_notarial": "Atto notarile",
  "acueducto": "Acquedotto",
  "anuncio_de_prensa": "Pubblicità sui giornali",
  "arbol_genealogico_anterior": "Albero genealogico precedente",
  "arco_triunfal": "Arco trionfale",
  "arrendamiento_contrato_de_colonia": "Contratto di locazione/locazione",
  "atalaya_torre_vigia": "Torre di guardia",
  "auto_de_fe_expediente_inquisitorial": "Fascicolo Autodafé/Inquisizione",
  "ayuntamiento_historico": "Municipio storico",
  "bando_ordenanza_municipal": "Proclama/ordinanza comunale",
  "database": "Banca dati",
  "bien_de_interes_cultural_bic": "Bene patrimoniale classificato (BIC)",
  "billete_de_embarque": "Biglietto d'imbarco/imbarco",
  "billete_de_transporte": "Biglietto di trasporto",
  "bodega_lagar_tradicional": "Cantina / torchio tradizionale",
  "bula_indulgencia": "Bolla papale/indulgenza",
  "bunker_fortificacion": "Bunker/fortificazione",
  "caja_de_cerillas_fosforera": "Scatola di fiammiferi",
  "calendario_publicitario": "Calendario pubblicitario",
  "calzada_romana": "strada romana",
  "campana_con_inscripcion_fundacional": "Campana (con iscrizione fondativa)",
  "carta_de_aprendizaje_examen_de_maestria_": "Documento di apprendistato/maestro di gilda",
  "carta_de_fundacion": "Carta della fondazione",
  "carta_de_naturaleza_nacionalizacion": "Documento di naturalizzazione/cittadinanza",
  "carta_de_pago_recibo_de_deuda": "Ricevuta di pagamento/estinzione del debito",
  "carcel_historica": "Prigione storica",
  "cartel_poster": "Manifesto",
  "cartilla_de_la_seguridad_social_mutualid": "Libretto previdenziale/fondi comuni",
  "cartilla_militar_libreta_de_servicio": "Libretto di servizio militare",
  "castillo_fortaleza": "Castello/fortezza",
  "castro": "Hillfort (Castro)",
  "catedral": "Cattedrale",
  "causa_penal_sumario": "Procedimento penale/accusa",
  "cedula_de_identidad": "Carta d'identità",
  "cementerio_historico": "Cimitero storico",
  "cenotafio": "Cenotafio",
  "census": "Censimento/registro degli abitanti",
  "censo_enfiteutico_foro": "Enfiteusi/rendita fondiaria",
  "certificado_de_vacunacion": "Certificato di vaccinazione",
  "chapa_pin_conmemorativo": "Spilla/distintivo commemorativo",
  "chimenea_industrial": "Camino industriale",
  "colegiata": "Chiesa collegiata",
  "concordia_acuerdo_entre_partes": "Concordia (accordo tra le parti)",
  "conjunto_historico_artistico": "Complesso storico-artistico",
  "contrato_de_matrimonio_civil": "Contratto di matrimonio civile",
  "contrato_de_trabajo": "Contratto di lavoro",
  "letter": "Corrispondenza",
  "cromo_album_de_cromos": "Album di figurine/carte collezionabili",
  "cruceiro_cruz_de_piedra": "Croce lungo la strada in pietra (cruceiro)",
  "cruz_de_termino_o_de_cementerio": "Croce di confine/cimitero",
  "decreto_ley_historica": "Decreto/legge storica",
  "denuncia_atestado_policial": "Rapporto/denuncia della polizia",
  "diary": "Diario",
  "diploma_o_certificado_decorativo": "Diploma/certificato decorativo",
  "ejecutoria_de_hidalguia_u_otra": "Ejecutoria (brevetto di nobiltà/giudizio)",
  "entrada_billete_de_espectaculo": "Biglietto per evento/spettacolo",
  "envoltorio_etiqueta_de_producto": "Involucro/etichetta del prodotto",
  "ermita_capilla": "Eremo/cappella",
  "escritura_de_compraventa": "Atto di vendita",
  "escudo_de_armas_expediente_heraldico": "Stemma/scheda araldica",
  "escudo_de_casa_piedra_armera": "Stemma della casa (pietra araldica)",
  "escudo_heraldico_en_fachada": "Scudo araldico sulla facciata",
  "esquela_necrologica": "Avviso di morte / necrologio",
  "estacion_de_ferrocarril_historica": "Stazione ferroviaria storica",
  "estatua_busto_conmemorativo": "Statua/busto commemorativo",
  "etiqueta_de_correspondencia_comercial": "Carta intestata/etichetta commerciale",
  "etiqueta_de_equipaje_hotel": "Etichetta bagaglio/hotel",
  "ex_libris": "Ex libris (ex libris)",
  "expediente_academico_matricula_escolar": "Titolo accademico/iscrizione scolastica",
  "expediente_de_depuracion_represion_polit": "Fascicolo di epurazione/repressione politico-politica",
  "expediente_de_dispensa_matrimonial": "Dossier di dispensa dal matrimonio",
  "expediente_de_hidalguia_nobleza": "File nobiltà / hidalguía",
  "expediente_de_limpieza_de_sangre": "File sulla purezza del sangue (limpieza de sangre).",
  "expediente_de_ordenacion_sacerdotal": "Fascicolo di ordinazione sacerdotale",
  "expediente_de_quintas_sorteo": "Coscrizione/progetto di fascicolo",
  "expediente_penitenciario": "Fascicolo carcere/penitenziario",
  "fabrica_historica": "Fabbrica storica",
  "faro": "Faro",
  "folleto_publicitario": "Opuscolo pubblicitario",
  "photograph": "Fotografia",
  "fuente_monumental": "Fontana monumentale",
  "fuero_carta_de_poblacion": "Carta dei privilegi/Carta insediativa",
  "grabado_litografia": "Incisione/litografia",
  "hoja_de_servicios": "Registro di servizio",
  "horno_de_pan_de_cal": "Forno per pane/lime",
  "hospital_historico": "Ospedale storico",
  "horreo": "Granaio rialzato (hórreo)",
  "iglesia": "Chiesa",
  "illustration": "Illustrazione",
  "transcription": "Indice/trascrizione",
  "inventario_post_mortem": "Inventario post mortem",
  "invitacion": "Invito",
  "jardin_historico": "Giardino storico",
  "juguete_de_papel_recortable": "Giocattolo/ritaglio di carta",
  "libro_de_cofradia_hermandad": "Libro Confraternita/confraternita",
  "libro_de_confirmaciones": "Registro delle conferme",
  "libro_de_cuentas_familiar": "Libro dei conti di famiglia",
  "libro_de_defunciones_por_epidemia": "Registro dei decessi per epidemia",
  "libro_de_escolaridad_calificaciones": "Registro scuola/voti",
  "libro_de_fabrica_parroquial": "Libro contabile in tessuto parrocchiale",
  "libro_de_familia": "Libretto di famiglia",
  "lonja_mercado_historico": "Borsa storica/mercato coperto",
  "map": "Mappa/piano",
  "matricula_del_mar": "Registro dei marittimi (matrícula del mar)",
  "mayorazgo_vinculo": "Proprietà implicata (mayorazgo)",
  "medalla_conmemorativa": "Medaglia commemorativa",
  "memoirs": "Memorie",
  "menu_de_restaurante_o_banquete": "Menù ristorante/banchetto",
  "miliario": "Pietra miliare (miliardaria)",
  "mojon_hito_de_termino": "Segnale di confine",
  "molino": "Mulino",
  "monasterio_convento": "Monastero/convento",
  "moneda_historica": "Moneta storica",
  "monumento_a_los_caidos": "Monumento ai caduti/guerra",
  "muralla": "Mura della città",
  "naipe_baraja_publicitaria": "Carte da gioco/mazzi pubblicitari",
  "necropolis": "Necropoli",
  "necropolis_judia": "Necropoli ebraica",
  "nicho_columbario": "Nicchia/colombario",
  "noria_pozo": "Ruota idraulica/pozzo",
  "notes": "Note",
  "nomina_libro_de_jornales": "Buste paga/libro salariale",
  "obelisco": "Obelisco",
  "artwork": "Opera d'arte",
  "other_doc": "Altro documento",
  "padron_de_riqueza_catastro": "Registro patrimoniale/catasto",
  "palacio_casona_indiana": "Palazzo/maniero indiano",
  "palomar": "Colombaia",
  "panteon_mausoleo_familiar": "Pantheon/mausoleo di famiglia",
  "panteon_de_hombres_ilustres": "Pantheon di personaggi illustri",
  "papel_moneda_local_vale_de_emergencia": "Banconota locale/documento di emergenza",
  "parte_de_guerra_correspondencia_militar": "Dispaccio di guerra/corrispondenza militare",
  "particion_de_herencia": "Divisione di un patrimonio",
  "baptism_record": "Registro del battesimo",
  "death_record": "Registro della morte",
  "marriage_record": "Documento di matrimonio",
  "birth_record": "Documento di nascita",
  "partitura_o_cancionero_popular": "Spartiti/libro di canzoni popolari",
  "pasaporte_salvoconducto": "Passaporto/salvacondotto",
  "patente_o_privilegio_industrial": "Brevetto/privilegio industriale",
  "patrimonio_de_la_humanidad_unesco": "Sito Patrimonio dell'Umanità (UNESCO)",
  "petroglifo": "Petroglifo",
  "pila_bautismal_historica": "Fonte battesimale storico",
  "placa_conmemorativa": "Targa commemorativa",
  "plaza_mayor_historica": "Storica piazza principale",
  "pleito_civil": "Causa civile",
  "poder_notarial": "Procura",
  "postal": "Cartolina",
  "poste_indicador_antiguo": "Vecchio cartello",
  "presa_azud_historico": "Diga/stramazzo storico",
  "privilegio_real_merced": "Privilegio/concessione reale",
  "profesion_religiosa_toma_de_habito": "Professione religiosa/assunzione dei voti",
  "programa_de_mano": "Programma (locandina)",
  "protocolo_notarial": "Protocollo notarile",
  "posito": "Deposito comunale di grano (pósito)",
  "puente_historico": "Ponte storico",
  "puerto_historico": "Porto storico",
  "publicidad_recortada_de_prensa": "Annuncio stampa ritagliato",
  "real_cedula": "Decreto reale (real cédula)",
  "recorte_de_hemeroteca_noticia_de_periodi": "Rassegna stampa/notizia",
  "recordatorio_religioso": "Biglietto ricordo religioso",
  "migration": "Registro della migrazione",
  "military": "Documento militare",
  "reloj_de_sol": "Meridiana",
  "retablo": "Pala d'altare (retablo)",
  "ruta_o_camino_historico": "Itinerario/strada storica",
  "santuario": "Santuario/santuario",
  "sello_vineta_fiscal_benefica_conmemorati": "Timbro/sigillo (fiscale, benefico, commemorativo)",
  "sello_postal_filatelia": "Francobollo (filatelia)",
  "sentencia_judicial": "Sentenza della Corte",
  "sepulcro_arca_funeraria": "Tomba/cassa funeraria",
  "sinagoga_mezquita_historica": "Sinagoga/moschea storica",
  "sitio_historico": "Sito storico",
  "tarjeta_de_visita_felicitacion": "Biglietto da visita/auguri",
  "tebeo_comic": "Comico",
  "teatro_historico": "Teatro storico",
  "testamento_codicilo": "Testamento/codicillo",
  "titulo_o_diploma": "Laurea/diploma",
  "torre_defensiva_torreon": "Torre difensiva",
  "administrative": "Procedimento amministrativo",
  "universidad_historica": "Università storica",
  "vale_cupon_bono_de_racionamiento": "Buono/buono razionamento",
  "via_crucis_hornacina": "Via Crucis/edicola a nicchia",
  "villa_romana": "Villa romana",
  "visita_pastoral": "Visita pastorale",
  "yacimiento_arqueologico": "Sito archeologico",
  "lapida_losa_sepulcral": "Lapide / lastra tombale",
  "epitafio": "Epitaffio",
  "dolmen_menhir_tumulo_megalitico": "Dolmen/menhir/tumulo megalitico",
};

/** Complete Italian catalogue; generated once and committed for offline use. */
export const DOC_FACET_LABEL_IT: Record<string, string> = {
  "Documentary heritage": "Patrimonio documentario",
  "Built / monumental heritage": "Patrimonio edilizio/monumentale",
  "Ephemera": "Effimera",
  "Archaeological heritage": "Patrimonio archeologico",
  "Intangible heritage": "Patrimonio immateriale",
  "Prehistory / Antiquity": "Preistoria/Antichità",
  "Medieval": "Medievale",
  "Early modern": "Prima età moderna",
  "Contemporary": "Contemporaneo",
  "Present day": "Oggi",
  "Cross-period": "Periodo incrociato",
  "Civil": "Civile",
  "Commercial": "Commerciale",
  "Domestic": "Domestico",
  "Educational": "Educativo",
  "Funerary": "Funerario",
  "Heraldic": "Araldico",
  "Judicial": "giudiziario",
  "Labour": "Lavoro",
  "Military": "Militare",
  "Notarial": "Notarile",
  "Leisure & popular culture": "Tempo libero e cultura popolare",
  "Press": "Premere",
  "Religious": "Religioso",
  "Health": "Salute",
  "Vital record": "Documento anagrafico",
  "File / procedure": "Fascicolo/procedura",
  "Correspondence": "Corrispondenza",
  "Personal / narrative writing": "Scrittura personale/narrativa",
  "Database / transcription": "Database/trascrizione",
  "Civil architecture": "Architettura civile",
  "Funerary architecture": "Architettura funeraria",
  "Military / defensive architecture": "Architettura militare/difensiva",
  "Religious architecture": "Architettura religiosa",
  "Rural / vernacular architecture": "Architettura rurale/vernacolare",
  "Natural feature": "Caratteristica naturale",
  "Minor urban feature": "Caratteristica urbana minore",
  "Infrastructure": "Infrastrutture",
  "Listed / protected": "Elencato / protetto",
  "No formal protection": "Nessuna tutela formale",
  "Photographic": "Fotografico",
  "Printed": "Stampato",
  "Manuscript": "Manoscritto",
  "Object": "Oggetto",
  "Useful for genealogy": "Utile per la genealogia",
};
