/** Complete Japanese catalogue; mirrors archiveDocTypes.zh-TW.ts. */
export const DOC_TYPE_LABEL_JA: Record<string, string> = {
  "acta_de_asociacion_sociedad": "協会・学会議事録",
  "acta_de_pleno_municipal_cabildo": "町議会/議会議事録",
  "acta_notarial": "公正証書",
  "acueducto": "水道橋",
  "anuncio_de_prensa": "新聞広告",
  "arbol_genealogico_anterior": "以前の家系図",
  "arco_triunfal": "凱旋門",
  "arrendamiento_contrato_de_colonia": "賃貸借契約",
  "atalaya_torre_vigia": "ものみの塔",
  "auto_de_fe_expediente_inquisitorial": "オートダフェ / 異端審問ファイル",
  "ayuntamiento_historico": "歴史ある市庁舎",
  "bando_ordenanza_municipal": "布告・条例",
  "database": "データベース",
  "bien_de_interes_cultural_bic": "登録遺産（BIC）",
  "billete_de_embarque": "乗船・乗船券",
  "billete_de_transporte": "交通チケット",
  "bodega_lagar_tradicional": "伝統的なワイナリー / プレスハウス",
  "bula_indulgencia": "教皇勅書 / 免罪符",
  "bunker_fortificacion": "バンカー/要塞",
  "caja_de_cerillas_fosforera": "マッチ箱",
  "calendario_publicitario": "広告カレンダー",
  "calzada_romana": "ローマの道",
  "campana_con_inscripcion_fundacional": "鐘（礎石銘あり）",
  "carta_de_aprendizaje_examen_de_maestria_": "見習い/ギルドマスターシップの記録",
  "carta_de_fundacion": "財団憲章",
  "carta_de_naturaleza_nacionalizacion": "帰化/市民権記録",
  "carta_de_pago_recibo_de_deuda": "支払いの領収書/債務免除",
  "carcel_historica": "歴史ある刑務所",
  "cartel_poster": "ポスター",
  "cartilla_de_la_seguridad_social_mutualid": "社会保障・投資信託小冊子",
  "cartilla_militar_libreta_de_servicio": "兵役に関する冊子",
  "castillo_fortaleza": "城・要塞",
  "castro": "ヒルフォート (カストロ)",
  "catedral": "大聖堂",
  "causa_penal_sumario": "刑事事件・起訴",
  "cedula_de_identidad": "身分証明書",
  "cementerio_historico": "歴史ある墓地",
  "cenotafio": "慰霊碑",
  "census": "国勢調査・住民登録",
  "censo_enfiteutico_foro": "肺気腫/地代",
  "certificado_de_vacunacion": "予防接種証明書",
  "chapa_pin_conmemorativo": "記念ピン・バッジ",
  "chimenea_industrial": "工業用煙突",
  "colegiata": "大学教会",
  "concordia_acuerdo_entre_partes": "コンコルディア（当事者間の和解）",
  "conjunto_historico_artistico": "歴史と芸術のアンサンブル",
  "contrato_de_matrimonio_civil": "民事婚契約",
  "contrato_de_trabajo": "雇用契約書",
  "letter": "対応",
  "cromo_album_de_cromos": "トレーディングカード/ステッカーアルバム",
  "cruceiro_cruz_de_piedra": "石の道端の十字架 (クルセイロ)",
  "cruz_de_termino_o_de_cementerio": "境界線・墓地の十字架",
  "decreto_ley_historica": "法令/歴史的法律",
  "denuncia_atestado_policial": "警察への通報・告訴状",
  "diary": "日記",
  "diploma_o_certificado_decorativo": "装飾的な卒業証書/証明書",
  "ejecutoria_de_hidalguia_u_otra": "エジェクトリア（貴族の特許・判断力）",
  "entrada_billete_de_espectaculo": "イベント/ショーチケット",
  "envoltorio_etiqueta_de_producto": "製品の包装紙/ラベル",
  "ermita_capilla": "エルミタージュ・礼拝堂",
  "escritura_de_compraventa": "売買証書",
  "escudo_de_armas_expediente_heraldico": "紋章/紋章ファイル",
  "escudo_de_casa_piedra_armera": "家の紋章（紋章石）",
  "escudo_heraldico_en_fachada": "ファサードの紋章入りの盾",
  "esquela_necrologica": "死亡通知/訃報",
  "estacion_de_ferrocarril_historica": "歴史ある鉄道駅",
  "estatua_busto_conmemorativo": "記念像・胸像",
  "etiqueta_de_correspondencia_comercial": "コマーシャルレターヘッド/ラベル",
  "etiqueta_de_equipaje_hotel": "荷物/ホテルのラベル",
  "ex_libris": "蔵書（蔵書票）",
  "expediente_academico_matricula_escolar": "学歴・就学状況",
  "expediente_de_depuracion_represion_polit": "粛清/政治弾圧ファイル",
  "expediente_de_dispensa_matrimonial": "婚姻調停ファイル",
  "expediente_de_hidalguia_nobleza": "貴族 / ヒダルギアファイル",
  "expediente_de_limpieza_de_sangre": "血液の純度 (リンピエザデサングレ) ファイル",
  "expediente_de_ordenacion_sacerdotal": "司祭叙階ファイル",
  "expediente_de_quintas_sorteo": "徴兵・徴兵ファイル",
  "expediente_penitenciario": "刑務所/刑務所ファイル",
  "fabrica_historica": "歴史ある工場",
  "faro": "灯台",
  "folleto_publicitario": "広告チラシ",
  "photograph": "写真",
  "fuente_monumental": "記念碑的な噴水",
  "fuero_carta_de_poblacion": "特権憲章/和解憲章",
  "grabado_litografia": "彫刻・リトグラフ",
  "hoja_de_servicios": "サービス実績",
  "horno_de_pan_de_cal": "パン/ライムオーブン",
  "hospital_historico": "歴史ある病院",
  "horreo": "高くなった穀倉 (ホロレオ)",
  "iglesia": "教会",
  "illustration": "図",
  "transcription": "索引/転写",
  "inventario_post_mortem": "死後の目録",
  "invitacion": "招待",
  "jardin_historico": "歴史ある庭園",
  "juguete_de_papel_recortable": "紙のおもちゃ / 切り抜き",
  "libro_de_cofradia_hermandad": "協会/兄弟愛の本",
  "libro_de_confirmaciones": "確認の登録",
  "libro_de_cuentas_familiar": "家計簿",
  "libro_de_defunciones_por_epidemia": "流行性死亡記録",
  "libro_de_escolaridad_calificaciones": "学校・成績記録",
  "libro_de_fabrica_parroquial": "教区の布地帳簿",
  "libro_de_familia": "家族記録簿",
  "lonja_mercado_historico": "歴史ある取引所・市場ホール",
  "map": "地図・プラン",
  "matricula_del_mar": "船員登録簿 (matrícula del mar)",
  "mayorazgo_vinculo": "関与する不動産 (マヨラズゴ)",
  "medalla_conmemorativa": "記念メダル",
  "memoirs": "紀要",
  "menu_de_restaurante_o_banquete": "レストラン・宴会メニュー",
  "miliario": "マイルストーン (ミリリオ)",
  "mojon_hito_de_termino": "境界マーカー",
  "molino": "ミル",
  "monasterio_convento": "修道院・修道院",
  "moneda_historica": "歴史的なコイン",
  "monumento_a_los_caidos": "戦争・戦没記念碑",
  "muralla": "城壁",
  "naipe_baraja_publicitaria": "トランプ/広告デッキ",
  "necropolis": "ネクロポリス",
  "necropolis_judia": "ユダヤ人の墓地遺跡",
  "nicho_columbario": "ニッチ/納骨堂",
  "noria_pozo": "水車・井戸",
  "notes": "注意事項",
  "nomina_libro_de_jornales": "給与・賃金台帳",
  "obelisco": "オベリスク",
  "artwork": "アートワーク",
  "other_doc": "その他の書類",
  "padron_de_riqueza_catastro": "資産台帳/台帳",
  "palacio_casona_indiana": "宮殿/インディアンマナーハウス",
  "palomar": "鳩小屋",
  "panteon_mausoleo_familiar": "家族のパンテオン / 霊廟",
  "panteon_de_hombres_ilustres": "著名な人物のパンテオン",
  "papel_moneda_local_vale_de_emergencia": "現地紙幣・緊急切符",
  "parte_de_guerra_correspondencia_militar": "戦争派遣・軍事対応",
  "particion_de_herencia": "不動産の分割",
  "baptism_record": "洗礼の記録",
  "death_record": "死亡記録",
  "marriage_record": "結婚歴",
  "birth_record": "出生記録",
  "partitura_o_cancionero_popular": "楽譜/ポピュラーソングブック",
  "pasaporte_salvoconducto": "パスポート / 安全行動",
  "patente_o_privilegio_industrial": "特許・産業上の特権",
  "patrimonio_de_la_humanidad_unesco": "世界遺産（ユネスコ）",
  "petroglifo": "ペトログリフ",
  "pila_bautismal_historica": "歴史的な洗礼フォント",
  "placa_conmemorativa": "記念楯",
  "plaza_mayor_historica": "歴史あるメイン広場",
  "pleito_civil": "民事訴訟",
  "poder_notarial": "委任状",
  "postal": "ポストカード",
  "poste_indicador_antiguo": "古い道標",
  "presa_azud_historico": "歴史あるダム・堰",
  "privilegio_real_merced": "王室特権・付与",
  "profesion_religiosa_toma_de_habito": "宗教上の職業/誓いを立てること",
  "programa_de_mano": "プログラム（チラシ）",
  "protocolo_notarial": "公証プロトコル",
  "posito": "共同穀物倉庫 (ポジト)",
  "puente_historico": "歴史ある橋",
  "puerto_historico": "歴史ある港",
  "publicidad_recortada_de_prensa": "プレス広告の切り抜き",
  "real_cedula": "王政令 (real cédula)",
  "recorte_de_hemeroteca_noticia_de_periodi": "報道の切り抜き/ニュース記事",
  "recordatorio_religioso": "宗教的な思い出のカード",
  "migration": "移行記録",
  "military": "戦歴",
  "reloj_de_sol": "日時計",
  "retablo": "祭壇画 (レタブロ)",
  "ruta_o_camino_historico": "歴史ある街道・道路",
  "santuario": "聖域・神社",
  "sello_vineta_fiscal_benefica_conmemorati": "切手・印章（財政・慈善・記念）",
  "sello_postal_filatelia": "切手（郵趣）",
  "sentencia_judicial": "裁判所の判決",
  "sepulcro_arca_funeraria": "墓/葬儀箱",
  "sinagoga_mezquita_historica": "歴史的なシナゴーグ/モスク",
  "sitio_historico": "史跡",
  "tarjeta_de_visita_felicitacion": "訪問・挨拶状",
  "tebeo_comic": "漫画",
  "teatro_historico": "歴史ある劇場",
  "testamento_codicilo": "ウィル / コディシル",
  "titulo_o_diploma": "学位/卒業証書",
  "torre_defensiva_torreon": "防御塔",
  "administrative": "行政手続き",
  "universidad_historica": "歴史ある大学",
  "vale_cupon_bono_de_racionamiento": "配給券・クーポン",
  "via_crucis_hornacina": "十字架の道 / 龕神社",
  "villa_romana": "ローマのヴィラ",
  "visita_pastoral": "司牧訪問",
  "yacimiento_arqueologico": "遺跡",
  "lapida_losa_sepulcral": "墓石・墓石",
  "epitafio": "碑文",
  "dolmen_menhir_tumulo_megalitico": "ドルメン / メンヒル / 巨石塚",
};

export const DOC_FACET_LABEL_JA: Record<string, string> = {
  "Documentary heritage": "ドキュメンタリー遺産",
  "Built / monumental heritage": "建造物/記念碑的遺産",
  "Ephemera": "エフェメラ",
  "Archaeological heritage": "考古学遺産",
  "Intangible heritage": "無形遺産",
  "Prehistory / Antiquity": "先史時代/古代",
  "Medieval": "中世",
  "Early modern": "近世",
  "Contemporary": "コンテンポラリー",
  "Present day": "現在",
  "Cross-period": "クロスピリオド",
  "Civil": "民事",
  "Commercial": "コマーシャル",
  "Domestic": "国内",
  "Educational": "教育的",
  "Funerary": "葬儀",
  "Heraldic": "紋章",
  "Judicial": "司法",
  "Labour": "労働",
  "Military": "軍隊",
  "Notarial": "公証人",
  "Leisure & popular culture": "レジャーと大衆文化",
  "Press": "プレス",
  "Religious": "宗教的",
  "Health": "健康",
  "Vital record": "重要な記録",
  "File / procedure": "ファイル/手順",
  "Correspondence": "対応",
  "Personal / narrative writing": "個人/物語の執筆",
  "Database / transcription": "データベース/トランスクリプション",
  "Civil architecture": "土木建築",
  "Funerary architecture": "葬儀建築",
  "Military / defensive architecture": "軍事/防御建築",
  "Religious architecture": "宗教建築",
  "Rural / vernacular architecture": "田舎/地域の建築",
  "Natural feature": "自然の特徴",
  "Minor urban feature": "小さな都市の特徴",
  "Infrastructure": "インフラストラクチャー",
  "Listed / protected": "リストされている/保護されている",
  "No formal protection": "正式な保護はありません",
  "Photographic": "写真",
  "Printed": "印刷済み",
  "Manuscript": "原稿",
  "Object": "物体",
  "Useful for genealogy": "系図に役立つ",
};
