/** Complete Simplified Chinese catalogue; mirrors archiveDocTypes.it.ts / .tr.ts. */
export const DOC_TYPE_LABEL_ZH_CN: Record<string, string> = {
  "acta_de_asociacion_sociedad": "协会 / 社团会议纪要",
  "acta_de_pleno_municipal_cabildo": "市政会议 / 市议会纪要",
  "acta_notarial": "公证记录",
  "acueducto": "引水渠",
  "anuncio_de_prensa": "报纸广告",
  "arbol_genealogico_anterior": "早期家谱",
  "arco_triunfal": "凯旋门",
  "arrendamiento_contrato_de_colonia": "租赁 / 租佃合同",
  "atalaya_torre_vigia": "瞭望塔 / 警戒塔",
  "auto_de_fe_expediente_inquisitorial": "火刑宣判 / 宗教裁判档案",
  "ayuntamiento_historico": "历史市政厅",
  "bando_ordenanza_municipal": "公告 / 市政条例",
  "database": "数据库",
  "bien_de_interes_cultural_bic": "受保护文化遗产（BIC）",
  "billete_de_embarque": "登机 / 登船票",
  "billete_de_transporte": "交通票据",
  "bodega_lagar_tradicional": "传统酒窖 / 榨酒坊",
  "bula_indulgencia": "教宗诏书 / 赎罪券",
  "bunker_fortificacion": "地堡 / 防御工事",
  "caja_de_cerillas_fosforera": "火柴盒",
  "calendario_publicitario": "广告日历",
  "calzada_romana": "古罗马道路",
  "campana_con_inscripcion_fundacional": "铜钟（带始建铭文）",
  "carta_de_aprendizaje_examen_de_maestria_": "学徒契约 / 行会师傅资格记录",
  "carta_de_fundacion": "创建特许状",
  "carta_de_naturaleza_nacionalizacion": "入籍 / 归化文书",
  "carta_de_pago_recibo_de_deuda": "付款收据 / 债务清偿证明",
  "carcel_historica": "历史监狱",
  "cartel_poster": "海报",
  "cartilla_de_la_seguridad_social_mutualid": "社保 / 互助会手册",
  "cartilla_militar_libreta_de_servicio": "兵役证 / 服役手册",
  "castillo_fortaleza": "城堡 / 要塞",
  "castro": "山丘堡垒（castro）",
  "catedral": "主教座堂",
  "causa_penal_sumario": "刑事案件 / 预审卷宗",
  "cedula_de_identidad": "身份证",
  "cementerio_historico": "历史公墓",
  "cenotafio": "衣冠冢",
  "census": "人口普查 / 户籍册",
  "censo_enfiteutico_foro": "永佃权 / 地租",
  "certificado_de_vacunacion": "疫苗接种证明",
  "chapa_pin_conmemorativo": "纪念徽章 / 胸针",
  "chimenea_industrial": "工业烟囱",
  "colegiata": "协同教堂",
  "concordia_acuerdo_entre_partes": "和解协议（当事人之间）",
  "conjunto_historico_artistico": "历史艺术建筑群",
  "contrato_de_matrimonio_civil": "民事婚姻契约",
  "contrato_de_trabajo": "劳动合同",
  "letter": "通信",
  "cromo_album_de_cromos": "集换卡 / 贴纸册",
  "cruceiro_cruz_de_piedra": "石制路边十字架（cruceiro）",
  "cruz_de_termino_o_de_cementerio": "地界 / 墓地十字架",
  "decreto_ley_historica": "法令 / 历史法律",
  "denuncia_atestado_policial": "报案 / 警方笔录",
  "diary": "日记",
  "diploma_o_certificado_decorativo": "装饰性文凭 / 证书",
  "ejecutoria_de_hidalguia_u_otra": "贵族身份判决（ejecutoria）",
  "entrada_billete_de_espectaculo": "演出门票",
  "envoltorio_etiqueta_de_producto": "产品包装 / 标签",
  "ermita_capilla": "隐修堂 / 小教堂",
  "escritura_de_compraventa": "买卖契约",
  "escudo_de_armas_expediente_heraldico": "纹章 / 纹章档案",
  "escudo_de_casa_piedra_armera": "宅邸纹章（纹章石）",
  "escudo_heraldico_en_fachada": "立面纹章",
  "esquela_necrologica": "讣告",
  "estacion_de_ferrocarril_historica": "历史火车站",
  "estatua_busto_conmemorativo": "纪念雕像 / 半身像",
  "etiqueta_de_correspondencia_comercial": "商业信笺 / 标签",
  "etiqueta_de_equipaje_hotel": "行李 / 酒店标签",
  "ex_libris": "藏书票（ex-libris）",
  "expediente_academico_matricula_escolar": "学籍档案 / 入学注册",
  "expediente_de_depuracion_represion_polit": "清洗 / 政治迫害档案",
  "expediente_de_dispensa_matrimonial": "婚姻豁免档案",
  "expediente_de_hidalguia_nobleza": "贵族 / 伊达尔戈身份档案",
  "expediente_de_limpieza_de_sangre": "血统纯正档案（limpieza de sangre）",
  "expediente_de_ordenacion_sacerdotal": "神职授任档案",
  "expediente_de_quintas_sorteo": "征兵 / 抽签档案",
  "expediente_penitenciario": "监狱档案",
  "fabrica_historica": "历史工厂",
  "faro": "灯塔",
  "folleto_publicitario": "广告传单",
  "photograph": "照片",
  "fuente_monumental": "纪念性喷泉",
  "fuero_carta_de_poblacion": "特许状 / 定居特许状",
  "grabado_litografia": "版画 / 石版画",
  "hoja_de_servicios": "服役记录",
  "horno_de_pan_de_cal": "面包炉 / 石灰窑",
  "hospital_historico": "历史医院",
  "horreo": "高架粮仓（hórreo）",
  "iglesia": "教堂",
  "illustration": "插图",
  "transcription": "索引 / 转录",
  "inventario_post_mortem": "身后财产清单",
  "invitacion": "请柬",
  "jardin_historico": "历史园林",
  "juguete_de_papel_recortable": "纸玩具 / 剪纸",
  "libro_de_cofradia_hermandad": "兄弟会簿册",
  "libro_de_confirmaciones": "坚振登记簿",
  "libro_de_cuentas_familiar": "家庭账簿",
  "libro_de_defunciones_por_epidemia": "疫病死亡登记簿",
  "libro_de_escolaridad_calificaciones": "学籍 / 成绩记录",
  "libro_de_fabrica_parroquial": "堂区经费账簿",
  "libro_de_familia": "家庭登记簿",
  "lonja_mercado_historico": "历史交易所 / 市场",
  "map": "地图 / 平面图",
  "matricula_del_mar": "海员登记册（matrícula del mar）",
  "mayorazgo_vinculo": "长子继承产业（mayorazgo）",
  "medalla_conmemorativa": "纪念章",
  "memoirs": "回忆录",
  "menu_de_restaurante_o_banquete": "餐厅 / 宴会菜单",
  "miliario": "里程碑（miliario）",
  "mojon_hito_de_termino": "界碑",
  "molino": "磨坊",
  "monasterio_convento": "修道院 / 女修道院",
  "moneda_historica": "历史钱币",
  "monumento_a_los_caidos": "阵亡将士纪念碑",
  "muralla": "城墙",
  "naipe_baraja_publicitaria": "纸牌 / 广告牌组",
  "necropolis": "墓园",
  "necropolis_judia": "犹太墓园",
  "nicho_columbario": "壁龛 / 骨灰龛",
  "noria_pozo": "水车 / 水井",
  "notes": "笔记",
  "nomina_libro_de_jornales": "工资单 / 工钱账簿",
  "obelisco": "方尖碑",
  "artwork": "艺术品",
  "other_doc": "其他文档",
  "padron_de_riqueza_catastro": "财产登记册 / 地籍",
  "palacio_casona_indiana": "宫殿 / 印第亚诺宅第",
  "palomar": "鸽舍",
  "panteon_mausoleo_familiar": "家族先贤祠 / 陵墓",
  "panteon_de_hombres_ilustres": "名人先贤祠",
  "papel_moneda_local_vale_de_emergencia": "地方纸币 / 应急代币券",
  "parte_de_guerra_correspondencia_militar": "战报 / 军事通信",
  "particion_de_herencia": "遗产分割",
  "baptism_record": "洗礼记录",
  "death_record": "死亡记录",
  "marriage_record": "婚姻记录",
  "birth_record": "出生记录",
  "partitura_o_cancionero_popular": "乐谱 / 民歌集",
  "pasaporte_salvoconducto": "护照 / 通行证",
  "patente_o_privilegio_industrial": "专利 / 工业特权",
  "patrimonio_de_la_humanidad_unesco": "世界遗产（UNESCO）",
  "petroglifo": "岩刻",
  "pila_bautismal_historica": "历史洗礼池",
  "placa_conmemorativa": "纪念牌",
  "plaza_mayor_historica": "历史主广场",
  "pleito_civil": "民事诉讼",
  "poder_notarial": "授权委托书",
  "postal": "明信片",
  "poste_indicador_antiguo": "旧路标",
  "presa_azud_historico": "历史水坝 / 堰",
  "privilegio_real_merced": "王室特许 / 恩赐",
  "profesion_religiosa_toma_de_habito": "入会发愿 / 受戒",
  "programa_de_mano": "演出节目单",
  "protocolo_notarial": "公证文书簿",
  "posito": "公共粮仓（pósito）",
  "puente_historico": "历史桥梁",
  "puerto_historico": "历史港口",
  "publicidad_recortada_de_prensa": "剪报广告",
  "real_cedula": "王室敕令",
  "recorte_de_hemeroteca_noticia_de_periodi": "报刊剪报 / 新闻剪报",
  "recordatorio_religioso": "宗教纪念卡",
  "migration": "移民记录",
  "military": "军事记录",
  "reloj_de_sol": "日晷",
  "retablo": "祭坛屏画",
  "ruta_o_camino_historico": "历史路线 / 古道",
  "santuario": "圣所 / 神龛",
  "sello_vineta_fiscal_benefica_conmemorati": "印章 / 票签（税票、慈善、纪念）",
  "sello_postal_filatelia": "邮票（集邮）",
  "sentencia_judicial": "法院判决",
  "sepulcro_arca_funeraria": "墓穴 / 石棺",
  "sinagoga_mezquita_historica": "历史犹太会堂 / 清真寺",
  "sitio_historico": "历史遗址",
  "tarjeta_de_visita_felicitacion": "名片 / 贺卡",
  "tebeo_comic": "漫画",
  "teatro_historico": "历史剧院",
  "testamento_codicilo": "遗嘱 / 遗嘱附录",
  "titulo_o_diploma": "学位 / 文凭",
  "torre_defensiva_torreon": "防御塔 / 堡垒",
  "administrative": "行政手续",
  "universidad_historica": "历史大学",
  "vale_cupon_bono_de_racionamiento": "配给券 / 票证",
  "via_crucis_hornacina": "苦路 / 壁龛",
  "villa_romana": "古罗马别墅",
  "visita_pastoral": "牧灵访问",
  "yacimiento_arqueologico": "考古遗址",
  "lapida_losa_sepulcral": "墓碑 / 墓板",
  "epitafio": "墓志铭",
  "dolmen_menhir_tumulo_megalitico": "石棚 / 立石 / 巨石冢"
};

export const DOC_FACET_LABEL_ZH_CN: Record<string, string> = {
  "Documentary heritage": "文献遗产",
  "Built / monumental heritage": "建筑遗产",
  "Ephemera": "临时资料",
  "Archaeological heritage": "考古遗产",
  "Intangible heritage": "非物质遗产",
  "Prehistory / Antiquity": "史前 / 古代",
  "Medieval": "中世纪",
  "Early modern": "近代早期",
  "Contemporary": "当代",
  "Present day": "现今",
  "Cross-period": "跨时期",
  "Civil": "民用",
  "Commercial": "商业",
  "Domestic": "家庭",
  "Educational": "教育",
  "Funerary": "丧葬",
  "Heraldic": "纹章",
  "Judicial": "司法",
  "Labour": "劳动",
  "Military": "军事",
  "Notarial": "公证",
  "Leisure & popular culture": "休闲与大众文化",
  "Press": "报刊",
  "Religious": "宗教",
  "Health": "医疗卫生",
  "Vital record": "民事登记记录",
  "File / procedure": "案卷 / 手续",
  "Correspondence": "书信",
  "Personal / narrative writing": "个人 / 叙事写作",
  "Database / transcription": "数据库 / 转录",
  "Civil architecture": "民用建筑",
  "Funerary architecture": "丧葬建筑",
  "Military / defensive architecture": "军事 / 防御建筑",
  "Religious architecture": "宗教建筑",
  "Rural / vernacular architecture": "乡村 / 乡土建筑",
  "Natural feature": "自然要素",
  "Minor urban feature": "城市小型要素",
  "Infrastructure": "基础设施",
  "Listed / protected": "已列入保护 / 受保护",
  "No formal protection": "无正式保护",
  "Photographic": "摄影",
  "Printed": "印刷",
  "Manuscript": "手稿",
  "Object": "实物",
  "Useful for genealogy": "有助族谱研究"
};
