export const DOC_TYPE_LABEL_TR: Record<string, string> = {
  "acta_de_asociacion_sociedad": "Dernek / topluluk tutanağı",
  "acta_de_pleno_municipal_cabildo": "Belediye meclisi / cabildo tutanağı",
  "acta_notarial": "Noter belgesi",
  "acueducto": "Su kemeri",
  "anuncio_de_prensa": "Gazete ilanı",
  "arbol_genealogico_anterior": "Önceki soy ağacı",
  "arco_triunfal": "Zafer takı",
  "arrendamiento_contrato_de_colonia": "Kira sözleşmesi",
  "atalaya_torre_vigia": "Gözetleme kulesi",
  "auto_de_fe_expediente_inquisitorial": "Auto-da-fé / Engizisyon dosyası",
  "ayuntamiento_historico": "Tarihi belediye binası",
  "bando_ordenanza_municipal": "Belediye bildirisi / yönetmeliği",
  "database": "Veri tabanı",
  "bien_de_interes_cultural_bic": "Tescilli kültür varlığı (BIC)",
  "billete_de_embarque": "Biniş kartı",
  "billete_de_transporte": "Ulaşım bileti",
  "bodega_lagar_tradicional": "Geleneksel şaraphane / üzüm sıkma tesisi",
  "bula_indulgencia": "Papalık fermanı / endüljans",
  "bunker_fortificacion": "Sığınak / tahkimat",
  "caja_de_cerillas_fosforera": "Kibrit kutusu",
  "calendario_publicitario": "Reklam takvimi",
  "calzada_romana": "Roma yolu",
  "campana_con_inscripcion_fundacional": "Çan (kuruluş kitabesiyle)",
  "carta_de_aprendizaje_examen_de_maestria_": "Çıraklık / lonca ustalık sınavı kaydı",
  "carta_de_fundacion": "Kuruluş beratı",
  "carta_de_naturaleza_nacionalizacion": "Vatandaşlığa kabul kaydı",
  "carta_de_pago_recibo_de_deuda": "Ödeme makbuzu / borç ibrası",
  "carcel_historica": "Tarihi hapishane",
  "cartel_poster": "Afiş",
  "cartilla_de_la_seguridad_social_mutualid": "Sosyal güvenlik / yardımlaşma sandığı cüzdanı",
  "cartilla_militar_libreta_de_servicio": "Askerlik cüzdanı / hizmet defteri",
  "castillo_fortaleza": "Kale / hisar",
  "castro": "Tepe kalesi (castro)",
  "catedral": "Katedral",
  "causa_penal_sumario": "Ceza davası / soruşturma dosyası",
  "cedula_de_identidad": "Kimlik kartı",
  "cementerio_historico": "Tarihi mezarlık",
  "cenotafio": "Kenotaf",
  "census": "Nüfus sayımı / sakinler kaydı",
  "censo_enfiteutico_foro": "Emfiteoz / toprak kirası",
  "certificado_de_vacunacion": "Aşı sertifikası",
  "chapa_pin_conmemorativo": "Hatıra rozeti / iğnesi",
  "chimenea_industrial": "Endüstriyel baca",
  "colegiata": "Kolej kilisesi",
  "concordia_acuerdo_entre_partes": "Concordia (taraflar arasında uzlaşma)",
  "conjunto_historico_artistico": "Tarihî ve sanatsal yapı topluluğu",
  "contrato_de_matrimonio_civil": "Sivil evlilik sözleşmesi",
  "contrato_de_trabajo": "İş sözleşmesi",
  "letter": "Yazışma",
  "cromo_album_de_cromos": "Koleksiyon kartı / çıkartma albümü",
  "cruceiro_cruz_de_piedra": "Taş yol kenarı haçı (cruceiro)",
  "cruz_de_termino_o_de_cementerio": "Sınır / mezarlık haçı",
  "decreto_ley_historica": "Kararname / tarihi kanun",
  "denuncia_atestado_policial": "Polis raporu/şikayet",
  "diary": "Günlük",
  "diploma_o_certificado_decorativo": "Dekoratif diploma/sertifika",
  "ejecutoria_de_hidalguia_u_otra": "Asalet hükmü (ejecutoria)",
  "entrada_billete_de_espectaculo": "Etkinlik / gösteri bileti",
  "envoltorio_etiqueta_de_producto": "Ürün ambalajı / etiketi",
  "ermita_capilla": "İnziva kilisesi / şapel",
  "escritura_de_compraventa": "Satış tapusu",
  "escudo_de_armas_expediente_heraldico": "Arma / heraldik dosya",
  "escudo_de_casa_piedra_armera": "Hane arması (arma taşı)",
  "escudo_heraldico_en_fachada": "Cephede heraldik arma",
  "esquela_necrologica": "Ölüm bildirimi / ölüm ilanı",
  "estacion_de_ferrocarril_historica": "Tarihi tren istasyonu",
  "estatua_busto_conmemorativo": "Hatıra heykeli / büstü",
  "etiqueta_de_correspondencia_comercial": "Ticari antetli kağıt / etiket",
  "etiqueta_de_equipaje_hotel": "Bagaj / otel etiketi",
  "ex_libris": "Ekslibris (kitap etiketi)",
  "expediente_academico_matricula_escolar": "Akademik kayıt / okula kayıt",
  "expediente_de_depuracion_represion_polit": "Tasfiye/siyasi baskı dosyası",
  "expediente_de_dispensa_matrimonial": "Evlilik izni dosyası",
  "expediente_de_hidalguia_nobleza": "Asalet / hidalguía dosyası",
  "expediente_de_limpieza_de_sangre": "Kan saflığı (limpieza de sangre) dosyası",
  "expediente_de_ordenacion_sacerdotal": "Rahiplik takdis dosyası",
  "expediente_de_quintas_sorteo": "Zorunlu askerlik / kura dosyası",
  "expediente_penitenciario": "Cezaevi dosyası",
  "fabrica_historica": "Tarihi fabrika",
  "faro": "Deniz feneri",
  "folleto_publicitario": "Reklam broşürü",
  "photograph": "Fotoğraf",
  "fuente_monumental": "Anıtsal çeşme",
  "fuero_carta_de_poblacion": "İmtiyaz / yerleşim beratı",
  "grabado_litografia": "Gravür / litografi",
  "hoja_de_servicios": "Hizmet kaydı",
  "horno_de_pan_de_cal": "Ekmek / kireç fırını",
  "hospital_historico": "Tarihi hastane",
  "horreo": "Yükseltilmiş tahıl ambarı (hórreo)",
  "iglesia": "Kilise",
  "illustration": "İllüstrasyon",
  "transcription": "Dizin / transkripsiyon",
  "inventario_post_mortem": "Ölüm sonrası envanter",
  "invitacion": "Davet",
  "jardin_historico": "Tarihi bahçe",
  "juguete_de_papel_recortable": "Kâğıt oyuncak / kesilebilir model",
  "libro_de_cofradia_hermandad": "Cemiyet / kardeşlik defteri",
  "libro_de_confirmaciones": "Konfirmasyon kayıt defteri",
  "libro_de_cuentas_familiar": "Aile hesap defteri",
  "libro_de_defunciones_por_epidemia": "Salgın ölüm kayıtları",
  "libro_de_escolaridad_calificaciones": "Okul karnesi / not defteri",
  "libro_de_fabrica_parroquial": "Kilise gelir-gider defteri",
  "libro_de_familia": "Aile kayıt defteri",
  "lonja_mercado_historico": "Tarihi borsa/pazar salonu",
  "map": "Harita / plan",
  "matricula_del_mar": "Denizciler kaydı (matrícula del mar)",
  "mayorazgo_vinculo": "Miras bağıyla korunan mülk (mayorazgo)",
  "medalla_conmemorativa": "Hatıra madalyası",
  "memoirs": "Anılar",
  "menu_de_restaurante_o_banquete": "Restoran / ziyafet menüsü",
  "miliario": "Kilometre taşı (miliario)",
  "mojon_hito_de_termino": "Sınır işaretleyici",
  "molino": "Değirmen",
  "monasterio_convento": "Manastır / rahibe manastırı",
  "moneda_historica": "Tarihî sikke",
  "monumento_a_los_caidos": "Savaş / şehitler anıtı",
  "muralla": "Şehir suru",
  "naipe_baraja_publicitaria": "Oyun kağıdı / reklam destesi",
  "necropolis": "Nekropol",
  "necropolis_judia": "Yahudi nekropolü",
  "nicho_columbario": "Niş / kolumbaryum",
  "noria_pozo": "Su çarkı / kuyu",
  "notes": "Notlar",
  "nomina_libro_de_jornales": "Bordro / maaş defteri",
  "obelisco": "Dikilitaş",
  "artwork": "Sanat eseri",
  "other_doc": "Diğer belge",
  "padron_de_riqueza_catastro": "Arazi varlığı sicili / kadastro",
  "palacio_casona_indiana": "Saray / Indiano malikanesi",
  "palomar": "Güvercinlik",
  "panteon_mausoleo_familiar": "Aile panteonu / mozolesi",
  "panteon_de_hombres_ilustres": "Ünlü şahsiyetlerin panteonu",
  "papel_moneda_local_vale_de_emergencia": "Yerel banknot / acil durum kuponu",
  "parte_de_guerra_correspondencia_militar": "Savaş raporu / askerî yazışma",
  "particion_de_herencia": "Tereke taksimi",
  "baptism_record": "Vaftiz kaydı",
  "death_record": "Ölüm kaydı",
  "marriage_record": "Evlilik kaydı",
  "birth_record": "Doğum kaydı",
  "partitura_o_cancionero_popular": "Notalar / popüler şarkı kitabı",
  "pasaporte_salvoconducto": "Pasaport / geçiş belgesi",
  "patente_o_privilegio_industrial": "Patent/sınai imtiyaz",
  "patrimonio_de_la_humanidad_unesco": "Dünya Mirası Alanı (UNESCO)",
  "petroglifo": "Petroglif",
  "pila_bautismal_historica": "Tarihî vaftiz kurnası",
  "placa_conmemorativa": "Hatıra plaketi",
  "plaza_mayor_historica": "Tarihi ana meydan",
  "pleito_civil": "Hukuk davası",
  "poder_notarial": "Vekâletname",
  "postal": "Kartpostal",
  "poste_indicador_antiguo": "Eski yön tabelası",
  "presa_azud_historico": "Tarihi baraj / savak",
  "privilegio_real_merced": "Kraliyet ayrıcalığı / hibe",
  "profesion_religiosa_toma_de_habito": "Dinî adak / ruhban kıyafeti giyme",
  "programa_de_mano": "Etkinlik programı",
  "protocolo_notarial": "Noter protokolü",
  "posito": "Ortak tahıl deposu (pósito)",
  "puente_historico": "Tarihi köprü",
  "puerto_historico": "Tarihi liman",
  "publicidad_recortada_de_prensa": "Gazeteden kesilmiş ilan",
  "real_cedula": "Kraliyet fermanı (cédula real)",
  "recorte_de_hemeroteca_noticia_de_periodi": "Gazete kupürü / haber",
  "recordatorio_religioso": "Dini anma kartı",
  "migration": "Göç kaydı",
  "military": "Askerî kayıt",
  "reloj_de_sol": "Güneş saati",
  "retablo": "Sunak panosu (retablo)",
  "ruta_o_camino_historico": "Tarihi rota/yol",
  "santuario": "Kutsal alan / türbe",
  "sello_vineta_fiscal_benefica_conmemorati": "Damga/mühür (mali, hayır kurumu, hatıra)",
  "sello_postal_filatelia": "Posta pulu (filateli)",
  "sentencia_judicial": "Mahkeme kararı",
  "sepulcro_arca_funeraria": "Mezar / lahit",
  "sinagoga_mezquita_historica": "Tarihi sinagog/cami",
  "sitio_historico": "Tarihi yer",
  "tarjeta_de_visita_felicitacion": "Kartvizit / tebrik kartı",
  "tebeo_comic": "Çizgi roman",
  "teatro_historico": "Tarihi tiyatro",
  "testamento_codicilo": "Vasiyetname / ek vasiyet",
  "titulo_o_diploma": "Unvan / diploma",
  "torre_defensiva_torreon": "Savunma kulesi / burç",
  "administrative": "İdari işlem",
  "universidad_historica": "Tarihi üniversite",
  "vale_cupon_bono_de_racionamiento": "Kupon / karne fişi",
  "via_crucis_hornacina": "Haç Yolu / yol kenarı nişi",
  "villa_romana": "Roma villası",
  "visita_pastoral": "Pastoral ziyaret",
  "yacimiento_arqueologico": "Arkeolojik sit",
  "lapida_losa_sepulcral": "Mezar taşı/mezar levhası",
  "epitafio": "Mezar kitabesi",
  "dolmen_menhir_tumulo_megalitico": "Dolmen / menhir / megalitik höyük",
};

export const DOC_FACET_LABEL_TR: Record<string, string> = {
  "Documentary heritage": "Belgesel miras",
  "Built / monumental heritage": "Yapılı / anıtsal miras",
  "Ephemera": "Efemera",
  "Archaeological heritage": "Arkeolojik miras",
  "Intangible heritage": "Somut olmayan kültürel miras",
  "Prehistory / Antiquity": "Tarih öncesi / Antik Çağ",
  "Medieval": "Orta Çağ",
  "Early modern": "Erken modern dönem",
  "Contemporary": "Çağdaş dönem",
  "Present day": "Günümüz",
  "Cross-period": "Dönemler arası",
  "Civil": "Sivil",
  "Commercial": "Ticari",
  "Domestic": "Ev içi",
  "Educational": "Eğitsel",
  "Funerary": "Cenaze",
  "Heraldic": "Heraldik",
  "Judicial": "Adli",
  "Labour": "Çalışma hayatı",
  "Military": "Askerî",
  "Notarial": "Noterlik",
  "Leisure & popular culture": "Eğlence ve popüler kültür",
  "Press": "Basın",
  "Religious": "Dinî",
  "Health": "Sağlık",
  "Vital record": "Medeni hâl kaydı",
  "File / procedure": "Dosya / işlem",
  "Correspondence": "Yazışma",
  "Personal / narrative writing": "Kişisel / anlatı yazısı",
  "Database / transcription": "Veri tabanı / transkripsiyon",
  "Civil architecture": "Sivil mimari",
  "Funerary architecture": "Mezar mimarisi",
  "Military / defensive architecture": "Askerî / savunma mimarisi",
  "Religious architecture": "Dinî mimari",
  "Rural / vernacular architecture": "Kırsal / yerel mimari",
  "Natural feature": "Doğal unsur",
  "Minor urban feature": "Küçük kentsel unsur",
  "Infrastructure": "Altyapı",
  "Listed / protected": "Tescilli / koruma altında",
  "No formal protection": "Resmî koruma yok",
  "Photographic": "Fotoğraf",
  "Printed": "Basılı",
  "Manuscript": "El yazması",
  "Object": "Nesne",
  "Useful for genealogy": "Şecere araştırması için yararlı",
};
