/** Complete Korean catalogue; mirrors archiveDocTypes.zh-TW.ts. */
export const DOC_TYPE_LABEL_KO: Record<string, string> = {
  "acta_de_asociacion_sociedad": "협회 · 학회 회의록",
  "acta_de_pleno_municipal_cabildo": "마을 의회/카빌도 회의록",
  "acta_notarial": "공증 증서",
  "acueducto": "수로",
  "anuncio_de_prensa": "신문광고",
  "arbol_genealogico_anterior": "이전 가계도",
  "arco_triunfal": "개선문",
  "arrendamiento_contrato_de_colonia": "임대/임대차 계약",
  "atalaya_torre_vigia": "망대",
  "auto_de_fe_expediente_inquisitorial": "아우토다페 / 인퀴지션 파일",
  "ayuntamiento_historico": "역사적인 시청",
  "bando_ordenanza_municipal": "포고 / 조례",
  "database": "데이터 베이스",
  "bien_de_interes_cultural_bic": "등재유산(BIC)",
  "billete_de_embarque": "탑승/승선권",
  "billete_de_transporte": "교통 티켓",
  "bodega_lagar_tradicional": "전통 와이너리/프레스하우스",
  "bula_indulgencia": "교황의 교서/면죄",
  "bunker_fortificacion": "벙커/요새",
  "caja_de_cerillas_fosforera": "성냥갑",
  "calendario_publicitario": "광고캘린더",
  "calzada_romana": "로마의 길",
  "campana_con_inscripcion_fundacional": "벨(기본 비문 있음)",
  "carta_de_aprendizaje_examen_de_maestria_": "견습/길드 마스터쉽 기록",
  "carta_de_fundacion": "재단 헌장",
  "carta_de_naturaleza_nacionalizacion": "귀화/시민권 기록",
  "carta_de_pago_recibo_de_deuda": "지급영수증/채무인수",
  "carcel_historica": "역사적인 감옥",
  "cartel_poster": "포스터",
  "cartilla_de_la_seguridad_social_mutualid": "사회 보장 / 뮤추얼 펀드 소책자",
  "cartilla_militar_libreta_de_servicio": "병역 소책자",
  "castillo_fortaleza": "성/요새",
  "castro": "힐포트(카스트로)",
  "catedral": "성당",
  "causa_penal_sumario": "형사사건/기소",
  "cedula_de_identidad": "신분증",
  "cementerio_historico": "역사적인 묘지",
  "cenotafio": "기념비",
  "census": "인구 조사 / 주민 등록",
  "censo_enfiteutico_foro": "폐기종 / 지상 임대료",
  "certificado_de_vacunacion": "예방접종 증명서",
  "chapa_pin_conmemorativo": "기념핀/배지",
  "chimenea_industrial": "산업용 굴뚝",
  "colegiata": "대학교회",
  "concordia_acuerdo_entre_partes": "콩코르디아(당사자 간 합의)",
  "conjunto_historico_artistico": "역사예술 앙상블",
  "contrato_de_matrimonio_civil": "민사결혼계약",
  "contrato_de_trabajo": "고용 계약",
  "letter": "일치",
  "cromo_album_de_cromos": "트레이딩 카드/스티커 앨범",
  "cruceiro_cruz_de_piedra": "돌 길가 십자가(cruceiro)",
  "cruz_de_termino_o_de_cementerio": "경계/묘지 십자가",
  "decreto_ley_historica": "법령 / 역사적 법률",
  "denuncia_atestado_policial": "경찰 신고/고발",
  "diary": "다이어리",
  "diploma_o_certificado_decorativo": "장식 졸업장/증명서",
  "ejecutoria_de_hidalguia_u_otra": "Ejecutoria (귀족의 특허 / 판결)",
  "entrada_billete_de_espectaculo": "이벤트/공연 티켓",
  "envoltorio_etiqueta_de_producto": "제품 포장지/라벨",
  "ermita_capilla": "암자 / 예배당",
  "escritura_de_compraventa": "판매 증서",
  "escudo_de_armas_expediente_heraldico": "문장 / 문장 파일",
  "escudo_de_casa_piedra_armera": "가문의 문장(문장)",
  "escudo_heraldico_en_fachada": "외관의 문장 방패",
  "esquela_necrologica": "사망 통지 / 사망 기사",
  "estacion_de_ferrocarril_historica": "역사적인 기차역",
  "estatua_busto_conmemorativo": "기념 동상 / 흉상",
  "etiqueta_de_correspondencia_comercial": "상업용 레터헤드/라벨",
  "etiqueta_de_equipaje_hotel": "수하물 / 호텔 라벨",
  "ex_libris": "Ex-libris(장서표)",
  "expediente_academico_matricula_escolar": "학업성적/재학",
  "expediente_de_depuracion_represion_polit": "퍼지/정치 탄압 파일",
  "expediente_de_dispensa_matrimonial": "결혼 경륜 파일",
  "expediente_de_hidalguia_nobleza": "귀족 / hidalguía 파일",
  "expediente_de_limpieza_de_sangre": "혈액 순도(limpieza de sangre) 파일",
  "expediente_de_ordenacion_sacerdotal": "성직자 안수 파일",
  "expediente_de_quintas_sorteo": "징병/초안 파일",
  "expediente_penitenciario": "감옥/교도소 파일",
  "fabrica_historica": "역사적인 공장",
  "faro": "등대",
  "folleto_publicitario": "광고 전단지",
  "photograph": "사진",
  "fuente_monumental": "기념비적인 분수",
  "fuero_carta_de_poblacion": "특권헌장/결제헌장",
  "grabado_litografia": "조각 / 석판화",
  "hoja_de_servicios": "서비스 기록",
  "horno_de_pan_de_cal": "빵 / 라임 오븐",
  "hospital_historico": "역사적인 병원",
  "horreo": "높은 곡물창고(horreo)",
  "iglesia": "교회",
  "illustration": "삽화",
  "transcription": "색인 / 전사",
  "inventario_post_mortem": "사후 재고",
  "invitacion": "초대",
  "jardin_historico": "역사적인 정원",
  "juguete_de_papel_recortable": "종이 장난감 / 컷 아웃",
  "libro_de_cofradia_hermandad": "형제애 / 형제애 책",
  "libro_de_confirmaciones": "확인 등록",
  "libro_de_cuentas_familiar": "가계부",
  "libro_de_defunciones_por_epidemia": "전염병 사망자 등록",
  "libro_de_escolaridad_calificaciones": "학교/성적기록",
  "libro_de_fabrica_parroquial": "교구 직물 장부",
  "libro_de_familia": "가족 기록부",
  "lonja_mercado_historico": "역사교류/시장회관",
  "map": "지도 / 계획",
  "matricula_del_mar": "선원 등록부(matrícula del mar)",
  "mayorazgo_vinculo": "수반부동산(mayorazgo)",
  "medalla_conmemorativa": "기념메달",
  "memoirs": "논문집",
  "menu_de_restaurante_o_banquete": "레스토랑 / 연회 메뉴",
  "miliario": "마일스톤(miliario)",
  "mojon_hito_de_termino": "경계 표식",
  "molino": "밀",
  "monasterio_convento": "수도원/수녀원",
  "moneda_historica": "역사적인 동전",
  "monumento_a_los_caidos": "전쟁/전몰자 추모비",
  "muralla": "성벽",
  "naipe_baraja_publicitaria": "트럼프패/광고 데크",
  "necropolis": "대규모 묘지",
  "necropolis_judia": "유대인 묘지",
  "nicho_columbario": "틈새시장/콜럼바리움",
  "noria_pozo": "물레방아/우물",
  "notes": "메모",
  "nomina_libro_de_jornales": "급여 / 임금 장부",
  "obelisco": "오벨리스크",
  "artwork": "삽화",
  "other_doc": "기타 문서",
  "padron_de_riqueza_catastro": "재산 등록 / 지적",
  "palacio_casona_indiana": "궁전/인디아노 매너 하우스",
  "palomar": "비둘기장",
  "panteon_mausoleo_familiar": "가족 판테온 / 영묘",
  "panteon_de_hombres_ilustres": "저명한 인물의 판테온",
  "papel_moneda_local_vale_de_emergencia": "지역권/비상전권",
  "parte_de_guerra_correspondencia_militar": "전쟁파병/군서신",
  "particion_de_herencia": "재산 분할",
  "baptism_record": "세례 기록",
  "death_record": "사망 기록",
  "marriage_record": "결혼 기록",
  "birth_record": "출생 기록",
  "partitura_o_cancionero_popular": "악보/인기가요집",
  "pasaporte_salvoconducto": "여권 / 안전 통행",
  "patente_o_privilegio_industrial": "특허/산업특권",
  "patrimonio_de_la_humanidad_unesco": "세계문화유산(유네스코)",
  "petroglifo": "암각화",
  "pila_bautismal_historica": "역사적인 세례반",
  "placa_conmemorativa": "기념패",
  "plaza_mayor_historica": "역사적인 중앙 광장",
  "pleito_civil": "민사소송",
  "poder_notarial": "위임장",
  "postal": "엽서",
  "poste_indicador_antiguo": "오래된 표지판",
  "presa_azud_historico": "역사적인 댐/보",
  "privilegio_real_merced": "왕실 특권/부여",
  "profesion_religiosa_toma_de_habito": "종교 직업 / 서약",
  "programa_de_mano": "프로그램(플레이빌)",
  "protocolo_notarial": "공증 프로토콜",
  "posito": "공동 곡물 상점(posito)",
  "puente_historico": "역사적인 다리",
  "puerto_historico": "역사적인 항구",
  "publicidad_recortada_de_prensa": "잘린 언론 광고",
  "real_cedula": "왕실 법령(real cédula)",
  "recorte_de_hemeroteca_noticia_de_periodi": "언론 스크랩/뉴스 항목",
  "recordatorio_religioso": "종교기념카드",
  "migration": "마이그레이션 기록",
  "military": "군사 기록",
  "reloj_de_sol": "해시계",
  "retablo": "제단화(레타블로)",
  "ruta_o_camino_historico": "역사적인 길 / 도로",
  "santuario": "성역 / 신사",
  "sello_vineta_fiscal_benefica_conmemorati": "우표 / 인감 (재정, 자선, 기념)",
  "sello_postal_filatelia": "우표(우표)",
  "sentencia_judicial": "법원 판결",
  "sepulcro_arca_funeraria": "무덤 / 장례 상자",
  "sinagoga_mezquita_historica": "역사적인 회당/모스크",
  "sitio_historico": "역사적인 장소",
  "tarjeta_de_visita_felicitacion": "방문/인사말 카드",
  "tebeo_comic": "만화 잡지",
  "teatro_historico": "역사적인 극장",
  "testamento_codicilo": "윌/코디실",
  "titulo_o_diploma": "학위 / 졸업장",
  "torre_defensiva_torreon": "방어 타워",
  "administrative": "행정절차",
  "universidad_historica": "역사적인 대학",
  "vale_cupon_bono_de_racionamiento": "배급권/쿠폰",
  "via_crucis_hornacina": "십자가의 길/틈새 성소",
  "villa_romana": "로마 빌라",
  "visita_pastoral": "목회자 방문",
  "yacimiento_arqueologico": "고고학 유적지",
  "lapida_losa_sepulcral": "묘비 / 무덤 석판",
  "epitafio": "비문",
  "dolmen_menhir_tumulo_megalitico": "고인돌/선돌/거석 마운드",
};

export const DOC_FACET_LABEL_KO: Record<string, string> = {
  "Documentary heritage": "다큐멘터리 유산",
  "Built / monumental heritage": "건축 / 기념비적 유산",
  "Ephemera": "하루살이",
  "Archaeological heritage": "고고학 유산",
  "Intangible heritage": "무형유산",
  "Prehistory / Antiquity": "선사시대/고대",
  "Medieval": "중세",
  "Early modern": "근대 초기",
  "Contemporary": "현대의",
  "Present day": "현재",
  "Cross-period": "기간 간",
  "Civil": "예의 바른",
  "Commercial": "광고",
  "Domestic": "국내의",
  "Educational": "교육적",
  "Funerary": "장례식",
  "Heraldic": "문장학",
  "Judicial": "사법",
  "Labour": "노동",
  "Military": "군대",
  "Notarial": "공증인",
  "Leisure & popular culture": "레저 및 대중문화",
  "Press": "누르다",
  "Religious": "종교의",
  "Health": "건강",
  "Vital record": "중요한 기록",
  "File / procedure": "파일/절차",
  "Correspondence": "일치",
  "Personal / narrative writing": "개인/서사적 글쓰기",
  "Database / transcription": "데이터베이스 / 전사",
  "Civil architecture": "토목 건축",
  "Funerary architecture": "장례식 건축",
  "Military / defensive architecture": "군사/방어 아키텍처",
  "Religious architecture": "종교 건축",
  "Rural / vernacular architecture": "농촌 / 토속 건축",
  "Natural feature": "자연적인 특징",
  "Minor urban feature": "사소한 도시 특징",
  "Infrastructure": "하부 구조",
  "Listed / protected": "등록/보호",
  "No formal protection": "공식적인 보호가 없음",
  "Photographic": "사진",
  "Printed": "인쇄됨",
  "Manuscript": "원고",
  "Object": "물체",
  "Useful for genealogy": "족보에 유용함",
};
