/** Complete Traditional Chinese catalogue; mirrors archiveDocTypes.it.ts / .tr.ts. */
export const DOC_TYPE_LABEL_ZH_TW: Record<string, string> = {
  "acta_de_asociacion_sociedad": "協會 / 社團會議紀要",
  "acta_de_pleno_municipal_cabildo": "市政會議 / 市議會紀要",
  "acta_notarial": "公證記錄",
  "acueducto": "引水渠",
  "anuncio_de_prensa": "報紙廣告",
  "arbol_genealogico_anterior": "早期家譜",
  "arco_triunfal": "凱旋門",
  "arrendamiento_contrato_de_colonia": "租賃 / 租佃合同",
  "atalaya_torre_vigia": "瞭望塔 / 警戒塔",
  "auto_de_fe_expediente_inquisitorial": "火刑宣判 / 宗教裁判檔案",
  "ayuntamiento_historico": "歷史市政廳",
  "bando_ordenanza_municipal": "公告 / 市政條例",
  "database": "資料庫",
  "bien_de_interes_cultural_bic": "受保護文化遺產（BIC）",
  "billete_de_embarque": "登機 / 登船票",
  "billete_de_transporte": "交通票據",
  "bodega_lagar_tradicional": "傳統酒窖 / 榨酒坊",
  "bula_indulgencia": "教宗詔書 / 贖罪券",
  "bunker_fortificacion": "地堡 / 防禦工事",
  "caja_de_cerillas_fosforera": "火柴盒",
  "calendario_publicitario": "廣告日曆",
  "calzada_romana": "古羅馬道路",
  "campana_con_inscripcion_fundacional": "銅鐘（帶始建銘文）",
  "carta_de_aprendizaje_examen_de_maestria_": "學徒契約 / 行會師傅資格記錄",
  "carta_de_fundacion": "建立特許狀",
  "carta_de_naturaleza_nacionalizacion": "入籍 / 歸化文書",
  "carta_de_pago_recibo_de_deuda": "付款收據 / 債務清償證明",
  "carcel_historica": "歷史監獄",
  "cartel_poster": "海報",
  "cartilla_de_la_seguridad_social_mutualid": "社保 / 互助會手冊",
  "cartilla_militar_libreta_de_servicio": "兵役證 / 服役手冊",
  "castillo_fortaleza": "城堡 / 要塞",
  "castro": "山丘堡壘（castro）",
  "catedral": "主教座堂",
  "causa_penal_sumario": "刑事案件 / 預審卷宗",
  "cedula_de_identidad": "身份證",
  "cementerio_historico": "歷史公墓",
  "cenotafio": "衣冠冢",
  "census": "人口普查 / 戶籍冊",
  "censo_enfiteutico_foro": "永佃權 / 地租",
  "certificado_de_vacunacion": "疫苗接種證明",
  "chapa_pin_conmemorativo": "紀念徽章 / 胸針",
  "chimenea_industrial": "工業煙囪",
  "colegiata": "協同教堂",
  "concordia_acuerdo_entre_partes": "和解協議（當事人之間）",
  "conjunto_historico_artistico": "歷史藝術建築群",
  "contrato_de_matrimonio_civil": "民事婚姻契約",
  "contrato_de_trabajo": "勞動合同",
  "letter": "通訊",
  "cromo_album_de_cromos": "集換卡 / 貼紙冊",
  "cruceiro_cruz_de_piedra": "石制路邊十字架（cruceiro）",
  "cruz_de_termino_o_de_cementerio": "地界 / 墓地十字架",
  "decreto_ley_historica": "法令 / 歷史法律",
  "denuncia_atestado_policial": "報案 / 警方筆錄",
  "diary": "日記",
  "diploma_o_certificado_decorativo": "裝飾性文憑 / 證書",
  "ejecutoria_de_hidalguia_u_otra": "貴族身份判決（ejecutoria）",
  "entrada_billete_de_espectaculo": "演出門票",
  "envoltorio_etiqueta_de_producto": "產品包裝 / 標籤",
  "ermita_capilla": "隱修堂 / 小教堂",
  "escritura_de_compraventa": "買賣契約",
  "escudo_de_armas_expediente_heraldico": "紋章 / 紋章檔案",
  "escudo_de_casa_piedra_armera": "宅邸紋章（紋章石）",
  "escudo_heraldico_en_fachada": "立面紋章",
  "esquela_necrologica": "訃告",
  "estacion_de_ferrocarril_historica": "歷史火車站",
  "estatua_busto_conmemorativo": "紀念雕像 / 半身像",
  "etiqueta_de_correspondencia_comercial": "商業信箋 / 標籤",
  "etiqueta_de_equipaje_hotel": "行李 / 酒店標籤",
  "ex_libris": "藏書票（ex-libris）",
  "expediente_academico_matricula_escolar": "學籍檔案 / 入學註冊",
  "expediente_de_depuracion_represion_polit": "清洗 / 政治迫害檔案",
  "expediente_de_dispensa_matrimonial": "婚姻豁免檔案",
  "expediente_de_hidalguia_nobleza": "貴族 / 伊達爾戈身份檔案",
  "expediente_de_limpieza_de_sangre": "血統純正檔案（limpieza de sangre）",
  "expediente_de_ordenacion_sacerdotal": "神職授任檔案",
  "expediente_de_quintas_sorteo": "徵兵 / 抽籤檔案",
  "expediente_penitenciario": "監獄檔案",
  "fabrica_historica": "歷史工廠",
  "faro": "燈塔",
  "folleto_publicitario": "廣告傳單",
  "photograph": "照片",
  "fuente_monumental": "紀念性噴泉",
  "fuero_carta_de_poblacion": "特許狀 / 定居特許狀",
  "grabado_litografia": "版畫 / 石版畫",
  "hoja_de_servicios": "服役記錄",
  "horno_de_pan_de_cal": "麵包爐 / 石灰窯",
  "hospital_historico": "歷史醫院",
  "horreo": "高架糧倉（hórreo）",
  "iglesia": "教堂",
  "illustration": "插圖",
  "transcription": "索引 / 轉錄",
  "inventario_post_mortem": "身後財產清單",
  "invitacion": "請柬",
  "jardin_historico": "歷史園林",
  "juguete_de_papel_recortable": "紙玩具 / 剪紙",
  "libro_de_cofradia_hermandad": "兄弟會簿冊",
  "libro_de_confirmaciones": "堅振登記簿",
  "libro_de_cuentas_familiar": "家庭賬簿",
  "libro_de_defunciones_por_epidemia": "疫病死亡登記簿",
  "libro_de_escolaridad_calificaciones": "學籍 / 成績記錄",
  "libro_de_fabrica_parroquial": "堂區經費賬簿",
  "libro_de_familia": "家庭登記簿",
  "lonja_mercado_historico": "歷史交易所 / 市場",
  "map": "地圖 / 平面圖",
  "matricula_del_mar": "海員登記冊（matrícula del mar）",
  "mayorazgo_vinculo": "長子繼承產業（mayorazgo）",
  "medalla_conmemorativa": "紀念章",
  "memoirs": "回憶錄",
  "menu_de_restaurante_o_banquete": "餐廳 / 宴會選單",
  "miliario": "里程碑（miliario）",
  "mojon_hito_de_termino": "界碑",
  "molino": "磨坊",
  "monasterio_convento": "修道院 / 女修道院",
  "moneda_historica": "歷史錢幣",
  "monumento_a_los_caidos": "陣亡將士紀念碑",
  "muralla": "城牆",
  "naipe_baraja_publicitaria": "紙牌 / 廣告牌組",
  "necropolis": "墓園",
  "necropolis_judia": "猶太墓園",
  "nicho_columbario": "壁龕 / 骨灰龕",
  "noria_pozo": "水車 / 水井",
  "notes": "筆記",
  "nomina_libro_de_jornales": "工資單 / 工錢賬簿",
  "obelisco": "方尖碑",
  "artwork": "藝術品",
  "other_doc": "其他文件",
  "padron_de_riqueza_catastro": "財產登記冊 / 地籍",
  "palacio_casona_indiana": "宮殿 / 印第亞諾宅第",
  "palomar": "鴿舍",
  "panteon_mausoleo_familiar": "家族先賢祠 / 陵墓",
  "panteon_de_hombres_ilustres": "名人先賢祠",
  "papel_moneda_local_vale_de_emergencia": "地方紙幣 / 應急代幣券",
  "parte_de_guerra_correspondencia_militar": "戰報 / 軍事通訊",
  "particion_de_herencia": "遺產分割",
  "baptism_record": "洗禮記錄",
  "death_record": "死亡記錄",
  "marriage_record": "婚姻記錄",
  "birth_record": "出生記錄",
  "partitura_o_cancionero_popular": "樂譜 / 民歌集",
  "pasaporte_salvoconducto": "護照 / 通行證",
  "patente_o_privilegio_industrial": "專利 / 工業特權",
  "patrimonio_de_la_humanidad_unesco": "世界遺產（UNESCO）",
  "petroglifo": "巖刻",
  "pila_bautismal_historica": "歷史洗禮池",
  "placa_conmemorativa": "紀念牌",
  "plaza_mayor_historica": "歷史主廣場",
  "pleito_civil": "民事訴訟",
  "poder_notarial": "授權委託書",
  "postal": "明信片",
  "poste_indicador_antiguo": "舊路標",
  "presa_azud_historico": "歷史水壩 / 堰",
  "privilegio_real_merced": "王室特許 / 恩賜",
  "profesion_religiosa_toma_de_habito": "入會發願 / 受戒",
  "programa_de_mano": "演出節目單",
  "protocolo_notarial": "公證文書簿",
  "posito": "公共糧倉（pósito）",
  "puente_historico": "歷史橋梁",
  "puerto_historico": "歷史港口",
  "publicidad_recortada_de_prensa": "剪報廣告",
  "real_cedula": "王室敕令",
  "recorte_de_hemeroteca_noticia_de_periodi": "報刊剪報 / 新聞剪報",
  "recordatorio_religioso": "宗教紀念卡",
  "migration": "移民記錄",
  "military": "軍事記錄",
  "reloj_de_sol": "日晷",
  "retablo": "祭壇屏畫",
  "ruta_o_camino_historico": "歷史路線 / 古道",
  "santuario": "聖所 / 神龕",
  "sello_vineta_fiscal_benefica_conmemorati": "印章 / 票籤（稅票、慈善、紀念）",
  "sello_postal_filatelia": "郵票（集郵）",
  "sentencia_judicial": "法院判決",
  "sepulcro_arca_funeraria": "墓穴 / 石棺",
  "sinagoga_mezquita_historica": "歷史猶太會堂 / 清真寺",
  "sitio_historico": "歷史遺址",
  "tarjeta_de_visita_felicitacion": "名片 / 賀卡",
  "tebeo_comic": "漫畫",
  "teatro_historico": "歷史劇院",
  "testamento_codicilo": "遺囑 / 遺囑附錄",
  "titulo_o_diploma": "學位 / 文憑",
  "torre_defensiva_torreon": "防禦塔 / 堡壘",
  "administrative": "行政手續",
  "universidad_historica": "歷史大學",
  "vale_cupon_bono_de_racionamiento": "配給券 / 票證",
  "via_crucis_hornacina": "苦路 / 壁龕",
  "villa_romana": "古羅馬別墅",
  "visita_pastoral": "牧靈訪問",
  "yacimiento_arqueologico": "考古遺址",
  "lapida_losa_sepulcral": "墓碑 / 墓板",
  "epitafio": "墓誌銘",
  "dolmen_menhir_tumulo_megalitico": "石棚 / 立石 / 巨石冢"
};

export const DOC_FACET_LABEL_ZH_TW: Record<string, string> = {
  "Documentary heritage": "文獻遺產",
  "Built / monumental heritage": "建築遺產",
  "Ephemera": "臨時資料",
  "Archaeological heritage": "考古遺產",
  "Intangible heritage": "非物質遺產",
  "Prehistory / Antiquity": "史前 / 古代",
  "Medieval": "中世紀",
  "Early modern": "近代早期",
  "Contemporary": "當代",
  "Present day": "現今",
  "Cross-period": "跨時期",
  "Civil": "民用",
  "Commercial": "商業",
  "Domestic": "家庭",
  "Educational": "教育",
  "Funerary": "喪葬",
  "Heraldic": "紋章",
  "Judicial": "司法",
  "Labour": "勞動",
  "Military": "軍事",
  "Notarial": "公證",
  "Leisure & popular culture": "休閒與大眾文化",
  "Press": "報刊",
  "Religious": "宗教",
  "Health": "醫療衛生",
  "Vital record": "民事登記記錄",
  "File / procedure": "案卷 / 手續",
  "Correspondence": "書信",
  "Personal / narrative writing": "個人 / 敘事寫作",
  "Database / transcription": "資料庫 / 轉錄",
  "Civil architecture": "民用建築",
  "Funerary architecture": "喪葬建築",
  "Military / defensive architecture": "軍事 / 防禦建築",
  "Religious architecture": "宗教建築",
  "Rural / vernacular architecture": "鄉村 / 鄉土建築",
  "Natural feature": "自然要素",
  "Minor urban feature": "城市小型要素",
  "Infrastructure": "基礎設施",
  "Listed / protected": "已列入保護 / 受保護",
  "No formal protection": "無正式保護",
  "Photographic": "攝影",
  "Printed": "印刷",
  "Manuscript": "手稿",
  "Object": "實物",
  "Useful for genealogy": "有助族譜研究"
};
