// Stable runtime messages shared by IPC and persisted image failure cards.
const rows = [
  ['The chat was deleted or changed.', 'El chat se ha eliminado o ha cambiado.', 'Le chat a été supprimé ou modifié.', 'Der Chat wurde gelöscht oder geändert.', 'O chat foi eliminado ou alterado.', 'O chat foi excluído ou alterado.', 'La chat è stata eliminata o modificata.', 'Sohbet silindi veya değiştirildi.', "对话已被删除或更改。", "對話已被刪除或更改。", "チャットが削除または変更されました。", "채팅이 삭제되거나 변경되었습니다."],
  ['Download original image', 'Descargar imagen original', 'Télécharger l’image originale', 'Originalbild herunterladen', 'Transferir imagem original', 'Baixar imagem original', 'Scarica immagine originale', 'Özgün görseli indir', "下载原图", "下載原圖", "元の画像をダウンロード", "원본 이미지 다운로드"],
  ['Original image', 'Imagen original', 'Image originale', 'Originalbild', 'Imagem original', 'Imagem original', 'Immagine originale', 'Özgün görsel', "原图", "原圖", "元の画像", "원본 이미지"],
  ['The skills library could not be read.', 'No se pudo leer la biblioteca de skills.', 'Impossible de lire la bibliothèque de skills.', 'Die Skill-Bibliothek konnte nicht gelesen werden.', 'Não foi possível ler a biblioteca de skills.', 'Não foi possível ler a biblioteca de skills.', 'Impossibile leggere la libreria di skill.', 'Skill kitaplığı okunamadı.', "无法读取技能库。", "無法讀取技能庫。", "スキルライブラリを読み取れませんでした。", "기술 라이브러리를 읽을 수 없습니다."],
  ['Add a name, description and instructions.', 'Añade un nombre, una descripción e instrucciones.', 'Ajoutez un nom, une description et des instructions.', 'Füge einen Namen, eine Beschreibung und Anweisungen hinzu.', 'Adiciona um nome, uma descrição e instruções.', 'Adicione um nome, uma descrição e instruções.', 'Aggiungi nome, descrizione e istruzioni.', 'Ad, açıklama ve talimatlar ekleyin.', "请添加名称、说明和指令。", "請新增名稱、說明和指令。", "名前、説明、手順を追加します。", "이름, 설명, 지침을 추가합니다."],
  ['The library supports up to 40 skills.', 'La biblioteca admite hasta 40 skills.', 'La bibliothèque accepte jusqu’à 40 skills.', 'Die Bibliothek unterstützt bis zu 40 Skills.', 'A biblioteca permite até 40 skills.', 'A biblioteca permite até 40 skills.', 'La libreria supporta fino a 40 skill.', 'Kitaplık en fazla 40 skill destekler.', "技能库最多支持 40 个技能。", "技能庫最多支援 40 個技能。", "ライブラリは最大40のスキルをサポートします。", "라이브러리는 최대 40개의 기술을 지원합니다."],
  ['This conversation has been deleted. Start a new chat.', 'Esta conversación se ha eliminado. Inicia un nuevo chat.', 'Cette conversation a été supprimée. Ouvrez un nouveau chat.', 'Dieses Gespräch wurde gelöscht. Starte einen neuen Chat.', 'Esta conversa foi eliminada. Inicia um novo chat.', 'Esta conversa foi excluída. Inicie um novo chat.', 'Questa conversazione è stata eliminata. Avvia una nuova chat.', 'Bu konuşma silindi. Yeni bir sohbet başlatın.', "此对话已被删除。请开始新对话。", "此對話已被刪除。請開始新對話。", "この会話は削除されました。新しいチャットを開始します。", "이 대화는 삭제되었습니다. 새로운 채팅을 시작하세요."],
  ['The generated image exceeds 40 MB.', 'La imagen generada supera los 40 MB.', 'L’image générée dépasse 40 Mo.', 'Das erzeugte Bild ist größer als 40 MB.', 'A imagem gerada excede 40 MB.', 'A imagem gerada excede 40 MB.', 'L’immagine generata supera i 40 MB.', 'Oluşturulan görsel 40 MB sınırını aşıyor.', "生成的图像超过 40 MB。", "生成的影像超過 40 MB。", "生成されたイメージは40 MB を超えます。", "생성된 이미지가 40MB를 초과합니다."],
  ['Unsupported generated image format.', 'El formato de la imagen generada no es compatible.', 'Le format de l’image générée n’est pas pris en charge.', 'Das Format des erzeugten Bildes wird nicht unterstützt.', 'O formato da imagem gerada não é suportado.', 'O formato da imagem gerada não é compatível.', 'Formato dell’immagine generata non supportato.', 'Oluşturulan görselin biçimi desteklenmiyor.', "不支持的生成图像格式。", "不支援的生成影像格式。", "生成された画像形式がサポートされていません。", "지원되지 않는 생성된 이미지 형식입니다."],
  ['Only one image can be generated per reply. Send another message to create a variation.', 'Solo se puede generar una imagen por respuesta. Envía otro mensaje para crear una variación.', 'Une seule image peut être générée par réponse. Envoyez un autre message pour créer une variante.', 'Pro Antwort kann ein Bild erstellt werden. Sende eine weitere Nachricht für eine Variante.', 'Só é possível gerar uma imagem por resposta. Envia outra mensagem para criar uma variação.', 'Só é possível gerar uma imagem por resposta. Envie outra mensagem para criar uma variação.', 'È possibile generare un’immagine per risposta. Invia un altro messaggio per creare una variante.', 'Her yanıtta bir görsel oluşturulabilir. Bir varyasyon için başka bir mesaj gönderin.', "每条回复只能生成一张图像。发送另一条消息以创建变体。", "每條回覆只能生成一張影像。傳送另一條訊息以建立變體。", "返信ごとに生成できる画像は1つだけです。別のメッセージを送信してバリエーションを作成します。", "답변당 하나의 이미지만 생성할 수 있습니다. 변형을 만들려면 다른 메시지를 보내세요."],
  ['Enable Image Atelier in Skills to generate images.', 'Activa Image Atelier en Skills para generar imágenes.', 'Activez Image Atelier dans Skills pour générer des images.', 'Aktiviere Image Atelier unter Skills, um Bilder zu erzeugen.', 'Ativa Image Atelier em Skills para gerar imagens.', 'Ative Image Atelier em Skills para gerar imagens.', 'Attiva Image Atelier in Skills per generare immagini.', 'Görsel oluşturmak için Skills bölümünde Image Atelier’i etkinleştirin.', "在「技能」中启用 Image Atelier 以生成图像。", "在「技能」中啟用 Image Atelier 以生成影像。", "スキルで Image Atelier を有効にして画像を生成します。", "이미지를 생성하려면 스킬에서 Image Atelier를 활성화하세요."],
  ['Start a saved chat in Nodi or the assistant to generate an image.', 'Inicia un chat guardado en Nodi o en el asistente para generar una imagen.', 'Ouvrez un chat enregistré dans Nodi ou l’assistant pour générer une image.', 'Starte einen gespeicherten Chat in Nodi oder im Assistenten, um ein Bild zu erzeugen.', 'Inicia um chat guardado no Nodi ou no assistente para gerar uma imagem.', 'Inicie um chat salvo no Nodi ou no assistente para gerar uma imagem.', 'Avvia una chat salvata in Nodi o nell’assistente per generare un’immagine.', 'Görsel oluşturmak için Nodi veya asistanda kayıtlı bir sohbet başlatın.', "在 Nodi 或助手中开始一个已保存的对话以生成图像。", "在 Nodi 或助手中開始一個已儲存的對話以生成影像。", "Nodi またはアシスタントで保存されたチャットを開始して、画像を生成します。", "Nodi 또는 도우미에서 저장된 채팅을 시작하여 이미지를 생성하세요."],
  ['The image brief was interrupted. Retry the response.', 'Las instrucciones de imagen se interrumpieron. Vuelve a generar la respuesta.', 'Les instructions d’image ont été interrompues. Relancez la réponse.', 'Die Bildanweisungen wurden unterbrochen. Erstelle die Antwort erneut.', 'As instruções de imagem foram interrompidas. Gera novamente a resposta.', 'As instruções da imagem foram interrompidas. Gere a resposta novamente.', 'Le istruzioni dell’immagine sono state interrotte. Rigenera la risposta.', 'Görsel talimatları kesildi. Yanıtı yeniden oluşturun.', "图像指令被中断。请重新生成回复。", "影像指令被中斷。請重新生成回覆。", "画像概要は中断されました。応答を再試行します。", "이미지 요약이 중단되었습니다. 응답을 다시 시도하십시오."],
  ['The model returned an invalid image brief. Retry the response.', 'El modelo devolvió instrucciones de imagen no válidas. Vuelve a generar la respuesta.', 'Le modèle a renvoyé des instructions d’image invalides. Relancez la réponse.', 'Das Modell lieferte ungültige Bildanweisungen. Erstelle die Antwort erneut.', 'O modelo devolveu instruções de imagem inválidas. Gera novamente a resposta.', 'O modelo retornou instruções de imagem inválidas. Gere a resposta novamente.', 'Il modello ha restituito istruzioni di immagine non valide. Rigenera la risposta.', 'Model geçersiz görsel talimatları döndürdü. Yanıtı yeniden oluşturun.', "模型返回了无效的图像指令。请重新生成回复。", "模型返回了無效的影像指令。請重新生成回覆。", "モデルは無効なイメージブリーフを返しました。応答を再試行します。", "모델이 잘못된 이미지 브리핑을 반환했습니다. 응답을 다시 시도하십시오."],
  ['Choose an image provider and model in Settings.', 'Elige un proveedor y un modelo de imagen en Ajustes.', 'Choisissez un fournisseur et un modèle d’image dans les paramètres.', 'Wähle einen Bildanbieter und ein Modell in den Einstellungen.', 'Escolhe um fornecedor e um modelo de imagem nas Definições.', 'Escolha um provedor e um modelo de imagem nas Configurações.', 'Scegli un fornitore e un modello di immagini nelle impostazioni.', 'Ayarlardan bir görsel sağlayıcısı ve modeli seçin.', "请在设置中选择图像提供商和模型。", "請在設定中選擇影像提供商和模型。", "[設定] で画像プロバイダーとモデルを選択します。", "설정에서 이미지 제공업체와 모델을 선택하세요."],
  ['Image generation failed. Please retry.', 'No se pudo generar la imagen. Vuelve a intentarlo.', 'Impossible de générer l’image. Réessayez.', 'Das Bild konnte nicht erstellt werden. Bitte erneut versuchen.', 'Não foi possível gerar a imagem. Tenta novamente.', 'Não foi possível gerar a imagem. Tente novamente.', 'Impossibile generare l’immagine. Riprova.', 'Görsel oluşturulamadı. Lütfen tekrar deneyin.', "图像生成失败。请重试。", "影像生成失敗。請重試。", "画像の生成に失敗しました。再試行してください。", "이미지 생성에 실패했습니다. 다시 시도해 주세요."],
  ['The image is no longer available.', 'La imagen ya no está disponible.', 'L’image n’est plus disponible.', 'Das Bild ist nicht mehr verfügbar.', 'A imagem já não está disponível.', 'A imagem não está mais disponível.', 'L’immagine non è più disponibile.', 'Görsel artık kullanılamıyor.', "该图像已不再可用。", "該影像已不再可用。", "画像はもう入手できません。", "이미지를 더 이상 사용할 수 없습니다."],
  ['The image could not be copied.', 'No se pudo copiar la imagen.', 'Impossible de copier l’image.', 'Das Bild konnte nicht kopiert werden.', 'Não foi possível copiar a imagem.', 'Não foi possível copiar a imagem.', 'Impossibile copiare l’immagine.', 'Görsel kopyalanamadı.', "无法复制该图像。", "無法複製該影像。", "画像をコピーできませんでした。", "이미지를 복사할 수 없습니다."],
];
export function localizeChatSkillError(message: string, language: string): string | null {
  const row = rows.find(item => item[0] === message);
  if (!row) return null;
  const index = ['en', 'es', 'fr', 'de', 'pt', 'pt-BR', 'it', 'tr', 'zh-CN', 'zh-TW', 'ja', 'ko'].indexOf(language);
  return row[index >= 0 ? index : 0];
}
