import type {
  ArchiveDescriptionUnit,
  ArchiveExcerpt,
  ArchiveItemFile,
  ArchiveRepository,
  ArchiveTextVersion,
} from './archiveTypes';
import type {
  PrimarySourceEntityProposal,
  PrimarySourceItemProfile,
  PrimarySourceNoteLink,
  PrimarySourcePersonMention,
  PrimarySourcePlaceMention,
} from './primarySourcesTypes';

const CREATED_AT = '2026-07-28T10:00:00.000Z';

export const PRIMARY_SOURCES_REFERENCE_REPOSITORY: ArchiveRepository = {
  repositoryId: 'ps-demo-repository',
  name: 'Archivo Municipal de Puerto Claro',
  shortName: 'AMPC',
  identifier: 'AMPC',
  address: null,
  websiteUrl: null,
  catalogUrl: 'https://example.invalid/catalog',
  countryCode: 'ES',
  contactNotes: null,
  accessNotes: 'Corpus ficticio para pruebas.',
  citationTemplate: '{repository}, {hierarchy}, {reference}, {title}, {date}, {locator}',
  createdAt: CREATED_AT,
  updatedAt: CREATED_AT,
};

export const PRIMARY_SOURCES_REFERENCE_UNITS: ArchiveDescriptionUnit[] = [
  {
    unitId: 'ps-demo-fonds',
    repositoryId: 'ps-demo-repository',
    parentUnitId: null,
    level: 'fonds',
    referenceCode: 'AMPC/FPC',
    title: 'Fondo Familia del Puerto',
    titleType: 'formal',
    date: { display: '1878–1912', startSort: '1878', endSort: '1912', certainty: 'between' },
    creatorDisplay: 'Familia del Puerto',
    extentDisplay: '2 cajas',
    scopeContent: 'Correspondencia, actas, fotografías y registros.',
    arrangement: 'Dos series conservadas según el orden original.',
    administrativeBiographicalHistory: null,
    custodialHistory: 'Depositado en el archivo municipal en 1975.',
    acquisitionInfo: null,
    accessConditions: 'Consulta abierta salvo piezas señaladas.',
    reproductionConditions: null,
    languageCodes: ['es'],
    scriptCodes: ['Latn'],
    physicalCharacteristics: null,
    findingAids: null,
    relatedUnits: null,
    sourceCatalogUrl: null,
    position: 0,
    metadata: {},
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
  {
    unitId: 'ps-demo-series-correspondence',
    repositoryId: 'ps-demo-repository',
    parentUnitId: 'ps-demo-fonds',
    level: 'series',
    referenceCode: 'AMPC/FPC/1',
    title: 'Correspondencia',
    titleType: 'formal',
    date: { display: '1878–1901', startSort: '1878', endSort: '1901', certainty: 'between' },
    creatorDisplay: 'Familia del Puerto',
    extentDisplay: '1 caja',
    scopeContent: null,
    arrangement: null,
    administrativeBiographicalHistory: null,
    custodialHistory: null,
    acquisitionInfo: null,
    accessConditions: null,
    reproductionConditions: null,
    languageCodes: ['es'],
    scriptCodes: ['Latn'],
    physicalCharacteristics: null,
    findingAids: null,
    relatedUnits: null,
    sourceCatalogUrl: null,
    position: 0,
    metadata: {},
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
  {
    unitId: 'ps-demo-letter',
    repositoryId: 'ps-demo-repository',
    parentUnitId: 'ps-demo-series-correspondence',
    level: 'item',
    referenceCode: 'AMPC/FPC/1/3',
    title: 'Carta de María López a Juan García',
    titleType: 'supplied',
    date: { display: 'hacia mayo de 1892', startSort: '1892-05-01', endSort: '1892-05-31', certainty: 'circa' },
    creatorDisplay: 'María López',
    extentDisplay: '2 folios',
    scopeContent: 'Carta relativa a una epidemia y al traslado de suministros.',
    arrangement: null,
    administrativeBiographicalHistory: null,
    custodialHistory: null,
    acquisitionInfo: null,
    accessConditions: 'Abierta.',
    reproductionConditions: 'Citar la signatura completa.',
    languageCodes: ['es'],
    scriptCodes: ['Latn'],
    physicalCharacteristics: 'Tinta ferrogálica; pérdida menor en margen.',
    findingAids: null,
    relatedUnits: null,
    sourceCatalogUrl: null,
    position: 0,
    metadata: { documentType: 'letter' },
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
];

export const PRIMARY_SOURCES_REFERENCE_PROFILE: PrimarySourceItemProfile = {
  itemId: 'ps-demo-item-letter',
  provenancePlaceId: 'ps-demo-place-carmona',
  dateCertainty: 'circa',
  accessStatus: 'open',
  embargoUntil: null,
  rightsStatement: 'Corpus ficticio, libre para pruebas.',
  reproductionConditions: 'Citar la signatura completa.',
  sensitivity: 'normal',
  processingStatus: 'ready',
  descriptionStatus: 'citation_ready',
  analysisStatus: 'draft',
  citationStatus: 'ready',
  captureSessionId: 'ps-demo-session',
  metadata: {},
  createdAt: CREATED_AT,
  updatedAt: CREATED_AT,
};

export const PRIMARY_SOURCES_REFERENCE_FILES: ArchiveItemFile[] = [
  {
    fileId: 'ps-demo-file-master',
    itemId: 'ps-demo-item-letter',
    parentFileId: null,
    role: 'master',
    versionNo: 1,
    sequenceNo: 0,
    pageLabel: 'fol. 1r',
    originalFileName: 'AMPC_FPC_1_3_001.tif',
    mimeType: 'image/tiff',
    byteSize: 42_000_000,
    hasContent: true,
    externalPath: null,
    contentHash: 'bfe61a9f2f15e1c9d2f9bda3b934a01e4f71edcbf3a4d75b86dd963f5d82ff79',
    hashAlgorithm: 'sha256',
    transformation: null,
    captureMetadata: { resolutionDpi: 600, device: 'demo-camera' },
    createdBy: 'demo',
    createdAt: CREATED_AT,
    verifiedAt: CREATED_AT,
    verificationStatus: 'verified',
    supersededAt: null,
  },
  {
    fileId: 'ps-demo-file-access',
    itemId: 'ps-demo-item-letter',
    parentFileId: 'ps-demo-file-master',
    role: 'derivative',
    versionNo: 1,
    sequenceNo: 0,
    pageLabel: 'fol. 1r',
    originalFileName: 'AMPC_FPC_1_3_001-access.jpg',
    mimeType: 'image/jpeg',
    byteSize: 1_200_000,
    hasContent: true,
    externalPath: null,
    contentHash: '3e2ac5c77d76bf73efee3ee6061d5ce27b20e6e104eca27ee634172ff49a316f',
    hashAlgorithm: 'sha256',
    transformation: { operation: 'access_copy', maxEdge: 2400, quality: 88 },
    captureMetadata: null,
    createdBy: 'demo',
    createdAt: CREATED_AT,
    verifiedAt: CREATED_AT,
    verificationStatus: 'verified',
    supersededAt: null,
  },
];

export const PRIMARY_SOURCES_REFERENCE_TEXT: ArchiveTextVersion = {
  textVersionId: 'ps-demo-text-diplomatic',
  itemId: 'ps-demo-item-letter',
  fileId: 'ps-demo-file-master',
  parentVersionId: null,
  kind: 'diplomatic',
  languageCode: 'es',
  content: 'Mi estimado Juan: el cólera ha llegado al puerto […]',
  status: 'reviewed',
  engine: null,
  model: null,
  confidence: null,
  editorialConventions: '[…] indica una laguna material.',
  createdBy: 'demo',
  createdAt: CREATED_AT,
  updatedAt: CREATED_AT,
  reviewedAt: CREATED_AT,
};

export const PRIMARY_SOURCES_REFERENCE_EXCERPT: ArchiveExcerpt = {
  excerptId: 'ps-demo-excerpt-1',
  itemId: 'ps-demo-item-letter',
  fileId: 'ps-demo-file-master',
  textVersionId: 'ps-demo-text-diplomatic',
  segmentId: 'ps-demo-segment-folio-1r',
  locatorDisplay: 'fol. 1r, líneas 3–4',
  locator: {
    folio: '1',
    side: 'recto',
    segmentId: 'ps-demo-segment-folio-1r',
    textRange: { start: 22, end: 49 },
    region: { x: 0.12, y: 0.28, width: 0.72, height: 0.11, canvasId: 'folio-1r' },
  },
  quotedText: 'el cólera ha llegado al puerto',
  languageCode: 'es',
  description: 'Mención explícita de la epidemia.',
  reviewStatus: 'reviewed',
  createdBy: 'demo',
  createdAt: CREATED_AT,
  updatedAt: CREATED_AT,
};

export const PRIMARY_SOURCES_REFERENCE_PROPOSAL: PrimarySourceEntityProposal = {
  proposalId: 'ps-demo-proposal-person',
  itemId: 'ps-demo-item-letter',
  excerptId: 'ps-demo-excerpt-1',
  proposalKind: 'person',
  payload: { originalLabel: 'Juan García', suggestedPreferredName: 'Juan García' },
  matchedTargetId: null,
  status: 'pending',
  confidence: 0.78,
  rationale: 'Destinatario nombrado en el saludo.',
  sourceEngine: 'fixture',
  sourceModel: 'none',
  fingerprint: 'fixture:ps-demo-excerpt-1:person:juan-garcia',
  createdAt: CREATED_AT,
  reviewedAt: null,
  reviewedBy: null,
  decisionNote: null,
};

export const PRIMARY_SOURCES_REFERENCE_PERSON_MENTION: PrimarySourcePersonMention = {
  mentionId: 'ps-demo-person-mention',
  itemId: 'ps-demo-item-letter',
  excerptId: 'ps-demo-excerpt-1',
  personId: null,
  originalLabel: 'Juan García',
  role: 'recipient',
  certainty: 1,
  identityStatus: 'unresolved_mention',
  createdAt: CREATED_AT,
  updatedAt: CREATED_AT,
};

export const PRIMARY_SOURCES_REFERENCE_PLACE_MENTION: PrimarySourcePlaceMention = {
  mentionId: 'ps-demo-place-mention',
  itemId: 'ps-demo-item-letter',
  excerptId: 'ps-demo-excerpt-1',
  placeId: null,
  originalLabel: 'el puerto',
  role: 'mentioned',
  certainty: 0.5,
  status: 'unresolved',
  createdAt: CREATED_AT,
  updatedAt: CREATED_AT,
};

export const PRIMARY_SOURCES_REFERENCE_NOTE_LINK: PrimarySourceNoteLink = {
  linkId: 'ps-demo-note-link',
  nodusId: 'ps-demo-note',
  targetKind: 'archive_excerpt',
  targetId: 'ps-demo-excerpt-1',
  excerptId: 'ps-demo-excerpt-1',
  relationKind: 'interprets',
  createdAt: CREATED_AT,
};

export const PRIMARY_SOURCES_MIGRATION_CASES = [
  'empty_vault',
  'archive_images',
  'archive_pdf_with_text',
  'genealogy_archive_links',
  'large_blob',
  'missing_file',
  'null_hash',
  'unknown_metadata_json',
  'non_latin_text',
  'previous_schema',
] as const;

export const PRIMARY_SOURCES_NO_LOSS_CRITERIA = [
  'row_counts',
  'identifiers',
  'blob_bytes',
  'content_hashes',
  'legacy_text',
  'folder_memberships',
  'tags',
  'person_links',
  'unknown_metadata',
  'rollback',
  'reopen',
  'pre_migration_backup',
] as const;
