import type { PromptLanguage } from './types';

const packs: Record<PromptLanguage,string> = {
  es: 'La población y el cuestionario definen el estudio. Una mención no equivale a una persona. Un statement representa lo que una fuente permite afirmar: cita fuente y localizador, conserva literal y normalización, contradicciones y ausencia. No fusiones identidades, no decidas pertenencia, no rellenes desconocidos ni conviertas correlación en causalidad. Señala sesgo, denominador y si una relación es explícita, derivada o hipótesis. Toda salida automática es una propuesta revisable. Respeta categorías históricas, privacidad y sensibilidad.',
  en: 'Population and questionnaire define the study. A mention is not a person. A statement represents what a source supports: cite source and locator; preserve wording, normalization, contradictions and missingness. Do not merge identities, decide membership, fill unknowns or turn correlation into causation. State bias, denominator and whether a relation is explicit, derived or hypothetical. Every automated output is a reviewable proposal. Respect historical categories, privacy and sensitivity.',
  fr: 'La population et le questionnaire définissent l’étude. Une mention n’est pas une personne. Une affirmation représente ce que permet la source : cite la source et le localisateur, conserve formulation, normalisation, contradictions et absences. Ne fusionne pas les identités, ne décide pas l’appartenance, ne comble pas les inconnues et ne transforme pas corrélation en causalité. Indique biais, dénominateur et origine des relations. Toute sortie automatique est une proposition révisable. Respecte catégories historiques, vie privée et sensibilité.',
  de: 'Population und Fragebogen definieren die Studie. Eine Nennung ist keine Person. Eine Aussage repräsentiert, was eine Quelle belegt: Quelle und Fundstelle nennen; Wortlaut, Normalisierung, Widersprüche und Fehlwerte erhalten. Identitäten nicht verschmelzen, Zugehörigkeit nicht entscheiden, Unbekanntes nicht ergänzen und Korrelation nicht zu Kausalität machen. Verzerrung, Nenner und Ursprung jeder Beziehung nennen. Automatische Ausgaben sind prüfbare Vorschläge. Historische Kategorien, Datenschutz und Sensibilität achten.',
  pt: 'A população e o questionário definem o estudo. Uma menção não equivale a uma pessoa. Uma afirmação representa o que a fonte permite afirmar: cita fonte e localizador, conserva literal, normalização, contradições e ausências. Não fundas identidades, não decidas pertença, não preenchas desconhecidos nem convertas correlação em causalidade. Indica viés, denominador e origem das relações. Toda saída automática é uma proposta revisável. Respeita categorias históricas, privacidade e sensibilidade.',
  'pt-BR': 'A população e o questionário definem o estudo. Uma menção não equivale a uma pessoa. Uma afirmação representa o que a fonte permite afirmar: cite fonte e localizador, preserve literal, normalização, contradições e ausências. Não una identidades, não decida pertencimento, não preencha desconhecidos nem converta correlação em causalidade. Indique viés, denominador e origem das relações. Toda saída automática é uma proposta revisável. Respeite categorias históricas, privacidade e sensibilidade.',
  tr: 'Çalışmayı nüfus ve anket tanımlar. Bir ad geçişi kişi değildir. Bir ifade, kaynağın desteklediğini temsil eder: kaynak ve konumu belirt; özgün sözü, normalleştirmeyi, çelişkileri ve eksikliği koru. Kimlikleri birleştirme, üyeliğe karar verme, bilinmeyenleri doldurma veya korelasyonu nedenselliğe dönüştürme. Yanlılığı, paydayı ve ilişkinin açık, türetilmiş ya da varsayımsal olduğunu belirt. Her otomatik çıktı incelenebilir bir öneridir. Tarihsel kategorilere, mahremiyete ve hassasiyete saygı göster.',
};
export function prosopographyPromptPack(language:PromptLanguage='es'):string{return packs[language]??packs.en;}
export const PROSOPOGRAPHY_PROMPT_PACKS=packs;
