import type { PromptLanguage } from './types';

const packs: Record<PromptLanguage,string> = {
  es: 'La población y el cuestionario definen el estudio. Una mención no equivale a una persona. Un statement representa lo que una fuente permite afirmar: cita fuente y localizador, conserva literal y normalización, contradicciones y ausencia. No fusiones identidades, no decidas pertenencia, no rellenes desconocidos ni conviertas correlación en causalidad. Señala sesgo, denominador y si una relación es explícita, derivada o hipótesis. Toda salida automática es una propuesta revisable. Respeta categorías históricas, privacidad y sensibilidad.',
  en: 'Population and questionnaire define the study. A mention is not a person. A statement represents what a source supports: cite source and locator; preserve wording, normalization, contradictions and missingness. Do not merge identities, decide membership, fill unknowns or turn correlation into causation. State bias, denominator and whether a relation is explicit, derived or hypothetical. Every automated output is a reviewable proposal. Respect historical categories, privacy and sensitivity.',
  fr: 'La population et le questionnaire définissent l’étude. Une mention n’est pas une personne. Une affirmation représente ce que permet la source : cite la source et le localisateur, conserve formulation, normalisation, contradictions et absences. Ne fusionne pas les identités, ne décide pas l’appartenance, ne comble pas les inconnues et ne transforme pas corrélation en causalité. Indique biais, dénominateur et origine des relations. Toute sortie automatique est une proposition révisable. Respecte catégories historiques, vie privée et sensibilité.',
  de: 'Population und Fragebogen definieren die Studie. Eine Nennung ist keine Person. Eine Aussage repräsentiert, was eine Quelle belegt: Quelle und Fundstelle nennen; Wortlaut, Normalisierung, Widersprüche und Fehlwerte erhalten. Identitäten nicht verschmelzen, Zugehörigkeit nicht entscheiden, Unbekanntes nicht ergänzen und Korrelation nicht zu Kausalität machen. Verzerrung, Nenner und Ursprung jeder Beziehung nennen. Automatische Ausgaben sind prüfbare Vorschläge. Historische Kategorien, Datenschutz und Sensibilität achten.',
  pt: 'A população e o questionário definem o estudo. Uma menção não equivale a uma pessoa. Uma afirmação representa o que a fonte permite afirmar: cita fonte e localizador, conserva literal, normalização, contradições e ausências. Não fundas identidades, não decidas pertença, não preenchas desconhecidos nem convertas correlação em causalidade. Indica viés, denominador e origem das relações. Toda saída automática é uma proposta revisável. Respeita categorias históricas, privacidade e sensibilidade.',
  'pt-BR': 'A população e o questionário definem o estudo. Uma menção não equivale a uma pessoa. Uma afirmação representa o que a fonte permite afirmar: cite fonte e localizador, preserve literal, normalização, contradições e ausências. Não una identidades, não decida pertencimento, não preencha desconhecidos nem converta correlação em causalidade. Indique viés, denominador e origem das relações. Toda saída automática é uma proposta revisável. Respeite categorias históricas, privacidade e sensibilidade.',
  it: 'La popolazione e il questionario definiscono lo studio. Una menzione non equivale a una persona. Un’affermazione rappresenta ciò che la fonte consente di sostenere: cita la fonte e il localizzatore; conserva il testo letterale, la normalizzazione, le contraddizioni e le assenze. Non fondere identità, non decidere l’appartenenza, non colmare gli elementi ignoti e non trasformare la correlazione in causalità. Indica distorsioni, denominatore e se una relazione è esplicita, derivata o ipotetica. Ogni risultato automatico è una proposta rivedibile. Rispetta le categorie storiche, la riservatezza e la sensibilità.',
  tr: 'Çalışmayı nüfus ve anket tanımlar. Bir ad geçişi kişi değildir. Bir ifade, kaynağın desteklediğini temsil eder: kaynak ve konumu belirt; özgün sözü, normalleştirmeyi, çelişkileri ve eksikliği koru. Kimlikleri birleştirme, üyeliğe karar verme, bilinmeyenleri doldurma veya korelasyonu nedenselliğe dönüştürme. Yanlılığı, paydayı ve ilişkinin açık, türetilmiş ya da varsayımsal olduğunu belirt. Her otomatik çıktı incelenebilir bir öneridir. Tarihsel kategorilere, mahremiyete ve hassasiyete saygı göster.',
  'zh-Hans': '人口与问卷界定研究。一次提及不等于一个人物。一条陈述代表来源所能支持的内容：引用来源与定位符，保留原文、规范化、矛盾与缺失。不要合并身份、裁定归属、填补未知或将相关关系变为因果关系。说明偏差、分母以及关系是明确、推导还是假设。所有自动输出均为可复核的提议。尊重历史类别、隐私与敏感性。',
  'zh-Hant': '人口與問卷界定研究。一次提及不等於一個人物。一則陳述代表來源所能支持者：引用來源與定位符，保留原文、正規化、矛盾與缺失。不要合併身分、裁定歸屬、填補未知或將相關關係變成因果關係。說明偏差、分母以及關係是明確、推導還是假設。所有自動輸出均為可複核的提案。尊重歷史類別、隱私與敏感性。',
  vi: 'Dân số và bảng hỏi định nghĩa nghiên cứu. Một lần xuất hiện không đồng nghĩa với một con người. Một phát biểu thể hiện điều mà nguồn tư liệu có thể chống đỡ: trích dẫn nguồn và vị trí định vị, giữ nguyên văn, chuẩn hóa, mâu thuẫn và dữ liệu thiếu. Không hợp nhất danh tính, không quyết định tư cách thành viên, không lấp đầy dữ liệu chưa biết hay biến tương quan thành nhân quả. Nêu rõ thiên lệch, mẫu số và liệu một quan hệ là hiển ngôn, suy diễn hay giả thuyết. Mọi kết quả tự động đều là đề xuất có thể xem xét lại. Tôn trọng các phạm trù lịch sử, quyền riêng tư và tính nhạy cảm.',
  ja: '人口と質問票が研究を定義します。一度の言及は一人の人物ではありません。一つの記述は資料が支持できる内容を表します。出典と所在情報を引用し、原文、正規化、矛盾、欠測を保持してください。身元を統合したり、所属を判断したり、不明な点を補ったり、相関を因果に変えたりしないでください。偏り、分母、および関係が明示的・導出的・仮説的のいずれであるかを示してください。自動出力はすべて再検討可能な提案です。歴史的な区分、プライバシー、機微性を尊重してください。',
  ru: 'Население и вопросник определяют исследование. Упоминание — это не человек. Утверждение отражает то, что позволяет источник: указывайте источник и локатор, сохраняйте формулировку, нормализацию, противоречия и пропуски. Не объединяйте личности, не решайте вопрос о принадлежности, не заполняйте неизвестное и не превращайте корреляцию в причинность. Указывайте смещение, знаменатель и то, является ли связь явной, производной или гипотетической. Любой автоматический результат — это предложение, доступное проверке. Уважайте исторические категории, приватность и чувствительность.',
  uk: 'Населення та опитувальник визначають дослідження. Згадка — це не особа. Твердження відображає те, що дозволяє джерело: зазначайте джерело й локатор, зберігайте формулювання, нормалізацію, суперечності та пропуски. Не об’єднуйте особи, не вирішуйте питання належності, не заповнюйте невідоме й не перетворюйте кореляцію на причинність. Зазначайте упередження, знаменник і те, чи є зв’язок явним, похідним або гіпотетичним. Будь-який автоматичний результат — це пропозиція, що підлягає перегляду. Поважайте історичні категорії, приватність і чутливість.',
  ko: '인구와 질문지가 연구를 정의합니다. 한 번의 언급은 한 사람이 아닙니다. 하나의 진술은 자료가 뒷받침할 수 있는 내용을 나타냅니다. 출처와 위치 표시를 인용하고, 원문, 정규화, 모순, 결측을 보존하십시오. 신원을 병합하거나 소속을 판정하거나 알 수 없는 값을 채우거나 상관관계를 인과관계로 바꾸지 마십시오. 편향, 분모, 그리고 관계가 명시적인지 도출된 것인지 가설적인지를 밝히십시오. 모든 자동 출력은 검토 가능한 제안입니다. 역사적 범주, 프라이버시, 민감성을 존중하십시오.',
};
export function prosopographyPromptPack(language:PromptLanguage='es'):string{return packs[language]??packs.en;}
export const PROSOPOGRAPHY_PROMPT_PACKS=packs;
