// SPDX-FileCopyrightText: 2026 Jorge Pérez Burgueño and Nodus contributors
// SPDX-License-Identifier: AGPL-3.0-only

import type { ReleaseHighlight } from './releaseNotes';

// Keep scope groups in display order: descending size, stable ties.
// Describe shipped behavior directly in every interface language.
export const RELEASE_5_7_2_HIGHLIGHTS: ReleaseHighlight[] = [
  {
    category: 'new',
    "scope": "academic",
    "es": "El Chat de investigación ahora planifica cada turno. Reescribe tu pregunta como un objetivo que se entiende por sí solo, mantiene el tema de la conversación, busca en el catálogo de la biblioteca los autores y títulos que mencionas, con los acentos unificados y un error de escritura tolerado, y lee varias fuentes antes de responder. Si la respuesta se apoya en menos de tres fuentes independientes y todavía quedan candidatas por leer, la rechaza y te dice cuáles son.",
    "en": "Research Chat now plans each turn. It rewrites your question as a goal that stands on its own, keeps the topic of the conversation, looks up the authors and titles you mention in the library catalogue with accents folded and one typo tolerated, and reads several sources before answering. If an answer rests on fewer than three independent sources while candidates remain unread, it rejects the answer and names those candidates.",
    "fr": "Le Chat de recherche planifie désormais chaque tour. Il reformule votre question en un objectif qui se comprend seul, conserve le sujet de la conversation, recherche dans le catalogue de la bibliothèque les auteurs et les titres que vous mentionnez, avec les accents unifiés et une faute de frappe tolérée, et lit plusieurs sources avant de répondre. Si une réponse s'appuie sur moins de trois sources indépendantes alors que des candidates restent non lues, il la refuse et nomme ces candidates.",
    "de": "Der Forschungschat plant jetzt jede Runde. Er formuliert deine Frage zu einem Ziel um, das für sich steht, behält das Thema des Gesprächs, sucht die Autoren und Titel, die du nennst, im Katalog der Bibliothek, mit vereinheitlichten Akzenten und einem tolerierten Tippfehler, und liest mehrere Quellen vor der Antwort. Stützt sich eine Antwort auf weniger als drei unabhängige Quellen, während Kandidaten ungelesen bleiben, weist er sie zurück und nennt diese Kandidaten.",
    "pt": "O Chat de investigação passa a planear cada turno. Reescreve a tua pergunta como um objetivo que se entende por si só, mantém o tema da conversa, procura no catálogo da biblioteca os autores e títulos que mencionas, com os acentos unificados e um erro de escrita tolerado, e lê várias fontes antes de responder. Se uma resposta se apoiar em menos de três fontes independentes e ainda houver candidatas por ler, rejeita-a e diz quais são.",
    "pt-BR": "O Chat de pesquisa agora planeja cada turno. Ele reescreve sua pergunta como um objetivo que se entende por si só, mantém o tema da conversa, procura no catálogo da biblioteca os autores e títulos que você menciona, com acentos unificados e um erro de digitação tolerado, e lê várias fontes antes de responder. Se uma resposta se apoiar em menos de três fontes independentes enquanto ainda há candidatas não lidas, ele a recusa e diz quais são.",
    "it": "La Chat di ricerca ora pianifica ogni turno. Riscrive la tua domanda come un obiettivo che si capisce da solo, mantiene l'argomento della conversazione, cerca nel catalogo della biblioteca gli autori e i titoli che indichi, con gli accenti uniformati e un errore di battitura tollerato, e legge più fonti prima di rispondere. Se una risposta si basa su meno di tre fonti indipendenti mentre restano candidate non lette, la rifiuta e ne indica i nomi.",
    "tr": "Araştırma Sohbeti artık her turu planlıyor. Sorunuzu kendi başına anlaşılan bir hedefe dönüştürüyor, sohbetin konusunu koruyor, belirttiğiniz yazar ve başlıkları kütüphane kataloğunda arıyor, aksanları birleştirip tek bir yazım hatasını hoş görüyor ve yanıtlamadan önce birkaç kaynak okuyor. Bir yanıt üçten az bağımsız kaynağa dayanıyorsa ve okunmamış adaylar varsa yanıtı reddediyor ve bu adayları söylüyor.",
    "zh-CN": "研究聊天现在会规划每一轮。它把你的问题改写成一个能独立理解的目标，保留对话的主题，在资料库目录中查找你提到的作者和标题，统一重音并容忍一个拼写错误，回答前阅读多个来源。如果回答依据的独立来源少于三个而仍有未读的候选，它会拒绝这个回答并列出那些候选。",
    "zh-TW": "研究聊天現在會規劃每一輪。它把你的問題改寫成一個能獨立理解的目標，保留對話的主題，在知識庫目錄中查找你提到的作者和標題，統一重音並容忍一個拼寫錯誤，回答前閱讀多個來源。如果回答依據的獨立來源少於三個而仍有未讀的候選，它會拒絕這個回答並列出那些候選。",
    "ja": "研究チャットは各ターンを計画するようになりました。質問を単独で理解できる目標に書き直し、会話の話題を保ち、指定した著者とタイトルをライブラリのカタログで検索します。アクセントは統一し、一文字の綴り間違いは許容します。回答の前に複数の資料を読みます。独立した資料が三件未満で未読の候補が残っている場合、その回答を退け、候補の名前を示します。",
    "ko": "연구 채팅이 이제 각 턴을 계획합니다. 질문을 그 자체로 이해되는 목표로 다시 쓰고, 대화의 주제를 유지하며, 언급한 저자와 제목을 보관함 카탈로그에서 찾습니다. 악센트는 통일하고 오타 하나는 허용합니다. 답하기 전에 여러 출처를 읽습니다. 독립 출처가 세 개 미만이고 읽지 않은 후보가 남아 있으면 그 답변을 거부하고 후보를 알려 줍니다."
  },
  {
    category: 'enhancement',
    "scope": "academic",
    "es": "Las preguntas de seguimiento conservan el hilo. Las citas anteriores vuelven a la conversación, la respuesta enumera solo las fuentes que han participado, con autor y año, y explica con palabras llanas qué buscó, qué consultó y qué leyó. Ya no dice que una obra indexada no tiene índice ni afirma que Zotero no está disponible.",
    "en": "Follow-up questions keep the thread. Earlier citations come back to the conversation, the answer lists only the sources that took part with their author and year, and it explains in plain words what it searched, looked up and read. It no longer says an indexed work has no index, and it no longer states that Zotero is unavailable.",
    "fr": "Les questions de suivi gardent le fil. Les citations précédentes reviennent dans la conversation, la réponse énumère uniquement les sources qui ont participé, avec leur auteur et leur année, et elle explique en mots simples ce qu'elle a cherché, consulté et lu. Elle ne dit plus qu'une œuvre indexée n'a pas d'index et n'affirme plus que Zotero n'est pas disponible.",
    "de": "Rückfragen behalten den Faden. Frühere Belege kommen ins Gespräch zurück, die Antwort nennt nur die beteiligten Quellen mit Autor und Jahr, und sie erklärt in einfachen Worten, was gesucht, nachgeschlagen und gelesen wurde. Sie behauptet nicht mehr, ein indexiertes Werk habe keinen Index, und nicht mehr, dass Zotero nicht verfügbar sei.",
    "pt": "As perguntas de seguimento mantêm o fio. As citações anteriores voltam à conversa, a resposta enumera apenas as fontes que participaram, com autor e ano, e explica em palavras simples o que procurou, consultou e leu. Já não diz que uma obra indexada não tem índice nem afirma que o Zotero não está disponível.",
    "pt-BR": "As perguntas de acompanhamento mantêm o fio. As citações anteriores voltam à conversa, a resposta lista apenas as fontes que participaram, com autor e ano, e explica em palavras simples o que buscou, consultou e leu. Não diz mais que uma obra indexada não tem índice nem afirma que o Zotero não está disponível.",
    "it": "Le domande di seguito mantengono il filo. Le citazioni precedenti tornano nella conversazione, la risposta elenca solo le fonti che hanno partecipato, con autore e anno, e spiega in parole semplici che cosa ha cercato, consultato e letto. Non dice più che un'opera indicizzata non ha indice e non afferma più che Zotero non è disponibile.",
    "tr": "Devam soruları konuyu sürdürür. Önceki alıntılar sohbete geri döner, yanıt yalnızca katılan kaynakları yazar ve yıl bilgisiyle listeler ve neyi aradığını, neye baktığını ve neyi okuduğunu sade sözlerle açıklar. Artık dizinlenmiş bir eser için dizin yok demez ve Zotero'nun kullanılamadığını söylemez.",
    "zh-CN": "后续提问保留上下文。之前的引用会回到对话中，回答只列出参与其中的来源及其作者和年份，并用直白的话说明搜索、查阅和阅读了什么。它不再把已建立索引的文献说成没有索引，也不再声称 Zotero 不可用。",
    "zh-TW": "後續提問保留上下文。之前的引用會回到對話中，回答只列出參與其中的來源及其作者和年份，並用直白的話說明搜尋、查閱和閱讀了什麼。它不再把已建立索引的文獻說成沒有索引，也不再聲稱 Zotero 無法使用。",
    "ja": "追加の質問は流れを保ちます。以前の引用が会話に戻り、回答は参加した資料だけを著者と年とともに列挙し、何を検索し、何を調べ、何を読んだかを平易な言葉で説明します。索引済みの文献を索引がないと述べることも、Zotero が使えないと述べることもなくなりました。",
    "ko": "이어지는 질문은 맥락을 유지합니다. 이전 인용이 대화로 돌아오고, 답변은 참여한 출처만 저자와 연도와 함께 나열하며, 무엇을 검색하고 확인하고 읽었는지 쉬운 말로 설명합니다. 색인이 있는 문헌을 색인 없다고 말하지 않고, Zotero를 쓸 수 없다고도 말하지 않습니다."
  },
  {
    category: 'fix',
    "scope": "academic",
    "es": "El Chat de investigación responde sin congelar la ventana. En una biblioteca de 1.229 fuentes, el bloqueo más largo de la interfaz bajó de unos cinco segundos a menos de uno. Una pregunta tampoco falla ya cuando una de las ideas guardadas no tiene enunciado.",
    "en": "Research Chat answers without freezing the window. On a library of 1,229 sources the longest block of the interface fell from about five seconds to under one. A question also no longer fails when one of the stored ideas has no statement.",
    "fr": "Le Chat de recherche répond sans figer la fenêtre. Sur une bibliothèque de 1 229 sources, le blocage le plus long de l'interface est passé d'environ cinq secondes à moins d'une seconde. Une question n'échoue plus non plus lorsqu'une des idées enregistrées n'a pas d'énoncé.",
    "de": "Der Forschungschat antwortet, ohne das Fenster einzufrieren. In einer Bibliothek mit 1.229 Quellen sank die längste Blockade der Oberfläche von etwa fünf Sekunden auf unter eine Sekunde. Eine Frage schlägt auch nicht mehr fehl, wenn eine der gespeicherten Ideen keine Aussage hat.",
    "pt": "O Chat de investigação responde sem bloquear a janela. Numa biblioteca de 1 229 fontes, o bloqueio mais longo da interface desceu de cerca de cinco segundos para menos de um. Uma pergunta também já não falha quando uma das ideias guardadas não tem enunciado.",
    "pt-BR": "O Chat de pesquisa responde sem travar a janela. Em uma biblioteca de 1.229 fontes, o bloqueio mais longo da interface caiu de cerca de cinco segundos para menos de um. Uma pergunta também não falha mais quando uma das ideias guardadas não tem enunciado.",
    "it": "La Chat di ricerca risponde senza bloccare la finestra. In una biblioteca di 1.229 fonti, il blocco più lungo dell'interfaccia è sceso da circa cinque secondi a meno di uno. Inoltre una domanda non fallisce più quando una delle idee salvate non ha un enunciato.",
    "tr": "Araştırma Sohbeti pencereyi dondurmadan yanıt verir. 1.229 kaynaklı bir kütüphanede arayüzün en uzun kilitlenmesi yaklaşık beş saniyeden bir saniyenin altına indi. Ayrıca kayıtlı fikirlerden birinin ifadesi yoksa soru artık başarısız olmaz.",
    "zh-CN": "研究聊天回答时不再让窗口卡住。在拥有 1,229 个来源的资料库中，界面最长的阻塞从约五秒降到一秒以内。另外，当某条已保存的观点没有陈述时，提问也不再失败。",
    "zh-TW": "研究聊天回答時不再讓視窗卡住。在擁有 1,229 個來源的知識庫中，介面最長的阻塞從約五秒降到一秒以內。另外，當某條已儲存的觀點沒有陳述時，提問也不再失敗。",
    "ja": "研究チャットはウィンドウを固まらせずに回答します。1,229 件の資料があるライブラリで、インターフェースの最長の停止は約五秒から一秒未満に短くなりました。また、保存されたアイデアに文がない場合でも質問が失敗しなくなりました。",
    "ko": "연구 채팅은 창을 멈추지 않고 답합니다. 1,229개 출처가 있는 보관함에서 인터페이스가 가장 오래 멈춘 시간이 약 5초에서 1초 미만으로 줄었습니다. 또한 저장된 아이디어에 진술이 없어도 질문이 실패하지 않습니다."
  },
  {
    category: 'enhancement',
    "scope": "academic",
    "es": "La preparación de documentos es más rápida y ocupa menos. Se preparan dos documentos a la vez, cada documento mantiene hasta cuatro lotes de vectores en curso, los vectores remotos se piden en paralelo, la fuente se comprueba como mucho cada cinco segundos en lugar de en cada página y los vectores se guardan una sola vez en un formato compacto. El almacén se compacta en segundo plano y la búsqueda semántica es más rápida.",
    "en": "Preparing documents is faster and takes less space. Two documents are prepared at the same time, each document keeps up to four batches of vectors in flight, remote embeddings are requested in parallel, the source is checked at most every five seconds instead of on every page, and vectors are stored once in a compact format. The store is compacted in the background and semantic search is faster.",
    "fr": "La préparation des documents est plus rapide et occupe moins d'espace. Deux documents sont préparés en même temps, chaque document garde jusqu'à quatre lots de vecteurs en cours, les vecteurs distants sont demandés en parallèle, la source est vérifiée au plus toutes les cinq secondes au lieu de chaque page, et les vecteurs sont stockés une seule fois dans un format compact. Le dépôt est compacté en arrière-plan et la recherche sémantique est plus rapide.",
    "de": "Das Vorbereiten von Dokumenten ist schneller und braucht weniger Platz. Zwei Dokumente werden gleichzeitig vorbereitet, je Dokument sind bis zu vier Stapel von Vektoren unterwegs, entfernte Vektoren werden parallel angefragt, die Quelle wird höchstens alle fünf Sekunden geprüft statt auf jeder Seite, und Vektoren werden einmal in einem kompakten Format gespeichert. Der Speicher wird im Hintergrund komprimiert und die semantische Suche ist schneller.",
    "pt": "A preparação de documentos é mais rápida e ocupa menos. Preparam-se dois documentos ao mesmo tempo, cada documento mantém até quatro lotes de vetores em curso, os vetores remotos são pedidos em paralelo, a fonte é verificada no máximo a cada cinco segundos em vez de em cada página e os vetores são guardados uma só vez num formato compacto. O armazém é compactado em segundo plano e a pesquisa semântica é mais rápida.",
    "pt-BR": "A preparação de documentos é mais rápida e ocupa menos. Dois documentos são preparados ao mesmo tempo, cada documento mantém até quatro lotes de vetores em andamento, os vetores remotos são solicitados em paralelo, a fonte é verificada no máximo a cada cinco segundos em vez de em cada página, e os vetores são guardados uma só vez em um formato compacto. O armazenamento é compactado em segundo plano e a busca semântica é mais rápida.",
    "it": "La preparazione dei documenti è più rapida e occupa meno spazio. Due documenti vengono preparati insieme, ogni documento tiene fino a quattro lotti di vettori in corso, i vettori remoti vengono richiesti in parallelo, la fonte viene controllata al massimo ogni cinque secondi invece che a ogni pagina e i vettori vengono salvati una sola volta in un formato compatto. L'archivio viene compattato in background e la ricerca semantica è più rapida.",
    "tr": "Belgelerin hazırlanması daha hızlı ve daha az yer kaplıyor. Aynı anda iki belge hazırlanıyor, her belge en fazla dört vektör grubunu uçuşta tutuyor, uzak vektörler paralel isteniyor, kaynak her sayfada değil en fazla beş saniyede bir denetleniyor ve vektörler tek seferde sıkışık bir biçimde saklanıyor. Depo arka planda sıkıştırılıyor ve anlamsal arama daha hızlı.",
    "zh-CN": "准备文档更快，占用也更少。两个文档同时准备，每个文档最多有四个向量批次在处理，远程向量并行请求，来源最多每五秒核对一次而不是每页核对，向量只以紧凑格式保存一次。存储在后台完成压缩，语义检索也更快。",
    "zh-TW": "準備文件更快，佔用也更少。兩個文件同時準備，每個文件最多有四個向量批次在處理，遠端向量並行請求，來源最多每五秒核對一次而不是每頁核對，向量只以緊湊格式儲存一次。儲存體在背景完成壓縮，語意檢索也更快。",
    "ja": "文書の準備は速くなり、使用する容量も減りました。二つの文書を同時に準備し、各文書は最大四つのベクトル処理を同時に進め、遠隔のベクトルは並行して要求します。出典の確認は各ページごとではなく最大五秒ごとになり、ベクトルは一度だけ小さな形式で保存します。保存領域は背景で整理され、意味検索も速くなりました。",
    "ko": "문서 준비가 더 빠르고 공간도 덜 씁니다. 문서 두 개를 동시에 준비하고, 문서마다 최대 네 개의 벡터 묶음을 동시에 처리하며, 원격 벡터는 병렬로 요청합니다. 출처 확인은 페이지마다가 아니라 최대 5초에 한 번 하고, 벡터는 한 번만 압축된 형식으로 저장합니다. 저장소는 백그라운드에서 정리되고 의미 검색도 더 빠릅니다."
  },
  {
    category: 'fix',
    "scope": "academic",
    "es": "Solo los escaneos reales esperan al OCR. Un libro digital ya no se manda a OCR porque tenga una sola página de imagen, y la vista previa de la preparación y la preparación usan ahora la misma regla.",
    "en": "Only real scans wait for OCR. A digital book is no longer sent to OCR because it has a single image-only page, and the preparation preview and the preparation itself now use the same rule.",
    "fr": "Seuls les vrais scans attendent l'OCR. Un livre numérique n'est plus envoyé à l'OCR parce qu'une seule de ses pages est une image, et l'aperçu de la préparation et la préparation elle-même appliquent désormais la même règle.",
    "de": "Nur echte Scans warten auf OCR. Ein digitales Buch wird nicht mehr wegen einer einzigen Bildseite an OCR geschickt, und die Vorschau der Vorbereitung und die Vorbereitung selbst folgen jetzt derselben Regel.",
    "pt": "Só os escaneamentos reais esperam pelo OCR. Um livro digital já não é enviado para OCR por ter uma única página de imagem, e a pré-visualização da preparação e a própria preparação usam agora a mesma regra.",
    "pt-BR": "Só os escaneamentos reais esperam pelo OCR. Um livro digital não é mais enviado ao OCR por ter uma única página de imagem, e a prévia da preparação e a própria preparação agora usam a mesma regra.",
    "it": "Solo le vere scansioni attendono l'OCR. Un libro digitale non viene più mandato all'OCR perché ha una sola pagina di immagine, e l'anteprima della preparazione e la preparazione stessa ora usano la stessa regola.",
    "tr": "Yalnızca gerçek taramalar OCR bekler. Dijital bir kitap tek bir görüntü sayfası olduğu için artık OCR'a gönderilmez ve hazırlık önizlemesi ile hazırlığın kendisi artık aynı kuralı kullanır.",
    "zh-CN": "只有真正的扫描件才等待 OCR。数字图书不再因为只有一页是图像就被送去 OCR，准备预览和准备本身现在使用同一套规则。",
    "zh-TW": "只有真正的掃描件才等待 OCR。數位圖書不再因為只有一頁是圖像就被送去 OCR，準備預覽和準備本身現在使用同一套規則。",
    "ja": "OCR を待つのは本当のスキャンだけになりました。デジタル書籍は、画像だけのページが一つあるという理由で OCR に送られなくなります。準備のプレビューと準備そのものが同じ規則を使うようになりました。",
    "ko": "실제 스캔만 OCR를 기다립니다. 디지털 도서는 이미지 페이지만 한 장 있다는 이유로 OCR로 보내지지 않으며, 준비 미리보기와 준비 자체가 이제 같은 규칙을 씁니다."
  },
  {
    category: 'enhancement',
    "scope": "academic",
    "es": "La salud del grafo, en Ajustes, Datos, detecta también las relaciones de una idea consigo misma y las repara.",
    "en": "Graph health in Settings, Data now also detects relations from an idea to itself and repairs them.",
    "fr": "La santé du graphe, dans Paramètres, Données, détecte aussi les relations d'une idée avec elle-même et les répare.",
    "de": "Die Graph-Gesundheit unter Einstellungen, Daten erkennt jetzt auch Beziehungen einer Idee zu sich selbst und repariert sie.",
    "pt": "A saúde do grafo, em Definições, Dados, deteta também as relações de uma ideia consigo mesma e repara-as.",
    "pt-BR": "A saúde do grafo, em Configurações, Dados, agora também detecta as relações de uma ideia consigo mesma e as repara.",
    "it": "La salute del grafo, in Impostazioni, Dati, ora rileva anche le relazioni di un'idea con se stessa e le ripara.",
    "tr": "Ayarlar, Veriler bölümündeki grafik sağlığı artık bir fikrin kendisiyle olan ilişkilerini de bulur ve onarır.",
    "zh-CN": "设置的数据部分中的图谱健康状况现在也会检测观点与自身之间的关系并修复它们。",
    "zh-TW": "設定的資料部分中的圖譜健康狀況現在也會偵測觀點與自身之間的關聯並修復它們。",
    "ja": "設定のデータにあるグラフの健全性が、アイデアが自分自身を指す関連も検出して修復するようになりました。",
    "ko": "설정의 데이터에 있는 그래프 상태가 이제 아이디어가 자기 자신을 가리키는 관계도 찾아 복구합니다."
  },
  {
    category: 'fix',
    "scope": "library",
    "es": "Una cita se apoya ahora en el pasaje que contiene el texto citado, dentro de su propia fuente y lo más cerca posible de su página. Los apoyos publicados antes se recolocan una vez por bóveda.",
    "en": "A citation now rests on the passage that holds the quoted text, inside its own source and as close as possible to its page. Supports published earlier are re-pointed once per vault.",
    "fr": "Une citation s'appuie désormais sur le passage qui contient le texte cité, dans sa propre source et au plus près de sa page. Les appuis publiés auparavant sont repositionnés une fois par coffre.",
    "de": "Ein Beleg stützt sich jetzt auf die Passage, die den zitierten Text enthält, innerhalb ihrer eigenen Quelle und möglichst nah an ihrer Seite. Früher veröffentlichte Stützen werden einmal pro Tresor neu zugeordnet.",
    "pt": "Uma citação apoia-se agora na passagem que contém o texto citado, dentro da sua própria fonte e o mais perto possível da sua página. Os apoios publicados antes são recolocados uma vez por cofre.",
    "pt-BR": "Uma citação agora se apoia no trecho que contém o texto citado, dentro da própria fonte e o mais perto possível de sua página. Os apoios publicados antes são reposicionados uma vez por cofre.",
    "it": "Una citazione ora si basa sul passaggio che contiene il testo citato, dentro la sua stessa fonte e il più vicino possibile alla sua pagina. Gli appoggi pubblicati prima vengono riposizionati una volta per vault.",
    "tr": "Bir alıntı artık alıntılanan metni içeren bölüme dayanır, kendi kaynağı içinde ve sayfasına olabildiğince yakın. Daha önce yayımlanmış dayanaklar kasa başına bir kez yeniden konumlandırılır.",
    "zh-CN": "引用现在依据包含该引文的片段，取自引文自己的来源，并尽可能靠近其页码。此前已发布的依据会按资料库重新定位一次。",
    "zh-TW": "引用現在依據包含該引文的片段，取自引文自己的來源，並盡可能靠近其頁碼。此前已發布的依據會按知識庫重新定位一次。",
    "ja": "引用は、引用された文を含む抜粋に基づくようになりました。引用自身の出典のうち、そのページに最も近いものです。以前に公開された根拠は、Vault ごとに一度再配置されます。",
    "ko": "인용은 이제 인용된 문장을 담은 구절에 근거합니다. 인용 자신의 출처이면서 해당 페이지에 가장 가까운 구절입니다. 이전에 게시된 근거는 Vault마다 한 번 다시 배치됩니다."
  },
  {
    category: 'fix',
    "scope": "library",
    "es": "El rango de páginas de una sección se queda dentro de su propia fuente. Ya no termina en la página del siguiente archivo adjunto.",
    "en": "A section's page range stays inside its own source. It no longer ends on the page of the next attachment.",
    "fr": "La plage de pages d'une section reste dans sa propre source. Elle ne se termine plus sur la page de la pièce jointe suivante.",
    "de": "Der Seitenbereich eines Abschnitts bleibt in seiner eigenen Quelle. Er endet nicht mehr auf der Seite des nächsten Anhangs.",
    "pt": "O intervalo de páginas de uma secção fica dentro da sua própria fonte. Já não termina na página do anexo seguinte.",
    "pt-BR": "O intervalo de páginas de uma seção fica dentro da própria fonte. Ele não termina mais na página do próximo anexo.",
    "it": "L'intervallo di pagine di una sezione resta dentro la sua stessa fonte. Non termina più sulla pagina dell'allegato successivo.",
    "tr": "Bir bölümün sayfa aralığı kendi kaynağı içinde kalır. Artık sonraki ekin sayfasında bitmez.",
    "zh-CN": "章节的页码范围留在自己的来源内。它不再结束于下一个附件的页码。",
    "zh-TW": "章節的頁碼範圍留在自己的來源內。它不再結束於下一個附件的頁碼。",
    "ja": "節のページ範囲は自分の出典の中で収まります。次の添付ファイルのページで終わることはなくなりました。",
    "ko": "섹션의 페이지 범위는 자기 출처 안에서 끝납니다. 더 이상 다음 첨부 파일의 페이지에서 끝나지 않습니다."
  },
  {
    category: 'fix',
    "scope": "library",
    "es": "Los registros de la biblioteca quedan más limpios. Una idea ya no puede relacionarse consigo misma, dos ideas del mismo escaneo con el mismo enunciado se unen en una sola, y los puntos de control de un trabajo fallido se descartan cuando otro posterior tiene éxito.",
    "en": "Library records are cleaner. An idea can no longer be related to itself, two ideas from the same scan with the same statement are joined into one, and the checkpoints of a failed job are dropped when a later one succeeds.",
    "fr": "Les enregistrements de la bibliothèque sont plus propres. Une idée ne peut plus être liée à elle-même, deux idées du même scan avec le même énoncé sont réunies en une seule, et les points de contrôle d'un travail échoué sont écartés lorsqu'un travail ultérieur réussit.",
    "de": "Die Einträge der Bibliothek sind sauberer. Eine Idee kann nicht mehr mit sich selbst verknüpft werden, zwei Ideen aus demselben Scan mit derselben Aussage werden zu einer zusammengeführt, und die Prüfpunkte eines fehlgeschlagenen Auftrags entfallen, sobald ein späterer erfolgreich ist.",
    "pt": "Os registos da biblioteca ficam mais limpos. Uma ideia já não pode ser relacionada consigo mesma, duas ideias do mesmo escaneamento com o mesmo enunciado juntam-se numa só, e os pontos de controlo de um trabalho falhado são descartados quando um posterior tem êxito.",
    "pt-BR": "Os registros da biblioteca ficam mais limpos. Uma ideia não pode mais ser relacionada consigo mesma, duas ideias do mesmo escaneamento com o mesmo enunciado são unidas em uma só, e os pontos de controle de um trabalho que falhou são descartados quando um posterior tem sucesso.",
    "it": "I record della biblioteca sono più puliti. Un'idea non può più essere collegata a se stessa, due idee della stessa scansione con lo stesso enunciato vengono unite in una sola, e i punti di controllo di un lavoro fallito vengono scartati quando uno successivo riesce.",
    "tr": "Kütüphane kayıtları daha temiz. Bir fikir artık kendisiyle ilişkilendirilemez, aynı taramadan aynı ifadeye sahip iki fikir tek fikirde birleştirilir ve başarısız bir işin kontrol noktaları sonraki bir iş başarılı olduğunda atılır.",
    "zh-CN": "资料库记录更干净。观点不再能与自身建立关联，同一次扫描中陈述相同的两条观点会合并为一条，失败任务的检查点在后来的任务成功后被丢弃。",
    "zh-TW": "知識庫記錄更乾淨。觀點不再能與自身建立關聯，同一次掃描中陳述相同的兩條觀點會合併為一條，失敗任務的檢查點在後來的任務成功後被丟棄。",
    "ja": "ライブラリの記録はより整いました。アイデアが自分自身と関連付けられることはなくなり、同じスキャンで同じ文を持つ二つのアイデアは一つにまとめられ、失敗した処理のチェックポイントは後の処理が成功した時点で破棄されます。",
    "ko": "보관함 기록이 더 깨끗해졌습니다. 아이디어는 더 이상 자기 자신과 연결될 수 없고, 같은 스캔에서 진술이 같은 두 아이디어는 하나로 합쳐지며, 실패한 작업의 체크포인트는 이후 작업이 성공하면 버려집니다."
  },
  {
    category: 'fix',
    "scope": "library",
    "es": "El texto extraído llega completo. Los caracteres que hacían que la consulta dejara de leer ahí se sustituyen, así que un pasaje ya no informa de una longitud más corta ni de un fragmento recortado. Además, una obra cuya ficha documental ha fallado ya no aparece en rojo como si no tuviera ficha, sino que se indica que ha fallado y se ofrece el reintento.",
    "en": "Extracted text arrives complete. The characters that made a query stop reading at that point are replaced, so a passage no longer reports a shorter length or a cut-off snippet. A work whose document profile failed no longer appears in red as if it had no profile at all, and the row now says the profile failed and offers the retry.",
    "fr": "Le texte extrait arrive complet. Les caractères qui faisaient s'arrêter la lecture d'une requête à cet endroit sont remplacés, donc un passage n'annonce plus une longueur plus courte ni un extrait tronqué. De plus, une œuvre dont la fiche documentaire a échoué n'apparaît plus en rouge comme si elle n'avait pas de fiche, la ligne indique que la fiche a échoué et propose de réessayer.",
    "de": "Der extrahierte Text kommt vollständig an. Die Zeichen, an denen eine Abfrage das Lesen abbrach, werden ersetzt, sodass eine Passage keine kürzere Länge und keinen abgeschnittenen Ausschnitt mehr meldet. Außerdem erscheint ein Werk, dessen Dokumentationsprofil fehlgeschlagen ist, nicht mehr rot, als hätte es kein Profil, sondern die Zeile sagt, dass es fehlgeschlagen ist, und bietet den erneuten Versuch an.",
    "pt": "O texto extraído chega completo. Os caracteres que faziam a consulta parar de ler nesse ponto são substituídos, por isso um passagem já não indica um comprimento mais curto nem um fragmento cortado. Além disso, uma obra cuja ficha documental falhou já não aparece a vermelho como se não tivesse ficha, a linha diz que falhou e oferece a nova tentativa.",
    "pt-BR": "O texto extraído chega completo. Os caracteres que faziam a consulta parar de ler naquele ponto são substituídos, então um trecho não informa mais um comprimento menor nem um fragmento cortado. Além disso, uma obra cuja ficha documental falhou não aparece mais em vermelho como se não tivesse ficha, a linha diz que falhou e oferece a nova tentativa.",
    "it": "Il testo estratto arriva completo. I caratteri che facevano smettere di leggere una query in quel punto vengono sostituiti, quindi un passaggio non indica più una lunghezza più corta né un estratto tagliato. Inoltre un'opera la cui scheda documentale è fallita non appare più in rosso come se non avesse scheda, la riga dice che è fallita e propone di riprovare.",
    "tr": "Çıkarılan metin eksiksiz geliyor. Bir sorgunun okumayı orada bırakmasına yol açan karakterler değiştiriliyor, böylece bir bölüm artık daha kısa bir uzunluk ya da kesilmiş bir alıntı bildirmiyor. Ayrıca belge kartı başarısız olan bir eser, kartı yokmuş gibi kırmızı görünmüyor, satır başarısız olduğunu söylüyor ve yeniden denemeyi sunuyor.",
    "zh-CN": "提取的文本完整送达。使查询在该处停止读取的字符会被替换，因此片段不再报告更短的长度或截断的摘要。另外，文档卡片失败的作品不再像没有卡片那样显示为红色，该行会说明已失败并提供重试。",
    "zh-TW": "擷取的文字完整送達。使查詢在該處停止讀取的字符會被取代，因此片段不再報告更短的長度或截斷的摘要。另外，文件卡片失敗的作品不再像沒有卡片那樣顯示為紅色，該列會說明已失敗並提供重試。",
    "ja": "抽出した文章は最後まで届きます。検索がそこで読むのを止めていた文字を置き換えるため、抜粋が短い長さや切り詰められた断片を報告することはなくなりました。また、文書プロファイルに失敗した作品は、プロファイルがないかのように赤く表示されず、失敗したことを示して再試行を提供します。",
    "ko": "추출한 텍스트가 온전히 전달됩니다. 조회가 그 지점에서 읽기를 멈추게 하던 문자를 바꾸므로, 구절이 더 짧은 길이나 잘린 일부를 보고하지 않습니다. 또한 문서 프로필이 실패한 문헌은 프로필이 없는 것처럼 빨갛게 표시되지 않고, 실패했음을 알리고 다시 시도를 제공합니다."
  },
  {
    category: 'fix',
    "scope": "ai",
    "es": "Después de un reprocesado, solo se vuelven a convertir en vectores las ideas cuyo texto de temas ha cambiado, y una sola vez cada una, en lugar de toda la biblioteca. Esto vale para el pase automático y para las dos acciones manuales de reprocesado.",
    "en": "After a reprocess pass, only the ideas whose theme text changed are converted into vectors again, once each, instead of the whole library. This applies to the automatic pass and to both manual reprocess actions.",
    "fr": "Après un retraitement, seules les idées dont le texte des thèmes a changé sont reconverties en vecteurs, une seule fois chacune, au lieu de toute la bibliothèque. Cela vaut pour la passe automatique et pour les deux actions manuelles de retraitement.",
    "de": "Nach einem erneuten Durchlauf werden nur die Ideen erneut in Vektoren umgewandelt, deren Thema-Text sich geändert hat, jede einmal, statt der ganzen Bibliothek. Das gilt für den automatischen Durchlauf und für beide manuellen Aktionen.",
    "pt": "Depois de um reprocessamento, só voltam a ser convertidas em vetores as ideias cujo texto de temas mudou, uma só vez cada, em vez de toda a biblioteca. Isto aplica-se à passagem automática e às duas ações manuais de reprocessamento.",
    "pt-BR": "Depois de um reprocessamento, só voltam a ser convertidas em vetores as ideias cujo texto de temas mudou, uma só vez cada, em vez de toda a biblioteca. Isso vale para a passagem automática e para as duas ações manuais de reprocessamento.",
    "it": "Dopo una rielaborazione, vengono riconvertite in vettori solo le idee il cui testo dei temi è cambiato, una sola volta ciascuna, invece dell'intera biblioteca. Vale per il passaggio automatico e per le due azioni manuali di rielaborazione.",
    "tr": "Yeniden işlemeden sonra tüm kütüphane yerine yalnızca tema metni değişen fikirler yeniden vektöre çevrilir, her biri bir kez. Bu, otomatik geçiş ve iki elle yeniden işleme eylemi için geçerlidir.",
    "zh-CN": "重新处理之后，只有主题文本发生变化的观点会再次转换为向量，每条只转换一次，而不是整个资料库。这一规则适用于自动处理和两个手动重新处理操作。",
    "zh-TW": "重新處理之後，只有主題文字發生變化的觀點會再次轉換為向量，每條只轉換一次，而不是整個知識庫。這項規則適用於自動處理和兩個手動重新處理操作。",
    "ja": "再処理のあと、ベクトルに変換し直すのはテーマの文章が変わったアイデアだけになり、それぞれ一度だけです。ライブラリ全体ではなくなりました。自動の処理と二つの手動の再処理に適用されます。",
    "ko": "다시 처리한 뒤에는 보관함 전체가 아니라 주제 문장이 바뀐 아이디어만 벡터로 다시 변환하며, 각각 한 번만 변환합니다. 자동 처리와 두 가지 수동 재처리 동작에 적용됩니다."
  },
  {
    category: 'fix',
    "scope": "general",
    "es": "Los paquetes de Linux vuelven a arrancar en Ubuntu 22.04, Debian 12 y otros sistemas con glibc anterior a 2.38. La versión 5.7.1 se detenía antes de su primera ventana con el aviso GLIBC_2.38 not found. Los paquetes de Linux se compilan ahora en Ubuntu 22.04 y la publicación falla si alguna biblioteca incluida necesita una glibc más reciente.",
    "en": "The Linux packages start again on Ubuntu 22.04, Debian 12 and other systems with glibc older than 2.38. Version 5.7.1 stopped before its first window with the message GLIBC_2.38 not found. Linux packages are now built on Ubuntu 22.04, and the release fails if any bundled library needs a newer glibc.",
    "fr": "Les paquets Linux démarrent de nouveau sur Ubuntu 22.04, Debian 12 et d'autres systèmes dont la glibc est antérieure à 2.38. La version 5.7.1 s'arrêtait avant sa première fenêtre avec le message GLIBC_2.38 not found. Les paquets Linux sont désormais compilés sur Ubuntu 22.04 et la publication échoue si une bibliothèque incluse exige une glibc plus récente.",
    "de": "Die Linux-Pakete starten wieder auf Ubuntu 22.04, Debian 12 und anderen Systemen mit einer glibc älter als 2.38. Version 5.7.1 blieb vor ihrem ersten Fenster mit der Meldung GLIBC_2.38 not found stehen. Linux-Pakete werden jetzt auf Ubuntu 22.04 gebaut, und die Veröffentlichung schlägt fehl, wenn eine mitgelieferte Bibliothek eine neuere glibc braucht.",
    "pt": "Os pacotes de Linux voltam a arrancar no Ubuntu 22.04, no Debian 12 e noutros sistemas com glibc anterior a 2.38. A versão 5.7.1 parava antes da primeira janela com a mensagem GLIBC_2.38 not found. Os pacotes de Linux são agora compilados no Ubuntu 22.04 e a publicação falha se alguma biblioteca incluída precisar de uma glibc mais recente.",
    "pt-BR": "Os pacotes de Linux voltam a iniciar no Ubuntu 22.04, no Debian 12 e em outros sistemas com glibc anterior a 2.38. A versão 5.7.1 parava antes da primeira janela com a mensagem GLIBC_2.38 not found. Os pacotes de Linux agora são compilados no Ubuntu 22.04 e a publicação falha se alguma biblioteca incluída precisar de uma glibc mais recente.",
    "it": "I pacchetti Linux tornano ad avviarsi su Ubuntu 22.04, Debian 12 e altri sistemi con glibc precedente alla 2.38. La versione 5.7.1 si fermava prima della prima finestra con il messaggio GLIBC_2.38 not found. I pacchetti Linux ora vengono compilati su Ubuntu 22.04 e la pubblicazione fallisce se una libreria inclusa richiede una glibc più recente.",
    "tr": "Linux paketleri Ubuntu 22.04, Debian 12 ve glibc sürümü 2.38'den eski olan diğer sistemlerde yeniden açılıyor. 5.7.1 sürümü ilk penceresinden önce GLIBC_2.38 not found iletisiyle duruyordu. Linux paketleri artık Ubuntu 22.04 üzerinde derleniyor ve pakete dahil bir kütüphane daha yeni bir glibc gerektirirse yayın başarısız oluyor.",
    "zh-CN": "Linux 软件包重新可以在 Ubuntu 22.04、Debian 12 以及 glibc 低于 2.38 的系统上启动。5.7.1 在这些系统上会在第一个窗口出现前停止，并提示 GLIBC_2.38 not found。Linux 软件包现在在 Ubuntu 22.04 上构建，如果有随附的库需要更新的 glibc，发布就会失败。",
    "zh-TW": "Linux 套件重新可以在 Ubuntu 22.04、Debian 12 以及 glibc 低於 2.38 的系統上啟動。5.7.1 在這些系統上會在第一個視窗出現前停止，並提示 GLIBC_2.38 not found。Linux 套件現在在 Ubuntu 22.04 上建置，如果有隨附的函式庫需要更新的 glibc，發佈就會失敗。",
    "ja": "Linux パッケージが Ubuntu 22.04、Debian 12、および glibc が 2.38 より古いシステムで再び起動します。5.7.1 では最初のウィンドウの前に GLIBC_2.38 not found と表示されて停止していました。Linux パッケージは Ubuntu 22.04 でビルドされ、同梱のライブラリがより新しい glibc を必要とすれば公開は失敗します。",
    "ko": "Linux 패키지가 Ubuntu 22.04, Debian 12 및 glibc가 2.38보다 오래된 시스템에서 다시 시작됩니다. 5.7.1은 첫 창이 뜨기 전에 GLIBC_2.38 not found 메시지와 함께 멈췄습니다. Linux 패키지는 이제 Ubuntu 22.04에서 빌드되며, 함께 포함된 라이브러리가 더 새로운 glibc를 요구하면 공개가 실패합니다."
  }
];
