import type { ReleaseHighlight } from './releaseNotes';

/**
 * v5.4.3: a reasoning model no longer gets the work summary stored clipped at the output
 * ceiling, the browser connector's pairing prompt reaches the front on macOS, and the JSON
 * payload a capability tool returns no longer competes with the answer it supports. Keep
 * the IT/TR arrays aligned with this order: they are matched by index.
 */
export const RELEASE_5_4_3_HIGHLIGHTS: ReleaseHighlight[] = [
  {
    scope: 'ai',
    es: 'Los resúmenes de las obras dejan de guardarse cortados a mitad de frase. En un modelo con razonamiento, el presupuesto de salida se agotaba pensando y la generación terminaba antes de escribir el final, pero el resumen se guardaba como completado. Ahora el primer intento dispone de más espacio y, si aun así se corta, Nodus lo reintenta una vez con el presupuesto más amplio de la aplicación. Si el modelo vuelve a agotarlo, el resumen se marca como fallido en lugar de guardarse incompleto.',
    en: 'Work summaries are no longer stored cut off mid-sentence. With a reasoning model, the output budget ran out while thinking and generation stopped before the closing lines, yet the summary was saved as completed. The first attempt now gets real headroom and, if it is still cut off, Nodus retries once at the app’s larger budget. If the model exhausts that too, the summary is marked as failed instead of stored incomplete.',
    fr: 'Les résumés des ouvrages ne sont plus enregistrés coupés en pleine phrase. Avec un modèle de raisonnement, le budget de sortie s’épuisait pendant la réflexion et la génération s’arrêtait avant la fin, mais le résumé était enregistré comme terminé. La première tentative dispose désormais d’une vraie marge et, si elle est encore coupée, Nodus réessaie une fois avec le budget plus large de l’application. Si le modèle l’épuise aussi, le résumé est marqué comme échoué au lieu d’être enregistré incomplet.',
    de: 'Zusammenfassungen von Werken werden nicht mehr mitten im Satz abgeschnitten gespeichert. Bei einem Denkmodell ging das Ausgabebudget beim Nachdenken zur Neige und die Erzeugung endete vor dem Schluss, die Zusammenfassung galt aber als fertig. Der erste Versuch erhält jetzt echten Spielraum, und wenn er trotzdem abgeschnitten wird, wiederholt Nodus ihn einmal mit dem größeren Budget der Anwendung. Erschöpft das Modell auch dieses, wird die Zusammenfassung als fehlgeschlagen markiert, statt unvollständig gespeichert zu werden.',
    pt: 'Os resumos das obras deixam de ser guardados cortados a meio da frase. Num modelo com raciocínio, o orçamento de saída esgotava-se a pensar e a geração parava antes do fim, mas o resumo era guardado como concluído. Agora a primeira tentativa tem espaço real e, se ainda assim for cortada, o Nodus repete uma vez com o orçamento maior da aplicação. Se o modelo também o esgotar, o resumo é marcado como falhado em vez de ser guardado incompleto.',
    'pt-BR': 'Os resumos das obras não são mais salvos cortados no meio da frase. Em um modelo com raciocínio, o orçamento de saída se esgotava pensando e a geração parava antes do fim, mas o resumo era salvo como concluído. Agora a primeira tentativa tem espaço real e, se ainda for cortada, o Nodus tenta uma vez com o orçamento maior do aplicativo. Se o modelo esgotar esse também, o resumo é marcado como falho em vez de ser salvo incompleto.',
    it: 'I riepiloghi delle opere non vengono più salvati tagliati a metà frase. Con un modello di ragionamento il budget di output si esauriva pensando e la generazione si fermava prima della fine, ma il riepilogo veniva salvato come completato. Ora il primo tentativo ha spazio reale e, se viene comunque tagliato, Nodus riprova una volta con il budget più ampio dell’app. Se anche quello si esaurisce, il riepilogo viene segnato come fallito invece di essere salvato incompleto.',
    tr: 'Eser özetleri artık cümle ortasında kesilmiş hâlde kaydedilmiyor. Bir akıl yürütme modelinde çıktı bütçesi düşünürken tükeniyor ve üretim sona ermeden duruyordu, ama özet tamamlanmış olarak kaydediliyordu. Artık ilk deneme gerçek bir alana sahip ve yine kesilirse Nodus uygulamanın daha geniş bütçesiyle bir kez daha deniyor. Model onu da tüketirse özet eksik kaydedilmek yerine başarısız olarak işaretleniyor.',
    'zh-CN': "文献摘要不再被截断在句子中间保存。使用推理模型时，输出预算在思考阶段就已耗尽，生成在写出结尾之前就停止，但摘要却被标记为已完成并保存。现在首次尝试拥有更多余量，如果仍被截断，Nodus会用应用更大的预算重试一次。若模型再次耗尽预算，摘要会被标记为失败，而不是以不完整状态保存。",
    'zh-TW': "文獻摘要不再被截斷在句子中間儲存。使用推理模型時，輸出預算在思考階段就已耗盡，生成在寫出結尾之前就停止，但摘要卻被標記為已完成並儲存。現在首次嘗試擁有更多餘量，如果仍被截斷，Nodus會用應用更大的預算重試一次。若模型再次耗盡預算，摘要會被標記為失敗，而不是以不完整狀態儲存。",
  },
  {
    scope: 'connector',
    es: 'El emparejamiento del navegador deja de esperar en silencio. En macOS, el aviso para emparejar se abría detrás de Chrome, que seguía siendo la aplicación activa, y la petición terminaba sin que nadie llegara a verlo. Ahora Nodus pasa al frente en cuanto recibe la solicitud y, si el sistema rechaza esa activación, pide atención como lo hace la plataforma, con un parpadeo en la barra de tareas o un rebote en el Dock. La señal se apaga en cuanto la ventana recibe el foco o el emparejamiento se resuelve.',
    en: 'Pairing your browser no longer waits in silence. On macOS, the pairing prompt opened behind Chrome, which remained the active app, and the request timed out with nobody seeing it. Nodus now comes to the front as soon as the request arrives and, when the system refuses that activation, asks for attention the way the platform does, with a taskbar flash or a dock bounce. The signal stops as soon as the window takes focus or the pairing is settled.',
    fr: 'L’appairage du navigateur ne reste plus en attente dans le silence. Sous macOS, l’invite d’appairage s’ouvrait derrière Chrome, qui restait l’application active, et la demande expirait sans que personne ne la voie. Nodus passe maintenant au premier plan dès que la demande arrive et, si le système refuse cette activation, réclame l’attention comme le fait la plateforme, par un clignotement dans la barre des tâches ou un rebond dans le Dock. Le signal cesse dès que la fenêtre prend le focus ou que l’appairage est réglé.',
    de: 'Die Kopplung des Browsers wartet nicht mehr stumm. Unter macOS öffnete sich der Kopplungshinweis hinter Chrome, das die aktive App blieb, und die Anfrage lief aus, ohne dass jemand sie sah. Nodus tritt jetzt in den Vordergrund, sobald die Anfrage eintrifft, und wenn das System diese Aktivierung verweigert, fordert es Aufmerksamkeit, wie es die Plattform tut, mit einem Blinken in der Taskleiste oder einem Hüpfen im Dock. Das Signal endet, sobald das Fenster den Fokus erhält oder die Kopplung abgeschlossen ist.',
    pt: 'O emparelhamento do navegador deixa de esperar em silêncio. No macOS, o aviso de emparelhamento abria-se atrás do Chrome, que continuava a ser a aplicação ativa, e o pedido expirava sem que ninguém o visse. Agora o Nodus vem para a frente assim que recebe o pedido e, se o sistema recusar essa ativação, pede atenção como a plataforma faz, com um piscar na barra de tarefas ou um salto no Dock. O sinal desliga assim que a janela recebe o foco ou o emparelhamento fica resolvido.',
    'pt-BR': 'O pareamento do navegador deixa de esperar em silêncio. No macOS, o aviso de pareamento abria atrás do Chrome, que continuava sendo o aplicativo ativo, e a solicitação expirava sem que ninguém a visse. Agora o Nodus vem para a frente assim que recebe a solicitação e, se o sistema recusar essa ativação, pede atenção como a plataforma faz, com um piscar na barra de tarefas ou um pulo no Dock. O sinal para assim que a janela recebe o foco ou o pareamento é resolvido.',
    it: 'L’accoppiamento del browser non resta più in attesa nel silenzio. Su macOS, l’avviso di accoppiamento si apriva dietro Chrome, che rimaneva l’app attiva, e la richiesta scadeva senza che nessuno lo vedesse. Ora Nodus passa in primo piano appena arriva la richiesta e, se il sistema rifiuta quell’attivazione, chiede attenzione come fa la piattaforma, con un lampeggio nella barra delle applicazioni o un rimbalzo nel Dock. Il segnale si spegne appena la finestra riceve il focus o l’accoppiamento viene risolto.',
    tr: 'Tarayıcı eşleştirmesi artık sessizce beklemiyor. macOS’ta eşleştirme uyarısı, etkin uygulama olmayı sürdüren Chrome’un arkasında açılıyor ve istek, kimse görmeden zaman aşımına uğruyordu. Nodus artık istek gelir gelmez öne geçiyor ve sistem bu etkinleştirmeyi reddederse platformun yaptığı gibi dikkat çekiyor, görev çubuğunda yanıp sönerek ya da Dock’ta zıplayarak. Sinyal, pencere odağı alır almaz veya eşleştirme sonuçlanınca duruyor.',
    'zh-CN': "浏览器配对不再默默等待。在macOS上，配对提示会打开在Chrome之后，而Chrome仍是活动应用，请求最终超时，无人看到。现在Nodus一收到请求就会置前，如果系统拒绝该激活，它会像平台那样请求关注，通过在任务栏闪烁或在Dock弹跳。窗口获得焦点或配对完成后，该信号立即停止。",
    'zh-TW': "瀏覽器配對不再默默等待。在macOS上，配對提示會開啟在Chrome之後，而Chrome仍是活動應用，請求最終超時，無人看到。現在Nodus一收到請求就會置前，如果系統拒絕該啟用，它會像平臺那樣請求關注，通過在工作列閃爍或在Dock彈跳。視窗獲得焦點或配對完成後，該訊號立即停止。",
  },
  {
    scope: 'plugin',
    es: 'Los resultados JSON de una herramienta dejan de ocupar la conversación como si fueran el entregable. Antes se volcaban en un bloque sin estilo y tan alto como la respuesta, así que una consulta de procedencia parecía salida de depuración junto a la figura que habías pedido. Ahora el JSON queda plegado bajo «Evidencia», a un clic, y la figura conserva el centro del mensaje.',
    en: 'A tool’s JSON results no longer take over the conversation as if they were the deliverable. They used to land in an unstyled block as tall as the answer, so a provenance query looked like debug output next to the figure you had asked for. The JSON now stays folded under “Evidence”, one click away, and the figure keeps the centre of the message.',
    fr: 'Les résultats JSON d’un outil n’occupent plus la conversation comme s’ils étaient le livrable. Ils s’affichaient dans un bloc sans style, aussi haut que la réponse, si bien qu’une requête de provenance ressemblait à une sortie de débogage à côté de la figure demandée. Le JSON reste désormais replié sous « Preuve », à un clic, et la figure garde le centre du message.',
    de: 'JSON-Ergebnisse eines Werkzeugs übernehmen nicht mehr die Unterhaltung, als wären sie das Ergebnis selbst. Sie landeten in einem unformatierten Block, so hoch wie die Antwort, sodass eine Herkunftsabfrage neben der gewünschten Abbildung wie Debug-Ausgabe aussah. Das JSON bleibt jetzt unter „Beleg“ eingeklappt, einen Klick entfernt, und die Abbildung behält die Mitte der Nachricht.',
    pt: 'Os resultados JSON de uma ferramenta deixam de ocupar a conversa como se fossem o resultado final. Apareciam num bloco sem estilo e tão alto como a resposta, pelo que uma consulta de proveniência parecia saída de depuração ao lado da figura pedida. Agora o JSON fica recolhido em «Evidência», a um clique, e a figura mantém o centro da mensagem.',
    'pt-BR': 'Os resultados JSON de uma ferramenta não ocupam mais a conversa como se fossem o entregável. Eles apareciam num bloco sem estilo e tão alto quanto a resposta, então uma consulta de procedência parecia saída de depuração ao lado da figura pedida. Agora o JSON fica recolhido em “Evidência”, a um clique, e a figura mantém o centro da mensagem.',
    it: 'I risultati JSON di uno strumento non occupano più la conversazione come se fossero il risultato finale. Comparivano in un blocco senza stile, alto quanto la risposta, così una query di provenienza sembrava output di debug accanto alla figura richiesta. Ora il JSON resta richiuso sotto «Prove», a un clic di distanza, e la figura mantiene il centro del messaggio.',
    tr: 'Bir aracın JSON sonuçları artık son ürünmüş gibi sohbeti kaplamıyor. Yanıt kadar yüksek, biçimsiz bir blok olarak görünüyorlardı ve bu yüzden bir köken sorgusu, istediğiniz şeklin yanında hata ayıklama çıktısı gibi duruyordu. JSON artık «Kanıt» altında katlanmış hâlde, tek tıkla açılıyor ve şekil mesajın merkezinde kalıyor.',
    'zh-CN': "工具的JSON结果不再像最终交付物那样占据整个对话。以前它们会被倾倒进一个没有样式、与回答同样高的区块，于是溯源查询在你请求的图形旁边看起来像调试输出。现在JSON折叠在「证据」下，一点即可展开，图形仍占据消息的中心。",
    'zh-TW': "工具的JSON結果不再像最終交付物那樣佔據整個對話。以前它們會被傾倒進一個沒有樣式、與回答同樣高的區塊，於是溯源查詢在你請求的圖形旁邊看起來像除錯輸出。現在JSON摺疊在「證據」下，一點即可展開，圖形仍佔據訊息的中心。",
  },
];
