import type { ReleaseHighlight } from './releaseNotes';

/** Added since the unpublished 5.3.2 notes, including conversation file attachments. */
export const RELEASE_5_4_0_ADDITIONS: ReleaseHighlight[] = [
  {
    scope: 'ai',
    es: 'Research chat se unifica en los nueve tipos de vault. Encuéntralo en Analizar, con el mismo selector de modelo, acciones de mensaje y paneles plegables de historial y contexto. Conserva las conversaciones anteriores y las fuentes, citas y herramientas propias de cada vault.',
    en: 'Research chat is unified across all nine vault types. Find it under Analyze, with shared model controls, message actions and collapsible history and context panels. Existing conversations and each vault’s sources, citations and tools are preserved.',
    fr: 'Research chat est unifié dans les neuf types de vault. Retrouvez-le dans Analyser avec les mêmes commandes de modèle et de message, et des panneaux repliables. Les conversations, sources, citations et outils propres à chaque vault sont conservés.',
    de: 'Research chat ist in allen neun Vault-Typen vereinheitlicht. Unter Analysieren finden Sie gemeinsame Modell- und Nachrichtenaktionen sowie einklappbare Verlaufs- und Kontextbereiche. Bestehende Gespräche, Quellen, Zitate und die Werkzeuge jedes Vaults bleiben erhalten.',
    pt: 'O Research chat está unificado nos nove tipos de vault. Encontra-o em Analisar, com controlos de modelo e mensagem comuns e painéis recolhíveis de histórico e contexto. As conversas, fontes, citações e ferramentas de cada vault mantêm-se.',
    'pt-BR': 'O Research chat está unificado nos nove tipos de vault. Encontre-o em Analisar, com controles de modelo e mensagem comuns e painéis recolhíveis de histórico e contexto. As conversas, fontes, citações e ferramentas de cada vault são preservadas.',
    it: 'Research chat è unificato nei nove tipi di vault. Si trova in Analizza, con controlli comuni per modello e messaggi e pannelli richiudibili per cronologia e contesto. Conversazioni, fonti, citazioni e strumenti di ogni vault restano disponibili.',
    tr: 'Research chat dokuz kasa türünde birleşiyor. Analiz bölümünde ortak model kontrolleri, mesaj işlemleri ve daraltılabilir geçmiş ve bağlam panelleriyle açılıyor. Önceki konuşmalar ve her kasanın kaynakları, alıntıları ve araçları korunuyor.',
  },
  {
    scope: 'ai',
    es: 'Elige el esfuerzo de razonamiento desde el Research chat. Los niveles disponibles se ajustan a las capacidades del proveedor y del modelo seleccionado, y se aplican a la conversación sin cambiar los ajustes de los demás chats.',
    en: 'Choose reasoning effort directly in Research chat. Available levels follow the selected provider and model’s capabilities and apply to the conversation without changing the settings of other chats.',
    fr: 'Choisissez l’effort de raisonnement dans Research chat. Les niveaux proposés suivent les capacités du fournisseur et du modèle sélectionnés, sans modifier les réglages des autres chats.',
    de: 'Wählen Sie den Denkaufwand direkt in Research chat. Die verfügbaren Stufen richten sich nach Anbieter und Modell und gelten für das Gespräch, ohne Einstellungen anderer Chats zu ändern.',
    pt: 'Escolhe o esforço de raciocínio no Research chat. Os níveis disponíveis respeitam as capacidades do fornecedor e do modelo escolhido, sem alterar as definições dos outros chats.',
    'pt-BR': 'Escolha o esforço de raciocínio no Research chat. Os níveis disponíveis respeitam as capacidades do provedor e do modelo escolhido, sem alterar as configurações dos outros chats.',
    it: 'Scegli lo sforzo di ragionamento direttamente in Research chat. I livelli disponibili rispettano le capacità del fornitore e del modello selezionati, senza cambiare le impostazioni delle altre chat.',
    tr: 'Akıl yürütme düzeyini Research chat içinden seçin. Kullanılabilir düzeyler seçilen sağlayıcı ve modelin yeteneklerine uyar ve diğer sohbetlerin ayarlarını değiştirmez.',
  },
  {
    scope: 'ai',
    es: 'Acota las fuentes del corpus por autor y por obra. El nuevo selector permite buscar y combinar ambas restricciones, las guarda con la conversación y evita que fuentes excluidas vuelvan a entrar a través del historial. Si la selección no aporta evidencia, el chat lo reconoce.',
    en: 'Narrow corpus sources by author and work. Search and combine both filters, save them with the conversation and keep excluded sources from returning through history. When the selection provides no evidence, the chat acknowledges it.',
    fr: 'Limitez les sources du corpus par auteur et par œuvre. Recherchez et combinez les filtres, enregistrés avec la conversation. Les sources exclues ne reviennent pas par l’historique, et le chat signale l’absence de preuves.',
    de: 'Grenzen Sie Korpusquellen nach Autor und Werk ein. Beide Filter sind durchsuchbar, kombinierbar und werden mit dem Gespräch gespeichert. Ausgeschlossene Quellen kommen nicht über den Verlauf zurück. Fehlende Belege werden benannt.',
    pt: 'Restringe as fontes do corpus por autor e obra. Pesquisa e combina os filtros, que ficam guardados com a conversa. As fontes excluídas não regressam pelo histórico, e o chat reconhece quando faltam evidências.',
    'pt-BR': 'Restrinja as fontes do corpus por autor e obra. Pesquise e combine os filtros, que ficam salvos com a conversa. As fontes excluídas não retornam pelo histórico, e o chat reconhece quando faltam evidências.',
    it: 'Limita le fonti del corpus per autore e opera. Cerca e combina i filtri, salvati con la conversazione. Le fonti escluse non rientrano attraverso la cronologia e la chat segnala quando mancano prove.',
    tr: 'Derlem kaynaklarını yazar ve esere göre daraltın. Aranabilir filtreleri birlikte kullanın ve konuşmayla kaydedin. Dışlanan kaynaklar geçmiş üzerinden geri gelmez. Seçim kanıt sağlamıyorsa sohbet bunu belirtir.',
  },
  {
    scope: 'ai',
    es: 'Guarda tus propias instrucciones para el Research chat. Crea, busca, edita y selecciona prompts dentro de cada vault para orientar el tono y la estructura de las respuestas. Puedes cambiarlos en una conversación existente sin perder su historial y volver a Default cuando quieras.',
    en: 'Save your own Research chat instructions. Create, search, edit and select prompts within each vault to guide response tone and structure. Switch prompts in an existing conversation without losing its history, or return to Default.',
    fr: 'Enregistrez vos instructions pour Research chat. Créez, recherchez, modifiez et sélectionnez des prompts dans chaque vault pour guider le ton et la structure. Changez-les sans perdre l’historique ou revenez à Default.',
    de: 'Speichern Sie eigene Anweisungen für Research chat. Erstellen, suchen und bearbeiten Sie Prompts pro Vault für Ton und Aufbau der Antworten. Wechseln Sie im laufenden Gespräch ohne Verlaufsverlust oder kehren Sie zu Default zurück.',
    pt: 'Guarda instruções próprias para o Research chat. Cria, pesquisa, edita e escolhe prompts em cada vault para orientar o tom e a estrutura. Muda de prompt sem perder o histórico ou regressa a Default.',
    'pt-BR': 'Salve instruções próprias para o Research chat. Crie, pesquise, edite e escolha prompts em cada vault para orientar o tom e a estrutura. Mude de prompt sem perder o histórico ou volte a Default.',
    it: 'Salva le tue istruzioni per Research chat. Crea, cerca, modifica e seleziona prompt in ogni vault per guidare tono e struttura. Cambia prompt senza perdere la cronologia o torna a Default.',
    tr: 'Research chat için kendi talimatlarınızı kaydedin. Her kasada yanıtların tonunu ve yapısını yönlendiren istemler oluşturun, arayın, düzenleyin ve seçin. Geçmişi kaybetmeden istem değiştirin veya Default seçeneğine dönün.',
  },
  {
    scope: 'ai',
    es: 'Adjunta archivos al Research chat con el botón + del cuadro de texto o arrastrándolos a la ventana. Lee DOC, DOCX, PDF, hojas de cálculo, CSV, XML, imágenes y otros formatos compatibles usando el proveedor y modelo elegidos, con visión cuando sea necesaria. Los adjuntos se conservan con la conversación y se borran al eliminarla. Sus tarjetas tienen contornos legibles en claro y oscuro y usan el acento del vault.',
    en: 'Attach files to Research chat with the textbox’s + button or by dropping them into the window. Read DOC, DOCX, PDF, spreadsheets, CSV, XML, images and other supported formats with your chosen provider and model, using vision when needed. Files stay with the conversation and are deleted with it. Cards have clear light and dark outlines and use the vault accent.',
    fr: 'Joignez des fichiers dans Research chat avec le bouton + ou par glisser-déposer. DOC, DOCX, PDF, tableurs, CSV, XML, images et autres formats pris en charge utilisent le modèle choisi, avec vision si nécessaire. Les fichiers suivent la conversation et sa suppression. Leurs cartes restent lisibles dans les deux thèmes et suivent l’accent du vault.',
    de: 'Hängen Sie Dateien in Research chat über + oder per Drag-and-drop an. DOC, DOCX, PDF, Tabellen, CSV, XML, Bilder und weitere unterstützte Formate nutzen den gewählten Anbieter und das Modell, bei Bedarf mit Bildverständnis. Dateien bleiben beim Gespräch und werden mit ihm gelöscht. Karten sind in beiden Designs klar umrandet und nutzen den Vault-Akzent.',
    pt: 'Anexa ficheiros ao Research chat com + ou arrastando-os para a janela. DOC, DOCX, PDF, folhas de cálculo, CSV, XML, imagens e outros formatos compatíveis usam o fornecedor e modelo escolhidos, com visão quando necessária. Os ficheiros acompanham a conversa e são eliminados com ela. Os cartões têm contornos legíveis nos dois temas e usam o destaque do vault.',
    'pt-BR': 'Anexe arquivos ao Research chat com + ou arrastando-os para a janela. DOC, DOCX, PDF, planilhas, CSV, XML, imagens e outros formatos compatíveis usam o provedor e modelo escolhidos, com visão quando necessária. Os arquivos acompanham a conversa e são excluídos com ela. Os cartões têm contornos legíveis nos dois temas e usam o destaque do vault.',
    it: 'Allega file a Research chat con + o trascinandoli nella finestra. DOC, DOCX, PDF, fogli di calcolo, CSV, XML, immagini e altri formati supportati usano fornitore e modello scelti, con visione quando necessaria. I file restano con la conversazione e vengono eliminati con essa. Le schede hanno bordi leggibili nei due temi e usano l’accento del vault.',
    tr: 'Research chat içine + düğmesiyle veya sürükleyerek dosya ekleyin. DOC, DOCX, PDF, tablolar, CSV, XML, resimler ve desteklenen diğer biçimler seçtiğiniz sağlayıcı ve modeli, gerektiğinde görme yeteneğini kullanır. Dosyalar konuşmayla saklanır ve silinir. Kartlar açık ve koyu temada belirgin kenarlara sahiptir ve kasanın vurgu rengini kullanır.',
  },
  {
    scope: 'ai',
    es: 'Leer y detener una respuesta resulta más cómodo. El Research chat respeta tu posición cuando subes a leer, y las vistas previas de las citas vuelven a abrirse correctamente. Al detener una respuesta, el texto ya recibido se conserva en el historial en lugar de desaparecer.',
    en: 'Reading and stopping answers is smoother. Research chat respects your position when you scroll up, and citation previews open correctly again. Stopping an answer preserves the text already received in history instead of making it disappear.',
    fr: 'La lecture et l’arrêt des réponses sont plus confortables. Research chat respecte votre position de lecture et les aperçus de citations s’ouvrent correctement. Arrêter une réponse conserve le texte déjà reçu dans l’historique.',
    de: 'Antworten lassen sich angenehmer lesen und stoppen. Research chat behält Ihre Leseposition beim Hochscrollen bei und öffnet Zitatvorschauen korrekt. Beim Stoppen bleibt der bereits empfangene Text im Verlauf erhalten.',
    pt: 'Ler e parar respostas é mais cómodo. O Research chat respeita a posição de leitura e abre corretamente as pré-visualizações das citações. Ao parar uma resposta, o texto recebido mantém-se no histórico.',
    'pt-BR': 'Ler e parar respostas ficou mais confortável. O Research chat respeita a posição de leitura e abre corretamente as prévias das citações. Ao parar uma resposta, o texto recebido permanece no histórico.',
    it: 'Leggere e interrompere le risposte è più comodo. Research chat rispetta la posizione di lettura e apre correttamente le anteprime delle citazioni. Interrompendo una risposta, il testo già ricevuto resta nella cronologia.',
    tr: 'Yanıtları okumak ve durdurmak daha rahat. Research chat yukarı kaydırdığınızda okuma konumunuzu korur ve alıntı önizlemeleri doğru açılır. Yanıt durdurulduğunda alınan metin kaybolmak yerine geçmişte kalır.',
  },
  {
    scope: 'ai',
    es: 'Las Skills visuales llegan a Deep Research e Immersion en escritorio. Elige las que puede usar cada informe y limita sus ejecuciones, con un máximo explícito para las de pago. Añade figuras a informes nuevos o existentes, abre sus recursos interactivos, descarga los resultados y conserva las figuras al exportar a PDF. Puedes retirar los recursos y deshacer el cambio.',
    en: 'Visual Skills come to desktop Deep Research and Immersion. Choose Skills per report and limit their runs, with an explicit ceiling for paid calls. Add figures to new or existing reports, open interactive resources, download results and keep figures in PDF exports. Remove resources and undo the change.',
    fr: 'Les Skills visuelles arrivent dans Deep Research et Immersion sur ordinateur. Choisissez-les par rapport et limitez les exécutions payantes. Ajoutez des figures aux rapports nouveaux ou existants, ouvrez les ressources interactives et conservez les figures en PDF. Le retrait peut être annulé.',
    de: 'Visuelle Skills kommen in Deep Research und Immersion auf dem Desktop. Wählen Sie Skills pro Bericht und begrenzen Sie kostenpflichtige Aufrufe ausdrücklich. Ergänzen Sie neue oder bestehende Berichte um interaktive Figuren und Downloads, auch im PDF. Das Entfernen lässt sich rückgängig machen.',
    pt: 'As Skills visuais chegam ao Deep Research e ao Immersion no computador. Escolhe-as por relatório e limita as chamadas pagas. Acrescenta figuras a relatórios novos ou existentes, abre recursos interativos e mantém as figuras no PDF. Podes retirar recursos e desfazer a alteração.',
    'pt-BR': 'As Skills visuais chegam ao Deep Research e ao Immersion no computador. Escolha por relatório e limite as chamadas pagas. Adicione figuras a relatórios novos ou existentes, abra recursos interativos e mantenha as figuras no PDF. Você pode remover recursos e desfazer a alteração.',
    it: 'Le Skills visive arrivano in Deep Research e Immersion su desktop. Sceglile per rapporto e limita esplicitamente le chiamate a pagamento. Aggiungi figure a rapporti nuovi o esistenti, apri risorse interattive e conserva le figure nei PDF. Puoi rimuovere risorse e annullare la modifica.',
    tr: 'Görsel Skills masaüstünde Deep Research ve Immersion’a geliyor. Her rapor için Skills seçin ve ücretli çağrılara açık bir üst sınır koyun. Yeni veya mevcut raporlara şekiller ekleyin, etkileşimli kaynakları açın ve PDF dışa aktarımlarında koruyun. Kaldırma işlemini geri alabilirsiniz.',
  },
  {
    scope: 'ai',
    es: 'Los mapas se construyen a partir de datos geográficos reales. Las Skills compatibles pueden usar límites administrativos, capas, rutas, marcadores y leyendas, con sus fuentes y atribuciones. Nodus genera un mapa vectorial descargable a partir de esos datos, sin pedir al modelo que invente fronteras o coordenadas.',
    en: 'Maps are built from real geographic data. Compatible Skills can use administrative boundaries, layers, routes, markers and legends with source attribution. Nodus produces downloadable vector maps from those data without asking the model to invent borders or coordinates.',
    fr: 'Les cartes reposent sur des données géographiques réelles. Les Skills compatibles utilisent limites administratives, couches, itinéraires et légendes avec leurs sources. Nodus produit des cartes vectorielles téléchargeables sans faire inventer les frontières au modèle.',
    de: 'Karten entstehen aus echten Geodaten. Kompatible Skills nutzen Verwaltungsgrenzen, Ebenen, Routen, Markierungen und Legenden mit Quellenangaben. Nodus erzeugt herunterladbare Vektorkarten, ohne das Modell Grenzen oder Koordinaten erfinden zu lassen.',
    pt: 'Os mapas partem de dados geográficos reais. As Skills compatíveis usam limites administrativos, camadas, rotas, marcadores e legendas com as respetivas fontes. O Nodus gera mapas vetoriais descarregáveis sem pedir ao modelo que invente fronteiras.',
    'pt-BR': 'Os mapas partem de dados geográficos reais. As Skills compatíveis usam limites administrativos, camadas, rotas, marcadores e legendas com as respectivas fontes. O Nodus gera mapas vetoriais para download sem pedir ao modelo que invente fronteiras.',
    it: 'Le mappe nascono da dati geografici reali. Le Skills compatibili usano confini amministrativi, livelli, percorsi, indicatori e legende con le relative fonti. Nodus genera mappe vettoriali scaricabili senza chiedere al modello di inventare confini.',
    tr: 'Haritalar gerçek coğrafi verilerden oluşturulur. Uyumlu Skills idari sınırları, katmanları, rotaları, işaretleri ve açıklamaları kaynaklarıyla kullanır. Nodus modelden sınır veya koordinat uydurmasını istemeden indirilebilir vektör haritaları üretir.',
  },
  {
    scope: 'ai',
    es: 'Las Skills compatibles pueden revisar si una imagen responde a tu petición. Usan miniaturas y el modelo con visión seleccionado, con un máximo explícito de llamadas de pago en los informes. Si la revisión no está disponible o no encuentra una imagen adecuada, el resultado lo indica sin presentar una imagen como verificada.',
    en: 'Compatible Skills can review whether an image fits your request. They use thumbnails and the selected vision model, with report controls limiting paid calls. If review is unavailable or finds no suitable image, the result says so instead of presenting an image as verified.',
    fr: 'Les Skills compatibles peuvent examiner la pertinence d’une image avec des miniatures et le modèle visuel choisi. Les rapports limitent les appels payants. Une vérification indisponible ou sans image adaptée est signalée clairement.',
    de: 'Kompatible Skills können Bilder anhand von Vorschaubildern mit dem gewählten Bildmodell auf Relevanz prüfen. Berichte begrenzen kostenpflichtige Aufrufe. Ist die Prüfung nicht verfügbar oder kein Bild passend, wird dies ausdrücklich angezeigt.',
    pt: 'As Skills compatíveis podem avaliar se uma imagem responde ao pedido, usando miniaturas e o modelo com visão escolhido. Os relatórios limitam chamadas pagas. Se a revisão não estiver disponível ou não encontrar uma imagem adequada, o resultado indica-o.',
    'pt-BR': 'As Skills compatíveis podem avaliar se uma imagem atende ao pedido, usando miniaturas e o modelo com visão escolhido. Os relatórios limitam chamadas pagas. Se a revisão estiver indisponível ou não encontrar uma imagem adequada, o resultado informa isso.',
    it: 'Le Skills compatibili possono valutare se un’immagine risponde alla richiesta usando miniature e il modello visivo scelto. I rapporti limitano le chiamate a pagamento. Una revisione non disponibile o senza immagini adatte viene segnalata chiaramente.',
    tr: 'Uyumlu Skills küçük resimleri ve seçilen görme modelini kullanarak bir resmin isteğe uygunluğunu değerlendirebilir. Raporlar ücretli çağrıları sınırlar. İnceleme kullanılamıyorsa veya uygun resim bulunamazsa sonuç bunu açıkça belirtir.',
  },
  {
    scope: 'ai',
    es: 'Los dibujos químicos y SVG toleran mejor las respuestas válidas. Un comentario dentro del dibujo ya no provoca que se descarte, y Chemistry Studio conserva las partes que puede representar cuando no logra verificar toda la propuesta. Las limitaciones siguen visibles y no se presentan como una validación completa.',
    en: 'Chemical drawings and SVG handle valid responses more reliably. Comments inside a drawing no longer cause rejection, and Chemistry Studio keeps the parts it can display when the whole proposal cannot be verified. Limitations remain visible rather than being presented as full validation.',
    fr: 'Les dessins chimiques et SVG acceptent mieux les réponses valides. Un commentaire ne fait plus rejeter le dessin. Chemistry Studio garde les parties représentables sans prétendre avoir vérifié toute la proposition, et affiche les limites.',
    de: 'Chemische Zeichnungen und SVG verarbeiten gültige Antworten zuverlässiger. Kommentare führen nicht mehr zur Ablehnung. Chemistry Studio behält darstellbare Teile bei, wenn sich nicht alles prüfen lässt, und zeigt die Grenzen der Prüfung weiter an.',
    pt: 'Os desenhos químicos e SVG aceitam melhor respostas válidas. Um comentário já não faz descartar o desenho. O Chemistry Studio mantém as partes representáveis quando não consegue verificar toda a proposta e continua a mostrar as limitações.',
    'pt-BR': 'Os desenhos químicos e SVG aceitam melhor respostas válidas. Um comentário não faz mais descartar o desenho. O Chemistry Studio mantém as partes representáveis quando não consegue verificar toda a proposta e continua mostrando as limitações.',
    it: 'I disegni chimici e SVG gestiscono meglio le risposte valide. Un commento non causa più lo scarto del disegno. Chemistry Studio conserva le parti rappresentabili quando non può verificare tutta la proposta e continua a indicare i limiti.',
    tr: 'Kimyasal çizimler ve SVG geçerli yanıtları daha iyi işler. Çizimdeki bir yorum artık reddedilmesine yol açmaz. Chemistry Studio tüm öneriyi doğrulayamadığında gösterebildiği kısımları korur ve sınırlamaları açıkça belirtir.',
  },
  {
    scope: 'general',
    es: 'Una búsqueda común para todos los vaults. Encuentra contenido con una consulta que combina coincidencias de texto y búsqueda semántica cuando está disponible. Filtra por los tipos de contenido propios de cada vault y guarda las búsquedas para volver a ellas.',
    en: 'One search experience across all vaults. Find content with a query combining text matches and semantic search when available. Filter by the content types supported by each vault and save searches to return to them.',
    fr: 'Une recherche commune à tous les vaults. Combinez les correspondances textuelles et la recherche sémantique lorsqu’elle est disponible. Filtrez selon les contenus du vault et enregistrez vos recherches.',
    de: 'Eine gemeinsame Suche für alle Vaults. Texttreffer werden mit semantischer Suche kombiniert, soweit verfügbar. Filtern Sie nach den Inhaltstypen des jeweiligen Vaults und speichern Sie Suchanfragen für später.',
    pt: 'Uma pesquisa comum a todos os vaults. Combina correspondências de texto e pesquisa semântica quando disponível. Filtra pelos tipos de conteúdo de cada vault e guarda as pesquisas para regressar a elas.',
    'pt-BR': 'Uma busca comum a todos os vaults. Combine correspondências de texto e busca semântica quando disponível. Filtre pelos tipos de conteúdo de cada vault e salve as buscas para voltar a elas.',
    it: 'Una ricerca comune a tutti i vault. Combina corrispondenze testuali e ricerca semantica quando disponibile. Filtra per i tipi di contenuto di ogni vault e salva le ricerche per ritrovarle.',
    tr: 'Tüm kasalarda ortak arama. Metin eşleşmelerini kullanılabildiğinde anlamsal aramayla birleştirin. Her kasanın içerik türlerine göre filtreleyin ve aramaları daha sonra dönmek üzere kaydedin.',
  },
  {
    scope: 'general',
    es: 'Más claridad en los controles y la navegación. Las acciones del grafo y el panel del Tutor mejoran sus iconos y contraste, y el selector de contexto del chat respeta el modo claro. Docencia deja de mostrar accesos a secciones todavía no disponibles. También se corrigen el centrado del botón de envío y el fondo del logotipo en claro.',
    en: 'Clearer controls and navigation. Graph actions and the Tutor panel gain improved icons and contrast, and chat context controls respect light mode. Teaching hides sections that are not available yet. The send button is centered and the logo background is corrected in light mode.',
    fr: 'Des commandes et une navigation plus claires. Les actions du graphe et le Tuteur gagnent en contraste, et le contexte du chat respecte le thème clair. Enseignement masque les sections indisponibles. Le bouton d’envoi et le fond du logo sont corrigés.',
    de: 'Übersichtlichere Bedienelemente und Navigation. Graphaktionen und Tutor erhalten bessere Symbole und Kontraste, der Chatkontext folgt dem hellen Design. Lehre blendet noch nicht verfügbare Bereiche aus. Sendeschaltfläche und Logohintergrund sind korrigiert.',
    pt: 'Controlos e navegação mais claros. As ações do grafo e o Tutor melhoram ícones e contraste, e o contexto do chat respeita o modo claro. Docência oculta secções ainda indisponíveis. Corrigidos o botão de envio e o fundo do logótipo.',
    'pt-BR': 'Controles e navegação mais claros. As ações do grafo e o Tutor melhoram ícones e contraste, e o contexto do chat respeita o modo claro. Docência oculta seções ainda indisponíveis. Corrigidos o botão de envio e o fundo do logotipo.',
    it: 'Controlli e navigazione più chiari. Le azioni del grafo e il Tutor migliorano icone e contrasto, mentre il contesto della chat rispetta il tema chiaro. Didattica nasconde sezioni non ancora disponibili. Corretti il pulsante di invio e lo sfondo del logo.',
    tr: 'Daha anlaşılır kontroller ve gezinme. Grafik işlemleri ve Eğitmen panelinin simgeleri ve kontrastı iyileştirildi. Sohbet bağlamı açık temaya uyar. Öğretim henüz kullanılmayan bölümleri gizler. Gönder düğmesi ve logo arka planı düzeltildi.',
  },
  {
    scope: 'marketplace',
    es: 'El Marketplace tiene un acceso propio desde la cabecera de Skills. Las skills y sus paquetes comparten una sola tarjeta, con su orden e identidad visual, botones más claros y errores de instalación traducidos. Es más fácil distinguir lo que tienes instalado de lo que puedes añadir.',
    en: 'The Marketplace has its own entry in the Skills header. Skills and their packages share one card with consistent ordering and visual identity, clearer buttons and translated installation errors. Installed and available items are easier to distinguish.',
    fr: 'Le Marketplace a son propre accès dans l’en-tête de Skills. Skills et paquets partagent une fiche, un ordre cohérent, des boutons plus clairs et des erreurs d’installation traduites. Les éléments installés sont plus faciles à repérer.',
    de: 'Der Marketplace hat einen eigenen Zugang im Skills-Kopfbereich. Skills und Pakete teilen eine Karte mit einheitlicher Reihenfolge, klareren Schaltflächen und übersetzten Installationsfehlern. Installierte und verfügbare Einträge sind leichter zu unterscheiden.',
    pt: 'O Marketplace tem acesso próprio no cabeçalho de Skills. Skills e pacotes partilham um cartão, com ordem e identidade visual consistentes, botões mais claros e erros de instalação traduzidos. É mais fácil identificar o que já está instalado.',
    'pt-BR': 'O Marketplace tem acesso próprio no cabeçalho de Skills. Skills e pacotes compartilham um cartão, com ordem e identidade visual consistentes, botões mais claros e erros de instalação traduzidos. É mais fácil identificar o que já está instalado.',
    it: 'Il Marketplace ha un accesso dedicato nell’intestazione di Skills. Skills e pacchetti condividono una scheda, un ordine coerente, pulsanti più chiari ed errori di installazione tradotti. Gli elementi installati sono più facili da riconoscere.',
    tr: 'Marketplace, Skills başlığında kendi girişine kavuşuyor. Skills ve paketler ortak sıralama ve görsel kimlikle tek kartta gösteriliyor. Düğmeler daha belirgin, kurulum hataları çevrilmiş ve kurulu öğeleri ayırt etmek daha kolay.',
  },
  {
    scope: 'plugin',
    es: 'Los plugins pueden mostrar modelos 3D interactivos y resultados más ricos. Explora modelos, fórmulas, gráficos, comparaciones, mapas, imágenes, audio y documentos ampliables en visores de Nodus. Los recursos locales se conservan con el resultado, y los archivos incluidos en un paquete se verifican antes de usarse.',
    en: 'Plugins can display interactive 3D models and richer results. Explore models, formulas, charts, comparisons, maps, images, audio and zoomable documents in Nodus viewers. Local resources stay with the result, and files included in a package are verified before use.',
    fr: 'Les plugins affichent des modèles 3D interactifs et des résultats enrichis. Explorez formules, graphiques, comparaisons, cartes, images, audio et documents agrandissables. Les ressources locales sont conservées et les fichiers des paquets vérifiés avant usage.',
    de: 'Plugins zeigen interaktive 3D-Modelle und reichhaltigere Ergebnisse. Erkunden Sie Formeln, Diagramme, Vergleiche, Karten, Bilder, Audio und zoombare Dokumente in Nodus. Lokale Ressourcen bleiben erhalten, Paketdateien werden vor der Nutzung geprüft.',
    pt: 'Os plugins mostram modelos 3D interativos e resultados mais ricos. Explora fórmulas, gráficos, comparações, mapas, imagens, áudio e documentos ampliáveis no Nodus. Os recursos locais mantêm-se e os ficheiros dos pacotes são verificados antes de usar.',
    'pt-BR': 'Os plugins mostram modelos 3D interativos e resultados mais ricos. Explore fórmulas, gráficos, comparações, mapas, imagens, áudio e documentos ampliáveis no Nodus. Os recursos locais são preservados e os arquivos dos pacotes são verificados antes do uso.',
    it: 'I plugin mostrano modelli 3D interattivi e risultati più ricchi. Esplora formule, grafici, confronti, mappe, immagini, audio e documenti ingrandibili in Nodus. Le risorse locali restano disponibili e i file dei pacchetti vengono verificati prima dell’uso.',
    tr: 'Eklentiler etkileşimli 3D modeller ve daha zengin sonuçlar gösterebilir. Nodus görüntüleyicilerinde formülleri, grafikleri, karşılaştırmaları, haritaları, resimleri, sesi ve yakınlaştırılabilir belgeleri inceleyin. Yerel kaynaklar korunur ve paket dosyaları kullanımdan önce doğrulanır.',
  },
  {
    scope: 'browser',
    es: 'Los marcadores del navegador ocupan menos espacio y se reconocen mejor. Las tarjetas son más compactas y recuperan los iconos de los sitios, también al editar un marcador. Las páginas de inicio y el gestor de marcadores comparten estas mejoras.',
    en: 'Browser bookmarks take less space and are easier to recognize. Cards are more compact and recover site icons, including when editing a bookmark. Start pages and the bookmark manager share these improvements.',
    fr: 'Les favoris du navigateur sont plus compacts et reconnaissables. Les cartes récupèrent les icônes des sites, y compris lors d’une modification. Les pages d’accueil et le gestionnaire de favoris partagent ces améliorations.',
    de: 'Browser-Lesezeichen brauchen weniger Platz und sind leichter erkennbar. Kompakte Karten laden Website-Symbole auch beim Bearbeiten nach. Startseiten und Lesezeichenverwaltung teilen diese Verbesserungen.',
    pt: 'Os marcadores do navegador ocupam menos espaço e reconhecem-se melhor. Os cartões são mais compactos e recuperam os ícones dos sites, também ao editar. As páginas iniciais e o gestor de marcadores partilham as melhorias.',
    'pt-BR': 'Os favoritos do navegador ocupam menos espaço e são mais fáceis de reconhecer. Os cartões são compactos e recuperam os ícones dos sites, inclusive ao editar. As páginas iniciais e o gerenciador de favoritos compartilham as melhorias.',
    it: 'I segnalibri del browser occupano meno spazio e si riconoscono meglio. Le schede sono più compatte e recuperano le icone dei siti anche durante la modifica. Le pagine iniziali e il gestore dei segnalibri condividono i miglioramenti.',
    tr: 'Tarayıcı yer imleri daha az yer kaplıyor ve daha kolay tanınıyor. Kartlar daha kompakt ve düzenleme sırasında da site simgelerini getiriyor. Başlangıç sayfaları ve yer imi yöneticisi bu iyileştirmeleri paylaşıyor.',
  },
  {
    scope: 'word',
    es: 'Las alternativas de redacción en Word respetan los espacios de la selección. Aplicar una sugerencia ya no pega palabras vecinas cuando Word incluye un espacio al seleccionar. Si la primera respuesta no aporta suficientes alternativas distintas, Nodus intenta completar la lista sin repetir las ya obtenidas.',
    en: 'Word writing alternatives preserve selection whitespace. Applying a suggestion no longer joins neighboring words when Word includes a space in the selection. If the first response provides too few distinct alternatives, Nodus tries to complete the list without repeating earlier suggestions.',
    fr: 'Les alternatives dans Word préservent les espaces de la sélection. Une suggestion ne colle plus les mots voisins. Si la première réponse ne donne pas assez d’alternatives distinctes, Nodus tente de compléter la liste sans répétition.',
    de: 'Formulierungsalternativen in Word erhalten die Leerzeichen der Auswahl. Vorschläge verbinden benachbarte Wörter nicht mehr versehentlich. Liefert die erste Antwort zu wenige unterschiedliche Alternativen, versucht Nodus die Liste ohne Wiederholungen zu ergänzen.',
    pt: 'As alternativas no Word preservam os espaços da seleção. Aplicar uma sugestão já não junta palavras vizinhas. Se a primeira resposta trouxer poucas alternativas distintas, o Nodus tenta completar a lista sem repetir as anteriores.',
    'pt-BR': 'As alternativas no Word preservam os espaços da seleção. Aplicar uma sugestão não junta mais palavras vizinhas. Se a primeira resposta trouxer poucas alternativas distintas, o Nodus tenta completar a lista sem repetir as anteriores.',
    it: 'Le alternative in Word conservano gli spazi della selezione. Applicare un suggerimento non unisce più parole vicine. Se la prima risposta offre poche alternative distinte, Nodus prova a completare la lista senza ripetizioni.',
    tr: 'Word yazım alternatifleri seçimdeki boşlukları korur. Öneri uygulamak artık komşu kelimeleri birleştirmez. İlk yanıt yeterli sayıda farklı alternatif sunmazsa Nodus önceki önerileri tekrarlamadan listeyi tamamlamayı dener.',
  },
];
