import type { ReleaseHighlight } from './releaseNotes';

/** Added since the unpublished 5.3.2 notes, including conversation file attachments. */
export const RELEASE_5_4_0_ADDITIONS: ReleaseHighlight[] = [
  {
    scope: 'ai',
    es: 'Research chat se unifica en los nueve tipos de vault. Encuéntralo en Analizar, con el mismo selector de modelo, acciones de mensaje y paneles plegables de historial y contexto. Conserva las conversaciones anteriores y las fuentes, citas y herramientas propias de cada vault.',
    en: 'Research chat is unified across all nine vault types. Find it under Analyze, with shared model controls, message actions and collapsible history and context panels. Existing conversations and each vault’s sources, citations and tools are preserved.',
    fr: 'Research chat est unifié dans les neuf types de vault. Retrouvez-le dans Analyser avec les mêmes commandes de modèle et de message, et des panneaux repliables. Les conversations, sources, citations et outils propres à chaque vault sont conservés.',
    de: 'Research chat ist in allen neun Vault-Typen vereinheitlicht. Unter Analysieren finden Sie gemeinsame Modell- und Nachrichtenaktionen sowie einklappbare Verlaufs- und Kontextbereiche. Bestehende Gespräche, Quellen, Zitate und die Werkzeuge jedes Vaults bleiben erhalten.',
    pt: 'O Research chat está unificado nos nove tipos de vault. Encontra-o em Analisar, com controlos de modelo e mensagem comuns e painéis recolhíveis de histórico e contexto. As conversas, fontes, citações e ferramentas de cada vault mantêm-se.',
    'pt-BR': 'O Research chat está unificado nos nove tipos de vault. Encontre-o em Analisar, com controles de modelo e mensagem comuns e painéis recolhíveis de histórico e contexto. As conversas, fontes, citações e ferramentas de cada vault são preservadas.',
    it: 'Research chat è unificato nei nove tipi di vault. Si trova in Analizza, con controlli comuni per modello e messaggi e pannelli richiudibili per cronologia e contesto. Conversazioni, fonti, citazioni e strumenti di ogni vault restano disponibili.',
    tr: 'Research chat dokuz kasa türünde birleşiyor. Analiz bölümünde ortak model kontrolleri, mesaj işlemleri ve daraltılabilir geçmiş ve bağlam panelleriyle açılıyor. Önceki konuşmalar ve her kasanın kaynakları, alıntıları ve araçları korunuyor.',
    'zh-CN': "Research chat在全部九种vault类型中实现统一。可在「分析」中找到它，拥有相同的模型选择器、消息操作，以及可折叠的历史记录和上下文面板。已有的对话以及每种vault各自的来源、引用和工具都会保留。",
    'zh-TW': "Research chat在全部九種vault型別中實現統一。可在「分析」中找到它，擁有相同的模型選擇器、訊息操作，以及可摺疊的歷史記錄和上下文面板。已有的對話以及每種vault各自的來源、引用和工具都會保留。",
  },
  {
    scope: 'ai',
    es: 'Elige el esfuerzo de razonamiento desde el Research chat. Los niveles disponibles se ajustan a las capacidades del proveedor y del modelo seleccionado, y se aplican a la conversación sin cambiar los ajustes de los demás chats.',
    en: 'Choose reasoning effort directly in Research chat. Available levels follow the selected provider and model’s capabilities and apply to the conversation without changing the settings of other chats.',
    fr: 'Choisissez l’effort de raisonnement dans Research chat. Les niveaux proposés suivent les capacités du fournisseur et du modèle sélectionnés, sans modifier les réglages des autres chats.',
    de: 'Wählen Sie den Denkaufwand direkt in Research chat. Die verfügbaren Stufen richten sich nach Anbieter und Modell und gelten für das Gespräch, ohne Einstellungen anderer Chats zu ändern.',
    pt: 'Escolhe o esforço de raciocínio no Research chat. Os níveis disponíveis respeitam as capacidades do fornecedor e do modelo escolhido, sem alterar as definições dos outros chats.',
    'pt-BR': 'Escolha o esforço de raciocínio no Research chat. Os níveis disponíveis respeitam as capacidades do provedor e do modelo escolhido, sem alterar as configurações dos outros chats.',
    it: 'Scegli lo sforzo di ragionamento direttamente in Research chat. I livelli disponibili rispettano le capacità del fornitore e del modello selezionati, senza cambiare le impostazioni delle altre chat.',
    tr: 'Akıl yürütme düzeyini Research chat içinden seçin. Kullanılabilir düzeyler seçilen sağlayıcı ve modelin yeteneklerine uyar ve diğer sohbetlerin ayarlarını değiştirmez.',
    'zh-CN': "可直接在Research chat中选择推理强度。可用级别取决于所选提供商和模型的能力，并仅应用于当前对话，不改变其他聊天的设置。",
    'zh-TW': "可直接在Research chat中選擇推理強度。可用級別取決於所選提供商和模型的能力，並僅應用於當前對話，不改變其他聊天的設定。",
  },
  {
    scope: 'ai',
    es: 'Acota las fuentes del corpus por autor y por obra. El nuevo selector permite buscar y combinar ambas restricciones, las guarda con la conversación y evita que fuentes excluidas vuelvan a entrar a través del historial. Si la selección no aporta evidencia, el chat lo reconoce.',
    en: 'Narrow corpus sources by author and work. Search and combine both filters, save them with the conversation and keep excluded sources from returning through history. When the selection provides no evidence, the chat acknowledges it.',
    fr: 'Limitez les sources du corpus par auteur et par œuvre. Recherchez et combinez les filtres, enregistrés avec la conversation. Les sources exclues ne reviennent pas par l’historique, et le chat signale l’absence de preuves.',
    de: 'Grenzen Sie Korpusquellen nach Autor und Werk ein. Beide Filter sind durchsuchbar, kombinierbar und werden mit dem Gespräch gespeichert. Ausgeschlossene Quellen kommen nicht über den Verlauf zurück. Fehlende Belege werden benannt.',
    pt: 'Restringe as fontes do corpus por autor e obra. Pesquisa e combina os filtros, que ficam guardados com a conversa. As fontes excluídas não regressam pelo histórico, e o chat reconhece quando faltam evidências.',
    'pt-BR': 'Restrinja as fontes do corpus por autor e obra. Pesquise e combine os filtros, que ficam salvos com a conversa. As fontes excluídas não retornam pelo histórico, e o chat reconhece quando faltam evidências.',
    it: 'Limita le fonti del corpus per autore e opera. Cerca e combina i filtri, salvati con la conversazione. Le fonti escluse non rientrano attraverso la cronologia e la chat segnala quando mancano prove.',
    tr: 'Derlem kaynaklarını yazar ve esere göre daraltın. Aranabilir filtreleri birlikte kullanın ve konuşmayla kaydedin. Dışlanan kaynaklar geçmiş üzerinden geri gelmez. Seçim kanıt sağlamıyorsa sohbet bunu belirtir.',
    'zh-CN': "按作者和文献缩小语料库来源范围。新的选择器支持搜索并组合这两种限制，将其与对话一起保存，并防止被排除的来源通过历史记录重新进入。如果所选内容无法提供证据，聊天会予以说明。",
    'zh-TW': "按作者和文獻縮小語料庫來源範圍。新的選擇器支援搜尋並組合這兩種限制，將其與對話一起儲存，並防止被排除的來源通過歷史記錄重新進入。如果所選內容無法提供證據，聊天會予以說明。",
  },
  {
    scope: 'ai',
    es: 'Guarda tus propias instrucciones para el Research chat. Crea, busca, edita y selecciona prompts dentro de cada vault para orientar el tono y la estructura de las respuestas. Puedes cambiarlos en una conversación existente sin perder su historial y volver a Default cuando quieras.',
    en: 'Save your own Research chat instructions. Create, search, edit and select prompts within each vault to guide response tone and structure. Switch prompts in an existing conversation without losing its history, or return to Default.',
    fr: 'Enregistrez vos instructions pour Research chat. Créez, recherchez, modifiez et sélectionnez des prompts dans chaque vault pour guider le ton et la structure. Changez-les sans perdre l’historique ou revenez à Default.',
    de: 'Speichern Sie eigene Anweisungen für Research chat. Erstellen, suchen und bearbeiten Sie Prompts pro Vault für Ton und Aufbau der Antworten. Wechseln Sie im laufenden Gespräch ohne Verlaufsverlust oder kehren Sie zu Default zurück.',
    pt: 'Guarda instruções próprias para o Research chat. Cria, pesquisa, edita e escolhe prompts em cada vault para orientar o tom e a estrutura. Muda de prompt sem perder o histórico ou regressa a Default.',
    'pt-BR': 'Salve instruções próprias para o Research chat. Crie, pesquise, edite e escolha prompts em cada vault para orientar o tom e a estrutura. Mude de prompt sem perder o histórico ou volte a Default.',
    it: 'Salva le tue istruzioni per Research chat. Crea, cerca, modifica e seleziona prompt in ogni vault per guidare tono e struttura. Cambia prompt senza perdere la cronologia o torna a Default.',
    tr: 'Research chat için kendi talimatlarınızı kaydedin. Her kasada yanıtların tonunu ve yapısını yönlendiren istemler oluşturun, arayın, düzenleyin ve seçin. Geçmişi kaybetmeden istem değiştirin veya Default seçeneğine dönün.',
    'zh-CN': "保存你自己的Research chat指令。可在每种vault内创建、搜索、编辑和选择提示词，以引导回答的语气和结构。你可以在已有对话中切换提示词而不丢失其历史记录，并可随时返回Default。",
    'zh-TW': "儲存你自己的Research chat指令。可在每種vault內建立、搜尋、編輯和選擇提示詞，以引導回答的語氣和結構。你可以在已有對話中切換提示詞而不丟失其歷史記錄，並可隨時返回Default。",
  },
  {
    scope: 'ai',
    es: 'Adjunta archivos al Research chat con el botón + del cuadro de texto o arrastrándolos a la ventana. Lee DOC, DOCX, PDF, hojas de cálculo, CSV, XML, imágenes y otros formatos compatibles usando el proveedor y modelo elegidos, con visión cuando sea necesaria. Los adjuntos se conservan con la conversación y se borran al eliminarla. Sus tarjetas tienen contornos legibles en claro y oscuro y usan el acento del vault.',
    en: 'Attach files to Research chat with the textbox’s + button or by dropping them into the window. Read DOC, DOCX, PDF, spreadsheets, CSV, XML, images and other supported formats with your chosen provider and model, using vision when needed. Files stay with the conversation and are deleted with it. Cards have clear light and dark outlines and use the vault accent.',
    fr: 'Joignez des fichiers dans Research chat avec le bouton + ou par glisser-déposer. DOC, DOCX, PDF, tableurs, CSV, XML, images et autres formats pris en charge utilisent le modèle choisi, avec vision si nécessaire. Les fichiers suivent la conversation et sa suppression. Leurs cartes restent lisibles dans les deux thèmes et suivent l’accent du vault.',
    de: 'Hängen Sie Dateien in Research chat über + oder per Drag-and-drop an. DOC, DOCX, PDF, Tabellen, CSV, XML, Bilder und weitere unterstützte Formate nutzen den gewählten Anbieter und das Modell, bei Bedarf mit Bildverständnis. Dateien bleiben beim Gespräch und werden mit ihm gelöscht. Karten sind in beiden Designs klar umrandet und nutzen den Vault-Akzent.',
    pt: 'Anexa ficheiros ao Research chat com + ou arrastando-os para a janela. DOC, DOCX, PDF, folhas de cálculo, CSV, XML, imagens e outros formatos compatíveis usam o fornecedor e modelo escolhidos, com visão quando necessária. Os ficheiros acompanham a conversa e são eliminados com ela. Os cartões têm contornos legíveis nos dois temas e usam o destaque do vault.',
    'pt-BR': 'Anexe arquivos ao Research chat com + ou arrastando-os para a janela. DOC, DOCX, PDF, planilhas, CSV, XML, imagens e outros formatos compatíveis usam o provedor e modelo escolhidos, com visão quando necessária. Os arquivos acompanham a conversa e são excluídos com ela. Os cartões têm contornos legíveis nos dois temas e usam o destaque do vault.',
    it: 'Allega file a Research chat con + o trascinandoli nella finestra. DOC, DOCX, PDF, fogli di calcolo, CSV, XML, immagini e altri formati supportati usano fornitore e modello scelti, con visione quando necessaria. I file restano con la conversazione e vengono eliminati con essa. Le schede hanno bordi leggibili nei due temi e usano l’accento del vault.',
    tr: 'Research chat içine + düğmesiyle veya sürükleyerek dosya ekleyin. DOC, DOCX, PDF, tablolar, CSV, XML, resimler ve desteklenen diğer biçimler seçtiğiniz sağlayıcı ve modeli, gerektiğinde görme yeteneğini kullanır. Dosyalar konuşmayla saklanır ve silinir. Kartlar açık ve koyu temada belirgin kenarlara sahiptir ve kasanın vurgu rengini kullanır.',
    'zh-CN': "通过文本框的+按钮或把文件拖入窗口，即可向Research chat添加附件。使用所选的提供商和模型读取DOC、DOCX、PDF、电子表格、CSV、XML、图像和其他受支持的格式，需要时启用视觉能力。附件会随对话保留，并在删除对话时一并删除。其卡片在浅色和深色下都有清晰的轮廓，并使用vault的强调色。",
    'zh-TW': "通過文本框的+按鈕或把檔案拖入視窗，即可向Research chat新增附件。使用所選的提供商和模型讀取DOC、DOCX、PDF、電子表格、CSV、XML、影像和其他受支援的格式，需要時啟用視覺能力。附件會隨對話保留，並在刪除對話時一併刪除。其卡片在淺色和深色下都有清晰的輪廓，並使用vault的強調色。",
  },
  {
    scope: 'ai',
    es: 'Leer y detener una respuesta resulta más cómodo. El Research chat respeta tu posición cuando subes a leer, y las vistas previas de las citas vuelven a abrirse correctamente. Al detener una respuesta, el texto ya recibido se conserva en el historial en lugar de desaparecer.',
    en: 'Reading and stopping answers is smoother. Research chat respects your position when you scroll up, and citation previews open correctly again. Stopping an answer preserves the text already received in history instead of making it disappear.',
    fr: 'La lecture et l’arrêt des réponses sont plus confortables. Research chat respecte votre position de lecture et les aperçus de citations s’ouvrent correctement. Arrêter une réponse conserve le texte déjà reçu dans l’historique.',
    de: 'Antworten lassen sich angenehmer lesen und stoppen. Research chat behält Ihre Leseposition beim Hochscrollen bei und öffnet Zitatvorschauen korrekt. Beim Stoppen bleibt der bereits empfangene Text im Verlauf erhalten.',
    pt: 'Ler e parar respostas é mais cómodo. O Research chat respeita a posição de leitura e abre corretamente as pré-visualizações das citações. Ao parar uma resposta, o texto recebido mantém-se no histórico.',
    'pt-BR': 'Ler e parar respostas ficou mais confortável. O Research chat respeita a posição de leitura e abre corretamente as prévias das citações. Ao parar uma resposta, o texto recebido permanece no histórico.',
    it: 'Leggere e interrompere le risposte è più comodo. Research chat rispetta la posizione di lettura e apre correttamente le anteprime delle citazioni. Interrompendo una risposta, il testo già ricevuto resta nella cronologia.',
    tr: 'Yanıtları okumak ve durdurmak daha rahat. Research chat yukarı kaydırdığınızda okuma konumunuzu korur ve alıntı önizlemeleri doğru açılır. Yanıt durdurulduğunda alınan metin kaybolmak yerine geçmişte kalır.',
    'zh-CN': "阅读和停止回答更加顺手。当你向上滚动阅读时，Research chat会保持你的位置，引用预览也能正常重新打开。停止回答时，已接收的文本会保留在历史记录中，而不是消失。",
    'zh-TW': "閱讀和停止回答更加順手。當你向上滾動閱讀時，Research chat會保持你的位置，引用預覽也能正常重新開啟。停止回答時，已接收的文本會保留在歷史記錄中，而不是消失。",
  },
  {
    scope: 'ai',
    es: 'Las Skills visuales llegan a Deep Research e Immersion en escritorio. Elige las que puede usar cada informe y limita sus ejecuciones, con un máximo explícito para las de pago. Añade figuras a informes nuevos o existentes, abre sus recursos interactivos, descarga los resultados y conserva las figuras al exportar a PDF. Puedes retirar los recursos y deshacer el cambio.',
    en: 'Visual Skills come to desktop Deep Research and Immersion. Choose Skills per report and limit their runs, with an explicit ceiling for paid calls. Add figures to new or existing reports, open interactive resources, download results and keep figures in PDF exports. Remove resources and undo the change.',
    fr: 'Les Skills visuelles arrivent dans Deep Research et Immersion sur ordinateur. Choisissez-les par rapport et limitez les exécutions payantes. Ajoutez des figures aux rapports nouveaux ou existants, ouvrez les ressources interactives et conservez les figures en PDF. Le retrait peut être annulé.',
    de: 'Visuelle Skills kommen in Deep Research und Immersion auf dem Desktop. Wählen Sie Skills pro Bericht und begrenzen Sie kostenpflichtige Aufrufe ausdrücklich. Ergänzen Sie neue oder bestehende Berichte um interaktive Figuren und Downloads, auch im PDF. Das Entfernen lässt sich rückgängig machen.',
    pt: 'As Skills visuais chegam ao Deep Research e ao Immersion no computador. Escolhe-as por relatório e limita as chamadas pagas. Acrescenta figuras a relatórios novos ou existentes, abre recursos interativos e mantém as figuras no PDF. Podes retirar recursos e desfazer a alteração.',
    'pt-BR': 'As Skills visuais chegam ao Deep Research e ao Immersion no computador. Escolha por relatório e limite as chamadas pagas. Adicione figuras a relatórios novos ou existentes, abra recursos interativos e mantenha as figuras no PDF. Você pode remover recursos e desfazer a alteração.',
    it: 'Le Skills visive arrivano in Deep Research e Immersion su desktop. Sceglile per rapporto e limita esplicitamente le chiamate a pagamento. Aggiungi figure a rapporti nuovi o esistenti, apri risorse interattive e conserva le figure nei PDF. Puoi rimuovere risorse e annullare la modifica.',
    tr: 'Görsel Skills masaüstünde Deep Research ve Immersion’a geliyor. Her rapor için Skills seçin ve ücretli çağrılara açık bir üst sınır koyun. Yeni veya mevcut raporlara şekiller ekleyin, etkileşimli kaynakları açın ve PDF dışa aktarımlarında koruyun. Kaldırma işlemini geri alabilirsiniz.',
    'zh-CN': "可视化Skill登陆桌面版Deep Research和Immersion。可为每份报告选择可用的Skill并限制其执行次数，付费调用设有明确上限。为新建或已有报告添加图形，打开其交互式资源，下载结果，并在导出为PDF时保留图形。你可以移除资源并撤销更改。",
    'zh-TW': "視覺化Skill登陸桌面版Deep Research和Immersion。可為每份報告選擇可用的Skill並限制其執行次數，付費呼叫設有明確上限。為新建或已有報告新增圖形，開啟其互動式資源，下載結果，並在匯出為PDF時保留圖形。你可以移除資源並撤銷更改。",
  },
  {
    scope: 'ai',
    es: 'Los mapas se construyen a partir de datos geográficos reales. Las Skills compatibles pueden usar límites administrativos, capas, rutas, marcadores y leyendas, con sus fuentes y atribuciones. Nodus genera un mapa vectorial descargable a partir de esos datos, sin pedir al modelo que invente fronteras o coordenadas.',
    en: 'Maps are built from real geographic data. Compatible Skills can use administrative boundaries, layers, routes, markers and legends with source attribution. Nodus produces downloadable vector maps from those data without asking the model to invent borders or coordinates.',
    fr: 'Les cartes reposent sur des données géographiques réelles. Les Skills compatibles utilisent limites administratives, couches, itinéraires et légendes avec leurs sources. Nodus produit des cartes vectorielles téléchargeables sans faire inventer les frontières au modèle.',
    de: 'Karten entstehen aus echten Geodaten. Kompatible Skills nutzen Verwaltungsgrenzen, Ebenen, Routen, Markierungen und Legenden mit Quellenangaben. Nodus erzeugt herunterladbare Vektorkarten, ohne das Modell Grenzen oder Koordinaten erfinden zu lassen.',
    pt: 'Os mapas partem de dados geográficos reais. As Skills compatíveis usam limites administrativos, camadas, rotas, marcadores e legendas com as respetivas fontes. O Nodus gera mapas vetoriais descarregáveis sem pedir ao modelo que invente fronteiras.',
    'pt-BR': 'Os mapas partem de dados geográficos reais. As Skills compatíveis usam limites administrativos, camadas, rotas, marcadores e legendas com as respectivas fontes. O Nodus gera mapas vetoriais para download sem pedir ao modelo que invente fronteiras.',
    it: 'Le mappe nascono da dati geografici reali. Le Skills compatibili usano confini amministrativi, livelli, percorsi, indicatori e legende con le relative fonti. Nodus genera mappe vettoriali scaricabili senza chiedere al modello di inventare confini.',
    tr: 'Haritalar gerçek coğrafi verilerden oluşturulur. Uyumlu Skills idari sınırları, katmanları, rotaları, işaretleri ve açıklamaları kaynaklarıyla kullanır. Nodus modelden sınır veya koordinat uydurmasını istemeden indirilebilir vektör haritaları üretir.',
    'zh-CN': "地图基于真实地理数据构建。兼容的Skill可以使用行政边界、图层、路线、标记和图例，并附来源与归属信息。Nodus会根据这些数据生成可下载的矢量地图，而不会要求模型凭空编造边界或坐标。",
    'zh-TW': "地圖基於真實地理資料構建。相容的Skill可以使用行政邊界、圖層、路線、標記和圖例，並附來源與歸屬資訊。Nodus會根據這些資料生成可下載的向量地圖，而不會要求模型憑空編造邊界或座標。",
  },
  {
    scope: 'ai',
    es: 'Las Skills compatibles pueden revisar si una imagen responde a tu petición. Usan miniaturas y el modelo con visión seleccionado, con un máximo explícito de llamadas de pago en los informes. Si la revisión no está disponible o no encuentra una imagen adecuada, el resultado lo indica sin presentar una imagen como verificada.',
    en: 'Compatible Skills can review whether an image fits your request. They use thumbnails and the selected vision model, with report controls limiting paid calls. If review is unavailable or finds no suitable image, the result says so instead of presenting an image as verified.',
    fr: 'Les Skills compatibles peuvent examiner la pertinence d’une image avec des miniatures et le modèle visuel choisi. Les rapports limitent les appels payants. Une vérification indisponible ou sans image adaptée est signalée clairement.',
    de: 'Kompatible Skills können Bilder anhand von Vorschaubildern mit dem gewählten Bildmodell auf Relevanz prüfen. Berichte begrenzen kostenpflichtige Aufrufe. Ist die Prüfung nicht verfügbar oder kein Bild passend, wird dies ausdrücklich angezeigt.',
    pt: 'As Skills compatíveis podem avaliar se uma imagem responde ao pedido, usando miniaturas e o modelo com visão escolhido. Os relatórios limitam chamadas pagas. Se a revisão não estiver disponível ou não encontrar uma imagem adequada, o resultado indica-o.',
    'pt-BR': 'As Skills compatíveis podem avaliar se uma imagem atende ao pedido, usando miniaturas e o modelo com visão escolhido. Os relatórios limitam chamadas pagas. Se a revisão estiver indisponível ou não encontrar uma imagem adequada, o resultado informa isso.',
    it: 'Le Skills compatibili possono valutare se un’immagine risponde alla richiesta usando miniature e il modello visivo scelto. I rapporti limitano le chiamate a pagamento. Una revisione non disponibile o senza immagini adatte viene segnalata chiaramente.',
    tr: 'Uyumlu Skills küçük resimleri ve seçilen görme modelini kullanarak bir resmin isteğe uygunluğunu değerlendirebilir. Raporlar ücretli çağrıları sınırlar. İnceleme kullanılamıyorsa veya uygun resim bulunamazsa sonuç bunu açıkça belirtir.',
    'zh-CN': "兼容的Skill可以检查图片是否符合你的要求。它们使用缩略图和所选的视觉模型，报告中付费调用设有明确上限。如果审核不可用或未找到合适的图片，结果会予以说明，而不会把某张图片呈现为已核实。",
    'zh-TW': "相容的Skill可以檢查圖片是否符合你的要求。它們使用縮圖和所選的視覺模型，報告中付費呼叫設有明確上限。如果稽核不可用或未找到合適的圖片，結果會予以說明，而不會把某張圖片呈現為已核實。",
  },
  {
    scope: 'ai',
    es: 'Los dibujos químicos y SVG toleran mejor las respuestas válidas. Un comentario dentro del dibujo ya no provoca que se descarte, y Chemistry Studio conserva las partes que puede representar cuando no logra verificar toda la propuesta. Las limitaciones siguen visibles y no se presentan como una validación completa.',
    en: 'Chemical drawings and SVG handle valid responses more reliably. Comments inside a drawing no longer cause rejection, and Chemistry Studio keeps the parts it can display when the whole proposal cannot be verified. Limitations remain visible rather than being presented as full validation.',
    fr: 'Les dessins chimiques et SVG acceptent mieux les réponses valides. Un commentaire ne fait plus rejeter le dessin. Chemistry Studio garde les parties représentables sans prétendre avoir vérifié toute la proposition, et affiche les limites.',
    de: 'Chemische Zeichnungen und SVG verarbeiten gültige Antworten zuverlässiger. Kommentare führen nicht mehr zur Ablehnung. Chemistry Studio behält darstellbare Teile bei, wenn sich nicht alles prüfen lässt, und zeigt die Grenzen der Prüfung weiter an.',
    pt: 'Os desenhos químicos e SVG aceitam melhor respostas válidas. Um comentário já não faz descartar o desenho. O Chemistry Studio mantém as partes representáveis quando não consegue verificar toda a proposta e continua a mostrar as limitações.',
    'pt-BR': 'Os desenhos químicos e SVG aceitam melhor respostas válidas. Um comentário não faz mais descartar o desenho. O Chemistry Studio mantém as partes representáveis quando não consegue verificar toda a proposta e continua mostrando as limitações.',
    it: 'I disegni chimici e SVG gestiscono meglio le risposte valide. Un commento non causa più lo scarto del disegno. Chemistry Studio conserva le parti rappresentabili quando non può verificare tutta la proposta e continua a indicare i limiti.',
    tr: 'Kimyasal çizimler ve SVG geçerli yanıtları daha iyi işler. Çizimdeki bir yorum artık reddedilmesine yol açmaz. Chemistry Studio tüm öneriyi doğrulayamadığında gösterebildiği kısımları korur ve sınırlamaları açıkça belirtir.',
    'zh-CN': "化学绘图和SVG对有效响应的容忍度更高。绘图内部的注释不再导致其被丢弃，当无法验证整个方案时，Chemistry Studio会保留能够呈现的部分。局限仍然可见，不会被当作完整验证。",
    'zh-TW': "化學繪圖和SVG對有效響應的容忍度更高。繪圖內部的註釋不再導致其被丟棄，當無法驗證整個方案時，Chemistry Studio會保留能夠呈現的部分。侷限仍然可見，不會被當作完整驗證。",
  },
  {
    scope: 'general',
    es: 'Una búsqueda común para todos los vaults. Encuentra contenido con una consulta que combina coincidencias de texto y búsqueda semántica cuando está disponible. Filtra por los tipos de contenido propios de cada vault y guarda las búsquedas para volver a ellas.',
    en: 'One search experience across all vaults. Find content with a query combining text matches and semantic search when available. Filter by the content types supported by each vault and save searches to return to them.',
    fr: 'Une recherche commune à tous les vaults. Combinez les correspondances textuelles et la recherche sémantique lorsqu’elle est disponible. Filtrez selon les contenus du vault et enregistrez vos recherches.',
    de: 'Eine gemeinsame Suche für alle Vaults. Texttreffer werden mit semantischer Suche kombiniert, soweit verfügbar. Filtern Sie nach den Inhaltstypen des jeweiligen Vaults und speichern Sie Suchanfragen für später.',
    pt: 'Uma pesquisa comum a todos os vaults. Combina correspondências de texto e pesquisa semântica quando disponível. Filtra pelos tipos de conteúdo de cada vault e guarda as pesquisas para regressar a elas.',
    'pt-BR': 'Uma busca comum a todos os vaults. Combine correspondências de texto e busca semântica quando disponível. Filtre pelos tipos de conteúdo de cada vault e salve as buscas para voltar a elas.',
    it: 'Una ricerca comune a tutti i vault. Combina corrispondenze testuali e ricerca semantica quando disponibile. Filtra per i tipi di contenuto di ogni vault e salva le ricerche per ritrovarle.',
    tr: 'Tüm kasalarda ortak arama. Metin eşleşmelerini kullanılabildiğinde anlamsal aramayla birleştirin. Her kasanın içerik türlerine göre filtreleyin ve aramaları daha sonra dönmek üzere kaydedin.',
    'zh-CN': "为所有vault提供统一的搜索。使用结合文本匹配和语义搜索（在可用时）的查询查找内容。按各vault特有的内容类型筛选，并保存搜索以便再次使用。",
    'zh-TW': "為所有vault提供統一的搜尋。使用結合文本匹配和語義搜尋（在可用時）的查詢查詢內容。按各vault特有的內容型別篩選，並儲存搜尋以便再次使用。",
  },
  {
    scope: 'general',
    es: 'Más claridad en los controles y la navegación. Las acciones del grafo y el panel del Tutor mejoran sus iconos y contraste, y el selector de contexto del chat respeta el modo claro. Docencia deja de mostrar accesos a secciones todavía no disponibles. También se corrigen el centrado del botón de envío y el fondo del logotipo en claro.',
    en: 'Clearer controls and navigation. Graph actions and the Tutor panel gain improved icons and contrast, and chat context controls respect light mode. Teaching hides sections that are not available yet. The send button is centered and the logo background is corrected in light mode.',
    fr: 'Des commandes et une navigation plus claires. Les actions du graphe et le Tuteur gagnent en contraste, et le contexte du chat respecte le thème clair. Enseignement masque les sections indisponibles. Le bouton d’envoi et le fond du logo sont corrigés.',
    de: 'Übersichtlichere Bedienelemente und Navigation. Graphaktionen und Tutor erhalten bessere Symbole und Kontraste, der Chatkontext folgt dem hellen Design. Lehre blendet noch nicht verfügbare Bereiche aus. Sendeschaltfläche und Logohintergrund sind korrigiert.',
    pt: 'Controlos e navegação mais claros. As ações do grafo e o Tutor melhoram ícones e contraste, e o contexto do chat respeita o modo claro. Docência oculta secções ainda indisponíveis. Corrigidos o botão de envio e o fundo do logótipo.',
    'pt-BR': 'Controles e navegação mais claros. As ações do grafo e o Tutor melhoram ícones e contraste, e o contexto do chat respeita o modo claro. Docência oculta seções ainda indisponíveis. Corrigidos o botão de envio e o fundo do logotipo.',
    it: 'Controlli e navigazione più chiari. Le azioni del grafo e il Tutor migliorano icone e contrasto, mentre il contesto della chat rispetta il tema chiaro. Didattica nasconde sezioni non ancora disponibili. Corretti il pulsante di invio e lo sfondo del logo.',
    tr: 'Daha anlaşılır kontroller ve gezinme. Grafik işlemleri ve Eğitmen panelinin simgeleri ve kontrastı iyileştirildi. Sohbet bağlamı açık temaya uyar. Öğretim henüz kullanılmayan bölümleri gizler. Gönder düğmesi ve logo arka planı düzeltildi.',
    'zh-CN': "控件与导航更加清晰。图谱操作和Tutor面板的图标与对比度得到改善，聊天上下文选择器遵循浅色模式。教学不再显示尚不可用的版块入口。还修正了发送按钮的居中和浅色模式下标志的背景。",
    'zh-TW': "控制元件與導航更加清晰。圖譜操作和Tutor面板的圖示與對比度得到改善，聊天上下文選擇器遵循淺色模式。教學不再顯示尚不可用的版塊入口。還修正了傳送按鈕的居中和淺色模式下標誌的背景。",
  },
  {
    scope: 'marketplace',
    es: 'El Marketplace tiene un acceso propio desde la cabecera de Skills. Las skills y sus paquetes comparten una sola tarjeta, con su orden e identidad visual, botones más claros y errores de instalación traducidos. Es más fácil distinguir lo que tienes instalado de lo que puedes añadir.',
    en: 'The Marketplace has its own entry in the Skills header. Skills and their packages share one card with consistent ordering and visual identity, clearer buttons and translated installation errors. Installed and available items are easier to distinguish.',
    fr: 'Le Marketplace a son propre accès dans l’en-tête de Skills. Skills et paquets partagent une fiche, un ordre cohérent, des boutons plus clairs et des erreurs d’installation traduites. Les éléments installés sont plus faciles à repérer.',
    de: 'Der Marketplace hat einen eigenen Zugang im Skills-Kopfbereich. Skills und Pakete teilen eine Karte mit einheitlicher Reihenfolge, klareren Schaltflächen und übersetzten Installationsfehlern. Installierte und verfügbare Einträge sind leichter zu unterscheiden.',
    pt: 'O Marketplace tem acesso próprio no cabeçalho de Skills. Skills e pacotes partilham um cartão, com ordem e identidade visual consistentes, botões mais claros e erros de instalação traduzidos. É mais fácil identificar o que já está instalado.',
    'pt-BR': 'O Marketplace tem acesso próprio no cabeçalho de Skills. Skills e pacotes compartilham um cartão, com ordem e identidade visual consistentes, botões mais claros e erros de instalação traduzidos. É mais fácil identificar o que já está instalado.',
    it: 'Il Marketplace ha un accesso dedicato nell’intestazione di Skills. Skills e pacchetti condividono una scheda, un ordine coerente, pulsanti più chiari ed errori di installazione tradotti. Gli elementi installati sono più facili da riconoscere.',
    tr: 'Marketplace, Skills başlığında kendi girişine kavuşuyor. Skills ve paketler ortak sıralama ve görsel kimlikle tek kartta gösteriliyor. Düğmeler daha belirgin, kurulum hataları çevrilmiş ve kurulu öğeleri ayırt etmek daha kolay.',
    'zh-CN': "Marketplace在Skills页首有了独立入口。Skill及其包共用一张卡片，具有统一的排序和视觉标识、更清晰的按钮，以及已翻译的安装错误。更容易区分已安装的内容和可以添加的内容。",
    'zh-TW': "Marketplace在Skills頁首有了獨立入口。Skill及其包共用一張卡片，具有統一的排序和視覺標識、更清晰的按鈕，以及已翻譯的安裝錯誤。更容易區分已安裝的內容和可以新增的內容。",
  },
  {
    scope: 'plugin',
    es: 'Los plugins pueden mostrar modelos 3D interactivos y resultados más ricos. Explora modelos, fórmulas, gráficos, comparaciones, mapas, imágenes, audio y documentos ampliables en visores de Nodus. Los recursos locales se conservan con el resultado, y los archivos incluidos en un paquete se verifican antes de usarse.',
    en: 'Plugins can display interactive 3D models and richer results. Explore models, formulas, charts, comparisons, maps, images, audio and zoomable documents in Nodus viewers. Local resources stay with the result, and files included in a package are verified before use.',
    fr: 'Les plugins affichent des modèles 3D interactifs et des résultats enrichis. Explorez formules, graphiques, comparaisons, cartes, images, audio et documents agrandissables. Les ressources locales sont conservées et les fichiers des paquets vérifiés avant usage.',
    de: 'Plugins zeigen interaktive 3D-Modelle und reichhaltigere Ergebnisse. Erkunden Sie Formeln, Diagramme, Vergleiche, Karten, Bilder, Audio und zoombare Dokumente in Nodus. Lokale Ressourcen bleiben erhalten, Paketdateien werden vor der Nutzung geprüft.',
    pt: 'Os plugins mostram modelos 3D interativos e resultados mais ricos. Explora fórmulas, gráficos, comparações, mapas, imagens, áudio e documentos ampliáveis no Nodus. Os recursos locais mantêm-se e os ficheiros dos pacotes são verificados antes de usar.',
    'pt-BR': 'Os plugins mostram modelos 3D interativos e resultados mais ricos. Explore fórmulas, gráficos, comparações, mapas, imagens, áudio e documentos ampliáveis no Nodus. Os recursos locais são preservados e os arquivos dos pacotes são verificados antes do uso.',
    it: 'I plugin mostrano modelli 3D interattivi e risultati più ricchi. Esplora formule, grafici, confronti, mappe, immagini, audio e documenti ingrandibili in Nodus. Le risorse locali restano disponibili e i file dei pacchetti vengono verificati prima dell’uso.',
    tr: 'Eklentiler etkileşimli 3D modeller ve daha zengin sonuçlar gösterebilir. Nodus görüntüleyicilerinde formülleri, grafikleri, karşılaştırmaları, haritaları, resimleri, sesi ve yakınlaştırılabilir belgeleri inceleyin. Yerel kaynaklar korunur ve paket dosyaları kullanımdan önce doğrulanır.',
    'zh-CN': "插件可以显示交互式3D模型和更丰富的结果。在Nodus查看器中浏览模型、公式、图表、对比、地图、图像、音频和可缩放文档。本地资源会随结果保留，包中包含的文件在使用前会经过验证。",
    'zh-TW': "外掛可以顯示互動式3D模型和更豐富的結果。在Nodus檢視器中瀏覽模型、公式、圖表、對比、地圖、影像、音訊和可縮放文件。本地資源會隨結果保留，包中包含的檔案在使用前會經過驗證。",
  },
  {
    scope: 'browser',
    es: 'Los marcadores del navegador ocupan menos espacio y se reconocen mejor. Las tarjetas son más compactas y recuperan los iconos de los sitios, también al editar un marcador. Las páginas de inicio y el gestor de marcadores comparten estas mejoras.',
    en: 'Browser bookmarks take less space and are easier to recognize. Cards are more compact and recover site icons, including when editing a bookmark. Start pages and the bookmark manager share these improvements.',
    fr: 'Les favoris du navigateur sont plus compacts et reconnaissables. Les cartes récupèrent les icônes des sites, y compris lors d’une modification. Les pages d’accueil et le gestionnaire de favoris partagent ces améliorations.',
    de: 'Browser-Lesezeichen brauchen weniger Platz und sind leichter erkennbar. Kompakte Karten laden Website-Symbole auch beim Bearbeiten nach. Startseiten und Lesezeichenverwaltung teilen diese Verbesserungen.',
    pt: 'Os marcadores do navegador ocupam menos espaço e reconhecem-se melhor. Os cartões são mais compactos e recuperam os ícones dos sites, também ao editar. As páginas iniciais e o gestor de marcadores partilham as melhorias.',
    'pt-BR': 'Os favoritos do navegador ocupam menos espaço e são mais fáceis de reconhecer. Os cartões são compactos e recuperam os ícones dos sites, inclusive ao editar. As páginas iniciais e o gerenciador de favoritos compartilham as melhorias.',
    it: 'I segnalibri del browser occupano meno spazio e si riconoscono meglio. Le schede sono più compatte e recuperano le icone dei siti anche durante la modifica. Le pagine iniziali e il gestore dei segnalibri condividono i miglioramenti.',
    tr: 'Tarayıcı yer imleri daha az yer kaplıyor ve daha kolay tanınıyor. Kartlar daha kompakt ve düzenleme sırasında da site simgelerini getiriyor. Başlangıç sayfaları ve yer imi yöneticisi bu iyileştirmeleri paylaşıyor.',
    'zh-CN': "浏览器书签占用更少空间，也更容易识别。卡片更紧凑，并恢复了网站图标，编辑书签时也是如此。起始页和书签管理器都享有这些改进。",
    'zh-TW': "瀏覽器書籤佔用更少空間，也更容易識別。卡片更緊湊，並恢復了網站圖示，編輯書籤時也是如此。起始頁和書籤管理器都享有這些改進。",
  },
  {
    scope: 'word',
    es: 'Las alternativas de redacción en Word respetan los espacios de la selección. Aplicar una sugerencia ya no pega palabras vecinas cuando Word incluye un espacio al seleccionar. Si la primera respuesta no aporta suficientes alternativas distintas, Nodus intenta completar la lista sin repetir las ya obtenidas.',
    en: 'Word writing alternatives preserve selection whitespace. Applying a suggestion no longer joins neighboring words when Word includes a space in the selection. If the first response provides too few distinct alternatives, Nodus tries to complete the list without repeating earlier suggestions.',
    fr: 'Les alternatives dans Word préservent les espaces de la sélection. Une suggestion ne colle plus les mots voisins. Si la première réponse ne donne pas assez d’alternatives distinctes, Nodus tente de compléter la liste sans répétition.',
    de: 'Formulierungsalternativen in Word erhalten die Leerzeichen der Auswahl. Vorschläge verbinden benachbarte Wörter nicht mehr versehentlich. Liefert die erste Antwort zu wenige unterschiedliche Alternativen, versucht Nodus die Liste ohne Wiederholungen zu ergänzen.',
    pt: 'As alternativas no Word preservam os espaços da seleção. Aplicar uma sugestão já não junta palavras vizinhas. Se a primeira resposta trouxer poucas alternativas distintas, o Nodus tenta completar a lista sem repetir as anteriores.',
    'pt-BR': 'As alternativas no Word preservam os espaços da seleção. Aplicar uma sugestão não junta mais palavras vizinhas. Se a primeira resposta trouxer poucas alternativas distintas, o Nodus tenta completar a lista sem repetir as anteriores.',
    it: 'Le alternative in Word conservano gli spazi della selezione. Applicare un suggerimento non unisce più parole vicine. Se la prima risposta offre poche alternative distinte, Nodus prova a completare la lista senza ripetizioni.',
    tr: 'Word yazım alternatifleri seçimdeki boşlukları korur. Öneri uygulamak artık komşu kelimeleri birleştirmez. İlk yanıt yeterli sayıda farklı alternatif sunmazsa Nodus önceki önerileri tekrarlamadan listeyi tamamlamayı dener.',
    'zh-CN': "Word中的写作备选会保留所选内容的空格。当Word在选取时包含空格，应用建议不再把相邻词语粘在一起。如果第一次响应提供的不同备选不足，Nodus会尝试补全列表而不重复已有的建议。",
    'zh-TW': "Word中的寫作備選會保留所選內容的空格。當Word在選取時包含空格，應用建議不再把相鄰詞語粘在一起。如果第一次響應提供的不同備選不足，Nodus會嘗試補全列表而不重複已有的建議。",
  },
];
