import type { ReleaseHighlight } from './releaseNotes';

/**
 * v5.4.2: the rebuilt Study question bank with Anki and Moodle interchange, Markdown
 * and LaTeX on every question and flashcard surface, seven new prompt languages, the
 * unified Marketplace catalogue and the fixes merged since 5.4.1. Keep the IT/TR
 * arrays aligned with this order: they are matched by index.
 */
export const RELEASE_5_4_2_HIGHLIGHTS: ReleaseHighlight[] = [
  {
    scope: 'estudio',
    es: 'El banco de preguntas de Estudio se reconstruye para trabajar en volumen. Preguntas y tarjetas viven en dos pestañas, con búsqueda y filtros por asignatura, tema, nivel cognitivo, fuente, material, documento, etiqueta o colección, ordenación y selección múltiple. Aplica estado, dificultad, categoría, etiquetas, colección y repaso a una selección entera, y crea, edita o borra cada tarjeta con sus propias acciones de repaso espaciado.',
    en: 'The Study question bank is rebuilt for working in volume. Questions and flashcards live in two tabs, with search and filters by subject, topic, cognitive level, source, material, document, tag or collection, sorting and multi-select. Apply status, difficulty, category, tags, collection and review state to a whole selection, and create, edit or delete each flashcard with its own spaced-repetition actions.',
    fr: 'La banque de questions d’Étude est reconstruite pour le travail en volume. Questions et cartes vivent dans deux onglets, avec recherche et filtres par matière, thème, niveau cognitif, source, matériel, document, étiquette ou collection, tri et sélection multiple. Appliquez statut, difficulté, catégorie, étiquettes, collection et état de révision à une sélection entière, et créez, modifiez ou supprimez chaque carte avec ses propres actions de révision espacée.',
    de: 'Die Fragenbank von Studium wird für die Arbeit in großem Umfang neu aufgebaut. Fragen und Karteikarten liegen in zwei Registerkarten, mit Suche und Filtern nach Fach, Thema, kognitiver Stufe, Quelle, Material, Dokument, Tag oder Sammlung, Sortierung und Mehrfachauswahl. Status, Schwierigkeit, Kategorie, Tags, Sammlung und Wiederholungsstand lassen sich auf eine ganze Auswahl anwenden. Jede Karteikarte wird mit ihren eigenen Aktionen für verteilte Wiederholung erstellt, bearbeitet oder gelöscht.',
    pt: 'O banco de perguntas do Estudo é reconstruído para trabalhar em volume. Perguntas e cartões vivem em dois separadores, com pesquisa e filtros por disciplina, tema, nível cognitivo, fonte, material, documento, etiqueta ou coleção, ordenação e seleção múltipla. Aplica estado, dificuldade, categoria, etiquetas, coleção e revisão a uma seleção inteira, e cria, edita ou elimina cada cartão com as suas próprias ações de revisão espaçada.',
    'pt-BR': 'O banco de questões do Estudo é reconstruído para trabalhar em volume. Questões e flashcards ficam em duas abas, com busca e filtros por disciplina, tema, nível cognitivo, fonte, material, documento, tag ou coleção, ordenação e seleção múltipla. Aplique status, dificuldade, categoria, tags, coleção e revisão a uma seleção inteira, e crie, edite ou exclua cada flashcard com suas próprias ações de revisão espaçada.',
    it: 'Il banco di domande di Studio viene ricostruito per lavorare in volume. Domande e flashcard vivono in due schede, con ricerca e filtri per materia, argomento, livello cognitivo, fonte, materiale, documento, tag o raccolta, ordinamento e selezione multipla. Applica stato, difficoltà, categoria, tag, raccolta e ripasso a un’intera selezione, e crea, modifica o elimina ogni flashcard con le sue azioni di ripetizione dilazionata.',
    tr: 'Çalışma soru bankası yoğun kullanım için yeniden kuruldu. Sorular ve kartlar iki sekmede yaşıyor. Ders, konu, bilişsel düzey, kaynak, materyal, belge, etiket veya koleksiyona göre arama ve filtreler, sıralama ve çoklu seçim var. Durum, zorluk, kategori, etiketler, koleksiyon ve tekrar durumunu tüm seçime uygulayın. Her kartı kendi aralıklı tekrar işlemleriyle oluşturun, düzenleyin veya silin.',
    'zh-CN': "学习题库为大批量操作而重建。问题与卡片分列两个标签页，支持搜索，以及按学科、主题、认知层级、来源、材料、文档、标签或合集筛选，支持排序和多选。可对整个选择应用状态、难度、类别、标签、合集和复习进度，并通过各自的间隔复习操作创建、编辑或删除每张卡片。",
  },
  {
    scope: 'estudio',
    es: 'El banco deja de estar encerrado. Importa y exporta Anki, con paquetes .apkg y TSV, cuestionarios Moodle en XML y GIFT, CSV y el propio JSON de Nodus desde un solo diálogo, que muestra qué va a entrar antes de tocar tus preguntas.',
    en: 'The bank is no longer locked in. Import and export Anki, with .apkg packages and TSV, Moodle quizzes in XML and GIFT, CSV and Nodus’s own JSON from one dialog that shows what will come in before touching your questions.',
    fr: 'La banque n’est plus fermée. Importez et exportez Anki, avec les paquets .apkg et TSV, les questionnaires Moodle en XML et GIFT, le CSV et le JSON propre à Nodus depuis une seule fenêtre, qui montre ce qui va entrer avant de toucher à vos questions.',
    de: 'Die Bank bleibt nicht länger verschlossen. Importieren und exportieren Sie Anki mit .apkg-Paketen und TSV, Moodle-Tests in XML und GIFT, CSV und Nodus-eigenes JSON in einem einzigen Dialog, der vorher zeigt, was hereinkommt.',
    pt: 'O banco deixa de estar fechado. Importa e exporta Anki, com pacotes .apkg e TSV, questionários Moodle em XML e GIFT, CSV e o próprio JSON do Nodus num único diálogo, que mostra o que vai entrar antes de tocar nas perguntas.',
    'pt-BR': 'O banco deixa de ficar preso. Importe e exporte Anki, com pacotes .apkg e TSV, questionários Moodle em XML e GIFT, CSV e o próprio JSON do Nodus em uma única janela, que mostra o que vai entrar antes de tocar nas questões.',
    it: 'Il banco non resta più chiuso. Importa ed esporta Anki, con pacchetti .apkg e TSV, questionari Moodle in XML e GIFT, CSV e il JSON di Nodus da un’unica finestra, che mostra cosa entrerà prima di toccare le domande.',
    tr: 'Soru bankası artık kapalı değil. Anki, .apkg paketleri ve TSV dahil, Moodle sınavları, XML ve GIFT dahil, CSV ve Nodus’un kendi JSON biçimi tek bir pencereden içe ve dışa aktarılıyor. Pencere, sorularınıza dokunmadan önce neyin gireceğini gösteriyor.',
    'zh-CN': "题库不再封闭。通过一个对话框即可导入和导出Anki（.apkg包和TSV）、Moodle的XML和GIFT测验、CSV以及Nodus自己的JSON，并在改动你的问题之前显示将要导入的内容。",
  },
  {
    scope: 'estudio',
    es: 'Las preguntas y tarjetas ya se leen como están escritas. Markdown y las fórmulas LaTeX se componen en el enunciado, las opciones, la respuesta y la explicación en todas las superficies, del banco y la sesión de repaso a la generación con IA, el generador de exámenes y los cuestionarios. Los campos de escritura ganan vista previa y el servidor web también las compone.',
    en: 'Questions and flashcards now read as they were written. Markdown and LaTeX formulas are typeset in the prompt, the options, the answer and the explanation on every surface, from the bank and the review session to AI generation, the exam builder and quizzes. Writing fields gain a preview, and the web server typesets them too.',
    fr: 'Les questions et les cartes se lisent désormais telles qu’elles ont été écrites. Le Markdown et les formules LaTeX sont composés dans l’énoncé, les options, la réponse et l’explication sur toutes les surfaces, de la banque et la session de révision à la génération par IA, le générateur d’examens et les quiz. Les champs de saisie gagnent un aperçu et le serveur web les compose aussi.',
    de: 'Fragen und Karteikarten lesen sich jetzt so, wie sie geschrieben wurden. Markdown und LaTeX-Formeln werden in Aufgabenstellung, Optionen, Antwort und Erklärung überall gesetzt, von der Bank und der Wiederholungssitzung bis zur KI-Erzeugung, dem Prüfungsgenerator und Quizzen. Eingabefelder erhalten eine Vorschau, und der Webserver setzt sie ebenfalls.',
    pt: 'As perguntas e os cartões leem-se agora como foram escritos. O Markdown e as fórmulas LaTeX são compostos no enunciado, nas opções, na resposta e na explicação em todas as superfícies, do banco e da sessão de revisão à geração com IA, ao gerador de exames e aos questionários. Os campos de escrita ganham pré-visualização e o servidor web também as compõe.',
    'pt-BR': 'As questões e os flashcards agora são lidos como foram escritos. Markdown e fórmulas LaTeX são compostos no enunciado, nas opções, na resposta e na explicação em todas as superfícies, do banco e da sessão de revisão à geração com IA, ao gerador de provas e aos questionários. Os campos de escrita ganham pré-visualização e o servidor web também as compõe.',
    it: 'Domande e flashcard ora si leggono come sono stati scritti. Markdown e formule LaTeX vengono composti in consegna, opzioni, risposta e spiegazione su ogni superficie, dal banco alla sessione di ripasso, fino alla generazione con IA, al generatore di esami e ai quiz. I campi di scrittura guadagnano l’anteprima e anche il server web le compone.',
    tr: 'Sorular ve kartlar artık yazıldıkları gibi okunuyor. Markdown ve LaTeX formülleri soru metninde, seçeneklerde, yanıtta ve açıklamada her yüzeyde diziliyor. Soru bankası ve tekrar oturumundan yapay zekâ üretimine, sınav oluşturucuya ve quizlere kadar. Yazma alanları önizleme kazanıyor ve web sunucusu da bunları diziyor.',
    'zh-CN': "问题和卡片现在能按书写的样子显示。Markdown和LaTeX公式会在题干、选项、答案和解析中排版呈现，覆盖所有界面，从题库和复习会话到AI生成、试卷生成器和测验。书写字段新增预览，Web服务器也会对其进行排版。",
  },
  {
    scope: 'ai',
    es: 'Guardar una respuesta del chat en tus notas conserva de dónde vino. La nota recuerda la conversación, el modelo y las fuentes, y desde la propia nota puedes volver a esa conversación y saltar al mensaje exacto. Al exportar las notas, la procedencia viaja con ellas.',
    en: 'Saving a chat answer to your notes keeps where it came from. The note remembers the conversation, the model and the sources, and from the note itself you can reopen that conversation and jump to the exact message. When you export your notes, the provenance travels with them.',
    fr: 'Enregistrer une réponse du chat dans vos notes conserve son origine. La note retient la conversation, le modèle et les sources, et depuis la note vous pouvez rouvrir cette conversation et sauter au message exact. À l’export des notes, la provenance voyage avec elles.',
    de: 'Eine Chat-Antwort in den Notizen zu speichern behält ihre Herkunft. Die Notiz merkt sich das Gespräch, das Modell und die Quellen. Aus der Notiz selbst öffnen Sie das Gespräch wieder und springen zur genauen Nachricht. Beim Export reist die Herkunft mit.',
    pt: 'Guardar uma resposta do chat nas notas conserva a sua origem. A nota recorda a conversa, o modelo e as fontes, e a partir da própria nota podes reabrir essa conversa e saltar para a mensagem exata. Ao exportar as notas, a procedência viaja com elas.',
    'pt-BR': 'Salvar uma resposta do chat nas notas preserva de onde ela veio. A nota lembra a conversa, o modelo e as fontes, e pela própria nota você pode reabrir essa conversa e ir à mensagem exata. Ao exportar as notas, a procedência viaja com elas.',
    it: 'Salvare una risposta della chat nelle note ne conserva l’origine. La nota ricorda la conversazione, il modello e le fonti, e dalla nota stessa puoi riaprire quella conversazione e saltare al messaggio esatto. Esportando le note, la provenienza viaggia con loro.',
    tr: 'Bir sohbet yanıtını notlara kaydetmek nereden geldiğini korur. Not, konuşmayı, modeli ve kaynakları hatırlar. Notun kendisinden o konuşmayı yeniden açıp tam mesaja atlayabilirsiniz. Notları dışa aktardığınızda bu köken bilgisi onlarla birlikte gider.',
    'zh-CN': "将聊天回答保存到笔记时会保留其来源。笔记会记住对话、模型和来源，并且你可以从笔记本身回到该对话并跳转到确切的消息。导出笔记时，来源信息会随之一起导出。",
  },
  {
    scope: 'ai',
    es: 'En los diálogos de creación de Deep Research e Immersion, solo Image Atelier se marca como de pago por llamada. Las demás Skills instaladas conservan el límite opcional de SVG Studio y dejan de pedirte un máximo obligatorio para confirmar.',
    en: 'In the Deep Research and Immersion creation dialogs, only Image Atelier is marked as paid per call. Every other installed Skill keeps SVG Studio’s optional ceiling and no longer asks for a mandatory maximum before you can confirm.',
    fr: 'Dans les fenêtres de création de Deep Research et Immersion, seule Image Atelier est marquée comme payante par appel. Les autres Skills installées conservent le plafond facultatif de SVG Studio et ne réclament plus de maximum obligatoire pour confirmer.',
    de: 'In den Erstellungsdialogen von Deep Research und Immersion ist nur Image Atelier als pro Aufruf kostenpflichtig markiert. Jede andere installierte Skill behält die optionale Obergrenze von SVG Studio und verlangt kein Pflichtmaximum mehr zum Bestätigen.',
    pt: 'Nas janelas de criação do Deep Research e do Immersion, só o Image Atelier é marcado como pago por chamada. As restantes Skills instaladas mantêm o limite opcional do SVG Studio e deixam de exigir um máximo obrigatório para confirmar.',
    'pt-BR': 'Nas janelas de criação do Deep Research e do Immersion, apenas o Image Atelier é marcado como pago por chamada. As outras Skills instaladas mantêm o limite opcional do SVG Studio e não exigem mais um máximo obrigatório para confirmar.',
    it: 'Nelle finestre di creazione di Deep Research e Immersion, solo Image Atelier è contrassegnata come a pagamento per chiamata. Le altre Skill installate mantengono il limite opzionale di SVG Studio e non richiedono più un massimo obbligatorio per confermare.',
    tr: 'Deep Research ve Immersion oluşturma pencerelerinde yalnızca Image Atelier çağrı başına ücretli olarak işaretleniyor. Kurulu diğer Skill’ler SVG Studio’nun isteğe bağlı sınırını koruyor ve onaylamadan önce zorunlu bir üst sınır istemiyor.',
    'zh-CN': "在Deep Research和Immersion的创建对话框中，只有Image Atelier被标记为按调用付费。其他已安装的Skill保留SVG Studio的可选上限，不再要求你填写必填的最大值才能确认。",
  },
  {
    scope: 'languages',
    es: 'Siete idiomas nuevos para generar contenido. Chino simplificado y tradicional, vietnamita, japonés, ruso, ucraniano y coreano se suman a los selectores de idioma de los prompts, que ya ofrecen quince. La interfaz mantiene sus ocho idiomas.',
    en: 'Seven new languages for generated content. Simplified and traditional Chinese, Vietnamese, Japanese, Russian, Ukrainian and Korean join the prompt language pickers, which now offer fifteen. The interface keeps its eight languages.',
    fr: 'Sept nouvelles langues pour le contenu généré. Le chinois simplifié et traditionnel, le vietnamien, le japonais, le russe, l’ukrainien et le coréen rejoignent les sélecteurs de langue des prompts, qui en proposent désormais quinze. L’interface conserve ses huit langues.',
    de: 'Sieben neue Sprachen für erzeugte Inhalte. Vereinfachtes und traditionelles Chinesisch, Vietnamesisch, Japanisch, Russisch, Ukrainisch und Koreanisch kommen zu den Sprachauswahlen der Prompts, die nun fünfzehn bieten. Die Oberfläche behält ihre acht Sprachen.',
    pt: 'Sete idiomas novos para o conteúdo gerado. Chinês simplificado e tradicional, vietnamita, japonês, russo, ucraniano e coreano juntam-se aos seletores de idioma dos prompts, que passam a oferecer quinze. A interface mantém os seus oito idiomas.',
    'pt-BR': 'Sete idiomas novos para o conteúdo gerado. Chinês simplificado e tradicional, vietnamita, japonês, russo, ucraniano e coreano entram nos seletores de idioma dos prompts, que agora oferecem quinze. A interface mantém seus oito idiomas.',
    it: 'Sette nuove lingue per i contenuti generati. Cinese semplificato e tradizionale, vietnamita, giapponese, russo, ucraino e coreano entrano nei selettori di lingua dei prompt, che ora ne offrono quindici. L’interfaccia mantiene le sue otto lingue.',
    tr: 'Üretilen içerik için yedi yeni dil. Basitleştirilmiş ve geleneksel Çince, Vietnamca, Japonca, Rusça, Ukraynaca ve Korece istem dili seçicilerine eklendi ve artık on beş dil sunuluyor. Arayüz kendi sekiz dilini koruyor.',
    'zh-CN': "新增七种内容生成语言。简体中文、繁体中文、越南语、日语、俄语、乌克兰语和韩语加入提示词语言选择器，该选择器现已提供十五种语言。界面仍保持八种语言。",
  },
  {
    scope: 'marketplace',
    es: 'El Marketplace muestra un solo catálogo. Skills, plugins, paquetes firmados y plugins pendientes de revisión comparten una lista y una tarjeta cada uno, con la misma identidad visual, los mismos detalles plegables y un único diálogo de permisos antes de instalar o actualizar.',
    en: 'The Marketplace shows one single catalog. Skills, plugins, signed packages and plugins awaiting review share one list with one card each, the same visual identity, the same collapsible details and one permissions dialog before installing or updating.',
    fr: 'Le Marketplace présente un catalogue unique. Skills, plugins, paquets signés et plugins en attente de révision partagent une seule liste, une fiche chacun, la même identité visuelle, les mêmes détails repliables et une seule fenêtre de permissions avant d’installer ou de mettre à jour.',
    de: 'Der Marketplace zeigt einen einzigen Katalog. Skills, Plugins, signierte Pakete und Plugins, die auf Prüfung warten, teilen sich eine Liste mit je einer Karte, derselben visuellen Identität, denselben einklappbaren Details und einem einzigen Berechtigungsdialog vor Installation oder Update.',
    pt: 'O Marketplace mostra um único catálogo. Skills, plugins, pacotes assinados e plugins à espera de revisão partilham uma lista, com um cartão cada, a mesma identidade visual, os mesmos detalhes recolhíveis e uma única caixa de diálogo de permissões antes de instalar ou atualizar.',
    'pt-BR': 'O Marketplace mostra um único catálogo. Skills, plugins, pacotes assinados e plugins aguardando revisão compartilham uma lista, com um cartão cada, a mesma identidade visual, os mesmos detalhes recolhíveis e uma única caixa de diálogo de permissões antes de instalar ou atualizar.',
    it: 'Il Marketplace mostra un solo catalogo. Skill, plugin, pacchetti firmati e plugin in attesa di revisione condividono un unico elenco con una scheda ciascuno, la stessa identità visiva, gli stessi dettagli richiudibili e un’unica finestra dei permessi prima di installare o aggiornare.',
    tr: 'Marketplace tek bir katalog gösteriyor. Skill’ler, eklentiler, imzalı paketler ve inceleme bekleyen eklentiler tek listede toplanıyor. Her biri kendi kartında, aynı görsel kimlikle, aynı daraltılabilir ayrıntılarla ve kurmadan ya da güncellemeden önce tek bir izin penceresiyle gösteriliyor.',
    'zh-CN': "Marketplace只显示一个统一目录。Skills、插件、已签名包和待审核插件共用一个列表，各自一张卡片，具有相同的视觉标识、相同的可折叠详情，以及安装或更新前唯一的权限对话框。",
  },
  {
    scope: 'plugin',
    es: 'Los paquetes firmados versión 2 usan su propio canal de ejecución. Sus herramientas dejan de anunciarse por el mecanismo genérico anterior y se ejecutan por la vía de capacidades de confianza que declaran, así que el chat deja de buscar una herramienta que el paquete no expone.',
    en: 'Signed version 2 packages use their own execution channel. Their tools are no longer advertised through the previous generic mechanism and run through the trusted capability path they declare, so a chat no longer reaches for a tool the package does not expose.',
    fr: 'Les paquets signés version 2 utilisent leur propre canal d’exécution. Leurs outils ne passent plus par l’ancien mécanisme générique et s’exécutent par la voie des capacités de confiance qu’ils déclarent, donc le chat ne tombe plus sur un outil que le paquet n’expose pas.',
    de: 'Signierte Pakete der Version 2 nutzen ihren eigenen Ausführungskanal. Ihre Werkzeuge werden nicht mehr über den bisherigen generischen Mechanismus angeboten und laufen über den vertrauenswürdigen Capability-Pfad, den sie deklarieren. Der Chat greift nicht mehr nach einem Werkzeug, das das Paket nicht anbietet.',
    pt: 'Os pacotes assinados versão 2 usam o seu próprio canal de execução. As suas ferramentas deixam de ser anunciadas pelo mecanismo genérico anterior e executam-se pela via de capacidades de confiança que declaram, pelo que o chat deixa de procurar uma ferramenta que o pacote não expõe.',
    'pt-BR': 'Os pacotes assinados versão 2 usam o próprio canal de execução. Suas ferramentas não são mais anunciadas pelo mecanismo genérico anterior e rodam pela via de capacidades confiáveis que declaram, então o chat não procura mais uma ferramenta que o pacote não expõe.',
    it: 'I pacchetti firmati versione 2 usano il proprio canale di esecuzione. I loro strumenti non passano più dal precedente meccanismo generico e vengono eseguiti tramite il percorso di capacità fidate che dichiarano, così la chat non cerca più uno strumento che il pacchetto non espone.',
    tr: 'İmzalı sürüm 2 paketleri kendi yürütme kanalını kullanıyor. Araçları artık önceki genel mekanizma üzerinden duyurulmuyor ve bildirdikleri güvenilir yetenek yolundan çalışıyor. Böylece sohbet, paketin sunmadığı bir aracı aramıyor.',
    'zh-CN': "版本2的已签名包使用自己的执行通道。其工具不再通过先前的通用机制公布，而是经由它们声明的受信能力路径执行，因此聊天不再去寻找包未公开的工具。",
  },
  {
    scope: 'browser',
    es: 'El navegador respeta las páginas que no declaran modo oscuro. Su fondo sigue los colores del propio documento en lugar de imponer el tema de la aplicación, así que una página 401 o sin estilos se lee sin seleccionar el texto. Las webs con autenticación básica HTTP ya pueden iniciar sesión desde una barra del navegador, que no guarda tus credenciales.',
    en: 'The browser respects pages that do not declare a dark scheme. Their surface follows the document’s own colours instead of imposing the app theme, so a 401 page or an unstyled document is readable without selecting its text. Sites using HTTP Basic authentication can now sign in through a browser bar that stores none of your credentials.',
    fr: 'Le navigateur respecte les pages qui ne déclarent pas de thème sombre. Leur fond suit les couleurs du document au lieu d’imposer le thème de l’application, donc une page 401 ou sans styles se lit sans sélectionner le texte. Les sites en authentification HTTP basique peuvent se connecter via une barre du navigateur, qui ne conserve aucun identifiant.',
    de: 'Der Browser respektiert Seiten, die kein dunkles Schema angeben. Ihre Fläche folgt den Farben des Dokuments, statt das App-Design aufzuzwingen, sodass eine 401-Seite oder ein ungestyltes Dokument ohne Textauswahl lesbar ist. Seiten mit HTTP-Basisauthentifizierung melden sich nun über eine Browserleiste an, die keine Zugangsdaten speichert.',
    pt: 'O navegador respeita as páginas que não declaram modo escuro. O fundo segue as cores do próprio documento em vez de impor o tema da aplicação, pelo que uma página 401 ou sem estilos se lê sem selecionar o texto. Os sites com autenticação básica HTTP já podem iniciar sessão numa barra do navegador, que não guarda as tuas credenciais.',
    'pt-BR': 'O navegador respeita as páginas que não declaram modo escuro. O fundo segue as cores do próprio documento em vez de impor o tema do aplicativo, então uma página 401 ou sem estilos é legível sem selecionar o texto. Sites com autenticação básica HTTP agora entram por uma barra do navegador, que não guarda suas credenciais.',
    it: 'Il browser rispetta le pagine che non dichiarano un tema scuro. La superficie segue i colori del documento invece di imporre il tema dell’app, quindi una pagina 401 o senza stili si legge senza selezionare il testo. I siti con autenticazione HTTP di base ora accedono da una barra del browser che non conserva le credenziali.',
    tr: 'Tarayıcı, koyu şema bildirmeyen sayfalara saygı gösteriyor. Yüzey, uygulama temasını dayatmak yerine belgenin kendi renklerini izliyor. Böylece 401 sayfası veya biçimsiz bir belge, metin seçmeden okunabiliyor. HTTP Basic kimlik doğrulaması kullanan sitelere artık tarayıcı çubuğundan giriş yapılabiliyor ve kimlik bilgileriniz saklanmıyor.',
    'zh-CN': "浏览器会尊重未声明深色模式的页面。其背景遵循文档自身的颜色，而不是强加应用主题，因此401页面或无样式页面无需选中文字即可阅读。使用HTTP基本认证的网站现在可以通过浏览器地址栏登录，该栏不会保存你的凭据。",
  },
  {
    scope: 'browser',
    es: 'La vista nativa del navegador se alinea con el zoom de la interfaz. Al ampliar o reducir con el zoom del renderizador, la página y su marco dejan de quedar desalineados y el contenido se mantiene en su sitio.',
    en: 'The browser’s native view aligns with the interface zoom. When you zoom in or out with the renderer zoom, the page and its frame stop drifting apart and the content stays in place.',
    fr: 'La vue native du navigateur s’aligne sur le zoom de l’interface. En zoomant avec celui du moteur de rendu, la page et son cadre ne se décalent plus et le contenu reste en place.',
    de: 'Die native Ansicht des Browsers richtet sich am Zoom der Oberfläche aus. Beim Vergrößern oder Verkleinern über den Renderer-Zoom driften Seite und Rahmen nicht mehr auseinander und der Inhalt bleibt an seinem Platz.',
    pt: 'A vista nativa do navegador alinha-se com o zoom da interface. Ao ampliar ou reduzir com o zoom do renderizador, a página e o seu enquadramento deixam de ficar desalinhados e o conteúdo mantém-se no sítio.',
    'pt-BR': 'A visualização nativa do navegador se alinha ao zoom da interface. Ao ampliar ou reduzir com o zoom do renderizador, a página e sua moldura não ficam mais desalinhadas e o conteúdo permanece no lugar.',
    it: 'La vista nativa del browser si allinea allo zoom dell’interfaccia. Ingrandendo o riducendo con lo zoom del renderer, la pagina e la sua cornice non restano più disallineate e il contenuto rimane al suo posto.',
    tr: 'Tarayıcının yerel görünümü arayüz yakınlaştırmasıyla hizalanıyor. Görüntüleyici yakınlaştırmasıyla büyütüp küçülttüğünüzde sayfa ve çerçevesi artık kaymıyor ve içerik yerinde kalıyor.',
    'zh-CN': "浏览器的原生视图与界面缩放对齐。使用渲染器缩放进行放大或缩小时，页面与其边框不再错位，内容保持原位。",
  },
  {
    scope: 'library',
    es: 'El análisis de la biblioteca se recupera mejor de los fallos pasajeros. Si Zotero no responde, el trabajo vuelve a la cola en lugar de darse por «sin texto», el filtro «Incompleto» comprueba los cinco pasos y el estado semántico coincide con el de cada fila, y una fusión interrumpida se reanuda solo por las ideas que faltan.',
    en: 'Library analysis recovers better from transient failures. When Zotero is unreachable, the work returns to the queue instead of being marked as having no text, the Incomplete filter checks all five steps and the semantic state agrees with each row, and an interrupted fusion resumes only the ideas that are missing.',
    fr: 'L’analyse de la bibliothèque se remet mieux des échecs passagers. Si Zotero ne répond pas, le travail retourne dans la file au lieu d’être marqué sans texte, le filtre Incomplet vérifie les cinq étapes et l’état sémantique correspond à chaque ligne, et une fusion interrompue reprend uniquement les idées manquantes.',
    de: 'Die Bibliotheksanalyse erholt sich besser von vorübergehenden Fehlern. Ist Zotero nicht erreichbar, kehrt die Arbeit in die Warteschlange zurück, statt als ohne Text markiert zu werden. Der Filter Unvollständig prüft alle fünf Schritte und der semantische Status stimmt mit der jeweiligen Zeile überein. Eine unterbrochene Fusion wird nur für die fehlenden Ideen fortgesetzt.',
    pt: 'A análise da biblioteca recupera melhor de falhas passageiras. Se o Zotero não responder, o trabalho volta à fila em vez de ficar marcado como sem texto, o filtro «Incompleto» verifica os cinco passos e o estado semântico coincide com o de cada linha, e uma fusão interrompida retoma apenas as ideias que faltam.',
    'pt-BR': 'A análise da biblioteca se recupera melhor de falhas passageiras. Se o Zotero não responde, o trabalho volta à fila em vez de ser marcado como sem texto, o filtro «Incompleto» verifica as cinco etapas e o estado semântico bate com o de cada linha, e uma fusão interrompida retoma apenas as ideias que faltam.',
    it: 'L’analisi della biblioteca si riprende meglio dagli errori temporanei. Se Zotero non risponde, il lavoro torna in coda invece di essere segnato come senza testo, il filtro Incompleto controlla tutti e cinque i passaggi e lo stato semantico coincide con quello di ogni riga, e una fusione interrotta riprende solo le idee mancanti.',
    tr: 'Kitaplık analizi geçici hatalardan daha iyi toparlanıyor. Zotero yanıt vermezse çalışma metinsiz olarak işaretlenmek yerine kuyruğa dönüyor. Eksik filtresi beş adımın tamamını denetliyor ve anlamsal durum her satırla uyuşuyor. Yarım kalan bir birleştirme yalnızca eksik fikirlerden devam ediyor.',
    'zh-CN': "文献库分析能更好地从暂时性故障中恢复。如果Zotero无响应，任务会回到队列，而不是被判为「没有文本」，「不完整」筛选会检查全部五个步骤，语义状态与每一行一致，被中断的融合只针对缺失的观点继续执行。",
  },
];
