// v2.6.0 and v2.6.1 intentionally share this exact Italian list — see the note
// next to RELEASE_2_6_HIGHLIGHTS in releaseNotes.ts.
const RELEASE_2_6_IT: string[] = [
  "Nodus per Zotero include ora una ricerca semantica multilingue completamente locale con un modello E5 small quantizzato. Il modello viene scaricato una sola volta, funziona sul dispositivo ed elimina la configurazione e il costo di un'API di embedding; gli indici compressi e i relativi vettori restano nel profilo Zotero.",
  "I PDF lunghi vengono ricostruiti per pagina, colonna e paragrafo, rimuovendo intestazioni e piè di pagina ripetuti e conservando le coordinate per citazioni ed evidenziazioni esatte. Un recuperatore limitato può riformulare le ricerche, ispezionare intervalli di pagine ed estendere le prove per due turni prima di rispondere, con OCR e analisi visiva quando necessari.",
  "Nel modale Novità, la N collegata di Nodus ruota formando una Z per identificare a colpo d'occhio i miglioramenti del componente aggiuntivo. Dentro Zotero, il componente aggiuntivo mantiene la normale N di Nodus.",
  "Strumenti inaugura Nodus Apps: crea con l'IA mini applicazioni complete e funzionanti — giochi, calcolatrici, pianificatori, sondaggi — con un catalogo iniziale già incluso. Ogni app può essere condivisa dal vivo con un codice QR o un PIN, così altre persone possono partecipare dal proprio telefono.",
  "Nuovo strumento Nodus Translate: traduci testo incollato, file e allegati di Zotero con il modello IA che preferisci. Conserva la struttura di DOCX ed EPUB e include una modalità facsimile per i PDF che mantiene il layout, le immagini e la geometria della pagina sostituendo il testo visibile.",
  "Generazione di immagini locale con FLUX.2 Klein: un modello scaricabile facoltativamente, con licenza Apache 2.0, che crea immagini direttamente sul tuo dispositivo, senza API, senza costi per utilizzo e senza inviare i tuoi prompt a terzi.",
  "Deep Research, Immersione e il Laboratorio di scrittura ora esportano report in PDF con un design professionale: copertina, indice navigabile, metriche in evidenza e sezioni numerate.",
  "Nodus Server, sperimentale: condividi una copia filtrata e di sola lettura di un deposito con una classe o un gruppo di lavoro, con accesso remoto da ChatGPT o Claude tramite un tunnel MCP protetto da OAuth. Viene eseguito sul tuo Docker, richiede una password di amministrazione sicura e riceve solo traffico HTTPS in uscita da Nodus Desktop.",
  "L'assistente di Nodus per Zotero diventa molto più completo: appare anche nel popup del lettore, risponde sul documento aperto o su più elementi selezionati, può evidenziare automaticamente i passaggi più rilevanti e salvare la conversazione come nota di Zotero.",
  "Nuova modalità agente in Nodus per Zotero: propone di creare note, evidenziazioni, etichette o modifiche ai campi a partire dalla conversazione, chiedendo conferma prima di applicare ogni azione.",
  "Il componente aggiuntivo Nodus per Zotero si installa e si aggiorna direttamente dalle Impostazioni, ed è anche pubblicato come file .xpi a ogni versione di Nodus per chi preferisce installarlo manualmente in Zotero.",
  "Nuova guida di benvenuto sui flussi connessi: spiega chiaramente quando usare il server MCP locale, quando usare il nuovo Nodus Server, come lavorare dentro Zotero e cosa offre il Toolkit completo."
];

export const RELEASE_2_6_2_IT: string[] = [
  "Il componente aggiuntivo Zotero ora divide l'indicizzazione in un indice rapido —estrae e suddivide il testo quasi subito— e uno completo che calcola gli embedding in background senza bloccare l'assistente. L'OCR è ora su richiesta invece di essere sempre attivo, e quando si legge un singolo documento l'intero testo viene usato direttamente nel contesto, eguagliando la velocità di altri strumenti di lettura.",
  "La ricerca semantica è più efficiente: le chiamate extra al modello vengono evitate quando ci sono pochi risultati, la riparazione delle citazioni è configurabile e i round di ricerca agentica sono regolabili (1 per impostazione predefinita). L'OCR viene elaborato in parallelo e gli embedding locali usano WebGPU quando disponibile, con fallback a Wasm.",
];

export const RELEASE_2_6_3_IT: string[] = [
  "Il componente aggiuntivo Nodus per Zotero si mantiene aggiornato da solo: si registra nel gestore di aggiornamenti di Zotero e installa ogni nuova versione automaticamente dall'ultima pubblicazione su GitHub, verificata da Zotero e applicata al riavvio. È attivo per impostazione predefinita e può essere disattivato nelle Impostazioni, che chiedono prima conferma.",
  "L'assistente di Nodus per Zotero risponde con precisione sui PDF lunghi: una mappa del documento gli fornisce dati reali sulle pagine —totale, pagina corrente, prima e ultima— così da non inventarli, e le domande su «pagina corrente», «ultima pagina» o «pagina N» recuperano quelle pagine esatte. Inoltre la prima risposta non attende più l'indicizzazione dell'intero documento: si calcolano solo gli embedding indispensabili e il resto prosegue in background.",
  "Nodus Server mantiene pubblicati in background tutti i depositi collegati, non solo quello aperto: cambiando deposito gli altri continuano a sincronizzarsi e a essere serviti, senza diventare obsoleti. Le Impostazioni mostrano ora tutte le tue connessioni con il relativo stato e puoi sincronizzare o disconnettere ciascuna separatamente.",
  "La generazione audio è più affidabile: la narrazione prosegue anche se esci dalla vista e recupera il suo avanzamento al ritorno, il riassunto di un report di Deep Research non viene più letto due volte e i segmenti lunghi non si interrompono più a metà parola. Anche la trascrizione con Whisper locale ora termina in background invece di essere annullata quando cambi schermata.",
  "I report PDF di Deep Research adottano un design più curato: copertina pulita con il marchio Nodus, riassunto esecutivo centrato, numerazione automatica delle sezioni e una matrice di tracciabilità compatta in forma di tabella.",
];

// Same order as RELEASE_3_0_0_HIGHLIGHTS — these arrays are matched by index, so a
// reordering here silently attaches an Italian sentence to a different highlight.
export const RELEASE_3_0_0_IT: string[] = [
  "Nuovo vault di Prosopografia, per studiare popolazioni storiche persona per persona. Acquisizione e critica delle fonti, risoluzione delle identità, factoidi con la loro prova, popolazioni, coorti e questionari, ricerca, analisi di rete a livelli e interscambio di dati: la prova sta attaccata al dato invece di restare dietro di esso.",
  "Nuovo vault di Fonti primarie, per lavorare con archivi storici. Repository e gerarchia archivistica, sessioni di acquisizione, collezioni di lavoro, modelli, file con la loro immagine, testo revisionato, estratti e collegamenti di prova, più mappa, cronologia, persone, relazioni, note e ricerca. Include un corpus documentale dimostrativo reversibile, con documenti sintetici, immagini generate e luoghi reali da gazetteer.",
  "Nuovo vault di Testimonianze, per storia orale e giornalismo. La sua unità non è la registrazione né la trascrizione: è l'intervista completa, con la sua preparazione, i suoi partecipanti, le sue sessioni, i suoi file originali, le sue trascrizioni e l'accordo con cui è stata fatta. Il menu resta a otto voci — Home, Cerca, Interviste, Partecipanti, Confronti, Note, Toolkit e Impostazioni — perché tutto il resto avviene dentro ciascuna intervista.",
  "Nuovo vault di Worldbuilding, per inventare mondi e scrivere al loro interno. Personaggi con la loro scheda completa, luoghi ad albero con 37 tipi, fazioni e culture, scene con doppio ordine —il giorno del mondo e l'ordine del racconto—, segreti che registrano chi li conosce e da quando, e un calendario proprio con le sue ere e i suoi mesi. Un personaggio è una persona con sopra uno strato di finzione, quindi eredita parentela, eventi di vita, luoghi e ritratto senza una seconda ontologia.",
  "La Biblioteca accademica si organizza attorno a una sola domanda: posso già usare quest'opera? I cinque stati della pipeline si riassumono in uno Stato leggibile, dodici colonne diventano otto, ogni riga ha un verbo principale, i filtri sono preimpostazioni che interrogano l'intero corpus, e un dettaglio per opera consente di ripetere ogni passaggio separatamente. I due indici prendono il nome da ciò che offrono —ricerca semantica e testo citabile— e un'opera analizzata dal suo riassunto non viene più conteggiata come «senza testo».",
  "Genealogia guadagna controllo su ciò che si vede: puoi nascondere e mostrare rami dell'albero, creare tipi di fatto propri che sono anche ricercabili, scegliere o creare un luogo già configurato mentre registri un fatto, e il calendario disegna finalmente gli eventi di più giorni come una barra continua.",
  "Docenza inaugura Analizzare —Chat, Idee e Grafo sul corpus del corso stesso— e trasforma «Unità didattiche» in un Deep Research con pubblico: lo stesso materiale produce un piano per chi tiene la lezione oppure appunti pronti da consegnare agli studenti, e il pubblico attraversa tutti e tre i prompt nelle sette lingue invece di essere aggiunto alla fine.",
  "Il server MCP e Nodus Server raggiungono la parità con i nuovi vault: Worldbuilding, Fonti primarie, Prosopografia e Testimonianze appaiono ora negli snapshot, espongono i loro strumenti e superano le stesse validazioni degli altri.",
  "La barra di Nodus in Zotero si connette da sola. Prima leggeva la sua configurazione una volta sola all'avvio, quindi aprire Zotero prima di Nodus ti lasciava «non connesso» fino a premere «Prova connessione» a mano; ora riprova con attesa crescente, al ritorno su Zotero, all'apertura delle sue impostazioni e prima di inviare un messaggio, e segue un Nodus che si riavvia su un'altra porta o ruota il suo token. Componente aggiuntivo 3.0.0.",
  "Il copilota di Word corregge la sua navigazione e si vede finalmente nella tua lingua. E l'assistente di configurazione smette di promettere «l'API locale di Zotero 7»: ciò che Nodus usa è l'implementazione locale della Web API v3 di Zotero, ed è quello che ora dice, in tutte e sette le lingue.",
  "Nodi sa finalmente cosa Nodus ha davvero: descrive il Toolkit già implementato, i vault disponibili, la roadmap del server, la collaborazione e le applicazioni per iOS e iPadOS in programma. In Worldbuilding, inoltre, risponde sulla stessa base e con le stesse citazioni della chat del mondo.",
  "Il turco è la settima lingua completa di Nodus, terminologia di parentela inclusa, e tutte le superfici del Toolkit sono finalmente tradotte.",
  "Il primo avvio cambia: la guida mostra la sola introduzione e ti dice dove sono le altre, e poi una schermata ti lascia dare un nome al tuo primo vault e scegliere la sua modalità invece di consegnarti un vault accademico chiamato «Principale». I dieci tutorial pubblicati vivono nelle Impostazioni, su quattro scaffali con schede e casella di ricerca, e quello di ogni vault appare quando lo crei.",
  "La configurazione dell'IA si può ora rinviare, e un download di modello che non vuoi più si annulla da dove è stato avviato.",
  "Suggerisci o segnala include ora un sondaggio facoltativo da 0 a 10 —copertura, usabilità, prestazioni, stabilità e design— con spazio per scrivere quello che vuoi. Tutte le risposte vanno in un unico thread pubblico condiviso invece di aprire una nuova segnalazione ogni volta, con la tua versione di Nodus e il tuo sistema operativo già compilati.",
  "Tre correzioni che si notano ogni giorno: i report in PDF uniformano il loro marchio per vault e perdono le bande grigie che alcuni lettori disegnavano attorno all'immagine di copertina, la personalizzazione della barra laterale è per vault invece che globale, e le immagini si caricano tramite la cache nativa e si possono scaricare nella loro risoluzione originale.",
];

export const RELEASE_2_7_0_IT: string[] = [
  "I tutorial di Nodus si possono ora guardare in video senza uscire dall'applicazione. Al primo avvio ti viene chiesto come preferisci imparare —guardare i tutorial o leggere la guida— e Impostazioni → Tutorial apre la stessa griglia, con lettore integrato, contrassegno «visto» condiviso tra i depositi e la guida scritta sempre a un clic come percorso offline. Anche i tour guidati di ogni deposito propongono il loro video, e il catalogo si aggiorna da solo ogni volta che ne pubblichiamo uno nuovo.",
  "I backup automatici non bloccano più l'applicazione. L'archivio viene ora compresso e cifrato senza bloccare il processo principale, così una libreria grande smette di scattare ogni mezz'ora; la sincronizzazione con Nodus Server fa lo stesso con la propria compressione. Il formato dei backup non cambia e quelli esistenti si ripristinano esattamente come prima.",
  "Nodi torna a rispondere all'istante e le sue liste si comportano bene. Le note rapide e la chat ora scorrono invece di schiacciare le righe e tagliare il testo a metà, e la mascotte non resta più congelata mentre il processo principale è occupato.",
  "Due ritocchi di interfaccia: il pulsante Aggiorna dell'intestazione non è più riempito con il colore d'accento e si uniforma al resto della barra, e nella scheda della persona i pulsanti di aggiunta (relazioni, luoghi, varianti del nome ed eventi di vita) si riducono a un'icona con descrizione al passaggio del mouse, così titolo e descrizione di ogni sezione tornano a stare su una riga.",
  "L'installazione del copilota di Word non tocca più la cache dei componenti aggiuntivi di Office. Prima venivano cancellati singoli file da quella cache —cosa che Microsoft sconsiglia— e ciò poteva impedire il caricamento di tutti i componenti aggiuntivi di Word; ora basta reinstallare dalle Impostazioni e riaprire Word. Il manuale del componente aggiuntivo descrive la vera procedura di installazione e come distinguerla da un guasto proprio di Office.",
];

/** Italian history, indexed by release and highlight order. */
const RELEASE_3_0_4_IT: string[] = [
  "Un client MCP può mettere in coda i report di Deep Research. Finora il client che ne chiedeva uno doveva tenere aperta la chiamata per tutta la generazione — diversi minuti in cui qualsiasi cosa poteva scadere — e rischiava di scontrarsi con un report avviato da te nell’applicazione. Ora lo mette in coda e torna a consultarlo quando vuole: Nodus ha un’unica corsia di generazione condivisa con la finestra, così non girano mai due report insieme; la striscia della coda contrassegna con un distintivo MCP quelli che arrivano da un client e Nodi ti avvisa quando uno finisce o fallisce, perché chi l’ha chiesto potrebbe essersi già disconnesso. Ogni lavoro resta legato alla cassaforte in cui è stato messo in coda, e cambiare cassaforte annulla ciò che era ancora in attesa per un’altra.",
  "Un’immagine fallita si può ritentare con un altro motore. Il nuovo tentativo riutilizzava il fornitore e il modello salvati sull’immagine che si era appena rifiutata, così un report bloccato su «non è stato possibile generare l’immagine» tornava sempre allo stesso motore, e cambiare fornitore nelle Impostazioni non serviva a nulla. Ora il motore viene da ciò che chiedi o dalle Impostazioni: un’immagine fallita si apre con il predefinito attuale, una già generata mantiene il suo, e la finestra di progettazione guadagna un selettore di modello con l’intero catalogo e il prezzo per immagine, mentre il piè di pagina dice che cosa userà il pulsante. Anche il motivo reale del fallimento apre il messaggio, tradotto in tutte e sette le lingue, invece di stare sotto un titolo generico che lo contraddiceva.",
  "La mappa degli argomenti disegna un’idea ben collegata per quello che è. Aprire un’idea centrale la appiattiva in una stella: il percorso limitava le sue idee nell’ordine del database prima di ordinarle per rilevanza, così alcuni dei suoi dibattiti più forti sparivano in silenzio, e conservava solo i collegamenti che aveva attraversato lui stesso, cosicché nessun ramo poteva ramificarsi per quanta profondità avessi impostato. Ora si espande partendo dal collegamento più forte, conserva tutti i collegamenti fra le idee che mostra, ripartisce ogni livello fra dibattiti, sostegni e il resto invece di lasciare che i dibattiti prendano tutti i posti, e l’intestazione conta le connessioni reali dell’idea e quanti collegamenti sono rimasti non disegnati.",
];

const RELEASE_3_0_3_IT: string[] = [
  "I report escono da Deep Research in blocco, e anche dalla loro scheda. Tutto ciò che la galleria produceva usciva uno alla volta, passando dal lettore: una libreria di trenta report significava trenta finestre di salvataggio, e una scheda non si poteva scaricare senza prima aprirla. Ora il pulsante Scarica dell’intestazione riutilizza la modalità di selezione — «seleziona tutto» compreso —, ti lascia scegliere Markdown, PDF o entrambi e consegna un unico ZIP; ogni scheda e ogni riga guadagnano inoltre la propria icona di download. I PDF vengono stampati uno alla volta con una barra di avanzamento, perché quella passata può durare un minuto e un minuto in silenzio sembra un blocco.",
  "Il design dell’immagine di un report può ora suggerirti la scena. «Suggerisci con l’IA» scrive nel campo del prompt una descrizione visiva ricavata dal riassunto del report stesso — la stessa che il generatore si sarebbe scritto da sé e che finora non vedevi mai. Puoi modificarla, e non viene salvato nulla finché non generi con essa.",
  "Annullare una narrazione ora la annulla davvero. Il pulsante non produceva nulla di visibile: il lavoro proseguiva fino alla fine della sezione — minuti di attesa, o all’infinito se la voce non rispondeva mai — e restava poi bloccato per tutto il resto della sessione, senza modo di ricominciare. Ora il clic viene riconosciuto subito, il segmento in corso viene scartato e una voce locale smette di consumare un core per finire una narrazione che nessuno ascolterà.",
];

const RELEASE_3_0_2_IT: string[] = [
  "Deep Research non afferma più di quanto possa sostenere. Ogni citazione viene verificata rispetto a ciò che la fonte dice davvero, e quella che non la sostiene sparisce dal testo e dalla bibliografia. Chi redige riceve ora il contenuto reale di ciò che cita — l’enunciato di ogni idea, ciò che afferma ogni lacuna, chi sostiene ciascuna posizione di un dibattito e il testo letterale di ogni passaggio con la sua pagina —, così i disaccordi fra autori vengono argomentati con nomi anziché citati di sfuggita. La copertura dichiarata è quella realmente citata, non quella assegnata.",
  "Un nuovo pannello indica quali affermazioni conviene verificare prima di citarle. Un terzo delle citazioni che superano la verifica ha un riscontro parziale: la fonte sostiene una versione più debole di quanto la frase affermi. Il report le elenca accanto al testo della loro fonte e all’autore e anno da aprire, così controllare un report passa dal leggere opere intere al confrontare una manciata di coppie.",
  "La mappa degli argomenti e i dibattiti non congelano più la finestra. Disegnavano in un colpo solo decine di migliaia di elementi e l’intera applicazione restava bloccata per uno o due secondi all’apertura; ora vengono disegnati a tratti mentre scorri. La mappa si dispiega inoltre un ramo alla volta invece di aprirsi tutta, così puoi seguire una linea argomentativa senza perderti.",
  "I personaggi intervistati parlano invece di recitare. In modalità dimostrativa rispondevano leggendo la propria scheda ad alta voce; ora rispondono con la loro voce, il loro carattere e i loro silenzi, come in un’intervista vera.",
  "Il runtime di Codex incluso in Nodus genera anche immagini, così puoi creare illustrazioni senza configurare alcuna chiave aggiuntiva se hai già collegato il tuo abbonamento ChatGPT. E la generazione con Google torna a funzionare: le veniva richiesto un formato di immagine che non accetta più.",
  "Gli aggiornamenti su macOS tornano a installarsi da soli. Nodus scaricava la nuova versione e poi non riusciva a chiudersi, così il programma di installazione restava in attesa all’infinito; forzare la chiusura se lo portava dietro e riaprivi sulla versione precedente, senza il minimo avviso. Ora la chiusura va sempre a buon fine, il programma di installazione porta a termine il lavoro anche se forzi l’uscita, e se un aggiornamento non si installa Nodus te lo dice all’avvio invece di riprovarci in silenzio.",
];

const RELEASE_3_0_1_IT: string[] = [
  "Le sezioni che restavano a pensare ora si aprono subito. Il grafo, la mappa degli argomenti, i dibattiti, il percorso di lettura e le schede d'autore si caricavano percorrendo l'intera biblioteca e bloccavano tutta l'applicazione mentre lo facevano; ora chiedono solo ciò che mostrano. In una cassaforte di quasi 10.000 idee il grafo passa da 2,7 secondi di finestra congelata a meno di 0,2.",
  "Nodi resta fermo quando non ha nulla da dire e torna a muoversi appena ce l'ha. La sua animazione non si fermava mai, nemmeno con l'applicazione a riposo: costava in permanenza mezzo core e scaldava la macchina. Ora mantiene la posa qualche secondo dopo l'ultima attività e si sveglia al passaggio del mouse, a un cambio di stato o all'arrivo di una notifica. Nessuna animazione è stata rimossa.",
  "La cache del testo estratto dai PDF ora ha un limite. Veniva scritta e mai ripulita, arrivando a occupare un quarto del file della cassaforte, che per giunta finisce intero in ogni backup. Ora è limitata a 64 MB conservando il più recente; nulla va perso, perché qualsiasi testo scartato viene riestratto dal suo PDF quando serve.",
];

const RELEASE_3_1_0_IT: string[] = [
  "Un vault può vivere su un server ed essere copiato per intero sul tuo computer. Quando lo crei scegli tra locale, come sempre, e connesso. Scrivi l’indirizzo del server e le tue credenziali e scarichi lo spazio a cui hai accesso. È un vero database sul tuo disco, quindi tutto funziona uguale, anche senza connessione. Si aggiorna da solo in background.",
  "Ogni account ha un livello di accesso in ogni spazio, e quel livello decide dove finisce il tuo lavoro. In lettura, tutto ciò che scrivi o generi resta sul tuo computer e non esce mai. In scrittura, le tue note e i tuoi rapporti raggiungono il vault principale alla prossima connessione del proprietario, e nel frattempo la schermata indica quante modifiche sono in attesa. Se ti revocano l’accesso, il vault resta intero sul tuo computer e smette soltanto di sincronizzarsi. Ora si condividono anche i vault di genealogia, insegnamento, studio e database.",
  "Questo computer può essere il server, senza Docker né dominio. Nelle Impostazioni scegli la modalità di base e Nodus lo avvia da solo. La scheda dice in ogni momento chi può collegarsi, solo questo computer, la tua rete locale o la tua Tailscale, e non serve mai nulla senza cifratura. Per collegare il telefono c’è un codice breve e leggibile, senza lettere che si confondono.",
  "Abbiamo corretto ciò che l’informativa sulla privacy diceva degli embedding. Sosteneva che non vengono mai caricati, e da quando esiste la ricerca semantica condivisa non era più vero. I vettori delle idee viaggiano davvero, per poter cercare per significato da una replica o dal telefono. Il documento ora lo dice, e c’è un nuovo interruttore, «Includi i vettori semantici», che lo ferma sul serio. Inoltre, un vault di studio o insegnamento condiviso non invia più registrazioni delle lezioni, tentativi né voti.",
];

const RELEASE_3_2_0_IT: string[] = [
  "Cercare per significato su un server Nodus non lo lascia più incapace di rispondere agli altri. Finora, mentre risolveva una ricerca, tutte le altre richieste aspettavano il loro turno. Quel calcolo ora gira su thread separati e il server continua a rispondere. Si nota soprattutto quando più persone consultano nello stesso momento.",
  "Il server non mette più da parte memoria alla cieca. Teneva in memoria tre vault pubblicati, di qualunque dimensione, e con un corpus grande superava il gigabyte. Il limite ora si misura in memoria e non in un numero di vault. Chi amministra un server può alzarlo se la sua macchina ha spazio.",
  "La coda di Deep Research ora dice a che punto è. Il rapporto in corso di generazione ha una barra con la sua percentuale reale, e quelli in attesa indicano quanti li precedono. Prima girava soltanto un'icona, senza modo di distinguere uno appena avviato da uno che stava per finire.",
  "Un rapporto finito appare da solo nella galleria. Se ne mettevi in coda diversi, tutti tranne l'ultimo restavano fuori finché non uscivi dalla sezione e rientravi. E un rapporto che viene generato ma non può essere salvato ora lo dice, invece di sparire senza lasciare traccia.",
  "Generare un rapporto non blocca più la finestra. Nodus percorre l'intero corpus più volte per ogni rapporto, e ognuna di quelle ricerche lasciava l'applicazione ferma per tutta la sua durata. Ora procedono a tratti e restituiscono il controllo tra l'una e l'altra, così puoi continuare a lavorare mentre il rapporto viene scritto.",
];

const RELEASE_3_2_1_IT: string[] = [
  "Un rapporto di Deep Research scritto sul telefono o su un altro computer ora arriva al vault. Il server accettava soltanto modifiche da 64 KB e un rapporto di quindici pagine occupa quasi il triplo, quindi veniva sempre rifiutato. Il limite sale a 256 KB per modifica e chi amministra un server può regolarlo.",
  "Una modifica che il server non può accettare ora spiega perché. Prima diceva soltanto che era troppo grande, senza dire quanto occupava né quale fosse il massimo. E una coda di modifiche che non entrava in un invio restava bloccata per sempre. Ora viene divisa in invii più piccoli finché non si svuota.",
];

const RELEASE_3_2_2_IT: string[] = [
  "Un errore di sincronizzazione già risolto smette di essere mostrato. Il pannello del vault poteva mostrare un guasto del server per tutto il resto della sessione, proprio accanto a una pubblicazione andata a buon fine. L'avviso sparisce appena la sincronizzazione torna a funzionare.",
];

const RELEASE_3_2_3_IT: string[] = [
  "La ricerca sul telefono smette di fallire quando ciò che cerchi compare in un tema, in un personaggio o in una scena. Bastava una sola di quelle schede perché l'app non riuscisse a leggere la risposta e non mostrasse alcun risultato. Ora ogni risultato arriva identificato e l'elenco si apre per intero.",
  "Un rapporto di Deep Research si può contrassegnare come letto, sul computer e sul telefono. La galleria lo dice a colpo d'occhio, con un contrassegno sulla copertina e il titolo più leggero, così non serve più aprire venti rapporti per capire quale resta da leggere.",
  "Sul telefono, seleziona un passaggio di un rapporto e conservalo come segnalibro di lettura. Ce n'è uno solo per rapporto, resta segnato nel testo stesso e riaprendo il rapporto si arriva proprio lì. Toccando il passaggio segnato lo puoi togliere.",
  "Ogni opera sul telefono ha ora un pulsante che la apre in Zotero per iPhone e iPad. La chiave di Zotero smette di essere una riga morta della scheda e diventa la via di ritorno al PDF, alle note e alle annotazioni che stanno nell'altra applicazione.",
];

const RELEASE_3_2_7_IT: string[] = [
  "Deep Research introduce evidenziazioni in sei colori, commenti a margine e un evidenziatore che può restare attivo. Anche i segnalibri passano al margine. Tutto viene salvato nel deposito e sincronizzato tramite Nodus Server tra computer e dispositivo mobile, anche se il telefono perde la connessione mentre annoti.",
  "Tornare a un rapporto è più facile. La biblioteca può separare i rapporti letti da quelli ancora da leggere, e i loro indicatori restano chiari sia in modalità chiara sia scura. Il segnalibro porta al passaggio esatto dalla barra e si rimuove dalla sua icona a margine. Le evidenziazioni spariscono con un clic, mentre i commenti si possono modificare o eliminare con conferma.",
  "Il Grafo ora si apre come un atlante leggibile del corpus. Prima mostra una costellazione di temi, entrando in uno rivela le idee più collegate, e le viste di contraddizioni, lettura, elementi in attesa e autori presentano scene delimitate. I corpora grandi si caricano per livelli invece di trasformarsi in un groviglio.",
  "Le risposte in corso non sembrano più un messaggio vuoto. Nodi e l'Assistente di ricerca mostrano lo stesso indicatore animato a tre punti mentre pensano, adattato sia alla finestra principale sia a quella mobile.",
];

const RELEASE_3_2_6_IT: string[] = [
  "Il livello di ragionamento appartiene ora a ogni attività. Prima, alzarlo su Immersione lo alzava anche su Deep Research e su tutte le altre che usavano quel modello. Ora ogni attività conserva il proprio, e in Fornitori si continua a fissare il valore predefinito del modello.",
  "Quel livello comanda anche sulle scansioni. L'estrazione, i riassunti e la fusione lo ignoravano del tutto e giravano sempre al livello più economico, qualunque cosa dicesse il selettore. Se non ne scegli nessuno, continuano a girare senza ragionamento ed esattamente alla stessa velocità.",
  "Idee consulta ora il deposito ogni volta che vi entri. Se una scansione terminava mentre eri in un'altra sezione, al ritorno poteva continuare a mostrare a lungo il conteggio precedente. Il primo caricamento riporta sempre le idee e il totale attuali.",
  "Svuotare le notifiche funziona allo stesso modo da Nodi e dall'intestazione. Dopo la conferma rimuove l'attività recente e scarta gli avvisi già visibili, mentre quelli futuri possono ancora arrivare. Le anteprime delle citazioni nella finestra mobile non restano più bloccate sul caricamento.",
  "Nodi può leggere per intero i rapporti di Deep Research e le Immersioni della vista corrente. Selezionando un passaggio compare una barra per copiarlo, lasciare un segnalibro persistente o chiedere a Nodi con quelle parole già citate. Funziona dentro Nodus e nella finestra mobile.",
  "Autori guadagna una vista Salvati accanto alle schede e alla matrice di sintesi. Puoi salvare qualcuno dalla scheda o dal dossier e ritrovarlo anche dopo una nuova scansione del deposito. Ricerca, filtri, esportazione e navigazione nel grafo restano disponibili dentro quella selezione.",
  "Novità e l'aggiornamento smettono di consumare risorse dopo essersi presentati. Le animazioni decorative si fermano, l'avanzamento del download si aggiorna a un ritmo ragionevole e la finestra di aggiornamento viene smontata alla chiusura. Anche la vecchia galleria mobile non ricompare nelle versioni successive.",
  "Gli assistenti collegati tramite MCP possono consultare ogni livello leggibile del deposito attivo, anche dopo aver cambiato tipo di deposito quando il client conserva un catalogo precedente. Possono anche elencare i Deep Research salvati e aprire il contenuto completo di ciascun rapporto. Le grandi raccolte si percorrono pagina per pagina senza raggiungere il limite di risposta.",
];

const RELEASE_3_2_5_IT: string[] = [
  "Le analisi tornano a creare idee nuove nei corpora grandi. Superate le 9999 idee, Nodus non sapeva più numerare la successiva e l'analisi approfondita di ogni opera falliva proprio alla fine, quando tutto il lavoro dell'IA era già stato speso. Un corpus fermo da settimane torna a crescere.",
  "La coda di analisi dice perché qualcosa è fallito. Prima mostrava solo «Fallito» e il motivo restava nella console di sviluppo, dove nessuno sarebbe andato a guardare. Lo stato di un'opera fallita porta ora il messaggio al passaggio del mouse, senza uscire dalla barra.",
  "Il livello di ragionamento si sceglie dove si sceglie il modello. In Impostazioni › Modelli, ogni attività che usa un modello Codex porta il suo livello accanto, da Basso a Massimo. Meno ragionamento risponde prima, e in un'analisi lunga quella differenza si misura in ore.",
  "Quel livello appartiene al modello, non all'attività. Sceglierlo in Modelli o in Fornitori è la stessa scelta, e tutte le attività che usano quel modello rileggono lo stesso valore. Lasciato su Predefinito, continua a seguire la raccomandazione del modello stesso anche se Codex la cambia.",
];

const RELEASE_3_2_4_IT: string[] = [
  "Le notifiche hanno ora un pulsante tutto loro nell'intestazione, subito prima di Impostazioni. Apre le stesse due liste che mostra Nodi: gli avvisi pubblicati da Nodus e quello che l'applicazione ha fatto. Funziona anche con la mascotte disattivata, che era proprio il caso in cui non c'era modo di raggiungerle.",
  "Nodus può ora dirti qualcosa tra una versione e l'altra: un sondaggio, un problema noto, una modifica importante. Ogni avviso arriva nella tua lingua, può contenere un link e resta da leggere finché non lo leggi, uno alla volta. Si disattiva nelle Impostazioni, e da quel momento Nodus smette di richiederlo.",
  "L'intestazione resta con meno icone. Depositi, Collezioni e Roadmap escono dalla barra di destra. Il deposito attivo si apre dal distintivo al centro, che ora si vede a qualsiasi larghezza di finestra. Collezioni vive nella palette dei comandi e la roadmap si trova nelle Impostazioni, dentro Informazioni su Nodus.",
  "La casella in arrivo compare solo quando è arrivato qualcosa da un altro dispositivo. Su un computer senza depositi collegati era un'icona perennemente vuota accanto a un'altra che non lo è mai. Anche il pulsante di aggiornamento sparisce dai depositi di fonti primarie, che non si sincronizzano con Zotero.",
  "Nodus dice finalmente dove trovarlo fuori dall'applicazione. La finestra delle novità e le Impostazioni, in Informazioni su Nodus, portano a Reddit, YouTube e X con l'icona di ogni rete. I collegamenti si aprono nel tuo browser e l'applicazione non invia nulla a quelle reti.",
  "Nodus mostra come si presenta su un telefono. Una galleria che compare una sola volta percorre nove schermate dell'app per il telefono, dice che cosa fa già e che cosa non fa ancora, e rimanda a un breve sondaggio su quanto ti interessa. Le immagini e il modulo sono in inglese, e la galleria stessa lo avverte.",
  "Leggere un rapporto sul telefono cambia in tre punti. Seleziona un passaggio e fai una domanda su di esso: le parole entrano nella conversazione di quel rapporto come citazione. Segnalibro e Chiedi ora vengono per primi nel menu di selezione, prima di Copia. Una fonte si apre nell'istante in cui viene premuta, e le citazioni che avevano smesso di rispondere si riaprono.",
  "Il motore di IA locale di Nodus smette di rispondere all'indirizzo sbagliato quando era già in funzione. La richiesta che avviava il server raggiungeva l'interfaccia giusta, quelle che lo trovavano acceso no, ed è da lì che arrivavano vettori vuoti, senza alcun avviso. Ora entrambi i percorsi leggono lo stesso indirizzo, e un test li tiene insieme.",
  "I pulsanti che arrivavano senza la loro icona ora ce l'hanno. Un nome che il set di icone non possiede non disegna nulla, così il pulsante restava al suo posto e si poteva premere mostrando uno spazio vuoto, come accadeva ad Avanti in Lacune accanto a un Indietro che la freccia ce l'aveva. Dodici nomi distribuiti su ventisei punti tornano a essere disegnati, e un test rifiuta qualsiasi icona inesistente.",
  "Un deposito accademico si apre con meno sezioni. Lacune diventa una scheda dentro Copertura, perché una lacuna significa qualcosa solo guardando che cosa manca alla tua domanda. Ipotesi e Percorso di lettura restano nascosti all'inizio, dato che su un corpus appena sincronizzato rispondevano con rumore. Entrambi tornano dalle Impostazioni.",
];

export const RELEASE_NOTES_IT: Record<string, string[]> = {
  "4.0.0": [
    "Biblioteca riunisce Globale e Questo vault in un'unica schermata. Chi aggiorna da Nodus 3 conserva inizialmente corpus, filtri, analisi e raccolte monitorate, e può attivare la biblioteca trasversale quando preferisce.",
    "La migrazione globale è facoltativa, mostra inventario, spazio e avanzamento e può essere annullata, ripresa o invertita senza modificare i vault di origine. Prima di convertire i dati, il primo avvio di Nodus 4 crea e verifica una copia di ripristino pre-v4.",
    "Nodus può ora gestire una biblioteca senza Zotero. Crea e modifica riferimenti, autori, tag, relazioni, allegati e raccolte, usa ricerche intelligenti e cestino, risolve identificatori e produce importazioni, esportazioni e citazioni offline.",
    "La Biblioteca si adatta al lavoro quotidiano. Trascina file in una raccolta, apri le azioni con il tasto destro, configura e sposta le colonne e lascia che Nodus deduca la scheda. I documenti brevi mostrano l’avanzamento, quelli lunghi entrano in una coda in background mentre si apre l’originale.",
    "Il lettore pulito mantiene separato l'originale e collega testo, pagine, immagini, tabelle e figure. Permette evidenziazioni, note, segnalibri di sezione e domande in chat, mentre impronte esatte impediscono alle analisi obsolete di apparire attuali.",
    "Il lettore apre Markdown pulito, PDF, EPUB, documenti, fogli di calcolo e immagini in schede compatte. La ricerca funziona in ogni formato, le viste continua e a pagina singola conservano le evidenziazioni durante lo zoom e la chat condivide le capacità di Nodi per citare documento e vault.",
    "Le citazioni arrivano in Biblioteca, Word e LibreOffice con riferimenti attivi, note e bibliografie. I selettori cercano senza dipendere da trattini o accenti e il gestore installa stili dal repository CSL ufficiale o da Zotero preservandone la licenza. Il connettore del browser aggiunge pagine e file con raccolta e tag.",
    "Nodus 4 è pubblicato esclusivamente con licenza AGPL-3.0. Informazioni su Nodus mostra la licenza e il codice sorgente esatto di questa versione, e Nodus Server offre lo stesso collegamento a chiunque lo utilizzi tramite la rete.",
  ],
  "3.2.7": RELEASE_3_2_7_IT,
  "3.2.6": RELEASE_3_2_6_IT,
  "3.2.5": RELEASE_3_2_5_IT,
  "3.2.4": RELEASE_3_2_4_IT,
  "3.2.3": RELEASE_3_2_3_IT,
  "3.2.2": RELEASE_3_2_2_IT,
  "3.2.1": RELEASE_3_2_1_IT,
  "3.2.0": RELEASE_3_2_0_IT,
  "3.1.0": RELEASE_3_1_0_IT,
  "3.0.4": RELEASE_3_0_4_IT,
  "3.0.3": RELEASE_3_0_3_IT,
  "3.0.2": RELEASE_3_0_2_IT,
  "3.0.1": RELEASE_3_0_1_IT,
  "3.0.0": RELEASE_3_0_0_IT,
  "2.7.0": RELEASE_2_7_0_IT,
  "2.6.3": RELEASE_2_6_3_IT,
  "2.6.2": RELEASE_2_6_2_IT,
  "2.6.1": RELEASE_2_6_IT,
  "2.6.0": RELEASE_2_6_IT,
  "2.5.4": [
    "PDF Presenter ora importa direttamente presentazioni PowerPoint, OpenDocument e Keynote oltre ai PDF. Nodus le converte localmente tramite PowerPoint, Keynote o LibreOffice installati, conserva le note del relatore quando il formato lo consente e non modifica il file originale.",
    "Quando chiudi la finestra principale su macOS senza uscire da Nodus e poi riapri l'app, vengono ripristinati correttamente sia la finestra sia il compagno Nodi sempre in primo piano, se era attivato."
  ],
  "2.5.3": [
    "PDF Presenter è molto più solido: gli strumenti di annotazione rispondono in modo affidabile, supportano scorciatoie e ridimensionamento in tempo reale, mentre la modalità presentatore funziona meglio con uno o più schermi e dal telecomando mobile. Puoi inoltre importare ed esportare le note del relatore in TXT e ridimensionare liberamente i video di YouTube.",
    "OCR Workspace ora separa «Nuovo OCR» e «Libreria», consente di cercare per titolo o contenuto trascritto e può elaborare più pagine in parallelo in base al provider. Rielaborando una pagina o un documento puoi scegliere un altro modello e vedere meglio l'avanzamento; i modelli locali continuano a lavorare una pagina alla volta per maggiore stabilità.",
    "Nodus Protect uniforma le dimensioni dei controlli e migliora la modifica visiva: la barra nera si regola con un cursore, mentre il suo spessore e la dimensione e intensità della sfocatura si aggiornano immediatamente nell'anteprima.",
    "Le Impostazioni hanno ora una sezione dedicata ad «Aggiornamenti e novità». Privacy, GDPR e Licenze si aprono direttamente in Nodus con contenuti localizzati e un collegamento al documento canonico, invece di mostrare Markdown esterno in un'altra lingua.",
    "Le impostazioni IA distinguono più chiaramente la selezione dei modelli dai servizi locali e vocali, allineano i selettori avanzati e migliorano il contrasto dell'avviso sulla privacy della Docenza. I tuoi modelli preferiti diventano una preferenza globale e restano disponibili quando cambi deposito.",
    "Studio offre ora un flusso di eliminazione sicuro e coerente: seleziona più appunti o materiali, spostali nel cestino e decidi se rimuovere anche idee, embedding, prove e connessioni. Le idee condivise con altre fonti vengono conservate, i processi IA non possono più ricreare contenuti eliminati e le singole idee si possono cancellare dalla loro scheda.",
    "Le intestazioni delle tabelle dei materiali e degli appunti condivisi sono ora centrate e allineate, rendendo più leggibili gli elenchi larghi.",
    "ChatGPT può ora collegarsi a Nodus tramite il tunnel MCP sicuro di OpenAI. Una procedura guidata installa e verifica il client ufficiale, protegge le credenziali, spiega autorizzazioni ed errori con passaggi concreti e si connette senza aprire porte né pubblicare la tua libreria; l'interfaccia è inoltre completamente leggibile nel tema chiaro.",
    "Database aggiunge colonne di confronto che calcolano il valore maggioritario esatto tra più proprietà, per riga o per l'intera colonna. Le colonne di testo e immagine IA possono usare un proprio modello e i processi lunghi conservano l'avanzamento quando cambi vista, con errori e tentativi più chiari.",
    "I messaggi della chat di Nodi ora possono essere selezionati come testo. Ogni risposta ha un pulsante per copiarla e dall'intestazione puoi copiare l'intera conversazione.",
    "La narrazione locale con Kokoro include ora voci in spagnolo di Spagna e dell'America Latina, con normalizzazione e pronuncia adattate affinché date, numeri e testo suonino naturali senza lasciare il dispositivo.",
    "Il deposito Docenza mostra chiaramente il suo stato BETA e lo stato vuoto del registro dei voti torna a offrire l'azione corretta per creare il primo registro."
  ],
  "2.5.2": [
    "Importare file è più diretto: il selettore di sistema si apre subito, senza finestre intermedie. L'avviso prima di registrare con il microfono — dove avvertire le persone che potrebbero essere registrate conta davvero — ora ti permette di accettarlo una volta, accettarlo e non mostrarlo più su questo dispositivo, oppure rifiutarlo.",
    "Corretto un errore per cui cambiare deposito poteva fallire con «table … already exists». I database creati da una versione precedente con una numerazione delle migrazioni diversa si riparano da soli — conservando i tuoi dati — invece di impedire l'apertura."
  ],
  "2.5.0": [
    "Novità in Strumenti: OCR Workspace trascrive PDF scansionati e immagini con qualsiasi modello dotato di visione — locale o nel cloud — e mantiene una libreria di OCR per documento. Ricostruisce un Markdown pulito, lascia intatto l'originale ed esporta il risultato.",
    "PDF Presenter arriva in Strumenti: presenta qualsiasi PDF come diapositive con vista relatore, note del relatore, strumenti di annotazione in tempo reale, video di YouTube per diapositiva e un telecomando dal telefono. La sua libreria conserva copie con cartelle e ricerca; l'originale non viene mai toccato.",
    "Nuovo deposito Docenza per gli insegnanti: organizza corsi, orario, calendario, materiali e registrazioni delle lezioni — riutilizzando il meglio della modalità Studio con un accento proprio — e aggiungi esami e rubriche con l'aiuto dell'IA. Include una demo e un tutorial guidato per iniziare.",
    "Il registro dei voti di Docenza calcola le valutazioni da un piano di valutazione fatto di regole e rubriche: gestisci gruppi di studenti, crea colonne da esami e rubriche, analizza la distribuzione dei risultati ed esporta tabellone, pagelle individuali, CSV e XLSX. I nomi degli studenti non vengono mai inviati all'IA: sono sostituiti da un codice.",
    "Il server MCP cresce: nuovi strumenti di sola lettura per la modalità Docenza, scrittura di righe e celle nei database e una limitazione per tipo di deposito, così ogni client vede solo gli strumenti pertinenti. Gli studenti sono sempre identificati da un codice, mai dal nome.",
    "Nuova categoria di plugin: i copiloti di Nodus per Microsoft Word e LibreOffice Writer funzionano direttamente nel tuo elaboratore di testi — il pannello segue il cursore, analizza il paragrafo, collega ciò che scrivi alla tua libreria e inserisce testo citato redatto dall'IA. Il copilota di Word aggiunge ora note a piè di pagina, redazione sulla selezione (riscrivere, ampliare o ribattere) e ricerca di passaggi citabili. Installali dalle Impostazioni e la connessione si configura da sola.",
    "Maggiore trasparenza sui tuoi dati: Nodus mostra avvisi sulla privacy dove le informazioni vengono elaborate, include un'informativa sulla privacy e avvisi di terze parti e aggiunge misure di conformità delle licenze. Tutta l'elaborazione sensibile rimane locale.",
    "Ora puoi usare il tuo abbonamento a ChatGPT (Codex) o a GitHub Copilot come provider di IA, invece di una chiave API a consumo. Si configurano da Impostazioni → Provider; Nodus avvisa quando un modello attinge alla quota del tuo abbonamento.",
    "L'estrazione delle idee è più affidabile con i modelli locali e del piano gratuito: i modelli di sola visione che restituivano risultati vuoti vengono ora esclusi dall'analisi con un avviso chiaro, e le scansioni approfondita e leggera falliscono con un errore utilizzabile invece di archiviare dati parziali.",
    "La roadmap di Nodus inaugura una vista con lo stato di ogni iniziativa — pianificata, in sviluppo o pubblicata — presentata in un modale cinematografico per vedere a colpo d'occhio dove è diretta l'app.",
    "Nodus è più veloce e più robusto: un audit delle prestazioni accelera nettamente diverse operazioni (miglioramento del testo, percorso di lettura e gallerie), evita i blocchi della finestra principale e rifiuta di aprire due istanze sullo stesso profilo; i backup e la sincronizzazione tra dispositivi ora si ripristinano in modo atomico e tollerano molto meglio i guasti.",
    "Study affina la sua chat: migliora il recupero dei contenuti per rispondere con ciò che si trova nel tuo deposito, corregge diverse traduzioni e ripara i controlli dell'intestazione.",
    "La gestione dei materiali in Studio e Docenza è più comoda: caricali con il trascinamento, rinominali o eliminali e goditi un visualizzatore PDF migliorato. Inoltre, Nodus chiede il consenso esplicito prima di inviare qualsiasi materiale a un modello di IA e i controlli dell'orario rimangono all'interno della loro fascia.",
    "Il deposito accademico dimostrativo inaugura un grafo della conoscenza più ricco — con più idee, temi e connessioni — per esplorare come Nodus mette in relazione la letteratura prima di caricare il tuo corpus.",
    "La chat di Nodi ora cita le fonti del corpus alla base delle sue risposte, proprio come l'assistente di ricerca, così puoi risalire da ogni affermazione alla tua libreria.",
    "Nodi rifinisce il suo aspetto nel tema chiaro: le barre di scorrimento dei suoi pannelli vengono di nuovo visualizzate correttamente."
  ],
  "2.4.0": [
    "Nodi ha un nuovo look tra cui puoi scegliere: mantieni la classica mascotte o passa a un'elegante sfera (una sfera di vetro che contiene una costellazione) e la tua scelta ti seguirà in tutta l'app. Nodi ottiene anche note Markdown rapide che puoi annotare direttamente dal suo menu radiale.",
    "Nodi si comporta in modo più stabile ovunque: la sovrapposizione mobile non sfarfalla più tra le app o quando la trascini e fai clic su di essa, rimbalza uniformemente sui bordi dello schermo, i suoi controlli si adattano al colore della cassaforte attiva e la sfera è perfettamente centrata nel tutorial.",
    "Nodus Toolkit arriva come nuova sezione Strumenti, con il suo primo convertitore, Nodus Convert: converti ed elabora file sul tuo computer, uno alla volta o in batch. Documenti (PDF, DOCX, EPUB, Markdown, HTML e testo), utilità PDF (unisci, dividi, ruota, riordina, estrai immagini e modifica metadati), OCR leggero con PDF ricercabile, immagini (inclusi HEIC, ridimensionamento e compressione) e utilità di testo. Tutto è locale e deterministico; il file originale non viene mai modificato.",
    "Nodus Convert continua a crescere: PDF in immagini, comprimi e converti in scala di grigi, aggiungi numeri di pagina, filigrane e ritaglia margini; nuove opzioni di ritaglio, rotazione, capovolgimento e filigrana per le immagini; e i lavori batch vengono ora consegnati impacchettati in un unico ZIP.",
    "Arriva Nodus Protect: combina PDF e immagini, oscura o sfoca i dati, ritaglia, ruota e raddrizza, aggiunge sette motivi di filigrana e un piè di pagina legale ed esporta copie rasterizzate senza testo o livelli nascosti. Può usare file dal disco o dal deposito, salvarli nella libreria Copie protette e creare o verificare marcature tracciabili IDPS v1 compatibili con IDprotector. Tutta l’elaborazione dei documenti avviene localmente.",
    "L’intera interfaccia di Nodus è ora disponibile anche in italiano, la settima lingua globale. Include navigazione, impostazioni, tutorial, ripristino, messaggi di runtime, vocabolario di ogni deposito, note di versione e Nodus Protect; l’impostazione separata della lingua dei prompt di IA rimane invariata.",
    "Diversi dettagli dell'interfaccia sono stati migliorati: il badge del caveau rimane centrato nell'intestazione invece di spostarsi sotto la guida dell'azione, lo spinner di caricamento della ricerca ora gira correttamente e le superfici e le sostituzioni del tema della luce sono state corrette.",
    "La modalità Novità ora presenta ogni modifica con un'icona per la sua area (deposito, server MCP, Nodi, lingue o strumenti) e raggruppa le modifiche per categoria, ordinate in modo che le aree con il maggior numero di aggiornamenti vengano visualizzate per prime.",
    "Study ora organizza corsi, materie e orari per anno accademico (ad esempio 2024/2025). L’anno è ereditabile – impostalo su un corso e le sue materie lo adottano, o impostalo per materia per una laurea pluriennale – quindi un corso insegnato di nuovo ogni settembre mantiene i materiali e l’orario dell’anno scorso invece di sovrascriverli, con una scorciatoia per copiare un orario in un altro anno accademico.",
    "L’intelligenza artificiale dello studio è più affidabile: le estrazioni non vengono più scartate silenziosamente quando un modello utilizza una formulazione leggermente diversa per le relazioni e le risposte troncate vengono rilevate invece di essere archiviate come dati parziali.",
    "Il server MCP ha ricevuto un controllo completo: una superficie di strumenti unificata e impaginata per ogni tipo di deposito (genealogia ed eventi e archivio di origine primaria, query e filtri di database digitati e banca delle domande di studio) oltre a tre modalità di errore silenzioso corrette, in modo che un corpus non indicizzato, un deposito cambiato o un fornitore di intelligenza artificiale in errore ora riportino chiaramente invece di fuorviare il cliente.",
    "Il selettore della lingua del prompt ora offre le varianti tedesca e portoghese (europea e brasiliana, scritte separatamente, senza alias), quindi le tue idee, rapporti e domande vengono generati nella lingua in cui leggi Nodus; Il turco funziona di nuovo su MCP e diverse traduzioni dell'interfaccia e il fallback inglese sono stati corretti.",
    "La genealogia è più fedele ai tuoi dati: l'importazione e l'esportazione di GEDCOM non trasforma più un bambino adottato in un bambino naturale in viaggio di andata e ritorno tra i programmi, e la rete di relazioni sociali ora mostra il nome di ogni contatto invece di punti anonimi.",
    "La modalità database si muove verso la versione beta con colonne formula costruite da ricette visive (operazioni, statistiche, se/allora con colori, testo combinato) che si comportano come qualsiasi altra colonna per filtri, ordinamenti ed esportazione; L'importazione CSV è notevolmente più veloce, la corrispondenza collettiva degli allegati è più intelligente e gli allegati delle immagini utilizzano le miniature."
  ],
  "2.3.8": [
    "Nodus è ora completamente disponibile in francese, tedesco, portoghese europeo e portoghese brasiliano. Ogni interfaccia mantiene il proprio vocabolario, copre anche tassonomie, parentela e recupero e ritorna in sicurezza all'inglese se manca una traduzione.",
    "La procedura guidata di configurazione dell'archivio ora rileva automaticamente l'intelligenza artificiale disponibile e i modelli di incorporamento tra provider locali e cloud. Combina i risultati in due chiari selettori ricercabili, tollera i provider offline e scarica un modello integrato solo al termine della configurazione.",
    "I controlli radiali di Nodi ora rimangono bilanciati in modo uniforme, rimangono cliccabili negli angoli superiori e rimangono visibili durante il suo addio. Il menu contestuale mantiene in modo affidabile l'azione chiusa e le interazioni evitano l'apertura o la chiusura accidentale.",
    "L'icona Nodus ora mantiene la stessa \"N\" compatta e stilizzata sia che l'applicazione sia aperta o chiusa. L'icona in bundle e le varianti dinamiche condividono una geometria, impedendo a macOS di mostrare un segno di grandi dimensioni dopo l'uscita."
  ],
  "2.3.7": [
    "L'albero genealogico è ora più diretto ed espressivo: trascina per spostarti, apri la cartella laterale con un clic e centra una persona con un doppio clic. I rami fondono i colori selezionati per entrambi i genitori ed evidenziano in oro i discendenti della persona focus; vengono ora distinti anche i rapporti familiari e sociali iniziali.",
    "La sequenza temporale e la mappa della genealogia ora presentano filtri a selezione multipla, schede più chiare, miniature e accesso completo ai dossier quando si fa clic su una persona. I problemi di sfarfallio e stratificazione sono scomparsi, la mappa si adatta ai punti visibili e i collegamenti di credito si aprono in modo sicuro nel browser.",
    "L'archivio genealogico ora porta la creazione delle voci in un'unica modalità ben organizzata, accetta qualsiasi tipo di allegato e supporta le importazioni da Zotero. I dossier personali includono anche un identificatore nazionale opzionale ricercabile in tutto il deposito.",
    "Ora è possibile scaricare i materiali di studio, rivelare il nome di ciascuna azione al passaggio del mouse e apparire correttamente all'interno dei corsi e delle materie assegnati. Nodi, chat e strumenti AI possono utilizzare il contenuto indicizzato di immagini, PDF e altri file.",
    "Study ora include una ricerca approfondita incentrata sull'apprendimento e riutilizza lo stesso grafico e motore di idee, design e funzionalità dei depositi accademici, mantenendo isolato il contenuto di ogni deposito. I nomi degli orari rimangono leggibili e il selettore non duplica più le emoji.",
    "Le procedure guidate per la creazione di archivi accademici, genealogici, di studio e di database ora ti consentono di scegliere modelli separati di intelligenza artificiale e di incorporamento, locali o basati su cloud, e di scaricare un modello locale quando necessario.",
    "Nodi contrae e gira gli arti mentre pensa, chiude gli occhi e ritorna dolcemente alla sua posa normale. Può anche essere trascinato sullo schermo intero e chiuso dal menu contestuale con un addio animato che ne spiega l'estetica.",
    "L'interfaccia ora mantiene il colore attivo del vault mentre ridimensiona la barra laterale, dà alle carte di creazione una dimensione coerente e corregge le superfici chiare, i pulsanti, i campi di ricerca e i menu a discesa. Le icone Novità identificano anche il relativo gruppo al passaggio del mouse.",
    "Nodus ora esegue un controllo di aggiornamento cinematografico all'avvio, segnalando se sei aggiornato, è disponibile una nuova versione o si è verificato un errore. Mostra l'avanzamento del download e supporta l'installazione e il riavvio senza sovrapporsi alla modalità Novità."
  ],
  "2.3.6": [
    "La parentela viene ora completamente ricalcolata ogni volta che cambia la persona focus: coniugi, genitori, figli, fratelli, suoceri, famiglie miste, cugini di qualsiasi grado e le relazioni intergenerazionali ricevono la loro etichetta precisa, anche negli alberi estesi. Anche Nodi e l'assistente capiscono queste relazioni calcolate.",
    "Il dossier della persona presenta ora Varianti del nome, Parentela, Eventi della vita, Luoghi, Documenti, Prove e Note in sezioni coerenti con Biografia e Relazioni. Varianti, eventi e luoghi vengono aggiunti tramite modalità pulite con pulsanti di dimensioni uniformi.",
    "L'icona Nodus aggiornata viene ora conservata anche durante il lancio di un'applicazione a freddo, prima che il vault attivo venga caricato.",
    "La modalità Novità ora mostra la cronologia completa della versione principale installata, ad esempio ogni versione 2.x, in inglese o spagnolo. Ogni modifica storica include anche l'icona e il colore della cassetta, oppure l'indicatore generale quando influisce sull'intera applicazione."
  ],
  "2.3.5": [
    "I rami estesi non si mescolano più: zii, zie e i loro partner rimangono all’interno del corrispondente blocco paterno o materno, con la coppia genitoriale come punto centrale e ogni generazione allineata in modo coerente.",
    "I filari di alberi orizzontali vengono ora percorsi esclusivamente attraverso lo spazio libero tra le generazioni. Anche i nomi, le etichette di parentela e le date hanno uno sfondo protettivo in modo che rimangano leggibili sia in modalità chiara che scura.",
    "L'albero ora include la ricerca tra nomi, date ed etichette di parentela, con corrispondenza senza accento. Le corrispondenze vengono evidenziate mentre il resto dell'albero rimane visibile in uno stato oscurato per preservare il contesto familiare."
  ],
  "2.3.4": [
    "L'albero ora mantiene separati i nuclei familiari, evitando che le linee dei nonni paterni e materni vengano unite in modo errato. I rami paterni e materni utilizzano il blu e il rosso per impostazione predefinita, ti consentono di scegliere i loro due colori principali e di distinguere i rami secondari attraverso variazioni tonali.",
    "Ogni persona ora mostra un'etichetta di parentela relativa alla persona focus dell'albero, inclusi genitori, fratelli, zii e zie, cugini, nipoti e nipoti, nonni, bisnonni, trisnonni e i loro discendenti equivalenti. Le etichette vengono ricalcolate quando cambia il focus e vengono incluse anche nel contesto Nodi e assistente.",
    "Le relazioni familiari e sociali ora condividono un'interfaccia più pulita: ogni sezione mantiene il suo elenco persistente e fornisce un pulsante che apre una modalità di aggiunta o modifica. I selettori includono la ricerca, supportano più persone e le relazioni sociali ti consentono di scegliere uno o più tipi predefiniti in un'unica operazione.",
    "Diversi dettagli dell'interfaccia sono stati migliorati: il marchio Nodus mantiene il suo margine quando la barra laterale è nascosta, la prima persona nell'elenco non viene più ritagliata, i menu a discesa appaiono sopra le modalità senza sovrapporre l'icona di ricerca e il testo e il banner di supporto non duplica più il pulsante PayPal."
  ],
  "2.3.3": [
    "I rapporti familiari ora possono essere creati da un dossier personale o direttamente dall'albero con un chiaro selettore: genitore, figlio, fratello o partner. Quando aggiungi un bambino, puoi specificare entrambi i genitori conosciuti o solo uno.",
    "La barra laterale dell'albero ora mantiene visibile ogni relazione della persona selezionata, quindi puoi modificarla, invertirla o eliminarla. Avverte inoltre sulle date cronologicamente improbabili senza bloccare i casi storici che è necessario documentare.",
    "L'albero ora posiziona gli antenati in alto per impostazione predefinita e può facoltativamente invertire il suo orientamento. Il layout e i connettori di genitore, figlio, fratello e partner sono stati corretti mantenendo compatibili le relazioni esistenti.",
    "La modalità Novità ora identifica visivamente ogni modifica: le modifiche generali utilizzano un'icona neutra, mentre le modifiche specifiche del vault mostrano il colore e l'icona corrispondenti sia in modalità chiara che scura."
  ],
  "2.3.2": [
    "Risolto un problema che impediva a Nodus di leggere alcune chiavi API AI salvate in precedenza, facendole scomparire dalle Impostazioni. Le chiavi non erano state cancellate: Nodus le recupera in modo sicuro e le include nuovamente nel backup del workspace protetto.",
    "Nodus ora rileva nuovamente il modello utilizzato per creare ciascun indice dello spazio di lavoro. Se i tuoi incorporamenti sono stati generati, ad esempio, con BGE-M3 tramite OpenRouter, quel modello viene selezionato nuovamente senza eliminare o reindicizzare alcun vettore.",
    "Vengono ripristinati anche i modelli preferiti e le selezioni per attività conservati prima della migrazione. La modalità di base o avanzata e il modello di incorporamento appartengono nuovamente a ciascuna area di lavoro, impedendo a un'area di lavoro di sovrascriverne un'altra."
  ],
  "2.3.1": [
    "Risolto un problema che impediva a Nodus di leggere alcune chiavi API AI salvate in precedenza, facendole scomparire dalle Impostazioni. Le chiavi non sono state cancellate: questa versione le recupera in modo sicuro, conserva le loro precedenti copie crittografate e le include nuovamente nel backup dell'area di lavoro protetta.",
    "Su macOS, Portachiavi potrebbe richiedere l'autorizzazione durante il ripristino. Verifica che la richiesta appartenga a Nodus e scegli “Consenti sempre”; se l'hai ignorato, riprova da Impostazioni → Provider."
  ],
  "2.3.0": [
    "Study Vault fa un grande passo avanti: corsi e materie, cartelle e appunti, materiali annotabili, registrazioni con trascrizioni, orari, calendario, banca delle domande, test, flashcard, revisioni, progressi, un grafico della conoscenza e chat basata sulla fonte.",
    "L'integrazione di Zotero va più in profondità: i vault possono utilizzare le librerie di gruppo e, da corsi o materiali, cercare un elemento e scegliere se importare il suo allegato in Nodus o mantenere un collegamento che lo apra in Zotero.",
    "Groq e Cerebras si uniscono ai fornitori di intelligenza artificiale, con la scoperta del modello ogni volta che il fornitore lo supporta. La configurazione di base e avanzata ora richiede conferma prima di cambiare modalità, impedendo configurazioni accidentali del modello incomplete.",
    "I modelli locali sono più facili da usare: scarica, seleziona e rimuovi modelli integrati per diverse attività e quando un modello richiede prima un motore, Nodus lo installa automaticamente prima di avviare il download.",
    "Una nuova guida essenziale al cinema con protagonista Nodi spiega casseforti, fornitori, modelli, incorporamenti e discorsi. Nodi viene presentato alla fine, rimane più calmo per tutto il tour e non si sovrappone più al compagno dal vivo.",
    "Un nuovo sistema di ripristino completo protegge automaticamente ogni deposito, documento, impostazione, cronologia, file e chiave in istantanee crittografate all'interno di una cartella sicura. Include una chiave di ripristino e un assistente di migrazione per installazioni precedenti, compatibile con le cartelle sincronizzate da Google Drive, Dropbox, iCloud e servizi simili.",
    "Le demo Academic, Genealogy, Databases e Study sono state ampliate in modo che nessuna sezione inizi vuota: includono cartelle, note, materiali, conversazioni, report ed esempi collegati che puoi esplorare e rimuovere in seguito.",
    "Nodi ora chiude correttamente il menu, la chat e i pannelli quando si fa clic altrove. Anche l'esperienza mobile e le animazioni dei tutorial sono state migliorate e l'icona dell'app ora mantiene l'archivio attivo e l'aspetto del tema dopo l'uscita.",
    "La navigazione nella barra laterale ora sembra più coerente: il marchio Nodus rimane centrato mentre il menu viene ridimensionato e l'intera intestazione può mostrarlo o nasconderlo.",
    "Il pannello Novità ora ha una presentazione cinematografica con Nodi che celebra, versioni e modifiche chiaramente visibili in modalità chiaro e scuro, oltre a una sezione opzionale per supportare il progetto open source tramite PayPal."
  ],
  "2.2.0": [
    "Ti presento Nodi, la nuova mascotte di Nodus: un piccolo nodo di luce che ti tiene compagnia, fluttuante in basso a destra. Trascinalo nella finestra e attivalo o disattivalo in Impostazioni → Interfaccia.",
    "Fai clic su Nodi per aprire il suo menu: una chat con un'IA che conosce Nodus e la tua configurazione, un centro notifiche (contrassegna gli elementi non letti con un punto rosso e una mano alzata) e una guida rapida. Nodi cambia persino abito per adattarsi alla modalità del caveau (accademico, genealogico, database), che puoi disattivare se preferisci il semplice Nodi.",
    "Se lo desideri, Nodi può vivere in una piccola finestra mobile del desktop, sempre in primo piano rispetto alle altre app, anche a schermo intero, quindi è sempre a portata di mano senza cambiare app."
  ],
  "2.1.1": [
    "I modelli che scegli per ciascun fornitore e per ciascuna attività di intelligenza artificiale sono ora condivisi in tutti i tuoi depositi, proprio come lo erano già le tue chiavi API. Configurali una volta e saranno pronti in ogni caveau.",
    "Poiché i depositi condividono chiavi e modelli, abbiamo rimosso il messaggio \"carica chiavi API da un altro deposito\": non era più necessario."
  ],
  "2.1.0": [
    "Nodus introduce la modalità Database: un gestore di database in stile Notion all'interno del tuo vault. Costruisci tabelle con molti tipi di colonne (testo, numero, selezione, data, relazione, rollup, immagine...), organizza i dati in diverse visualizzazioni con filtri e ordinamento e modifica tutto direttamente nella griglia. Importa ed esporta CSV ogni volta che ne hai bisogno.",
    "Colonne AI: lascia che l'IA riempia un'intera colonna dal resto della riga, con testo (riepiloghi, classificazioni, traduzioni) o con immagini generate. E una chat integrata risponde alle domande sui dati della tua tabella.",
    "Analisi statistica onesta: l'intelligenza artificiale propone le giuste analisi sulle colonne reali (correlazioni, chi-quadrato, ANOVA, regressione) e l'app le calcola in modo deterministico, con grafici nativi: mappe di calore, grafici a dispersione e grafici a scatola. I piani dell'IA; il motore calcola, senza numeri inventati.",
    "L'archivio genealogico è ricostruito come una griglia modificabile in stile database: modifica ogni cella in linea, archivia i documenti in più cartelle contemporaneamente e classificali con una tassonomia di oltre 190 tipi di documenti del patrimonio, completi di ricerca intelligente e filtri sfaccettati."
  ],
  "2.0.2": [
    "L'Archivio ottiene un campo \"Sorgente\" su ogni documento: registra da dove proviene (l'archivio o il repository, una citazione o un URL). È la spina dorsale di una buona citazione genealogica e viaggia con i tuoi backup come il resto del documento."
  ],
  "2.0.1": [
    "Il commutatore del deposito ora mostra un badge con il tipo di ciascun deposito (Accademico, Genealogico...) e l'etichetta \"Attivo\" e il pulsante \"Carica\" condividono finalmente la stessa tipografia.",
    "Nel dossier persona, i pulsanti di modifica ed eliminazione delle relazioni sociali sono ora icone, e il pannello verticale “Regola inquadratura” si chiude con un clic esterno e non è più disallineato.",
    "Risolto il problema con la finestra delle novità: ora appare correttamente dopo l'aggiornamento e recupera le modifiche 2.0.0 se le hai perse."
  ],
  "2.0.0": [
    "Nodus introduce i tipi di deposito: ogni deposito ora ha una modalità che personalizza le sezioni mostrate e il personaggio dell'assistente AI. Questa versione include due modalità, \"Accademica\" e \"Genealogia\", e prevede un'anteprima di quelle successive: Studio, Fonti primarie e Database.",
    "Nuova modalità Genealogia: ricostruisci la storia familiare da fonti primarie con dossier personali, un albero genealogico, una cronologia, un archivio di prove e una mappa reale. L'assistente funge da genealogista e propone la parentela in base alle prove, seguendo lo standard della prova genealogica.",
    "Relazioni sociali: una seconda rete, indipendente dalla parentela, per amicizie, mecenatismo, impiego, rivalità e corrispondenza - il materiale dello storico sociale e prosopografico.",
    "Deep Research apprende la genealogia: compone un rapporto genealogico sull'archivio e sulla biblioteca indicizzati per incorporamento. L'intestazione ora mostra la modalità del deposito attivo nel suo colore principale.",
    "Backup multi-deposito: il sistema di backup automatico crittografato ora copre tutti i tuoi depositi con rotazione generazionale."
  ],
  "1.8.0": [
    "Nuovo copilota di scrittura per LibreOffice Writer (Linux, macOS e Windows): installa la macro da Impostazioni → Copilota di scrittura (LibreOffice), eseguila in Writer e il riquadro copilot segue il cursore per analizzare il paragrafo e inserire il testo citato redatto da AI. La connessione si configura da sola.",
    "Nodus sbarca su Linux: ogni versione ora include programmi di installazione .deb e AppImage e l'app eredita il tema del cursore di sistema su Wayland.",
    "Le lingue di richiesta ora includono il francese e il turco: idee, rapporti di ricerca approfondita e bozze di workshop possono essere generati anche in quelle lingue. Le citazioni letterali mantengono sempre la lingua di partenza.",
    "Risolto: i PDF locali allegati dopo una prima scansione vengono ripresi durante la sincronizzazione invece di rimanere contrassegnati come \"senza testo\" per sempre.",
    "Questa versione include il primo contributo esterno del progetto: il copilota di LibreOffice, i pacchetti Linux e i nuovi linguaggi nati dal lavoro di Oğuz Karayemiş (@oguzkarayemis). Grazie!"
  ],
  "1.7.5": [
    "I modelli locali (LM Studio / Ollama) con una piccola finestra di contesto non falliscono più nell'assistente di ricerca: l'app ora adatta il contesto alla finestra del modello in modo che possa sempre rispondere.",
    "Le citazioni dai modelli locali ora vengono visualizzate correttamente come \"Autore, Anno\" invece dell'ID dell'idea interna.",
    "La procedura guidata di configurazione ora mostra le raccolte come una struttura espandibile, in modo da poter monitorare sottoraccolte specifiche quando una raccolta è molto grande."
  ],
  "1.7.4": [
    "Immersion ha una nuova galleria con visualizzazioni a griglia ed elenco, oltre a un pulsante \"Nuova immersione\" con la propria finestra di dialogo, proprio come Deep Research.",
    "Selezione multipla in Ricerca approfondita e Immersione per eliminare più elementi contemporaneamente, con conferma.",
    "Nuovo pulsante \"Traduci\": genera una traduzione AI di un report o di un'immersione in qualsiasi lingua. Ogni traduzione viene salvata per essere riletta, rigenerata o eliminata.",
    "Dopo ogni aggiornamento vedrai questa finestra delle novità con le ultime modifiche e correzioni."
  ],
  "1.7.3": [
    "L'interfaccia non si blocca più mentre l'audio della narrazione viene generato in Ricerca profonda e Immersione.",
    "Risolto il problema con la voce \"Sharvard\": ora appare come una voce maschile, che è ciò che effettivamente rende il motore."
  ]
};
