import type { ReleaseHighlight } from './releaseNotes';

/**
 * v5.4.4: Nodus Research is now available in Simplified Chinese. Behind that, a
 * custom OpenAI-compatible gateway stops dropping long scans, the Documentary
 * Index shows standalone jobs, linking from the global library refreshes the
 * vault list, and the Server image boots again. The languages note is one plain
 * line on purpose: it is the whole news. Keep the IT/TR/ZH arrays aligned with
 * this order: they are matched by index.
 */
export const RELEASE_5_4_4_HIGHLIGHTS: ReleaseHighlight[] = [
  {
    scope: 'languages',
    es: 'Nodus Research ya está disponible en chino simplificado.',
    en: 'Nodus Research is now available in Simplified Chinese.',
    fr: 'Nodus Research est désormais disponible en chinois simplifié.',
    de: 'Nodus Research ist jetzt auf vereinfachtem Chinesisch verfügbar.',
    pt: 'O Nodus Research já está disponível em chinês simplificado.',
    'pt-BR': 'O Nodus Research agora está disponível em chinês simplificado.',
    it: 'Nodus Research è ora disponibile in cinese semplificato.',
    tr: 'Nodus Research artık Basitleştirilmiş Çince dilinde kullanılabiliyor.',
    'zh-CN': 'Nodus Research 现已提供简体中文版本。',
    'zh-TW': 'Nodus Research 現已提供簡體中文版本。',
  },
  {
    scope: 'ai',
    es: 'Los escaneos sobre una pasarela propia dejan de morir por una conexión caída. Un fallo de socket sin estado, el «Connection error.» del SDK o un reinicio de conexión, ahora se trata como recuperable, así que la cola vuelve a intentarlo en lugar de darse por vencida. Nodus también envía al proveedor personalizado el esfuerzo de razonamiento que elijas y pide a un modelo con razonamiento que omita su traza privada en los escaneos de fondo, que era lo que agotaba el presupuesto y alargaba la generación hasta que la pasarela la cortaba.',
    en: 'Scans on a custom gateway stop dying from a dropped connection. A status-less socket failure, the SDK’s “Connection error.” or a connection reset, is now treated as recoverable, so the queue retries instead of giving up. Nodus also forwards the reasoning effort you choose to a custom provider and asks a thinking model to skip its private trace on background scans, which is what exhausted the budget and stretched the generation until the gateway cut it.',
    fr: 'Les analyses via une passerelle personnalisée ne meurent plus d’une connexion coupée. Une panne de socket sans statut, le « Connection error. » du SDK ou une réinitialisation de connexion, est désormais considérée comme récupérable, et la file réessaie au lieu d’abandonner. Nodus transmet aussi au fournisseur personnalisé l’effort de raisonnement que vous choisissez et demande à un modèle de raisonnement d’omettre sa trace privée lors des analyses en arrière-plan, ce qui épuisait le budget et allongeait la génération jusqu’à ce que la passerelle la coupe.',
    de: 'Scans über ein eigenes Gateway sterben nicht mehr an einer abgebrochenen Verbindung. Ein Socket-Fehler ohne Status, der „Connection error.“ des SDK oder ein Verbindungs-Reset, gilt jetzt als behebbar, sodass die Warteschlange erneut versucht statt aufzugeben. Nodus leitet außerdem den gewählten Denkaufwand an einen benutzerdefinierten Anbieter weiter und bittet ein Denkmodell, bei Hintergrund-Scans seine private Spur auszulassen, was das Budget aufbrauchte und die Generierung verlängerte, bis das Gateway sie abschnitt.',
    pt: 'As análises através de uma passagem própria deixam de morrer por uma ligação caída. Uma falha de socket sem estado, o «Connection error.» do SDK ou um reinício de ligação, passa a ser tratada como recuperável, por isso a fila volta a tentar em vez de desistir. O Nodus também envia ao fornecedor personalizado o esforço de raciocínio que escolher e pede a um modelo com raciocínio que omita a sua traça privada nas análises de fundo, que era o que esgotava o orçamento e prolongava a geração até a passagem a cortar.',
    'pt-BR': 'As análises em um gateway próprio deixam de morrer por uma conexão interrompida. Uma falha de socket sem status, o “Connection error.” do SDK ou um reset de conexão, agora é tratada como recuperável, então a fila tenta de novo em vez de desistir. O Nodus também repassa ao provedor personalizado o esforço de raciocínio que você escolher e pede a um modelo de raciocínio que omita seu traço privado nas análises em segundo plano, que era o que esgotava o orçamento e alongava a geração até o gateway cortá-la.',
    it: 'Le analisi su un gateway personale non muoiono più per una connessione caduta. Un errore di socket senza stato, il «Connection error.» dell’SDK o un reset della connessione, ora viene considerato recuperabile, così la coda riprova invece di arrendersi. Nodus inoltra inoltre al fornitore personalizzato lo sforzo di ragionamento che scegli e chiede a un modello di ragionamento di omettere la sua traccia privata nelle analisi in background, che era ciò che esauriva il budget e allungava la generazione finché il gateway la interrompeva.',
    tr: 'Özel bir ağ geçidi üzerindeki taramalar artık kopan bağlantı yüzünden ölmüyor. Durum kodu olmayan bir soket hatası, SDK’nın «Connection error.» iletisi ya da bir bağlantı sıfırlaması, artık kurtarılabilir sayılıyor ve kuyruk pes etmek yerine yeniden deniyor. Nodus ayrıca seçtiğiniz akıl yürütme eforunu özel sağlayıcıya iletiyor ve bir akıl yürütme modelinden arka plan taramalarında özel izini atlamasını istiyor. Bütçeyi tüketen ve üretimi ağ geçidi kesene kadar uzatan da buydu.',
    'zh-CN': '在自定义网关上运行的扫描不再因为连接中断而失败。没有状态码的套接字故障、SDK 的「Connection error.」或连接重置，现在会被视为可恢复，队列会重试而不是放弃。Nodus 还会把你选择的推理强度转发给自定义提供商，并在后台扫描时要求推理模型跳过其私有思考过程，正是它耗尽了预算并让生成拖到网关切断连接。',
    'zh-TW': '在自定義閘道器上執行的掃描不再因為連線中斷而失敗。沒有狀態碼的套接字故障、SDK 的「Connection error.」或連線重置，現在會被視為可恢復，佇列會重試而不是放棄。Nodus 還會把你選擇的推理強度轉發給自定義提供商，並在後臺掃描時要求推理模型跳過其私有思考過程，正是它耗盡了預算並讓生成拖到閘道器切斷連線。',
  },
  {
    scope: 'library',
    es: 'El Índice documental muestra también los escaneos sueltos. El análisis de una sola obra o la preparación de un Deep Research creaban un trabajo sin campaña que no aparecía en ninguna fila, así que pulsar reintentar encolaba trabajo invisible. Ahora cada uno tiene su fila, con un botón de reintento si falló y otro de cancelación si sigue en marcha, y el panel y el contador de la cabecera lo cuentan como cualquier otro trabajo.',
    en: 'The Documentary Index shows standalone scans too. A single work’s analysis or the preparation of a Deep Research created a job with no campaign that appeared in no row, so pressing retry queued invisible work. Each one now has its own row, with a retry button if it failed and a cancel button if it is still running, and the panel and the header badge count it like any other job.',
    fr: 'L’Index documentaire affiche aussi les analyses isolées. L’analyse d’une seule œuvre ou la préparation d’un Deep Research créaient une tâche sans campagne qui n’apparaissait sur aucune ligne, si bien qu’appuyer sur réessayer mettait en file un travail invisible. Chacune a désormais sa ligne, avec un bouton réessayer en cas d’échec et un bouton annuler si elle tourne encore, et le panneau comme le compteur d’en-tête la comptent comme n’importe quelle autre tâche.',
    de: 'Der Dokumentarische Index zeigt auch einzelne Scans. Die Analyse eines einzelnen Werks oder die Vorbereitung einer Deep Research erzeugte einen Auftrag ohne Kampagne, der in keiner Zeile auftauchte, sodass ein Klick auf Wiederholen unsichtbare Arbeit einreihte. Jeder hat jetzt seine eigene Zeile, mit einer Wiederholen-Schaltfläche bei einem Fehler und einer Abbrechen-Schaltfläche, solange er läuft, und das Panel und der Zähler in der Kopfzeile zählen ihn wie jeden anderen Auftrag.',
    pt: 'O Índice documental mostra também as análises soltas. A análise de uma só obra ou a preparação de um Deep Research criavam um trabalho sem campanha que não aparecia em nenhuma linha, por isso carregar em repetir encolava trabalho invisível. Agora cada um tem a sua linha, com um botão de repetir se falhou e outro de cancelar se ainda está a correr, e o painel e o contador do cabeçalho contam-no como qualquer outro trabalho.',
    'pt-BR': 'O Índice documental também mostra as análises avulsas. A análise de uma única obra ou a preparação de um Deep Research criavam um trabalho sem campanha que não aparecia em nenhuma linha, então apertar repetir enfileirava trabalho invisível. Agora cada um tem sua linha, com um botão de repetir se falhou e outro de cancelar se ainda está rodando, e o painel e o contador do cabeçalho o contam como qualquer outro trabalho.',
    it: 'L’Indice documentale mostra anche le analisi singole. L’analisi di una sola opera o la preparazione di un Deep Research creavano un lavoro senza campagna che non compariva in nessuna riga, così premere riprova accodava lavoro invisibile. Ora ognuno ha la sua riga, con un pulsante riprova se ha fallito e uno annulla se è ancora in corso, e il pannello e il contatore dell’intestazione lo contano come qualsiasi altro lavoro.',
    tr: 'Belgesel Dizini tek başına çalışan taramaları da gösteriyor. Tek bir eserin analizi ya da bir Deep Research hazırlığı, kampanyası olmayan ve hiçbir satırda görünmeyen bir iş oluşturuyordu, bu yüzden yeniden dene’ye basmak görünmez bir işi kuyruğa alıyordu. Artık her birinin kendi satırı var, başarısızsa yeniden dene, hâlâ sürüyorsa iptal düğmesiyle, ve panel ile başlık rozeti onu diğer işler gibi sayıyor.',
    'zh-CN': '文献索引现在也会显示单独的扫描任务。单篇作品的分析或 Deep Research 的准备工作会创建一个没有批次的任务，它不出现在任何一行里，于是点击重试只是把看不见的工作排入队列。现在每个任务都有自己的行，失败时有重试按钮，仍在运行时有取消按钮，面板和标题栏徽章也会像其他任务一样统计它。',
    'zh-TW': '文獻索引現在也會顯示單獨的掃描任務。單篇作品的分析或 Deep Research 的準備工作會建立一個沒有批次的任務，它不出現在任何一行裡，於是點選重試只是把看不見的工作排入佇列。現在每個任務都有自己的行，失敗時有重試按鈕，仍在執行時有取消按鈕，面板和標題欄徽章也會像其他任務一樣統計它。',
  },
  {
    scope: 'library',
    es: 'Enlazar desde la biblioteca global se refleja al instante. Al llevar obras a una bóveda, su lista de Biblioteca se servía de una caché que el enlace no invalidaba, así que al volver a «Esta bóveda» veías la página anterior. Ahora el enlace refresca la lista. La cola de extracción también deja de mostrar mensajes sin traducir, y una fila solo se pinta en rojo cuando el trabajo ha fallado de verdad.',
    en: 'Linking from the global library shows up right away. When you brought works into a vault, its Library list was served from a cache the link never invalidated, so returning to “This vault” showed the previous page. Linking now refreshes the list. The extraction queue also stops showing untranslated messages, and a row is only painted red when the job really failed.',
    fr: 'La liaison depuis la bibliothèque globale s’affiche immédiatement. Lorsque vous ameniez des œuvres dans un coffre, sa liste de bibliothèque provenait d’un cache que la liaison n’invalidait pas, si bien qu’en revenant à « Ce coffre » vous voyiez la page précédente. La liaison actualise désormais la liste. La file d’extraction cesse aussi d’afficher des messages non traduits, et une ligne n’est peinte en rouge que si la tâche a vraiment échoué.',
    de: 'Das Verknüpfen aus der globalen Bibliothek ist sofort sichtbar. Wenn Sie Werke in einen Tresor brachten, wurde dessen Bibliotheksliste aus einem Cache bedient, den die Verknüpfung nie ungültig machte, sodass Sie bei der Rückkehr zu „Dieser Tresor“ die vorherige Seite sahen. Die Verknüpfung aktualisiert die Liste jetzt. Die Extraktionswarteschlange zeigt auch keine unübersetzten Meldungen mehr, und eine Zeile wird nur rot gemalt, wenn der Auftrag wirklich fehlgeschlagen ist.',
    pt: 'Ligar a partir da biblioteca global reflete-se de imediato. Ao trazer obras para um cofre, a sua lista de Biblioteca era servida por uma cache que a ligação não invalidava, por isso ao voltar a «Este cofre» via a página anterior. Agora a ligação atualiza a lista. A fila de extração também deixa de mostrar mensagens sem tradução, e uma linha só fica vermelha quando o trabalho falhou de verdade.',
    'pt-BR': 'Vincular a partir da biblioteca global aparece na hora. Ao levar obras para um cofre, a lista de Biblioteca dele vinha de um cache que o vínculo nunca invalidava, então ao voltar para “Este cofre” você via a página anterior. Agora o vínculo atualiza a lista. A fila de extração também para de mostrar mensagens sem tradução, e uma linha só fica vermelha quando o trabalho realmente falhou.',
    it: 'Il collegamento dalla biblioteca globale si vede subito. Quando portavi opere in un deposito, la sua lista di Biblioteca veniva da una cache che il collegamento non invalidava, così tornando a «Questo deposito» vedevi la pagina precedente. Ora il collegamento aggiorna la lista. Anche la coda di estrazione smette di mostrare messaggi non tradotti, e una riga viene dipinta di rosso solo quando il lavoro è davvero fallito.',
    tr: 'Genel kütüphaneden bağlama anında görünüyor. Eserleri bir kasaya taşıdığınızda, o kasanın Kütüphane listesi bağlamanın geçersiz kılmadığı bir önbellekten geliyordu, bu yüzden «Bu kasa»ya döndüğünüzde önceki sayfayı görüyordunuz. Artık bağlama listeyi yeniliyor. Çıkarma kuyruğu da çevrilmemiş iletileri göstermeyi bırakıyor ve bir satır yalnızca iş gerçekten başarısız olduğunda kırmızıya boyanıyor.',
    'zh-CN': '从全局文献库链接后会立即反映。把作品带入某个 vault 时，它的文献库列表来自一个链接从未失效的缓存，因此返回「此 vault」时看到的还是上一页。现在链接会刷新列表。提取队列也不再显示未翻译的消息，只有当任务真正失败时行才会变红。',
    'zh-TW': '從全域性文獻庫連結後會立即反映。把作品帶入某個 vault 時，它的文獻庫列表來自一個連結從未失效的快取，因此返回「此 vault」時看到的還是上一頁。現在連結會重新整理列表。提取佇列也不再顯示未翻譯的訊息，只有當任務真正失敗時行才會變紅。',
  },
  {
    scope: 'server',
    es: 'La imagen de Nodus Server vuelve a arrancar. Su ruta de PDF importaba una dependencia para recortar los glifos chinos que la imagen no instalaba, así que el contenedor se caía nada más iniciarse. La dependencia ya está declarada y la comprobación de salud del arranque pasa.',
    en: 'The Nodus Server image starts again. Its PDF path imported a dependency for subsetting Chinese glyphs that the image never installed, so the container fell over as soon as it started. The dependency is now declared and the startup health check passes.',
    fr: 'L’image de Nodus Server redémarre. Son chemin PDF importait une dépendance pour découper les glyphes chinois que l’image n’installait pas, si bien que le conteneur tombait dès son démarrage. La dépendance est désormais déclarée et le contrôle de santé au démarrage passe.',
    de: 'Das Nodus-Server-Image startet wieder. Sein PDF-Pfad importierte eine Abhängigkeit zum Zuschneiden chinesischer Glyphen, die das Image nie installierte, sodass der Container beim Start umfiel. Die Abhängigkeit ist jetzt deklariert und die Startprüfung der Gesundheit besteht.',
    pt: 'A imagem do Nodus Server volta a arrancar. O seu caminho de PDF importava uma dependência para recortar os glifos chineses que a imagem não instalava, por isso o contentor caía assim que iniciava. A dependência já está declarada e a verificação de saúde do arranque passa.',
    'pt-BR': 'A imagem do Nodus Server volta a iniciar. Seu caminho de PDF importava uma dependência para recortar os glifos chineses que a imagem não instalava, então o contêiner caía assim que iniciava. A dependência agora está declarada e a verificação de saúde na inicialização passa.',
    it: 'L’immagine di Nodus Server torna ad avviarsi. Il suo percorso PDF importava una dipendenza per ritagliare i glifi cinesi che l’immagine non installava, così il container cadeva appena partiva. La dipendenza ora è dichiarata e il controllo di salute all’avvio passa.',
    tr: 'Nodus Server imajı yeniden başlıyor. PDF yolu, imajın kurmadığı bir bağımlılığı, Çince glifleri kırpmak için içe aktarıyordu, bu yüzden konteyner başlar başlamaz düşüyordu. Bağımlılık artık bildirildi ve başlangıçtaki sağlık denetimi geçiyor.',
    'zh-CN': 'Nodus Server 镜像重新可以启动。它的 PDF 流程引入了一个用于裁剪中文字形的依赖，而镜像从未安装它，于是容器一启动就崩溃。该依赖现已声明，启动时的健康检查通过。',
    'zh-TW': 'Nodus Server 映象重新可以啟動。它的 PDF 流程引入了一個用於裁剪中文字形的依賴，而映象從未安裝它，於是容器一啟動就崩潰。該依賴現已宣告，啟動時的健康檢查通過。',
  },
];
