// SPDX-FileCopyrightText: 2026 Jorge Pérez Burgueño and Nodus contributors
// SPDX-License-Identifier: AGPL-3.0-only
import type { CategorizedReleaseHighlight } from './releaseNotes';

/** Final user-visible outcomes from v5.7.2..044ea310. Pre-release iterations are folded into each feature. */
export const RELEASE_5_7_3_HIGHLIGHTS: CategorizedReleaseHighlight[] = [
  {
    category: 'new', scope: 'drift',
    es: 'Nodus Drift permite combinar hasta seis sonidos ambientales, ruidos o tonos binaurales sin conexión. Ajusta el volumen de cada sonido, guarda mezclas con nombre y encuentra sonidos por búsqueda, favoritos o categorías. Tiene una vista a pantalla completa y un reproductor que permite controlar la mezcla mientras usas otras herramientas de Nodus.',
    en: 'Nodus Drift lets you combine up to six ambient sounds, noises or binaural tones offline. Adjust each sound’s volume, save named mixes and find sounds through search, favourites or categories. It has a fullscreen view and a player that lets you control the mix while using other Nodus tools.',
    fr: 'Nodus Drift permet de combiner jusqu’à six sons d’ambiance, bruits ou sons binauraux hors connexion. Réglez chaque volume, enregistrez des mélanges nommés et trouvez des sons par recherche, favoris ou catégories. Une vue plein écran et un lecteur permettent de contrôler le mélange tout en utilisant les autres outils de Nodus.',
    de: 'Mit Nodus Drift kombinieren Sie offline bis zu sechs Umgebungsgeräusche, Rauschsignale oder binaurale Töne. Regeln Sie die Lautstärke jedes Tons, speichern Sie benannte Mischungen und finden Sie Töne über Suche, Favoriten oder Kategorien. Eine Vollbildansicht und ein Player erlauben die Steuerung, während Sie andere Nodus-Werkzeuge nutzen.',
    pt: 'O Nodus Drift permite combinar até seis sons ambientes, ruídos ou tons binaurais sem ligação à Internet. Ajuste o volume de cada som, guarde misturas com nome e encontre sons por pesquisa, favoritos ou categorias. Inclui uma vista de ecrã inteiro e um leitor para controlar a mistura enquanto utiliza outras ferramentas do Nodus.',
    'pt-BR': 'O Nodus Drift permite combinar até seis sons ambientes, ruídos ou tons binaurais sem conexão. Ajuste o volume de cada som, salve combinações com nome e encontre sons por busca, favoritos ou categorias. Inclui uma visualização em tela cheia e um player para controlar a combinação enquanto usa outras ferramentas do Nodus.',
    it: 'Nodus Drift permette di combinare fino a sei suoni ambientali, rumori o toni binaurali senza connessione. Regola il volume di ogni suono, salva mix con un nome e trova suoni tramite ricerca, preferiti o categorie. Include una vista a schermo intero e un lettore per controllare il mix mentre usi altri strumenti di Nodus.',
    tr: 'Nodus Drift çevrimdışı olarak en fazla altı ortam sesi, gürültü veya binaural tonu birleştirmenizi sağlar. Her sesin düzeyini ayarlayın, karışımları adlandırarak kaydedin ve arama, favoriler veya kategorilerle ses bulun. Tam ekran görünümü ve oynatıcı sayesinde diğer Nodus araçlarını kullanırken karışımı yönetebilirsiniz.',
    'zh-CN': 'Nodus Drift 可离线混合最多六种环境音、噪声或双耳音调。你可以调整每种声音的音量、保存命名组合，并通过搜索、收藏或分类查找声音。它提供全屏视图和播放器，使用其他 Nodus 工具时也能控制组合。',
    'zh-TW': 'Nodus Drift 可離線混合最多六種環境音、雜訊或雙耳音調。你可以調整每種聲音的音量、儲存具名組合，並透過搜尋、收藏或分類尋找聲音。它提供全螢幕檢視和播放器，使用其他 Nodus 工具時也能控制組合。',
    ja: 'Nodus Driftは、最大6つの環境音、ノイズ、バイノーラルトーンをオフラインで組み合わせます。音ごとの音量調整、名前付きミックスの保存、検索・お気に入り・カテゴリによる音探しができます。全画面表示とプレイヤーがあり、他のNodusツールを使いながらミックスを操作できます。',
    ko: 'Nodus Drift는 오프라인에서 환경음, 잡음, 바이노럴 톤을 최대 6개까지 조합할 수 있습니다. 각 소리의 음량을 조절하고 이름을 붙여 저장하며 검색, 즐겨찾기, 분류로 소리를 찾을 수 있습니다. 전체 화면 보기와 플레이어를 통해 다른 Nodus 도구를 사용하면서도 조합을 제어할 수 있습니다.',
  },
  {
    category: 'new', scope: 'estudio',
    es: 'La guía de estudio completa genera capítulos a partir de los materiales, notas y grabaciones que elijas. Incluye explicaciones con citas, conceptos, fórmulas, preguntas de autoevaluación y una ficha de repaso. Puedes añadir figuras de tus materiales y contenido web opcional, identificado por separado. Antes de empezar muestra una estimación de coste y tiempo. Exporta la guía a PDF, Word o Markdown, o descarga solo la ficha de repaso.',
    en: 'The complete study guide generates chapters from the materials, notes and recordings you select. It includes cited explanations, concepts, formulas, self-check questions and a review sheet. You can add figures from your materials and optional web content, labelled separately. Before starting, it shows an estimate of cost and time. Export the guide to PDF, Word or Markdown, or download just the review sheet.',
    fr: 'Le guide d’étude complet génère des chapitres à partir des documents, notes et enregistrements choisis. Il comprend des explications citées, des concepts, des formules, des questions d’autoévaluation et une fiche de révision. Vous pouvez ajouter des figures de vos documents et du contenu web facultatif, identifié séparément. Le coût et la durée sont estimés avant de commencer. Exportez le guide en PDF, Word ou Markdown, ou téléchargez uniquement la fiche de révision.',
    de: 'Der vollständige Lernleitfaden erstellt Kapitel aus den ausgewählten Materialien, Notizen und Aufnahmen. Er enthält Erklärungen mit Quellenangaben, Begriffe, Formeln, Selbstprüfungsfragen und ein Wiederholungsblatt. Abbildungen aus Ihren Materialien und separat gekennzeichnete optionale Webinhalte lassen sich hinzufügen. Vor dem Start werden Kosten und Dauer geschätzt. Exportieren Sie den Leitfaden als PDF, Word oder Markdown oder laden Sie nur das Wiederholungsblatt herunter.',
    pt: 'O guia de estudo completo gera capítulos a partir dos materiais, notas e gravações que escolher. Inclui explicações com citações, conceitos, fórmulas, perguntas de autoavaliação e uma ficha de revisão. Pode adicionar figuras dos seus materiais e conteúdo web opcional, identificado separadamente. Antes de começar, mostra uma estimativa de custo e tempo. Exporte o guia para PDF, Word ou Markdown, ou descarregue apenas a ficha de revisão.',
    'pt-BR': 'O guia de estudo completo gera capítulos a partir dos materiais, notas e gravações que você escolher. Inclui explicações com citações, conceitos, fórmulas, perguntas de autoavaliação e uma ficha de revisão. Você pode adicionar figuras dos seus materiais e conteúdo web opcional, identificado separadamente. Antes de começar, mostra uma estimativa de custo e tempo. Exporte o guia para PDF, Word ou Markdown, ou baixe apenas a ficha de revisão.',
    it: 'La guida di studio completa genera capitoli dai materiali, dalle note e dalle registrazioni selezionati. Include spiegazioni con citazioni, concetti, formule, domande di autovalutazione e una scheda di ripasso. Puoi aggiungere figure dei tuoi materiali e contenuti web facoltativi, indicati separatamente. Prima di iniziare mostra una stima di costo e tempo. Esporta la guida in PDF, Word o Markdown, oppure scarica solo la scheda di ripasso.',
    tr: 'Kapsamlı çalışma rehberi, seçtiğiniz materyallerden, notlardan ve kayıtlardan bölümler oluşturur. Kaynak gösteren açıklamalar, kavramlar, formüller, öz değerlendirme soruları ve bir tekrar özeti içerir. Materyallerinizden görseller ve ayrı etiketlenen isteğe bağlı web içeriği ekleyebilirsiniz. Başlamadan önce maliyet ve süre tahmini gösterilir. Rehberi PDF, Word veya Markdown olarak dışa aktarabilir ya da yalnızca tekrar özetini indirebilirsiniz.',
    'zh-CN': '完整学习指南根据你选择的资料、笔记和录音生成章节，包含带引用的讲解、概念、公式、自测问题和复习提要。你可以加入资料中的插图，以及单独标注的可选网络内容。开始前会显示费用和时间估算。指南可导出为 PDF、Word 或 Markdown，也可以只下载复习提要。',
    'zh-TW': '完整學習指南根據你選擇的資料、筆記和錄音產生章節，包含附引用的講解、概念、公式、自測問題和複習提要。你可以加入資料中的插圖，以及單獨標示的選用網路內容。開始前會顯示費用和時間估算。指南可匯出為 PDF、Word 或 Markdown，也可以只下載複習提要。',
    ja: '完全版学習ガイドは、選択した教材、ノート、録音から章を作成します。出典付きの説明、概念、数式、理解度確認の質問、復習シートを含みます。教材の図や、別途明示される任意のウェブ情報を追加できます。開始前に費用と所要時間の見積もりを表示します。PDF、Word、Markdownで書き出すか、復習シートだけをダウンロードできます。',
    ko: '전체 학습 가이드는 선택한 자료, 노트, 녹음으로 장을 생성합니다. 출처가 있는 설명, 개념, 공식, 자기 점검 질문과 복습 요약을 포함합니다. 자료의 그림과 별도로 표시되는 선택적 웹 콘텐츠를 추가할 수 있습니다. 시작 전에 비용과 시간 예상치를 보여 줍니다. 가이드를 PDF, Word, Markdown으로 내보내거나 복습 요약만 다운로드할 수 있습니다.',
  },
  {
    category: 'new', scope: 'ai',
    es: 'En Ajustes puedes comprobar qué modelos favoritos no aparecen en el catálogo de su proveedor. Puedes quitarlos de favoritos o sustituirlos en todas las tareas que los usan. Si el catálogo no se puede consultar, la comprobación lo indica. Un modelo ausente del catálogo puede seguir funcionando como alias.',
    en: 'In Settings, you can check which favourite models are absent from their provider’s catalogue. Remove them from favourites or replace them in every task that uses them. If a catalogue cannot be read, the check reports it. A model absent from the catalogue may still work as an alias.',
    fr: 'Dans les réglages, vérifiez quels modèles favoris sont absents du catalogue de leur fournisseur. Retirez-les des favoris ou remplacez-les dans toutes les tâches qui les utilisent. Si un catalogue est inaccessible, la vérification le signale. Un modèle absent peut encore fonctionner comme alias.',
    de: 'In den Einstellungen können Sie prüfen, welche favorisierten Modelle im Katalog ihres Anbieters fehlen. Entfernen Sie diese aus den Favoriten oder ersetzen Sie sie in allen Aufgaben, die sie verwenden. Ein nicht lesbarer Katalog wird gemeldet. Ein fehlendes Modell kann als Alias weiterhin funktionieren.',
    pt: 'Nas Definições pode verificar quais os modelos favoritos que não aparecem no catálogo do fornecedor. Remova-os dos favoritos ou substitua-os em todas as tarefas que os utilizam. Se um catálogo não puder ser consultado, a verificação indica-o. Um modelo ausente pode continuar a funcionar como alias.',
    'pt-BR': 'Nas Configurações você pode verificar quais modelos favoritos não aparecem no catálogo do provedor. Remova-os dos favoritos ou substitua-os em todas as tarefas que os usam. Se um catálogo não puder ser consultado, a verificação informa isso. Um modelo ausente pode continuar funcionando como alias.',
    it: 'Nelle Impostazioni puoi verificare quali modelli preferiti non compaiono nel catalogo del fornitore. Rimuovili dai preferiti o sostituiscili in tutte le attività che li usano. Se un catalogo non è consultabile, la verifica lo segnala. Un modello assente può ancora funzionare come alias.',
    tr: 'Ayarlar bölümünde hangi favori modellerin sağlayıcı kataloğunda bulunmadığını kontrol edebilirsiniz. Bunları favorilerden kaldırın veya kullanan tüm görevlerde değiştirin. Katalog okunamıyorsa kontrol bunu bildirir. Katalogda bulunmayan bir model takma ad olarak çalışmaya devam edebilir.',
    'zh-CN': '在设置中可以检查哪些收藏模型未出现在提供商的目录中。你可以将其移出收藏，或替换所有使用该模型的任务配置。如果无法读取目录，检查会明确提示。目录中缺失的模型仍可能作为别名正常使用。',
    'zh-TW': '在設定中可以檢查哪些收藏模型未出現在供應商的目錄中。你可以將其移出收藏，或替換所有使用該模型的任務設定。如果無法讀取目錄，檢查會明確提示。目錄中缺少的模型仍可能作為別名正常使用。',
    ja: '設定で、お気に入りのモデルがプロバイダーの一覧にあるか確認できます。一覧にないモデルをお気に入りから削除するか、使用するすべてのタスクで置き換えられます。一覧を取得できない場合はその旨を表示します。一覧にないモデルも別名として引き続き使える場合があります。',
    ko: '설정에서 제공업체 목록에 없는 즐겨찾기 모델을 확인할 수 있습니다. 즐겨찾기에서 제거하거나 해당 모델을 사용하는 모든 작업에서 교체할 수 있습니다. 목록을 읽을 수 없으면 확인 결과에 표시됩니다. 목록에 없는 모델도 별칭으로 계속 작동할 수 있습니다.',
  },
  {
    category: 'enhancement', scope: 'library',
    es: 'La Biblioteca identifica las obras cuyo texto procede principalmente de OCR y muestra cuántas páginas no se procesaron por el límite de OCR. Distingue esas páginas de las que no tienen texto recuperado y solo muestra el límite cuando consta en los datos de extracción.',
    en: 'The Library identifies works whose text was mainly recovered through OCR and shows how many pages were not processed because of the OCR limit. It distinguishes those pages from pages without recovered text and only shows the limit when it is recorded in the extraction data.',
    fr: 'La Bibliothèque identifie les œuvres dont le texte provient principalement de l’OCR et indique le nombre de pages non traitées en raison de sa limite. Elle distingue ces pages de celles sans texte récupéré et affiche la limite uniquement si elle figure dans les données d’extraction.',
    de: 'Die Bibliothek kennzeichnet Werke, deren Text überwiegend durch OCR gewonnen wurde, und zeigt die wegen des OCR-Limits nicht verarbeiteten Seiten. Sie unterscheidet diese von Seiten ohne gewonnenen Text und zeigt das Limit nur an, wenn es in den Extraktionsdaten vermerkt ist.',
    pt: 'A Biblioteca identifica as obras cujo texto foi sobretudo recuperado por OCR e mostra quantas páginas não foram processadas devido ao limite de OCR. Distingue essas páginas das que não têm texto recuperado e só mostra o limite quando consta dos dados de extração.',
    'pt-BR': 'A Biblioteca identifica as obras cujo texto foi recuperado principalmente por OCR e mostra quantas páginas não foram processadas devido ao limite de OCR. Distingue essas páginas das que não têm texto recuperado e só mostra o limite quando ele consta nos dados de extração.',
    it: 'La Biblioteca identifica le opere il cui testo è stato recuperato soprattutto tramite OCR e mostra quante pagine non sono state elaborate a causa del limite OCR. Le distingue dalle pagine senza testo recuperato e mostra il limite solo quando è registrato nei dati di estrazione.',
    tr: 'Kütüphane, metni çoğunlukla OCR ile elde edilen eserleri belirtir ve OCR sınırı nedeniyle işlenmeyen sayfa sayısını gösterir. Bu sayfaları metni alınamayan sayfalardan ayırır ve sınırı yalnızca çıkarma verilerinde kayıtlıysa gösterir.',
    'zh-CN': '资料库会标出主要通过 OCR 恢复文本的作品，并显示因 OCR 上限而未处理的页数。这些页面与未恢复出文本的页面分开统计，只有提取数据中记录了上限时才会显示该上限。',
    'zh-TW': '知識庫會標示主要透過 OCR 還原文字的作品，並顯示因 OCR 上限而未處理的頁數。這些頁面與未還原出文字的頁面分開統計，只有擷取資料中記錄了上限時才會顯示該上限。',
    ja: 'ライブラリは、主にOCRでテキストを復元した作品を示し、OCRの上限で処理されなかったページ数を表示します。テキストを復元できなかったページとは区別し、上限は抽出データに記録されている場合だけ表示します。',
    ko: '라이브러리는 주로 OCR로 텍스트를 복원한 자료를 표시하고 OCR 한도로 처리하지 못한 페이지 수를 보여 줍니다. 이를 텍스트를 복원하지 못한 페이지와 구분하며, 추출 데이터에 기록된 경우에만 한도를 표시합니다.',
  },
  {
    category: 'enhancement', scope: 'library',
    es: 'La actualización de las citas guardadas a los pasajes correctos tarda menos al abrir una bóveda. La reparación evita consultas repetidas sobre las mismas fuentes, especialmente en bibliotecas grandes.',
    en: 'Updating saved citations to the correct passages takes less time when opening a vault. The repair avoids repeated queries over the same sources, especially in large libraries.',
    fr: 'La mise à jour des citations enregistrées vers les passages corrects prend moins de temps à l’ouverture d’un coffre. La réparation évite les requêtes répétées sur les mêmes sources, surtout dans les grandes bibliothèques.',
    de: 'Beim Öffnen eines Tresors werden gespeicherte Zitate schneller den richtigen Passagen zugeordnet. Die Reparatur vermeidet wiederholte Abfragen derselben Quellen, besonders in großen Bibliotheken.',
    pt: 'A atualização das citações guardadas para os excertos corretos demora menos ao abrir um cofre. A reparação evita consultas repetidas às mesmas fontes, sobretudo em bibliotecas grandes.',
    'pt-BR': 'A atualização das citações salvas para os trechos corretos leva menos tempo ao abrir um cofre. A correção evita consultas repetidas às mesmas fontes, especialmente em bibliotecas grandes.',
    it: 'All’apertura di una cassaforte, l’aggiornamento delle citazioni salvate ai passaggi corretti richiede meno tempo. La riparazione evita query ripetute sulle stesse fonti, soprattutto nelle biblioteche grandi.',
    tr: 'Bir kasa açılırken kaydedilmiş alıntıların doğru pasajlara bağlanması daha az zaman alır. Onarım, özellikle büyük kütüphanelerde aynı kaynakların tekrar tekrar sorgulanmasını önler.',
    'zh-CN': '打开保险库时，将已保存引用更新到正确段落所需的时间更短。修复会避免对同一来源重复查询，大型资料库受益尤其明显。',
    'zh-TW': '開啟保管庫時，將已儲存引用更新至正確段落所需的時間更短。修復會避免對同一來源重複查詢，大型知識庫受益尤其明顯。',
    ja: '保管庫を開く際、保存済みの引用を正しい文章へ更新する処理が速くなりました。同じ出典への繰り返し照会を避けるため、大規模なライブラリで特に効果があります。',
    ko: '보관함을 열 때 저장된 인용을 올바른 구절에 연결하는 시간이 줄었습니다. 같은 출처를 반복해서 조회하지 않으므로 대규모 라이브러리에서 특히 효과가 있습니다.',
  },
  {
    category: 'enhancement', scope: 'academic',
    es: 'Research Chat prepara más rápido el inventario de fuentes en corpus grandes y reduce el texto que envía al modelo para describir el ámbito de consulta. La cobertura guardada incluye solo las fuentes consultadas. Si una petición supera el límite del modelo, el aviso explica qué parte ocupa demasiado y qué puedes reducir.',
    en: 'Research Chat prepares the source inventory faster in large corpora and reduces the text sent to the model to describe the query scope. Saved coverage includes only consulted sources. If a request exceeds the model’s limit, the notice explains which part is too large and what you can reduce.',
    fr: 'Le Chat de recherche prépare plus vite l’inventaire des sources dans les grands corpus et réduit le texte décrivant le périmètre envoyé au modèle. La couverture enregistrée ne contient que les sources consultées. Si une requête dépasse la limite du modèle, le message précise quelle partie est trop volumineuse et ce que vous pouvez réduire.',
    de: 'Der Forschungschat erstellt das Quellenverzeichnis großer Korpora schneller und sendet kürzere Beschreibungen des Abfragebereichs an das Modell. Die gespeicherte Abdeckung enthält nur konsultierte Quellen. Überschreitet eine Anfrage das Modelllimit, erklärt der Hinweis, welcher Teil zu groß ist und was Sie reduzieren können.',
    pt: 'O Chat de investigação prepara mais depressa o inventário de fontes em corpus grandes e reduz o texto enviado ao modelo para descrever o âmbito da consulta. A cobertura guardada inclui apenas as fontes consultadas. Se um pedido exceder o limite do modelo, o aviso explica qual a parte demasiado grande e o que pode reduzir.',
    'pt-BR': 'O Chat de pesquisa prepara mais rápido o inventário de fontes em corpus grandes e reduz o texto enviado ao modelo para descrever o escopo da consulta. A cobertura salva inclui apenas as fontes consultadas. Se um pedido exceder o limite do modelo, o aviso explica qual parte é grande demais e o que você pode reduzir.',
    it: 'La Chat di ricerca prepara più rapidamente l’inventario delle fonti nei corpus grandi e riduce il testo inviato al modello per descrivere l’ambito della ricerca. La copertura salvata include solo le fonti consultate. Se una richiesta supera il limite del modello, l’avviso spiega quale parte è troppo grande e cosa puoi ridurre.',
    tr: 'Araştırma Sohbeti büyük derlemlerde kaynak envanterini daha hızlı hazırlar ve sorgu kapsamını açıklamak için modele gönderilen metni azaltır. Kaydedilen kapsam yalnızca başvurulan kaynakları içerir. İstek model sınırını aşarsa bildirim hangi kısmın büyük olduğunu ve neleri azaltabileceğinizi açıklar.',
    'zh-CN': '研究聊天在大型语料库中更快地准备来源清单，并缩短发送给模型的查询范围说明。保存的覆盖记录只包含实际查阅的来源。如果请求超出模型限制，提示会说明哪部分过大以及可以缩减什么。',
    'zh-TW': '研究聊天在大型語料庫中更快地準備來源清單，並縮短傳送給模型的查詢範圍說明。儲存的涵蓋紀錄只包含實際查閱的來源。如果請求超出模型限制，提示會說明哪部分過大以及可以縮減什麼。',
    ja: '研究チャットは大規模コーパスの出典一覧をより速く準備し、検索範囲の説明としてモデルに送るテキストを減らします。保存する参照範囲には実際に調べた出典だけを含めます。リクエストがモデルの上限を超えた場合、どの部分が大きすぎるかと削減できる内容を表示します。',
    ko: '연구 채팅은 대규모 말뭉치의 출처 목록을 더 빠르게 준비하고 조회 범위를 설명하기 위해 모델에 보내는 텍스트를 줄입니다. 저장된 검토 범위에는 실제로 확인한 출처만 포함됩니다. 요청이 모델 한도를 넘으면 어떤 부분이 너무 큰지와 줄일 수 있는 내용을 알려 줍니다.',
  },
  {
    category: 'fix', scope: 'ai',
    es: 'Nodus usa los límites de contexto y entrada que informa cada proveedor y los aplica también a la generación de informes. Conserva los límites personalizados si falla la consulta del catálogo y calcula por separado el espacio para razonar y responder. Esto evita rechazar peticiones válidas o superar el límite del modelo.',
    en: 'Nodus uses the context and input limits reported by each provider and also applies them to report generation. It preserves custom limits if catalogue discovery fails and budgets reasoning and response space separately. This avoids rejecting valid requests or exceeding the model’s limit.',
    fr: 'Nodus utilise les limites de contexte et d’entrée annoncées par chaque fournisseur, y compris pour les rapports. Les limites personnalisées sont conservées si le catalogue est inaccessible, et l’espace de raisonnement et de réponse est calculé séparément. Cela évite de rejeter des requêtes valides ou de dépasser la limite du modèle.',
    de: 'Nodus verwendet die vom Anbieter gemeldeten Kontext- und Eingabelimits auch für die Berichtserstellung. Eigene Limits bleiben bei fehlgeschlagener Katalogabfrage erhalten. Platz für Denkprozess und Antwort wird getrennt berechnet. So werden gültige Anfragen nicht abgewiesen und Modelllimits nicht überschritten.',
    pt: 'O Nodus utiliza os limites de contexto e entrada indicados por cada fornecedor e aplica-os também à geração de relatórios. Mantém os limites personalizados se a consulta do catálogo falhar e calcula separadamente o espaço para raciocínio e resposta. Evita assim rejeitar pedidos válidos ou exceder o limite do modelo.',
    'pt-BR': 'O Nodus usa os limites de contexto e entrada informados por cada provedor e os aplica também à geração de relatórios. Mantém os limites personalizados se a consulta do catálogo falhar e calcula separadamente o espaço para raciocínio e resposta. Isso evita rejeitar pedidos válidos ou exceder o limite do modelo.',
    it: 'Nodus usa i limiti di contesto e input dichiarati dal fornitore anche per generare i report. Conserva i limiti personalizzati se la consultazione del catalogo fallisce e calcola separatamente lo spazio per ragionamento e risposta. Questo evita di rifiutare richieste valide o superare il limite del modello.',
    tr: 'Nodus her sağlayıcının bildirdiği bağlam ve girdi sınırlarını rapor oluştururken de kullanır. Katalog sorgusu başarısız olursa özel sınırları korur, düşünme ve yanıt alanını ayrı hesaplar. Böylece geçerli isteklerin reddedilmesi veya model sınırının aşılması önlenir.',
    'zh-CN': 'Nodus 使用各提供商报告的上下文和输入上限，并将其应用于报告生成。目录查询失败时会保留自定义上限，且分别计算推理与回答所需空间。这可避免拒绝有效请求或超出模型限制。',
    'zh-TW': 'Nodus 使用各供應商回報的上下文和輸入上限，並將其套用於報告產生。目錄查詢失敗時會保留自訂上限，且分別計算推理與回答所需空間。這可避免拒絕有效請求或超出模型限制。',
    ja: 'Nodusはプロバイダーが示すコンテキストと入力の上限を使い、レポート生成にも適用します。一覧の取得に失敗してもカスタム上限を保持し、推論と回答の領域を別々に計算します。有効なリクエストの拒否やモデル上限の超過を防ぎます。',
    ko: 'Nodus는 제공업체가 알리는 컨텍스트와 입력 한도를 보고서 생성에도 적용합니다. 목록 조회에 실패해도 사용자 지정 한도를 유지하고 추론과 답변 공간을 따로 계산합니다. 이를 통해 유효한 요청이 거부되거나 모델 한도를 넘는 문제를 방지합니다.',
  },
  {
    category: 'fix', scope: 'ai',
    es: 'Las respuestas de IA que siguen enviando texto o razonamiento ya no se interrumpen al cumplir tres minutos. El tiempo de espera se controla por inactividad, con un límite total que evita peticiones interminables.',
    en: 'AI responses that keep sending text or reasoning no longer stop at three minutes. The timeout tracks inactivity, with a total limit that prevents requests from running indefinitely.',
    fr: 'Les réponses d’IA qui continuent à envoyer du texte ou du raisonnement ne s’interrompent plus après trois minutes. Le délai dépend de l’inactivité, avec une limite totale pour éviter les requêtes sans fin.',
    de: 'KI-Antworten, die weiter Text oder Denkinhalte senden, brechen nicht mehr nach drei Minuten ab. Das Zeitlimit richtet sich nach Inaktivität. Eine Gesamtdauer begrenzt weiterhin endlose Anfragen.',
    pt: 'As respostas de IA que continuam a enviar texto ou raciocínio já não param ao fim de três minutos. O tempo de espera depende da inatividade, com um limite total para evitar pedidos intermináveis.',
    'pt-BR': 'As respostas de IA que continuam enviando texto ou raciocínio não param mais após três minutos. O tempo de espera depende da inatividade, com um limite total para evitar pedidos intermináveis.',
    it: 'Le risposte IA che continuano a inviare testo o ragionamento non si interrompono più dopo tre minuti. Il timeout dipende dall’inattività, con un limite totale per evitare richieste interminabili.',
    tr: 'Metin veya düşünme verisi göndermeye devam eden yapay zekâ yanıtları artık üç dakika sonunda kesilmez. Zaman aşımı hareketsizliğe göre belirlenir ve isteklerin sonsuza kadar sürmesini önleyen bir toplam sınır uygulanır.',
    'zh-CN': '持续发送文本或推理内容的 AI 回答不再在三分钟时中断。超时根据无活动时长判断，同时保留总时长上限，防止请求无限运行。',
    'zh-TW': '持續傳送文字或推理內容的 AI 回答不再於三分鐘時中斷。逾時依無活動時長判斷，同時保留總時長上限，避免請求無限執行。',
    ja: 'テキストや推論を送信し続けているAIの回答は、3分経過だけで中断されなくなりました。通信が止まった時間でタイムアウトを判断し、無期限に続くリクエストを防ぐ総時間の上限も設けています。',
    ko: '텍스트나 추론을 계속 보내는 AI 답변은 더 이상 3분이 지났다는 이유로 중단되지 않습니다. 응답이 없는 시간으로 시간 초과를 판단하고 무한 실행을 막는 전체 시간 한도도 유지합니다.',
  },
  {
    category: 'fix', scope: 'zotero',
    es: 'La sincronización archiva en Nodus las obras enviadas a la papelera, eliminadas o fusionadas en Zotero. Conserva sus notas y análisis, permite restaurarlas si vuelven a Zotero y reintenta las comprobaciones pendientes si se interrumpe la conexión.',
    en: 'Sync archives works in Nodus when they are trashed, deleted or merged in Zotero. It preserves their notes and analysis, lets you restore them if they return to Zotero and retries pending checks if the connection is interrupted.',
    fr: 'La synchronisation archive dans Nodus les œuvres mises à la corbeille, supprimées ou fusionnées dans Zotero. Leurs notes et analyses sont conservées. Elles peuvent être restaurées si elles reviennent dans Zotero, et les vérifications en attente sont réessayées après une coupure de connexion.',
    de: 'Die Synchronisierung archiviert Werke in Nodus, wenn sie in Zotero in den Papierkorb verschoben, gelöscht oder zusammengeführt werden. Notizen und Analysen bleiben erhalten. Zurückgekehrte Werke können wiederhergestellt werden. Bei Verbindungsabbrüchen werden ausstehende Prüfungen erneut versucht.',
    pt: 'A sincronização arquiva no Nodus as obras enviadas para o lixo, eliminadas ou fundidas no Zotero. Conserva as notas e análises, permite restaurá-las se regressarem ao Zotero e repete as verificações pendentes se a ligação for interrompida.',
    'pt-BR': 'A sincronização arquiva no Nodus as obras enviadas à lixeira, excluídas ou mescladas no Zotero. Conserva notas e análises, permite restaurá-las se voltarem ao Zotero e repete as verificações pendentes se a conexão for interrompida.',
    it: 'La sincronizzazione archivia in Nodus le opere cestinate, eliminate o unite in Zotero. Conserva note e analisi, permette di ripristinarle se tornano in Zotero e ripete le verifiche in sospeso se la connessione si interrompe.',
    tr: 'Eşitleme, Zotero’da çöpe taşınan, silinen veya birleştirilen eserleri Nodus’ta arşivler. Notları ve analizleri korur, eserler Zotero’ya dönerse geri yüklemenizi sağlar ve bağlantı kesilirse bekleyen kontrolleri yeniden dener.',
    'zh-CN': '同步会在 Nodus 中归档被 Zotero 移入回收站、删除或合并的作品。笔记和分析会保留，作品重新出现在 Zotero 时可恢复。如果连接中断，待完成的检查会重试。',
    'zh-TW': '同步會在 Nodus 中封存被 Zotero 移入垃圾桶、刪除或合併的作品。筆記和分析會保留，作品重新出現在 Zotero 時可還原。如果連線中斷，待完成的檢查會重試。',
    ja: '同期では、Zoteroでゴミ箱に入れた作品、削除した作品、統合した作品をNodusでアーカイブします。ノートと分析は保持され、Zoteroに戻った作品は復元できます。接続が切れた場合は未完了の確認を再試行します。',
    ko: '동기화는 Zotero에서 휴지통으로 이동하거나 삭제 또는 병합한 자료를 Nodus에 보관 처리합니다. 노트와 분석은 유지되며 Zotero에 다시 나타나면 복원할 수 있습니다. 연결이 끊기면 대기 중인 확인을 다시 시도합니다.',
  },
];
