// SPDX-FileCopyrightText: 2026 Jorge Pérez Burgueño and Nodus contributors
// SPDX-License-Identifier: AGPL-3.0-only

import type { ReleaseHighlight } from './releaseNotes';

// Keep scope groups in display order: descending size, stable ties.
// Describe shipped behavior directly in every interface language.
export const RELEASE_5_6_0_HIGHLIGHTS: ReleaseHighlight[] = [
  {
    "scope": "academic",
    "es": "Al crear una bóveda académica puedes elegir entre Auto y Manual. En Manual, importar o sincronizar documentos no genera ideas ni temas automáticamente. La elección se guarda para esa bóveda y no se puede cambiar después de crearla.",
    "en": "When creating an academic vault, you can choose Auto or Manual. In Manual mode, importing or syncing documents does not automatically generate ideas or themes. The choice is saved for that vault and cannot be changed after creation.",
    "fr": "À la création d’un coffre académique, vous pouvez choisir Auto ou Manuel. En mode Manuel, importer ou synchroniser des documents ne génère pas automatiquement d’idées ni de thèmes. Ce choix est enregistré pour le coffre et ne peut plus être modifié après sa création.",
    "de": "Beim Erstellen eines akademischen Tresors kannst du Auto oder Manuell wählen. Im manuellen Modus erzeugt das Importieren oder Synchronisieren von Dokumenten keine automatischen Ideen oder Themen. Die Wahl wird für diesen Tresor gespeichert und kann nach der Erstellung nicht geändert werden.",
    "pt": "Ao criar um cofre académico, podes escolher Auto ou Manual. No modo Manual, importar ou sincronizar documentos não gera ideias nem temas automaticamente. A escolha fica guardada nesse cofre e não pode ser alterada depois da criação.",
    "pt-BR": "Ao criar um cofre acadêmico, você pode escolher Auto ou Manual. No modo Manual, importar ou sincronizar documentos não gera ideias nem temas automaticamente. A escolha fica salva nesse cofre e não pode ser alterada após a criação.",
    "it": "Quando crei un archivio accademico puoi scegliere Auto o Manuale. In modalità Manuale, importare o sincronizzare documenti non genera automaticamente idee o temi. La scelta viene salvata per quell’archivio e non può essere cambiata dopo la creazione.",
    "tr": "Akademik kasa oluştururken Otomatik veya Manuel seçebilirsiniz. Manuel modda belge içe aktarma veya eşitleme, otomatik olarak fikir ya da tema oluşturmaz. Seçim bu kasa için kaydedilir ve oluşturulduktan sonra değiştirilemez.",
    "zh-CN": "创建学术库时，可以选择自动或手动模式。在手动模式下，导入或同步文献不会自动生成观点或主题。模式选择保存在该库中，创建后无法更改。",
    "zh-TW": "建立學術庫時，可以選擇自動或手動模式。在手動模式下，匯入或同步文獻不會自動產生觀點或主題。模式選擇儲存在該庫中，建立後無法變更。",
    "ja": "学術保管庫を作成するときに、自動または手動を選べます。手動モードでは、文献をインポートまたは同期してもアイデアやテーマは自動生成されません。選択は保管庫ごとに保存され、作成後は変更できません。",
    "ko": "학술 보관함을 만들 때 자동 또는 수동을 선택할 수 있습니다. 수동 모드에서는 문서를 가져오거나 동기화해도 아이디어나 주제가 자동 생성되지 않습니다. 선택은 해당 보관함에 저장되며 생성 후에는 바꿀 수 없습니다."
  },
  {
    "scope": "academic",
    "es": "El modo Manual permite escribir ideas y añadir citas, obras, temas y conexiones desde un mismo formulario. Todos esos vínculos son opcionales. Las ideas se indexan localmente para buscarlas, sin IA generativa. Chat de investigación y Deep Research pueden consultarlas cuando los ejecutas.",
    "en": "Manual mode lets you write ideas and add quotations, works, themes and connections in one form. All these links are optional. Ideas are indexed locally for search, without generative AI. Research Chat and Deep Research can use them when you run those tools.",
    "fr": "Le mode Manuel permet de rédiger des idées et d’ajouter citations, ouvrages, thèmes et connexions dans un même formulaire. Tous ces liens sont facultatifs. Les idées sont indexées localement pour la recherche, sans IA générative. Le Chat de recherche et Deep Research peuvent les utiliser lorsque vous lancez ces outils.",
    "de": "Im manuellen Modus kannst du Ideen schreiben und Zitate, Werke, Themen und Verbindungen in einem Formular ergänzen. Alle Verknüpfungen sind optional. Ideen werden lokal für die Suche indexiert, ohne generative KI. Forschungschat und Deep Research können sie nutzen, wenn du diese Werkzeuge startest.",
    "pt": "O modo Manual permite escrever ideias e adicionar citações, obras, temas e ligações num só formulário. Todas as associações são opcionais. As ideias são indexadas localmente para pesquisa, sem IA generativa. O Chat de investigação e o Deep Research podem consultá-las quando executas essas ferramentas.",
    "pt-BR": "O modo Manual permite escrever ideias e adicionar citações, obras, temas e conexões em um só formulário. Todas essas associações são opcionais. As ideias são indexadas localmente para pesquisa, sem IA generativa. O Chat de pesquisa e o Deep Research podem consultá-las quando você executa essas ferramentas.",
    "it": "La modalità Manuale permette di scrivere idee e aggiungere citazioni, opere, temi e collegamenti in un unico modulo. Tutti questi legami sono facoltativi. Le idee sono indicizzate localmente per la ricerca, senza IA generativa. Chat di ricerca e Deep Research possono usarle quando avvii questi strumenti.",
    "tr": "Manuel modda tek bir formda fikir yazabilir, alıntı, eser, tema ve bağlantı ekleyebilirsiniz. Bu ilişkilerin tümü isteğe bağlıdır. Fikirler, üretken yapay zekâ kullanılmadan arama için yerel olarak dizinlenir. Araştırma Sohbeti ve Deep Research, bu araçları çalıştırdığınızda fikirlerinizi kullanabilir.",
    "zh-CN": "手动模式允许在同一个表单中撰写观点，并添加引文、文献、主题和连接。这些关联均为可选。观点在本地建立搜索索引，不使用生成式 AI。启动研究聊天或 Deep Research 时，这些工具可以使用你的观点。",
    "zh-TW": "手動模式允許在同一份表單中撰寫觀點，並加入引文、文獻、主題和連結。這些關聯皆為選填。觀點在本機建立搜尋索引，不使用生成式 AI。啟動研究聊天或 Deep Research 時，這些工具可以使用你的觀點。",
    "ja": "手動モードでは、同じフォームでアイデアを書き、引用、文献、テーマ、接続を追加できます。これらの関連付けはすべて任意です。アイデアは生成 AI を使わず、検索用にローカルで索引化されます。研究チャットや Deep Research を実行すると、これらのツールでアイデアを利用できます。",
    "ko": "수동 모드에서는 하나의 양식에서 아이디어를 작성하고 인용문, 문헌, 주제, 연결을 추가할 수 있습니다. 모든 연결은 선택 사항입니다. 아이디어는 생성형 AI 없이 검색용으로 로컬에서 색인됩니다. 연구 채팅과 Deep Research를 실행하면 이 도구들이 아이디어를 활용할 수 있습니다."
  },
  {
    "scope": "academic",
    "es": "Concilium es una nueva función del Chat de investigación que permite consultar entre dos y cinco modelos con la misma pregunta, fuentes y archivos. El modelo que elijas como coordinador redacta la respuesta final a partir de las respuestas individuales. Puedes abrir cada respuesta y consultar los errores, incluso después de volver a abrir la conversación.",
    "en": "Concilium is a new Research Chat feature that lets you consult two to five models with the same question, sources and files. The model you choose as coordinator writes the final answer from the individual responses. You can open each response and inspect errors, even after reopening the conversation.",
    "fr": "Concilium est une nouvelle fonction du Chat de recherche qui permet de consulter deux à cinq modèles avec la même question, les mêmes sources et fichiers. Le modèle choisi comme coordinateur rédige la réponse finale à partir des réponses individuelles. Vous pouvez ouvrir chaque réponse et consulter les erreurs, même après avoir rouvert la conversation.",
    "de": "Concilium ist eine neue Funktion im Forschungschat, mit der du zwei bis fünf Modelle mit derselben Frage, denselben Quellen und Dateien befragen kannst. Das als Koordinator gewählte Modell erstellt aus den Einzelantworten die endgültige Antwort. Jede Antwort und mögliche Fehler bleiben auch nach erneutem Öffnen des Gesprächs einsehbar.",
    "pt": "O Concilium é uma nova função do Chat de investigação que permite consultar dois a cinco modelos com a mesma pergunta, fontes e ficheiros. O modelo escolhido como coordenador escreve a resposta final a partir das respostas individuais. Podes abrir cada resposta e consultar erros, mesmo depois de reabrir a conversa.",
    "pt-BR": "O Concilium é uma nova função do Chat de pesquisa que permite consultar de dois a cinco modelos com a mesma pergunta, fontes e arquivos. O modelo escolhido como coordenador escreve a resposta final com base nas respostas individuais. Você pode abrir cada resposta e consultar erros, mesmo depois de reabrir a conversa.",
    "it": "Concilium è una nuova funzione della Chat di ricerca che permette di consultare da due a cinque modelli con la stessa domanda, fonti e file. Il modello scelto come coordinatore scrive la risposta finale sulla base delle risposte individuali. Puoi aprire ogni risposta e consultare gli errori anche dopo aver riaperto la conversazione.",
    "tr": "Araştırma Sohbeti’nin yeni Concilium özelliğiyle aynı soru, kaynak ve dosyaları iki ila beş modele sorabilirsiniz. Koordinatör olarak seçtiğiniz model, bireysel yanıtlardan son yanıtı oluşturur. Sohbeti yeniden açtıktan sonra da her yanıtı açabilir ve hataları inceleyebilirsiniz.",
    "zh-CN": "研究聊天新增 Concilium 功能，可以让二至五个模型回答相同问题，并使用相同来源和文件。你指定的协调模型根据各个模型的回答撰写最终答复。你可以查看每个回答和错误信息，重新打开对话后仍可查看。",
    "zh-TW": "研究聊天新增 Concilium 功能，可以讓二至五個模型回答相同問題，並使用相同來源和檔案。你指定的協調模型根據各個模型的回答撰寫最終答覆。你可以查看每個回答和錯誤訊息，重新開啟對話後仍可查看。",
    "ja": "研究チャットの新機能 Concilium では、同じ質問、ソース、ファイルを使って2〜5個のモデルに回答を求められます。取りまとめ役に選んだモデルが個別の回答をもとに最終回答を作成します。各回答とエラーは、会話を開き直した後も確認できます。",
    "ko": "연구 채팅의 새로운 Concilium 기능으로 같은 질문, 출처, 파일을 사용해 두 개에서 다섯 개의 모델에 답변을 요청할 수 있습니다. 조정자로 선택한 모델이 개별 답변을 바탕으로 최종 답변을 작성합니다. 대화를 다시 연 뒤에도 각 답변과 오류를 확인할 수 있습니다."
  },
  {
    "scope": "academic",
    "es": "Los temas del grafo se abren en pestañas independientes. Puedes mostrar el tema completo o las ideas situadas a una, dos o tres conexiones de la idea seleccionada, y limitar las conexiones dibujadas por idea sin ocultar las ideas del conjunto elegido.",
    "en": "Graph themes open in separate tabs. You can show the whole theme or ideas within one, two or three connections of the selected idea, and limit the connections drawn per idea without hiding ideas in the selected set.",
    "fr": "Les thèmes du graphe s’ouvrent dans des onglets distincts. Vous pouvez afficher tout le thème ou les idées à une, deux ou trois connexions de l’idée sélectionnée, et limiter les connexions dessinées par idée sans masquer les idées de l’ensemble choisi.",
    "de": "Themen des Graphen öffnen sich in eigenen Tabs. Du kannst das ganze Thema oder Ideen innerhalb von einer, zwei oder drei Verbindungen zur ausgewählten Idee anzeigen und die gezeichneten Verbindungen pro Idee begrenzen, ohne Ideen der gewählten Menge auszublenden.",
    "pt": "Os temas do grafo abrem em separadores independentes. Podes mostrar o tema completo ou as ideias a uma, duas ou três ligações da ideia selecionada, e limitar as ligações desenhadas por ideia sem ocultar ideias do conjunto escolhido.",
    "pt-BR": "Os temas do grafo abrem em abas independentes. Você pode mostrar o tema completo ou as ideias a uma, duas ou três conexões da ideia selecionada, e limitar as conexões desenhadas por ideia sem ocultar ideias do conjunto escolhido.",
    "it": "I temi del grafo si aprono in schede indipendenti. Puoi mostrare l’intero tema o le idee a una, due o tre connessioni dall’idea selezionata, e limitare i collegamenti disegnati per idea senza nascondere le idee dell’insieme scelto.",
    "tr": "Grafik temaları ayrı sekmelerde açılır. Tüm temayı veya seçilen fikirden bir, iki ya da üç bağlantı uzaklıktaki fikirleri gösterebilir, seçili kümedeki fikirleri gizlemeden fikir başına çizilen bağlantıları sınırlayabilirsiniz.",
    "zh-CN": "图谱主题在独立标签页中打开。可以显示整个主题，或显示距所选观点一、二或三次连接的观点。还可以限制每个观点绘制的连接数，而不隐藏所选范围内的观点。",
    "zh-TW": "圖譜主題在獨立分頁中開啟。可以顯示整個主題，或顯示距所選觀點一、二或三次連結的觀點。也可以限制每個觀點繪製的連結數，而不隱藏所選範圍內的觀點。",
    "ja": "グラフのテーマは独立したタブで開きます。テーマ全体、または選択したアイデアから1〜3回の接続で到達するアイデアを表示できます。選択範囲のアイデアを隠さずに、アイデアごとの描画接続数を制限することもできます。",
    "ko": "그래프 주제는 독립된 탭으로 열립니다. 전체 주제 또는 선택한 아이디어에서 한 번, 두 번, 세 번의 연결로 도달하는 아이디어를 표시할 수 있습니다. 선택 범위의 아이디어를 숨기지 않고 아이디어당 그리는 연결 수를 제한할 수도 있습니다."
  },
  {
    "scope": "general",
    "es": "Las actualizaciones se muestran en el aviso de la cabecera, sin abrir un segundo diálogo al iniciar la aplicación. Desde ese aviso puedes consultar el progreso y las acciones disponibles.",
    "en": "Updates appear in the header notice without opening a second dialog when the app starts. The notice shows progress and the available actions.",
    "fr": "Les mises à jour apparaissent dans l’avis de l’en-tête, sans ouvrir une seconde boîte de dialogue au démarrage. Cet avis indique la progression et les actions disponibles.",
    "de": "Updates erscheinen im Hinweis in der Kopfzeile, ohne beim App-Start einen zweiten Dialog zu öffnen. Der Hinweis zeigt den Fortschritt und die verfügbaren Aktionen.",
    "pt": "As atualizações aparecem no aviso do cabeçalho, sem abrir um segundo diálogo ao iniciar a aplicação. O aviso mostra o progresso e as ações disponíveis.",
    "pt-BR": "As atualizações aparecem no aviso do cabeçalho, sem abrir um segundo diálogo ao iniciar o aplicativo. O aviso mostra o progresso e as ações disponíveis.",
    "it": "Gli aggiornamenti appaiono nell’avviso dell’intestazione, senza aprire una seconda finestra di dialogo all’avvio. L’avviso mostra l’avanzamento e le azioni disponibili.",
    "tr": "Güncellemeler, uygulama açılışında ikinci bir iletişim kutusu açmadan üst bilgideki bildirimde gösterilir. İlerleme durumunu ve kullanılabilir işlemleri buradan görebilirsiniz.",
    "zh-CN": "更新信息显示在顶部通知中，启动应用时不会再打开第二个对话框。可在通知中查看进度和可用操作。",
    "zh-TW": "更新資訊顯示在頂部通知中，啟動應用程式時不會再開啟第二個對話方塊。可在通知中查看進度和可用操作。",
    "ja": "更新情報は上部の通知に表示され、起動時に2つ目のダイアログを開きません。通知から進行状況と利用可能な操作を確認できます。",
    "ko": "업데이트는 앱 시작 시 두 번째 대화상자를 열지 않고 상단 알림에 표시됩니다. 알림에서 진행 상태와 사용 가능한 작업을 확인할 수 있습니다."
  },
  {
    "scope": "general",
    "es": "El aviso de que falta configurar un modelo de IA aparece en Notificaciones. Desde allí puedes abrir los ajustes necesarios para completar la configuración.",
    "en": "The warning about a missing AI model configuration appears in Notifications. You can open the relevant settings from there to complete the configuration.",
    "fr": "L’avertissement signalant l’absence de configuration d’un modèle d’IA apparaît dans les Notifications. Vous pouvez y ouvrir les réglages nécessaires pour terminer la configuration.",
    "de": "Die Warnung zur fehlenden KI-Modellkonfiguration erscheint unter Benachrichtigungen. Von dort kannst du die nötigen Einstellungen öffnen und die Konfiguration abschließen.",
    "pt": "O aviso de falta de configuração de um modelo de IA aparece nas Notificações. A partir daí podes abrir as definições necessárias para concluir a configuração.",
    "pt-BR": "O aviso de falta de configuração de um modelo de IA aparece nas Notificações. Por ali você pode abrir as configurações necessárias para concluir a configuração.",
    "it": "L’avviso relativo alla mancata configurazione di un modello IA appare nelle Notifiche. Da lì puoi aprire le impostazioni necessarie per completare la configurazione.",
    "tr": "Yapay zekâ modeli yapılandırmasının eksik olduğunu belirten uyarı Bildirimler bölümünde görünür. Yapılandırmayı tamamlamak için gerekli ayarları buradan açabilirsiniz.",
    "zh-CN": "尚未配置 AI 模型的提示显示在通知面板中。你可以从那里打开相关设置，完成配置。",
    "zh-TW": "尚未設定 AI 模型的提示顯示在通知面板中。你可以從那裡開啟相關設定，完成設定程序。",
    "ja": "AI モデルが未設定の場合の警告は通知パネルに表示されます。そこから必要な設定を開き、設定を完了できます。",
    "ko": "AI 모델 설정이 누락되었다는 경고는 알림 패널에 표시됩니다. 여기에서 필요한 설정을 열어 구성을 완료할 수 있습니다."
  },
  {
    "scope": "general",
    "es": "La cabecera del Chat de investigación mantiene sus controles dentro del espacio disponible y elimina acciones duplicadas. Esto facilita su uso cuando la ventana es estrecha.",
    "en": "The Research Chat header keeps its controls within the available space and removes duplicate actions. This makes it easier to use in narrow windows.",
    "fr": "L’en-tête du Chat de recherche conserve ses commandes dans l’espace disponible et supprime les actions en double. Il est ainsi plus facile à utiliser dans une fenêtre étroite.",
    "de": "Die Kopfzeile des Forschungschats hält ihre Bedienelemente im verfügbaren Platz und entfernt doppelte Aktionen. Dadurch lässt sie sich in schmalen Fenstern leichter bedienen.",
    "pt": "O cabeçalho do Chat de investigação mantém os controlos dentro do espaço disponível e remove ações duplicadas. Isto facilita a utilização em janelas estreitas.",
    "pt-BR": "O cabeçalho do Chat de pesquisa mantém os controles dentro do espaço disponível e remove ações duplicadas. Isso facilita o uso em janelas estreitas.",
    "it": "L’intestazione della Chat di ricerca mantiene i controlli nello spazio disponibile e rimuove le azioni duplicate. Questo ne facilita l’uso nelle finestre strette.",
    "tr": "Araştırma Sohbeti üst bilgisi, kontrolleri kullanılabilir alan içinde tutar ve yinelenen işlemleri kaldırır. Böylece dar pencerelerde kullanımı kolaylaşır.",
    "zh-CN": "研究聊天的顶部控件保持在可用空间内，并移除了重复操作。在较窄窗口中使用更加方便。",
    "zh-TW": "研究聊天的頂部控制項保持在可用空間內，並移除了重複操作。在較窄視窗中使用更加方便。",
    "ja": "研究チャットのヘッダーは操作ボタンを利用可能な幅に収め、重複する操作を削除します。幅の狭いウィンドウでも使いやすくなります。",
    "ko": "연구 채팅의 상단 컨트롤이 사용 가능한 공간 안에 배치되고 중복 작업이 제거됩니다. 폭이 좁은 창에서도 사용하기 편리합니다."
  },
  {
    "scope": "estudio",
    "es": "En Estudio y Docencia puedes seleccionar las fuentes del chat por curso, asignatura y carpeta. El buscador encuentra títulos, nombres de archivo, etiquetas y ubicaciones. Puedes seleccionar grupos y conservar la selección al filtrar.",
    "en": "In Study and Teaching, you can select chat sources by course, subject and folder. Search finds titles, filenames, tags and locations. You can select groups and keep your selection while filtering.",
    "fr": "Dans Étude et Enseignement, vous pouvez sélectionner les sources du chat par cursus, matière et dossier. La recherche trouve les titres, noms de fichiers, étiquettes et emplacements. Vous pouvez sélectionner des groupes et conserver la sélection pendant le filtrage.",
    "de": "In Studium und Lehre kannst du Chatquellen nach Kurs, Fach und Ordner auswählen. Die Suche findet Titel, Dateinamen, Tags und Ablageorte. Du kannst Gruppen auswählen und die Auswahl beim Filtern beibehalten.",
    "pt": "Em Estudo e Ensino, podes selecionar fontes do chat por curso, disciplina e pasta. A pesquisa encontra títulos, nomes de ficheiros, etiquetas e localizações. Podes selecionar grupos e manter a seleção ao filtrar.",
    "pt-BR": "Em Estudo e Ensino, você pode selecionar fontes do chat por curso, disciplina e pasta. A busca encontra títulos, nomes de arquivos, etiquetas e locais. Você pode selecionar grupos e manter a seleção ao filtrar.",
    "it": "In Studio e Didattica puoi selezionare le fonti della chat per corso, materia e cartella. La ricerca trova titoli, nomi di file, etichette e posizioni. Puoi selezionare gruppi e mantenere la selezione durante il filtraggio.",
    "tr": "Çalışma ve Öğretim alanlarında sohbet kaynaklarını kurs, ders ve klasöre göre seçebilirsiniz. Arama, başlıkları, dosya adlarını, etiketleri ve konumları bulur. Grupları seçebilir ve filtreleme sırasında seçiminizi koruyabilirsiniz.",
    "zh-CN": "在学习和教学库中，可以按课程、科目和文件夹选择聊天来源。搜索支持标题、文件名、标签和位置。可以按组选取，筛选时保留已有选择。",
    "zh-TW": "在學習與教學庫中，可以按課程、科目和資料夾選擇聊天來源。搜尋支援標題、檔案名稱、標籤和位置。可以按群組選取，篩選時保留既有選擇。",
    "ja": "学習と教育では、コース、科目、フォルダーごとにチャットのソースを選べます。検索はタイトル、ファイル名、タグ、保存場所に対応しています。グループを選択でき、絞り込み中も選択内容を保持します。",
    "ko": "학습과 교육에서 과정, 과목, 폴더별로 채팅 출처를 선택할 수 있습니다. 검색은 제목, 파일 이름, 태그, 위치를 찾습니다. 그룹을 선택하고 필터링 중에도 선택을 유지할 수 있습니다."
  },
  {
    "scope": "estudio",
    "es": "En Estudio y Docencia puedes mover notas y materiales entre ubicaciones desde la lista o la cuadrícula. Se conservan el contenido, las anotaciones, el conocimiento generado y las demás ubicaciones. Las carpetas y los temas usan la misma acción de mover.",
    "en": "In Study and Teaching, you can move notes and materials between locations from the list or grid. Content, annotations, generated knowledge and other locations are preserved. Folders and topics use the same move action.",
    "fr": "Dans Étude et Enseignement, vous pouvez déplacer notes et documents entre emplacements depuis la liste ou la grille. Le contenu, les annotations, les connaissances générées et les autres emplacements sont conservés. Les dossiers et sujets utilisent la même action de déplacement.",
    "de": "In Studium und Lehre kannst du Notizen und Materialien aus der Liste oder dem Raster an einen anderen Ort verschieben. Inhalt, Anmerkungen, erzeugtes Wissen und weitere Ablageorte bleiben erhalten. Ordner und Themen verwenden dieselbe Verschiebeaktion.",
    "pt": "Em Estudo e Ensino, podes mover notas e materiais entre localizações a partir da lista ou grelha. São preservados o conteúdo, as anotações, o conhecimento gerado e as outras localizações. As pastas e os tópicos usam a mesma ação de mover.",
    "pt-BR": "Em Estudo e Ensino, você pode mover notas e materiais entre locais pela lista ou grade. O conteúdo, as anotações, o conhecimento gerado e os demais locais são preservados. As pastas e os tópicos usam a mesma ação de mover.",
    "it": "In Studio e Didattica puoi spostare note e materiali tra posizioni dalla lista o dalla griglia. Contenuti, annotazioni, conoscenze generate e altre posizioni vengono conservati. Cartelle e argomenti usano la stessa azione di spostamento.",
    "tr": "Çalışma ve Öğretim alanlarında notları ve materyalleri liste veya ızgaradan farklı konumlara taşıyabilirsiniz. İçerik, açıklamalar, oluşturulan bilgi ve diğer konumlar korunur. Klasörler ve konular aynı taşıma işlemini kullanır.",
    "zh-CN": "在学习和教学库中，可以从列表或网格将笔记和资料移动到其他位置。内容、批注、已生成的知识和其他存放位置均会保留。文件夹和课题也使用相同的移动操作。",
    "zh-TW": "在學習與教學庫中，可以從清單或格狀檢視將筆記和教材移至其他位置。內容、註解、已產生的知識和其他存放位置皆會保留。資料夾與課題也使用相同的移動操作。",
    "ja": "学習と教育では、一覧またはグリッドからノートや資料の保存場所を移動できます。内容、注釈、生成済みの知識、ほかの保存場所は保持されます。フォルダーとトピックも同じ移動操作を使います。",
    "ko": "학습과 교육에서 목록 또는 격자를 통해 노트와 자료를 다른 위치로 이동할 수 있습니다. 내용, 주석, 생성된 지식, 다른 저장 위치는 유지됩니다. 폴더와 항목도 같은 이동 작업을 사용합니다."
  },
  {
    "scope": "nodi",
    "es": "Nodi busca en la documentación de Nodus la información relacionada con tus preguntas sobre la aplicación. Así puede explicar funciones, ajustes y procedimientos con información más completa. El selector de Skills también evita el desplazamiento horizontal.",
    "en": "Nodi searches the Nodus documentation for information relevant to your questions about the app. This provides more complete information about features, settings and procedures. The Skills picker also avoids horizontal scrolling.",
    "fr": "Nodi recherche dans la documentation de Nodus les informations liées à vos questions sur l’application. Il dispose ainsi d’informations plus complètes sur les fonctions, réglages et procédures. Le sélecteur de Skills évite aussi le défilement horizontal.",
    "de": "Nodi sucht in der Nodus-Dokumentation nach Informationen zu deinen Fragen über die App. Damit stehen vollständigere Informationen zu Funktionen, Einstellungen und Abläufen bereit. Die Skills-Auswahl vermeidet außerdem horizontales Scrollen.",
    "pt": "O Nodi pesquisa na documentação do Nodus informações relacionadas com as tuas perguntas sobre a aplicação. Assim dispõe de informação mais completa sobre funções, definições e procedimentos. O seletor de Skills também evita o deslocamento horizontal.",
    "pt-BR": "O Nodi busca na documentação do Nodus informações relacionadas às suas perguntas sobre o aplicativo. Assim dispõe de informações mais completas sobre funções, configurações e procedimentos. O seletor de Skills também evita a rolagem horizontal.",
    "it": "Nodi cerca nella documentazione di Nodus le informazioni relative alle tue domande sull’applicazione. Dispone così di informazioni più complete su funzioni, impostazioni e procedure. Il selettore Skills evita anche lo scorrimento orizzontale.",
    "tr": "Nodi, uygulamayla ilgili sorularınız için Nodus belgelerinde ilgili bilgileri arar. Böylece özellikler, ayarlar ve işlemler hakkında daha kapsamlı bilgi kullanabilir. Skills seçicisi de yatay kaydırmayı önler.",
    "zh-CN": "Nodi 在 Nodus 文档中查找与你的应用使用问题相关的信息，从而更完整地说明功能、设置和操作步骤。Skills 选择器也避免了横向滚动。",
    "zh-TW": "Nodi 在 Nodus 文件中查找與你的應用程式使用問題相關的資訊，從而更完整地說明功能、設定和操作步驟。Skills 選擇器也避免了水平捲動。",
    "ja": "Nodi は、アプリについての質問に関連する情報を Nodus のドキュメントから検索します。機能、設定、手順について、より充実した情報を利用できます。Skills の選択画面では横スクロールも防ぎます。",
    "ko": "Nodi가 앱 관련 질문에 필요한 정보를 Nodus 문서에서 검색합니다. 기능, 설정, 절차에 관해 더 완전한 정보를 활용할 수 있습니다. Skills 선택기에서도 가로 스크롤이 발생하지 않도록 수정했습니다."
  },
  {
    "scope": "toolkit",
    "es": "Nodus Tools reúne las utilidades y herramientas de investigación en un catálogo con buscador. Puedes abrir una herramienta desde el catálogo y fijarla por separado en la barra lateral.",
    "en": "Nodus Tools brings utilities and research tools together in a searchable catalogue. You can open a tool from the catalogue and pin it individually to the sidebar.",
    "fr": "Nodus Tools regroupe les utilitaires et outils de recherche dans un catalogue avec recherche. Vous pouvez ouvrir un outil depuis le catalogue et l’épingler individuellement dans la barre latérale.",
    "de": "Nodus Tools vereint Hilfsprogramme und Forschungswerkzeuge in einem durchsuchbaren Katalog. Du kannst ein Werkzeug dort öffnen und einzeln in der Seitenleiste anheften.",
    "pt": "O Nodus Tools reúne utilitários e ferramentas de investigação num catálogo com pesquisa. Podes abrir uma ferramenta no catálogo e fixá-la individualmente na barra lateral.",
    "pt-BR": "O Nodus Tools reúne utilitários e ferramentas de pesquisa em um catálogo com busca. Você pode abrir uma ferramenta pelo catálogo e fixá-la individualmente na barra lateral.",
    "it": "Nodus Tools riunisce utilità e strumenti di ricerca in un catalogo con ricerca. Puoi aprire uno strumento dal catalogo e fissarlo singolarmente nella barra laterale.",
    "tr": "Nodus Tools, yardımcı araçları ve araştırma araçlarını aranabilir bir katalogda toplar. Bir aracı katalogdan açabilir ve kenar çubuğuna ayrı olarak sabitleyebilirsiniz.",
    "zh-CN": "Nodus Tools 将实用工具和研究工具集中在可搜索的目录中。你可以从目录打开工具，并将各个工具单独固定到侧边栏。",
    "zh-TW": "Nodus Tools 將實用工具與研究工具集中在可搜尋的目錄中。你可以從目錄開啟工具，並將各個工具個別釘選到側邊欄。",
    "ja": "Nodus Tools は、ユーティリティと研究ツールを検索可能なカタログにまとめます。カタログからツールを開き、個別にサイドバーへ固定できます。",
    "ko": "Nodus Tools는 유틸리티와 연구 도구를 검색 가능한 목록으로 제공합니다. 목록에서 도구를 열고 각 도구를 개별적으로 사이드바에 고정할 수 있습니다."
  },
  {
    "scope": "zotero",
    "es": "El complemento de Zotero cierra su base de datos al salir, aunque hayas cerrado antes la barra lateral. Esto corrige un problema que podía impedir que Zotero terminara de cerrarse y bloquear el siguiente inicio.",
    "en": "The Zotero plugin closes its database on exit, even if you closed the sidebar first. This fixes a problem that could prevent Zotero from shutting down and block the next launch.",
    "fr": "Le module Zotero ferme sa base de données à la sortie, même si vous avez déjà fermé la barre latérale. Cela corrige un problème qui pouvait empêcher Zotero de se fermer et bloquer son prochain démarrage.",
    "de": "Das Zotero-Plugin schließt beim Beenden seine Datenbank, auch wenn die Seitenleiste zuvor geschlossen wurde. Dies behebt einen Fehler, der das Beenden von Zotero verhindern und den nächsten Start blockieren konnte.",
    "pt": "O complemento do Zotero fecha a base de dados ao sair, mesmo que tenhas fechado primeiro a barra lateral. Isto corrige um problema que podia impedir o Zotero de encerrar e bloquear o arranque seguinte.",
    "pt-BR": "O complemento do Zotero fecha o banco de dados ao sair, mesmo que você tenha fechado a barra lateral antes. Isso corrige um problema que podia impedir o Zotero de encerrar e bloquear a próxima inicialização.",
    "it": "Il componente aggiuntivo Zotero chiude il database all’uscita, anche se hai già chiuso la barra laterale. Questo risolve un problema che poteva impedire a Zotero di chiudersi e bloccare l’avvio successivo.",
    "tr": "Zotero eklentisi, kenar çubuğunu önceden kapatmış olsanız bile çıkışta veritabanını kapatır. Bu, Zotero’nun kapanmasını engelleyebilen ve sonraki açılışı durdurabilen bir sorunu düzeltir.",
    "zh-CN": "Zotero 插件在退出时关闭数据库，即使你此前已关闭侧边栏也会如此。这修复了可能导致 Zotero 无法完全退出、阻止下次启动的问题。",
    "zh-TW": "Zotero 外掛程式在結束時關閉資料庫，即使你先前已關閉側邊欄也會如此。這修正了可能導致 Zotero 無法完全結束、阻止下次啟動的問題。",
    "ja": "Zotero プラグインは、先にサイドバーを閉じていても終了時にデータベースを閉じます。Zotero が終了できず、次回の起動が妨げられることがあった問題を修正します。",
    "ko": "Zotero 플러그인은 사이드바를 먼저 닫았더라도 종료 시 데이터베이스를 닫습니다. Zotero가 완전히 종료되지 않아 다음 실행이 차단될 수 있었던 문제를 수정합니다."
  }
];
