import type { ReleaseHighlight } from './releaseNotes';

/**
 * v5.4.4: Simplified Chinese becomes a full ninth interface language, exported
 * PDFs keep CJK text on desktop and server, document scans survive dropped
 * connections and picky gateways, and the library list stays fresh after a
 * global link. Keep the IT/TR arrays aligned with this order: they are matched
 * by index.
 */
export const RELEASE_5_4_4_HIGHLIGHTS: ReleaseHighlight[] = [
  {
    scope: 'languages',
    es: 'Nodus ya habla chino simplificado. Puedes elegirlo en Ajustes y toda la interfaz lo sigue, incluidos los menús, los diálogos de archivo, los mensajes de error y las bóvedas de demostración que se abren al empezar. Nada se queda en español o en inglés después de cambiar.',
    en: 'Nodus now speaks Simplified Chinese. You can pick it in Settings and the whole interface follows, including menus, file dialogs, error messages and the demo vaults that open on first run. Nothing stays in Spanish or English after you switch.',
    fr: 'Nodus parle désormais chinois simplifié. Vous le choisissez dans les Paramètres et toute l’interface suit, y compris les menus, les dialogues de fichier, les messages d’erreur et les coffres de démonstration qui s’ouvrent au démarrage. Rien ne reste en espagnol ou en anglais après le changement.',
    de: 'Nodus spricht jetzt Vereinfachtes Chinesisch. Sie wählen es in den Einstellungen und die gesamte Oberfläche folgt, einschließlich Menüs, Dateidialoge, Fehlermeldungen und der Demo-Tresore beim ersten Start. Nach dem Wechsel bleibt nichts auf Spanisch oder Englisch stehen.',
    pt: 'O Nodus passa a falar chinês simplificado. Pode escolhê-lo nas Definições e toda a interface acompanha, incluindo menus, diálogos de ficheiro, mensagens de erro e os cofres de demonstração que abrem ao começar. Nada fica em espanhol ou inglês depois de mudar.',
    'pt-BR': 'O Nodus agora fala chinês simplificado. Você escolhe em Configurações e a interface inteira acompanha, incluindo menus, diálogos de arquivo, mensagens de erro e os cofres de demonstração que abrem no início. Nada fica em espanhol ou inglês depois de trocar.',
    it: 'Nodus ora parla cinese semplificato. Lo scegli nelle Impostazioni e l’intera interfaccia segue, inclusi menu, finestre di dialogo dei file, messaggi di errore e i depositi dimostrativi che si aprono all’inizio. Dopo il cambio nulla resta in spagnolo o in inglese.',
    tr: 'Nodus artık Basitleştirilmiş Çince konuşuyor. Ayarlar içinden seçiyorsunuz ve menüler, dosya pencereleri, hata iletileri ve ilk açılışta gelen tanıtım kasaları dahil tüm arayüz bunu izliyor. Değişimden sonra hiçbir şey İspanyolca veya İngilizce kalmıyor.',
    'zh-CN': 'Nodus现在支持简体中文。你可以在设置中选择，整个界面都会跟随，包括菜单、文件对话框、错误信息以及首次运行时打开的演示库。切换之后，不会再有残留的西班牙语或英语界面。',
  },
  {
    scope: 'general',
    es: 'Los PDF exportados ya conservan el texto en chino, japonés y coreano. Los informes, las marcas de agua y las anotaciones de estudio perdían esos caracteres o fallaban por completo. Tanto la aplicación de escritorio como el servidor ahora incluyen una fuente china compacta y ajustan esas líneas carácter a carácter, así que los informes en alfabeto latino se ven igual que antes.',
    en: 'Exported PDFs now keep Chinese, Japanese and Korean text. Reports, watermarks and study annotations used to lose those characters or fail outright. Both the desktop app and the server now embed a compact Chinese font and wrap those lines character by character, so Latin reports look exactly as before.',
    fr: 'Les PDF exportés conservent désormais le texte en chinois, japonais et coréen. Les rapports, les filigranes et les annotations d’étude perdaient ces caractères ou échouaient complètement. L’application de bureau et le serveur intègrent maintenant une police chinoise compacte et découpent ces lignes caractère par caractère, et les rapports en alphabet latin gardent exactement leur aspect.',
    de: 'Exportierte PDFs behalten jetzt chinesischen, japanischen und koreanischen Text. Berichte, Wasserzeichen und Studienanmerkungen verloren diese Zeichen oder schlugen vollständig fehl. Die Desktop-App und der Server betten nun eine kompakte chinesische Schrift ein und umbrechen diese Zeilen Zeichen für Zeichen, sodass lateinische Berichte genau wie bisher aussehen.',
    pt: 'Os PDF exportados passam a conservar o texto em chinês, japonês e coreano. Os relatórios, as marcas de água e as anotações de estudo perdiam esses caracteres ou falhavam por completo. A aplicação de secretária e o servidor incluem agora um tipo de letra chinês compacto e ajustam essas linhas carácter a carácter, por isso os relatórios em alfabeto latino mantêm exatamente o mesmo aspeto.',
    'pt-BR': 'Os PDFs exportados agora preservam o texto em chinês, japonês e coreano. Relatórios, marcas d’água e anotações de estudo perdiam esses caracteres ou falhavam por completo. O aplicativo de desktop e o servidor agora incluem uma fonte chinesa compacta e quebram essas linhas caractere por caractere, então os relatórios em alfabeto latino ficam exatamente como antes.',
    it: 'I PDF esportati ora conservano il testo in cinese, giapponese e coreano. I report, le filigrane e le annotazioni di studio perdevano quei caratteri o fallivano del tutto. L’app desktop e il server includono ora un font cinese compatto e mandano a capo quelle righe carattere per carattere, così i report in alfabeto latino restano esattamente come prima.',
    tr: 'Dışa aktarılan PDF’ler artık Çince, Japonca ve Korece metinleri koruyor. Raporlar, filigranlar ve çalışma notları bu karakterleri kaybediyor veya tamamen başarısız oluyordu. Masaüstü uygulaması ve sunucu artık kompakt bir Çince yazı tipi gömüyor ve bu satırları karakter karakter kaydırıyor, bu yüzden Latin alfabesiyle yazılmış raporlar eskisi gibi görünüyor.',
    'zh-CN': '导出的PDF现在可以保留中文、日文和韩文。正文报告、水印和学习批注过去会丢失这些字符，甚至直接导出失败。桌面端和服务器现在都会嵌入一款紧凑的中文字体，并对这些行按字符逐字换行，因此拉丁字母报告的外观与之前完全一致。',
  },
  {
    scope: 'ai',
    es: 'Los análisis de documentos sobreviven a conexiones caídas y a pasarelas exigentes. Si la red se cae a mitad del análisis, Nodus ahora lo reintenta en lugar de fallar con un error de conexión. Los modelos de razonamiento personalizados también reciben control explícito sobre su razonamiento privado, y una pista rechazada nunca tumba el análisis por sí sola.',
    en: 'Document scans survive dropped connections and picky gateways. If the network drops mid-scan, Nodus now retries instead of failing with a connection error. Custom thinking models also get explicit control over their private reasoning, and a rejected reasoning hint never fails the scan on its own.',
    fr: 'Les analyses de documents survivent aux connexions coupées et aux passerelles exigeantes. Si le réseau tombe en pleine analyse, Nodus réessaie au lieu d’échouer sur une erreur de connexion. Les modèles de raisonnement personnalisés reçoivent aussi un contrôle explicite sur leur raisonnement privé, et une indication rejetée ne fait jamais échouer l’analyse à elle seule.',
    de: 'Dokumentenanalysen überstehen abgebrochene Verbindungen und wählerische Gateways. Fällt das Netz mitten in der Analyse aus, versucht Nodus es nun erneut, statt mit einem Verbindungsfehler zu scheitern. Eigene Denkmodelle erhalten außerdem eine ausdrückliche Kontrolle über ihr privates Nachdenken, und ein abgelehnter Denkanstoß lässt die Analyse niemals allein scheitern.',
    pt: 'As análises de documentos sobrevivem a ligações caídas e a gateways exigentes. Se a rede cair a meio da análise, o Nodus tenta de novo em vez de falhar com um erro de ligação. Os modelos de raciocínio personalizados também recebem controlo explícito sobre o seu raciocínio privado, e uma pista rejeitada nunca deita a análise abaixo por si só.',
    'pt-BR': 'As análises de documentos sobrevivem a conexões caídas e a gateways exigentes. Se a rede cair no meio da análise, o Nodus tenta de novo em vez de falhar com um erro de conexão. Os modelos de raciocínio personalizados também ganham controle explícito sobre seu raciocínio privado, e uma dica rejeitada nunca derruba a análise sozinha.',
    it: 'Le analisi dei documenti sopravvivono a connessioni cadute e a gateway esigenti. Se la rete cade a metà analisi, Nodus ora riprova invece di fallire con un errore di connessione. Anche i modelli di ragionamento personalizzati ricevono un controllo esplicito sul proprio ragionamento privato, e un suggerimento rifiutato non fa mai fallire l’analisi da solo.',
    tr: 'Belge taramaları kopan bağlantılara ve seçici ağ geçitlerine dayanıyor. Ağ taramanın ortasında koparsa Nodus artık bir bağlantı hatasıyla düşmek yerine yeniden deniyor. Özel düşünme modelleri de kendi gizli akıl yürütmeleri üzerinde açık bir denetim alıyor ve reddedilen bir ipucu taramayı tek başına asla düşürmüyor.',
    'zh-CN': '文档扫描现在能承受连接中断和挑剔的网关。如果网络在扫描中途断开，Nodus会重试，而不是直接报连接错误失败。自定义思考模型也可以明确控制其私有推理过程，被拒绝的推理提示绝不会单独导致扫描失败。',
  },
  {
    scope: 'library',
    es: 'La lista de la biblioteca se mantiene al día y la cola de extracción habla tu idioma. Enlazar documentos desde la biblioteca global ahora actualiza la vista de la bóveda al momento en lugar de mostrar la página anterior. Los mensajes de la cola están totalmente traducidos, y los trabajos sueltos del Índice documental aparecen con su propio reintento y cuentan para la insignia del encabezado.',
    en: 'The library list stays fresh and the extraction queue speaks your language. Linking documents from the global library now refreshes the vault view at once instead of showing the old page. Queue messages are fully translated, and standalone Documentary Index jobs appear with their own retry and count toward the header badge.',
    fr: 'La liste de la bibliothèque reste à jour et la file d’extraction parle votre langue. Lier des documents depuis la bibliothèque globale actualise désormais la vue du coffre aussitôt au lieu d’afficher l’ancienne page. Les messages de la file sont entièrement traduits, et les tâches isolées de l’Index documentaire apparaissent avec leur propre bouton de reprise et comptent dans le badge de l’en-tête.',
    de: 'Die Bibliotheksliste bleibt frisch und die Extraktionswarteschlange spricht Ihre Sprache. Das Verknüpfen von Dokumenten aus der globalen Bibliothek aktualisiert jetzt sofort die Tresoransicht, statt die alte Seite zu zeigen. Warteschlangenmeldungen sind vollständig übersetzt, und eigenständige Jobs des Dokumentenindex erscheinen mit eigenem Wiederholen und zählen für die Kopfzeilenplakette.',
    pt: 'A lista da biblioteca mantém-se atualizada e a fila de extração fala a sua língua. Ligar documentos da biblioteca global atualiza agora a vista do cofre de imediato em vez de mostrar a página antiga. As mensagens da fila estão totalmente traduzidas, e os trabalhos isolados do Índice documental aparecem com a sua própria repetição e contam para o emblema do cabeçalho.',
    'pt-BR': 'A lista da biblioteca fica atualizada e a fila de extração fala o seu idioma. Vincular documentos da biblioteca global agora atualiza a visão do cofre na hora em vez de mostrar a página antiga. As mensagens da fila estão totalmente traduzidas, e os trabalhos avulsos do Índice documental aparecem com a própria repetição e contam para o selo do cabeçalho.',
    it: 'L’elenco della biblioteca resta aggiornato e la coda di estrazione parla la tua lingua. Collegare documenti dalla biblioteca globale ora aggiorna subito la vista del deposito invece di mostrare la pagina precedente. I messaggi della coda sono interamente tradotti, e i lavori isolati dell’Indice documentale compaiono con il proprio pulsante di ripetizione e contano per il distintivo dell’intestazione.',
    tr: 'Kütüphane listesi güncel kalıyor ve çıkarma kuyruğu sizin dilinizi konuşuyor. Genel kütüphaneden belge bağlamak artık eski sayfayı göstermek yerine kasa görünümünü hemen yeniliyor. Kuyruk iletileri tamamen çevrildi ve bağımsız Belgesel Dizin işleri kendi yeniden deneme düğmesiyle görünüyor ve başlık rozetine sayılıyor.',
    'zh-CN': '文献库列表保持最新，抽取队列也会说你的语言。从全局文献库链接文档后，库视图会立即刷新，不再显示旧页面。队列消息已全部翻译，独立的文献索引任务会显示自己的重试按钮，并计入顶栏角标。',
  },
];
