import type { ReleaseHighlight } from './releaseNotes';

/**
 * v5.4.2: the rebuilt Study question bank with Anki and Moodle interchange, Markdown
 * and LaTeX on every question and flashcard surface, seven new prompt languages, the
 * unified Marketplace catalogue and the fixes merged since 5.4.1. Keep the IT/TR
 * arrays aligned with this order: they are matched by index.
 */
export const RELEASE_5_4_2_HIGHLIGHTS: ReleaseHighlight[] = [
  {
    scope: 'estudio',
    es: 'El banco de preguntas de Estudio se reconstruye para trabajar en volumen. Preguntas y tarjetas viven en dos pestañas, con búsqueda y filtros por asignatura, tema, nivel cognitivo, fuente, material, documento, etiqueta o colección, ordenación y selección múltiple. Aplica estado, dificultad, categoría, etiquetas, colección y repaso a una selección entera, y crea, edita o borra cada tarjeta con sus propias acciones de repaso espaciado.',
    en: 'The Study question bank is rebuilt for working in volume. Questions and flashcards live in two tabs, with search and filters by subject, topic, cognitive level, source, material, document, tag or collection, sorting and multi-select. Apply status, difficulty, category, tags, collection and review state to a whole selection, and create, edit or delete each flashcard with its own spaced-repetition actions.',
    fr: 'La banque de questions d’Étude est reconstruite pour le travail en volume. Questions et cartes vivent dans deux onglets, avec recherche et filtres par matière, thème, niveau cognitif, source, matériel, document, étiquette ou collection, tri et sélection multiple. Appliquez statut, difficulté, catégorie, étiquettes, collection et état de révision à une sélection entière, et créez, modifiez ou supprimez chaque carte avec ses propres actions de révision espacée.',
    de: 'Die Fragenbank von Studium wird für die Arbeit in großem Umfang neu aufgebaut. Fragen und Karteikarten liegen in zwei Registerkarten, mit Suche und Filtern nach Fach, Thema, kognitiver Stufe, Quelle, Material, Dokument, Tag oder Sammlung, Sortierung und Mehrfachauswahl. Status, Schwierigkeit, Kategorie, Tags, Sammlung und Wiederholungsstand lassen sich auf eine ganze Auswahl anwenden. Jede Karteikarte wird mit ihren eigenen Aktionen für verteilte Wiederholung erstellt, bearbeitet oder gelöscht.',
    pt: 'O banco de perguntas do Estudo é reconstruído para trabalhar em volume. Perguntas e cartões vivem em dois separadores, com pesquisa e filtros por disciplina, tema, nível cognitivo, fonte, material, documento, etiqueta ou coleção, ordenação e seleção múltipla. Aplica estado, dificuldade, categoria, etiquetas, coleção e revisão a uma seleção inteira, e cria, edita ou elimina cada cartão com as suas próprias ações de revisão espaçada.',
    'pt-BR': 'O banco de questões do Estudo é reconstruído para trabalhar em volume. Questões e flashcards ficam em duas abas, com busca e filtros por disciplina, tema, nível cognitivo, fonte, material, documento, tag ou coleção, ordenação e seleção múltipla. Aplique status, dificuldade, categoria, tags, coleção e revisão a uma seleção inteira, e crie, edite ou exclua cada flashcard com suas próprias ações de revisão espaçada.',
    it: 'Il banco di domande di Studio viene ricostruito per lavorare in volume. Domande e flashcard vivono in due schede, con ricerca e filtri per materia, argomento, livello cognitivo, fonte, materiale, documento, tag o raccolta, ordinamento e selezione multipla. Applica stato, difficoltà, categoria, tag, raccolta e ripasso a un’intera selezione, e crea, modifica o elimina ogni flashcard con le sue azioni di ripetizione dilazionata.',
    tr: 'Çalışma soru bankası yoğun kullanım için yeniden kuruldu. Sorular ve kartlar iki sekmede yaşıyor. Ders, konu, bilişsel düzey, kaynak, materyal, belge, etiket veya koleksiyona göre arama ve filtreler, sıralama ve çoklu seçim var. Durum, zorluk, kategori, etiketler, koleksiyon ve tekrar durumunu tüm seçime uygulayın. Her kartı kendi aralıklı tekrar işlemleriyle oluşturun, düzenleyin veya silin.',
    'zh-CN': "学习题库为大批量操作而重建。问题与卡片分列两个标签页，支持搜索，以及按学科、主题、认知层级、来源、材料、文档、标签或合集筛选，支持排序和多选。可对整个选择应用状态、难度、类别、标签、合集和复习进度，并通过各自的间隔复习操作创建、编辑或删除每张卡片。",
    'zh-TW': "學習題庫為大批次操作而重建。問題與卡片分列兩個標籤頁，支援搜尋，以及按學科、主題、認知層級、來源、材料、文件、標籤或合集篩選，支援排序和多選。可對整個選擇應用狀態、難度、類別、標籤、合集和複習進度，並通過各自的間隔複習操作建立、編輯或刪除每張卡片。",
    ko: "학습 문제 은행은 대량 작업을 위해 재구성되었습니다. 질문과 플래시카드는 주제, 주제, 인지 수준, 소스, 자료, 문서, 태그 또는 컬렉션별 검색 및 필터, 정렬 및 다중 선택 기능이 있는 두 개의 탭에 있습니다. 상태, 난이도, 카테고리, 태그, 컬렉션 및 검토 상태를 전체 선택 항목에 적용하고 고유한 간격 반복 동작으로 각 플래시카드를 생성, 편집 또는 삭제합니다.",
    ja: "学習用の質問バンクは、大量に作業できるように再構築されています。質問とフラッシュカードは2つのタブに表示され、主題、トピック、認知レベル、ソース、資料、ドキュメント、タグまたはコレクションによる検索とフィルター、並べ替えと複数選択が可能です。ステータス、難易度、カテゴリ、タグ、コレクションおよびレビュー状態を選択全体に適用し、独自の間隔をあけた繰り返しアクションで各フラッシュカードを作成、編集、または削除します。",
  },
  {
    scope: 'estudio',
    es: 'El banco deja de estar encerrado. Importa y exporta Anki, con paquetes .apkg y TSV, cuestionarios Moodle en XML y GIFT, CSV y el propio JSON de Nodus desde un solo diálogo, que muestra qué va a entrar antes de tocar tus preguntas.',
    en: 'The bank is no longer locked in. Import and export Anki, with .apkg packages and TSV, Moodle quizzes in XML and GIFT, CSV and Nodus’s own JSON from one dialog that shows what will come in before touching your questions.',
    fr: 'La banque n’est plus fermée. Importez et exportez Anki, avec les paquets .apkg et TSV, les questionnaires Moodle en XML et GIFT, le CSV et le JSON propre à Nodus depuis une seule fenêtre, qui montre ce qui va entrer avant de toucher à vos questions.',
    de: 'Die Bank bleibt nicht länger verschlossen. Importieren und exportieren Sie Anki mit .apkg-Paketen und TSV, Moodle-Tests in XML und GIFT, CSV und Nodus-eigenes JSON in einem einzigen Dialog, der vorher zeigt, was hereinkommt.',
    pt: 'O banco deixa de estar fechado. Importa e exporta Anki, com pacotes .apkg e TSV, questionários Moodle em XML e GIFT, CSV e o próprio JSON do Nodus num único diálogo, que mostra o que vai entrar antes de tocar nas perguntas.',
    'pt-BR': 'O banco deixa de ficar preso. Importe e exporte Anki, com pacotes .apkg e TSV, questionários Moodle em XML e GIFT, CSV e o próprio JSON do Nodus em uma única janela, que mostra o que vai entrar antes de tocar nas questões.',
    it: 'Il banco non resta più chiuso. Importa ed esporta Anki, con pacchetti .apkg e TSV, questionari Moodle in XML e GIFT, CSV e il JSON di Nodus da un’unica finestra, che mostra cosa entrerà prima di toccare le domande.',
    tr: 'Soru bankası artık kapalı değil. Anki, .apkg paketleri ve TSV dahil, Moodle sınavları, XML ve GIFT dahil, CSV ve Nodus’un kendi JSON biçimi tek bir pencereden içe ve dışa aktarılıyor. Pencere, sorularınıza dokunmadan önce neyin gireceğini gösteriyor.',
    'zh-CN': "题库不再封闭。通过一个对话框即可导入和导出Anki（.apkg包和TSV）、Moodle的XML和GIFT测验、CSV以及Nodus自己的JSON，并在改动你的问题之前显示将要导入的内容。",
    'zh-TW': "題庫不再封閉。通過一個對話方塊即可匯入和匯出Anki（.apkg包和TSV）、Moodle的XML和GIFT測驗、CSV以及Nodus自己的JSON，並在改動你的問題之前顯示將要匯入的內容。",
    ko: "은행은 더 이상 갇혀 있지 않습니다. 질문을 터치하기 전에 무엇이 나올지 보여주는 하나의 대화 상자에서.apkg 패키지와 TSV, XML 및 GIFT, CSV 및 Nodus의 자체 JSON으로 된 Moodle 퀴즈를 사용하여 Anki를 가져오고 내보낼 수 있습니다.",
    ja: "銀行はもうロックインされません。.apkg パッケージと TSV を使用した Anki、XML と GIFT の Moodle クイズ、CSV、および Nodus 独自の JSON を、質問に触れる前に何が表示されるかを示す1つのダイアログからインポートおよびエクスポートします。",
  },
  {
    scope: 'estudio',
    es: 'Las preguntas y tarjetas ya se leen como están escritas. Markdown y las fórmulas LaTeX se componen en el enunciado, las opciones, la respuesta y la explicación en todas las superficies, del banco y la sesión de repaso a la generación con IA, el generador de exámenes y los cuestionarios. Los campos de escritura ganan vista previa y el servidor web también las compone.',
    en: 'Questions and flashcards now read as they were written. Markdown and LaTeX formulas are typeset in the prompt, the options, the answer and the explanation on every surface, from the bank and the review session to AI generation, the exam builder and quizzes. Writing fields gain a preview, and the web server typesets them too.',
    fr: 'Les questions et les cartes se lisent désormais telles qu’elles ont été écrites. Le Markdown et les formules LaTeX sont composés dans l’énoncé, les options, la réponse et l’explication sur toutes les surfaces, de la banque et la session de révision à la génération par IA, le générateur d’examens et les quiz. Les champs de saisie gagnent un aperçu et le serveur web les compose aussi.',
    de: 'Fragen und Karteikarten lesen sich jetzt so, wie sie geschrieben wurden. Markdown und LaTeX-Formeln werden in Aufgabenstellung, Optionen, Antwort und Erklärung überall gesetzt, von der Bank und der Wiederholungssitzung bis zur KI-Erzeugung, dem Prüfungsgenerator und Quizzen. Eingabefelder erhalten eine Vorschau, und der Webserver setzt sie ebenfalls.',
    pt: 'As perguntas e os cartões leem-se agora como foram escritos. O Markdown e as fórmulas LaTeX são compostos no enunciado, nas opções, na resposta e na explicação em todas as superfícies, do banco e da sessão de revisão à geração com IA, ao gerador de exames e aos questionários. Os campos de escrita ganham pré-visualização e o servidor web também as compõe.',
    'pt-BR': 'As questões e os flashcards agora são lidos como foram escritos. Markdown e fórmulas LaTeX são compostos no enunciado, nas opções, na resposta e na explicação em todas as superfícies, do banco e da sessão de revisão à geração com IA, ao gerador de provas e aos questionários. Os campos de escrita ganham pré-visualização e o servidor web também as compõe.',
    it: 'Domande e flashcard ora si leggono come sono stati scritti. Markdown e formule LaTeX vengono composti in consegna, opzioni, risposta e spiegazione su ogni superficie, dal banco alla sessione di ripasso, fino alla generazione con IA, al generatore di esami e ai quiz. I campi di scrittura guadagnano l’anteprima e anche il server web le compone.',
    tr: 'Sorular ve kartlar artık yazıldıkları gibi okunuyor. Markdown ve LaTeX formülleri soru metninde, seçeneklerde, yanıtta ve açıklamada her yüzeyde diziliyor. Soru bankası ve tekrar oturumundan yapay zekâ üretimine, sınav oluşturucuya ve quizlere kadar. Yazma alanları önizleme kazanıyor ve web sunucusu da bunları diziyor.',
    'zh-CN': "问题和卡片现在能按书写的样子显示。Markdown和LaTeX公式会在题干、选项、答案和解析中排版呈现，覆盖所有界面，从题库和复习会话到AI生成、试卷生成器和测验。书写字段新增预览，Web服务器也会对其进行排版。",
    'zh-TW': "問題和卡片現在能按書寫的樣子顯示。Markdown和LaTeX公式會在題幹、選項、答案和解析中排版呈現，覆蓋所有介面，從題庫和複習會話到AI生成、試卷生成器和測驗。書寫欄位新增預覽，Web伺服器也會對其進行排版。",
    ko: "이제 질문과 플래시카드가 쓰여진 대로 읽혀집니다. Markdown 및 LaTeX 수식은 은행 및 검토 세션부터 AI 생성, 시험 작성기 및 퀴즈에 이르기까지 모든 표면에서 프롬프트, 옵션, 답변 및 설명에 조판됩니다. 쓰기 필드는 미리보기를 얻고 웹 서버도 이를 조판합니다.",
    ja: "質問とフラッシュカードは、書かれたとおりに読み取られるようになりました。 Markdown と LaTeX の数式は、銀行やレビューセッションから AI 生成、試験ビルダーやクイズに至るまで、プロンプト、オプション、解答、説明のあらゆる面にタイプセットされています。書き込みフィールドはプレビューを取得し、Web サーバーもそれらを植字します。",
  },
  {
    scope: 'ai',
    es: 'Guardar una respuesta del chat en tus notas conserva de dónde vino. La nota recuerda la conversación, el modelo y las fuentes, y desde la propia nota puedes volver a esa conversación y saltar al mensaje exacto. Al exportar las notas, la procedencia viaja con ellas.',
    en: 'Saving a chat answer to your notes keeps where it came from. The note remembers the conversation, the model and the sources, and from the note itself you can reopen that conversation and jump to the exact message. When you export your notes, the provenance travels with them.',
    fr: 'Enregistrer une réponse du chat dans vos notes conserve son origine. La note retient la conversation, le modèle et les sources, et depuis la note vous pouvez rouvrir cette conversation et sauter au message exact. À l’export des notes, la provenance voyage avec elles.',
    de: 'Eine Chat-Antwort in den Notizen zu speichern behält ihre Herkunft. Die Notiz merkt sich das Gespräch, das Modell und die Quellen. Aus der Notiz selbst öffnen Sie das Gespräch wieder und springen zur genauen Nachricht. Beim Export reist die Herkunft mit.',
    pt: 'Guardar uma resposta do chat nas notas conserva a sua origem. A nota recorda a conversa, o modelo e as fontes, e a partir da própria nota podes reabrir essa conversa e saltar para a mensagem exata. Ao exportar as notas, a procedência viaja com elas.',
    'pt-BR': 'Salvar uma resposta do chat nas notas preserva de onde ela veio. A nota lembra a conversa, o modelo e as fontes, e pela própria nota você pode reabrir essa conversa e ir à mensagem exata. Ao exportar as notas, a procedência viaja com elas.',
    it: 'Salvare una risposta della chat nelle note ne conserva l’origine. La nota ricorda la conversazione, il modello e le fonti, e dalla nota stessa puoi riaprire quella conversazione e saltare al messaggio esatto. Esportando le note, la provenienza viaggia con loro.',
    tr: 'Bir sohbet yanıtını notlara kaydetmek nereden geldiğini korur. Not, konuşmayı, modeli ve kaynakları hatırlar. Notun kendisinden o konuşmayı yeniden açıp tam mesaja atlayabilirsiniz. Notları dışa aktardığınızda bu köken bilgisi onlarla birlikte gider.',
    'zh-CN': "将聊天回答保存到笔记时会保留其来源。笔记会记住对话、模型和来源，并且你可以从笔记本身回到该对话并跳转到确切的消息。导出笔记时，来源信息会随之一起导出。",
    'zh-TW': "將聊天回答儲存到筆記時會保留其來源。筆記會記住對話、模型和來源，並且你可以從筆記本身回到該對話並跳轉到確切的訊息。匯出筆記時，來源資訊會隨之一起匯出。",
    ko: "메모에 채팅 답변을 저장하면 해당 답변의 출처가 유지됩니다. 메모는 대화, 모델 및 출처를 기억하며 메모 자체에서 해당 대화를 다시 열고 정확한 메시지로 이동할 수 있습니다. 노트를 내보내면 출처도 함께 이동됩니다.",
    ja: "チャットの回答をメモに保存すると、その回答の出所が維持されます。メモは会話、モデル、ソースを記憶しており、メモ自体からその会話を再度開いて、正確なメッセージにジャンプすることができます。メモをエクスポートすると、出所も一緒に移動します。",
  },
  {
    scope: 'ai',
    es: 'En los diálogos de creación de Deep Research e Immersion, solo Image Atelier se marca como de pago por llamada. Las demás Skills instaladas conservan el límite opcional de SVG Studio y dejan de pedirte un máximo obligatorio para confirmar.',
    en: 'In the Deep Research and Immersion creation dialogs, only Image Atelier is marked as paid per call. Every other installed Skill keeps SVG Studio’s optional ceiling and no longer asks for a mandatory maximum before you can confirm.',
    fr: 'Dans les fenêtres de création de Deep Research et Immersion, seule Image Atelier est marquée comme payante par appel. Les autres Skills installées conservent le plafond facultatif de SVG Studio et ne réclament plus de maximum obligatoire pour confirmer.',
    de: 'In den Erstellungsdialogen von Deep Research und Immersion ist nur Image Atelier als pro Aufruf kostenpflichtig markiert. Jede andere installierte Skill behält die optionale Obergrenze von SVG Studio und verlangt kein Pflichtmaximum mehr zum Bestätigen.',
    pt: 'Nas janelas de criação do Deep Research e do Immersion, só o Image Atelier é marcado como pago por chamada. As restantes Skills instaladas mantêm o limite opcional do SVG Studio e deixam de exigir um máximo obrigatório para confirmar.',
    'pt-BR': 'Nas janelas de criação do Deep Research e do Immersion, apenas o Image Atelier é marcado como pago por chamada. As outras Skills instaladas mantêm o limite opcional do SVG Studio e não exigem mais um máximo obrigatório para confirmar.',
    it: 'Nelle finestre di creazione di Deep Research e Immersion, solo Image Atelier è contrassegnata come a pagamento per chiamata. Le altre Skill installate mantengono il limite opzionale di SVG Studio e non richiedono più un massimo obbligatorio per confermare.',
    tr: 'Deep Research ve Immersion oluşturma pencerelerinde yalnızca Image Atelier çağrı başına ücretli olarak işaretleniyor. Kurulu diğer Skill’ler SVG Studio’nun isteğe bağlı sınırını koruyor ve onaylamadan önce zorunlu bir üst sınır istemiyor.',
    'zh-CN': "在Deep Research和Immersion的创建对话框中，只有Image Atelier被标记为按调用付费。其他已安装的Skill保留SVG Studio的可选上限，不再要求你填写必填的最大值才能确认。",
    'zh-TW': "在Deep Research和Immersion的建立對話方塊中，只有Image Atelier被標記為按呼叫付費。其他已安裝的Skill保留SVG Studio的可選上限，不再要求你填寫必填的最大值才能確認。",
    ko: "Deep Research 및 Immersion 생성 대화 상자에서는 Image Atelier만 통화당 유료로 표시됩니다. 설치된 다른 모든 스킬은 SVG Studio의 선택적 한도를 유지하며 더 이상 확인하기 전에 필수 최대값을 묻지 않습니다.",
    ja: "Deep Research および Immersion 作成ダイアログでは、Image Atelier のみが通話ごとに支払い済みとしてマークされています。インストールされている他のすべてのスキルは、SVG Studio のオプションの上限を維持し、確認する前に必須の最大値を要求することはなくなりました。",
  },
  {
    scope: 'languages',
    es: 'Siete idiomas nuevos para generar contenido. Chino simplificado y tradicional, vietnamita, japonés, ruso, ucraniano y coreano se suman a los selectores de idioma de los prompts, que ya ofrecen quince. La interfaz mantiene sus ocho idiomas.',
    en: 'Seven new languages for generated content. Simplified and traditional Chinese, Vietnamese, Japanese, Russian, Ukrainian and Korean join the prompt language pickers, which now offer fifteen. The interface keeps its eight languages.',
    fr: 'Sept nouvelles langues pour le contenu généré. Le chinois simplifié et traditionnel, le vietnamien, le japonais, le russe, l’ukrainien et le coréen rejoignent les sélecteurs de langue des prompts, qui en proposent désormais quinze. L’interface conserve ses huit langues.',
    de: 'Sieben neue Sprachen für erzeugte Inhalte. Vereinfachtes und traditionelles Chinesisch, Vietnamesisch, Japanisch, Russisch, Ukrainisch und Koreanisch kommen zu den Sprachauswahlen der Prompts, die nun fünfzehn bieten. Die Oberfläche behält ihre acht Sprachen.',
    pt: 'Sete idiomas novos para o conteúdo gerado. Chinês simplificado e tradicional, vietnamita, japonês, russo, ucraniano e coreano juntam-se aos seletores de idioma dos prompts, que passam a oferecer quinze. A interface mantém os seus oito idiomas.',
    'pt-BR': 'Sete idiomas novos para o conteúdo gerado. Chinês simplificado e tradicional, vietnamita, japonês, russo, ucraniano e coreano entram nos seletores de idioma dos prompts, que agora oferecem quinze. A interface mantém seus oito idiomas.',
    it: 'Sette nuove lingue per i contenuti generati. Cinese semplificato e tradizionale, vietnamita, giapponese, russo, ucraino e coreano entrano nei selettori di lingua dei prompt, che ora ne offrono quindici. L’interfaccia mantiene le sue otto lingue.',
    tr: 'Üretilen içerik için yedi yeni dil. Basitleştirilmiş ve geleneksel Çince, Vietnamca, Japonca, Rusça, Ukraynaca ve Korece istem dili seçicilerine eklendi ve artık on beş dil sunuluyor. Arayüz kendi sekiz dilini koruyor.',
    'zh-CN': "新增七种内容生成语言。简体中文、繁体中文、越南语、日语、俄语、乌克兰语和韩语加入提示词语言选择器，该选择器现已提供十五种语言。界面仍保持八种语言。",
    'zh-TW': "新增七種內容生成語言。簡體中文、繁體中文、越南語、日語、俄語、烏克蘭語和韓語加入提示詞語言選擇器，該選擇器現已提供十五種語言。介面仍保持八種語言。",
    ko: "생성된 콘텐츠를 위한 7개의 새로운 언어. 간체 및 번체 중국어, 베트남어, 일본어, 러시아어, 우크라이나어 및 한국어가 프롬프트 언어 선택기에 합류하여 현재 15개를 제공합니다. 인터페이스는 8개 언어를 유지합니다.",
    ja: "生成されたコンテンツ用に7つの新しい言語。簡体字および繁体字中国語、ベトナム語、日本語、ロシア語、ウクライナ語、韓国語がプロンプト言語選択ツールに加わり、現在15言語が提供されています。インターフェイスは8つの言語を維持します。",
  },
  {
    scope: 'marketplace',
    es: 'El Marketplace muestra un solo catálogo. Skills, plugins, paquetes firmados y plugins pendientes de revisión comparten una lista y una tarjeta cada uno, con la misma identidad visual, los mismos detalles plegables y un único diálogo de permisos antes de instalar o actualizar.',
    en: 'The Marketplace shows one single catalog. Skills, plugins, signed packages and plugins awaiting review share one list with one card each, the same visual identity, the same collapsible details and one permissions dialog before installing or updating.',
    fr: 'Le Marketplace présente un catalogue unique. Skills, plugins, paquets signés et plugins en attente de révision partagent une seule liste, une fiche chacun, la même identité visuelle, les mêmes détails repliables et une seule fenêtre de permissions avant d’installer ou de mettre à jour.',
    de: 'Der Marketplace zeigt einen einzigen Katalog. Skills, Plugins, signierte Pakete und Plugins, die auf Prüfung warten, teilen sich eine Liste mit je einer Karte, derselben visuellen Identität, denselben einklappbaren Details und einem einzigen Berechtigungsdialog vor Installation oder Update.',
    pt: 'O Marketplace mostra um único catálogo. Skills, plugins, pacotes assinados e plugins à espera de revisão partilham uma lista, com um cartão cada, a mesma identidade visual, os mesmos detalhes recolhíveis e uma única caixa de diálogo de permissões antes de instalar ou atualizar.',
    'pt-BR': 'O Marketplace mostra um único catálogo. Skills, plugins, pacotes assinados e plugins aguardando revisão compartilham uma lista, com um cartão cada, a mesma identidade visual, os mesmos detalhes recolhíveis e uma única caixa de diálogo de permissões antes de instalar ou atualizar.',
    it: 'Il Marketplace mostra un solo catalogo. Skill, plugin, pacchetti firmati e plugin in attesa di revisione condividono un unico elenco con una scheda ciascuno, la stessa identità visiva, gli stessi dettagli richiudibili e un’unica finestra dei permessi prima di installare o aggiornare.',
    tr: 'Marketplace tek bir katalog gösteriyor. Skill’ler, eklentiler, imzalı paketler ve inceleme bekleyen eklentiler tek listede toplanıyor. Her biri kendi kartında, aynı görsel kimlikle, aynı daraltılabilir ayrıntılarla ve kurmadan ya da güncellemeden önce tek bir izin penceresiyle gösteriliyor.',
    'zh-CN': "Marketplace只显示一个统一目录。Skills、插件、已签名包和待审核插件共用一个列表，各自一张卡片，具有相同的视觉标识、相同的可折叠详情，以及安装或更新前唯一的权限对话框。",
    'zh-TW': "Marketplace只顯示一個統一目錄。Skills、外掛、已簽名包和待稽核外掛共用一個列表，各自一張卡片，具有相同的視覺標識、相同的可摺疊詳情，以及安裝或更新前唯一的權限對話方塊。",
    ko: "Marketplace에는 하나의 단일 카탈로그가 표시됩니다. 검토 대기 중인 기술, 플러그인, 서명된 패키지 및 플러그인은 설치 또는 업데이트 전에 각각 하나의 카드, 동일한 시각적 ID, 동일한 축소 가능한 세부 정보 및 하나의 권한 대화 상자와 하나의 목록을 공유합니다.",
    ja: "マーケットプレイスには1つのカタログが表示されます。スキル、プラグイン、署名済みパッケージ、およびレビュー待ちのプラグインは、インストールまたは更新する前に、それぞれ1枚のカードを含む1つのリスト、同じビジュアルアイデンティティ、同じ折りたたみ可能な詳細、および1つの権限ダイアログを共有します。",
  },
  {
    scope: 'plugin',
    es: 'Los paquetes firmados versión 2 usan su propio canal de ejecución. Sus herramientas dejan de anunciarse por el mecanismo genérico anterior y se ejecutan por la vía de capacidades de confianza que declaran, así que el chat deja de buscar una herramienta que el paquete no expone.',
    en: 'Signed version 2 packages use their own execution channel. Their tools are no longer advertised through the previous generic mechanism and run through the trusted capability path they declare, so a chat no longer reaches for a tool the package does not expose.',
    fr: 'Les paquets signés version 2 utilisent leur propre canal d’exécution. Leurs outils ne passent plus par l’ancien mécanisme générique et s’exécutent par la voie des capacités de confiance qu’ils déclarent, donc le chat ne tombe plus sur un outil que le paquet n’expose pas.',
    de: 'Signierte Pakete der Version 2 nutzen ihren eigenen Ausführungskanal. Ihre Werkzeuge werden nicht mehr über den bisherigen generischen Mechanismus angeboten und laufen über den vertrauenswürdigen Capability-Pfad, den sie deklarieren. Der Chat greift nicht mehr nach einem Werkzeug, das das Paket nicht anbietet.',
    pt: 'Os pacotes assinados versão 2 usam o seu próprio canal de execução. As suas ferramentas deixam de ser anunciadas pelo mecanismo genérico anterior e executam-se pela via de capacidades de confiança que declaram, pelo que o chat deixa de procurar uma ferramenta que o pacote não expõe.',
    'pt-BR': 'Os pacotes assinados versão 2 usam o próprio canal de execução. Suas ferramentas não são mais anunciadas pelo mecanismo genérico anterior e rodam pela via de capacidades confiáveis que declaram, então o chat não procura mais uma ferramenta que o pacote não expõe.',
    it: 'I pacchetti firmati versione 2 usano il proprio canale di esecuzione. I loro strumenti non passano più dal precedente meccanismo generico e vengono eseguiti tramite il percorso di capacità fidate che dichiarano, così la chat non cerca più uno strumento che il pacchetto non espone.',
    tr: 'İmzalı sürüm 2 paketleri kendi yürütme kanalını kullanıyor. Araçları artık önceki genel mekanizma üzerinden duyurulmuyor ve bildirdikleri güvenilir yetenek yolundan çalışıyor. Böylece sohbet, paketin sunmadığı bir aracı aramıyor.',
    'zh-CN': "版本2的已签名包使用自己的执行通道。其工具不再通过先前的通用机制公布，而是经由它们声明的受信能力路径执行，因此聊天不再去寻找包未公开的工具。",
    'zh-TW': "版本2的已簽名包使用自己的執行通道。其工具不再通過先前的通用機制公佈，而是經由它們宣告的受信能力路徑執行，因此聊天不再去尋找包未公開的工具。",
    ko: "서명된 버전 2 패키지는 자체 실행 채널을 사용합니다. 해당 도구는 더 이상 이전 일반 메커니즘을 통해 광고되지 않으며 선언한 신뢰할 수 있는 기능 경로를 통해 실행되므로 패키지가 노출하지 않는 도구에 대한 채팅이 더 이상 도달하지 않습니다.",
    ja: "署名付きバージョン2パッケージは独自の実行チャネルを使用します。彼らのツールは、以前の汎用メカニズムを通じてアドバタイズされなくなり、宣言された信頼できる機能パスを通じて実行されるため、パッケージが公開していないツールにチャットが到達することはなくなりました。",
  },
  {
    scope: 'browser',
    es: 'El navegador respeta las páginas que no declaran modo oscuro. Su fondo sigue los colores del propio documento en lugar de imponer el tema de la aplicación, así que una página 401 o sin estilos se lee sin seleccionar el texto. Las webs con autenticación básica HTTP ya pueden iniciar sesión desde una barra del navegador, que no guarda tus credenciales.',
    en: 'The browser respects pages that do not declare a dark scheme. Their surface follows the document’s own colours instead of imposing the app theme, so a 401 page or an unstyled document is readable without selecting its text. Sites using HTTP Basic authentication can now sign in through a browser bar that stores none of your credentials.',
    fr: 'Le navigateur respecte les pages qui ne déclarent pas de thème sombre. Leur fond suit les couleurs du document au lieu d’imposer le thème de l’application, donc une page 401 ou sans styles se lit sans sélectionner le texte. Les sites en authentification HTTP basique peuvent se connecter via une barre du navigateur, qui ne conserve aucun identifiant.',
    de: 'Der Browser respektiert Seiten, die kein dunkles Schema angeben. Ihre Fläche folgt den Farben des Dokuments, statt das App-Design aufzuzwingen, sodass eine 401-Seite oder ein ungestyltes Dokument ohne Textauswahl lesbar ist. Seiten mit HTTP-Basisauthentifizierung melden sich nun über eine Browserleiste an, die keine Zugangsdaten speichert.',
    pt: 'O navegador respeita as páginas que não declaram modo escuro. O fundo segue as cores do próprio documento em vez de impor o tema da aplicação, pelo que uma página 401 ou sem estilos se lê sem selecionar o texto. Os sites com autenticação básica HTTP já podem iniciar sessão numa barra do navegador, que não guarda as tuas credenciais.',
    'pt-BR': 'O navegador respeita as páginas que não declaram modo escuro. O fundo segue as cores do próprio documento em vez de impor o tema do aplicativo, então uma página 401 ou sem estilos é legível sem selecionar o texto. Sites com autenticação básica HTTP agora entram por uma barra do navegador, que não guarda suas credenciais.',
    it: 'Il browser rispetta le pagine che non dichiarano un tema scuro. La superficie segue i colori del documento invece di imporre il tema dell’app, quindi una pagina 401 o senza stili si legge senza selezionare il testo. I siti con autenticazione HTTP di base ora accedono da una barra del browser che non conserva le credenziali.',
    tr: 'Tarayıcı, koyu şema bildirmeyen sayfalara saygı gösteriyor. Yüzey, uygulama temasını dayatmak yerine belgenin kendi renklerini izliyor. Böylece 401 sayfası veya biçimsiz bir belge, metin seçmeden okunabiliyor. HTTP Basic kimlik doğrulaması kullanan sitelere artık tarayıcı çubuğundan giriş yapılabiliyor ve kimlik bilgileriniz saklanmıyor.',
    'zh-CN': "浏览器会尊重未声明深色模式的页面。其背景遵循文档自身的颜色，而不是强加应用主题，因此401页面或无样式页面无需选中文字即可阅读。使用HTTP基本认证的网站现在可以通过浏览器地址栏登录，该栏不会保存你的凭据。",
    'zh-TW': "瀏覽器會尊重未宣告深色模式的頁面。其背景遵循文件自身的顏色，而不是強加應用主題，因此401頁面或無樣式頁面無需選中文字即可閱讀。使用HTTP基本認證的網站現在可以通過瀏覽器位址列登入，該欄不會儲存你的憑據。",
    ko: "브라우저는 다크 스킴을 선언하지 않은 페이지를 존중합니다. 표면은 앱 테마를 강요하는 대신 문서 고유의 색상을 따르므로 401 페이지나 스타일이 지정되지 않은 문서는 텍스트를 선택하지 않고도 읽을 수 있습니다. HTTP 기본 인증을 사용하는 사이트는 이제 사용자의 자격 증명이 전혀 저장되지 않은 브라우저 표시줄을 통해 로그인할 수 있습니다.",
    ja: "ブラウザーは、ダークスキームを宣言していないページを尊重します。表面はアプリのテーマを押し付けるのではなく、ドキュメント自体の色に従っているため、401ページやスタイルのないドキュメントは、テキストを選択しなくても読むことができます。 HTTP 基本認証を使用するサイトは、資格情報を保存しないブラウザバーからサインインできるようになりました。",
  },
  {
    scope: 'browser',
    es: 'La vista nativa del navegador se alinea con el zoom de la interfaz. Al ampliar o reducir con el zoom del renderizador, la página y su marco dejan de quedar desalineados y el contenido se mantiene en su sitio.',
    en: 'The browser’s native view aligns with the interface zoom. When you zoom in or out with the renderer zoom, the page and its frame stop drifting apart and the content stays in place.',
    fr: 'La vue native du navigateur s’aligne sur le zoom de l’interface. En zoomant avec celui du moteur de rendu, la page et son cadre ne se décalent plus et le contenu reste en place.',
    de: 'Die native Ansicht des Browsers richtet sich am Zoom der Oberfläche aus. Beim Vergrößern oder Verkleinern über den Renderer-Zoom driften Seite und Rahmen nicht mehr auseinander und der Inhalt bleibt an seinem Platz.',
    pt: 'A vista nativa do navegador alinha-se com o zoom da interface. Ao ampliar ou reduzir com o zoom do renderizador, a página e o seu enquadramento deixam de ficar desalinhados e o conteúdo mantém-se no sítio.',
    'pt-BR': 'A visualização nativa do navegador se alinha ao zoom da interface. Ao ampliar ou reduzir com o zoom do renderizador, a página e sua moldura não ficam mais desalinhadas e o conteúdo permanece no lugar.',
    it: 'La vista nativa del browser si allinea allo zoom dell’interfaccia. Ingrandendo o riducendo con lo zoom del renderer, la pagina e la sua cornice non restano più disallineate e il contenuto rimane al suo posto.',
    tr: 'Tarayıcının yerel görünümü arayüz yakınlaştırmasıyla hizalanıyor. Görüntüleyici yakınlaştırmasıyla büyütüp küçülttüğünüzde sayfa ve çerçevesi artık kaymıyor ve içerik yerinde kalıyor.',
    'zh-CN': "浏览器的原生视图与界面缩放对齐。使用渲染器缩放进行放大或缩小时，页面与其边框不再错位，内容保持原位。",
    'zh-TW': "瀏覽器的原生檢視與介面縮放對齊。使用渲染器縮放進行放大或縮小時，頁面與其邊框不再錯位，內容保持原位。",
    ko: "브라우저의 기본 보기는 인터페이스 확대/축소에 맞춰 정렬됩니다. 렌더러 확대/축소를 사용하여 확대하거나 축소하면 페이지와 해당 프레임이 분리되는 것을 멈추고 콘텐츠가 제자리에 유지됩니다.",
    ja: "ブラウザのネイティブビューはインターフェイスのズームに合わせて調整されます。レンダラーズームを使用してズームインまたはズームアウトすると、ページとそのフレームが離れてしまうことがなくなり、コンテンツは所定の位置に留まります。",
  },
  {
    scope: 'library',
    es: 'El análisis de la biblioteca se recupera mejor de los fallos pasajeros. Si Zotero no responde, el trabajo vuelve a la cola en lugar de darse por «sin texto», el filtro «Incompleto» comprueba los cinco pasos y el estado semántico coincide con el de cada fila, y una fusión interrumpida se reanuda solo por las ideas que faltan.',
    en: 'Library analysis recovers better from transient failures. When Zotero is unreachable, the work returns to the queue instead of being marked as having no text, the Incomplete filter checks all five steps and the semantic state agrees with each row, and an interrupted fusion resumes only the ideas that are missing.',
    fr: 'L’analyse de la bibliothèque se remet mieux des échecs passagers. Si Zotero ne répond pas, le travail retourne dans la file au lieu d’être marqué sans texte, le filtre Incomplet vérifie les cinq étapes et l’état sémantique correspond à chaque ligne, et une fusion interrompue reprend uniquement les idées manquantes.',
    de: 'Die Bibliotheksanalyse erholt sich besser von vorübergehenden Fehlern. Ist Zotero nicht erreichbar, kehrt die Arbeit in die Warteschlange zurück, statt als ohne Text markiert zu werden. Der Filter Unvollständig prüft alle fünf Schritte und der semantische Status stimmt mit der jeweiligen Zeile überein. Eine unterbrochene Fusion wird nur für die fehlenden Ideen fortgesetzt.',
    pt: 'A análise da biblioteca recupera melhor de falhas passageiras. Se o Zotero não responder, o trabalho volta à fila em vez de ficar marcado como sem texto, o filtro «Incompleto» verifica os cinco passos e o estado semântico coincide com o de cada linha, e uma fusão interrompida retoma apenas as ideias que faltam.',
    'pt-BR': 'A análise da biblioteca se recupera melhor de falhas passageiras. Se o Zotero não responde, o trabalho volta à fila em vez de ser marcado como sem texto, o filtro «Incompleto» verifica as cinco etapas e o estado semântico bate com o de cada linha, e uma fusão interrompida retoma apenas as ideias que faltam.',
    it: 'L’analisi della biblioteca si riprende meglio dagli errori temporanei. Se Zotero non risponde, il lavoro torna in coda invece di essere segnato come senza testo, il filtro Incompleto controlla tutti e cinque i passaggi e lo stato semantico coincide con quello di ogni riga, e una fusione interrotta riprende solo le idee mancanti.',
    tr: 'Kitaplık analizi geçici hatalardan daha iyi toparlanıyor. Zotero yanıt vermezse çalışma metinsiz olarak işaretlenmek yerine kuyruğa dönüyor. Eksik filtresi beş adımın tamamını denetliyor ve anlamsal durum her satırla uyuşuyor. Yarım kalan bir birleştirme yalnızca eksik fikirlerden devam ediyor.',
    'zh-CN': "文献库分析能更好地从暂时性故障中恢复。如果Zotero无响应，任务会回到队列，而不是被判为「没有文本」，「不完整」筛选会检查全部五个步骤，语义状态与每一行一致，被中断的融合只针对缺失的观点继续执行。",
    'zh-TW': "文獻庫分析能更好地從暫時性故障中恢復。如果Zotero無響應，任務會回到佇列，而不是被判為「沒有文本」，「不完整」篩選會檢查全部五個步驟，語義狀態與每一行一致，被中斷的融合只針對缺失的觀點繼續執行。",
    ko: "라이브러리 분석은 일시적인 오류로부터 더 잘 복구됩니다. Zotero에 연결할 수 없는 경우 작업은 텍스트가 없는 것으로 표시되는 대신 대기열로 돌아가고, 불완전 필터는 다섯 단계를 모두 확인하고 의미 상태가 각 행과 일치하며 중단된 융합은 누락된 아이디어만 재개합니다.",
    ja: "ライブラリ分析は、一時的な障害からより適切に回復します。 Zotero に到達できない場合、作業はテキストなしとしてマークされる代わりにキューに戻り、Incomplete フィルターが5つのステップすべてをチェックし、セマンティック状態が各行と一致し、中断されたフュージョンが不足しているアイデアのみを再開します。",
  },
];
