import type { PromptLanguage } from './types';

export interface StudyDiarizationPromptPack {
  expected(count: number): string;
  inferSpeakers: string;
  analyze: string;
  json: string;
  turns: string;
  noNames: string;
  transcript: string;
}

const schema = (fragment: string) => `{"segments":[{"startSeconds":0.0,"endSeconds":1.2,"speaker":"speaker_1","text":"${fragment}","confidence":0.95}]}`;

const PACKS: Record<PromptLanguage, StudyDiarizationPromptPack> = {
  es: { expected: (count) => `Se esperan aproximadamente ${count} hablantes.`, inferSpeakers: 'Determina el número de hablantes por sus voces; no lo deduzcas por el contenido.', analyze: 'Analiza acústicamente este audio y realiza diarización de hablantes.', json: `Devuelve exclusivamente JSON con esta forma:\n\n${schema('fragmento oído')}`, turns: 'Crea un segmento por turno de voz. Usa el mismo identificador para la misma voz y otro cuando cambie la voz.', noNames: 'No inventes nombres propios para los hablantes. Los tiempos deben estar en segundos y no solaparse.', transcript: 'La transcripción existente se aporta solo para facilitar la alineación; la aplicación preservará literalmente su texto:' },
  en: { expected: (count) => `Approximately ${count} speakers are expected.`, inferSpeakers: 'Determine the number of speakers from their voices; do not infer it from the content.', analyze: 'Analyze this audio acoustically and perform speaker diarization.', json: `Return exclusively JSON in this form:\n\n${schema('heard fragment')}`, turns: 'Create one segment per speaking turn. Use the same identifier for the same voice and a different one when the voice changes.', noNames: 'Do not invent proper names for speakers. Times must be in seconds and must not overlap.', transcript: 'The existing transcript is provided only to assist alignment; the application will preserve its text verbatim:' },
  fr: { expected: (count) => `Environ ${count} locuteurs sont attendus.`, inferSpeakers: 'Détermine le nombre de locuteurs à partir de leurs voix ; ne le déduis pas du contenu.', analyze: 'Analyse acoustiquement cet audio et effectue une diarisation des locuteurs.', json: `Renvoie exclusivement du JSON sous cette forme :\n\n${schema('fragment entendu')}`, turns: 'Crée un segment par tour de parole. Utilise le même identifiant pour une même voix et un autre lorsque la voix change.', noNames: 'N’invente pas de noms propres pour les locuteurs. Les temps doivent être exprimés en secondes et ne pas se chevaucher.', transcript: 'La transcription existante est fournie uniquement pour faciliter l’alignement ; l’application en conservera littéralement le texte :' },
  de: { expected: (count) => `Es werden ungefähr ${count} Sprecher erwartet.`, inferSpeakers: 'Bestimme die Anzahl der Sprecher anhand ihrer Stimmen; leite sie nicht aus dem Inhalt ab.', analyze: 'Analysiere dieses Audio akustisch und führe eine Sprecherdiarisierung durch.', json: `Gib ausschließlich JSON in dieser Form zurück:\n\n${schema('gehörter Ausschnitt')}`, turns: 'Erstelle ein Segment pro Sprecherwechsel. Verwende für dieselbe Stimme dieselbe Kennung und bei einem Stimmenwechsel eine andere.', noNames: 'Erfinde keine Eigennamen für Sprecher. Zeiten müssen in Sekunden angegeben werden und dürfen sich nicht überschneiden.', transcript: 'Das vorhandene Transkript dient nur zur Unterstützung der Ausrichtung; die Anwendung bewahrt seinen Text wortgetreu:' },
  pt: { expected: (count) => `Esperam-se aproximadamente ${count} intervenientes.`, inferSpeakers: 'Determina o número de intervenientes pelas vozes; não o deduzas pelo conteúdo.', analyze: 'Analisa acusticamente este áudio e realiza a diarização dos intervenientes.', json: `Devolve exclusivamente JSON com esta forma:\n\n${schema('fragmento ouvido')}`, turns: 'Cria um segmento por turno de fala. Usa o mesmo identificador para a mesma voz e outro quando a voz mudar.', noNames: 'Não inventes nomes próprios para os intervenientes. Os tempos devem estar em segundos e não podem sobrepor-se.', transcript: 'A transcrição existente é fornecida apenas para facilitar o alinhamento; a aplicação preservará literalmente o seu texto:' },
  'pt-BR': { expected: (count) => `São esperados aproximadamente ${count} participantes.`, inferSpeakers: 'Determine o número de participantes por suas vozes; não o deduza pelo conteúdo.', analyze: 'Analise acusticamente este áudio e faça a diarização dos participantes.', json: `Retorne exclusivamente JSON neste formato:\n\n${schema('fragmento ouvido')}`, turns: 'Crie um segmento por turno de fala. Use o mesmo identificador para a mesma voz e outro quando a voz mudar.', noNames: 'Não invente nomes próprios para os participantes. Os tempos devem estar em segundos e não podem se sobrepor.', transcript: 'A transcrição existente é fornecida somente para facilitar o alinhamento; o aplicativo preservará literalmente seu texto:' },
  it: { expected: (count) => `Sono previsti circa ${count} parlanti.`, inferSpeakers: 'Determina il numero di parlanti dalle loro voci; non dedurlo dal contenuto.', analyze: 'Analizza acusticamente questo audio ed esegui la diarizzazione dei parlanti.', json: `Restituisci esclusivamente JSON in questa forma:\n\n${schema('frammento udito')}`, turns: 'Crea un segmento per ogni turno di parola. Usa lo stesso identificatore per la stessa voce e uno diverso quando la voce cambia.', noNames: 'Non inventare nomi propri per i parlanti. I tempi devono essere espressi in secondi e non sovrapporsi.', transcript: 'La trascrizione esistente è fornita solo per facilitare l’allineamento; l’applicazione ne conserverà letteralmente il testo:' },
  tr: { expected: (count) => `Yaklaşık ${count} konuşmacı bekleniyor.`, inferSpeakers: 'Konuşmacı sayısını seslerinden belirle; içerikten çıkarma.', analyze: 'Bu sesi akustik olarak incele ve konuşmacı diarizasyonu yap.', json: `Yalnızca şu biçimde JSON döndür:\n\n${schema('duyulan parça')}`, turns: 'Her konuşma sırası için bir segment oluştur. Aynı ses için aynı kimliği, ses değiştiğinde farklı bir kimliği kullan.', noNames: 'Konuşmacılar için özel ad uydurma. Zamanlar saniye cinsinden olmalı ve çakışmamalıdır.', transcript: 'Mevcut transkript yalnızca hizalamayı kolaylaştırmak için sağlanmıştır; uygulama metni birebir koruyacaktır:' },
  'zh-Hans': { expected: (count) => `预计大约有 ${count} 位说话人。`, inferSpeakers: '根据声音判断说话人数量；不要根据内容推断。', analyze: '对这段音频进行声学分析并执行说话人分离（diarization）。', json: `仅返回如下形式的 JSON：\n\n${schema('听到的片段')}`, turns: '每个发言轮次创建一个片段。同一声音使用相同的标识符，声音变化时使用不同的标识符。', noNames: '不要为说话人编造姓名。时间必须以秒为单位，且不得重叠。', transcript: '提供的现有转录文本仅用于协助对齐；应用将逐字保留其文本：' },
  'zh-Hant': { expected: (count) => `預計約有 ${count} 位說話者。`, inferSpeakers: '根據聲音判斷說話者數量；不要根據內容推斷。', analyze: '對這段音訊進行聲學分析並執行說話者分離（diarization）。', json: `僅回傳如下形式的 JSON：\n\n${schema('聽到的片段')}`, turns: '每個發言輪次建立一個片段。同一聲音使用相同的識別碼，聲音改變時使用不同的識別碼。', noNames: '不要為說話者編造姓名。時間必須以秒為單位，且不得重疊。', transcript: '提供的現有轉錄文字僅用於協助對齊；應用程式將逐字保留其文字：' },
  vi: { expected: (count) => `Dự kiến có khoảng ${count} người nói.`, inferSpeakers: 'Xác định số lượng người nói dựa trên giọng nói của họ; không suy đoán từ nội dung.', analyze: 'Phân tích âm thanh này bằng phương pháp âm học và thực hiện phân tách người nói (diarization).', json: `Chỉ trả về JSON theo dạng sau:\n\n${schema('đoạn nghe được')}`, turns: 'Tạo một đoạn cho mỗi lượt nói. Dùng cùng một mã định danh cho cùng một giọng nói và mã khác khi giọng nói thay đổi.', noNames: 'Không bịa đặt tên riêng cho người nói. Thời gian phải tính bằng giây và không được chồng lấn.', transcript: 'Bản ghi chép hiện có chỉ được cung cấp để hỗ trợ căn chỉnh; ứng dụng sẽ giữ nguyên văn bản của bản ghi này:' },
  ja: { expected: (count) => `話者は約 ${count} 名と想定されます。`, inferSpeakers: '声に基づいて話者数を判断してください。内容から推測しないでください。', analyze: 'この音声を音響的に分析し、話者ダイアリゼーションを実行してください。', json: `次の形式の JSON のみを返してください：\n\n${schema('聞き取った断片')}`, turns: '発話ターンごとに 1 つのセグメントを作成してください。同じ声には同じ識別子を使用し、声が変わったら別の識別子を使用してください。', noNames: '話者に固有名を捏造しないでください。時刻は秒単位で指定し、重複させないでください。', transcript: '既存の文字起こしは位置合わせを支援するためにのみ提供されます。アプリケーションはそのテキストをそのまま保持します：' },
  ru: { expected: (count) => `Ожидается примерно ${count} говорящих.`, inferSpeakers: 'Определите число говорящих по их голосам; не выводите его из содержания.', analyze: 'Проанализируйте это аудио акустически и выполните диаризацию говорящих.', json: `Верните ИСКЛЮЧИТЕЛЬНО JSON следующей формы:\n\n${schema('услышанный фрагмент')}`, turns: 'Создайте по одному сегменту на каждую реплику. Используйте один и тот же идентификатор для одного голоса и другой — когда голос меняется.', noNames: 'Не выдумывайте имена собственные для говорящих. Время должно быть указано в секундах и не пересекаться.', transcript: 'Существующая транскрипция предоставлена только для облегчения выравнивания; приложение сохранит её текст дословно:' },
  uk: { expected: (count) => `Очікується приблизно ${count} мовців.`, inferSpeakers: 'Визначте кількість мовців за їхніми голосами; не виводьте її зі змісту.', analyze: 'Проаналізуйте це аудіо акустично та виконайте діаризацію мовців.', json: `Поверніть ВИКЛЮЧНО JSON такої форми:\n\n${schema('почутий фрагмент')}`, turns: 'Створіть по одному сегменту на кожну репліку. Використовуйте той самий ідентифікатор для одного голосу та інший — коли голос змінюється.', noNames: 'Не вигадуйте власні імена для мовців. Час має бути вказано в секундах і не перекриватися.', transcript: 'Наявна транскрипція надана лише для полегшення вирівнювання; застосунок збереже її текст дослівно:' },
  ko: { expected: (count) => `약 ${count}명의 화자가 예상됩니다.`, inferSpeakers: '목소리로 화자 수를 판단하십시오. 내용에서 추론하지 마십시오.', analyze: '이 오디오를 음향적으로 분석하고 화자 분리(diarization)를 수행하십시오.', json: `다음 형식의 JSON만 반환하십시오:\n\n${schema('들린 단편')}`, turns: '발화 순서마다 하나의 세그먼트를 만드십시오. 같은 목소리에는 같은 식별자를 사용하고, 목소리가 바뀌면 다른 식별자를 사용하십시오.', noNames: '화자에게 고유 이름을 지어내지 마십시오. 시간은 초 단위여야 하며 겹치지 않아야 합니다.', transcript: '기존 전사는 정렬을 돕기 위해서만 제공됩니다. 애플리케이션은 그 텍스트를 그대로 보존합니다:' },
};

export function studyDiarizationPromptPack(language: PromptLanguage = 'es'): StudyDiarizationPromptPack {
  return PACKS[language] ?? PACKS.es;
}
