import type { PromptLanguage } from './types';

export interface StudyDiarizationPromptPack {
  expected(count: number): string;
  inferSpeakers: string;
  analyze: string;
  json: string;
  turns: string;
  noNames: string;
  transcript: string;
}

const schema = (fragment: string) => `{"segments":[{"startSeconds":0.0,"endSeconds":1.2,"speaker":"speaker_1","text":"${fragment}","confidence":0.95}]}`;

const PACKS: Record<PromptLanguage, StudyDiarizationPromptPack> = {
  es: { expected: (count) => `Se esperan aproximadamente ${count} hablantes.`, inferSpeakers: 'Determina el número de hablantes por sus voces; no lo deduzcas por el contenido.', analyze: 'Analiza acústicamente este audio y realiza diarización de hablantes.', json: `Devuelve exclusivamente JSON con esta forma:\n\n${schema('fragmento oído')}`, turns: 'Crea un segmento por turno de voz. Usa el mismo identificador para la misma voz y otro cuando cambie la voz.', noNames: 'No inventes nombres propios para los hablantes. Los tiempos deben estar en segundos y no solaparse.', transcript: 'La transcripción existente se aporta solo para facilitar la alineación; la aplicación preservará literalmente su texto:' },
  en: { expected: (count) => `Approximately ${count} speakers are expected.`, inferSpeakers: 'Determine the number of speakers from their voices; do not infer it from the content.', analyze: 'Analyze this audio acoustically and perform speaker diarization.', json: `Return exclusively JSON in this form:\n\n${schema('heard fragment')}`, turns: 'Create one segment per speaking turn. Use the same identifier for the same voice and a different one when the voice changes.', noNames: 'Do not invent proper names for speakers. Times must be in seconds and must not overlap.', transcript: 'The existing transcript is provided only to assist alignment; the application will preserve its text verbatim:' },
  fr: { expected: (count) => `Environ ${count} locuteurs sont attendus.`, inferSpeakers: 'Détermine le nombre de locuteurs à partir de leurs voix ; ne le déduis pas du contenu.', analyze: 'Analyse acoustiquement cet audio et effectue une diarisation des locuteurs.', json: `Renvoie exclusivement du JSON sous cette forme :\n\n${schema('fragment entendu')}`, turns: 'Crée un segment par tour de parole. Utilise le même identifiant pour une même voix et un autre lorsque la voix change.', noNames: 'N’invente pas de noms propres pour les locuteurs. Les temps doivent être exprimés en secondes et ne pas se chevaucher.', transcript: 'La transcription existante est fournie uniquement pour faciliter l’alignement ; l’application en conservera littéralement le texte :' },
  de: { expected: (count) => `Es werden ungefähr ${count} Sprecher erwartet.`, inferSpeakers: 'Bestimme die Anzahl der Sprecher anhand ihrer Stimmen; leite sie nicht aus dem Inhalt ab.', analyze: 'Analysiere dieses Audio akustisch und führe eine Sprecherdiarisierung durch.', json: `Gib ausschließlich JSON in dieser Form zurück:\n\n${schema('gehörter Ausschnitt')}`, turns: 'Erstelle ein Segment pro Sprecherwechsel. Verwende für dieselbe Stimme dieselbe Kennung und bei einem Stimmenwechsel eine andere.', noNames: 'Erfinde keine Eigennamen für Sprecher. Zeiten müssen in Sekunden angegeben werden und dürfen sich nicht überschneiden.', transcript: 'Das vorhandene Transkript dient nur zur Unterstützung der Ausrichtung; die Anwendung bewahrt seinen Text wortgetreu:' },
  pt: { expected: (count) => `Esperam-se aproximadamente ${count} intervenientes.`, inferSpeakers: 'Determina o número de intervenientes pelas vozes; não o deduzas pelo conteúdo.', analyze: 'Analisa acusticamente este áudio e realiza a diarização dos intervenientes.', json: `Devolve exclusivamente JSON com esta forma:\n\n${schema('fragmento ouvido')}`, turns: 'Cria um segmento por turno de fala. Usa o mesmo identificador para a mesma voz e outro quando a voz mudar.', noNames: 'Não inventes nomes próprios para os intervenientes. Os tempos devem estar em segundos e não podem sobrepor-se.', transcript: 'A transcrição existente é fornecida apenas para facilitar o alinhamento; a aplicação preservará literalmente o seu texto:' },
  'pt-BR': { expected: (count) => `São esperados aproximadamente ${count} participantes.`, inferSpeakers: 'Determine o número de participantes por suas vozes; não o deduza pelo conteúdo.', analyze: 'Analise acusticamente este áudio e faça a diarização dos participantes.', json: `Retorne exclusivamente JSON neste formato:\n\n${schema('fragmento ouvido')}`, turns: 'Crie um segmento por turno de fala. Use o mesmo identificador para a mesma voz e outro quando a voz mudar.', noNames: 'Não invente nomes próprios para os participantes. Os tempos devem estar em segundos e não podem se sobrepor.', transcript: 'A transcrição existente é fornecida somente para facilitar o alinhamento; o aplicativo preservará literalmente seu texto:' },
  it: { expected: (count) => `Sono previsti circa ${count} parlanti.`, inferSpeakers: 'Determina il numero di parlanti dalle loro voci; non dedurlo dal contenuto.', analyze: 'Analizza acusticamente questo audio ed esegui la diarizzazione dei parlanti.', json: `Restituisci esclusivamente JSON in questa forma:\n\n${schema('frammento udito')}`, turns: 'Crea un segmento per ogni turno di parola. Usa lo stesso identificatore per la stessa voce e uno diverso quando la voce cambia.', noNames: 'Non inventare nomi propri per i parlanti. I tempi devono essere espressi in secondi e non sovrapporsi.', transcript: 'La trascrizione esistente è fornita solo per facilitare l’allineamento; l’applicazione ne conserverà letteralmente il testo:' },
  tr: { expected: (count) => `Yaklaşık ${count} konuşmacı bekleniyor.`, inferSpeakers: 'Konuşmacı sayısını seslerinden belirle; içerikten çıkarma.', analyze: 'Bu sesi akustik olarak incele ve konuşmacı diarizasyonu yap.', json: `Yalnızca şu biçimde JSON döndür:\n\n${schema('duyulan parça')}`, turns: 'Her konuşma sırası için bir segment oluştur. Aynı ses için aynı kimliği, ses değiştiğinde farklı bir kimliği kullan.', noNames: 'Konuşmacılar için özel ad uydurma. Zamanlar saniye cinsinden olmalı ve çakışmamalıdır.', transcript: 'Mevcut transkript yalnızca hizalamayı kolaylaştırmak için sağlanmıştır; uygulama metni birebir koruyacaktır:' },
};

export function studyDiarizationPromptPack(language: PromptLanguage = 'es'): StudyDiarizationPromptPack {
  return PACKS[language] ?? PACKS.es;
}
