import type { PromptLanguage } from './types';

/** Copy surrounding the two native Study/Teaching prompt packs.
 *
 * This copy is intentionally kept separate from the base pedagogical prompts in
 * `studyDeepResearch.ts`: these clauses are shared by the planner, writer, quality
 * repair and final audit, and must travel as one language-complete contract.
 */
export interface StudyDeepResearchProgressCopy {
  snapshot: (unitMode: boolean) => string;
  planning: (fixed: boolean, teacherPlan: boolean, unitMode: boolean, count: number) => string;
  section: (teacherPlan: boolean, title: string) => string;
  assembling: (teacherPlan: boolean, unitMode: boolean) => string;
  done: (teacherPlan: boolean, unitMode: boolean, single: boolean, sections: number, sources: number) => string;
  noSources: (unitMode: boolean) => string;
  stoppedReason: string;
  noCitations: string;
}

export interface StudyDeepResearchPromptPack {
  fixedOutlineRule: string;
  sectionFocusRule: string;
  plannerRules: readonly string[];
  writerRules: readonly string[];
  finalizerRules: readonly string[];
  finalAuditRules: readonly string[];
  reviseStudySection: (teacherPlan: boolean) => string;
  progress: StudyDeepResearchProgressCopy;
}

const LANGUAGES: readonly PromptLanguage[] = ['es', 'en', 'fr', 'de', 'pt', 'pt-BR', 'it', 'tr', 'zh-Hans', 'zh-Hant', 'vi', 'ja', 'ru', 'uk', 'ko'];

const PACKS: Record<PromptLanguage, StudyDeepResearchPromptPack> = {
  es: {
    fixedOutlineRule: 'ESTRUCTURA FIJADA POR EL DOCENTE: el campo "fixedSections" define exactamente las partes de la unidad, su número y su orden. Devuelve EXACTAMENTE esas partes, con los mismos id y en el mismo orden. No añadas, elimines ni reordenes ninguna. Cuando una parte trae "title", cópialo literalmente; cuando viene vacío, ponle tú un título. Cuando trae "focus", es una instrucción del docente sobre qué debe tratar esa parte: respétala al asignarle propósito, afirmaciones clave y fuentes.',
    sectionFocusRule: 'El campo "teacherFocus" es una instrucción del docente sobre lo que esta parte debe tratar. Es vinculante: organiza la parte en torno a ella y no la sustituyas por otro enfoque, aunque las fuentes sugieran uno más amplio.',
    plannerRules: [
      'CALIDAD DE FUENTES: asigna a cada parte de desarrollo al menos tres materiales distintos cuando existan y sean pertinentes. Evita que varias partes dependan siempre del mismo material. La diversidad nunca justifica incluir una fuente marginal.',
      'Cada afirmación clave debe poder demostrarse con los extractos asignados. Si los materiales no cubren una parte del objetivo, conviértelo en un límite explícito y no en una afirmación especulativa.',
      'COBERTURA OBLIGATORIA: asigna cada elemento de `coverageQuestions` al menos a una parte copiándolo literalmente en el campo `coverageQuestions` de esa parte. No omitas una pregunta difícil y no inventes una respuesta si las fuentes no bastan.',
    ],
    writerRules: [
      'La extensión la determina la evidencia y la función didáctica de esta parte. Desarrolla cada concepto, conexión, matiz o desacuerdo que aporte valor y detente cuando el valor marginal sea nulo; no persigas una cantidad de palabras/párrafos ni repitas una idea con reformulaciones.',
      'ESTÁNDAR DE CALIDAD: cada párrafo sustantivo debe conectar su afirmación con evidencia concreta. Cuando haya tres o más materiales, incluye al menos tres párrafos que pongan dos fuentes en diálogo explícito; con dos materiales, hazlo en al menos dos. Explica si convergen, discrepan o cumplen funciones distintas: juntar enlaces no cuenta como síntesis.',
      'No confundas una analogía pedagógica con un hecho documentado. Distingue lo que dicen los materiales de la explicación que construyes a partir de ellos y declara los límites del corpus.',
    ],
    finalizerRules: ['El título y el resumen solo pueden sintetizar lo establecido en `sectionFindings`. No prometas aprendizajes, relaciones, ejemplos o certezas que el cuerpo y las fuentes usadas no desarrollen.'],
    finalAuditRules: [
      'Eres el control epistemológico final de un informe de estudio o unidad didáctica. Audita solo título, resumen, limitaciones y próximos pasos.',
      'Compara cada afirmación del resumen con `sectionFindings`. Estrecha o elimina cualquier concepto, relación, dominio, ejemplo, aprendizaje o certeza que el cuerpo no establezca.',
      'No introduzcas información nueva ni elimines limitaciones previas. Los próximos pasos pueden comprobar o ampliar lo aprendido, pero no presentarlo como ya demostrado.',
      'Conserva el idioma. Devuelve SOLO JSON con {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}.',
    ],
    reviseStudySection: (teacherPlan) => [
      teacherPlan ? 'Eres el editor pedagógico final de una parte de una unidad didáctica profesional.' : 'Eres el editor pedagógico final de un informe de estudio riguroso.',
      'Reescribe el borrador para corregir exclusivamente los problemas medidos que se indican.',
      'Conserva la extensión, el idioma, la audiencia y el propósito. Usa solo los extractos permitidos y copia sus enlaces exactos. No inventes hechos, ejemplos atribuidos ni materiales.',
      'Mejora la progresión conceptual, la explicación de mecanismos, el contraste entre fuentes, los matices y la conexión explícita con el objetivo.',
      teacherPlan ? 'Conserva las actividades y comprobaciones de comprensión, pero asegúrate de que se derivan de los materiales y de que son realizables.' : 'Los ejemplos o analogías deben distinguirse con claridad de los hechos documentados y no sustituir la evidencia.',
      'No acumules citas para elevar artificialmente la densidad. Cada párrafo sustantivo debe quedar respaldado y, cuando haya tres o más materiales, al menos tres párrafos deben poner dos fuentes en diálogo explícito; con dos materiales, hazlo en al menos dos párrafos. Explica la relación, no juntes enlaces.',
      'Mantén un único encabezado ##, sin microsecciones ni listas salvo necesidad pedagógica estricta. Devuelve solo el Markdown revisado.',
    ].join('\n'),
    progress: {
      snapshot: (unitMode) => unitMode ? 'Recuperando materiales, apuntes y transcripciones de clase…' : 'Recuperando apuntes, materiales y transcripciones relevantes…',
      planning: (fixed, teacherPlan, unitMode, count) => fixed ? `Ajustando el esquema indicado (${count} partes) a los materiales…` : teacherPlan ? `Diseñando la unidad en ${count} partes…` : unitMode ? `Preparando apuntes para el alumnado en ${count} partes…` : `Diseñando una explicación didáctica en ${count} secciones…`,
      section: (teacherPlan, title) => `${teacherPlan ? 'Redactando' : 'Explicando'}: ${title}`,
      assembling: (teacherPlan, unitMode) => teacherPlan ? 'Preparando síntesis, materiales y propuestas de evaluación…' : unitMode ? 'Preparando síntesis, fuentes y actividades de autoevaluación…' : 'Preparando síntesis, fuentes y actividades de comprensión…',
      done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Unidad lista: ${single ? 'bloque continuo' : `${sections} partes`} · ${sources} materiales` : unitMode ? `Apuntes listos: ${single ? 'bloque continuo' : `${sections} partes`} · ${sources} materiales` : `Informe de estudio listo: ${single ? 'bloque continuo' : `${sections} secciones`} · ${sources} fuentes`,
      noSources: (unitMode) => unitMode ? 'No hay contenido indexado suficiente en los materiales de clase para diseñar la unidad.' : 'No hay contenido indexado suficiente en los materiales de estudio para generar el informe.',
      stoppedReason: 'El contexto se acotó a los fragmentos más relevantes del índice de estudio.',
      noCitations: 'Sin fuentes citadas',
    },
  },
  en: {
    fixedOutlineRule: 'TEACHER-FIXED STRUCTURE: the `fixedSections` field defines exactly the unit’s parts, count, and order. Return EXACTLY those parts, with the same ids and in the same order. Do not add, remove, or reorder any. When a part has a `title`, copy it literally; when it is empty, supply a title. When it has a `focus`, it is the teacher’s instruction about what that part must cover: honor it when assigning purpose, key claims, and sources.',
    sectionFocusRule: 'The `teacherFocus` field is the teacher’s instruction about what this part must cover. It is binding: organize the part around it and do not replace it with another focus, even if the sources suggest a broader one.',
    plannerRules: ['SOURCE QUALITY: assign at least three distinct materials to each development part whenever they exist and are relevant. Avoid making several parts depend on the same material. Diversity never justifies including a marginal source.', 'Every key claim must be demonstrable from the assigned extracts. If the materials do not cover part of the objective, turn it into an explicit limitation, never a speculative claim.', 'MANDATORY COVERAGE: assign every `coverageQuestions` item to at least one part by copying it literally into that part’s `coverageQuestions` field. Do not omit a difficult question or invent an answer when the sources are insufficient.'],
    writerRules: ['Evidence and this part’s teaching function determine its length. Develop every concept, connection, nuance, or disagreement that adds value and stop when marginal value is zero; do not chase a word/paragraph count or repeat an idea in reworded form.', 'QUALITY STANDARD: every substantive paragraph must connect its claim to concrete evidence. With three or more materials, include at least three paragraphs that explicitly put two sources in dialogue; with two materials, do so in at least two. Explain whether they converge, disagree, or serve different functions: placing links together is not synthesis.', 'Do not confuse a pedagogical analogy with a documented fact. Distinguish what the materials say from the explanation you construct from them and state the corpus limits.'],
    finalizerRules: ['The title and abstract may synthesize only what is established in `sectionFindings`. Do not promise learning, relationships, examples, or certainty that the body and sources used do not develop.'],
    finalAuditRules: ['You are the final epistemic control for a study report or teaching unit. Audit only title, abstract, limitations, and next steps.', 'Compare every abstract claim with `sectionFindings`. Narrow or remove any concept, relationship, domain, example, learning outcome, or certainty that the body does not establish.', 'Do not introduce new information or remove prior limitations. Next steps may check or extend learning, but must not present it as already demonstrated.', 'Preserve the language. Return VALID JSON ONLY as {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}.'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? 'You are the final pedagogical editor of a professional teaching-unit part.' : 'You are the final pedagogical editor of a rigorous study report.', 'Rewrite the draft to correct exclusively the measured problems listed.', 'Preserve length, language, audience, and purpose. Use only the permitted extracts and copy their exact links. Do not invent facts, attributed examples, or materials.', 'Improve conceptual progression, explanation of mechanisms, contrast between sources, nuance, and the explicit connection to the objective.', teacherPlan ? 'Keep the learning activities and comprehension checks, but ensure they derive from the materials and are feasible.' : 'Examples or analogies must be clearly distinguished from documented facts and must not replace evidence.', 'Do not accumulate citations to raise density artificially. Every substantive paragraph must be supported and, with three or more materials, at least three paragraphs must explicitly put two sources in dialogue; with two materials, do so in at least two paragraphs. Explain the relationship rather than placing links together.', 'Keep one ## heading, with no micro-sections or lists except where strictly pedagogically necessary. Return only the revised Markdown.'].join('\n'),
    progress: {
      snapshot: (unitMode) => unitMode ? 'Retrieving classroom materials, notes, and transcripts…' : 'Retrieving relevant notes, materials, and transcripts…',
      planning: (fixed, teacherPlan, unitMode, count) => fixed ? `Adapting the requested outline (${count} parts) to the materials…` : teacherPlan ? `Designing the unit in ${count} parts…` : unitMode ? `Preparing student notes in ${count} parts…` : `Designing a teaching explanation in ${count} sections…`,
      section: (teacherPlan, title) => `${teacherPlan ? 'Writing' : 'Explaining'}: ${title}`,
      assembling: (teacherPlan, unitMode) => teacherPlan ? 'Preparing synthesis, materials, and assessment proposals…' : unitMode ? 'Preparing synthesis, sources, and self-check activities…' : 'Preparing synthesis, sources, and comprehension activities…',
      done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Unit ready: ${single ? 'continuous block' : `${sections} parts`} · ${sources} materials` : unitMode ? `Notes ready: ${single ? 'continuous block' : `${sections} parts`} · ${sources} materials` : `Study report ready: ${single ? 'continuous block' : `${sections} sections`} · ${sources} sources`,
      noSources: (unitMode) => unitMode ? 'There is not enough indexed content in the classroom materials to design the unit.' : 'There is not enough indexed content in the study materials to generate the report.',
      stoppedReason: 'Context was narrowed to the most relevant fragments in the study index.',
      noCitations: 'No cited sources',
    },
  },
  fr: {
    fixedOutlineRule: 'STRUCTURE FIXÉE PAR L’ENSEIGNANT : le champ `fixedSections` définit exactement les parties de l’unité, leur nombre et leur ordre. Retournez EXACTEMENT ces parties, avec les mêmes ids et dans le même ordre. N’en ajoutez, n’en supprimez et n’en réordonnez aucune. Lorsqu’une partie comporte un `title`, recopiez-le littéralement; lorsqu’il est vide, donnez-lui un titre. Lorsqu’elle comporte un `focus`, il s’agit de l’instruction de l’enseignant sur ce que la partie doit traiter : respectez-la pour attribuer objectif, affirmations clés et sources.',
    sectionFocusRule: 'Le champ `teacherFocus` est l’instruction de l’enseignant sur ce que cette partie doit traiter. Elle est contraignante : organisez la partie autour d’elle et ne la remplacez pas par une autre orientation, même si les sources en suggèrent une plus large.',
    plannerRules: ['QUALITÉ DES SOURCES : attribuez à chaque partie de développement au moins trois documents distincts lorsqu’ils existent et sont pertinents. Évitez que plusieurs parties dépendent toujours du même document. La diversité ne justifie jamais une source marginale.', 'Chaque affirmation clé doit pouvoir être démontrée par les extraits attribués. Si les matériaux ne couvrent pas une partie de l’objectif, transformez-la en limite explicite et non en affirmation spéculative.', 'COUVERTURE OBLIGATOIRE : attribuez chaque élément de `coverageQuestions` à au moins une partie en le recopiant littéralement dans le champ `coverageQuestions` de cette partie. N’omettez pas une question difficile et n’inventez pas de réponse lorsque les sources sont insuffisantes.'],
    writerRules: ['La longueur est déterminée par les preuves et la fonction pédagogique de cette partie. Développez chaque concept, lien, nuance ou désaccord qui apporte une valeur et arrêtez-vous lorsque la valeur marginale est nulle; ne poursuivez pas un nombre de mots ou de paragraphes et ne répétez pas une idée reformulée.', 'STANDARD DE QUALITÉ : chaque paragraphe substantiel doit relier son affirmation à une preuve concrète. Avec au moins trois documents, incluez au moins trois paragraphes mettant explicitement deux sources en dialogue; avec deux documents, faites-le dans au moins deux. Expliquez si elles convergent, divergent ou remplissent des fonctions différentes : juxtaposer des liens ne constitue pas une synthèse.', 'Ne confondez pas une analogie pédagogique avec un fait documenté. Distinguez ce que disent les matériaux de l’explication que vous construisez à partir d’eux et déclarez les limites du corpus.'],
    finalizerRules: ['Le titre et le résumé ne peuvent synthétiser que ce qui est établi dans `sectionFindings`. Ne promettez pas d’apprentissages, de relations, d’exemples ou de certitudes que le corps et les sources utilisées ne développent pas.'],
    finalAuditRules: ['Vous êtes le contrôle épistémique final d’un rapport d’étude ou d’une unité didactique. Auditez uniquement le titre, le résumé, les limites et les prochaines étapes.', 'Comparez chaque affirmation du résumé à `sectionFindings`. Réduisez ou supprimez tout concept, relation, domaine, exemple, apprentissage ou degré de certitude que le corps n’établit pas.', 'N’introduisez aucune information nouvelle et ne supprimez pas les limites précédentes. Les prochaines étapes peuvent vérifier ou approfondir les acquis, mais ne doivent pas les présenter comme déjà démontrés.', 'Conservez la langue. Retournez UNIQUEMENT un JSON valide sous la forme {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}.'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? 'Vous êtes l’éditeur pédagogique final d’une partie d’une unité didactique professionnelle.' : 'Vous êtes l’éditeur pédagogique final d’un rapport d’étude rigoureux.', 'Réécrivez le brouillon pour corriger exclusivement les problèmes mesurés indiqués.', 'Conservez la longueur, la langue, le public et l’objectif. Utilisez uniquement les extraits autorisés et copiez leurs liens exacts. N’inventez ni faits, ni exemples attribués, ni matériaux.', 'Améliorez la progression conceptuelle, l’explication des mécanismes, le contraste entre les sources, les nuances et le lien explicite avec l’objectif.', teacherPlan ? 'Conservez les activités et les vérifications de compréhension, mais assurez-vous qu’elles découlent des matériaux et sont réalisables.' : 'Les exemples ou analogies doivent être clairement distingués des faits documentés et ne pas remplacer les preuves.', 'N’accumulez pas les citations pour augmenter artificiellement la densité. Chaque paragraphe substantiel doit être étayé et, avec au moins trois documents, au moins trois paragraphes doivent mettre explicitement deux sources en dialogue; avec deux documents, faites-le dans au moins deux paragraphes. Expliquez la relation au lieu de juxtaposer les liens.', 'Gardez un seul titre ##, sans micro-sections ni listes sauf nécessité pédagogique stricte. Retournez uniquement le Markdown révisé.'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? 'Récupération des supports, notes et transcriptions de cours…' : 'Récupération des notes, supports et transcriptions pertinents…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `Adaptation du plan indiqué (${count} parties) aux supports…` : teacherPlan ? `Conception de l’unité en ${count} parties…` : unitMode ? `Préparation des notes pour les élèves en ${count} parties…` : `Conception d’une explication pédagogique en ${count} sections…`, section: (teacherPlan, title) => `${teacherPlan ? 'Rédaction' : 'Explication'} : ${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? 'Préparation de la synthèse, des supports et des propositions d’évaluation…' : unitMode ? 'Préparation de la synthèse, des sources et des activités d’autoévaluation…' : 'Préparation de la synthèse, des sources et des activités de compréhension…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Unité prête : ${single ? 'bloc continu' : `${sections} parties`} · ${sources} supports` : unitMode ? `Notes prêtes : ${single ? 'bloc continu' : `${sections} parties`} · ${sources} supports` : `Rapport d’étude prêt : ${single ? 'bloc continu' : `${sections} sections`} · ${sources} sources`, noSources: (unitMode) => unitMode ? 'Le contenu indexé des supports de cours est insuffisant pour concevoir l’unité.' : 'Le contenu indexé des supports d’étude est insuffisant pour générer le rapport.', stoppedReason: 'Le contexte a été limité aux fragments les plus pertinents de l’index d’étude.', noCitations: 'Aucune source citée' },
  },
  de: {
    fixedOutlineRule: 'VON DER LEHRKRAFT FESTGELEGTE STRUKTUR: Das Feld `fixedSections` definiert genau die Teile der Einheit sowie deren Anzahl und Reihenfolge. Geben Sie GENAU diese Teile mit denselben ids und in derselben Reihenfolge zurück. Fügen Sie keine hinzu, entfernen oder ordnen Sie keine um. Wenn ein Teil einen `title` hat, kopieren Sie ihn wörtlich; wenn er leer ist, vergeben Sie einen Titel. Ein `focus` ist die Anweisung der Lehrkraft, was dieser Teil behandeln muss: Berücksichtigen Sie ihn bei Zweck, Kernaussagen und Quellen.',
    sectionFocusRule: 'Das Feld `teacherFocus` ist die Anweisung der Lehrkraft, was dieser Teil behandeln muss. Sie ist verbindlich: Richten Sie den Teil daran aus und ersetzen Sie sie nicht durch einen anderen Schwerpunkt, auch wenn die Quellen einen umfassenderen nahelegen.',
    plannerRules: ['QUELLENQUALITÄT: Weisen Sie jedem Entwicklungsteil mindestens drei verschiedene Materialien zu, sofern sie vorhanden und relevant sind. Vermeiden Sie, dass mehrere Teile immer vom selben Material abhängen. Vielfalt rechtfertigt niemals eine randständige Quelle.', 'Jede Kernaussage muss aus den zugewiesenen Auszügen belegbar sein. Decken die Materialien einen Teil des Ziels nicht ab, machen Sie daraus eine ausdrückliche Einschränkung, niemals eine spekulative Aussage.', 'VERBINDLICHE ABDECKUNG: Weisen Sie jedes Element von `coverageQuestions` mindestens einem Teil zu, indem Sie es wörtlich in dessen Feld `coverageQuestions` kopieren. Lassen Sie keine schwierige Frage aus und erfinden Sie keine Antwort, wenn die Quellen nicht ausreichen.'],
    writerRules: ['Die Länge wird durch Belege und die didaktische Funktion dieses Teils bestimmt. Entwickeln Sie jedes wertvolle Konzept, jede Verbindung, Nuance oder Uneinigkeit und hören Sie auf, wenn der Grenznutzen null ist; verfolgen Sie keine Wort-/Absatzmenge und wiederholen Sie keine Idee umformuliert.', 'QUALITÄTSSTANDARD: Jeder inhaltliche Absatz muss seine Aussage mit konkreten Belegen verbinden. Bei mindestens drei Materialien fügen Sie mindestens drei Absätze ein, die zwei Quellen ausdrücklich in Dialog bringen; bei zwei Materialien tun Sie dies in mindestens zwei Absätzen. Erklären Sie, ob sie übereinstimmen, abweichen oder unterschiedliche Funktionen erfüllen: Links nebeneinanderzustellen ist keine Synthese.', 'Verwechseln Sie eine didaktische Analogie nicht mit einer dokumentierten Tatsache. Unterscheiden Sie, was die Materialien sagen, von der daraus entwickelten Erklärung und benennen Sie die Grenzen des Korpus.'],
    finalizerRules: ['Titel und Zusammenfassung dürfen nur das in `sectionFindings` Festgestellte zusammenfassen. Versprechen Sie keine Lerninhalte, Beziehungen, Beispiele oder Gewissheiten, die der Textkörper und die verwendeten Quellen nicht entwickeln.'],
    finalAuditRules: ['Sie sind die abschließende erkenntnistheoretische Kontrolle eines Studienberichts oder einer Unterrichtseinheit. Prüfen Sie ausschließlich Titel, Zusammenfassung, Einschränkungen und nächste Schritte.', 'Vergleichen Sie jede Aussage der Zusammenfassung mit `sectionFindings`. Grenzen oder entfernen Sie jedes Konzept, jede Beziehung, jeden Bereich, jedes Beispiel, jedes Lernergebnis oder jede Gewissheit, die der Textkörper nicht belegt.', 'Führen Sie keine neuen Informationen ein und entfernen Sie keine bisherigen Einschränkungen. Nächste Schritte dürfen das Gelernte prüfen oder erweitern, es aber nicht als bereits bewiesen darstellen.', 'Behalten Sie die Sprache bei. Geben Sie AUSSCHLIESSLICH gültiges JSON zurück: {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}.'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? 'Sie sind der abschließende didaktische Redakteur eines professionellen Teils einer Unterrichtseinheit.' : 'Sie sind der abschließende didaktische Redakteur eines gründlichen Studienberichts.', 'Schreiben Sie den Entwurf neu, um ausschließlich die genannten gemessenen Probleme zu beheben.', 'Bewahren Sie Länge, Sprache, Zielgruppe und Zweck. Verwenden Sie nur die erlaubten Auszüge und kopieren Sie deren exakte Links. Erfinden Sie keine Fakten, zugeschriebenen Beispiele oder Materialien.', 'Verbessern Sie begriffliche Progression, Mechanismuserklärung, Quellenvergleich, Nuancen und die ausdrückliche Verbindung zum Ziel.', teacherPlan ? 'Bewahren Sie Aktivitäten und Verständnisprüfungen, aber stellen Sie sicher, dass sie aus den Materialien abgeleitet und durchführbar sind.' : 'Beispiele oder Analogien müssen klar von dokumentierten Fakten unterschieden werden und dürfen Belege nicht ersetzen.', 'Häufen Sie keine Zitate an, um die Dichte künstlich zu erhöhen. Jeder inhaltliche Absatz muss belegt sein; bei mindestens drei Materialien müssen mindestens drei Absätze zwei Quellen ausdrücklich in Dialog bringen, bei zwei Materialien mindestens zwei Absätze. Erklären Sie die Beziehung statt Links nebeneinanderzustellen.', 'Behalten Sie eine einzige ##-Überschrift, ohne Mikroabschnitte oder Listen außer bei strikt didaktischer Notwendigkeit. Geben Sie nur das überarbeitete Markdown zurück.'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? 'Unterrichtsmaterialien, Notizen und Transkripte werden abgerufen…' : 'Relevante Notizen, Materialien und Transkripte werden abgerufen…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `Die vorgegebene Gliederung (${count} Teile) wird an die Materialien angepasst…` : teacherPlan ? `Die Einheit wird in ${count} Teilen entworfen…` : unitMode ? `Lernnotizen werden in ${count} Teilen vorbereitet…` : `Eine didaktische Erklärung wird in ${count} Abschnitten entworfen…`, section: (teacherPlan, title) => `${teacherPlan ? 'Verfassen' : 'Erklären'}: ${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? 'Zusammenfassung, Materialien und Prüfungsvorschläge werden vorbereitet…' : unitMode ? 'Zusammenfassung, Quellen und Aktivitäten zur Selbstkontrolle werden vorbereitet…' : 'Zusammenfassung, Quellen und Aktivitäten zur Verständnisprüfung werden vorbereitet…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Einheit bereit: ${single ? 'fortlaufender Block' : `${sections} Teile`} · ${sources} Materialien` : unitMode ? `Notizen bereit: ${single ? 'fortlaufender Block' : `${sections} Teile`} · ${sources} Materialien` : `Studienbericht bereit: ${single ? 'fortlaufender Block' : `${sections} Abschnitte`} · ${sources} Quellen`, noSources: (unitMode) => unitMode ? 'Der indexierte Inhalt der Unterrichtsmaterialien reicht zum Entwerfen der Einheit nicht aus.' : 'Der indexierte Inhalt der Studienmaterialien reicht zum Erstellen des Berichts nicht aus.', stoppedReason: 'Der Kontext wurde auf die relevantesten Fragmente des Studienindex beschränkt.', noCitations: 'Keine zitierten Quellen' },
  },
  pt: {
    fixedOutlineRule: 'ESTRUTURA FIXADA PELO DOCENTE: o campo `fixedSections` define exatamente as partes da unidade, o seu número e a sua ordem. Devolve EXATAMENTE essas partes, com os mesmos ids e pela mesma ordem. Não acrescentes, elimines nem reordenes nenhuma. Quando uma parte tem `title`, copia-o literalmente; quando está vazio, atribui um título. Quando tem `focus`, é a instrução do docente sobre o que essa parte deve tratar: respeita-a ao atribuir propósito, afirmações-chave e fontes.',
    sectionFocusRule: 'O campo `teacherFocus` é a instrução do docente sobre o que esta parte deve tratar. É vinculativa: organiza a parte em torno dela e não a substituas por outra orientação, mesmo que as fontes sugiram uma mais ampla.',
    plannerRules: ['QUALIDADE DAS FONTES: atribui a cada parte de desenvolvimento pelo menos três materiais distintos quando existam e sejam pertinentes. Evita que várias partes dependam sempre do mesmo material. A diversidade nunca justifica incluir uma fonte marginal.', 'Cada afirmação-chave tem de poder ser demonstrada pelos excertos atribuídos. Se os materiais não cobrirem uma parte do objetivo, transforma-a numa limitação explícita e não numa afirmação especulativa.', 'COBERTURA OBRIGATÓRIA: atribui cada elemento de `coverageQuestions` a pelo menos uma parte, copiando-o literalmente para o campo `coverageQuestions` dessa parte. Não omitas uma pergunta difícil nem inventes uma resposta quando as fontes não forem suficientes.'],
    writerRules: ['A extensão é determinada pela evidência e pela função pedagógica desta parte. Desenvolve cada conceito, ligação, nuance ou desacordo que acrescente valor e para quando o valor marginal for nulo; não procures uma quantidade de palavras/parágrafos nem repitas uma ideia reformulada.', 'PADRÃO DE QUALIDADE: cada parágrafo substancial deve ligar a sua afirmação a evidência concreta. Com três ou mais materiais, inclui pelo menos três parágrafos que ponham explicitamente duas fontes em diálogo; com dois materiais, faz isso em pelo menos dois. Explica se convergem, divergem ou cumprem funções diferentes: juntar ligações não é síntese.', 'Não confundas uma analogia pedagógica com um facto documentado. Distingue o que dizem os materiais da explicação que constróis a partir deles e declara os limites do corpus.'],
    finalizerRules: ['O título e o resumo só podem sintetizar o que está estabelecido em `sectionFindings`. Não prometas aprendizagens, relações, exemplos ou certezas que o corpo e as fontes usadas não desenvolvam.'],
    finalAuditRules: ['És o controlo epistemológico final de um relatório de estudo ou unidade didática. Audita apenas o título, o resumo, as limitações e os passos seguintes.', 'Compara cada afirmação do resumo com `sectionFindings`. Estreita ou elimina qualquer conceito, relação, domínio, exemplo, aprendizagem ou certeza que o corpo não estabeleça.', 'Não introduzas informação nova nem elimines limitações anteriores. Os passos seguintes podem verificar ou ampliar o que foi aprendido, mas não apresentá-lo como já demonstrado.', 'Conserva a língua. Devolve APENAS JSON válido no formato {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}.'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? 'És o editor pedagógico final de uma parte de uma unidade didática profissional.' : 'És o editor pedagógico final de um relatório de estudo rigoroso.', 'Reescreve o rascunho para corrigir exclusivamente os problemas medidos indicados.', 'Conserva a extensão, a língua, o público e o propósito. Usa apenas os excertos permitidos e copia as suas ligações exatas. Não inventes factos, exemplos atribuídos nem materiais.', 'Melhora a progressão conceptual, a explicação de mecanismos, o contraste entre fontes, as nuances e a ligação explícita ao objetivo.', teacherPlan ? 'Conserva as atividades e verificações de compreensão, mas garante que derivam dos materiais e são realizáveis.' : 'Os exemplos ou analogias devem distinguir-se claramente dos factos documentados e não substituir a evidência.', 'Não acumules citações para elevar artificialmente a densidade. Cada parágrafo substancial deve ser apoiado e, com três ou mais materiais, pelo menos três parágrafos devem pôr explicitamente duas fontes em diálogo; com dois materiais, faz isso em pelo menos dois parágrafos. Explica a relação, não juntes ligações.', 'Mantém um único título ##, sem micro-secções nem listas salvo necessidade pedagógica estrita. Devolve apenas o Markdown revisto.'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? 'A recuperar materiais, notas e transcrições de aula…' : 'A recuperar notas, materiais e transcrições relevantes…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `A ajustar o esquema indicado (${count} partes) aos materiais…` : teacherPlan ? `A conceber a unidade em ${count} partes…` : unitMode ? `A preparar apontamentos para os alunos em ${count} partes…` : `A conceber uma explicação pedagógica em ${count} secções…`, section: (teacherPlan, title) => `${teacherPlan ? 'A redigir' : 'A explicar'}: ${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? 'A preparar síntese, materiais e propostas de avaliação…' : unitMode ? 'A preparar síntese, fontes e atividades de autoavaliação…' : 'A preparar síntese, fontes e atividades de compreensão…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Unidade pronta: ${single ? 'bloco contínuo' : `${sections} partes`} · ${sources} materiais` : unitMode ? `Apontamentos prontos: ${single ? 'bloco contínuo' : `${sections} partes`} · ${sources} materiais` : `Relatório de estudo pronto: ${single ? 'bloco contínuo' : `${sections} secções`} · ${sources} fontes`, noSources: (unitMode) => unitMode ? 'Não há conteúdo indexado suficiente nos materiais de aula para conceber a unidade.' : 'Não há conteúdo indexado suficiente nos materiais de estudo para gerar o relatório.', stoppedReason: 'O contexto foi limitado aos fragmentos mais relevantes do índice de estudo.', noCitations: 'Sem fontes citadas' },
  },
  'pt-BR': {
    fixedOutlineRule: 'ESTRUTURA FIXADA PELO DOCENTE: o campo `fixedSections` define exatamente as partes da unidade, seu número e sua ordem. Retorne EXATAMENTE essas partes, com os mesmos ids e na mesma ordem. Não acrescente, remova nem reordene nenhuma. Quando uma parte tiver `title`, copie-o literalmente; quando estiver vazio, atribua um título. Quando tiver `focus`, será a instrução do docente sobre o que essa parte deve abordar: respeite-a ao atribuir propósito, afirmações-chave e fontes.',
    sectionFocusRule: 'O campo `teacherFocus` é a instrução do docente sobre o que esta parte deve abordar. É vinculante: organize a parte em torno dele e não o substitua por outro foco, mesmo que as fontes sugiram um mais amplo.',
    plannerRules: ['QUALIDADE DAS FONTES: atribua a cada parte de desenvolvimento pelo menos três materiais distintos quando existirem e forem pertinentes. Evite que várias partes dependam sempre do mesmo material. A diversidade nunca justifica incluir uma fonte marginal.', 'Cada afirmação-chave deve poder ser demonstrada pelos excertos atribuídos. Se os materiais não cobrirem parte do objetivo, transforme isso em uma limitação explícita, nunca em uma afirmação especulativa.', 'COBERTURA OBRIGATÓRIA: atribua cada elemento de `coverageQuestions` a pelo menos uma parte, copiando-o literalmente no campo `coverageQuestions` dessa parte. Não omita uma pergunta difícil nem invente uma resposta quando as fontes não forem suficientes.'],
    writerRules: ['A extensão é determinada pela evidência e pela função didática desta parte. Desenvolva cada conceito, conexão, nuance ou discordância que acrescente valor e pare quando o valor marginal for nulo; não persiga uma quantidade de palavras/parágrafos nem repita uma ideia reformulada.', 'PADRÃO DE QUALIDADE: cada parágrafo substantivo deve conectar sua afirmação a evidência concreta. Com três ou mais materiais, inclua pelo menos três parágrafos que coloquem explicitamente duas fontes em diálogo; com dois materiais, faça isso em pelo menos dois. Explique se convergem, divergem ou cumprem funções diferentes: juntar links não é síntese.', 'Não confunda uma analogia pedagógica com um fato documentado. Diferencie o que os materiais dizem da explicação que você constrói a partir deles e declare os limites do corpus.'],
    finalizerRules: ['O título e o resumo só podem sintetizar o que estiver estabelecido em `sectionFindings`. Não prometa aprendizagens, relações, exemplos ou certezas que o corpo e as fontes usadas não desenvolvam.'],
    finalAuditRules: ['Você é o controle epistemológico final de um relatório de estudo ou unidade didática. Audite apenas título, resumo, limitações e próximos passos.', 'Compare cada afirmação do resumo com `sectionFindings`. Restrinja ou elimine qualquer conceito, relação, domínio, exemplo, aprendizagem ou certeza que o corpo não estabeleça.', 'Não introduza informação nova nem elimine limitações anteriores. Os próximos passos podem verificar ou ampliar o que foi aprendido, mas não apresentá-lo como já demonstrado.', 'Preserve o idioma. Retorne SOMENTE JSON válido no formato {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}.'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? 'Você é o editor pedagógico final de uma parte de uma unidade didática profissional.' : 'Você é o editor pedagógico final de um relatório de estudo rigoroso.', 'Reescreva o rascunho para corrigir exclusivamente os problemas medidos indicados.', 'Preserve a extensão, o idioma, o público e o propósito. Use apenas os excertos permitidos e copie seus links exatos. Não invente fatos, exemplos atribuídos nem materiais.', 'Melhore a progressão conceitual, a explicação de mecanismos, o contraste entre fontes, as nuances e a conexão explícita com o objetivo.', teacherPlan ? 'Preserve as atividades e verificações de compreensão, mas garanta que derivem dos materiais e sejam realizáveis.' : 'Exemplos ou analogias devem ser claramente diferenciados de fatos documentados e não substituir a evidência.', 'Não acumule citações para elevar artificialmente a densidade. Cada parágrafo substantivo deve ser apoiado e, com três ou mais materiais, pelo menos três parágrafos devem colocar explicitamente duas fontes em diálogo; com dois materiais, faça isso em pelo menos dois parágrafos. Explique a relação em vez de juntar links.', 'Mantenha um único título ##, sem microsseções ou listas salvo necessidade pedagógica estrita. Retorne apenas o Markdown revisado.'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? 'Recuperando materiais, anotações e transcrições de aula…' : 'Recuperando anotações, materiais e transcrições relevantes…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `Ajustando o esquema indicado (${count} partes) aos materiais…` : teacherPlan ? `Projetando a unidade em ${count} partes…` : unitMode ? `Preparando anotações para os estudantes em ${count} partes…` : `Projetando uma explicação didática em ${count} seções…`, section: (teacherPlan, title) => `${teacherPlan ? 'Redigindo' : 'Explicando'}: ${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? 'Preparando síntese, materiais e propostas de avaliação…' : unitMode ? 'Preparando síntese, fontes e atividades de autoavaliação…' : 'Preparando síntese, fontes e atividades de compreensão…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Unidade pronta: ${single ? 'bloco contínuo' : `${sections} partes`} · ${sources} materiais` : unitMode ? `Anotações prontas: ${single ? 'bloco contínuo' : `${sections} partes`} · ${sources} materiais` : `Relatório de estudo pronto: ${single ? 'bloco contínuo' : `${sections} seções`} · ${sources} fontes`, noSources: (unitMode) => unitMode ? 'Não há conteúdo indexado suficiente nos materiais de aula para projetar a unidade.' : 'Não há conteúdo indexado suficiente nos materiais de estudo para gerar o relatório.', stoppedReason: 'O contexto foi limitado aos fragmentos mais relevantes do índice de estudo.', noCitations: 'Sem fontes citadas' },
  },
  it: {
    fixedOutlineRule: 'STRUTTURA FISSATA DAL DOCENTE: il campo `fixedSections` definisce esattamente le parti dell’unità, il loro numero e il loro ordine. Restituisci ESATTAMENTE quelle parti, con gli stessi id e nello stesso ordine. Non aggiungerne, eliminarne o riordinarne alcuna. Quando una parte contiene `title`, copialo letteralmente; quando è vuoto, assegna un titolo. Quando contiene `focus`, è l’istruzione del docente su ciò che la parte deve trattare: rispettala nell’assegnare scopo, affermazioni chiave e fonti.',
    sectionFocusRule: 'Il campo `teacherFocus` è l’istruzione del docente su ciò che questa parte deve trattare. È vincolante: organizza la parte attorno a essa e non sostituirla con un altro orientamento, anche se le fonti ne suggeriscono uno più ampio.',
    plannerRules: ['QUALITÀ DELLE FONTI: assegna a ogni parte di sviluppo almeno tre materiali distinti quando esistono e sono pertinenti. Evita che più parti dipendano sempre dallo stesso materiale. La diversità non giustifica mai una fonte marginale.', 'Ogni affermazione chiave deve poter essere dimostrata dagli estratti assegnati. Se i materiali non coprono una parte dell’obiettivo, trasformala in un limite esplicito e non in un’affermazione speculativa.', 'COPERTURA OBBLIGATORIA: assegna ogni elemento di `coverageQuestions` ad almeno una parte copiandolo letteralmente nel campo `coverageQuestions` di quella parte. Non omettere una domanda difficile e non inventare una risposta quando le fonti non bastano.'],
    writerRules: ['La lunghezza è determinata dalle prove e dalla funzione didattica di questa parte. Sviluppa ogni concetto, collegamento, sfumatura o disaccordo che aggiunga valore e fermati quando il valore marginale è nullo; non inseguire un numero di parole/paragrafi né ripetere un’idea riformulata.', 'STANDARD DI QUALITÀ: ogni paragrafo sostanziale deve collegare la propria affermazione a prove concrete. Con almeno tre materiali, includi almeno tre paragrafi che mettano esplicitamente due fonti in dialogo; con due materiali, fallo in almeno due. Spiega se convergono, divergono o svolgono funzioni diverse: affiancare link non è sintesi.', 'Non confondere un’analogia didattica con un fatto documentato. Distingui ciò che dicono i materiali dalla spiegazione che costruisci a partire da essi e dichiara i limiti del corpus.'],
    finalizerRules: ['Il titolo e la sintesi possono sintetizzare soltanto ciò che è stabilito in `sectionFindings`. Non promettere apprendimenti, relazioni, esempi o certezze che il corpo e le fonti usate non sviluppano.'],
    finalAuditRules: ['Sei il controllo epistemico finale di una relazione di studio o di un’unità didattica. Audita solo titolo, sintesi, limiti e passi successivi.', 'Confronta ogni affermazione della sintesi con `sectionFindings`. Restringi o elimina qualsiasi concetto, relazione, ambito, esempio, apprendimento o certezza che il corpo non stabilisca.', 'Non introdurre nuove informazioni né eliminare i limiti precedenti. I passi successivi possono verificare o ampliare quanto appreso, ma non presentarlo come già dimostrato.', 'Conserva la lingua. Restituisci SOLO JSON valido nel formato {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}.'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? 'Sei l’editor didattico finale di una parte di un’unità didattica professionale.' : 'Sei l’editor didattico finale di una relazione di studio rigorosa.', 'Riscrivi la bozza per correggere esclusivamente i problemi misurati indicati.', 'Conserva lunghezza, lingua, pubblico e scopo. Usa solo gli estratti consentiti e copia i loro link esatti. Non inventare fatti, esempi attribuiti o materiali.', 'Migliora la progressione concettuale, la spiegazione dei meccanismi, il contrasto tra fonti, le sfumature e il collegamento esplicito con l’obiettivo.', teacherPlan ? 'Conserva le attività e le verifiche della comprensione, ma assicurati che derivino dai materiali e siano realizzabili.' : 'Esempi o analogie devono essere chiaramente distinti dai fatti documentati e non sostituire le prove.', 'Non accumulare citazioni per aumentare artificialmente la densità. Ogni paragrafo sostanziale deve essere supportato e, con almeno tre materiali, almeno tre paragrafi devono mettere esplicitamente due fonti in dialogo; con due materiali, fallo in almeno due paragrafi. Spiega la relazione, non affiancare link.', 'Mantieni un solo titolo ##, senza microsezioni o elenchi salvo stretta necessità didattica. Restituisci solo il Markdown revisionato.'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? 'Recupero di materiali, appunti e trascrizioni delle lezioni…' : 'Recupero di appunti, materiali e trascrizioni pertinenti…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `Adattamento dello schema indicato (${count} parti) ai materiali…` : teacherPlan ? `Progettazione dell’unità in ${count} parti…` : unitMode ? `Preparazione degli appunti per gli studenti in ${count} parti…` : `Progettazione di una spiegazione didattica in ${count} sezioni…`, section: (teacherPlan, title) => `${teacherPlan ? 'Redazione' : 'Spiegazione'}: ${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? 'Preparazione di sintesi, materiali e proposte di valutazione…' : unitMode ? 'Preparazione di sintesi, fonti e attività di autovalutazione…' : 'Preparazione di sintesi, fonti e attività di comprensione…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Unità pronta: ${single ? 'blocco continuo' : `${sections} parti`} · ${sources} materiali` : unitMode ? `Appunti pronti: ${single ? 'blocco continuo' : `${sections} parti`} · ${sources} materiali` : `Relazione di studio pronta: ${single ? 'blocco continuo' : `${sections} sezioni`} · ${sources} fonti`, noSources: (unitMode) => unitMode ? 'Il contenuto indicizzato dei materiali didattici non è sufficiente per progettare l’unità.' : 'Il contenuto indicizzato dei materiali di studio non è sufficiente per generare la relazione.', stoppedReason: 'Il contesto è stato limitato ai frammenti più pertinenti dell’indice di studio.', noCitations: 'Nessuna fonte citata' },
  },
  tr: {
    fixedOutlineRule: 'ÖĞRETMENİN SABİTLEDİĞİ YAPI: `fixedSections` alanı ünitenin bölümlerini, sayısını ve sırasını tam olarak tanımlar. AYNI bölümleri, aynı id değerleriyle ve aynı sırada döndürün. Hiçbirini eklemeyin, çıkarmayın veya yeniden sıralamayın. Bir bölümde `title` varsa kelimesi kelimesine kopyalayın; boşsa bir başlık verin. `focus` varsa bu, öğretmenin bölümün ele alması gereken konuya ilişkin talimatıdır: amaç, temel iddialar ve kaynakları atarken buna uyun.',
    sectionFocusRule: '`teacherFocus` alanı, öğretmenin bu bölümün ele alması gereken konuya ilişkin talimatıdır. Bağlayıcıdır: bölümü bunun etrafında düzenleyin ve kaynaklar daha geniş bir odak önerse bile bunu başka bir odakla değiştirmeyin.',
    plannerRules: ['KAYNAK KALİTESİ: mevcut ve ilgili olduklarında her geliştirme bölümüne en az üç farklı materyal atayın. Birden çok bölümün sürekli aynı materyale dayanmasından kaçının. Çeşitlilik, marjinal bir kaynağı eklemeyi asla haklı çıkarmaz.', 'Her temel iddia, atanan alıntılardan gösterilebilir olmalıdır. Materyaller hedefin bir bölümünü kapsamıyorsa bunu spekülatif bir iddia değil, açık bir sınırlılık hâline getirin.', 'ZORUNLU KAPSAM: her `coverageQuestions` öğesini kelimesi kelimesine o bölümün `coverageQuestions` alanına kopyalayarak en az bir bölüme atayın. Zor bir soruyu atlamayın ve kaynaklar yetmiyorsa yanıt uydurmayın.'],
    writerRules: ['Uzunluğu bu bölümün kanıtları ve pedagojik işlevi belirler. Değer katan her kavramı, bağlantıyı, nüansı veya anlaşmazlığı geliştirin ve marjinal değer sıfır olduğunda durun; bir kelime/paragraf sayısını hedeflemeyin veya bir fikri yeniden ifade ederek tekrarlamayın.', 'KALİTE STANDARDI: her önemli paragraf iddiasını somut kanıta bağlamalıdır. Üç veya daha fazla materyal olduğunda iki kaynağı açıkça diyaloğa sokan en az üç paragraf ekleyin; iki materyalde bunu en az iki paragrafta yapın. Birleşiyor, ayrışıyor veya farklı işlevler görüyorlarsa açıklayın: bağlantıları yan yana koymak sentez değildir.', 'Pedagojik bir benzetmeyi belgelenmiş gerçekle karıştırmayın. Materyallerin söylediklerini onlardan kurduğunuz açıklamadan ayırın ve korpusun sınırlarını belirtin.'],
    finalizerRules: ['Başlık ve özet yalnızca `sectionFindings` içinde ortaya konanları sentezleyebilir. Gövdenin ve kullanılan kaynakların geliştirmediği öğrenmeleri, ilişkileri, örnekleri veya kesinlikleri vaat etmeyin.'],
    finalAuditRules: ['Bir çalışma raporunun veya öğretim ünitesinin nihai epistemik denetçisisiniz. Yalnızca başlığı, özeti, sınırlılıkları ve sonraki adımları denetleyin.', 'Özetteki her iddiayı `sectionFindings` ile karşılaştırın. Gövdenin ortaya koymadığı kavramı, ilişkiyi, alanı, örneği, öğrenmeyi veya kesinliği daraltın ya da kaldırın.', 'Yeni bilgi eklemeyin ve önceki sınırlılıkları kaldırmayın. Sonraki adımlar öğrenilenleri sınayabilir veya genişletebilir, ancak bunları zaten kanıtlanmış gibi sunmamalıdır.', 'Dili koruyun. YALNIZCA {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]} biçiminde geçerli JSON döndürün.'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? 'Profesyonel bir öğretim ünitesi bölümünün nihai pedagojik editörüsünüz.' : 'Titiz bir çalışma raporunun nihai pedagojik editörüsünüz.', 'Taslağı yalnızca belirtilen ölçülmüş sorunları düzeltmek için yeniden yazın.', 'Uzunluğu, dili, hedef kitleyi ve amacı koruyun. Yalnızca izin verilen alıntıları kullanın ve kesin bağlantılarını kopyalayın. Olgu, atfedilmiş örnek veya materyal uydurmayın.', 'Kavramsal ilerlemeyi, mekanizma açıklamasını, kaynaklar arasındaki karşıtlığı, nüansları ve hedefle açık bağlantıyı geliştirin.', teacherPlan ? 'Etkinlikleri ve anlama kontrollerini koruyun, ancak bunların materyallerden türediğinden ve uygulanabilir olduğundan emin olun.' : 'Örnekler veya benzetmeler belgelenmiş gerçeklerden açıkça ayrılmalı ve kanıtın yerini almamalıdır.', 'Yoğunluğu yapay olarak artırmak için alıntıları biriktirmeyin. Her önemli paragraf desteklenmeli; üç veya daha fazla materyalde en az üç paragraf iki kaynağı açıkça diyaloğa sokmalı, iki materyalde bunu en az iki paragraf yapmalıdır. Bağlantıları yan yana koymak yerine ilişkiyi açıklayın.', 'Tek bir ## başlığını koruyun; kesin pedagojik gereklilik dışında mikro bölümler veya listeler kullanmayın. Yalnızca gözden geçirilmiş Markdown döndürün.'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? 'Ders materyalleri, notlar ve transkriptler alınıyor…' : 'İlgili notlar, materyaller ve transkriptler alınıyor…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `Belirtilen taslak (${count} bölüm) materyallere uyarlanıyor…` : teacherPlan ? `Ünite ${count} bölüm hâlinde tasarlanıyor…` : unitMode ? `Öğrenci notları ${count} bölüm hâlinde hazırlanıyor…` : `Pedagojik açıklama ${count} bölüm hâlinde tasarlanıyor…`, section: (teacherPlan, title) => `${teacherPlan ? 'Yazılıyor' : 'Açıklanıyor'}: ${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? 'Sentez, materyaller ve değerlendirme önerileri hazırlanıyor…' : unitMode ? 'Sentez, kaynaklar ve öz değerlendirme etkinlikleri hazırlanıyor…' : 'Sentez, kaynaklar ve anlama etkinlikleri hazırlanıyor…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Ünite hazır: ${single ? 'kesintisiz blok' : `${sections} bölüm`} · ${sources} materyal` : unitMode ? `Notlar hazır: ${single ? 'kesintisiz blok' : `${sections} bölüm`} · ${sources} materyal` : `Çalışma raporu hazır: ${single ? 'kesintisiz blok' : `${sections} bölüm`} · ${sources} kaynak`, noSources: (unitMode) => unitMode ? 'Üniteyi tasarlamak için ders materyallerinde yeterli dizinlenmiş içerik yok.' : 'Raporu oluşturmak için çalışma materyallerinde yeterli dizinlenmiş içerik yok.', stoppedReason: 'Bağlam, çalışma dizinindeki en ilgili parçalara daraltıldı.', noCitations: 'Atıf yapılan kaynak yok' },
  },
  'zh-Hans': {
    fixedOutlineRule: '教师固定结构：`fixedSections` 字段精确定义了本单元的各部分、数量与顺序。请严格返回这些部分，id 与顺序保持一致。不得新增、删除或重排任何部分。当某部分带有 `title` 时，请原样复制；为空时，请自行拟定标题。当某部分带有 `focus` 时，它是教师对该部分应涵盖内容的指示：在分配目的、关键论断和来源时务必遵循。',
    sectionFocusRule: '`teacherFocus` 字段是教师对本部分应涵盖内容的指示。它具有约束力：请围绕它组织本部分，不得以其他重点替代，即使来源提示了更宽泛的重点。',
    plannerRules: ['来源质量：只要存在且相关，就为每个展开部分分配至少三种不同材料。避免多个部分总是依赖同一材料。多样性绝不能成为纳入边缘来源的理由。', '每条关键论断都必须能由所分配的摘录加以证明。若材料未覆盖目标的某一部分，应将其转化为明确的局限性，而绝不能变成推测性论断。', '强制覆盖：将每个 `coverageQuestions` 条目原样复制到至少一个部分的 `coverageQuestions` 字段中。不得遗漏困难问题，也不得在来源不足时编造答案。'],
    writerRules: ['篇幅由证据和本部分的教学功能决定。请展开每个有价值的概念、联系、细微差别或分歧，并在边际价值为零时停止；不要追求字数/段落数，也不要用改写的方式重复同一观点。', '质量标准：每个实质性段落都必须将其论断与具体证据联系起来。当材料达到三种或更多时，至少要有三个段落明确让两种来源展开对话；只有两种材料时，至少要有两个段落这样做。请说明它们是趋同、分歧还是承担不同功能：把链接放在一起并不等于综合。', '不要将教学类比与有据可查的事实混为一谈。请区分材料所述与你据此构建的解释，并说明语料库的局限。'],
    finalizerRules: ['标题和摘要只能综合 `sectionFindings` 中已确立的内容。不得承诺正文与所用来源并未展开的学习成果、关系、示例或确定性。'],
    finalAuditRules: ['你是学习报告或教学单元的最终认识论把关者。只审核标题、摘要、局限性和后续步骤。', '将摘要中的每条论断与 `sectionFindings` 对照。凡正文未确立的概念、关系、领域、示例、学习成果或确定性，一律收窄或删除。', '不得引入新信息，也不得删除先前的局限性。后续步骤可以检验或扩展所学内容，但不得将其呈现为已被证明。', '保持语言不变。仅返回有效 JSON：{"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}。'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? '你是专业教学单元某一部分的最终教学编辑。' : '你是严谨学习报告的最终教学编辑。', '重写草稿，仅修正所列出的已测量问题。', '保持篇幅、语言、受众和目的不变。只使用获准的摘录，并原样复制其链接。不得编造事实、杜撰归属的示例或材料。', '改进概念递进、机制阐释、来源之间的对比、细微差别以及与目标的明确联系。', teacherPlan ? '保留学习活动和理解检查，但确保它们源自材料且切实可行。' : '示例或类比必须与有据可查的事实明确区分，且不得取代证据。', '不要堆砌引文以人为提高密度。每个实质性段落都必须有依据，且当材料达到三种或更多时，至少三个段落必须明确让两种来源展开对话；只有两种材料时，至少两个段落这样做。请阐释其关系，而不是把链接放在一起。', '保持一个 ## 标题，除非教学上严格必要，不得设置微章节或列表。只返回修改后的 Markdown。'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? '正在检索课堂材料、笔记和文字记录…' : '正在检索相关笔记、材料和文字记录…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `正在将指定大纲（${count} 个部分）与材料适配…` : teacherPlan ? `正在设计由 ${count} 个部分组成的单元…` : unitMode ? `正在准备 ${count} 个部分的学生笔记…` : `正在设计分 ${count} 节的教学讲解…`, section: (teacherPlan, title) => `${teacherPlan ? '撰写' : '讲解'}：${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? '正在准备综合、材料和评估建议…' : unitMode ? '正在准备综合、来源和自评活动…' : '正在准备综合、来源和理解活动…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `单元已就绪：${single ? '连续块' : `${sections} 个部分`} · ${sources} 份材料` : unitMode ? `笔记已就绪：${single ? '连续块' : `${sections} 个部分`} · ${sources} 份材料` : `学习报告已就绪：${single ? '连续块' : `${sections} 节`} · ${sources} 个来源`, noSources: (unitMode) => unitMode ? '课堂材料中没有足够的已索引内容来设计该单元。' : '学习材料中没有足够的已索引内容来生成该报告。', stoppedReason: '上下文已收窄至学习索引中最相关的片段。', noCitations: '无引用来源' },
  },
  'zh-Hant': {
    fixedOutlineRule: '教師固定結構：`fixedSections` 欄位精確定義了本單元的各部分、數量與順序。請嚴格傳回這些部分，id 與順序保持一致。不得新增、刪除或重排任何部分。當某部分帶有 `title` 時，請原樣複製；為空時，請自行擬定標題。當某部分帶有 `focus` 時，它是教師對該部分應涵蓋內容的指示：在指派目的、關鍵論斷和來源時務必遵循。',
    sectionFocusRule: '`teacherFocus` 欄位是教師對本部分應涵蓋內容的指示。它具有約束力：請圍繞它組織本部分，不得以其他重點取代，即使來源提示了更廣泛的重點。',
    plannerRules: ['來源品質：只要存在且相關，就為每個展開部分指派至少三種不同教材。避免多個部分總是依賴同一教材。多樣性絕不能成為納入邊緣來源的理由。', '每條關鍵論斷都必須能由所指派的摘錄加以證明。若教材未涵蓋目標的某一部分，應將其轉化為明確的限制，而絕不能變成推測性論斷。', '強制涵蓋：將每個 `coverageQuestions` 項目原樣複製到至少一個部分的 `coverageQuestions` 欄位中。不得遺漏困難問題，也不得在來源不足時編造答案。'],
    writerRules: ['篇幅由證據和本部分的教學功能決定。請展開每個有價值的概念、連結、細微差異或分歧，並在邊際價值為零時停止；不要追求字數/段落數，也不要用改寫的方式重複同一觀點。', '品質標準：每個實質性段落都必須將其論斷與具體證據連結起來。當教材達到三種或更多時，至少要有三個段落明確讓兩種來源展開對話；只有兩種教材時，至少要有兩個段落這樣做。請說明它們是趨同、分歧還是承擔不同功能：把連結放在一起並不等於綜合。', '不要將教學類比與有據可查的事實混為一談。請區分教材所述與你據此建構的解釋，並說明語料庫的局限。'],
    finalizerRules: ['標題和摘要只能綜合 `sectionFindings` 中已確立的內容。不得承諾正文與所用來源並未展開的學習成果、關係、示例或確定性。'],
    finalAuditRules: ['你是學習報告或教學單元的最終認識論把關者。只審核標題、摘要、限制和後續步驟。', '將摘要中的每條論斷與 `sectionFindings` 對照。凡正文未確立的概念、關係、領域、示例、學習成果或確定性，一律收窄或刪除。', '不得引入新資訊，也不得刪除先前的限制。後續步驟可以檢驗或擴展所學內容，但不得將其呈現為已被證明。', '保持語言不變。僅傳回有效 JSON：{"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}。'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? '你是專業教學單元某一部分的最終教學編輯。' : '你是嚴謹學習報告的最終教學編輯。', '重寫草稿，僅修正所列出的已量測問題。', '保持篇幅、語言、受眾和目的一致。只使用獲准的摘錄，並原樣複製其連結。不得編造事實、杜撰歸屬的示例或教材。', '改進概念遞進、機制闡釋、來源之間的對比、細微差異以及與目標的明確連結。', teacherPlan ? '保留學習活動和理解檢查，但確保它們源自教材且切實可行。' : '示例或類比必須與有據可查的事實明確區分，且不得取代證據。', '不要堆砌引文以人為提高密度。每個實質性段落都必須有依據，且當教材達到三種或更多時，至少三個段落必須明確讓兩種來源展開對話；只有兩種教材時，至少兩個段落這樣做。請闡釋其關係，而不是把連結放在一起。', '保持一個 ## 標題，除非教學上嚴格必要，不得設置微章節或清單。只傳回修改後的 Markdown。'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? '正在檢索課堂教材、筆記和逐字稿…' : '正在檢索相關筆記、教材和逐字稿…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `正在將指定大綱（${count} 個部分）與教材適配…` : teacherPlan ? `正在設計由 ${count} 個部分組成的單元…` : unitMode ? `正在準備 ${count} 個部分的學生筆記…` : `正在設計分 ${count} 節的教學講解…`, section: (teacherPlan, title) => `${teacherPlan ? '撰寫' : '講解'}：${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? '正在準備綜合、教材和評量建議…' : unitMode ? '正在準備綜合、來源和自評活動…' : '正在準備綜合、來源和理解活動…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `單元已就緒：${single ? '連續區塊' : `${sections} 個部分`} · ${sources} 份教材` : unitMode ? `筆記已就緒：${single ? '連續區塊' : `${sections} 個部分`} · ${sources} 份教材` : `學習報告已就緒：${single ? '連續區塊' : `${sections} 節`} · ${sources} 個來源`, noSources: (unitMode) => unitMode ? '課堂教材中沒有足夠的已索引內容來設計該單元。' : '學習教材中沒有足夠的已索引內容來產生該報告。', stoppedReason: '上下文已收窄至學習索引中最相關的片段。', noCitations: '無引用來源' },
  },
  vi: {
    fixedOutlineRule: 'CẤU TRÚC DO GIÁO VIÊN CỐ ĐỊNH: trường `fixedSections` xác định chính xác các phần của đơn vị, số lượng và thứ tự của chúng. Hãy trả về ĐÚNG các phần đó, với cùng id và cùng thứ tự. Không thêm, bớt hay sắp xếp lại bất kỳ phần nào. Khi một phần có `title`, hãy sao chép nguyên văn; khi để trống, hãy tự đặt tiêu đề. Khi một phần có `focus`, đó là chỉ dẫn của giáo viên về nội dung phần đó phải đề cập: hãy tuân thủ khi phân bổ mục đích, luận điểm chính và nguồn.',
    sectionFocusRule: 'Trường `teacherFocus` là chỉ dẫn của giáo viên về nội dung phần này phải đề cập. Chỉ dẫn này có tính ràng buộc: hãy tổ chức phần này xoay quanh nó và không thay thế bằng một trọng tâm khác, kể cả khi các nguồn gợi ý một trọng tâm rộng hơn.',
    plannerRules: ['CHẤT LƯỢNG NGUỒN: hãy phân bổ ít nhất ba tài liệu khác nhau cho mỗi phần triển khai khi chúng tồn tại và phù hợp. Tránh để nhiều phần luôn phụ thuộc vào cùng một tài liệu. Tính đa dạng không bao giờ biện minh cho việc đưa vào một nguồn ngoại vi.', 'Mỗi luận điểm chính phải có thể chứng minh được từ các trích đoạn được phân bổ. Nếu tài liệu không bao quát một phần của mục tiêu, hãy chuyển nó thành một giới hạn rõ ràng, tuyệt đối không thành luận điểm suy đoán.', 'BAO QUÁT BẮT BUỘC: hãy phân bổ mọi mục `coverageQuestions` cho ít nhất một phần bằng cách sao chép nguyên văn vào trường `coverageQuestions` của phần đó. Không bỏ qua câu hỏi khó và không bịa câu trả lời khi các nguồn không đủ.'],
    writerRules: ['Độ dài do bằng chứng và chức năng giảng dạy của phần này quyết định. Hãy phát triển mọi khái niệm, mối liên hệ, sắc thái hoặc bất đồng mang lại giá trị và dừng lại khi giá trị biên bằng không; đừng chạy theo số từ/đoạn hay lặp lại một ý bằng cách diễn đạt lại.', 'TIÊU CHUẨN CHẤT LƯỢNG: mỗi đoạn văn thực chất phải kết nối luận điểm của mình với bằng chứng cụ thể. Khi có ba tài liệu trở lên, hãy đưa vào ít nhất ba đoạn đặt hai nguồn vào đối thoại một cách rõ ràng; khi có hai tài liệu, hãy làm điều đó trong ít nhất hai đoạn. Hãy giải thích chúng hội tụ, bất đồng hay đảm nhận các chức năng khác nhau: đặt các liên kết cạnh nhau không phải là tổng hợp.', 'Đừng nhầm lẫn một phép so sánh sư phạm với một dữ kiện được ghi chép. Hãy phân biệt điều tài liệu nói với lời giải thích bạn xây dựng từ chúng và nêu rõ các giới hạn của ngữ liệu.'],
    finalizerRules: ['Tiêu đề và tóm tắt chỉ được tổng hợp những gì đã được xác lập trong `sectionFindings`. Không hứa hẹn về kiến thức, mối quan hệ, ví dụ hay độ chắc chắn mà phần thân và các nguồn được sử dụng không triển khai.'],
    finalAuditRules: ['Bạn là người kiểm soát nhận thức luận cuối cùng của một báo cáo học tập hoặc đơn vị giảng dạy. Chỉ kiểm toán tiêu đề, tóm tắt, các giới hạn và các bước tiếp theo.', 'So sánh từng luận điểm trong tóm tắt với `sectionFindings`. Hãy thu hẹp hoặc loại bỏ mọi khái niệm, mối quan hệ, lĩnh vực, ví dụ, kết quả học tập hoặc độ chắc chắn mà phần thân không xác lập.', 'Không đưa thông tin mới vào và không xóa các giới hạn trước đó. Các bước tiếp theo có thể kiểm chứng hoặc mở rộng những gì đã học, nhưng không được trình bày chúng như đã được chứng minh.', 'Giữ nguyên ngôn ngữ. CHỈ trả về JSON hợp lệ theo dạng {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}.'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? 'Bạn là biên tập viên sư phạm cuối cùng của một phần trong đơn vị giảng dạy chuyên nghiệp.' : 'Bạn là biên tập viên sư phạm cuối cùng của một báo cáo học tập nghiêm ngặt.', 'Hãy viết lại bản thảo để chỉ sửa chữa các vấn đề đo lường được đã liệt kê.', 'Giữ nguyên độ dài, ngôn ngữ, đối tượng và mục đích. Chỉ sử dụng các trích đoạn được phép và sao chép nguyên văn các liên kết của chúng. Không bịa đặt dữ kiện, ví dụ được gán nguồn hay tài liệu.', 'Cải thiện tiến trình khái niệm, giải thích cơ chế, đối chiếu giữa các nguồn, sắc thái và kết nối rõ ràng với mục tiêu.', teacherPlan ? 'Giữ nguyên các hoạt động học tập và kiểm tra hiểu bài, nhưng đảm bảo chúng xuất phát từ tài liệu và khả thi.' : 'Ví dụ hoặc phép so sánh phải được phân biệt rõ ràng với các dữ kiện được ghi chép và không được thay thế bằng chứng.', 'Không tích lũy trích dẫn để tăng mật độ một cách giả tạo. Mỗi đoạn văn thực chất phải được chống đỡ và, khi có ba tài liệu trở lên, ít nhất ba đoạn phải đặt hai nguồn vào đối thoại rõ ràng; khi có hai tài liệu, hãy làm điều đó trong ít nhất hai đoạn. Hãy giải thích mối quan hệ thay vì đặt các liên kết cạnh nhau.', 'Giữ một tiêu đề ## duy nhất, không có tiểu mục hay danh sách trừ khi thật sự cần thiết về mặt sư phạm. Chỉ trả về Markdown đã chỉnh sửa.'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? 'Đang truy xuất tài liệu lớp học, ghi chú và bản ghi…' : 'Đang truy xuất ghi chú, tài liệu và bản ghi liên quan…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `Đang điều chỉnh đề cương đã chỉ định (${count} phần) cho phù hợp với tài liệu…` : teacherPlan ? `Đang thiết kế đơn vị gồm ${count} phần…` : unitMode ? `Đang chuẩn bị ghi chú cho học sinh gồm ${count} phần…` : `Đang thiết kế bài giảng gồm ${count} mục…`, section: (teacherPlan, title) => `${teacherPlan ? 'Đang soạn' : 'Đang giải thích'}: ${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? 'Đang chuẩn bị tổng hợp, tài liệu và đề xuất đánh giá…' : unitMode ? 'Đang chuẩn bị tổng hợp, nguồn và hoạt động tự đánh giá…' : 'Đang chuẩn bị tổng hợp, nguồn và hoạt động hiểu bài…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Đơn vị đã sẵn sàng: ${single ? 'khối liền mạch' : `${sections} phần`} · ${sources} tài liệu` : unitMode ? `Ghi chú đã sẵn sàng: ${single ? 'khối liền mạch' : `${sections} phần`} · ${sources} tài liệu` : `Báo cáo học tập đã sẵn sàng: ${single ? 'khối liền mạch' : `${sections} mục`} · ${sources} nguồn`, noSources: (unitMode) => unitMode ? 'Không có đủ nội dung được lập chỉ mục trong tài liệu lớp học để thiết kế đơn vị.' : 'Không có đủ nội dung được lập chỉ mục trong tài liệu học tập để tạo báo cáo.', stoppedReason: 'Ngữ cảnh đã được thu hẹp vào những đoạn liên quan nhất trong chỉ mục học tập.', noCitations: 'Không có nguồn được trích dẫn' },
  },
  ja: {
    fixedOutlineRule: '教師が固定した構成：`fixedSections` フィールドは、単元の各部分、その数、順序を正確に定義します。それらの部分を、同じ id で同じ順序のまま、正確に返してください。追加・削除・並べ替えは一切しないでください。部分に `title` がある場合はそのままコピーし、空の場合はタイトルを付けてください。部分に `focus` がある場合は、その部分が扱うべき内容についての教師の指示です。目的、主要な主張、出典を割り当てる際は必ず従ってください。',
    sectionFocusRule: '`teacherFocus` フィールドは、この部分が扱うべき内容についての教師の指示です。これは拘束力を持ちます。それを中心に部分を構成し、出典がより広い焦点を示唆していても、別の焦点に置き換えないでください。',
    plannerRules: ['出典の品質：存在し関連性がある場合は、各展開部分に少なくとも 3 つの異なる資料を割り当ててください。複数の部分が常に同じ資料に依存するのは避けてください。多様性は、周辺的な出典を含める理由には決してなりません。', '各主要な主張は、割り当てられた抜粋から立証できなければなりません。資料が目的の一部をカバーしていない場合は、推測的な主張ではなく、明示的な限界として扱ってください。', '必須の網羅：`coverageQuestions` の各項目を、その部分の `coverageQuestions` フィールドにそのままコピーして、少なくとも 1 つの部分に割り当ててください。難しい質問を省略したり、出典が不十分なときに回答を捏造したりしないでください。'],
    writerRules: ['長さは、証拠とこの部分の教育上の機能によって決まります。価値のある概念、つながり、ニュアンス、意見の相違をすべて展開し、限界価値がゼロになったら止めてください。語数や段落数を追ったり、同じ考えを言い換えて繰り返したりしないでください。', '品質基準：実質的な各段落は、その主張を具体的な証拠に結び付けなければなりません。資料が 3 つ以上ある場合は、2 つの出典を明示的に対話させる段落を少なくとも 3 つ含めてください。資料が 2 つの場合は、少なくとも 2 つの段落でそうしてください。それらが一致するのか、相違するのか、異なる役割を果たすのかを説明してください。リンクを並べることは総合ではありません。', '教育的な類推を文献に基づく事実と混同しないでください。資料が述べていることと、それらからあなたが構築する説明を区別し、コーパスの限界を明示してください。'],
    finalizerRules: ['タイトルと要約は、`sectionFindings` で確立された内容のみを総合できます。本文と使用した出典が展開していない学習、関係、例、確実性を約束しないでください。'],
    finalAuditRules: ['あなたは学習レポートまたは授業単元の最終的な認識論的統制者です。タイトル、要約、限界、次のステップのみを監査してください。', '要約の各主張を `sectionFindings` と比較してください。本文が確立していない概念、関係、領域、例、学習成果、確実性は、狭めるか削除してください。', '新しい情報を導入したり、以前の限界を削除したりしないでください。次のステップは学習内容を確認・拡張するものであっても、すでに証明済みであるかのように提示してはなりません。', '言語を維持してください。有効な JSON のみを {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]} の形式で返してください。'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? 'あなたは、専門的な授業単元の一部を仕上げる最終的な教育編集者です。' : 'あなたは、厳密な学習レポートを仕上げる最終的な教育編集者です。', '下書きを書き直し、記載された測定済みの問題のみを修正してください。', '長さ、言語、読者、目的を維持してください。許可された抜粋のみを使用し、その正確なリンクをコピーしてください。事実、帰属された例、資料を捏造しないでください。', '概念の展開、メカニズムの説明、出典間の対比、ニュアンス、目的との明示的なつながりを改善してください。', teacherPlan ? '学習活動と理解度チェックは維持しつつ、それらが資料に基づき実行可能であることを確認してください。' : '例や類推は、文献に基づく事実と明確に区別し、証拠に代わってはなりません。', '密度を人為的に高めるために引用を積み重ねないでください。実質的な各段落は裏付けられなければならず、資料が 3 つ以上ある場合は少なくとも 3 つの段落が 2 つの出典を明示的に対話させ、資料が 2 つの場合は少なくとも 2 つの段落でそうしてください。リンクを並べるのではなく、関係を説明してください。', '## 見出しを 1 つだけ保持し、教育上どうしても必要な場合を除いて小見出しや箇条書きは使わないでください。修正後の Markdown のみを返してください。'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? '授業資料、ノート、文字起こしを取得しています…' : '関連するノート、資料、文字起こしを取得しています…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `指定された構成（${count} 部）を資料に合わせて調整しています…` : teacherPlan ? `${count} 部構成の単元を設計しています…` : unitMode ? `${count} 部構成の生徒用ノートを準備しています…` : `${count} 節構成の授業解説を設計しています…`, section: (teacherPlan, title) => `${teacherPlan ? '執筆中' : '解説中'}：${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? '総合、資料、評価案を準備しています…' : unitMode ? '総合、出典、自己評価活動を準備しています…' : '総合、出典、理解活動を準備しています…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `単元の準備が整いました：${single ? '連続ブロック' : `${sections} 部`} · 資料 ${sources} 件` : unitMode ? `ノートの準備が整いました：${single ? '連続ブロック' : `${sections} 部`} · 資料 ${sources} 件` : `学習レポートの準備が整いました：${single ? '連続ブロック' : `${sections} 節`} · 出典 ${sources} 件`, noSources: (unitMode) => unitMode ? '単元を設計するのに十分な索引付けされた内容が授業資料にありません。' : 'レポートを生成するのに十分な索引付けされた内容が学習資料にありません。', stoppedReason: '文脈は学習索引の中で最も関連する断片に絞り込まれました。', noCitations: '引用された出典なし' },
  },
  ru: {
    fixedOutlineRule: 'СТРУКТУРА, ЗАФИКСИРОВАННАЯ ПРЕПОДАВАТЕЛЕМ: поле `fixedSections` точно определяет части модуля, их количество и порядок. Верните РОВНО эти части, с теми же id и в том же порядке. Не добавляйте, не удаляйте и не меняйте их порядок. Если у части есть `title`, скопируйте его буквально; если оно пусто, придумайте заголовок. Если у части есть `focus`, это указание преподавателя о том, что должна охватывать эта часть: соблюдайте его при назначении цели, ключевых утверждений и источников.',
    sectionFocusRule: 'Поле `teacherFocus` — это указание преподавателя о том, что должна охватывать эта часть. Оно обязательно к соблюдению: организуйте часть вокруг него и не заменяйте его другим фокусом, даже если источники предлагают более широкий.',
    plannerRules: ['КАЧЕСТВО ИСТОЧНИКОВ: назначайте каждой содержательной части не менее трёх различных материалов, когда они существуют и уместны. Избегайте ситуации, когда несколько частей постоянно зависят от одного и того же материала. Разнообразие никогда не оправдывает включение второстепенного источника.', 'Каждое ключевое утверждение должно быть доказуемо на основе назначенных фрагментов. Если материалы не охватывают часть цели, превратите это в явное ограничение, а не в спекулятивное утверждение.', 'ОБЯЗАТЕЛЬНЫЙ ОХВАТ: назначьте каждый элемент `coverageQuestions` хотя бы одной части, скопировав его буквально в поле `coverageQuestions` этой части. Не пропускайте сложный вопрос и не придумывайте ответ, когда источников недостаточно.'],
    writerRules: ['Объём определяется доказательствами и дидактической функцией этой части. Раскрывайте каждую ценную идею, связь, нюанс или разногласие и останавливайтесь, когда предельная ценность равна нулю; не гонитесь за количеством слов или абзацев и не повторяйте мысль в перефразированном виде.', 'СТАНДАРТ КАЧЕСТВА: каждый содержательный абзац должен связывать своё утверждение с конкретными доказательствами. При трёх и более материалах включите не менее трёх абзацев, которые явно вводят два источника в диалог; при двух материалах сделайте это как минимум в двух абзацах. Объясните, сходятся ли они, расходятся или выполняют разные функции: простое соседство ссылок не является синтезом.', 'Не путайте педагогическую аналогию с документально подтверждённым фактом. Отличайте то, что говорят материалы, от объяснения, которое вы строите на их основе, и указывайте границы корпуса.'],
    finalizerRules: ['Заголовок и аннотация могут обобщать только то, что установлено в `sectionFindings`. Не обещайте знания, связи, примеры или определённость, которые не раскрыты в основном тексте и использованных источниках.'],
    finalAuditRules: ['Вы — финальный эпистемический контролёр учебного отчёта или учебного модуля. Проверяйте только заголовок, аннотацию, ограничения и следующие шаги.', 'Сравните каждое утверждение аннотации с `sectionFindings`. Сузьте или удалите любое понятие, связь, область, пример, результат обучения или определённость, которые не установлены в основном тексте.', 'Не вводите новую информацию и не удаляйте прежние ограничения. Следующие шаги могут проверять или расширять изученное, но не должны представлять его как уже доказанное.', 'Сохраняйте язык. Возвращайте ТОЛЬКО корректный JSON в формате {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}.'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? 'Вы — финальный педагогический редактор части профессионального учебного модуля.' : 'Вы — финальный педагогический редактор строгого учебного отчёта.', 'Перепишите черновик, чтобы исправить исключительно перечисленные измеренные проблемы.', 'Сохраните объём, язык, аудиторию и цель. Используйте только разрешённые фрагменты и копируйте их точные ссылки. Не выдумывайте факты, приписанные примеры или материалы.', 'Улучшите концептуальную последовательность, объяснение механизмов, сопоставление источников, нюансы и явную связь с целью.', teacherPlan ? 'Сохраните учебные задания и проверки понимания, но убедитесь, что они вытекают из материалов и выполнимы.' : 'Примеры и аналогии должны быть чётко отделены от документально подтверждённых фактов и не заменять доказательства.', 'Не накапливайте цитаты для искусственного повышения плотности. Каждый содержательный абзац должен быть подкреплён, и при трёх и более материалах не менее трёх абзацев должны явно вводить два источника в диалог; при двух материалах делайте это как минимум в двух абзацах. Объясняйте взаимосвязь, а не просто ставьте ссылки рядом.', 'Сохраняйте один заголовок ##, без микроразделов и списков, кроме случаев строгой педагогической необходимости. Возвращайте только исправленный Markdown.'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? 'Получение учебных материалов, заметок и расшифровок…' : 'Получение релевантных заметок, материалов и расшифровок…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `Адаптация заданного плана (${count} частей) к материалам…` : teacherPlan ? `Проектирование модуля из ${count} частей…` : unitMode ? `Подготовка заметок для учащихся из ${count} частей…` : `Проектирование учебного объяснения из ${count} разделов…`, section: (teacherPlan, title) => `${teacherPlan ? 'Написание' : 'Объяснение'}: ${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? 'Подготовка синтеза, материалов и предложений по оцениванию…' : unitMode ? 'Подготовка синтеза, источников и заданий для самопроверки…' : 'Подготовка синтеза, источников и заданий на понимание…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Модуль готов: ${single ? 'непрерывный блок' : `${sections} частей`} · материалов: ${sources}` : unitMode ? `Заметки готовы: ${single ? 'непрерывный блок' : `${sections} частей`} · материалов: ${sources}` : `Учебный отчёт готов: ${single ? 'непрерывный блок' : `${sections} разделов`} · источников: ${sources}`, noSources: (unitMode) => unitMode ? 'В учебных материалах недостаточно проиндексированного содержимого для проектирования модуля.' : 'В учебных материалах недостаточно проиндексированного содержимого для создания отчёта.', stoppedReason: 'Контекст был сужен до наиболее релевантных фрагментов учебного индекса.', noCitations: 'Без цитируемых источников' },
  },
  uk: {
    fixedOutlineRule: 'СТРУКТУРА, ЗАФІКСОВАНА ВИКЛАДАЧЕМ: поле `fixedSections` точно визначає частини модуля, їхню кількість і порядок. Поверніть РІВНО ці частини, з тими самими id і в тому самому порядку. Не додавайте, не видаляйте й не змінюйте їхній порядок. Якщо частина має `title`, скопіюйте його дослівно; якщо воно порожнє, придумайте заголовок. Якщо частина має `focus`, це вказівка викладача про те, що має охоплювати ця частина: дотримуйтеся її, призначаючи мету, ключові твердження та джерела.',
    sectionFocusRule: 'Поле `teacherFocus` — це вказівка викладача про те, що має охоплювати ця частина. Вона обов’язкова: організуйте частину навколо неї й не замінюйте її іншим фокусом, навіть якщо джерела пропонують ширший.',
    plannerRules: ['ЯКІСТЬ ДЖЕРЕЛ: призначайте кожній змістовій частині щонайменше три різні матеріали, коли вони існують і є доречними. Уникайте ситуації, коли кілька частин постійно залежать від одного й того самого матеріалу. Різноманітність ніколи не виправдовує включення другорядного джерела.', 'Кожне ключове твердження має бути доводжуваним на основі призначених фрагментів. Якщо матеріали не охоплюють частину мети, перетворіть це на явне обмеження, а не на спекулятивне твердження.', 'ОБОВ’ЯЗКОВЕ ОХОПЛЕННЯ: призначте кожен елемент `coverageQuestions` щонайменше одній частині, скопіювавши його дослівно в поле `coverageQuestions` цієї частини. Не пропускайте складне питання й не вигадуйте відповідь, коли джерел недостатньо.'],
    writerRules: ['Обсяг визначають докази та дидактична функція цієї частини. Розкривайте кожну цінну ідею, зв’язок, нюанс чи розбіжність і зупиняйтеся, коли гранична цінність дорівнює нулю; не женіться за кількістю слів чи абзаців і не повторюйте думку в перефразованому вигляді.', 'СТАНДАРТ ЯКОСТІ: кожен змістовий абзац має пов’язувати своє твердження з конкретними доказами. За трьох і більше матеріалів включіть щонайменше три абзаци, які явно вводять два джерела в діалог; за двох матеріалів зробіть це щонайменше в двох абзацах. Поясніть, чи вони збігаються, розходяться чи виконують різні функції: просте сусідство посилань не є синтезом.', 'Не плутайте педагогічну аналогію з документально підтвердженим фактом. Відрізняйте те, що кажуть матеріали, від пояснення, яке ви будуєте на їхній основі, і зазначайте межі корпусу.'],
    finalizerRules: ['Заголовок і анотація можуть узагальнювати лише те, що встановлено в `sectionFindings`. Не обіцяйте знань, зв’язків, прикладів або визначеності, яких не розкривають основний текст і використані джерела.'],
    finalAuditRules: ['Ви — фінальний епістемічний контролер навчального звіту або навчального модуля. Перевіряйте лише заголовок, анотацію, обмеження та наступні кроки.', 'Порівняйте кожне твердження анотації з `sectionFindings`. Звузьте або вилучіть будь-яке поняття, зв’язок, сферу, приклад, результат навчання чи визначеність, яких не встановлює основний текст.', 'Не вводьте нової інформації та не вилучайте попередніх обмежень. Наступні кроки можуть перевіряти або розширювати вивчене, але не повинні подавати його як уже доведене.', 'Зберігайте мову. Повертайте ЛИШЕ коректний JSON у форматі {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}.'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? 'Ви — фінальний педагогічний редактор частини професійного навчального модуля.' : 'Ви — фінальний педагогічний редактор суворого навчального звіту.', 'Перепишіть чернетку, щоб виправити виключно перелічені виміряні проблеми.', 'Збережіть обсяг, мову, аудиторію та мету. Використовуйте лише дозволені фрагменти й копіюйте їхні точні посилання. Не вигадуйте фактів, приписаних прикладів чи матеріалів.', 'Покращте концептуальну послідовність, пояснення механізмів, зіставлення джерел, нюанси та явний зв’язок із метою.', teacherPlan ? 'Збережіть навчальні завдання та перевірки розуміння, але переконайтеся, що вони випливають із матеріалів і є здійсненними.' : 'Приклади й аналогії мають бути чітко відокремлені від документально підтверджених фактів і не замінювати докази.', 'Не накопичуйте цитати для штучного підвищення щільності. Кожен змістовий абзац має бути підкріплений, і за трьох і більше матеріалів щонайменше три абзаци мають явно вводити два джерела в діалог; за двох матеріалів робіть це щонайменше в двох абзацах. Пояснюйте взаємозв’язок, а не просто ставте посилання поряд.', 'Зберігайте один заголовок ##, без мікророзділів і списків, крім випадків суворої педагогічної необхідності. Повертайте лише виправлений Markdown.'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? 'Отримання навчальних матеріалів, нотаток і транскриптів…' : 'Отримання доречних нотаток, матеріалів і транскриптів…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `Адаптація заданого плану (${count} частин) до матеріалів…` : teacherPlan ? `Проєктування модуля з ${count} частин…` : unitMode ? `Підготовка нотаток для учнів із ${count} частин…` : `Проєктування навчального пояснення з ${count} розділів…`, section: (teacherPlan, title) => `${teacherPlan ? 'Написання' : 'Пояснення'}: ${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? 'Підготовка синтезу, матеріалів і пропозицій щодо оцінювання…' : unitMode ? 'Підготовка синтезу, джерел і завдань для самоперевірки…' : 'Підготовка синтезу, джерел і завдань на розуміння…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Модуль готовий: ${single ? 'безперервний блок' : `${sections} частин`} · матеріалів: ${sources}` : unitMode ? `Нотатки готові: ${single ? 'безперервний блок' : `${sections} частин`} · матеріалів: ${sources}` : `Навчальний звіт готовий: ${single ? 'безперервний блок' : `${sections} розділів`} · джерел: ${sources}`, noSources: (unitMode) => unitMode ? 'У навчальних матеріалах недостатньо проіндексованого вмісту для проєктування модуля.' : 'У навчальних матеріалах недостатньо проіндексованого вмісту для створення звіту.', stoppedReason: 'Контекст було звужено до найдоречніших фрагментів навчального індексу.', noCitations: 'Без цитованих джерел' },
  },
  ko: {
    fixedOutlineRule: '교사가 고정한 구조: `fixedSections` 필드는 단원의 각 부분과 개수, 순서를 정확히 정의합니다. 동일한 id와 동일한 순서로 그 부분들을 정확히 반환하십시오. 어떤 부분도 추가, 삭제, 재정렬하지 마십시오. 부분에 `title`이 있으면 그대로 복사하고, 비어 있으면 제목을 붙이십시오. 부분에 `focus`가 있으면 해당 부분이 다루어야 할 내용에 대한 교사의 지침입니다. 목적, 핵심 주장, 출처를 배정할 때 이를 반드시 따르십시오.',
    sectionFocusRule: '`teacherFocus` 필드는 이 부분이 다루어야 할 내용에 대한 교사의 지침입니다. 이는 구속력을 가집니다. 이를 중심으로 부분을 구성하고, 출처가 더 넓은 초점을 시사하더라도 다른 초점으로 대체하지 마십시오.',
    plannerRules: ['출처 품질: 존재하고 관련성이 있다면 각 전개 부분에 서로 다른 자료를 최소 세 개 배정하십시오. 여러 부분이 항상 같은 자료에 의존하지 않도록 하십시오. 다양성은 주변적 출처를 포함할 이유가 결코 되지 못합니다.', '모든 핵심 주장은 배정된 발췌문으로 입증할 수 있어야 합니다. 자료가 목표의 일부를 다루지 못하면 이를 추측성 주장이 아니라 명시적인 한계로 바꾸십시오.', '필수 포괄: 모든 `coverageQuestions` 항목을 해당 부분의 `coverageQuestions` 필드에 그대로 복사하여 최소 한 부분에 배정하십시오. 어려운 질문을 누락하거나 출처가 불충분할 때 답을 지어내지 마십시오.'],
    writerRules: ['분량은 증거와 이 부분의 교수 기능에 따라 결정됩니다. 가치를 더하는 모든 개념, 연결, 뉘앙스, 이견을 전개하고 한계 가치가 0이 되면 멈추십시오. 단어/문단 수를 좇거나 같은 생각을 다른 표현으로 반복하지 마십시오.', '품질 기준: 모든 실질적 문단은 자신의 주장을 구체적 증거와 연결해야 합니다. 자료가 세 개 이상이면 두 출처를 명시적으로 대화시키는 문단을 최소 세 개 포함하십시오. 자료가 두 개면 최소 두 문단에서 그렇게 하십시오. 그것들이 수렴하는지, 상충하는지, 서로 다른 기능을 하는지 설명하십시오. 링크를 나란히 놓는 것은 종합이 아닙니다.', '교수학적 비유를 문헌으로 입증된 사실과 혼동하지 마십시오. 자료가 말하는 것과 그로부터 구성하는 설명을 구분하고 코퍼스의 한계를 밝히십시오.'],
    finalizerRules: ['제목과 초록은 `sectionFindings`에 확립된 내용만 종합할 수 있습니다. 본문과 사용된 출처가 전개하지 않은 학습, 관계, 예시, 확실성을 약속하지 마십시오.'],
    finalAuditRules: ['당신은 학습 보고서 또는 교수 단원의 최종 인식론적 통제자입니다. 제목, 초록, 한계, 다음 단계만 감사하십시오.', '초록의 모든 주장을 `sectionFindings`와 비교하십시오. 본문이 확립하지 않은 개념, 관계, 영역, 예시, 학습 성과, 확실성은 좁히거나 제거하십시오.', '새로운 정보를 도입하거나 이전의 한계를 제거하지 마십시오. 다음 단계는 학습 내용을 확인하거나 확장할 수 있지만, 이미 입증된 것으로 제시해서는 안 됩니다.', '언어를 유지하십시오. 유효한 JSON만 {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]} 형식으로 반환하십시오.'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? '당신은 전문 교수 단원의 한 부분을 마무리하는 최종 교수 편집자입니다.' : '당신은 엄격한 학습 보고서를 마무리하는 최종 교수 편집자입니다.', '나열된 측정된 문제만 수정하도록 초안을 다시 작성하십시오.', '분량, 언어, 독자, 목적을 유지하십시오. 허용된 발췌문만 사용하고 그 정확한 링크를 복사하십시오. 사실, 출처가 부여된 예시, 자료를 지어내지 마십시오.', '개념 전개, 메커니즘 설명, 출처 간 대비, 뉘앙스, 목표와의 명시적 연결을 개선하십시오.', teacherPlan ? '학습 활동과 이해도 점검은 유지하되, 그것들이 자료에서 비롯되고 실행 가능한지 확인하십시오.' : '예시나 비유는 문헌으로 입증된 사실과 명확히 구분되어야 하며 증거를 대체해서는 안 됩니다.', '밀도를 인위적으로 높이기 위해 인용을 축적하지 마십시오. 모든 실질적 문단은 뒷받침되어야 하며, 자료가 세 개 이상이면 최소 세 문단이 두 출처를 명시적으로 대화시키고, 자료가 두 개면 최소 두 문단에서 그렇게 하십시오. 링크를 나란히 놓는 대신 관계를 설명하십시오.', '## 제목을 하나만 유지하고, 교육상 반드시 필요한 경우를 제외하고 소단원이나 목록을 사용하지 마십시오. 수정된 Markdown만 반환하십시오.'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? '수업 자료, 노트, 전사본을 가져오는 중…' : '관련 노트, 자료, 전사본을 가져오는 중…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `지정된 개요(${count}개 부분)를 자료에 맞추는 중…` : teacherPlan ? `${count}개 부분으로 단원을 설계하는 중…` : unitMode ? `${count}개 부분으로 학생 노트를 준비하는 중…` : `${count}개 절로 교수 설명을 설계하는 중…`, section: (teacherPlan, title) => `${teacherPlan ? '작성 중' : '설명 중'}: ${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? '종합, 자료, 평가 제안을 준비하는 중…' : unitMode ? '종합, 출처, 자기 점검 활동을 준비하는 중…' : '종합, 출처, 이해 활동을 준비하는 중…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `단원 준비 완료: ${single ? '연속 블록' : `${sections}개 부분`} · 자료 ${sources}개` : unitMode ? `노트 준비 완료: ${single ? '연속 블록' : `${sections}개 부분`} · 자료 ${sources}개` : `학습 보고서 준비 완료: ${single ? '연속 블록' : `${sections}개 절`} · 출처 ${sources}개`, noSources: (unitMode) => unitMode ? '단원을 설계하기에 수업 자료에 색인된 내용이 충분하지 않습니다.' : '보고서를 생성하기에 학습 자료에 색인된 내용이 충분하지 않습니다.', stoppedReason: '문맥이 학습 색인의 가장 관련성 높은 단편으로 좁혀졌습니다.', noCitations: '인용된 출처 없음' },
  },
};

function normalizeLanguage(language: PromptLanguage): PromptLanguage {
  return LANGUAGES.includes(language) ? language : 'es';
}

export function studyDeepResearchPromptPack(language: PromptLanguage = 'es'): StudyDeepResearchPromptPack {
  return PACKS[normalizeLanguage(language)];
}

export const STUDY_DEEP_RESEARCH_PROMPT_PACKS = PACKS;
