import type { PromptLanguage } from './types';

/** Copy surrounding the two native Study/Teaching prompt packs.
 *
 * This copy is intentionally kept separate from the base pedagogical prompts in
 * `studyDeepResearch.ts`: these clauses are shared by the planner, writer, quality
 * repair and final audit, and must travel as one language-complete contract.
 */
export interface StudyDeepResearchProgressCopy {
  snapshot: (unitMode: boolean) => string;
  planning: (fixed: boolean, teacherPlan: boolean, unitMode: boolean, count: number) => string;
  section: (teacherPlan: boolean, title: string) => string;
  assembling: (teacherPlan: boolean, unitMode: boolean) => string;
  done: (teacherPlan: boolean, unitMode: boolean, single: boolean, sections: number, sources: number) => string;
  noSources: (unitMode: boolean) => string;
  stoppedReason: string;
  noCitations: string;
}

export interface StudyDeepResearchPromptPack {
  fixedOutlineRule: string;
  sectionFocusRule: string;
  plannerRules: readonly string[];
  writerRules: readonly string[];
  finalizerRules: readonly string[];
  finalAuditRules: readonly string[];
  reviseStudySection: (teacherPlan: boolean) => string;
  progress: StudyDeepResearchProgressCopy;
}

const LANGUAGES: readonly PromptLanguage[] = ['es', 'en', 'fr', 'de', 'pt', 'pt-BR', 'it', 'tr'];

const PACKS: Record<PromptLanguage, StudyDeepResearchPromptPack> = {
  es: {
    fixedOutlineRule: 'ESTRUCTURA FIJADA POR EL DOCENTE: el campo "fixedSections" define exactamente las partes de la unidad, su número y su orden. Devuelve EXACTAMENTE esas partes, con los mismos id y en el mismo orden. No añadas, elimines ni reordenes ninguna. Cuando una parte trae "title", cópialo literalmente; cuando viene vacío, ponle tú un título. Cuando trae "focus", es una instrucción del docente sobre qué debe tratar esa parte: respétala al asignarle propósito, afirmaciones clave y fuentes.',
    sectionFocusRule: 'El campo "teacherFocus" es una instrucción del docente sobre lo que esta parte debe tratar. Es vinculante: organiza la parte en torno a ella y no la sustituyas por otro enfoque, aunque las fuentes sugieran uno más amplio.',
    plannerRules: [
      'CALIDAD DE FUENTES: asigna a cada parte de desarrollo al menos tres materiales distintos cuando existan y sean pertinentes. Evita que varias partes dependan siempre del mismo material. La diversidad nunca justifica incluir una fuente marginal.',
      'Cada afirmación clave debe poder demostrarse con los extractos asignados. Si los materiales no cubren una parte del objetivo, conviértelo en un límite explícito y no en una afirmación especulativa.',
      'COBERTURA OBLIGATORIA: asigna cada elemento de `coverageQuestions` al menos a una parte copiándolo literalmente en el campo `coverageQuestions` de esa parte. No omitas una pregunta difícil y no inventes una respuesta si las fuentes no bastan.',
    ],
    writerRules: [
      'La extensión la determina la evidencia y la función didáctica de esta parte. Desarrolla cada concepto, conexión, matiz o desacuerdo que aporte valor y detente cuando el valor marginal sea nulo; no persigas una cantidad de palabras/párrafos ni repitas una idea con reformulaciones.',
      'ESTÁNDAR DE CALIDAD: cada párrafo sustantivo debe conectar su afirmación con evidencia concreta. Cuando haya tres o más materiales, incluye al menos tres párrafos que pongan dos fuentes en diálogo explícito; con dos materiales, hazlo en al menos dos. Explica si convergen, discrepan o cumplen funciones distintas: juntar enlaces no cuenta como síntesis.',
      'No confundas una analogía pedagógica con un hecho documentado. Distingue lo que dicen los materiales de la explicación que construyes a partir de ellos y declara los límites del corpus.',
    ],
    finalizerRules: ['El título y el resumen solo pueden sintetizar lo establecido en `sectionFindings`. No prometas aprendizajes, relaciones, ejemplos o certezas que el cuerpo y las fuentes usadas no desarrollen.'],
    finalAuditRules: [
      'Eres el control epistemológico final de un informe de estudio o unidad didáctica. Audita solo título, resumen, limitaciones y próximos pasos.',
      'Compara cada afirmación del resumen con `sectionFindings`. Estrecha o elimina cualquier concepto, relación, dominio, ejemplo, aprendizaje o certeza que el cuerpo no establezca.',
      'No introduzcas información nueva ni elimines limitaciones previas. Los próximos pasos pueden comprobar o ampliar lo aprendido, pero no presentarlo como ya demostrado.',
      'Conserva el idioma. Devuelve SOLO JSON con {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}.',
    ],
    reviseStudySection: (teacherPlan) => [
      teacherPlan ? 'Eres el editor pedagógico final de una parte de una unidad didáctica profesional.' : 'Eres el editor pedagógico final de un informe de estudio riguroso.',
      'Reescribe el borrador para corregir exclusivamente los problemas medidos que se indican.',
      'Conserva la extensión, el idioma, la audiencia y el propósito. Usa solo los extractos permitidos y copia sus enlaces exactos. No inventes hechos, ejemplos atribuidos ni materiales.',
      'Mejora la progresión conceptual, la explicación de mecanismos, el contraste entre fuentes, los matices y la conexión explícita con el objetivo.',
      teacherPlan ? 'Conserva las actividades y comprobaciones de comprensión, pero asegúrate de que se derivan de los materiales y de que son realizables.' : 'Los ejemplos o analogías deben distinguirse con claridad de los hechos documentados y no sustituir la evidencia.',
      'No acumules citas para elevar artificialmente la densidad. Cada párrafo sustantivo debe quedar respaldado y, cuando haya tres o más materiales, al menos tres párrafos deben poner dos fuentes en diálogo explícito; con dos materiales, hazlo en al menos dos párrafos. Explica la relación, no juntes enlaces.',
      'Mantén un único encabezado ##, sin microsecciones ni listas salvo necesidad pedagógica estricta. Devuelve solo el Markdown revisado.',
    ].join('\n'),
    progress: {
      snapshot: (unitMode) => unitMode ? 'Recuperando materiales, apuntes y transcripciones de clase…' : 'Recuperando apuntes, materiales y transcripciones relevantes…',
      planning: (fixed, teacherPlan, unitMode, count) => fixed ? `Ajustando el esquema indicado (${count} partes) a los materiales…` : teacherPlan ? `Diseñando la unidad en ${count} partes…` : unitMode ? `Preparando apuntes para el alumnado en ${count} partes…` : `Diseñando una explicación didáctica en ${count} secciones…`,
      section: (teacherPlan, title) => `${teacherPlan ? 'Redactando' : 'Explicando'}: ${title}`,
      assembling: (teacherPlan, unitMode) => teacherPlan ? 'Preparando síntesis, materiales y propuestas de evaluación…' : unitMode ? 'Preparando síntesis, fuentes y actividades de autoevaluación…' : 'Preparando síntesis, fuentes y actividades de comprensión…',
      done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Unidad lista: ${single ? 'bloque continuo' : `${sections} partes`} · ${sources} materiales` : unitMode ? `Apuntes listos: ${single ? 'bloque continuo' : `${sections} partes`} · ${sources} materiales` : `Informe de estudio listo: ${single ? 'bloque continuo' : `${sections} secciones`} · ${sources} fuentes`,
      noSources: (unitMode) => unitMode ? 'No hay contenido indexado suficiente en los materiales de clase para diseñar la unidad.' : 'No hay contenido indexado suficiente en los materiales de estudio para generar el informe.',
      stoppedReason: 'El contexto se acotó a los fragmentos más relevantes del índice de estudio.',
      noCitations: 'Sin fuentes citadas',
    },
  },
  en: {
    fixedOutlineRule: 'TEACHER-FIXED STRUCTURE: the `fixedSections` field defines exactly the unit’s parts, count, and order. Return EXACTLY those parts, with the same ids and in the same order. Do not add, remove, or reorder any. When a part has a `title`, copy it literally; when it is empty, supply a title. When it has a `focus`, it is the teacher’s instruction about what that part must cover: honor it when assigning purpose, key claims, and sources.',
    sectionFocusRule: 'The `teacherFocus` field is the teacher’s instruction about what this part must cover. It is binding: organize the part around it and do not replace it with another focus, even if the sources suggest a broader one.',
    plannerRules: ['SOURCE QUALITY: assign at least three distinct materials to each development part whenever they exist and are relevant. Avoid making several parts depend on the same material. Diversity never justifies including a marginal source.', 'Every key claim must be demonstrable from the assigned extracts. If the materials do not cover part of the objective, turn it into an explicit limitation, never a speculative claim.', 'MANDATORY COVERAGE: assign every `coverageQuestions` item to at least one part by copying it literally into that part’s `coverageQuestions` field. Do not omit a difficult question or invent an answer when the sources are insufficient.'],
    writerRules: ['Evidence and this part’s teaching function determine its length. Develop every concept, connection, nuance, or disagreement that adds value and stop when marginal value is zero; do not chase a word/paragraph count or repeat an idea in reworded form.', 'QUALITY STANDARD: every substantive paragraph must connect its claim to concrete evidence. With three or more materials, include at least three paragraphs that explicitly put two sources in dialogue; with two materials, do so in at least two. Explain whether they converge, disagree, or serve different functions: placing links together is not synthesis.', 'Do not confuse a pedagogical analogy with a documented fact. Distinguish what the materials say from the explanation you construct from them and state the corpus limits.'],
    finalizerRules: ['The title and abstract may synthesize only what is established in `sectionFindings`. Do not promise learning, relationships, examples, or certainty that the body and sources used do not develop.'],
    finalAuditRules: ['You are the final epistemic control for a study report or teaching unit. Audit only title, abstract, limitations, and next steps.', 'Compare every abstract claim with `sectionFindings`. Narrow or remove any concept, relationship, domain, example, learning outcome, or certainty that the body does not establish.', 'Do not introduce new information or remove prior limitations. Next steps may check or extend learning, but must not present it as already demonstrated.', 'Preserve the language. Return VALID JSON ONLY as {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}.'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? 'You are the final pedagogical editor of a professional teaching-unit part.' : 'You are the final pedagogical editor of a rigorous study report.', 'Rewrite the draft to correct exclusively the measured problems listed.', 'Preserve length, language, audience, and purpose. Use only the permitted extracts and copy their exact links. Do not invent facts, attributed examples, or materials.', 'Improve conceptual progression, explanation of mechanisms, contrast between sources, nuance, and the explicit connection to the objective.', teacherPlan ? 'Keep the learning activities and comprehension checks, but ensure they derive from the materials and are feasible.' : 'Examples or analogies must be clearly distinguished from documented facts and must not replace evidence.', 'Do not accumulate citations to raise density artificially. Every substantive paragraph must be supported and, with three or more materials, at least three paragraphs must explicitly put two sources in dialogue; with two materials, do so in at least two paragraphs. Explain the relationship rather than placing links together.', 'Keep one ## heading, with no micro-sections or lists except where strictly pedagogically necessary. Return only the revised Markdown.'].join('\n'),
    progress: {
      snapshot: (unitMode) => unitMode ? 'Retrieving classroom materials, notes, and transcripts…' : 'Retrieving relevant notes, materials, and transcripts…',
      planning: (fixed, teacherPlan, unitMode, count) => fixed ? `Adapting the requested outline (${count} parts) to the materials…` : teacherPlan ? `Designing the unit in ${count} parts…` : unitMode ? `Preparing student notes in ${count} parts…` : `Designing a teaching explanation in ${count} sections…`,
      section: (teacherPlan, title) => `${teacherPlan ? 'Writing' : 'Explaining'}: ${title}`,
      assembling: (teacherPlan, unitMode) => teacherPlan ? 'Preparing synthesis, materials, and assessment proposals…' : unitMode ? 'Preparing synthesis, sources, and self-check activities…' : 'Preparing synthesis, sources, and comprehension activities…',
      done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Unit ready: ${single ? 'continuous block' : `${sections} parts`} · ${sources} materials` : unitMode ? `Notes ready: ${single ? 'continuous block' : `${sections} parts`} · ${sources} materials` : `Study report ready: ${single ? 'continuous block' : `${sections} sections`} · ${sources} sources`,
      noSources: (unitMode) => unitMode ? 'There is not enough indexed content in the classroom materials to design the unit.' : 'There is not enough indexed content in the study materials to generate the report.',
      stoppedReason: 'Context was narrowed to the most relevant fragments in the study index.',
      noCitations: 'No cited sources',
    },
  },
  fr: {
    fixedOutlineRule: 'STRUCTURE FIXÉE PAR L’ENSEIGNANT : le champ `fixedSections` définit exactement les parties de l’unité, leur nombre et leur ordre. Retournez EXACTEMENT ces parties, avec les mêmes ids et dans le même ordre. N’en ajoutez, n’en supprimez et n’en réordonnez aucune. Lorsqu’une partie comporte un `title`, recopiez-le littéralement; lorsqu’il est vide, donnez-lui un titre. Lorsqu’elle comporte un `focus`, il s’agit de l’instruction de l’enseignant sur ce que la partie doit traiter : respectez-la pour attribuer objectif, affirmations clés et sources.',
    sectionFocusRule: 'Le champ `teacherFocus` est l’instruction de l’enseignant sur ce que cette partie doit traiter. Elle est contraignante : organisez la partie autour d’elle et ne la remplacez pas par une autre orientation, même si les sources en suggèrent une plus large.',
    plannerRules: ['QUALITÉ DES SOURCES : attribuez à chaque partie de développement au moins trois documents distincts lorsqu’ils existent et sont pertinents. Évitez que plusieurs parties dépendent toujours du même document. La diversité ne justifie jamais une source marginale.', 'Chaque affirmation clé doit pouvoir être démontrée par les extraits attribués. Si les matériaux ne couvrent pas une partie de l’objectif, transformez-la en limite explicite et non en affirmation spéculative.', 'COUVERTURE OBLIGATOIRE : attribuez chaque élément de `coverageQuestions` à au moins une partie en le recopiant littéralement dans le champ `coverageQuestions` de cette partie. N’omettez pas une question difficile et n’inventez pas de réponse lorsque les sources sont insuffisantes.'],
    writerRules: ['La longueur est déterminée par les preuves et la fonction pédagogique de cette partie. Développez chaque concept, lien, nuance ou désaccord qui apporte une valeur et arrêtez-vous lorsque la valeur marginale est nulle; ne poursuivez pas un nombre de mots ou de paragraphes et ne répétez pas une idée reformulée.', 'STANDARD DE QUALITÉ : chaque paragraphe substantiel doit relier son affirmation à une preuve concrète. Avec au moins trois documents, incluez au moins trois paragraphes mettant explicitement deux sources en dialogue; avec deux documents, faites-le dans au moins deux. Expliquez si elles convergent, divergent ou remplissent des fonctions différentes : juxtaposer des liens ne constitue pas une synthèse.', 'Ne confondez pas une analogie pédagogique avec un fait documenté. Distinguez ce que disent les matériaux de l’explication que vous construisez à partir d’eux et déclarez les limites du corpus.'],
    finalizerRules: ['Le titre et le résumé ne peuvent synthétiser que ce qui est établi dans `sectionFindings`. Ne promettez pas d’apprentissages, de relations, d’exemples ou de certitudes que le corps et les sources utilisées ne développent pas.'],
    finalAuditRules: ['Vous êtes le contrôle épistémique final d’un rapport d’étude ou d’une unité didactique. Auditez uniquement le titre, le résumé, les limites et les prochaines étapes.', 'Comparez chaque affirmation du résumé à `sectionFindings`. Réduisez ou supprimez tout concept, relation, domaine, exemple, apprentissage ou degré de certitude que le corps n’établit pas.', 'N’introduisez aucune information nouvelle et ne supprimez pas les limites précédentes. Les prochaines étapes peuvent vérifier ou approfondir les acquis, mais ne doivent pas les présenter comme déjà démontrés.', 'Conservez la langue. Retournez UNIQUEMENT un JSON valide sous la forme {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}.'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? 'Vous êtes l’éditeur pédagogique final d’une partie d’une unité didactique professionnelle.' : 'Vous êtes l’éditeur pédagogique final d’un rapport d’étude rigoureux.', 'Réécrivez le brouillon pour corriger exclusivement les problèmes mesurés indiqués.', 'Conservez la longueur, la langue, le public et l’objectif. Utilisez uniquement les extraits autorisés et copiez leurs liens exacts. N’inventez ni faits, ni exemples attribués, ni matériaux.', 'Améliorez la progression conceptuelle, l’explication des mécanismes, le contraste entre les sources, les nuances et le lien explicite avec l’objectif.', teacherPlan ? 'Conservez les activités et les vérifications de compréhension, mais assurez-vous qu’elles découlent des matériaux et sont réalisables.' : 'Les exemples ou analogies doivent être clairement distingués des faits documentés et ne pas remplacer les preuves.', 'N’accumulez pas les citations pour augmenter artificiellement la densité. Chaque paragraphe substantiel doit être étayé et, avec au moins trois documents, au moins trois paragraphes doivent mettre explicitement deux sources en dialogue; avec deux documents, faites-le dans au moins deux paragraphes. Expliquez la relation au lieu de juxtaposer les liens.', 'Gardez un seul titre ##, sans micro-sections ni listes sauf nécessité pédagogique stricte. Retournez uniquement le Markdown révisé.'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? 'Récupération des supports, notes et transcriptions de cours…' : 'Récupération des notes, supports et transcriptions pertinents…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `Adaptation du plan indiqué (${count} parties) aux supports…` : teacherPlan ? `Conception de l’unité en ${count} parties…` : unitMode ? `Préparation des notes pour les élèves en ${count} parties…` : `Conception d’une explication pédagogique en ${count} sections…`, section: (teacherPlan, title) => `${teacherPlan ? 'Rédaction' : 'Explication'} : ${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? 'Préparation de la synthèse, des supports et des propositions d’évaluation…' : unitMode ? 'Préparation de la synthèse, des sources et des activités d’autoévaluation…' : 'Préparation de la synthèse, des sources et des activités de compréhension…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Unité prête : ${single ? 'bloc continu' : `${sections} parties`} · ${sources} supports` : unitMode ? `Notes prêtes : ${single ? 'bloc continu' : `${sections} parties`} · ${sources} supports` : `Rapport d’étude prêt : ${single ? 'bloc continu' : `${sections} sections`} · ${sources} sources`, noSources: (unitMode) => unitMode ? 'Le contenu indexé des supports de cours est insuffisant pour concevoir l’unité.' : 'Le contenu indexé des supports d’étude est insuffisant pour générer le rapport.', stoppedReason: 'Le contexte a été limité aux fragments les plus pertinents de l’index d’étude.', noCitations: 'Aucune source citée' },
  },
  de: {
    fixedOutlineRule: 'VON DER LEHRKRAFT FESTGELEGTE STRUKTUR: Das Feld `fixedSections` definiert genau die Teile der Einheit sowie deren Anzahl und Reihenfolge. Geben Sie GENAU diese Teile mit denselben ids und in derselben Reihenfolge zurück. Fügen Sie keine hinzu, entfernen oder ordnen Sie keine um. Wenn ein Teil einen `title` hat, kopieren Sie ihn wörtlich; wenn er leer ist, vergeben Sie einen Titel. Ein `focus` ist die Anweisung der Lehrkraft, was dieser Teil behandeln muss: Berücksichtigen Sie ihn bei Zweck, Kernaussagen und Quellen.',
    sectionFocusRule: 'Das Feld `teacherFocus` ist die Anweisung der Lehrkraft, was dieser Teil behandeln muss. Sie ist verbindlich: Richten Sie den Teil daran aus und ersetzen Sie sie nicht durch einen anderen Schwerpunkt, auch wenn die Quellen einen umfassenderen nahelegen.',
    plannerRules: ['QUELLENQUALITÄT: Weisen Sie jedem Entwicklungsteil mindestens drei verschiedene Materialien zu, sofern sie vorhanden und relevant sind. Vermeiden Sie, dass mehrere Teile immer vom selben Material abhängen. Vielfalt rechtfertigt niemals eine randständige Quelle.', 'Jede Kernaussage muss aus den zugewiesenen Auszügen belegbar sein. Decken die Materialien einen Teil des Ziels nicht ab, machen Sie daraus eine ausdrückliche Einschränkung, niemals eine spekulative Aussage.', 'VERBINDLICHE ABDECKUNG: Weisen Sie jedes Element von `coverageQuestions` mindestens einem Teil zu, indem Sie es wörtlich in dessen Feld `coverageQuestions` kopieren. Lassen Sie keine schwierige Frage aus und erfinden Sie keine Antwort, wenn die Quellen nicht ausreichen.'],
    writerRules: ['Die Länge wird durch Belege und die didaktische Funktion dieses Teils bestimmt. Entwickeln Sie jedes wertvolle Konzept, jede Verbindung, Nuance oder Uneinigkeit und hören Sie auf, wenn der Grenznutzen null ist; verfolgen Sie keine Wort-/Absatzmenge und wiederholen Sie keine Idee umformuliert.', 'QUALITÄTSSTANDARD: Jeder inhaltliche Absatz muss seine Aussage mit konkreten Belegen verbinden. Bei mindestens drei Materialien fügen Sie mindestens drei Absätze ein, die zwei Quellen ausdrücklich in Dialog bringen; bei zwei Materialien tun Sie dies in mindestens zwei Absätzen. Erklären Sie, ob sie übereinstimmen, abweichen oder unterschiedliche Funktionen erfüllen: Links nebeneinanderzustellen ist keine Synthese.', 'Verwechseln Sie eine didaktische Analogie nicht mit einer dokumentierten Tatsache. Unterscheiden Sie, was die Materialien sagen, von der daraus entwickelten Erklärung und benennen Sie die Grenzen des Korpus.'],
    finalizerRules: ['Titel und Zusammenfassung dürfen nur das in `sectionFindings` Festgestellte zusammenfassen. Versprechen Sie keine Lerninhalte, Beziehungen, Beispiele oder Gewissheiten, die der Textkörper und die verwendeten Quellen nicht entwickeln.'],
    finalAuditRules: ['Sie sind die abschließende erkenntnistheoretische Kontrolle eines Studienberichts oder einer Unterrichtseinheit. Prüfen Sie ausschließlich Titel, Zusammenfassung, Einschränkungen und nächste Schritte.', 'Vergleichen Sie jede Aussage der Zusammenfassung mit `sectionFindings`. Grenzen oder entfernen Sie jedes Konzept, jede Beziehung, jeden Bereich, jedes Beispiel, jedes Lernergebnis oder jede Gewissheit, die der Textkörper nicht belegt.', 'Führen Sie keine neuen Informationen ein und entfernen Sie keine bisherigen Einschränkungen. Nächste Schritte dürfen das Gelernte prüfen oder erweitern, es aber nicht als bereits bewiesen darstellen.', 'Behalten Sie die Sprache bei. Geben Sie AUSSCHLIESSLICH gültiges JSON zurück: {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}.'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? 'Sie sind der abschließende didaktische Redakteur eines professionellen Teils einer Unterrichtseinheit.' : 'Sie sind der abschließende didaktische Redakteur eines gründlichen Studienberichts.', 'Schreiben Sie den Entwurf neu, um ausschließlich die genannten gemessenen Probleme zu beheben.', 'Bewahren Sie Länge, Sprache, Zielgruppe und Zweck. Verwenden Sie nur die erlaubten Auszüge und kopieren Sie deren exakte Links. Erfinden Sie keine Fakten, zugeschriebenen Beispiele oder Materialien.', 'Verbessern Sie begriffliche Progression, Mechanismuserklärung, Quellenvergleich, Nuancen und die ausdrückliche Verbindung zum Ziel.', teacherPlan ? 'Bewahren Sie Aktivitäten und Verständnisprüfungen, aber stellen Sie sicher, dass sie aus den Materialien abgeleitet und durchführbar sind.' : 'Beispiele oder Analogien müssen klar von dokumentierten Fakten unterschieden werden und dürfen Belege nicht ersetzen.', 'Häufen Sie keine Zitate an, um die Dichte künstlich zu erhöhen. Jeder inhaltliche Absatz muss belegt sein; bei mindestens drei Materialien müssen mindestens drei Absätze zwei Quellen ausdrücklich in Dialog bringen, bei zwei Materialien mindestens zwei Absätze. Erklären Sie die Beziehung statt Links nebeneinanderzustellen.', 'Behalten Sie eine einzige ##-Überschrift, ohne Mikroabschnitte oder Listen außer bei strikt didaktischer Notwendigkeit. Geben Sie nur das überarbeitete Markdown zurück.'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? 'Unterrichtsmaterialien, Notizen und Transkripte werden abgerufen…' : 'Relevante Notizen, Materialien und Transkripte werden abgerufen…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `Die vorgegebene Gliederung (${count} Teile) wird an die Materialien angepasst…` : teacherPlan ? `Die Einheit wird in ${count} Teilen entworfen…` : unitMode ? `Lernnotizen werden in ${count} Teilen vorbereitet…` : `Eine didaktische Erklärung wird in ${count} Abschnitten entworfen…`, section: (teacherPlan, title) => `${teacherPlan ? 'Verfassen' : 'Erklären'}: ${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? 'Zusammenfassung, Materialien und Prüfungsvorschläge werden vorbereitet…' : unitMode ? 'Zusammenfassung, Quellen und Aktivitäten zur Selbstkontrolle werden vorbereitet…' : 'Zusammenfassung, Quellen und Aktivitäten zur Verständnisprüfung werden vorbereitet…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Einheit bereit: ${single ? 'fortlaufender Block' : `${sections} Teile`} · ${sources} Materialien` : unitMode ? `Notizen bereit: ${single ? 'fortlaufender Block' : `${sections} Teile`} · ${sources} Materialien` : `Studienbericht bereit: ${single ? 'fortlaufender Block' : `${sections} Abschnitte`} · ${sources} Quellen`, noSources: (unitMode) => unitMode ? 'Der indexierte Inhalt der Unterrichtsmaterialien reicht zum Entwerfen der Einheit nicht aus.' : 'Der indexierte Inhalt der Studienmaterialien reicht zum Erstellen des Berichts nicht aus.', stoppedReason: 'Der Kontext wurde auf die relevantesten Fragmente des Studienindex beschränkt.', noCitations: 'Keine zitierten Quellen' },
  },
  pt: {
    fixedOutlineRule: 'ESTRUTURA FIXADA PELO DOCENTE: o campo `fixedSections` define exatamente as partes da unidade, o seu número e a sua ordem. Devolve EXATAMENTE essas partes, com os mesmos ids e pela mesma ordem. Não acrescentes, elimines nem reordenes nenhuma. Quando uma parte tem `title`, copia-o literalmente; quando está vazio, atribui um título. Quando tem `focus`, é a instrução do docente sobre o que essa parte deve tratar: respeita-a ao atribuir propósito, afirmações-chave e fontes.',
    sectionFocusRule: 'O campo `teacherFocus` é a instrução do docente sobre o que esta parte deve tratar. É vinculativa: organiza a parte em torno dela e não a substituas por outra orientação, mesmo que as fontes sugiram uma mais ampla.',
    plannerRules: ['QUALIDADE DAS FONTES: atribui a cada parte de desenvolvimento pelo menos três materiais distintos quando existam e sejam pertinentes. Evita que várias partes dependam sempre do mesmo material. A diversidade nunca justifica incluir uma fonte marginal.', 'Cada afirmação-chave tem de poder ser demonstrada pelos excertos atribuídos. Se os materiais não cobrirem uma parte do objetivo, transforma-a numa limitação explícita e não numa afirmação especulativa.', 'COBERTURA OBRIGATÓRIA: atribui cada elemento de `coverageQuestions` a pelo menos uma parte, copiando-o literalmente para o campo `coverageQuestions` dessa parte. Não omitas uma pergunta difícil nem inventes uma resposta quando as fontes não forem suficientes.'],
    writerRules: ['A extensão é determinada pela evidência e pela função pedagógica desta parte. Desenvolve cada conceito, ligação, nuance ou desacordo que acrescente valor e para quando o valor marginal for nulo; não procures uma quantidade de palavras/parágrafos nem repitas uma ideia reformulada.', 'PADRÃO DE QUALIDADE: cada parágrafo substancial deve ligar a sua afirmação a evidência concreta. Com três ou mais materiais, inclui pelo menos três parágrafos que ponham explicitamente duas fontes em diálogo; com dois materiais, faz isso em pelo menos dois. Explica se convergem, divergem ou cumprem funções diferentes: juntar ligações não é síntese.', 'Não confundas uma analogia pedagógica com um facto documentado. Distingue o que dizem os materiais da explicação que constróis a partir deles e declara os limites do corpus.'],
    finalizerRules: ['O título e o resumo só podem sintetizar o que está estabelecido em `sectionFindings`. Não prometas aprendizagens, relações, exemplos ou certezas que o corpo e as fontes usadas não desenvolvam.'],
    finalAuditRules: ['És o controlo epistemológico final de um relatório de estudo ou unidade didática. Audita apenas o título, o resumo, as limitações e os passos seguintes.', 'Compara cada afirmação do resumo com `sectionFindings`. Estreita ou elimina qualquer conceito, relação, domínio, exemplo, aprendizagem ou certeza que o corpo não estabeleça.', 'Não introduzas informação nova nem elimines limitações anteriores. Os passos seguintes podem verificar ou ampliar o que foi aprendido, mas não apresentá-lo como já demonstrado.', 'Conserva a língua. Devolve APENAS JSON válido no formato {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}.'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? 'És o editor pedagógico final de uma parte de uma unidade didática profissional.' : 'És o editor pedagógico final de um relatório de estudo rigoroso.', 'Reescreve o rascunho para corrigir exclusivamente os problemas medidos indicados.', 'Conserva a extensão, a língua, o público e o propósito. Usa apenas os excertos permitidos e copia as suas ligações exatas. Não inventes factos, exemplos atribuídos nem materiais.', 'Melhora a progressão conceptual, a explicação de mecanismos, o contraste entre fontes, as nuances e a ligação explícita ao objetivo.', teacherPlan ? 'Conserva as atividades e verificações de compreensão, mas garante que derivam dos materiais e são realizáveis.' : 'Os exemplos ou analogias devem distinguir-se claramente dos factos documentados e não substituir a evidência.', 'Não acumules citações para elevar artificialmente a densidade. Cada parágrafo substancial deve ser apoiado e, com três ou mais materiais, pelo menos três parágrafos devem pôr explicitamente duas fontes em diálogo; com dois materiais, faz isso em pelo menos dois parágrafos. Explica a relação, não juntes ligações.', 'Mantém um único título ##, sem micro-secções nem listas salvo necessidade pedagógica estrita. Devolve apenas o Markdown revisto.'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? 'A recuperar materiais, notas e transcrições de aula…' : 'A recuperar notas, materiais e transcrições relevantes…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `A ajustar o esquema indicado (${count} partes) aos materiais…` : teacherPlan ? `A conceber a unidade em ${count} partes…` : unitMode ? `A preparar apontamentos para os alunos em ${count} partes…` : `A conceber uma explicação pedagógica em ${count} secções…`, section: (teacherPlan, title) => `${teacherPlan ? 'A redigir' : 'A explicar'}: ${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? 'A preparar síntese, materiais e propostas de avaliação…' : unitMode ? 'A preparar síntese, fontes e atividades de autoavaliação…' : 'A preparar síntese, fontes e atividades de compreensão…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Unidade pronta: ${single ? 'bloco contínuo' : `${sections} partes`} · ${sources} materiais` : unitMode ? `Apontamentos prontos: ${single ? 'bloco contínuo' : `${sections} partes`} · ${sources} materiais` : `Relatório de estudo pronto: ${single ? 'bloco contínuo' : `${sections} secções`} · ${sources} fontes`, noSources: (unitMode) => unitMode ? 'Não há conteúdo indexado suficiente nos materiais de aula para conceber a unidade.' : 'Não há conteúdo indexado suficiente nos materiais de estudo para gerar o relatório.', stoppedReason: 'O contexto foi limitado aos fragmentos mais relevantes do índice de estudo.', noCitations: 'Sem fontes citadas' },
  },
  'pt-BR': {
    fixedOutlineRule: 'ESTRUTURA FIXADA PELO DOCENTE: o campo `fixedSections` define exatamente as partes da unidade, seu número e sua ordem. Retorne EXATAMENTE essas partes, com os mesmos ids e na mesma ordem. Não acrescente, remova nem reordene nenhuma. Quando uma parte tiver `title`, copie-o literalmente; quando estiver vazio, atribua um título. Quando tiver `focus`, será a instrução do docente sobre o que essa parte deve abordar: respeite-a ao atribuir propósito, afirmações-chave e fontes.',
    sectionFocusRule: 'O campo `teacherFocus` é a instrução do docente sobre o que esta parte deve abordar. É vinculante: organize a parte em torno dele e não o substitua por outro foco, mesmo que as fontes sugiram um mais amplo.',
    plannerRules: ['QUALIDADE DAS FONTES: atribua a cada parte de desenvolvimento pelo menos três materiais distintos quando existirem e forem pertinentes. Evite que várias partes dependam sempre do mesmo material. A diversidade nunca justifica incluir uma fonte marginal.', 'Cada afirmação-chave deve poder ser demonstrada pelos excertos atribuídos. Se os materiais não cobrirem parte do objetivo, transforme isso em uma limitação explícita, nunca em uma afirmação especulativa.', 'COBERTURA OBRIGATÓRIA: atribua cada elemento de `coverageQuestions` a pelo menos uma parte, copiando-o literalmente no campo `coverageQuestions` dessa parte. Não omita uma pergunta difícil nem invente uma resposta quando as fontes não forem suficientes.'],
    writerRules: ['A extensão é determinada pela evidência e pela função didática desta parte. Desenvolva cada conceito, conexão, nuance ou discordância que acrescente valor e pare quando o valor marginal for nulo; não persiga uma quantidade de palavras/parágrafos nem repita uma ideia reformulada.', 'PADRÃO DE QUALIDADE: cada parágrafo substantivo deve conectar sua afirmação a evidência concreta. Com três ou mais materiais, inclua pelo menos três parágrafos que coloquem explicitamente duas fontes em diálogo; com dois materiais, faça isso em pelo menos dois. Explique se convergem, divergem ou cumprem funções diferentes: juntar links não é síntese.', 'Não confunda uma analogia pedagógica com um fato documentado. Diferencie o que os materiais dizem da explicação que você constrói a partir deles e declare os limites do corpus.'],
    finalizerRules: ['O título e o resumo só podem sintetizar o que estiver estabelecido em `sectionFindings`. Não prometa aprendizagens, relações, exemplos ou certezas que o corpo e as fontes usadas não desenvolvam.'],
    finalAuditRules: ['Você é o controle epistemológico final de um relatório de estudo ou unidade didática. Audite apenas título, resumo, limitações e próximos passos.', 'Compare cada afirmação do resumo com `sectionFindings`. Restrinja ou elimine qualquer conceito, relação, domínio, exemplo, aprendizagem ou certeza que o corpo não estabeleça.', 'Não introduza informação nova nem elimine limitações anteriores. Os próximos passos podem verificar ou ampliar o que foi aprendido, mas não apresentá-lo como já demonstrado.', 'Preserve o idioma. Retorne SOMENTE JSON válido no formato {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}.'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? 'Você é o editor pedagógico final de uma parte de uma unidade didática profissional.' : 'Você é o editor pedagógico final de um relatório de estudo rigoroso.', 'Reescreva o rascunho para corrigir exclusivamente os problemas medidos indicados.', 'Preserve a extensão, o idioma, o público e o propósito. Use apenas os excertos permitidos e copie seus links exatos. Não invente fatos, exemplos atribuídos nem materiais.', 'Melhore a progressão conceitual, a explicação de mecanismos, o contraste entre fontes, as nuances e a conexão explícita com o objetivo.', teacherPlan ? 'Preserve as atividades e verificações de compreensão, mas garanta que derivem dos materiais e sejam realizáveis.' : 'Exemplos ou analogias devem ser claramente diferenciados de fatos documentados e não substituir a evidência.', 'Não acumule citações para elevar artificialmente a densidade. Cada parágrafo substantivo deve ser apoiado e, com três ou mais materiais, pelo menos três parágrafos devem colocar explicitamente duas fontes em diálogo; com dois materiais, faça isso em pelo menos dois parágrafos. Explique a relação em vez de juntar links.', 'Mantenha um único título ##, sem microsseções ou listas salvo necessidade pedagógica estrita. Retorne apenas o Markdown revisado.'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? 'Recuperando materiais, anotações e transcrições de aula…' : 'Recuperando anotações, materiais e transcrições relevantes…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `Ajustando o esquema indicado (${count} partes) aos materiais…` : teacherPlan ? `Projetando a unidade em ${count} partes…` : unitMode ? `Preparando anotações para os estudantes em ${count} partes…` : `Projetando uma explicação didática em ${count} seções…`, section: (teacherPlan, title) => `${teacherPlan ? 'Redigindo' : 'Explicando'}: ${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? 'Preparando síntese, materiais e propostas de avaliação…' : unitMode ? 'Preparando síntese, fontes e atividades de autoavaliação…' : 'Preparando síntese, fontes e atividades de compreensão…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Unidade pronta: ${single ? 'bloco contínuo' : `${sections} partes`} · ${sources} materiais` : unitMode ? `Anotações prontas: ${single ? 'bloco contínuo' : `${sections} partes`} · ${sources} materiais` : `Relatório de estudo pronto: ${single ? 'bloco contínuo' : `${sections} seções`} · ${sources} fontes`, noSources: (unitMode) => unitMode ? 'Não há conteúdo indexado suficiente nos materiais de aula para projetar a unidade.' : 'Não há conteúdo indexado suficiente nos materiais de estudo para gerar o relatório.', stoppedReason: 'O contexto foi limitado aos fragmentos mais relevantes do índice de estudo.', noCitations: 'Sem fontes citadas' },
  },
  it: {
    fixedOutlineRule: 'STRUTTURA FISSATA DAL DOCENTE: il campo `fixedSections` definisce esattamente le parti dell’unità, il loro numero e il loro ordine. Restituisci ESATTAMENTE quelle parti, con gli stessi id e nello stesso ordine. Non aggiungerne, eliminarne o riordinarne alcuna. Quando una parte contiene `title`, copialo letteralmente; quando è vuoto, assegna un titolo. Quando contiene `focus`, è l’istruzione del docente su ciò che la parte deve trattare: rispettala nell’assegnare scopo, affermazioni chiave e fonti.',
    sectionFocusRule: 'Il campo `teacherFocus` è l’istruzione del docente su ciò che questa parte deve trattare. È vincolante: organizza la parte attorno a essa e non sostituirla con un altro orientamento, anche se le fonti ne suggeriscono uno più ampio.',
    plannerRules: ['QUALITÀ DELLE FONTI: assegna a ogni parte di sviluppo almeno tre materiali distinti quando esistono e sono pertinenti. Evita che più parti dipendano sempre dallo stesso materiale. La diversità non giustifica mai una fonte marginale.', 'Ogni affermazione chiave deve poter essere dimostrata dagli estratti assegnati. Se i materiali non coprono una parte dell’obiettivo, trasformala in un limite esplicito e non in un’affermazione speculativa.', 'COPERTURA OBBLIGATORIA: assegna ogni elemento di `coverageQuestions` ad almeno una parte copiandolo letteralmente nel campo `coverageQuestions` di quella parte. Non omettere una domanda difficile e non inventare una risposta quando le fonti non bastano.'],
    writerRules: ['La lunghezza è determinata dalle prove e dalla funzione didattica di questa parte. Sviluppa ogni concetto, collegamento, sfumatura o disaccordo che aggiunga valore e fermati quando il valore marginale è nullo; non inseguire un numero di parole/paragrafi né ripetere un’idea riformulata.', 'STANDARD DI QUALITÀ: ogni paragrafo sostanziale deve collegare la propria affermazione a prove concrete. Con almeno tre materiali, includi almeno tre paragrafi che mettano esplicitamente due fonti in dialogo; con due materiali, fallo in almeno due. Spiega se convergono, divergono o svolgono funzioni diverse: affiancare link non è sintesi.', 'Non confondere un’analogia didattica con un fatto documentato. Distingui ciò che dicono i materiali dalla spiegazione che costruisci a partire da essi e dichiara i limiti del corpus.'],
    finalizerRules: ['Il titolo e la sintesi possono sintetizzare soltanto ciò che è stabilito in `sectionFindings`. Non promettere apprendimenti, relazioni, esempi o certezze che il corpo e le fonti usate non sviluppano.'],
    finalAuditRules: ['Sei il controllo epistemico finale di una relazione di studio o di un’unità didattica. Audita solo titolo, sintesi, limiti e passi successivi.', 'Confronta ogni affermazione della sintesi con `sectionFindings`. Restringi o elimina qualsiasi concetto, relazione, ambito, esempio, apprendimento o certezza che il corpo non stabilisca.', 'Non introdurre nuove informazioni né eliminare i limiti precedenti. I passi successivi possono verificare o ampliare quanto appreso, ma non presentarlo come già dimostrato.', 'Conserva la lingua. Restituisci SOLO JSON valido nel formato {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]}.'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? 'Sei l’editor didattico finale di una parte di un’unità didattica professionale.' : 'Sei l’editor didattico finale di una relazione di studio rigorosa.', 'Riscrivi la bozza per correggere esclusivamente i problemi misurati indicati.', 'Conserva lunghezza, lingua, pubblico e scopo. Usa solo gli estratti consentiti e copia i loro link esatti. Non inventare fatti, esempi attribuiti o materiali.', 'Migliora la progressione concettuale, la spiegazione dei meccanismi, il contrasto tra fonti, le sfumature e il collegamento esplicito con l’obiettivo.', teacherPlan ? 'Conserva le attività e le verifiche della comprensione, ma assicurati che derivino dai materiali e siano realizzabili.' : 'Esempi o analogie devono essere chiaramente distinti dai fatti documentati e non sostituire le prove.', 'Non accumulare citazioni per aumentare artificialmente la densità. Ogni paragrafo sostanziale deve essere supportato e, con almeno tre materiali, almeno tre paragrafi devono mettere esplicitamente due fonti in dialogo; con due materiali, fallo in almeno due paragrafi. Spiega la relazione, non affiancare link.', 'Mantieni un solo titolo ##, senza microsezioni o elenchi salvo stretta necessità didattica. Restituisci solo il Markdown revisionato.'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? 'Recupero di materiali, appunti e trascrizioni delle lezioni…' : 'Recupero di appunti, materiali e trascrizioni pertinenti…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `Adattamento dello schema indicato (${count} parti) ai materiali…` : teacherPlan ? `Progettazione dell’unità in ${count} parti…` : unitMode ? `Preparazione degli appunti per gli studenti in ${count} parti…` : `Progettazione di una spiegazione didattica in ${count} sezioni…`, section: (teacherPlan, title) => `${teacherPlan ? 'Redazione' : 'Spiegazione'}: ${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? 'Preparazione di sintesi, materiali e proposte di valutazione…' : unitMode ? 'Preparazione di sintesi, fonti e attività di autovalutazione…' : 'Preparazione di sintesi, fonti e attività di comprensione…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Unità pronta: ${single ? 'blocco continuo' : `${sections} parti`} · ${sources} materiali` : unitMode ? `Appunti pronti: ${single ? 'blocco continuo' : `${sections} parti`} · ${sources} materiali` : `Relazione di studio pronta: ${single ? 'blocco continuo' : `${sections} sezioni`} · ${sources} fonti`, noSources: (unitMode) => unitMode ? 'Il contenuto indicizzato dei materiali didattici non è sufficiente per progettare l’unità.' : 'Il contenuto indicizzato dei materiali di studio non è sufficiente per generare la relazione.', stoppedReason: 'Il contesto è stato limitato ai frammenti più pertinenti dell’indice di studio.', noCitations: 'Nessuna fonte citata' },
  },
  tr: {
    fixedOutlineRule: 'ÖĞRETMENİN SABİTLEDİĞİ YAPI: `fixedSections` alanı ünitenin bölümlerini, sayısını ve sırasını tam olarak tanımlar. AYNI bölümleri, aynı id değerleriyle ve aynı sırada döndürün. Hiçbirini eklemeyin, çıkarmayın veya yeniden sıralamayın. Bir bölümde `title` varsa kelimesi kelimesine kopyalayın; boşsa bir başlık verin. `focus` varsa bu, öğretmenin bölümün ele alması gereken konuya ilişkin talimatıdır: amaç, temel iddialar ve kaynakları atarken buna uyun.',
    sectionFocusRule: '`teacherFocus` alanı, öğretmenin bu bölümün ele alması gereken konuya ilişkin talimatıdır. Bağlayıcıdır: bölümü bunun etrafında düzenleyin ve kaynaklar daha geniş bir odak önerse bile bunu başka bir odakla değiştirmeyin.',
    plannerRules: ['KAYNAK KALİTESİ: mevcut ve ilgili olduklarında her geliştirme bölümüne en az üç farklı materyal atayın. Birden çok bölümün sürekli aynı materyale dayanmasından kaçının. Çeşitlilik, marjinal bir kaynağı eklemeyi asla haklı çıkarmaz.', 'Her temel iddia, atanan alıntılardan gösterilebilir olmalıdır. Materyaller hedefin bir bölümünü kapsamıyorsa bunu spekülatif bir iddia değil, açık bir sınırlılık hâline getirin.', 'ZORUNLU KAPSAM: her `coverageQuestions` öğesini kelimesi kelimesine o bölümün `coverageQuestions` alanına kopyalayarak en az bir bölüme atayın. Zor bir soruyu atlamayın ve kaynaklar yetmiyorsa yanıt uydurmayın.'],
    writerRules: ['Uzunluğu bu bölümün kanıtları ve pedagojik işlevi belirler. Değer katan her kavramı, bağlantıyı, nüansı veya anlaşmazlığı geliştirin ve marjinal değer sıfır olduğunda durun; bir kelime/paragraf sayısını hedeflemeyin veya bir fikri yeniden ifade ederek tekrarlamayın.', 'KALİTE STANDARDI: her önemli paragraf iddiasını somut kanıta bağlamalıdır. Üç veya daha fazla materyal olduğunda iki kaynağı açıkça diyaloğa sokan en az üç paragraf ekleyin; iki materyalde bunu en az iki paragrafta yapın. Birleşiyor, ayrışıyor veya farklı işlevler görüyorlarsa açıklayın: bağlantıları yan yana koymak sentez değildir.', 'Pedagojik bir benzetmeyi belgelenmiş gerçekle karıştırmayın. Materyallerin söylediklerini onlardan kurduğunuz açıklamadan ayırın ve korpusun sınırlarını belirtin.'],
    finalizerRules: ['Başlık ve özet yalnızca `sectionFindings` içinde ortaya konanları sentezleyebilir. Gövdenin ve kullanılan kaynakların geliştirmediği öğrenmeleri, ilişkileri, örnekleri veya kesinlikleri vaat etmeyin.'],
    finalAuditRules: ['Bir çalışma raporunun veya öğretim ünitesinin nihai epistemik denetçisisiniz. Yalnızca başlığı, özeti, sınırlılıkları ve sonraki adımları denetleyin.', 'Özetteki her iddiayı `sectionFindings` ile karşılaştırın. Gövdenin ortaya koymadığı kavramı, ilişkiyi, alanı, örneği, öğrenmeyi veya kesinliği daraltın ya da kaldırın.', 'Yeni bilgi eklemeyin ve önceki sınırlılıkları kaldırmayın. Sonraki adımlar öğrenilenleri sınayabilir veya genişletebilir, ancak bunları zaten kanıtlanmış gibi sunmamalıdır.', 'Dili koruyun. YALNIZCA {"title":"...","abstract":"...","limitations":["..."],"nextSteps":["..."]} biçiminde geçerli JSON döndürün.'],
    reviseStudySection: (teacherPlan) => [teacherPlan ? 'Profesyonel bir öğretim ünitesi bölümünün nihai pedagojik editörüsünüz.' : 'Titiz bir çalışma raporunun nihai pedagojik editörüsünüz.', 'Taslağı yalnızca belirtilen ölçülmüş sorunları düzeltmek için yeniden yazın.', 'Uzunluğu, dili, hedef kitleyi ve amacı koruyun. Yalnızca izin verilen alıntıları kullanın ve kesin bağlantılarını kopyalayın. Olgu, atfedilmiş örnek veya materyal uydurmayın.', 'Kavramsal ilerlemeyi, mekanizma açıklamasını, kaynaklar arasındaki karşıtlığı, nüansları ve hedefle açık bağlantıyı geliştirin.', teacherPlan ? 'Etkinlikleri ve anlama kontrollerini koruyun, ancak bunların materyallerden türediğinden ve uygulanabilir olduğundan emin olun.' : 'Örnekler veya benzetmeler belgelenmiş gerçeklerden açıkça ayrılmalı ve kanıtın yerini almamalıdır.', 'Yoğunluğu yapay olarak artırmak için alıntıları biriktirmeyin. Her önemli paragraf desteklenmeli; üç veya daha fazla materyalde en az üç paragraf iki kaynağı açıkça diyaloğa sokmalı, iki materyalde bunu en az iki paragraf yapmalıdır. Bağlantıları yan yana koymak yerine ilişkiyi açıklayın.', 'Tek bir ## başlığını koruyun; kesin pedagojik gereklilik dışında mikro bölümler veya listeler kullanmayın. Yalnızca gözden geçirilmiş Markdown döndürün.'].join('\n'),
    progress: { snapshot: (unitMode) => unitMode ? 'Ders materyalleri, notlar ve transkriptler alınıyor…' : 'İlgili notlar, materyaller ve transkriptler alınıyor…', planning: (fixed, teacherPlan, unitMode, count) => fixed ? `Belirtilen taslak (${count} bölüm) materyallere uyarlanıyor…` : teacherPlan ? `Ünite ${count} bölüm hâlinde tasarlanıyor…` : unitMode ? `Öğrenci notları ${count} bölüm hâlinde hazırlanıyor…` : `Pedagojik açıklama ${count} bölüm hâlinde tasarlanıyor…`, section: (teacherPlan, title) => `${teacherPlan ? 'Yazılıyor' : 'Açıklanıyor'}: ${title}`, assembling: (teacherPlan, unitMode) => teacherPlan ? 'Sentez, materyaller ve değerlendirme önerileri hazırlanıyor…' : unitMode ? 'Sentez, kaynaklar ve öz değerlendirme etkinlikleri hazırlanıyor…' : 'Sentez, kaynaklar ve anlama etkinlikleri hazırlanıyor…', done: (teacherPlan, unitMode, single, sections, sources) => teacherPlan ? `Ünite hazır: ${single ? 'kesintisiz blok' : `${sections} bölüm`} · ${sources} materyal` : unitMode ? `Notlar hazır: ${single ? 'kesintisiz blok' : `${sections} bölüm`} · ${sources} materyal` : `Çalışma raporu hazır: ${single ? 'kesintisiz blok' : `${sections} bölüm`} · ${sources} kaynak`, noSources: (unitMode) => unitMode ? 'Üniteyi tasarlamak için ders materyallerinde yeterli dizinlenmiş içerik yok.' : 'Raporu oluşturmak için çalışma materyallerinde yeterli dizinlenmiş içerik yok.', stoppedReason: 'Bağlam, çalışma dizinindeki en ilgili parçalara daraltıldı.', noCitations: 'Atıf yapılan kaynak yok' },
  },
};

function normalizeLanguage(language: PromptLanguage): PromptLanguage {
  return LANGUAGES.includes(language) ? language : 'es';
}

export function studyDeepResearchPromptPack(language: PromptLanguage = 'es'): StudyDeepResearchPromptPack {
  return PACKS[normalizeLanguage(language)];
}

export const STUDY_DEEP_RESEARCH_PROMPT_PACKS = PACKS;
