/**
 * Exam paper builder (teaching vault).
 *
 * This is the *printable exam* model: a teacher composes numbered questions of
 * several types, each written by hand or generated by AI from the subject's own
 * materials, and exports the result to Word/PDF. It is deliberately separate from
 * `studyAssessments.ts` — that one models an interactive test the student *takes*
 * (attempts, grading, correction mode); this one models a document that gets
 * printed, so it carries layout intent (answer lines, option columns, images) that
 * an on-screen quiz never needs.
 *
 * Everything here is pure and dependency-free so it can be unit-tested and shared by
 * the renderer (builder UI), the main process (export) and the AI generator.
 */

export const EXAM_QUESTION_TYPES = [
  'section',
  'short_essay',
  'medium_essay',
  'long_essay',
  'short_answer',
  'definition',
  'multiple_choice',
  'true_false',
  'matching',
  'ordering',
  'fill_blank',
  'image_comment',
  'problem',
] as const;

export type ExamQuestionType = (typeof EXAM_QUESTION_TYPES)[number];

/** The document's own language, independent from the interface language. */
export const EXAM_LANGUAGES = ['es', 'en', 'fr', 'de', 'pt', 'pt-BR'] as const;
export type ExamLanguage = (typeof EXAM_LANGUAGES)[number];

export interface ExamQuestionTypeDef {
  id: ExamQuestionType;
  /** Spanish source string, translated through t() in the UI. */
  label: string;
  description: string;
  icon: string;
  /** Blank ruled lines the printed paper leaves for the answer. */
  answerLines: number;
  defaultPoints: number;
  /** Needs a list of choices whose count the teacher sets. */
  needsOptions?: boolean;
  defaultOptionCount?: number;
  /** Needs left/right pairs to join with arrows. */
  needsPairs?: boolean;
  /** Needs an ordered list of items to sort. */
  needsItems?: boolean;
  /** Needs an embedded image to comment on. */
  needsImage?: boolean;
  /**
   * Not a question but a shared statement (a source text, a case, a picture) that
   * several sub-questions hang from. It takes no points of its own: its mark is the
   * sum of its sub-questions, so the two can never disagree on the printed paper.
   */
  isSection?: boolean;
  /** May carry an image even though it does not require one. */
  allowsImage?: boolean;
}

/**
 * The catalogue the "add question" menu renders. `answerLines` is what makes the
 * printed paper usable: a long essay needs a page of space, a true/false needs none.
 */
export const EXAM_QUESTION_TYPE_DEFS: ExamQuestionTypeDef[] = [
  { id: 'section', label: 'Enunciado de sección', description: 'Texto, caso o imagen común del que cuelgan varias preguntas.', icon: 'layers', answerLines: 0, defaultPoints: 0, isSection: true, allowsImage: true },
  { id: 'short_essay', label: 'Desarrollo corto', description: 'Respuesta argumentada breve, de unas pocas líneas.', icon: 'edit', answerLines: 6, defaultPoints: 1 },
  { id: 'medium_essay', label: 'Desarrollo intermedio', description: 'Respuesta argumentada de media página.', icon: 'notebook', answerLines: 12, defaultPoints: 2 },
  { id: 'long_essay', label: 'Desarrollo largo', description: 'Tema a desarrollar con una página completa de espacio.', icon: 'book', answerLines: 24, defaultPoints: 3 },
  { id: 'short_answer', label: 'Respuesta breve', description: 'Pregunta directa que se responde en una línea.', icon: 'help', answerLines: 2, defaultPoints: 0.5 },
  { id: 'definition', label: 'Definición', description: 'Definir un término o concepto clave.', icon: 'bulb', answerLines: 4, defaultPoints: 1 },
  { id: 'multiple_choice', label: 'Cuestionario', description: 'Pregunta con varias opciones; eliges cuántas.', icon: 'table', answerLines: 0, defaultPoints: 0.5, needsOptions: true, defaultOptionCount: 4 },
  { id: 'true_false', label: 'Verdadero o falso', description: 'Afirmación que el alumnado marca como verdadera o falsa.', icon: 'check', answerLines: 0, defaultPoints: 0.25 },
  { id: 'matching', label: 'Relacionar con flechas', description: 'Dos columnas que se unen con flechas.', icon: 'network', answerLines: 0, defaultPoints: 1, needsPairs: true },
  { id: 'ordering', label: 'Ordenar elementos', description: 'Elementos que se numeran en el orden correcto.', icon: 'route', answerLines: 0, defaultPoints: 1, needsItems: true },
  { id: 'fill_blank', label: 'Completar huecos', description: 'Texto con huecos que hay que rellenar.', icon: 'layers', answerLines: 3, defaultPoints: 1 },
  { id: 'image_comment', label: 'Comentario de imagen', description: 'Imagen que el alumnado debe comentar o identificar.', icon: 'image', answerLines: 10, defaultPoints: 2, needsImage: true },
  { id: 'problem', label: 'Problema o caso práctico', description: 'Supuesto práctico que exige resolución razonada.', icon: 'flask', answerLines: 14, defaultPoints: 2 },
];

const DEFS_BY_ID = new Map<ExamQuestionType, ExamQuestionTypeDef>(EXAM_QUESTION_TYPE_DEFS.map((def) => [def.id, def]));

export function isExamQuestionType(value: unknown): value is ExamQuestionType {
  return typeof value === 'string' && DEFS_BY_ID.has(value as ExamQuestionType);
}

/** Definition for a type; unknown ids fall back to the short essay. */
export function examQuestionTypeDef(type: unknown): ExamQuestionTypeDef {
  return DEFS_BY_ID.get(type as ExamQuestionType) ?? DEFS_BY_ID.get('short_essay')!;
}

/** True for the shared-statement block, false for anything the student answers. */
export function isExamSection(type: unknown): boolean {
  return examQuestionTypeDef(type).isSection === true;
}

/** The types offered inside a section: everything except another section. */
export const EXAM_SUBQUESTION_TYPE_DEFS = EXAM_QUESTION_TYPE_DEFS.filter((def) => !def.isSection);

export interface ExamOption {
  id: string;
  text: string;
  /** Only used for the optional answer key; never printed on the student's copy. */
  correct: boolean;
}

export interface ExamPair {
  id: string;
  left: string;
  right: string;
}

export interface ExamLogo {
  /** `data:image/...;base64,...` — kept inline so an exam is self-contained. */
  dataUrl: string;
  name: string;
}

export interface ExamHeaderConfig {
  institution: string;
  subjectName: string;
  teachers: string;
  groupLabel: string;
  examTitle: string;
  dateText: string;
  durationMinutes: number | null;
  instructions: string;
  showStudentName: boolean;
  showStudentId: boolean;
  showGroup: boolean;
  showDate: boolean;
  showGradeBox: boolean;
  showPoints: boolean;
}

export interface ExamQuestion {
  id: string;
  shortId: string;
  examId: string;
  /** Set on a sub-question to the id of the `section` it hangs from; null at top level. */
  parentId: string | null;
  position: number;
  type: ExamQuestionType;
  prompt: string;
  points: number;
  options: ExamOption[];
  pairs: ExamPair[];
  items: string[];
  imageDataUrl: string | null;
  imageCaption: string;
  /** Overrides the type's default ruled-line count when not null. */
  answerLines: number | null;
  /** Model answer / correction criteria. Optional, only in the answer key. */
  solution: string;
  /** The teacher's instruction used to generate it, kept so it can be re-run. */
  aiPrompt: string;
  generatedBy: 'manual' | 'ai';
  createdAt: string;
  updatedAt: string;
}

export interface TeachingExam {
  id: string;
  shortId: string;
  title: string;
  subjectId: string | null;
  courseId: string | null;
  language: ExamLanguage;
  /**
   * False while the exam still follows the interface language; set the moment the
   * teacher picks a language for THIS exam, and remembered from then on.
   */
  languageLocked: boolean;
  targetQuestionCount: number;
  header: ExamHeaderConfig;
  logos: ExamLogo[];
  createdAt: string;
  updatedAt: string;
}

export interface TeachingExamDetail extends TeachingExam {
  questions: ExamQuestion[];
}

export interface TeachingExamInput {
  title: string;
  subjectId?: string | null;
  courseId?: string | null;
  language?: ExamLanguage;
  languageLocked?: boolean;
  targetQuestionCount?: number;
  header?: Partial<ExamHeaderConfig>;
  logos?: ExamLogo[];
}

export interface ExamQuestionInput {
  type: ExamQuestionType;
  parentId?: string | null;
  prompt?: string;
  points?: number;
  options?: ExamOption[];
  pairs?: ExamPair[];
  items?: string[];
  imageDataUrl?: string | null;
  imageCaption?: string;
  answerLines?: number | null;
  solution?: string;
  aiPrompt?: string;
  generatedBy?: 'manual' | 'ai';
}

/** At most two logos fit the header band without crowding the title. */
export const MAX_EXAM_LOGOS = 2;
/** Keeps a self-contained exam from bloating the vault database. */
export const MAX_EXAM_LOGO_BYTES = 512 * 1024;
export const MAX_EXAM_IMAGE_BYTES = 4 * 1024 * 1024;

export function defaultExamHeader(overrides: Partial<ExamHeaderConfig> = {}): ExamHeaderConfig {
  return {
    institution: '',
    subjectName: '',
    teachers: '',
    groupLabel: '',
    examTitle: '',
    dateText: '',
    durationMinutes: null,
    instructions: '',
    showStudentName: true,
    showStudentId: false,
    showGroup: true,
    showDate: true,
    showGradeBox: true,
    showPoints: true,
    ...overrides,
  };
}

/** A blank question of `type`, pre-filled with the shape that type requires. */
export function defaultExamQuestion(type: ExamQuestionType): ExamQuestionInput {
  const def = examQuestionTypeDef(type);
  const options: ExamOption[] = def.needsOptions
    ? Array.from({ length: def.defaultOptionCount ?? 4 }, (_, index) => ({ id: `O${index + 1}`, text: '', correct: index === 0 }))
    : [];
  const pairs: ExamPair[] = def.needsPairs
    ? Array.from({ length: 4 }, (_, index) => ({ id: `P${index + 1}`, left: '', right: '' }))
    : [];
  const items = def.needsItems ? ['', '', '', ''] : [];
  return {
    type,
    prompt: '',
    points: def.defaultPoints,
    options,
    pairs,
    items,
    imageDataUrl: null,
    imageCaption: '',
    answerLines: null,
    solution: '',
    aiPrompt: '',
    generatedBy: 'manual',
  };
}

/** Resize a multiple-choice question's option list, preserving what was typed. */
export function resizeExamOptions(options: ExamOption[], count: number): ExamOption[] {
  const target = Math.max(2, Math.min(10, Math.round(count)));
  const next = options.slice(0, target).map((option, index) => ({ ...option, id: `O${index + 1}` }));
  while (next.length < target) next.push({ id: `O${next.length + 1}`, text: '', correct: false });
  // A choice question with no marked answer would export an empty answer key.
  if (next.length && !next.some((option) => option.correct)) next[0] = { ...next[0], correct: true };
  return next;
}

/** Points are quarters at the finest, so two decimals always represent them exactly. */
function roundPoints(total: number): number {
  return Math.round(total * 100) / 100;
}

/**
 * The paper's total mark.
 *
 * Sections are skipped: a section's mark IS the sum of its sub-questions, so counting
 * both would double every grouped exercise.
 */
export function examTotalPoints(questions: Array<Pick<ExamQuestion, 'points' | 'type'>>): number {
  return roundPoints(
    questions.reduce(
      (sum, question) => (isExamSection(question.type) || !Number.isFinite(question.points) ? sum : sum + question.points),
      0
    )
  );
}

export interface ExamNumberedQuestion {
  question: ExamQuestion;
  /** `3` for a standalone question, `3.2` for the second one inside section 3. */
  number: string;
}

/**
 * One printed exercise: either a lone question, or a section statement with the
 * sub-questions that hang from it.
 */
export interface ExamBlock {
  /** The shared statement, or null when this block is a single top-level question. */
  section: ExamQuestion | null;
  /** The exercise number the paper prints (`1`, `2`, …). */
  number: string;
  questions: ExamNumberedQuestion[];
  /** What the exercise is worth: the sum of its sub-questions. */
  points: number;
}

/**
 * Turns the flat stored list into the nested structure everything renders from.
 *
 * Numbering is decided HERE and nowhere else, so the builder, the preview, the PDF, the
 * Word file and the answer key can never disagree about what "question 3.2" refers to.
 * Orphans (a sub-question whose section was deleted out from under it) are promoted to
 * top level rather than dropped, so no content can silently vanish from a paper.
 */
export function groupExamQuestions(questions: ExamQuestion[]): ExamBlock[] {
  const sorted = [...questions].sort((a, b) => a.position - b.position);
  const sectionIds = new Set(sorted.filter((question) => isExamSection(question.type)).map((question) => question.id));
  const childrenBySection = new Map<string, ExamQuestion[]>();
  for (const question of sorted) {
    if (isExamSection(question.type)) continue;
    if (question.parentId && sectionIds.has(question.parentId)) {
      const bucket = childrenBySection.get(question.parentId) ?? [];
      bucket.push(question);
      childrenBySection.set(question.parentId, bucket);
    }
  }

  const blocks: ExamBlock[] = [];
  let counter = 0;
  for (const question of sorted) {
    const isChild = !isExamSection(question.type) && question.parentId != null && sectionIds.has(question.parentId);
    if (isChild) continue;
    counter += 1;
    const number = String(counter);
    if (isExamSection(question.type)) {
      const children = childrenBySection.get(question.id) ?? [];
      blocks.push({
        section: question,
        number,
        questions: children.map((child, index) => ({ question: child, number: `${number}.${index + 1}` })),
        points: examTotalPoints(children),
      });
    } else {
      blocks.push({ section: null, number, questions: [{ question, number }], points: examTotalPoints([question]) });
    }
  }
  return blocks;
}

/** Every question in printing order, paired with the number the paper shows. */
export function flattenExamBlocks(blocks: ExamBlock[]): ExamNumberedQuestion[] {
  return blocks.flatMap((block) => block.questions);
}

/**
 * Split `total` across `count` sub-questions in quarter-point steps, giving the
 * remainder to the first ones — so 5 points over 3 questions reads 1.75 / 1.75 / 1.5
 * rather than 1.6666 repeating, which no teacher would write on a paper.
 */
export function distributeSectionPoints(total: number, count: number): number[] {
  if (count <= 0) return [];
  // A non-finite total is an empty or half-typed field, not a request to zero the
  // exercise: `Math.max(0, NaN)` is NaN, and it propagated into every sub-question.
  if (!Number.isFinite(total)) return [];
  const quarters = Math.max(0, Math.round(total * 4));
  const base = Math.floor(quarters / count);
  const remainder = quarters - base * count;
  return Array.from({ length: count }, (_, index) => (base + (index < remainder ? 1 : 0)) / 4);
}

/** Ruled lines the printed paper leaves for a question. */
export function examAnswerLines(question: Pick<ExamQuestion, 'type' | 'answerLines'>): number {
  if (question.answerLines != null && Number.isFinite(question.answerLines)) return Math.max(0, Math.min(40, Math.round(question.answerLines)));
  return examQuestionTypeDef(question.type).answerLines;
}

export function renumberExamQuestions<T extends { position: number }>(questions: T[]): T[] {
  return questions.map((question, index) => ({ ...question, position: index }));
}

/** Move a question and return the reordered ids, for the repo to persist. */
export function moveExamQuestion(ids: string[], from: number, to: number): string[] {
  if (from < 0 || from >= ids.length) return ids.slice();
  const target = Math.max(0, Math.min(ids.length - 1, to));
  const next = ids.slice();
  const [moved] = next.splice(from, 1);
  next.splice(target, 0, moved);
  return next;
}

export interface ExamIssue {
  questionId?: string;
  field: 'subject' | 'prompt' | 'options' | 'pairs' | 'items' | 'image' | 'count' | 'points' | 'section';
  /** Spanish source string, translated through t() in the UI. */
  message: string;
}

/**
 * Everything that would make the exported paper wrong or unusable. The builder shows
 * these inline and blocks export until they're clear, so a teacher never prints a
 * question with empty options or a missing image.
 */
export function validateExam(exam: TeachingExam, questions: ExamQuestion[]): ExamIssue[] {
  const issues: ExamIssue[] = [];
  if (!exam.subjectId) issues.push({ field: 'subject', message: 'Elige la asignatura del examen.' });
  if (!questions.length) issues.push({ field: 'count', message: 'Añade al menos una pregunta.' });
  // A section with nothing under it prints a statement nobody is asked to answer.
  for (const block of groupExamQuestions(questions)) {
    if (block.section && !block.questions.length) {
      issues.push({ questionId: block.section.id, field: 'section', message: 'Añade al menos una pregunta dentro del enunciado.' });
    }
  }
  for (const question of questions) {
    const def = examQuestionTypeDef(question.type);
    if (!question.prompt.trim()) issues.push({ questionId: question.id, field: 'prompt', message: 'Escribe el enunciado o genéralo con IA.' });
    // A section carries no mark of its own, so there is nothing to check.
    if (def.isSection) continue;
    if (!Number.isFinite(question.points) || question.points < 0) issues.push({ questionId: question.id, field: 'points', message: 'La puntuación debe ser un número positivo.' });
    if (def.needsOptions) {
      const filled = question.options.filter((option) => option.text.trim());
      if (filled.length < 2) issues.push({ questionId: question.id, field: 'options', message: 'Escribe al menos dos opciones.' });
    }
    if (def.needsPairs) {
      const filled = question.pairs.filter((pair) => pair.left.trim() && pair.right.trim());
      if (filled.length < 2) issues.push({ questionId: question.id, field: 'pairs', message: 'Escribe al menos dos parejas para relacionar.' });
    }
    if (def.needsItems) {
      const filled = question.items.filter((item) => item.trim());
      if (filled.length < 2) issues.push({ questionId: question.id, field: 'items', message: 'Escribe al menos dos elementos para ordenar.' });
    }
    if (def.needsImage && !question.imageDataUrl) issues.push({ questionId: question.id, field: 'image', message: 'Inserta la imagen que hay que comentar.' });
  }
  return issues;
}

/**
 * Labels printed on the document. These follow the EXAM's language, not the
 * interface language: a teacher with an English UI still prints a Spanish exam.
 * Kept as in-data tables (not i18n keys) for exactly that reason.
 */
export interface ExamDocumentLabels {
  studentName: string;
  studentId: string;
  group: string;
  date: string;
  grade: string;
  /** Plural form ("puntos"). */
  points: string;
  /** Singular form ("punto") — a question worth exactly 1 must not read "1 puntos". */
  point: string;
  duration: string;
  minutes: string;
  instructions: string;
  question: string;
  total: string;
  answerKey: string;
  trueLabel: string;
  falseLabel: string;
  columnA: string;
  columnB: string;
}

const DOCUMENT_LABELS: Record<ExamLanguage, ExamDocumentLabels> = {
  es: { studentName: 'Nombre y apellidos', studentId: 'DNI / Nº de expediente', group: 'Grupo', date: 'Fecha', grade: 'Calificación', points: 'puntos', point: 'punto', duration: 'Duración', minutes: 'minutos', instructions: 'Instrucciones', question: 'Pregunta', total: 'Total', answerKey: 'Solucionario', trueLabel: 'Verdadero', falseLabel: 'Falso', columnA: 'Columna A', columnB: 'Columna B' },
  en: { studentName: 'Name and surname', studentId: 'Student ID', group: 'Group', date: 'Date', grade: 'Grade', points: 'points', point: 'point', duration: 'Duration', minutes: 'minutes', instructions: 'Instructions', question: 'Question', total: 'Total', answerKey: 'Answer key', trueLabel: 'True', falseLabel: 'False', columnA: 'Column A', columnB: 'Column B' },
  fr: { studentName: 'Nom et prénom', studentId: 'Numéro d’étudiant', group: 'Groupe', date: 'Date', grade: 'Note', points: 'points', point: 'point', duration: 'Durée', minutes: 'minutes', instructions: 'Consignes', question: 'Question', total: 'Total', answerKey: 'Corrigé', trueLabel: 'Vrai', falseLabel: 'Faux', columnA: 'Colonne A', columnB: 'Colonne B' },
  de: { studentName: 'Name und Nachname', studentId: 'Matrikelnummer', group: 'Gruppe', date: 'Datum', grade: 'Note', points: 'Punkte', point: 'Punkt', duration: 'Dauer', minutes: 'Minuten', instructions: 'Hinweise', question: 'Aufgabe', total: 'Gesamt', answerKey: 'Lösungsschlüssel', trueLabel: 'Wahr', falseLabel: 'Falsch', columnA: 'Spalte A', columnB: 'Spalte B' },
  pt: { studentName: 'Nome e apelidos', studentId: 'Nº de estudante', group: 'Turma', date: 'Data', grade: 'Classificação', points: 'pontos', point: 'ponto', duration: 'Duração', minutes: 'minutos', instructions: 'Instruções', question: 'Pergunta', total: 'Total', answerKey: 'Soluções', trueLabel: 'Verdadeiro', falseLabel: 'Falso', columnA: 'Coluna A', columnB: 'Coluna B' },
  'pt-BR': { studentName: 'Nome e sobrenome', studentId: 'Matrícula', group: 'Turma', date: 'Data', grade: 'Nota', points: 'pontos', point: 'ponto', duration: 'Duração', minutes: 'minutos', instructions: 'Instruções', question: 'Questão', total: 'Total', answerKey: 'Gabarito', trueLabel: 'Verdadeiro', falseLabel: 'Falso', columnA: 'Coluna A', columnB: 'Coluna B' },
};

export function normalizeExamLanguage(value: unknown): ExamLanguage {
  return (EXAM_LANGUAGES as readonly string[]).includes(value as string) ? (value as ExamLanguage) : 'es';
}

export function examDocumentLabels(language: unknown): ExamDocumentLabels {
  return DOCUMENT_LABELS[normalizeExamLanguage(language)];
}

/** `1,5 puntos` in Spanish, `1.5 points` in English — the separator follows the doc. */
export function formatExamPoints(points: number, language: ExamLanguage): string {
  const labels = examDocumentLabels(language);
  const rounded = Math.round(points * 100) / 100;
  const text = Number.isInteger(rounded)
    ? String(rounded)
    : rounded.toFixed(2).replace(/0$/, '').replace('.', language === 'en' ? '.' : ',');
  // "1 punto", but "0,5 puntos" and "2 puntos" — only exactly one takes the singular.
  return `${text} ${rounded === 1 ? labels.point : labels.points}`;
}

/** The letter shown next to a multiple-choice option (a), b), c)…). */
export function examOptionLetter(index: number): string {
  return String.fromCharCode(97 + (index % 26));
}

/* ------------------------------------------------- AI + export contracts ---- */
// Type-only import: erased at runtime, so this module stays dependency-free.
import type { ModelRef } from './types';

export interface ExamQuestionGenerationRequest {
  type: ExamQuestionType;
  /** The teacher's instruction, e.g. "sobre la Revolución Industrial, nivel 2º ESO". */
  instruction: string;
  subjectId?: string | null;
  courseId?: string | null;
  topicId?: string | null;
  language: ExamLanguage;
  /** Multiple choice only. */
  optionCount?: number;
  /** Passed when regenerating, so the model produces something different. */
  avoidPrompt?: string;
  model?: ModelRef | null;
}

export interface ExamQuestionGenerationResult {
  question: ExamQuestionInput;
  model: ModelRef;
  /** How many material chunks were used as evidence; 0 means it wrote from scratch. */
  sourceCount: number;
}

/**
 * The language the DOCUMENT is written in: the teacher's explicit choice once they have
 * made one, otherwise whatever the interface is currently set to.
 */
export function effectiveExamLanguage(
  exam: Pick<TeachingExam, 'language' | 'languageLocked'>,
  interfaceLanguage: unknown
): ExamLanguage {
  return exam.languageLocked ? normalizeExamLanguage(exam.language) : normalizeExamLanguage(interfaceLanguage);
}

/**
 * What goes in the downloaded file:
 *  - `exam`        the blank paper the students sit
 *  - `examWithKey` the same paper followed by the marking key
 *  - `keyOnly`     just the key, for the person marking
 */
export const EXAM_EXPORT_CONTENTS = ['exam', 'examWithKey', 'keyOnly'] as const;
export type ExamExportContent = (typeof EXAM_EXPORT_CONTENTS)[number];

export interface ExamExportOptions {
  content?: ExamExportContent;
  /** @deprecated superseded by `content`; kept so older callers still work. */
  includeAnswerKey?: boolean;
}

/** Normalise the two ways callers can ask for the key. */
export function examExportContent(options: ExamExportOptions | undefined): ExamExportContent {
  if (options?.content && (EXAM_EXPORT_CONTENTS as readonly string[]).includes(options.content)) return options.content;
  return options?.includeAnswerKey ? 'examWithKey' : 'exam';
}

export type ExamExportFormat = 'docx' | 'pdf';

export interface ExamImagePick {
  dataUrl: string;
  name: string;
}

/** A logo kept in the vault's reusable library, ready to stamp on any exam. */
export interface TeachingLogo {
  id: string;
  shortId: string;
  name: string;
  dataUrl: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Logos are downscaled on import to this longest edge before being stored. A crest
 * printed 110px wide needs nothing bigger, and it keeps a 12 MP phone photo from
 * turning into a multi-megabyte base64 string inside every exported document.
 */
export const LOGO_MAX_EDGE = 512;
