/** Complete Italian catalogue; generated once and committed for offline use. */
export const TREE_KINSHIP_ROLE_LABEL_IT: Record<string, string> = {
  "focus": "Concentrarsi sulla persona",
  "father": "Padre",
  "mother": "Madre",
  "parent": "Genitore",
  "grandfather": "Nonno",
  "grandmother": "Nonna",
  "grandparent": "Nonno",
  "paternal_grandfather": "Nonno paterno",
  "paternal_grandmother": "Nonna paterna",
  "paternal_grandparent": "Nonno paterno",
  "maternal_grandfather": "Nonno materno",
  "maternal_grandmother": "Nonna materna",
  "maternal_grandparent": "Nonno materno",
  "great_grandfather": "Bisnonno",
  "great_grandmother": "Bisnonna",
  "great_grandparent": "Bisnonno",
  "great_great_grandfather": "Trisavolo",
  "great_great_grandmother": "Trisnonna",
  "great_great_grandparent": "Trisnonno",
  "paternal_ancestor": "Antenato paterno",
  "maternal_ancestor": "Antenato materno",
  "ancestor": "Antenato",
  "brother": "Fratello",
  "sister": "Sorella",
  "sibling": "Fratello",
  "husband": "Marito",
  "wife": "Moglie",
  "spouse": "Coniuge/partner",
  "son": "Figlio",
  "daughter": "Figlia",
  "child": "Bambino",
  "grandson": "Nipote",
  "granddaughter": "Nipote",
  "grandchild": "Nipote",
  "great_grandson": "Pronipote",
  "great_granddaughter": "Pronipote",
  "great_grandchild": "Pronipote",
  "great_great_grandson": "Pronipote",
  "great_great_granddaughter": "Pronipote",
  "great_great_grandchild": "Pronipote",
  "paternal_uncle": "Zio paterno",
  "paternal_aunt": "Zia paterna",
  "maternal_uncle": "Zio materno",
  "maternal_aunt": "Zia materna",
  "uncle_aunt": "Zio/zia",
  "paternal_granduncle": "Prozio paterno",
  "paternal_grandaunt": "Prozio paterno",
  "maternal_granduncle": "Prozio materno",
  "maternal_grandaunt": "Prozio materno",
  "granduncle_aunt": "Prozio/prozio",
  "great_granduncle": "Proprozio",
  "great_grandaunt": "Pronipote",
  "great_granduncle_aunt": "Proprozio/proprozio",
  "nephew": "nipote",
  "niece": "Nipote",
  "nibling": "Nipote/nipote",
  "grandnephew": "Nipote",
  "grandniece": "Nipote",
  "grandnibling": "Nipote/nipote",
  "great_grandnephew": "Pronipote",
  "great_grandniece": "Pronipote",
  "great_grandnibling": "Pronipote/pronipote",
  "male_cousin": "Cugino maschio",
  "female_cousin": "Cugina femmina",
  "cousin": "Cugino",
  "father_in_law": "Suocero",
  "mother_in_law": "Suocera",
  "parent_in_law": "Suocero",
  "son_in_law": "Genero",
  "daughter_in_law": "Nuora",
  "child_in_law": "Nuora",
  "brother_in_law": "Cognato",
  "sister_in_law": "Cognata",
  "sibling_in_law": "Cognato",
  "stepfather": "Patrigno",
  "stepmother": "Matrigna",
  "stepparent": "Genitore acquisito",
  "stepson": "Figliastro",
  "stepdaughter": "Figliastra",
  "stepchild": "Figliastro",
  "co_parent": "Co-genitore",
  "descendant": "Discendente",
  "relative_by_marriage": "Parente per matrimonio",
  "connected_relative": "Collegamento familiare",
  "unrelated": "Nessuna parentela registrata",
};
