import React from 'react';
import ReactDOM from 'react-dom/client';
import type { NodusApi } from '../shared/types';
import type { PrimarySourceArchiveWorkspace } from '../shared/primarySourcesTypes';
import { PrimarySourcesArchiveView } from '../src/views/PrimarySourcesArchiveView';
import '../src/index.css';

const createdAt = '2026-07-29T10:00:00.000Z';
const unitBase = {
  localLevelLabel: null,
  titleType: 'formal' as const,
  date: { display: null, startSort: null, endSort: null, certainty: 'unknown' as const },
  creatorDisplay: null,
  extentDisplay: null,
  scopeContent: null,
  arrangement: null,
  administrativeBiographicalHistory: null,
  custodialHistory: null,
  acquisitionInfo: null,
  accessConditions: null,
  reproductionConditions: null,
  languageCodes: ['es'],
  scriptCodes: ['Latn'],
  physicalCharacteristics: null,
  findingAids: null,
  relatedUnits: null,
  sourceCatalogUrl: null,
  metadata: {},
  createdAt,
  updatedAt: createdAt,
};
const fonds = {
  ...unitBase,
  unitId: 'fonds',
  repositoryId: 'repo',
  parentUnitId: null,
  level: 'fonds' as const,
  referenceCode: 'AMPC/FPC',
  title: 'Fondo Familia del Puerto',
  position: 0,
};
const series = {
  ...unitBase,
  unitId: 'series',
  repositoryId: 'repo',
  parentUnitId: 'fonds',
  level: 'series' as const,
  referenceCode: 'AMPC/FPC/1',
  title: 'Correspondencia',
  position: 0,
};
const itemUnit = {
  ...unitBase,
  unitId: 'item-letter',
  repositoryId: 'repo',
  parentUnitId: 'series',
  level: 'item' as const,
  referenceCode: 'AMPC/FPC/1/3',
  title: 'Carta de María López a Juan García',
  creatorDisplay: 'María López',
  date: { display: 'hacia mayo de 1892', startSort: '1892-05-01', endSort: '1892-05-31', certainty: 'circa' as const },
  scopeContent: 'Carta relativa a una epidemia y al traslado de suministros.',
  position: 0,
};
const photoUnit = {
  ...unitBase,
  unitId: 'item-photo',
  repositoryId: 'repo',
  parentUnitId: 'series',
  level: 'item' as const,
  referenceCode: 'AMPC/FPC/1/9',
  title: 'Retrato del personal del puerto',
  creatorDisplay: 'Fotógrafo desconocido',
  date: { display: 'ca. 1895', startSort: '1895', endSort: '1895', certainty: 'circa' as const },
  position: 1,
};
const profileBase = {
  dateCertainty: 'circa' as const,
  embargoUntil: null,
  rightsStatement: null,
  reproductionConditions: null,
  processingStatus: 'ready' as const,
  descriptionStatus: 'described' as const,
  analysisStatus: 'draft' as const,
  citationStatus: 'general_locator' as const,
  captureSessionId: 'session',
  metadata: {},
  createdAt,
  updatedAt: createdAt,
};
const itemBase = {
  folderId: null,
  kind: 'image' as const,
  mimeType: 'image/tiff',
  bytes: 4_200_000,
  hasBlob: true,
  extractedText: null,
  description: null,
  source: null,
  contentHash: 'hash',
  docType: null,
  metadata: null,
  year: null,
  linkedPersons: [],
  tags: [],
  folderIds: ['collection'],
  hasEmbedding: false,
  createdAt,
  updatedAt: createdAt,
};

const workspace: PrimarySourceArchiveWorkspace = {
  repositories: [{
    repositoryId: 'repo',
    name: 'Archivo Municipal de Puerto Claro',
    shortName: 'AMPC',
    identifier: 'AMPC',
    address: null,
    websiteUrl: null,
    catalogUrl: null,
    countryCode: 'ES',
    contactNotes: null,
    accessNotes: null,
    citationTemplate: null,
    createdAt,
    updatedAt: createdAt,
  }],
  units: [fonds, series, itemUnit, photoUnit],
  sessions: [{
    sessionId: 'session',
    repositoryId: 'repo',
    title: 'Consulta de julio',
    sessionKind: 'consultation',
    startedOn: '2026-07-08',
    endedOn: '2026-07-10',
    researcher: 'Investigadora',
    device: null,
    fondsScope: null,
    referenceScope: null,
    reproductionTerms: null,
    namingPattern: null,
    notes: null,
    createdAt,
    updatedAt: createdAt,
  }],
  collections: [{ folderId: 'collection', name: 'Epidemias y sanidad', parentId: null, createdAt }],
  templates: [],
  rows: [
    {
      item: {
        ...itemBase,
        itemId: 'letter',
        title: itemUnit.title,
        fileName: 'AMPC_FPC_1_3_001.tif',
        extractedText: 'Mi estimado Juan: el cólera ha llegado al puerto.',
      },
      unit: itemUnit,
      profile: {
        ...profileBase,
        itemId: 'letter',
        accessStatus: 'open',
        sensitivity: 'normal',
      },
      repositoryName: 'Archivo Municipal de Puerto Claro',
      masterCount: 1,
      derivativeCount: 2,
      textVersionCount: 2,
      revision: 'revision-letter',
    },
    {
      item: {
        ...itemBase,
        itemId: 'photo',
        title: photoUnit.title,
        fileName: 'personal_puerto_1895.tif',
      },
      unit: photoUnit,
      profile: {
        ...profileBase,
        itemId: 'photo',
        accessStatus: 'restricted',
        sensitivity: 'personal',
      },
      repositoryName: 'Archivo Municipal de Puerto Claro',
      masterCount: 1,
      derivativeCount: 1,
      textVersionCount: 0,
      revision: 'revision-photo',
    },
  ],
};

const mockMaster = {
  fileId: 'master-letter-v1',
  itemId: 'letter',
  parentFileId: null,
  role: 'master' as const,
  versionNo: 1,
  sequenceNo: 0,
  pageLabel: 'Placa 1',
  originalFileName: 'AMPC_FPC_1_3_001.tif',
  mimeType: 'image/tiff',
  byteSize: 4_200_000,
  hasContent: true,
  externalPath: null,
  contentHash: 'c4d3d67c8b9d12c3e9f4a21f6f87c03e1e5f69af8473d98e59c6fc98f4079f1c',
  hashAlgorithm: 'sha256' as const,
  transformation: null,
  captureMetadata: { device: 'Cámara cenital' },
  createdBy: 'Investigadora',
  createdAt,
  verifiedAt: createdAt,
  verificationStatus: 'verified' as const,
  supersededAt: null,
};

const diplomaticText = `Mi estimado Juan:

El cólera ha llegado al puerto. Ayer fueron trasladadas doce cajas de medicinas al lazareto.

Te ruego comuniques al alcalde que la situación es urgente, aunque todavía conservamos agua limpia.`;

const mockDossier = (itemId: string) => {
  const row = workspace.rows.find((candidate) => candidate.item.itemId === itemId) ?? workspace.rows[0];
  const file = { ...mockMaster, itemId: row.item.itemId, originalFileName: row.item.fileName };
  const automatic = {
    textVersionId: `ocr-${itemId}`,
    itemId,
    fileId: file.fileId,
    parentVersionId: null,
    kind: 'ocr' as const,
    languageCode: 'es',
    content: diplomaticText.replace('doce', 'dose'),
    status: 'automatic' as const,
    engine: 'Tesseract',
    model: null,
    confidence: 0.91,
    editorialConventions: null,
    createdBy: 'OCR local',
    createdAt: '2026-07-29T09:00:00.000Z',
    updatedAt: '2026-07-29T09:00:00.000Z',
    reviewedAt: null,
  };
  const reviewed = {
    ...automatic,
    textVersionId: `diplomatic-${itemId}`,
    parentVersionId: automatic.textVersionId,
    kind: 'diplomatic' as const,
    content: diplomaticText,
    status: 'in_review' as const,
    engine: null,
    confidence: null,
    editorialConventions: 'Ortografía y puntuación conservadas; correcciones evidentes documentadas.',
    createdBy: 'Investigadora',
    createdAt,
    updatedAt: createdAt,
  };
  const firstEnd = diplomaticText.indexOf('\n\n');
  const secondStart = firstEnd + 2;
  return {
    row,
    files: [file],
    textVersions: row.item.itemId === 'letter' ? [reviewed, automatic] : [],
    textSegments: row.item.itemId === 'letter' ? [{
      segmentId: 'segment-letter-1',
      textVersionId: reviewed.textVersionId,
      fileId: file.fileId,
      sequenceNo: 0,
      pageLabel: 'fol. 3r',
      startOffset: 0,
      endOffset: firstEnd,
      content: diplomaticText.slice(0, firstEnd),
      bbox: null,
      timeStartMs: null,
      timeEndMs: null,
      confidence: null,
      createdAt,
      updatedAt: createdAt,
    }, {
      segmentId: 'segment-letter-2',
      textVersionId: reviewed.textVersionId,
      fileId: file.fileId,
      sequenceNo: 1,
      pageLabel: 'fol. 3v',
      startOffset: secondStart,
      endOffset: diplomaticText.length,
      content: diplomaticText.slice(secondStart),
      bbox: null,
      timeStartMs: null,
      timeEndMs: null,
      confidence: null,
      createdAt,
      updatedAt: createdAt,
    }] : [],
    excerpts: row.item.itemId === 'letter' ? [{
      excerptId: 'excerpt-letter-1',
      itemId,
      fileId: file.fileId,
      textVersionId: reviewed.textVersionId,
      segmentId: 'segment-letter-2',
      locatorDisplay: 'fol. 3v, líneas 2–3',
      locator: {
        pageLabel: 'fol. 3v',
        segmentId: 'segment-letter-2',
        textRange: {
          start: diplomaticText.indexOf('Ayer'),
          end: diplomaticText.indexOf('lazareto.') + 'lazareto.'.length,
        },
      },
      quotedText: 'Ayer fueron trasladadas doce cajas de medicinas al lazareto.',
      languageCode: 'es',
      description: 'Traslado de suministros durante la epidemia.',
      reviewStatus: 'reviewed' as const,
      createdBy: 'Investigadora',
      createdAt,
      updatedAt: createdAt,
    }] : [],
    analysis: row.item.itemId === 'letter' ? {
      analysisId: 'analysis-letter',
      itemId,
      originNotes: 'Carta conservada en el fondo familiar; ingreso por donación en 1981.',
      purposeAudience: 'Comunicación privada dirigida a un familiar con acceso al gobierno municipal.',
      contentForm: 'Carta personal manuscrita.',
      perspectiveBias: 'La autora observa la crisis desde el entorno portuario y prioriza la logística.',
      silencesLimits: 'No incorpora la experiencia de pacientes ni cifras sanitarias completas.',
      authenticityNotes: 'Papel, tinta y sello postal compatibles con la fecha atribuida.',
      representativeness: null,
      corroboration: 'El traslado se menciona también en el libro de actas municipal.',
      questions: 'Localizar el parte médico de la misma semana.',
      status: 'draft' as const,
      createdAt,
      updatedAt: createdAt,
    } : null,
    proposals: row.item.itemId === 'letter' ? [{
      proposalId: 'proposal-person-1',
      itemId,
      excerptId: 'excerpt-letter-1',
      proposalKind: 'person' as const,
      payload: {
        displayName: 'Joaquín Varela',
        originalLabel: 'Joaquín Varela',
        sex: 'male',
        quote: 'Mi querido Joaquín',
        location: 'fol. 3r, línea 1',
      },
      matchedTargetId: 'person-existing-1',
      status: 'pending' as const,
      confidence: 0.94,
      rationale: 'explicit_person_mention',
      sourceEngine: 'openai',
      sourceModel: 'gpt-5-mini',
      fingerprint: 'fingerprint-person',
      createdAt,
      reviewedAt: null,
      reviewedBy: null,
      decisionNote: null,
    }, {
      proposalId: 'proposal-place-1',
      itemId,
      excerptId: 'excerpt-letter-1',
      proposalKind: 'place' as const,
      payload: {
        name: 'Cádiz',
        originalLabel: 'Cádiz',
        kind: 'municipality',
        quote: 'Aquí en Cádiz',
        location: 'fol. 3r, línea 2',
      },
      matchedTargetId: 'place-existing-1',
      status: 'pending' as const,
      confidence: 0.9,
      rationale: 'explicit_place_mention',
      sourceEngine: 'openai',
      sourceModel: 'gpt-5-mini',
      fingerprint: 'fingerprint-place',
      createdAt,
      reviewedAt: null,
      reviewedBy: null,
      decisionNote: null,
    }, {
      proposalId: 'proposal-relation-1',
      itemId,
      excerptId: 'excerpt-letter-1',
      proposalKind: 'relation' as const,
      payload: {
        subject: 'Joaquín Varela',
        subjectTargetId: 'person-existing-1',
        relation: 'father',
        object: 'Elena Varela',
        objectTargetId: null,
        quote: 'Joaquín, padre de Elena',
        location: 'fol. 3v, línea 1',
      },
      matchedTargetId: null,
      status: 'pending' as const,
      confidence: 0.86,
      rationale: 'explicit_kinship_claim',
      sourceEngine: 'openai',
      sourceModel: 'gpt-5-mini',
      fingerprint: 'fingerprint-relation',
      createdAt,
      reviewedAt: null,
      reviewedBy: null,
      decisionNote: null,
    }, {
      proposalId: 'proposal-event-accepted',
      itemId,
      excerptId: 'excerpt-letter-1',
      proposalKind: 'event' as const,
      payload: { type: 'other', label: 'Traslado de medicinas', date: '18 de agosto de 1894' },
      matchedTargetId: null,
      status: 'accepted' as const,
      confidence: 0.92,
      rationale: 'explicit_event',
      sourceEngine: 'openai',
      sourceModel: 'gpt-5-mini',
      fingerprint: 'fingerprint-event',
      createdAt,
      reviewedAt: createdAt,
      reviewedBy: 'Investigadora',
      decisionNote: 'Fecha comprobada.',
    }] : [],
    proposalDecisions: row.item.itemId === 'letter' ? [{
      decisionId: 'decision-event-accepted',
      proposalId: 'proposal-event-accepted',
      itemId,
      decision: 'accepted' as const,
      originalPayload: { type: 'other', label: 'Traslado de medicinas', date: '18 agosto 1894' },
      decidedPayload: { type: 'other', label: 'Traslado de medicinas', date: '18 de agosto de 1894' },
      matchedTargetId: null,
      materializedTargetKind: 'event' as const,
      materializedTargetId: 'event-accepted-1',
      evidenceId: 'evidence-event-1',
      evidenceRole: 'supports' as const,
      reviewer: 'Investigadora',
      note: 'Fecha comprobada.',
      createdAt,
    }] : [],
    proposalCandidates: row.item.itemId === 'letter' ? [{
      proposalId: 'proposal-person-1',
      candidates: [{
        field: 'target' as const,
        targetKind: 'person' as const,
        targetId: 'person-existing-1',
        label: 'Joaquín Varela',
        detail: '1848 – 1910',
        match: 'exact' as const,
      }],
    }, {
      proposalId: 'proposal-place-1',
      candidates: [{
        field: 'target' as const,
        targetKind: 'place' as const,
        targetId: 'place-existing-1',
        label: 'Cádiz',
        detail: 'Andalucía, España',
        match: 'exact' as const,
      }],
    }, {
      proposalId: 'proposal-relation-1',
      candidates: [{
        field: 'subject' as const,
        targetKind: 'person' as const,
        targetId: 'person-existing-1',
        label: 'Joaquín Varela',
        detail: '1848 – 1910',
        match: 'exact' as const,
      }, {
        field: 'object' as const,
        targetKind: 'person' as const,
        targetId: 'person-existing-2',
        label: 'Elena Varela',
        detail: '1876 – 1944',
        match: 'exact' as const,
      }],
    }] : [],
    evidence: row.item.itemId === 'letter' ? [{
      evidenceId: 'evidence-event-1',
      targetKind: 'event' as const,
      targetId: 'event-accepted-1',
      itemId,
      excerptId: 'excerpt-letter-1',
      evidenceRole: 'supports' as const,
      certainty: 0.92,
      reviewStatus: 'reviewed' as const,
      sourceVersionId: reviewed.textVersionId,
      quote: 'Ayer fueron trasladadas doce cajas de medicinas al lazareto.',
      location: 'fol. 3v, líneas 2–3',
      createdBy: 'Investigadora',
      createdAt,
      updatedAt: createdAt,
    }, {
      evidenceId: 'evidence-contradiction-1',
      targetKind: 'event' as const,
      targetId: 'event-older-1',
      itemId,
      excerptId: 'excerpt-letter-1',
      evidenceRole: 'contradicts' as const,
      certainty: 0.78,
      reviewStatus: 'reviewed' as const,
      sourceVersionId: reviewed.textVersionId,
      quote: 'La situación es urgente.',
      location: 'fol. 3v, línea 4',
      createdBy: 'Investigadora',
      createdAt,
      updatedAt: createdAt,
    }] : [],
    resolutions: row.item.itemId === 'letter' ? [{
      resolutionId: 'resolution-person-1',
      entityKind: 'person' as const,
      sourceEntityId: 'mention-person-1',
      targetEntityId: 'person-existing-1',
      decision: 'confirm' as const,
      rationale: 'Coincidencia exacta comprobada.',
      status: 'active' as const,
      createdBy: 'Investigadora',
      createdAt,
      revertedAt: null,
    }] : [],
    integrityChecks: [],
    history: [{
      eventId: `historic-${itemId}`,
      itemId,
      fileId: file.fileId,
      action: 'file_created' as const,
      details: { role: 'master', byteSize: file.byteSize, contentHash: file.contentHash },
      createdBy: 'Investigadora',
      createdAt,
    }],
    integrity: { verified: 1, pending: 0, missing: 0, mismatch: 0, error: 0, orphanDerivatives: 0, unhashed: 0 },
  };
};

const api = {
  getPrimarySourcesWorkspace: async () => workspace,
  getPrimarySourceDossier: async (itemId: string) => mockDossier(itemId),
  choosePrimarySourceFiles: async () => [],
  ingestPrimarySources: async () => ({ added: 0, duplicates: 0, rows: [] }),
  createPrimarySourceUnit: async () => itemUnit,
  createPrimarySourceRepository: async () => workspace.repositories[0],
  createPrimarySourceCaptureSession: async () => workspace.sessions[0],
  createPrimarySourceCollection: async () => workspace.collections[0],
  createPrimarySourceDescriptionTemplate: async () => workspace.templates[0],
  previewPrimarySourceBulkEdit: async (itemIds: string[]) => ({
    itemIds,
    affected: itemIds.length,
    missing: [],
    revisions: Object.fromEntries(itemIds.map((id) => [id, `revision-${id}`])),
    warnings: [],
  }),
  applyPrimarySourceBulkEdit: async () => workspace.rows,
  updatePrimarySourceArchiveRecord: async () => workspace.rows[0],
  addPrimarySourceFiles: async () => ({ added: [mockMaster], dossier: mockDossier('letter') }),
  updatePrimarySourceFileMetadata: async () => mockDossier('letter'),
  reorderPrimarySourceFileGroups: async () => mockDossier('letter'),
  verifyPrimarySourceFiles: async () => mockDossier('letter'),
  regeneratePrimarySourceThumbnail: async () => mockDossier('letter'),
  savePrimarySourceFile: async () => '/tmp/source.tif',
  openPrimarySourceFileExternal: async () => true,
  createPrimarySourceTextVersion: async () => mockDossier('letter'),
  setPrimarySourceTextReviewStatus: async () => mockDossier('letter'),
  createPrimarySourceExcerpt: async () => mockDossier('letter'),
  setPrimarySourceExcerptReviewStatus: async () => mockDossier('letter'),
  savePrimarySourceAnalysis: async () => mockDossier('letter'),
  extractPrimarySourceProposals: async () => ({
    result: { created: 0, reused: 4, proposals: mockDossier('letter').proposals, sourceEngine: 'openai', sourceModel: 'gpt-5-mini' },
    dossier: mockDossier('letter'),
  }),
  acceptPrimarySourceProposal: async () => ({
    result: {
      proposal: mockDossier('letter').proposals[3],
      decision: mockDossier('letter').proposalDecisions[0],
      evidence: mockDossier('letter').evidence[0],
      idempotent: false,
    },
    dossier: mockDossier('letter'),
  }),
  decidePrimarySourceProposal: async () => mockDossier('letter'),
  revertPrimarySourceEntityResolution: async () => mockDossier('letter'),
} as unknown as NodusApi;

window.nodus = api;
const dark = new URLSearchParams(window.location.search).get('theme') !== 'light';
document.documentElement.classList.toggle('dark', dark);
document.documentElement.classList.toggle('light', !dark);

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <div style={{ height: '100vh' }}>
      <PrimarySourcesArchiveView />
    </div>
  </React.StrictMode>
);
