import { createRequire } from 'node:module';
import path from 'node:path';
import { _electron as electron } from 'playwright-core';
import { fileURLToPath } from 'node:url';
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const require = createRequire(path.join(repoRoot, 'package.json'));
const env = { ...process.env, NODUS_USERDATA: path.join(repoRoot, '.tutorial-out/nodi/profile'), NODUS_DISABLE_AUTO_UPDATE: '1', NODUS_E2E_UPDATE_STATUS: 'not-available' };
delete env.ELECTRON_RUN_AS_NODE;
const app = await electron.launch({ executablePath: require('electron'), args: [repoRoot], env });
const page = await app.firstWindow();
await page.waitForFunction(() => Boolean(document.getElementById('root')?.children.length), { timeout: 30000 });
await page.evaluate(() => window.nodus.updateSettings({ uiLanguage: 'en', theme: 'light', basicsTutorialVersion: 9999, recoverySetupVersion: 9999 })).catch(()=>{});
await page.reload(); await page.waitForTimeout(3500);
await page.locator('[data-tour="nav-settings"], button[title="Settings"]').first().click().catch(()=>{});
await page.waitForTimeout(2500);
const inputs = await page.evaluate(() => [...document.querySelectorAll('input')].map(i => i.placeholder).filter(Boolean).slice(0,8));
console.log('placeholders:', JSON.stringify(inputs));
const tabs = await page.evaluate(() => [...document.querySelectorAll('button, a')].map(b => b.innerText?.trim()).filter(t => t && t.length < 24).slice(0, 30));
console.log('nav:', JSON.stringify(tabs));
const search = page.locator('input[placeholder*="ettings"], input[placeholder*="earch"]').first();
if (await search.isVisible().catch(()=>false)) { await search.fill('MCP'); await page.waitForTimeout(2000); }
console.log('card present:', await page.locator('[data-testid="mcp-settings-card"]').count());
console.log('server card:', await page.locator('[data-testid="nodus-server-settings-card"]').count());
// The testid wraps only the ChatGPT promo box; the real controls are its siblings.
const card = page.locator('section.card:has([data-testid="mcp-settings-card"])');
const boxes = card.locator('input[type="checkbox"]');
console.log('checkboxes in card:', await boxes.count(), 'first checked:', await boxes.first().isChecked().catch(e => 'ERR ' + e.message.split('\n')[0]));
await boxes.first().check({ timeout: 4000 }).then(() => console.log('check(): ok')).catch(e => console.log('check() FAILED:', e.message.split('\n')[0]));
await page.waitForTimeout(2500);
const labels = [];
const n = await card.locator('button').count();
for (let i = 0; i < n; i++) labels.push((await card.locator('button').nth(i).innerText().catch(()=>'')).replace(/\s+/g,' ').trim());
console.log('card buttons:', JSON.stringify(labels));
console.log('token:', ((await page.evaluate(async () => (await window.nodus.getSettings())?.mcpToken)) ?? '').length, 'chars');
const sb = page.locator('input[placeholder*="ettings"], input[placeholder*="earch"]').first();
await sb.fill('Nodus Server').catch(() => console.log('search box not reachable'));
await page.waitForTimeout(2000);
const sc = page.locator('section.card:has([data-testid="nodus-server-settings-card"])');
console.log('server section:', await sc.count());
const sn = await sc.locator('button').count().catch(()=>0);
const slabels = [];
for (let i = 0; i < sn; i++) slabels.push((await sc.locator('button').nth(i).innerText().catch(()=>'')).replace(/\s+/g,' ').trim());
console.log('server inputs:', JSON.stringify(await sc.locator('input').evaluateAll((ns) => ns.map((n) => n.placeholder || n.type))));
console.log('server buttons:', JSON.stringify(slabels));
await app.close();
