// Interface copy for capability packages. The packages themselves ship their own
// localized labels; these are the controls Nodus puts around them.
const rows = [
  ["Paquetes oficiales", "Official packages", "Paquets officiels", "Offizielle Pakete", "Pacotes oficiais", "Pacotes oficiais", "Pacchetti ufficiali", "Resmi paketler"],
  ["Publicados y firmados por NodusResearch. Cada paquete trae sus propias capabilities y su propia configuración.", "Published and signed by NodusResearch. Each package brings its own capabilities and its own settings.", "Publiés et signés par NodusResearch. Chaque paquet apporte ses propres capacités et ses propres réglages.", "Von NodusResearch veröffentlicht und signiert. Jedes Paket bringt eigene Capabilities und eigene Einstellungen mit.", "Publicados e assinados pela NodusResearch. Cada pacote traz as suas próprias capabilities e a sua própria configuração.", "Publicados e assinados pela NodusResearch. Cada pacote traz suas próprias capabilities e sua própria configuração.", "Pubblicati e firmati da NodusResearch. Ogni pacchetto porta le proprie capability e le proprie impostazioni.", "NodusResearch tarafından yayımlanır ve imzalanır. Her paket kendi capability’lerini ve kendi ayarlarını getirir."],
  ["Actualizar catálogo", "Refresh catalogue", "Actualiser le catalogue", "Katalog aktualisieren", "Atualizar catálogo", "Atualizar catálogo", "Aggiorna catalogo", "Kataloğu yenile"],
  ["Catálogo actualizado.", "Catalogue refreshed.", "Catalogue actualisé.", "Katalog aktualisiert.", "Catálogo atualizado.", "Catálogo atualizado.", "Catalogo aggiornato.", "Katalog yenilendi."],
  ["Actualiza el catálogo para ver los paquetes disponibles.", "Refresh the catalogue to see the available packages.", "Actualisez le catalogue pour voir les paquets disponibles.", "Aktualisiere den Katalog, um die verfügbaren Pakete zu sehen.", "Atualiza o catálogo para veres os pacotes disponíveis.", "Atualize o catálogo para ver os pacotes disponíveis.", "Aggiorna il catalogo per vedere i pacchetti disponibili.", "Kullanılabilir paketleri görmek için kataloğu yenileyin."],
  ["La actualización pide permisos nuevos. Revísalos y apruébala para instalarla.", "The update asks for new permissions. Review them and approve it to install.", "La mise à jour demande de nouvelles permissions. Examinez-les et approuvez-la pour l’installer.", "Das Update verlangt neue Berechtigungen. Prüfe sie und genehmige es zur Installation.", "A atualização pede permissões novas. Revê-as e aprova-a para instalar.", "A atualização pede novas permissões. Revise-as e aprove-a para instalar.", "L’aggiornamento chiede nuovi permessi. Esaminali e approvalo per installarlo.", "Güncelleme yeni izinler istiyor. Bunları inceleyip kurulum için onaylayın."],
  ["Capabilities", "Capabilities", "Capacités", "Capabilities", "Capabilities", "Capabilities", "Capability", "Capability’ler"],
  ["Plataformas", "Platforms", "Plateformes", "Plattformen", "Plataformas", "Plataformas", "Piattaforme", "Platformlar"],
  ["No instalado", "Not installed", "Non installé", "Nicht installiert", "Não instalado", "Não instalado", "Non installato", "Kurulu değil"],
  ["Aprobar permisos", "Approve permissions", "Approuver les permissions", "Berechtigungen genehmigen", "Aprovar permissões", "Aprovar permissões", "Approva i permessi", "İzinleri onayla"],
  ["Paquete instalado.", "Package installed.", "Paquet installé.", "Paket installiert.", "Pacote instalado.", "Pacote instalado.", "Pacchetto installato.", "Paket kuruldu."],
  ["Paquete actualizado.", "Package updated.", "Paquet mis à jour.", "Paket aktualisiert.", "Pacote atualizado.", "Pacote atualizado.", "Pacchetto aggiornato.", "Paket güncellendi."],
  ["Actualización aplicada.", "Update applied.", "Mise à jour appliquée.", "Update angewendet.", "Atualização aplicada.", "Atualização aplicada.", "Aggiornamento applicato.", "Güncelleme uygulandı."],
  ["Se ha vuelto a la versión anterior.", "Rolled back to the previous version.", "Retour à la version précédente.", "Auf die vorherige Version zurückgesetzt.", "Voltou à versão anterior.", "Voltou à versão anterior.", "Ripristinata la versione precedente.", "Önceki sürüme dönüldü."],
  ["Paquete desinstalado.", "Package uninstalled.", "Paquet désinstallé.", "Paket deinstalliert.", "Pacote desinstalado.", "Pacote desinstalado.", "Pacchetto disinstallato.", "Paket kaldırıldı."],
  ["¿Desinstalar este paquete? Los resultados que ya están en tus chats se conservan; sus credenciales se borran.", "Uninstall this package? Results already in your chats are kept; its credentials are deleted.", "Désinstaller ce paquet ? Les résultats déjà présents dans vos conversations sont conservés ; ses identifiants sont supprimés.", "Dieses Paket deinstallieren? Ergebnisse, die bereits in deinen Chats stehen, bleiben erhalten; seine Zugangsdaten werden gelöscht.", "Desinstalar este pacote? Os resultados que já estão nos teus chats mantêm-se; as suas credenciais são apagadas.", "Desinstalar este pacote? Os resultados que já estão nos seus chats são mantidos; suas credenciais são excluídas.", "Disinstallare questo pacchetto? I risultati già presenti nelle chat restano; le sue credenziali vengono eliminate.", "Bu paket kaldırılsın mı? Sohbetlerinizde bulunan sonuçlar korunur; kimlik bilgileri silinir."],
  ["Configurada", "Configured", "Configurée", "Konfiguriert", "Configurada", "Configurada", "Configurata", "Yapılandırıldı"],
  ["Necesaria", "Required", "Requise", "Erforderlich", "Necessária", "Necessária", "Necessaria", "Gerekli"],
  ["Opcional", "Optional", "Facultative", "Optional", "Opcional", "Opcional", "Facoltativa", "İsteğe bağlı"],
  ["Leer los términos", "Read the terms", "Lire les conditions", "Bedingungen lesen", "Ler os termos", "Ler os termos", "Leggi i termini", "Koşulları okuyun"],
  ["El resultado de la capability no se pudo leer.", "The capability result could not be read.", "Le résultat de la capacité n’a pas pu être lu.", "Das Capability-Ergebnis konnte nicht gelesen werden.", "O resultado da capability não pôde ser lido.", "O resultado da capability não pôde ser lido.", "Non è stato possibile leggere il risultato della capability.", "Capability sonucu okunamadı."],
  ["Este resultado lo produjo un paquete que ya no está instalado.", "This result came from a package that is no longer installed.", "Ce résultat provient d’un paquet qui n’est plus installé.", "Dieses Ergebnis stammt aus einem Paket, das nicht mehr installiert ist.", "Este resultado veio de um pacote que já não está instalado.", "Este resultado veio de um pacote que não está mais instalado.", "Questo risultato proviene da un pacchetto che non è più installato.", "Bu sonuç, artık kurulu olmayan bir paketten geldi."],
  ["Reinstalar el paquete", "Reinstall the package", "Réinstaller le paquet", "Paket neu installieren", "Reinstalar o pacote", "Reinstalar o pacote", "Reinstalla il pacchetto", "Paketi yeniden kur"],
  ["El contenido guardado ya no coincide con su huella y no se puede mostrar.", "The stored content no longer matches its fingerprint and cannot be shown.", "Le contenu enregistré ne correspond plus à son empreinte et ne peut pas être affiché.", "Der gespeicherte Inhalt stimmt nicht mehr mit seinem Fingerabdruck überein und kann nicht angezeigt werden.", "O conteúdo guardado já não corresponde à sua impressão digital e não pode ser mostrado.", "O conteúdo salvo não corresponde mais à sua impressão digital e não pode ser exibido.", "Il contenuto salvato non corrisponde più alla sua impronta e non può essere mostrato.", "Saklanan içerik artık parmak iziyle eşleşmiyor ve gösterilemiyor."],
  ["El contenido guardado ya no está disponible.", "The stored content is no longer available.", "Le contenu enregistré n’est plus disponible.", "Der gespeicherte Inhalt ist nicht mehr verfügbar.", "O conteúdo guardado já não está disponível.", "O conteúdo salvo não está mais disponível.", "Il contenuto salvato non è più disponibile.", "Saklanan içerik artık mevcut değil."],
];
export const CAPABILITIES_TRANSLATIONS = Object.fromEntries(
  ['en', 'fr', 'de', 'pt', 'pt-BR', 'it', 'tr'].map((language, index) => [language, Object.fromEntries(rows.map(row => [row[0], row[index + 1]]))]),
) as Record<string, Record<string, string>>;
