#!/usr/bin/env node
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import { createServer } from 'node:http';
import { mkdir } from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { _electron as electron } from 'playwright-core';

import { prepareQaProfile } from './qa-paths.mjs';
import { writeNotionParityReport } from './report.mjs';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..'); const require = createRequire(import.meta.url); const marker = '--electron-loop-15';
if (!process.argv.includes(marker)) { execFileSync(path.join(repoRoot, 'node_modules/.bin/electron'), [fileURLToPath(import.meta.url), marker, ...process.argv.slice(2)], {
  cwd: repoRoot, env: { ...process.env, ELECTRON_RUN_AS_NODE: '1' }, stdio: 'inherit',
}); process.exit(0); }
const option = (name) => { const inline = process.argv.find((value) => value.startsWith(`--${name}=`)); if (inline) return inline.slice(name.length + 3); const index = process.argv.indexOf(`--${name}`); return index >= 0 ? process.argv[index + 1] : null; };
const retain = process.argv.includes('--retain'); const skipBuild = process.argv.includes('--skip-build'); const runId = `loop-15-${new Date().toISOString().replace(/[:.]/g,'-')}`;
const outputDir = path.resolve(option('output') ?? path.join(repoRoot,'reports','notion-parity',runId)); await mkdir(outputDir,{recursive:true});
const profile = await prepareQaProfile({repoRoot,requestedPath:option('profile'),retain}); const auditFile=path.join(profile.profilePath,'qa-database-audit.jsonl'); const exportDir=path.join(profile.profilePath,'exports');
const axePath=require.resolve('axe-core/axe.min.js'); const appVersion=require(path.join(repoRoot,'package.json')).version;
const report={format:'nodus.notion-parity.qa',formatVersion:1,loop:15,runId,startedAt:new Date().toISOString(),finishedAt:null,outcome:'running',profile:{path:profile.profilePath,qaRoot:profile.qaRoot,retained:profile.retained},gates:[],metrics:{},screenshots:[],accessibility:[],console:{errors:[],pageErrors:[]},databaseAudit:[],failure:null};
const gate=(name,status,detail='')=>report.gates.push({name,status,detail}); let app=null; let vault; let fixture; let restoredVault; let webhookServer=null; let webhookRequests=0;
function environment(){const env={...process.env,NODUS_USERDATA:profile.profilePath,NODUS_QA_ROOT:profile.qaRoot,NODUS_QA_DATABASE_AUDIT_LOG:auditFile,NODUS_QA_EXPORT_DIR:exportDir,NODUS_QA_DATABASE_AUTOMATION_DELAY_MS:'900',NODUS_DISABLE_AUTO_UPDATE:'1',NODUS_E2E_UPDATE_STATUS:'not-available',NODUS_E2E_DISABLE_STUDY_BACKGROUND_AI:'1'};delete env.ELECTRON_RUN_AS_NODE;return env;}
async function closeApp(target){if(!target)return;const child=target.process();let timer;const closed=await Promise.race([target.close().then(()=>true,()=>false),new Promise((resolve)=>{timer=setTimeout(()=>resolve(false),5000);})]);clearTimeout(timer);if(!closed&&child.exitCode===null&&!child.killed)child.kill('SIGKILL');}
async function launchApp(){const target=await electron.launch({executablePath:require('electron'),args:[repoRoot],env:environment()});const page=await target.firstWindow();page.setDefaultTimeout(45_000);await page.addInitScript({path:axePath});
  page.on('pageerror',(error)=>report.console.pageErrors.push(String(error?.stack??error)));page.on('console',(message)=>{if(message.type()==='error')report.console.errors.push(message.text());});await page.waitForLoadState('domcontentloaded');await page.waitForFunction(()=>Boolean(document.getElementById('root')?.children.length));
  await page.evaluate(async(version)=>{localStorage.setItem('nodus.lastSeenVersion',version);localStorage.setItem('nodus.mobileTeaserSeen.3.2.4','1');localStorage.setItem('nodus.toolkitBetaGuideSeen.2.4.0','1');localStorage.setItem('nodus.tutorialVideosAnnouncementSeen.2026-07','1');localStorage.setItem('nodus.platformHighlightsSeen.2026-07','1');sessionStorage.setItem('nodus.startupUpdateChecked','1');
    await window.nodus.updateSettings({onboardingComplete:true,basicsTutorialVersion:5,recoverySetupVersion:1,firstVaultVersion:1,tourComplete:true,advancedTourComplete:true,databasesTourComplete:true,mascotEnabled:false,theme:'light',uiLanguage:'es'});},appVersion);await page.reload();await page.getByTestId('app-shell').waitFor();return{app:target,page};}
async function capture(page,label,theme,width,height){await page.setViewportSize({width,height});if(page.url().startsWith('file:')){await page.evaluate((value)=>window.nodus.updateSettings({theme:value}),theme);await page.waitForFunction((value)=>document.documentElement.classList.contains('dark')===(value==='dark'),theme);}const file=path.join(outputDir,`${label}-${theme}-${width}x${height}.png`);await page.screenshot({path:file});const layout=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,document:document.documentElement.scrollWidth,body:document.body.scrollWidth}));assert.ok(layout.document<=width+1&&layout.body<=width+1,`${label} desborda a ${width}px/${theme}`);report.screenshots.push({label,theme,viewport:`${width}x${height}`,path:file,layout});}
async function auditA11y(page,label){if(!await page.evaluate(()=>Boolean(window.axe)))await page.addScriptTag({path:axePath});const violations=await page.evaluate(async()=>(await window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}})).violations.map((item)=>({id:item.id,impact:item.impact,nodes:item.nodes.slice(0,12).map((node)=>node.target)})));report.accessibility.push({label,violations});assert.deepEqual(violations.filter((item)=>item.impact==='critical'||item.impact==='serious'),[]);}
async function openDatabase(page,name){await page.getByRole('button',{name,exact:true}).first().click();await page.getByText('Ada',{exact:true}).first().waitFor();}
async function openWorkspace(page){await page.getByTestId('database-automation-workspace-button').click();await page.getByTestId('database-automation-workspace').waitFor();}
async function publicWindow(url){const pending=app.waitForEvent('window');await app.evaluate(async({BrowserWindow},target)=>{const win=new BrowserWindow({width:390,height:844,show:true,webPreferences:{contextIsolation:true,sandbox:true}});await win.loadURL(target);},url);const page=await pending;page.setDefaultTimeout(30_000);await page.waitForLoadState('domcontentloaded');await page.addInitScript({path:axePath});await page.reload();await page.waitForLoadState('domcontentloaded');return page;}

try{
  for(const script of ['test-database-automations.mjs','test-database-row-query.mjs','test-pages.mjs','test-sync-package.mjs','test-nodus-server-mutations.mjs','test-ipc-contract.mjs','test-i18n-coverage.mjs'])execFileSync(process.execPath,[path.join(repoRoot,'scripts',script)],{cwd:repoRoot,stdio:'inherit'});
  gate('Unidad, SQLite, HTTP, sync, contratos e i18n','passed','Migración v145, idempotencia, ciclos, reintentos, programación, formularios HTTP, sync, IPC y ocho idiomas.');
  if(!skipBuild||!fs.existsSync(path.join(repoRoot,'dist-electron','main.js')))execFileSync('npm',['run','build'],{cwd:repoRoot,stdio:'inherit'});gate('Typecheck y build','passed',skipBuild?'Build de esta revisión reutilizado.':'npm run build completado.');
  webhookServer=createServer((request,response)=>{webhookRequests+=1;request.resume();response.writeHead(webhookRequests===1?503:204);response.end();});await new Promise((resolve)=>webhookServer.listen(0,'127.0.0.1',resolve));const webhookPort=webhookServer.address().port;

  let page;({app,page}=await launchApp());vault=await page.evaluate(async()=>{const created=await window.nodus.createVault({name:'Bucle 15 · automatizaciones',type:'databases'});const switched=await window.nodus.switchVault(created.vault.id);if(!switched.ok)throw new Error(switched.message);await window.nodus.updateSettings({onboardingComplete:true,basicsTutorialVersion:5,recoverySetupVersion:1,firstVaultVersion:1,tourComplete:true,advancedTourComplete:true,databasesTourComplete:true,mascotEnabled:false,theme:'light',uiLanguage:'es'});return created.vault;});
  assert.ok(path.resolve(vault.path).startsWith(path.resolve(profile.profilePath)+path.sep));await page.reload();await page.getByTestId('app-shell').waitFor();
  fixture=await page.evaluate(async()=>{const database=await window.nodus.createDatabase('Solicitudes automatizadas QA','table');const title=await window.nodus.createDatabaseColumn(database.id,'Nombre','title');const status=await window.nodus.createDatabaseColumn(database.id,'Estado','text');const result=await window.nodus.createDatabaseColumn(database.id,'Resultado','rich_text');const button=await window.nodus.createDatabaseColumn(database.id,'Aprobar','button',{buttonLabel:'Aprobar',buttonColor:'#6d28d9'});const row=await window.nodus.createDatabaseRow(database.id);await window.nodus.setDatabaseCell(row.id,title.id,'Ada');return{database,title,status,result,button,row};});
  gate('Vault y fixture por APIs reales','passed','Vault databases aislado con página/fila y propiedades título, texto, rich text y botón.');

  await page.reload();await openDatabase(page,fixture.database.name);await openWorkspace(page);await page.getByTestId('database-automation-loading').waitFor();await capture(page,'automations-loading','light',1024,768);await page.getByTestId('database-automation-loading').waitFor({state:'detached'});await page.getByTestId('database-automation-empty').waitFor();
  await capture(page,'automations-empty','dark',1024,768);await auditA11y(page,'automations-empty-dark');
  await page.getByTestId('automation-name').fill('Completar aprobaciones');await page.getByTestId('automation-trigger').selectOption('property_changed');await page.getByLabel('Propiedad del disparador').selectOption(fixture.status.id);await page.getByLabel('Ejecutar sólo si se cumple una condición').check();
  await page.getByTestId('automation-condition-column').selectOption(fixture.status.id);await page.getByTestId('automation-condition-operator').selectOption('equals');await page.getByTestId('automation-condition-value').fill('aprobado');await page.getByTestId('automation-action').selectOption('set_property');await page.getByTestId('automation-action-column').selectOption(fixture.result.id);await page.getByLabel('Valor o plantilla').fill('Aprobada: {{row.title}}');await page.getByTestId('create-database-automation').click();await page.getByTestId('database-automation-loading').waitFor({state:'detached'});
  await page.getByTestId('database-automation-card').filter({hasText:'Completar aprobaciones'}).waitFor();await capture(page,'automations-populated','light',1440,1000);await capture(page,'automations-populated','dark',1440,1000);await auditA11y(page,'automations-populated');
  const triggered=await page.evaluate(async({rowId,statusId,resultId})=>{await window.nodus.setDatabaseCell(rowId,statusId,'aprobado');return window.nodus.getDatabaseRow(rowId);},{rowId:fixture.row.id,statusId:fixture.status.id,resultId:fixture.result.id});assert.equal(triggered.cells[fixture.result.id],'Aprobada: Ada');

  const apiState=await page.evaluate(async({databaseId,rowId,buttonId,statusId,port})=>{const buttonRule=await window.nodus.createDatabaseAutomationRule(databaseId,{name:'Aprobar con botón',trigger:{type:'button',columnId:buttonId},actions:[{type:'set_property',columnId:statusId,value:{type:'literal',value:'botón'}}]});const webhook=await window.nodus.createDatabaseAutomationRule(databaseId,{name:'Webhook QA',enabled:false,trigger:{type:'row_created'},actions:[{type:'webhook',url:`http://127.0.0.1:${port}/qa`,method:'POST',headers:{'content-type':'application/json'},body:'{"row":"{{row.id}}"}'}],maxAttempts:3,retryDelayMs:10});const first=await window.nodus.runDatabaseAutomationRule(webhook.id,rowId,'qa:webhook:once');const second=await window.nodus.runDatabaseAutomationRule(webhook.id,rowId,'qa:webhook:once');return{buttonRule,webhook,first,second};},{databaseId:fixture.database.id,rowId:fixture.row.id,buttonId:fixture.button.id,statusId:fixture.status.id,port:webhookPort});
  assert.equal(apiState.first.status,'succeeded');assert.equal(apiState.first.attempt,2);assert.equal(apiState.second.id,apiState.first.id);assert.equal(webhookRequests,2);gate('Disparadores, reintentos e idempotencia','passed','Edición real disparó regla condicional; webhook local falló, reintentó y la misma event key no duplicó.');
  await page.getByRole('button',{name:'Cerrar',exact:true}).last().click();const buttonCell=page.locator(`[data-row-id="${fixture.row.id}"][data-column-id="${fixture.button.id}"] button`);await buttonCell.scrollIntoViewIfNeeded();await buttonCell.click();await page.waitForFunction(async({row,status})=>(await window.nodus.getDatabaseRow(row)).cells[status]==='botón',{row:fixture.row.id,status:fixture.status.id});
  await openWorkspace(page);await page.getByTestId('database-automation-loading').waitFor({state:'detached'});await page.getByRole('tab',{name:'Ejecuciones'}).click();await page.getByTestId('database-automation-runs-panel').waitFor();assert.ok(await page.getByRole('cell',{name:'succeeded'}).count()>=2);await capture(page,'automation-runs','light',1024,768);await capture(page,'automation-runs','dark',1024,768);gate('Botón y registro','passed','Botón de celda incrementó su estado, ejecutó regla y el log conserva intentos/acciones/estado.');

  await page.getByRole('tab',{name:'Formularios'}).click();await page.getByTestId('database-form-empty').waitFor();await capture(page,'forms-empty','light',1024,768);await page.getByTestId('form-name').fill('Solicitud pública');await page.getByTestId('form-slug').fill('solicitud-publica');await page.getByLabel('Descripción').fill('Cuéntanos quién eres.');const fields=page.getByRole('group',{name:'Campos visibles'});await fields.getByRole('checkbox').first().check();await fields.getByRole('checkbox').nth(1).check();await page.getByTestId('create-database-form').click();await page.getByTestId('database-automation-loading').waitFor({state:'detached'});await page.getByTestId('database-form-card').filter({hasText:'Solicitud pública'}).waitFor();await capture(page,'forms-populated','dark',1440,1000);await auditA11y(page,'forms-populated');
  const forms=await page.evaluate(async(databaseId)=>{const list=await window.nodus.listDatabaseForms(databaseId);const status=await window.nodus.getDatabaseFormServerStatus();const auth=await window.nodus.createDatabaseForm(databaseId,{name:'Solicitud privada',slug:'solicitud-privada',access:'authenticated',authToken:'qa-token',fields:[{columnId:list[0].fields[0].columnId,label:'Nombre privado',description:null,required:true,width:'full'}]});return{list,status,auth};},fixture.database.id);assert.equal(forms.status.running,true);assert.ok(forms.status.origin);

  let publicPage=await publicWindow(`${forms.status.origin}/forms/solicitud-publica`);await publicPage.setViewportSize({width:390,height:844});await capture(publicPage,'public-form-empty','light',390,844);await auditA11y(publicPage,'public-form-empty');
  await Promise.all([publicPage.waitForNavigation({waitUntil:'domcontentloaded'}),publicPage.evaluate(()=>document.querySelector('form').submit())]);assert.equal(await publicPage.locator('[role="alert"]').count(),1);await capture(publicPage,'public-form-error','light',390,844);
  await publicPage.getByLabel('Nombre').fill('Katherine');await Promise.all([publicPage.waitForNavigation({waitUntil:'domcontentloaded'}),publicPage.getByRole('button',{name:'Enviar respuesta'}).click()]);await publicPage.getByRole('heading',{name:'Respuesta enviada'}).waitFor();await capture(publicPage,'public-form-confirmation','light',390,844);await publicPage.close();
  publicPage=await publicWindow(`${forms.status.origin}/forms/solicitud-publica?theme=dark`);await publicPage.setViewportSize({width:390,height:844});await capture(publicPage,'public-form-empty','dark',390,844);await auditA11y(publicPage,'public-form-dark');await publicPage.close();
  const authPage=await publicWindow(`${forms.status.origin}/forms/solicitud-privada`);await authPage.setViewportSize({width:390,height:844});assert.equal(await authPage.getByLabel('Token de acceso').count(),1);await capture(authPage,'public-form-no-permission','light',390,844);await authPage.getByLabel('Token de acceso').fill('incorrecto');await Promise.all([authPage.waitForNavigation({waitUntil:'domcontentloaded'}),authPage.getByRole('button',{name:'Acceder'}).click()]);await authPage.getByRole('alert').waitFor();await capture(authPage,'public-form-auth-error','light',390,844);await authPage.close();
  const formState=await page.evaluate(async({databaseId,formId})=>({rows:(await window.nodus.queryDatabaseRows({databaseId,limit:500})).rows,submissions:await window.nodus.listDatabaseFormSubmissions(formId,100)}),{databaseId:fixture.database.id,formId:forms.list[0].id});assert.equal(formState.submissions.length,1);assert.ok(formState.rows.some((row)=>row.cells[fixture.title.id]==='Katherine'));gate('Formularios HTTP reales','passed','Publicación UI, GET/POST reales, validación, confirmación, tema oscuro, móvil 390 px, token incorrecto y creación transaccional de fila/página.');

  const saved=await page.evaluate(async(databaseId)=>({exported:await window.nodus.exportDatabase(databaseId,'json'),backup:await window.nodus.backupDatabase(),restoredVault:await window.nodus.createVault({name:'Bucle 15 · restaurado',type:'databases'})}),fixture.database.id);assert.equal(saved.exported.canceled,false);const exported=JSON.parse(fs.readFileSync(saved.exported.path,'utf8'));assert.ok(exported.automations.length>=3);assert.equal(exported.forms.length,2);assert.ok(Object.values(exported.formSubmissions).flat().length>=1);restoredVault=saved.restoredVault.vault;await closeApp(app);app=null;for(const suffix of ['-wal','-shm'])fs.rmSync(`${restoredVault.path}${suffix}`,{force:true});fs.copyFileSync(saved.backup,restoredVault.path);
  ({app,page}=await launchApp());const switched=await page.evaluate((id)=>window.nodus.switchVault(id),restoredVault.id);assert.equal(switched.ok,true);const restored=await page.evaluate(async(databaseId)=>({rules:await window.nodus.listDatabaseAutomationRules(databaseId),runs:await window.nodus.listDatabaseAutomationRuns(databaseId,500),forms:await window.nodus.listDatabaseForms(databaseId)}),fixture.database.id);assert.ok(restored.rules.length>=3);assert.ok(restored.runs.length>=4);assert.equal(restored.forms.length,2);gate('Exportación, backup y restauración','passed','JSON incluye reglas, ejecuciones, formularios y respuestas; backup reabierto conserva el modelo completo.');
  await page.reload();await openDatabase(page,fixture.database.name);await openWorkspace(page);await page.getByTestId('database-automation-loading').waitFor({state:'detached'});await capture(page,'restored-reopened','light',1440,1000);await closeApp(app);app=null;
  const Database=require('better-sqlite3');const sqlite=new Database(restoredVault.path,{readonly:true,fileMustExist:true});Object.assign(report.metrics,{quickCheck:sqlite.pragma('quick_check',{simple:true}),foreignKeyViolations:sqlite.pragma('foreign_key_check').length,rules:sqlite.prepare('SELECT COUNT(*) AS n FROM automation_rules').get().n,runs:sqlite.prepare('SELECT COUNT(*) AS n FROM automation_runs').get().n,notifications:sqlite.prepare('SELECT COUNT(*) AS n FROM automation_notifications').get().n,forms:sqlite.prepare('SELECT COUNT(*) AS n FROM database_forms').get().n,submissions:sqlite.prepare('SELECT COUNT(*) AS n FROM database_form_submissions').get().n});sqlite.close();assert.equal(report.metrics.quickCheck,'ok');assert.equal(report.metrics.foreignKeyViolations,0);
  report.databaseAudit=fs.readFileSync(auditFile,'utf8').trim().split('\n').filter(Boolean).map((line)=>JSON.parse(line));assert.ok(report.databaseAudit.length>0);assert.ok(report.databaseAudit.every((entry)=>path.resolve(entry.path).startsWith(path.resolve(profile.profilePath)+path.sep)));assert.deepEqual(report.console.pageErrors,[]);assert.deepEqual(report.console.errors.filter((message)=>!/favicon|Autofill/i.test(message)),[]);gate('Reapertura, integridad, aislamiento y consola','passed',`${report.databaseAudit.length} aperturas QA; quick_check=ok; FK=0; consola limpia.`);report.outcome='passed';
}catch(error){report.outcome='failed';report.failure=String(error?.stack??error);gate('Resultado','failed',report.failure);throw error;}
finally{await closeApp(app);if(webhookServer)await new Promise((resolve)=>webhookServer.close(resolve));report.finishedAt=new Date().toISOString();const paths=await writeNotionParityReport(outputDir,report);console.log(`Loop 15 report: ${paths.htmlPath}`);await profile.cleanup();}
